app/_assets/stylesheets/base.less
app/_assets/stylesheets/page.less
app/_layouts/docs.html
app/docs/0.1.1beta-2/getting-started/adding-consumers.md
app/docs/0.1.1beta-2/getting-started/adding-your-api.md
app/docs/0.1.1beta-2/getting-started/enabling-plugins.md
app/docs/0.1.1beta-2/getting-started/introduction.md
app/docs/0.1.1beta-2/getting-started/quickstart.md
app/docs/0.1.1beta-2/index.md
app/docs/0.1.1beta-2/internal-api.md

feat(docs): Initial re-write and re-structuring

---

app/_assets/stylesheets/base.less
app/_assets/stylesheets/page.less
app/_assets/stylesheets/variables.less

I wonder why it has so much padding on the sides. Also the font seems smaller/out of sync with our text font. For now I only fixed the padding of `<code>` elements in `<p>` but I actually don't see a reason to have such a big padding everywhere.
Before/After of an endpoint description (same padding for background but nicer font imho...)
Before/After of some text with inline `<code>` (smaller padding on the side because... and the font does not feel smaller like the old one on the left)

[fix] inline <code> padding and font

---

app/_layouts/docs.html
app/docs/0.1.1beta-2/cli.md
app/docs/0.1.1beta-2/configuration.md
app/docs/0.1.1beta-2/getting-started/quickstart.md

Here is the Kong configuration reference. I tried to be as inspired as possible for the intro text but well, it wasn't that efficient...
Also I am not sure about the side menu in `docs.html`.
@Nijikokun Please review, rephrase, reword :)
@thefosk I still don't know what `nginx_plus_status` really does. Could you please update the PR or explain here.
**Depends on Mashape/kong#162 being merged.**

[feature] configuration reference

---

app/_includes/pages/download/docker.md

This PR proposes to switch to the new Dockerhub repos, as already discussed internally:
- [mashape/cassandra](https://registry.hub.docker.com/u/mashape/cassandra/)
- [mashape/kong](https://registry.hub.docker.com/u/mashape/kong/)
Both of them:
- have been updated (docs + Dockerfile): mashape/docker-cassandra#1 and mashape/docker-kong#3
- have a nicer README on Dockerhub that complies with most official repos
mashape/kong is trying to go as an "Official Image", [here](https://github.com/Mashape/docker-kong/issues/4) is the roadmap for that, with what is done and left to do.
Screenshot of the website update:
**Once this is merged, we should remove the old Dockerhub repos [mashape/docker-kong](https://hub.docker.com/u/mashape/docker-kong/) (287 downloads, 3 stars) and …

[docs] update download section to the new Docker images

---

app/plugins/file-log.md

Looks like it was copied from the tcplog page.

Changed the needed `name` parameter in filelog pg

---

app/_data/kong_versions.yml
app/_includes/nav.html
app/_includes/pages/download/centos.md
app/_includes/pages/download/debian.md
app/_includes/pages/download/osx.md
app/_includes/pages/download/other.md
app/_includes/pages/download/ubuntu.md
app/docs/0.2.1/about/how.md
app/docs/0.2.1/about/plugins.md
app/docs/0.2.1/about/scaling.md
app/docs/0.2.1/about/what.md
app/docs/0.2.1/admin-api.md
app/docs/0.2.1/cli.md
app/docs/0.2.1/configuration.md
app/docs/0.2.1/getting-started/adding-consumers.md
app/docs/0.2.1/getting-started/adding-your-api.md
app/docs/0.2.1/getting-started/enabling-plugins.md
app/docs/0.2.1/getting-started/introduction.md
app/docs/0.2.1/getting-started/quickstart.md
app/docs/0.2.1/index.md
app/docs/0.2.1/tutorials/hello-world.md
app/docs/0.2.1/tutorials/installing-plugin.md
app/docs/0.2.1/tutorials/introduction.md

This PR is where the 0.2.1 docs should be updated.
For now, the docs **are still under 0.2.0** so we are able to see what changed in between those 2 versions in term fo documentation. Before merging, one will have to rename the folder to 0.2.1 and retrieve the old 0.2.0 folder. Fixing the redirections from `latest`, etc.
Still missing before releasing:
- A dropdown to switch the version
- An alert saying the docs are outdated #61

[docs] 0.2.1

---

app/docs/0.3.2/getting-started/adding-your-api.md
app/docs/0.3.2/proxy-layer-reference.md

This guide describes the behaviour of the `8000` port and explains all the ways Kong can route requests to the configured upstream services.
It addresses #80, #104, and eventually #87 through a brief note. A "Going to production" guide would be a good addition for the docs, and a good conclusion chapter to that guide.
Please review for feedback about content and language!

docs: New proxy layer reference draft

---

gulpfile.js

Otherwise simply running `gulp` for local work would throw an error
because of the missing environment variables, even if they are only
required when deploying.

fix(gulp) only require cloudflare in its own task

---

app/docs/0.5.x/admin-api.md

a small typo, and an inconsistency.
Updated based on doc inconsistency, without checking the code! So __please check carefully before merging__.
The "Retrieve Plugin" was listed as a POST, was missing a header and included a "Request body" block.

typo fix, and retrieve plugin updated to be a GET request

---

app/docs/0.4.x/proxy.md
app/docs/0.5.x/proxy.md

- Add a note stating which proxying method has precedence, and how they
do not relate in any way.
- Add a note explaining that `strip_request_path` is irrelevant when the
request is being proxied by `request_host`.

docs(proxy) add notes for methods precedence

---

app/docs/0.6.x/plugin-development/admin-api.md

The change fixes compile error for plugin development admin api example.

fix plugin development admin-api compile error

---

app/plugins/request-transformer.md

The example code for this plugin appears to still be referring to the `.form` config attribute. The references to `.form` attribute in the example has been changed to `.body`.

Updated example code to reflect body attribute

---

app/install/heroku.md

This is a rev to simply & update the Heroku install instructions, since we released a Kong 0.7.0 buildpack for Heroku.
@ahmadnassri I opened this a few days ago, but it somehow was closed. Here it is again.
Also, it seems that the Heroku install page is now missing, so maybe merging this will put it back :8ball:

Heroku installation revs for Kong 0.7.0

---

app/docs/0.8.x/plugin-development/custom-entities.md

The module name should not have the ".lua" extension:
```
"kong.plugins.<plugin_name>.daos.lua"
```
should be:
```
"kong.plugins.<plugin_name>.daos"
```

Remove unnecessary ".lua" extension

---

app/community/index.html

Updates https://getkong.org/community/ to include community tools from [KONG Readme](https://github.com/Mashape/kong/blob/master/README.md#community-resources-and-tools) as per issue #141.
Final appearance:

Adds list of community tools to community page

---

app/enterprise/index.html

Removes three lines from Kong Enterprise Subscription column's "Official Production Support" set as outlined in #240.

feat(enterprise): remove production support features

---

app/community/index.html

Include the new Kong Toronto meetup and alphabetise Meetup list on https://getkong.org/community/ as such:

feat(community): add Kong Toronto to Meetup list

---

app/_assets/stylesheets/header.less
app/_includes/footer.html
app/_includes/nav.html
app/enterprise/index.html

Change all request demo links to direct to mashape.com/enterprise
1) Add new mashape.com/enterprise product link in header
2) Update links in getkong.org/enterprise to new enterprise page (request demo, and talk to kong experts)
3) Remove form in getkong.org/enterprise
4) Reduce product links' margin in header
5) Remove link to 'Marketplace' in header
6) Make product links in header uppercase
1) This link has not changed, should it? @sinzone 
2) This link directs to mashape.com/enterprise
3) This form will be removed with this PR

feat(links): change demo links to new enterprise page

---

app/plugins/key-authentication.md

I've added the "-d ''" parameter to the _Create a Customer_ curl example. If this is not done, the endpoint returns a bad response.
I've also added the response data to other endpoint examples for that page since they were on some of the other examples. The more examples, the better IMHO.

Fix "Create a Customer" example. Add response data to other examples.

---

app/plugins/oauth2-authentication.md

I noticed that Kong was returning a refresh_token as part of generating an access_token. This change provides an example on how you can use the refresh_token to generate a new one.

Add example CURL request to refresh access token

---

app/install/vagrant.md

From looking at the kong-vagrant repo it looks like it uses Postgres as a backing store, not Cassandra. 
https://github.com/Mashape/kong-vagrant/blob/master/provision.sh#L15

kong-vagrant uses postgres, not cassandra

---

app/plugins/oauth2-authentication.md

Fix the markdown spaces in the OAuth2 example of use Refresh Token to get a new access token.

Fix OAuth2 example of use Refresh Token to get a new access token

---

app/docs/0.9.x/configuration.md

In the docs for 0.9.x, clarify purpose of cluster_listen_rpc configuration parameter.
* docs/0.9.x/configuration.md: clarify purpose of cluster_listen_rpc
As a new kong user, I was unsure of the purpose of cluster_listen_rpc from reading the 0.9.x docs. After reading through the code, I'd like to submit this to make that clearer for other new users.
This relates to PR https://github.com/Mashape/kong/pull/1860 to update the same explanation in kong.conf.default.
Thank you for your time.

docs(config) 0.9.x: clarify purpose of cluster_listen_rpc

---

app/about/faq.md
app/plugins/basic-authentication.md
app/plugins/key-authentication.md

Mention the ACL plugin in related authentication docs (FAQ, key-authentication, basic-authentication), and clarify that by default the auth plugins grant access to all consumers authenticated with that plugin.
If I'm mistaken there, please let me know.
Thank you for your time.

docs: Mention ACL plugin in related authentication docs: FAQ, key-authentication, basic-authentication

---

app/plugins/acl.md

acl.md: Fix broken link to FAQ entry
Fixes broken link at https://getkong.org/plugins/acl/ at "authentication plugin" into the FAQ:
\- https://getkong.org/about/faq/#how-can-i-add-an-authentication-layer-on-a-microservice/api?
\+ https://getkong.org/about/faq/#how-can-i-add-authentication-to-a-microservice-api

docs(acl) Fix link to faq-authentication

---

app/_data/kong_versions.yml
gulpfile.js

Bring back the missing version dropdown menu.

fix(docs): bring back version dropdown

---

app/plugins/key-authentication.md

underscore is not allowed in a header name, see https://github.com/Mashape/kong/pull/2142

key-auth: note that an underscore is not allowed

---

app/plugins/file-log.md
app/plugins/http-log.md
app/plugins/loggly.md
app/plugins/syslog.md
app/plugins/tcp-log.md
app/plugins/udp-log.md

* Missing latency field in TCP logging example
* Proper upstream_url in several logging examples
* Remove undefined authenticated_entity keys

doc(plugins) sync logging plugin docs

---

app/docs/0.10.x/getting-started/adding-your-api.md

The response value for hosts attribute in the Add Your API section had
an incorrect value of example.org. It is now changed to example.com to
reflect the rest of the document.

change hosts response value

---

app/_includes/head.html
gulpfile.js

Upon further investigation after #353, I felt more could be done for folks loading getkong for the first time.
- greatly reduce load times with async font loading
- unfortunately causes FOUT (flash of unstyled text)

fix(optimisations): load fonts asynchronously

---

gulpfile.js

Fixes BrowserSync refresh issue in https://github.com/Mashape/getkong.org/pull/372#discussion_r109814366
- refresh browser after `html` or `images` tasks finish

fix(gulp): perform browsersync refresh after gulp tasks finish

---

app/plugins/jwt.md

All credential options have default creation values, so there's no
need for the user to define any request body params. However, curl
will not automatically send the Content-Type header as a result of
definine the method as POST via -X; this results in an unsupported
media type error generated from the Admin API.

docs(jwt) Denote necessary Content-Type header for credential creation

---

app/plugins/acl.md
app/plugins/ip-restriction.md

This is a source of confusion, as the current kong model doesn't execute
`self_check` as one would expect when calling `dao:update`.

docs(acl,ip-restriction) clarify positive/negative security models

---

app/install/docker.md

I think it is best practice to use a tag when calling an image. Using latest will save us the step of adding in the number each time. This may also avoid confusion for people who already have an older image of Kong cached.

added tag to the kong docker command

---

app/_includes/footer.html
app/_includes/nav.html

Customer support would like to make user access to the support portal easier by adding links to every marketing site's header and footer.

feat(includes): add support link to nav and footer

---

app/_assets/stylesheets/base.less
app/_includes/nav.html

- hide support link in second header row since it was causing display issues, taking up too much width
- still show support link on small screens

fix(nav): hide support in second header row

---

app/docs/0.10.x/configuration.md

Configuration Reference:
* `server_tokens`
* `latency_tokens`
See: https://github.com/Mashape/kong/pull/2259

docs(conf) add documentation for server_tokens and latency_tokens configuration fields

---

app/plugins/file-log.md
app/plugins/http-log.md
app/plugins/loggly.md
app/plugins/syslog.md
app/plugins/tcp-log.md
app/plugins/udp-log.md

Deals with Kong issue https://github.com/Mashape/kong/pull/2429: logging retries and failure info
and https://github.com/Mashape/kong/pull/2430 for adding a basic auth header with the http log plugin
This documents the additional changes in https://github.com/Mashape/kong/pull/2467.

docs(log) http-log authentication and retries logging

---

app/plugins/runscope.md

- Changed "resopnse" to "response"

Fixed misspelling on the Runscope plugin page

---

app/docs/0.10.x/auth.md
app/docs/0.10.x/proxy.md
app/plugins/http-log.md

This journey started when I noticed that (ironically) the [this website is Open-Source](https://getkong.org/docs/0.10.x/proxy/#conclusion) link is incorrectly marked-down(?). Then I noticed the markdown link right below it was also bogus, which led me to look for other incorrect markdown `grep -Ero '\[[a-z0-9-]{5,}\]' .` ... and here we are.
I tested them locally, and everything looked like I expected, so I hope it works when deployed, also.

Broken self link, and misc markdown fixes

---

app/_assets/stylesheets/pages/plugin.less

Fixes the leading paragraph for the Plugins page by removing the margin removal declaration.

feat(styles): remove bottom margin removal from leading paragraph

---

app/_assets/stylesheets/pages/plugins.less

- Fix flexbox widths on Plugins page for IE11 users.

fix(plugins): change flexbox widths for IE11

---

.travis.yml

Node 4 was giving our builds issues when Yarn ran. Now it ought to work.

fix(travis): upgrade node version

---

app/docs/0.10.x/proxy.md

note: this also has to go to the 0.11 branch

docs(retries) document the retries setting

---

app/docs/0.11.x/configuration.md
app/docs/0.11.x/loadbalancing.md

implements the 'stale ttl' settings and the `search` and `ndots` parameters

docs(dns) update dns settings documentation

---

app/plugins/aws-lambda.md

Follow-up doc improvement for Mashape/kong#2651

docs(aws-lambda) add a reminding note for URI-encoded secrets in payloads

---

app/docs/0.10.x/configuration.md

Instructions on how to setup a website with the same server
name and port as the API.

docs(configuration) serving website and API

---

app/docs/0.11.x/clustering.md

Document the new clustering behavior of Kong 0.11.0. We also mention
what clustering is **not** about, and that a downstream load-balancer is
required for distributing clients traffic across multiple Kong nodes.

docs(clustering) new clustering reference

---

app/_data/kong_versions.yml
app/install/source.md

* Bump OpenResty version to the latest release
* Remove --without-luajit-lua52, matching setup
currently used in Travis.

docs(install) update OpenResty version and flags

---

app/docs/0.11.x/configuration.md

Update documentation to refer to `kong prepare` instead of `kong compile`, matching the feature set for 0.11. I also revised the entire section for customized Nginx setups, based on my experience learning my way around it, hopefully making it clearer.

docs(configuration) update to use `kong prepare`

---

app/docs/0.10.x/plugin-development/file-structure.md
app/docs/0.11.x/plugin-development/file-structure.md
app/docs/0.9.x/plugin-development/file-structure.md

Remove lingering reference to the YAML config file format,
updating it to the custom kong.conf format.
The syntax-highlighting marker in Markdown remains tagged as
`yaml` only to gray out the comment.

docs(plugin-dev) use new config file format

---

app/plugins/cors.md

Two pages have the same origin if the protocol, port (if one is specified), and host are the same for both pages.
ref: https://tools.ietf.org/html/rfc6454#section-4

docs(cors) fix origin value

---

app/install/aws-linux.md
app/install/centos.md
app/install/debian.md
app/install/osx.md
app/install/redhat.md
app/install/ubuntu.md
jekyll.yml

WIP
* Update download locations to point to Bintray (yay);
* Update package names - `kong` is now `kong-community-edition`
* Add Debian 9 and Ubuntu Zesty;
* Remove OSX `.pkg` from the intall page - use Homebrew instead.

feat(install) update download locations

---

app/docs/0.10.x/plugin-development/entities-cache.md
app/docs/0.11.x/plugin-development/entities-cache.md
app/docs/0.8.x/plugin-development/entities-cache.md
app/docs/0.9.x/plugin-development/entities-cache.md

In DAO docs, the method `find_by_keys` doesn't exist since version 0.8.x.

fix(docs): Fix example in entities cache: Use dao find_all method instead of find_by_keys

---

app/plugins/rate-limiting.md
app/plugins/response-rate-limiting.md

There is a parameter introduced with https://github.com/Mashape/kong/commit/209872eb800215144d35d39dff353c4348b07874 called **hide_client_headers** that is missing from the rate-limiting plugin documentation.

docs(rate-limiting) add hide_client_headers reference

---

app/docs/0.11.x/configuration.md

There was a typo in the examples for custom configs, making them unable to copy and paste.

docs(configuration) fix a small typo in the example templates

---

app/docs/0.10.x/admin-api.md
app/docs/0.11.x/admin-api.md

As discussed in issue [#2876](https://github.com/Mashape/kong/issues/2876), the concept of deleting target objects was not quite clear. 
In kong 0.11 the /upstreams/<id>/targets/active API gives a 'method not allowed'. So I removed it from the documentation too.

added explanation on targets 

---

app/plugins/index.html
jekyll.yml

We're reevaluating our strategy for community management.
For now we want to leave github issues for *bugs*, not general
questions or suggestions. At the same time the gitter chat lacks
permanency and the mailing list visibility. While we decide what
to do, we've decided to just hide the button.

docs(plugins) remove the "open an issue" button

---

app/docs/0.11.x/admin-api.md

As a follow-up to:
Kong/kong#3007 (PR)
Kong/kong#2774 (issue)
This commit adds clarifications as to the current behavior of PUT
endpoints on the Admin API. As much as we acknowledge that their
behavior is not compliant with the HTTP specifications, we do wish to
clarify their behavior to avoid confusion as of today, until a different
implementation sees the light of day.

docs(admin) clarify PUT endpoints behavior

---

app/docs/0.10.x/admin-api.md
app/docs/0.11.x/admin-api.md

endpoint
We mistakenly document that `/apis/{api name or id}/plugins/{plugin name
or id}` is a valid endpoint for 0.10 and 0.11 versions.
The correct endpoint is `/apis/{api name or id}/plugins/{plugin id}`.
See
https://github.com/Kong/kong/commit/7b2523f78751c661c7d2d3f612df8046292cbdcf
which was a revert commit for a previous commit introducing such "plugin
by name".

docs(admin) remove 'plugin name or id' from /apis/:api/plugins/:plugin

---

app/docs/0.11.x/admin-api.md
app/docs/0.11.x/getting-started/adding-your-api.md

Make the documented response match the behavior in 0.11.0
ref: [kong/dao/schemas/apis.lua#L206](https://github.com/Kong/kong/blob/f2ee2da36f4d381fdda9ceedf5339dc1d1421d4c/kong/dao/schemas/apis.lua#L206)

docs(admin-api quickstart) set http_if_terminated false by default

---

app/plugins/key-authentication.md

https://github.com/Kong/getkong.org/commit/b8c09d989b08525df433ef3200e529b28c25ffb5 added an extra hyphen which does not render
the [page](https://getkong.org/plugins/key-authentication) correctly.

fix(key-auth) fix page template to render page correctly

---

app/plugins/ldap-authentication.md

Use [the standard LDAP port (TCP/389)](https://wiki.wireshark.org/LDAP) in the example instead of 398.

docs(auth-ldap) use standard LDAP port in example

---

app/_data/docs_nav_0.13.x.yml
app/docs/0.13.x/admin-api.md

This is a continuation of #587 with a few things I noticed were missing on the Admin API docs:
* It says `Service` most of the time it said `API` before (not always).
* Ditto for `api_id` and `service_id`.
* Precedence of routing rules has changed (especially since we now have route_id in addition to service_id
* Some paths have changed. `/api/<id>/plugins` is not available in "service mode" (because plugins can't be nested inside services, only routes can for now). So I have changed it to just `/plugins` (and then you add the `service_id` on the json body)

docs(0.13.x) add Admin API Services and Routes [BIS]

---

app/install/centos.md
app/install/redhat.md

Update RHEL and CentOS install page to include additional info on how to set up the RPM repo.

docs(install) rhel and centos additional info

---

app/docs/0.12.x/admin-api.md
app/docs/0.13.x/admin-api.md

Includes the commit for 0.12.x as well (should it?)

docs(0.13.x/admin-api) add node_id to `/` endpoint

---

app/_layouts/docs.html

This PR adds reversed to the loop of releases in the docs dropdown
Before:
After:

Order of releases in the docs dropdown

---

app/_layouts/plugin.html
app/plugins/key-authentication.md

Since this change modifies the plugins layout, all plugins will have to be adapted to using it (if this is not desired, we can use two different plugin layouts).
There are 4 steps to transform a plugin:
1. Move the "top description" out of the "content" and into a field called `description` in the yml front of the file.
2. Add a section called `params` to the yml front. It needs the following fields:
* `name` (the name of the plugin, i.e. `key-auth`).
* `api_id` true if this plugin can be attached to APIs, false if it doesnt
* `service_id` true if this plugin can be attached to services, false otherwise
* `route_id` ditto for routes
* `config`: This will be a list of n fields, with 4 properties each. Usually
you can get this list by reformatting the "markdown table" at the end of 
the …

docs(plugins) update the plugin layout to generate "Getting Started"

---

app/install/docker.md

Minimum recommended PostgreSQL version is 9.5 since Kong 0.12.x

docs(install) update example to use PSQL 9.5

---

app/docs/enterprise/0.31-x/plugins/request-transformer.md
app/docs/enterprise/0.31-x/setting-up-admin-api-rbac.md

I bumped into the highlighting syntax error in the RBAC docs, then inspired by our seaside conversation on fixing docs, jumped in to fix it. While I was at it, I noticed a stray backslash in `request-transformer-advanced` and fell into a bit of a rabbit hole fixing that plugin's docs. :)

miscelaneous fixes in EE docs

---

app/docs/enterprise/0.31-x/installation/docker.md

Updating Docker EE instructions with the following:
* RBAC instructions include user creation steps and link to larger RBAC article
* Separate Vitals instructions removed (the initial run already enables it)
* Moved FAQ to end of article. Fixed issues with formatting
* Instructions for trial users

Updates to Docker EE instructions

---

CONTRIBUTING.md

* improve phrasing in various places
* respect 80 col limit
* more git commit format scopes and context
* add missing ToC links
* remove git instructions that seem "extraneous" for a simple
documentation website (they apply better to a complex codebase like that
of Kong/kong where those excerpts were taken from)

docs(contributing) various improvements

---

app/install/aws-linux.md
app/install/centos.md
app/install/debian.md
app/install/kubernetes.md
app/install/redhat.md
app/install/ubuntu.md

Minor updates to install instructions to direct trial customers to use their EE packages.
Kubernetes has additional instructions for uploading images.

Trial callouts

---

app/docs/enterprise/0.31-x/plugins/request-transformer.md

config.remove.headers should be config.replace.headers in second location
* ...
Fix #XXX

two times config.remove.headers

---

app/docs/enterprise/0.31-x/developer-portal/authentication.md

Updates Kong Dev Portal authentication documentation to use Routes/Services
rather than then the now deprecated API entity

docs(ee/dev-portal) Update dev portal auth docs for Routes/Services

---

app/docs/0.13.x/admin-api.md

The `name` field is optional for the Services Entity, updated documentation to accurately reflect Services schema.

docs(fix) add optional tag to name field of Services entity

---

app/docs/0.13.x/loadbalancing.md

WIth the update to 0.13, routes and services, some info on ports was lost.

fix(balancing) fix port omission

---

app/_plugins/alias_generator.rb
app/docs/enterprise/0.31-x/developer-portal/customization.md
app/plugins/response-rate-limiting.md

This fixes the following warnings that happen when building getkong.org
from master:
```
Error reading file /Users/kikito/code/work/getkong.org/app/plugins/response-rate-limiting.md: (<unknown>): mapping values are not allowed in this context at line 60 column 76
Deprecation: posts.each should be changed toposts.docs.each.
Called by /Users/kikito/code/work/getkong.org/app/_plugins/alias_generator.rb:42:in `process_posts'.
Liquid Warning: Liquid syntax error (line 220): Unexpected character / in "{{/layout}}" in docs/enterprise/0.31-x/developer-portal/customization.md
Liquid Warning: Liquid syntax error (line 267): Unexpected character = in "{{> spec-dropdown url="/documentation/"}}" in docs/enterprise/0.31-x/developer-portal/customization.md
Liquid Warning: Liquid syntax error (line 274): …
```

chore(*) fix jekyll warnings

---

app/docs/0.13.x/secure-admin-api.md

When following the docs I couldn't get it right the first time, because the docs were saying to post params that version 0.13.0 no longer accept, like "upstream_url" in Services and "uris" in Routes.
I think this way will be more clear to new users understand.
* [Edited docs to bootstrapping Kong API Loopback]

docs(proxy) fix bootstrapped code in Kong API Loopback

---

app/docs/0.13.x/plugin-development/tests.md

* helpers.start_kong needs custom_plugin name in plugin tests
https://github.com/Kong/kong/issues/3403

docs(ce/app-docs) plugin tests should pass plugin name in helpers.start_kong

---

app/_data/docs_nav_ee_0.31-x.yml
app/docs/enterprise/0.31-x/plugins/rate-limiting.md
app/docs/enterprise/0.31-x/plugins/request-transformer.md

Make it more clear that Request Transformer and Rate Limiting are different in EE and CE

docs(fix) disambiguate advanced rate limting plugin

---

app/_assets/stylesheets/page.less
app/_data/docs_nav_ee_0.32-x.yml
app/docs/enterprise/0.32-x/kong-architecture-patterns.md
app/docs/enterprise/0.32-x/plugins/rate-limiting-advanced.md

* fix link to rate limiting (RL) advanced in 0.32 nav
* fix table styling on RL and break word on configs in second column
* add architecture guide doc to 0.32 from 0.31

docs(ee/*) .32 fixes, RL advanced, table styling, architecture doc

---

app/docs/enterprise/0.31-x/developer-portal/authentication.md

The original version of the Dev Portal Authentication document for 0.31
used Routes and Services instead of APIs. They aren't available in 0.31.
Replaced instructions with equivalent instructions for APIs.

fix(dev-portal) use APIs in 0.31 Dev Portal docs

---

app/docs/enterprise/0.32-x/developer-portal/faq.md

Answers a frequently asked question about how to modify code snippets for documentation pages on the Developer Portal.

docs(ee/portal/faq) add code snippet q & a

---

app/docs/enterprise/0.32-x/installation/docker.md

Fix mismatch between tar/tar.gz in install steps. Both are now tar.gz, as that's what we deliver from Bintray.

fix(ee/docker-install) correct minor discrepancy

---

app/docs/enterprise/0.32-x/plugins/rate-limiting-advanced.md

Updating the page of rate-limiting-advanced plugin to use the correct name.

fix(docs) point to rate-limiting-advanced

---

app/plugins/ee-canary-release.md
app/plugins/ee-forward-proxy.md
app/plugins/ee-oauth2-introspection.md
app/plugins/ee-openid-connect.md
app/plugins/ee-proxy-caching.md
app/plugins/ee-rate-limiting.md
app/plugins/ee-request-transformer.md

It was annoying that you couldn't see links to the more explicit and detailed documentation that our amazing team has written. Now they are there.

doc(ee/plugins) add links to detail documentation

---

app/docs/0.14.x/plugin-development/custom-logic.md

Adds following plugins to plugins priority table:
- `pre-function`
- `post-function`
- `azure-functions`
- `prometheus`
- `zipkin`

docs(plugins) updates priorities table to include new plugins for 0.14.0 release

---

app/_layouts/default.html

The notification banner URL was never changed from Mashape and was causing a 404

fix(*) Update URL to notification widget

---

app/_assets/stylesheets/page.less
app/_includes/header.html
app/plugins/azure-functions.md
app/plugins/openwhisk.md
app/plugins/zipkin.md

Adds three `header` parameters:
- `page.header_btn_repo_href` — link to source repo
- `header_btn_repo_text` — text for the button (by default it is `Source Code`)
- `page.header_btn_repo_target ` — the target attribute value (not used, but as an option)
Also adds `page.header_btn_repo_href` to following plugins:
- `azure-functions`
- `openwhisk`
- `zipkin`
The `page.header_btn_repo_href` for `serverless-functions` is added to respective PRs:
- https://github.com/Kong/docs.konghq.com/pull/744
We need to add it to `prometheus` once such PR exists.

docs(repo-link) add repo-link header button

---

app/_layouts/default.html

This PR removes the script calling The old Mashape notification banner. This is no longer used and should not be rendered on this site.

feat(*) Remove unused Mashape Notification Widget

---

app/enterprise/0.31-x/plugins/rbac-api.md
app/enterprise/0.32-x/plugins/rbac-api.md

Fix a number of typos in RBAC API documenation
* Correct mispelled `path` method to `patch`
* Use `/rbac/users/` or `/rbac/roles/` instead of `/rbac/permissions/` where appropriate.
0.33 RBAC API docs were reviewed also and did not appear to exhibit the same issues. They were probably fixed during the general revision for entity-level RBAC.

Fix typos in RBAC API documentation

---

app/enterprise/0.33-x/admin-gui/configuration/authentication.md

Call out the auto-generated RBAC token when creating an admin
As far as I know, this distinction will actually go away in the future, but for now it's fairly easy to auto-generate an RBAC user and ignore their token when creating an admin/try to use the key auth credential as an RBAC token unsuccessfully.

Clarify difference between GUI key and RBAC token

---

app/install/redhat.md

Update RHEL packages/repository URLs. Previously to Kong CE 0.14.0, only
CentOS packages were provided - the RHEL page pointed to CentOS artifacts.
Starting with 0.14.0, we support both CentOS and RHEL. This commit updates
the RHEL install page to point to the correct packages/repository.

docs(ce/install) rhel install

---

app/_assets/stylesheets/base.less
app/enterprise/0.33-x/plugins/rate-limiting-advanced.md

Tables with long parameter names overflowing content container - increase maximum page width to allow for wider tables
*  Increased container max width from 1020px to 1100px
Fix JPK rate-limiting table overflow bug
###Before:
###After

fix(formatting): Reformat Rate-limiting table

---

app/plugins/acl.md

This is in direct relation to my proposed PR here: https://github.com/Kong/kong/pull/3703
New flag hide_groups_header to turn off passing the API providers potentially extraneous growing `X-Consumer-Groups` header list.
*Edited /app/plugins/acl.md to include new flag field and related information about its use.
Syncs with PR https://github.com/Kong/kong/pull/3703

Boolean Flag Proposed In Kong PR Change #3703

---

app/0.14.x/admin-api.md

In v0.14.0, the `/snis` endpoint accepts the nested attribute `certificate.id`. This is incorrectly documented as the flat attribute `certificate_id`.
See specification [here](https://github.com/Kong/kong/blob/0.14.0/spec/02-integration/04-admin_api/06-certificates_routes_spec.lua#L681) with correct attribute.
This PR updates the snis admin API documentation.
* amended `certificate.id` attribute name and description
* amended example response bodies
Found as part of another PR.

docs(ce/admin) fix snis certificate id attribute

---

app/enterprise/0.32-x/developer-portal/configuration/networking.md
app/enterprise/0.33-x/developer-portal/configuration/networking.md

Update broken proxy and gui URLs and refactor to use reference links
* Edited doc `enterprise/0.32-x/developer-portal/configuration/networking`
* Edited doc `enterprise/0.330x/developer-portal/configuration/networking`
Fixes Issue #832 
- [x ] Spellchecked my updates
- [x ] Ready to be merged

fix(links): Update proxy and portal gui URLs

---

app/enterprise/0.33-x/installation/docker.md

Modified Kong EE Docker instructions for version .33. Re
* removed reference to Portal_GUI_URI
* Removed assumption that dev portal should be expected to be blank
* Added text to change localhost to server host or IP if installed on remote system.

Nr 33 docs

---

.travis.yml

cacheing the node_modules directory can make the build faster but also leads to cases where `node_modules` is MIA so lets sacrifice the speed gain for reliability.

fix(travis): don't cache the node_modules directory

---

app/_assets/css/hub.css

Moves plugin publisher down from Z-Index 1000 to 5

fix(cookie-policy): Ensure cookie-policy is on top layer

---

app/0.14.x/admin-api.md
app/0.14.x/plugin-development/custom-logic.md

`"total"` is no longer included in the response from `GET /consumers`. This PR removes it from the example response.
* Edited `app/0.14.x/admin-api.md`
Fixes: https://github.com/Kong/kong/issues/3602
I'm unsure of when `"total`" was removed from `GET /consumers`. I can dig through the code a bit to try and find it, and then update other versions besides `0.14.x` where necessary. If someone happens to know off the top of their head and could save me a little time, that'd be much appreciated!

remove "total" from GET /consumers response

---

app/0.10.x/admin-api.md
app/0.11.x/clustering.md
app/0.12.x/clustering.md
app/0.13.x/admin-api.md
app/0.13.x/clustering.md
app/0.14.x/clustering.md
app/_hub/kong-inc/proxy-cache/0.31-x.md
app/_hub/kong-inc/proxy-cache/0.32-x.md
app/_hub/kong-inc/proxy-cache/index.md
app/enterprise/0.31-x/plugins/http-proxy-caching.md
app/enterprise/0.32-x/plugins/http-proxy-caching.md
app/enterprise/0.33-x/plugins/http-proxy-caching.md
app/enterprise/0.33-x/rbac/admin-api.md
app/plugins/aws-lambda.md

The docs site uses an extension that will automatically make any header into an anchor link. 
If there more than one header with the same text (aka multiple "Endpoint" headers) on the same page, the anchor link will only point to the first one
To avoid this, and improve SEO by not having too many headers, I have changed every page where "Endpoint" and "Response" appear multiple times to bolded words vs headers
**Endpoint** vs

fix(anchor-links): Remove duplicate anchor links

---

app/_assets/css/hub.css
app/_assets/stylesheets/page.less

Adjust margin on header now that summit banner is gone

fix: header styling

---

app/_hub/kong-inc/aws-lambda/index.md
app/plugins/aws-lambda.md

Fix the examples in the end of the doc to use `--data-urlencode` as recommended in the configuration section.

docs(lambda-plugin) fix url-encoded parameters

---

app/_assets/stylesheets/base.less
app/_assets/stylesheets/page.less
app/_layouts/docs.html

Replaces h1 on docs layout, when docs page is not root.
Shows layout's h1 only when page edition is defined.
* H1 cleanup on docs pages, leaving layout's h1 only on root index pages.
cc @moaiandin

fix(layout) H1 cleanup on docs pages

---

app/_hub/zillowgroup/kong-terraform/index.md

Based on discussion with @coopr, clarify that "Kong Terraform module" deployment is really an AWS deployment by way of Terraform.

Revise kong-terraform naming & description to express its "AWS" nature

---

app/enterprise/0.32-x/plugins/openid-connect.md
app/enterprise/0.33-x/plugins/openid-connect.md

Noticed a small typo in the OIDC plugin docs. Redis configuration is referenced in the `session_memcache_socket` section.
* Updated 0.33, 0.32 docs. 
No associated GitHub issue.

Replace redis reference in session_memcache_socket docs for OIDC plugin

---

app/install/kubernetes.md

The current Kong deployment instructions for Kubernetes only has instructions for GKE (Gcloud). We are going to use in a AKS (Azure) environment.
* Edited docs to add aks instructions for kubernetes deployment.

docs(kubernetes/aks): add aks instructions for kubernetes deployment

---

app/_hub/kong-inc/proxy-cache/0.31-x.md
app/_hub/kong-inc/proxy-cache/0.32-x.md
app/_hub/kong-inc/proxy-cache/index.md
app/enterprise/0.31-x/plugins/http-proxy-caching.md
app/enterprise/0.32-x/plugins/http-proxy-caching.md
app/enterprise/0.33-x/plugins/http-proxy-caching.md

This plugin has a parameter for config.cache_control which is a Boolean value for whether or not to respect RFC 7234. I added a link to the RFC in question as some may not know it off hand
made RFC 7234 a link pointing to ]https://tools.ietf.org/html/rfc7234#section-5.2](https://tools.ietf.org/html/rfc7234#section-5.2)
The following docs were updated:
* app/_hub/kong-inc/proxy-cache/0.31-x.md
* app/_hub/kong-inc/proxy-cache/0.32-x.md
* app/_hub/kong-inc/proxy-cache/index.md
* app/enterprise/0.31-x/plugins/http-proxy-caching.md
* app/enterprise/0.32-x/plugins/http-proxy-caching.md
* …

docs(hub) added link to RFC to proxy-cache

---

app/_includes/delighted.html
app/_includes/head.html

This PR adds a customer satisfaction (CSAT) slide-up survey to the docs.KongHQ.com site.
It is intended that this survey be as un-obtrusive as possible - as such, it is currently set to:
* Display only to return visitors 
* Display to any given visitor no more than once every three months (in practice, it may display even less frequently, and it is easy to reduce this frequency if desired)
This survey will be run first as short test, no more than 7 days, though it is desired we run this survey always, to track the results of our efforts to improve Kong's documentation. 
To test this survey on any given page, add `?delighted=test` to the page URL to force the survey widget to display.

feat(*) add Delighted CSAT survey widget

---

app/enterprise/changelog.md

* Added dates in `YYYY/MM/DD` format to each release in the changelog. If there wasn't a corresponding blog post I used `git blame` to get a date.
| release  | date source                                                                     |
|----------|---------------------------------------------------------------------------------|
| `0.30`   | [blog](https://konghq.com/blog/microservice-visibility-resiliency-kong-ee-030/) |
| `0.31`   | `git blame`                                                                     |
| `0.31-1` | `git blame`                                                                     |
| `0.32`   | [blog](https://konghq.com/blog/kong-ee-0-32-analytics-zipkin-tracing/)          |
| `0.33`   | [blog](https://konghq.com/blog/announcing-kong-enterprise-0-33/) …

Add dates to Kong Enterprise changelog

---

app/_hub/optum/kong-response-size-limiting/index.md

Set api_id: false to disable documentation around setting response size limiting to API resources as plugin does not support the deprecated resource.
Thx @coopr for the insight in our discussions over here:
https://github.com/Kong/docs.konghq.com/pull/900

docs(hub) fix up optum response-size-limiting plugin

---

app/install/ubuntu.md

Include link to Bionic package in the CE Ubuntu installation instructions
* [Edited docs to include Bionic package link]
N/A

fix(ce-bionic-link-in-install): Include link to Bionic package in the CE

---

app/enterprise/0.33-x/developer-portal/managing-developers.md

Adds Admin API commands for manipulating Developers alongside their GUI
equivalents.
`POST` exists but isn't covered, as we don't currently have a GUI tool for it. It's also a bit incomplete as it doesn't assign a default status and does not reject requests that don't include a status, allowing the creation of phantom developers that can't be seen in the GUI.

feat(dev-portal) document Admin API for Developers

---

app/0.14.x/getting-started/adding-consumers.md

Fixed formatting on getting-started/adding-consumers page.
Due to bad indents the whole content was formatted as code snippet:
Fixed bad indents.

fixed formatting of getting-started/adding-consumers

---

app/0.14.x/getting-started/configuring-a-service.md

Fixed formatting on getting-started/configuring-a-service page.
Due to bad indents the whole content was formatted as code snippet:
Fixed bad indents.

docs(getting-started-configuring-a-service) fixed formatting

---

app/install/dcos.md

Fix a link to the Kong universe in section 5 of the [Kong DCOS](https://docs.konghq.com/install/dcos/) docs.
* Fix a link in the deployment documentation
N/A

docs(install) fix typo in kong universe link

---

app/_assets/css/hub.css
app/_assets/stylesheets/page.less
app/_assets/stylesheets/pages/extension.less

Move `ol` style from `extension.less` to `page.less` to make numbered list styling consistent.
Fix #914

Make numbered list styling consistent

---

gulpfile.js
package.json

[`gulp-util`](https://www.npmjs.com/package/gulp-util) has been deprecated. Continuing to use this dependency may prevent the use version 4 of Gulp.
See:
- https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
- https://github.com/gulpjs/gulp-util/issues/143

Replace depricated gulp-util

---

CONTRIBUTING.md
app/0.10.x/configuration.md
app/0.11.x/configuration.md
app/0.12.x/configuration.md
app/0.13.x/configuration.md
app/0.13.x/proxy.md
app/0.14.x/configuration.md
app/0.14.x/proxy.md
app/0.4.x/tutorials/hello-world.md
app/0.9.x/configuration.md
app/_hub/kong-inc/rate-limiting-advanced/0.31-x.md
app/_hub/kong-inc/rate-limiting-advanced/0.32-x.md
app/_hub/kong-inc/rate-limiting-advanced/index.md
app/_hub/kong-inc/request-transformer-advanced/0.31-x.md
app/_hub/kong-inc/request-transformer-advanced/0.32-x.md
app/_hub/kong-inc/request-transformer-advanced/index.md
app/_hub/kong-inc/request-transformer/index.md
app/_hub/kong-inc/response-transformer/index.md
app/_hub/optum/kong-response-size-limiting/index.md
app/_hub/optum/kong-service-virtualization/index.md
app/_hub/optum/kong-spec-expose/index.md
app/_hub/optum/kong-splunk-log/index.md
app/_hub/optum/kong-upstream-jwt/index.md
app/enterprise/0.31-x/allowing-multiple-authentication-methods.md
app/enterprise/0.31-x/setting-up-admin-api-rbac.md
app/enterprise/0.32-x/allowing-multiple-authentication-methods.md
app/enterprise/0.32-x/setting-up-admin-api-rbac.md
app/enterprise/0.33-x/allowing-multiple-authentication-methods.md
app/enterprise/0.33-x/rbac/overview.md

Add bash annotations to markdown code snippets throughout the documentation.
I.e., replace
```
$ some_command
with
```bash
$ some_command
where appropriate.
Needed for #969

docs(*) Add bash annotations to markdown code snippets

---

app/_assets/stylesheets/syntax.less

Dont allow user to select generic prompt `$`. This will only work when the markdown language is used e.g. ```bash. Will need to search and find places where bash is not specified in another PR.
Fix #939

style(syntax) dont allow selecting generic prompt symbol

---

app/0.11.x/plugin-development/entities-cache.md
app/0.11.x/plugin-development/file-structure.md
app/0.12.x/plugin-development/entities-cache.md
app/0.12.x/plugin-development/file-structure.md
app/0.13.x/plugin-development/entities-cache.md
app/0.13.x/plugin-development/file-structure.md
app/0.14.x/plugin-development/file-structure.md

Removed in Kong 0.11, the old `hooks.lua` module is irrelevant to
subsequent versions of the plugins development guide. See:
https://github.com/Kong/kong/blob/master/CHANGELOG.md#0110---20170816
We keep the note on how the new process is similar to pre-0.11 in 0.11
and 0.12 versions, but remove this note from the 0.13 version.
The 0.14 version already got rid of mentions of the `hooks.lua` module.

docs(plugins-dev) remove mentions of `hooks.lua`

---

app/_assets/stylesheets/base.less

Added styling to display `<code>` in links better.
**Existing**: https://docs.konghq.com/enterprise/0.33-x/developer-portal/configuration/networking/
**Updated:**
------
**Existing:** https://docs.konghq.com/0.14.x/proxy/
**Updated:**
* Added styles to `<code>` nested in `<a>`
Fix #834

docs: format <code> in <a> to look 'linky'

---

jekyll.yml

Switch to Jekyll's default markdown engine **Kramdown**.
Kramdown fixes the [TOC issue](https://github.com/Kong/docs.konghq.com/pull/920#issuecomment-428736885) present in articles with duplicate headings, such as https://docs.konghq.com/0.14.x/admin-api/.
Additionally, before migrating from existing engine Redcarpet, the following points need to be verified to make sure nothing breaks in the docs:
Found no instances of the above in the docs. Someone more familiar with the contents of the docs could verify.
* Update Jekyll config to use Kramdown instead of Redcarpet
Fix #933, #942

Switch to Kramdown engine

---

app/privacy/index.md
app/terms/index.md

Redirect /terms and /privacy to www.KongHQ.com website pages

docs(terms and privacy) redirect and mark dead

---

app/_hub/kong-inc/hmac-auth/index.md

In the example, the step that adds a route included a name on it. Routes do not support names currently, so this would have produced an error.
Removed `-d "name=hmac-test" ` from the demo as routes do not support names currently
* removed a single line
Fix #XXX

removed name from route in example

---

app/_plugins/versions.rb

Support version numbers without a trailing `x` - like the upcoming `Kong 1.0` release. 
Fix #947

feat(versions) support version numbers without trailing x

---

app/_assets/stylesheets/pages/docs.less
app/_assets/stylesheets/pages/extension.less

Bug 993 is caused by an incorrect font-size for h2 elements. An incorrect assignment meant that h2 and h3 were the same 26px size.
* Change h2 size from 26px to 30px
Fix #993

docs(css) fix h2 size for bug 993

---

app/enterprise/0.34-x/deployment-guide.md

Styles the values of configuration properties listed in the upgrade guide as inline code. They were wrapped in single quotes, rather than back ticks.
* Change quotes to backticks

docs(ee/upgrade) style values of config properties as code

---

app/_assets/stylesheets/page.less
app/_layouts/docs.html

Widens the header title and decreases the drop-down menu's container so that the full width of the header section is occupied. Enterprise does not have search (yet); the space allocated to search remained open and empty in Kong Enterprise doc, which squished the page titles and created too much whitespace.
Before:
After:
* Create classes for Enterprise headers that can easily be deleted if a search bar is added later.
* Only apply classes if the page edition is Enterprise.

docs(ee/header) widen page header

---

app/enterprise/0.34-x/kong-manager/configuration/networking.md
app/enterprise/0.34-x/property-reference.md

Makes users aware of a potential issue if they do not configure SMTP correctly. Currently, the application does not provide an error message; noting it in documentation is the best temporary solution.
* Mention importance of SMTP configuration in Networking section

docs(ee/smtp) warning about not configuring smtp

---

.github/PULL_REQUEST_TEMPLATE.md

Add a note about the automatic Netlify preview to the header comment in the PR template.

repo(pr) add preview info to PR template

---

app/_hub/kong-inc/prometheus/index.md

Corrects docs to show that Prometheus plugin can NOT be added to an API.

docs(hub/kong_inc/prometheus) correct API flag

---

app/enterprise/0.34-x/kong-manager/configuration/authentication.md

Fix typos on https://docs.konghq.com/enterprise/0.34-x/kong-manager/configuration/authentication/, including one that would prevent the initial super admin from being created
* updated commands
* fixed typos

fix(kong-manager) fix typos on authentication page

---

app/_hub/kong-inc/prometheus/index.md

This was a documentation error as the plugin makes sense only at the
service level currently.
ad31ba0888 disabled it for API entity but during the review. @hbagdi
missed to disable it for Route entity as well.

docs(prometheus) disable docs on routes for Prometheus plugin

---

app/0.14.x/proxy.md
app/1.0.x/proxy.md

Update route priority example to clarify difference between regex and prefix path routes. Add a second prefix example to demonstrate prefix path sorting. Added several minor points of clarification to surrounding description.
The existing prefix example included a `regex_priority` on a prefix route although it does serve any function. Though this route was then (correctly) sorted above regex routes, the inclusion of a superfluous priority could confuse users into thinking priority was evaluated lowest to highest, which is incorrect.
This change removes the superfluous priority and adds a second prefix route to demonstrate their sorting (by length).
Only applied to 0.14 and 1.0, as I don't think this is significant enough to backport to earlier docs. 0.15 doesn't have this doc yet for some …

Clarify route priority example

---

app/0.11.x/getting-started/quickstart.md
app/0.12.x/getting-started/quickstart.md
app/0.13.x/getting-started/quickstart.md
app/0.14.x/getting-started/quickstart.md
app/1.0.x/getting-started/quickstart.md
app/enterprise/0.31-x/getting-started/quickstart.md
app/enterprise/0.31-x/installation/amazon-linux.md
app/enterprise/0.32-x/getting-started/quickstart.md
app/enterprise/0.32-x/installation/amazon-linux.md
app/enterprise/0.33-x/admin-gui/configuration/getting-started.md
app/enterprise/0.33-x/getting-started/quickstart.md
app/enterprise/0.33-x/installation/amazon-linux.md
app/enterprise/0.34-x/getting-started/quickstart.md
app/enterprise/0.34-x/installation/amazon-linux.md
app/enterprise/0.34-x/kong-manager/configuration/getting-started.md

Enterprise docs (i.e. Amazon Linux Installation and Kong Manager) mention using `kong.conf.default`. Since users can create their own configuration, it makes more sense to write a generic `path/to/kong.conf`. To better interrelate the docs as part of our new content strategy, the notes now include version-aware links to doc that describes loading configuration files.
* Replace `-c kong.conf.default` with `[-c /path/to/kong.conf]`
* Add a note about loading different config files
* Provide a link to the correct version of loading config
Fix TD-31 (internal)

docs(config) replace kong.conf.default with generic path and a note TD-31

---

app/enterprise/0.34-x/property-reference.md

Corrects `portal_gui_use_subdomains`

docs(typo) correct property name

---

app/_assets/css/hub.css
app/_includes/nav.html

* dynamically assign active class again for /docs/ and /hub/ (the only 2
links that stay within the website)
* do not underline navbar links when browing the /hub/

fix(navbar) fix various navbar header styling issues

---

README.md
app/1.0.x/cli.md
autodoc-cli/data.lua
autodoc-cli/run.lua
gulpfile.js

Adds a new script, `autodoc-cli`, which will:
* Extract the output of the `--help` for every `kong` CLI subcommand
* Generate a new `cli.md` in the path corresponding to the provided KONG_VERSION.
Includes a new gulp task to launch it, `cli-docs`.
Also includes the result of running it for Kong 1.0.x. It already paid for itself by catching two flags that we forgot to document. :)

feat(autodoc) add an auto-generator for cli.md

---

app/_hub/arecabay/ab-microsensor/index.md

docs(ce/ee) moving ArecaBay plugin into analytics-monitoring only

---

app/install/docker.md

Change command for database migration
* Edited Docker Installation doc. Replaced `up` with `bootstrap`.
If use command `up` then error is thrown `Error: cannot run migrations: database needs bootstrapping; run 'kong migrations bootstrap'`

change `up` command to `bootstrap` in docker installation guide

---

app/enterprise/0.34-x/admin-api-audit-log.md
app/enterprise/0.34-x/property-reference.md

Provides a complete property reference for Kong Enterprise; most sections outside of Kong Manager and Dev Portal were missing. Any shared properties with Core have links to the relevant doc.
* Add either a description or a link to all missing properties in Enterprise
* Replace sub-section in Audit Log with a link to the main property reference
* Fix any noticeable formatting issues
Fix TD-39 (internal)
_Needed in order to merge_:

docs(ee/config) complete property reference for enterprise TD-39

---

app/enterprise/0.34-x/developer-portal/configuration/authentication.md
app/enterprise/0.34-x/developer-portal/configuration/workspaces.md
app/enterprise/0.34-x/developer-portal/developers/developer-access.md
app/enterprise/0.34-x/developer-portal/introduction.md

Fix the link to Developer Statuses and various plugin pages.
* Fix links to Developer Status by using new path introduced in 0.34
* Fix links to various pages by removing `.org` in URL
* Fix links that redirected by specifying the path
Fix (internal) TD-2 and related cases

docs(ee/dev-portal) fix links to dev status and plugins TD-2

---

app/_assets/stylesheets/pages/install-method.less

I cannot see why the margin for this element was negative, but inverting it fixes the overlap in #1020
* Fix overlap of subscribe element
Fix #1020

style(install) invert margin for email sign-up

---

app/_assets/stylesheets/base.less

Browsers will respect the `name` attribute as another way to link to sections of the page. I've limited it to just `a` tags but I'm not sure if other pages use different tags. If others are used, then they'll have to be added too.
* Have anchor tags with `name` attributes respect the same behavior as headings with `id`s
Fix #1039

fix(*) anchors with name attrs now properly offset

---

app/enterprise/0.34-x/developer-portal/configuration/workspaces.md

Fixed broken image link in Developer portal page
The developer portal overview was supposed to be shown, but seems like the doc generator is not parsing as expected. The whitespace between the text and hyperlinks are causing the issue.
```
```
* Fixed broken image link in [developer-portal/configuration/workspaces.md]
Fix N/A

docs(ee/dev-portal) broken image link

---

app/_assets/javascripts/app.js
app/_assets/stylesheets/page.less
app/_assets/stylesheets/variables.less

**Before**
**After**
The amount of spacing that currently exists when you click on headers pushes the heading a bit too far down because the old navbar was taller.
* Pixel height in styles changed
None that I'm aware of

style(*) shrink header spacing after small navbar

---

app/enterprise/0.34-x/getting-started/enabling-plugins.md

Update video in Getting Started: Enabling Plugins from using Key Auth in 0.33 to using Basic Auth in 0.34. The main reasons are to (1) show the updated UI and (2) match the new instructions for 0.34.
Preview here: https://5c5b7dd8855af400084e079a--kongdocs.netlify.com/enterprise/0.34-x/getting-started/enabling-plugins/

docs(ee/34/plugins) update video to basic auth

---

app/1.0.x/index.md
app/1.0.x/upgrading.md

* Updates `kong migrations` CLI options
* Adds a *upgrading.md* section, with just the `1.0` guide, pointing to the full in-repo guide for older versions

Docs CLI migrations + upgrade path

---

app/1.0.x/proxy.md

Replace the broken RFC 3986 link with a working one.
Fix #1120

docs(ce/proxy) replace rfc 3986 link

---

app/_assets/stylesheets/pages/extension.less

Lowers the z-index of the version picker on hub plugin pages
_Before_
_After_
* extenstion.less

Fix z-index of hub version dropdown

---

app/1.0.x/plugin-development/tests.md

The documentation for spec/kong_tests.conf had a broken link to the key-auth plugin
* Fixed link to the key-auth plugin
Fix #1166

docs(ce/plugin-development) fix broken link

---

app/_hub/kong-inc/key-auth/0.2-x.md
app/_hub/kong-inc/key-auth/index.md

Clarify allowed key names for key-auth
* Update key-auth documentation to indicate that there are additional limits on allowed key names if passing the key in a header.

hub(key-auth) clarify allowed key characters

---

app/1.0.x/plugin-development/access-the-datastore.md
app/1.0.x/plugin-development/admin-api.md
app/1.0.x/plugin-development/entities-cache.md

The Plugin Development Guide had some references to deprecated modules:
* The `kong.dao` module has now been superseeded by `kong.db` for all entities
* The `helpers` parameter on admin apis
is now replaced by the PDK
* The crud_helpers module is now replaced
by kong.api.endpoints

docs(1.0) remove old modules from plugin dev guide

---

app/_assets/stylesheets/footer.less

hide overflow on footer newsletter signup to eliminate unneccesary vertical scrollbar due to iframe overflow
* update footer.less to hide newsletter ul column vertical overflow
Fix #1173
- [x ] [Commit message & atomicity](https://github.com/Kong/docs.konghq.com/blob/master/CONTRIBUTING.md#commit-atomicity) checked
- [x ] Documentation
- [x ] Spellchecked my updates
- [x ] Ready to be merged

* update overflow on footer form

---

app/_assets/javascripts/app.js
app/_assets/stylesheets/header.less
app/_assets/stylesheets/page.less
app/_layouts/docs.html
app/_layouts/extension.html

Collapses sidebar on small devices instead of showing it above the main content. Sorry for giant screenshots!
_Closed_
_Open_
* Adds class to sidebar
* Adds small JS to toggle open class
- [ x ] [Commit message & atomicity](https://github.com/Kong/docs.konghq.com/blob/master/CONTRIBUTING.md#commit-atomicity) checked
- [ x ] Ready to be merged

feat(Sidebar) Collapse sidebar on small screens

---

.github/main.workflow
README.md

Leverage Github Actions to deploy the site automatically when master is updated
Following this tutorial: https://github.com/BryanSchuetz/jekyll-deploy-gh-pages
* Adds main.workflow

feat(config) - auto-deploy workflow

---

STYLEGUIDE.md

Fixes an issue with the out-of-date, confused Quip doc. Admin should be used for the Kong entity, admin and super admin for the particular Role. The titles of each entry should match the expected use, e.g., 
**Thing One**
Use proper case
**thing two**
Use lowercase
* Made "super admin" section consistent
* Update "Admin, admin" section with clarification

docs(style) clarify admin, super admin

---

app/1.1.x/db-less-and-declarative-config.md

Some plugins were missing due to an oversight. Thanks @hbagdi for the heads up!

docs(1.1) add missing plugins in Declarative Config guide

---

app/0.14.x/admin-api.md

While working with pagination in the 0.14.1 version of kong I discovered an inconsistency in behavior between various endpoints that is not reflected by the documentation.
```
r = requests.get(f'{kong_url}/services')
>>> r.json()['next']
'/services?offset=WyJmNmExOWYzNi1hOGYzLTQzYmMtOWNlMy0wZjcyMjk2ZTU0MWUiXQ'
>>> r = requests.get(f'{kong_url}/plugins')
>>> r.json()['next']
'<kong_url_ommitted>/plugins?offset=Mg%3D%3D&size=100'
```
The `/services` endpoint does not include the domain when it returns the url to the next page, but the `/plugins` endpoint does. Presumably this is fixed in later versions of kong, but the documentation for 0.14 should reflect it. I do not know how far back this problem exists. Please let me know if I should update other older documentation.
* Edited docs to …

docs(admin) Update service pagination info

---

app/_hub/kong-inc/serverless-functions/index.md

The backslash is only required when directly submitting code, not when using the file upload in curl.

fix(hub): serverless-fn remove backslash in code

---

app/_includes/nav.html

Show "Install Kong" CTA on all hub pages
* update template conditionals to display install cta on hub & plugin pages
- [N/A] Documentation

conditionally displaay install button on main nav

---

app/1.1.x/admin-api.md
app/1.1.x/db-less-admin-api.md
app/_data/docs_nav_1.1.x.yml
autodoc-admin-api/data.lua
autodoc-admin-api/run.lua

Adds a new page for Admin API in DB-less Mode (which includes `/config`, and
where all entity endpoints only contain GET operations except for the healthcheck
setters).
The sidebar still points to the regular Admin API, but I added a pointer to DB-less
Mode at the top of the regular Admin API docs and vice-versa. This is a stopgap
measure before we do a more thorough reorganization of the Admin API reference docs.
Includes title capitalization fixes matching the docs styleguide (which I plan to later refactor to the other `autodoc` scripts).

docs(1.1.x/admin-api) add DB-less Admin API docs

---

README.md
templates/how-to.md

Corrected Some Grammer Mistake now docs look much better to read
* [Edited docs too...]
* ...
Fix #XXX

Corrected Grammer Mistakes

---

package.json

Downgrades bootstrap back down to 3.3.5 as our styles do not support bootstrap 4

downgrade bootstrap

---

app/enterprise/0.35-x/deployment/migrations.md

Add upgrade instructions for users going from Kong Core to Kong Enterprise 0.35.
The 0.35 upgrade viability checker relies on either the presence of all 0.34 migrations or the absence of the `schema_migrations` table, which 1.0 removes. Because of this, 0.14 and 0.15 fail 0.35's upgrade check. These versions cannot be upgraded to 0.34, as 0.34 is based on Core 0.13. As such, the only viable upgrade path is to first upgrade them to 1.0.

docs(35/migrations) cover upgrade paths from Core

---

app/enterprise/0.35-x/deployment/migrations.md

Currently, the Upgrade Guide suggests an immediate step from 0.34 to 0.35. Going to 0.34.1 is necessary in between, so this PR adds the missing step.

docs(35/migrations) mention 0.34.1 as intermediary step

---

app/enterprise/0.35-x/getting-started/start-kong.md

In the Getting Started guide, once a user has started Kong, they have a list of default ports used with Kong Enterprise. 
Each port listing will also link to the related configuration property in case the organization wants to know where to change the ports used or to deactivate unused ones. 
For this PR:

docs(35/start) provide default ports for enterprise

---

app/enterprise/0.35-x/deployment/migrations.md

This change adds more context to the warning for blue/green deploys in .35.
- [] Documentation 
- [] Tagged "Team Docs" as reviewers [NOT CURRENTLY AN OPTION]

chore(migrations) improve migration doc accuracy

---

app/_hub/kong-inc/rate-limiting-advanced/index.md

Note that the Redis timeout in the plugin configuration is measured in milliseconds.

docs(rate-limiting-advanced) note unit for timeout

---

app/_hub/kong-inc/ldap-auth-advanced/index.md

Fixes issue where all declared content in YAML front matter was broken due to the outside quotes. Long term solution would be to flag a failure in Travis CI. Incidentally, the error message stated an incorrect line number--said line 116, whereas error was on line 118.

hotfix(hub/ldap-adv) fix yaml formatting

---

app/1.1.x/db-less-and-declarative-config.md

Fixes a small spelling error / typo
* Spelling error on the db-less config docs
None
I have done no checks on the checklist.

Fix configuration typo in db-less docs

---

app/1.0.x/admin-api.md
autodoc-admin-api/run.lua

This is a backport of #1194 for the 1.0.x docs.
It modifies the auto-generation template so that several h4-level headers are replaced by plain text. This way they don't clutter the auto-generated TOC.

Docs(1.0.x) h4s from api docs

---

autodoc-admin-api/run.lua

This is needed for autodoc-admin-api to generate correctly with current
`master` and `next` of kong/kong.

fix(autodoc-admin-api) add newly needed boilerplate

---

app/_hub/kong-inc/file-log/index.md
app/_hub/kong-inc/http-log/index.md
app/_hub/kong-inc/syslog/index.md
app/_hub/kong-inc/tcp-log/index.md
app/_hub/kong-inc/udp-log/index.md

This is a continuation of #1251.
On that PR the TLS field was added to the docs of *older versions of the
plugins* (`0.1-x`, etc) but not to the *current* ones (`index.md`). This PR fixes that problem.

docs(plugins) add new tls field in *current* versions of the plugins

---

app/enterprise/0.35-x/property-reference.md

Original: admin)gui_auth_header
Fixed: admin_gui_auth_header
Fix a typo of configuration directive.
* Original: admin)gui_auth_header
* Fixed: admin_gui_auth_header
* [app/enterprise/0.35-x/property-reference.md]: fix typo

docs(0.35-x/conf-ref) fix a typo of configuration directive

---

app/enterprise/0.35-x/admin-api/audit-log.md
app/enterprise/0.35-x/admin-api/vitals/vitals-prometheus-strategy.md
app/enterprise/0.35-x/plugins/statsd.rules.yaml

- updates broken links in the Admin API section
- formats docs to adhere to 80 character line limit
- adds missing `statsd` yaml file

Admin API broken links

---

autodoc-admin-api/data.lua

`https_redirect_status_code` is a new property on route introduced in
Kong 1.2.0.

docs(route) add description for https_redirect_status_code

---

app/_hub/kong-inc/proxy-cache/index.md

Adds `memory` as the example value for `config.strategy` in the **Proxy Cache** plugin
Fix #1344

fix(docs): Proxy Cache examples

---

app/1.0.x/admin-api.md
app/enterprise/0.35-x/admin-api/rbac/reference.md

GET `/rbac/users` and `/consumers` lists all respective entities except those associated with Admin accounts. This leads to confusion when users can't find the entities they'd expect.
* Added a note under List Users (for RBAC in Enterprise)
* Added a note under List Consumers (Core entities that are tied to Enterprise Admins)
@kikito , please note that (1) there is a requested change outside of Enterprise, and (2) the Kong Enterprise version is hardcoded in the link since there is not a dynamic way to connect Kong and Kong Enterprise versions.

docs(*) mention rbac/users and consumers for admins are not listed

---

app/_hub/kong-inc/proxy-cache/index.md

Updates incorrect example endpoint in **Proxy Cache** documentation

fix(hub): Fix typo in proxy-cache request

---

app/1.0.x/admin-api.md
app/1.1.x/admin-api.md
app/_hub/kong-inc/acl/index.md
app/_hub/kong-inc/bot-detection/index.md
app/_hub/kong-inc/cors/index.md
app/_hub/kong-inc/ip-restriction/index.md
app/_hub/kong-inc/key-auth/index.md
app/_hub/kong-inc/oauth2/index.md
app/_hub/kong-inc/request-transformer/index.md
app/_layouts/extension.html

Fixes array notation in documentation examples, also removes the `comma separated` advice.
See:
- https://github.com/Kong/kong/issues/4445
- https://discuss.konghq.com/t/cors-plugin-issue-with-v1-0-3/2838
- https://github.com/Kong/docs.konghq.com/issues/1197

docs(*) fix array notation in examples (>= 1.0.0)

---

app/enterprise/0.35-x/kong-manager/authentication/super-admin.md

The previous note suggested that setting a password would also create an RBAC token with the same value. (That is only true for the Super Admin created at the time of migration using the env var, whereas this guide pertains to creating SAs after installation.) 0.35 is the only version affected.

docs(35/km/auth) stop implying password = token

---

app/enterprise/0.35-x/kong-manager/administration/workspaces/workspaces.md

changes "mananger" to "manger" in url
[RBAC in Kong Manager](/enterprise/{{page.kong_version}}/kong-mananger/administration/rbac/rbac). 	
to
[RBAC in Kong Manager](/enterprise/{{page.kong_version}}/kong-manager/administration/rbac/rbac). 
Fixes dead link

fix(docs): fix url typo

---

app/_assets/stylesheets/pages/install-method.less
app/_layouts/install.html
app/install/aws-cloudformation.md
app/install/aws-linux.md
app/install/aws-marketplace.md
app/install/centos.md
app/install/dcos.md
app/install/debian.md
app/install/google-cloud.md
app/install/kubernetes.md
app/install/macos.md
app/install/redhat.md
app/install/ubuntu.md
app/install/vagrant.md

Allow core installation docs to use the Table of Contents extension 
* Adds call to toc.html in install page layout, moves it out of main content section to ensure it displays correctly
* Updates all installation pages to use the new TOC
Fix #917

fix(install): Fix generated TOC styling

---

app/_assets/javascripts/app.js
app/_layouts/docs.html

Fixes smooth scrolling when clicking on a Table of Contents link on documentation pages
* Adds `anchor_class="scroll-to"` to toc call in doc.html (documentation layout) so that the smooth scrolling JS works (this was apparently broken)
* Adds a window width check to smooth-scrolling to reduce offset for smaller screens - this fixes the anchor-links cutting off the heading on screens smaller than 1000px wide

fix(js): Fix smooth scrolling

---

app/1.2.x/admin-api.md

Forward ports changed to to `1.2.x` which were merged here:
https://github.com/Kong/docs.konghq.com/pull/1225

docs(*) forward port array notation in admin api docs

---

app/install/kubernetes.md

- mention the existence of the Make tasks in kong-dist-kubernetes
- change k8s cluster to a prerequisite don't document how to provision one
- similarly let's not document how to use minikube
- demonstrate how to access the admin-api / proxy and continue the getting started tutorial at adding a configuring a service
To do but out of scope is we need to duplicate all relevant admin api examples for declarative. Right now it's not clear where best to direct folks after they finish setting up declarative / db-less Kong
To do in the a PR to follow this one is continue the k8s w\ datastore examples to include setting up https://github.com/Kong/kubernetes-sidecar-injector and running bookinfo.yaml

doc(k8s) re-do and update the Kong w\ k8s installation docs

---

app/_layouts/extension.html

Fixes declarative configuration array notation examples, e.g.:
```yaml
plugins:
- name: cors
config: 
methods: GETPOST
```
to:
```yaml
plugins:
- name: cors
config: 
methods:
- GET
- POST
```
See the problem here:
https://docs.konghq.com/hub/kong-inc/cors/

docs(*) fix declarative configuration array notation

---

app/install/docker.md

The docker installation command running a Kong container, more specifically DB-less, was missing a symbol that meant you could not just copy and paste the command into a bash prompt to execute.

adding missing bash symbol to docker installation

---

app/_hub/kong-inc/proxy-cache/0.31-x.md
app/_hub/kong-inc/proxy-cache/0.32-x.md
app/_hub/kong-inc/proxy-cache/0.33-x.md
app/_hub/kong-inc/proxy-cache/0.34-x.md
app/_hub/kong-inc/proxy-cache/index.md

Clarify `proxy-cache` plugin content-type matching.

docs(hub/proxy-cache) clarify content-type matching

---

app/enterprise/0.35-x/kong-manager/authentication/ldap.md

Fixes internal issue TD-311
LDAP example in Kong Manager authentication doc shows the field `consumer_by` as a string vs an array - this will result in an error if one tries to implement it.

fix(doc): Edit consumer_by to be array

---

app/enterprise/0.35-x/kong-manager/networking/configuration.md
app/enterprise/0.35-x/kong-manager/security.md

* Adds a new section to Networking about configuring TLS and the problem posed by self-signed certs with localhost
* Change the title of the Authentication section to clearly emphasize that it is accomplished through configuring Kong a certain way, and not through enabling plugins globally
* Add a table of contents to the Securing Kong Manager page
TODO:
* Turn TLS section into a page
* Add a link to the new TLS page on the Networking page
* Provide an introduction to the Networking section
* Move Securing KM to a higher position, pre-networking
* Divide Securing KM into subsections: Secure Networking and Identity and Access Management

docs(35/km/security) add TLS and localhost explanations and references

---

app/1.2.x/admin-api.md
app/1.2.x/proxy.md

This PR adds sni wildcard reference to `Configuring SSL` as well as documenting the matching priority of snis

docs(snis) add sni wildcard reference to `Configuring SSL`

---

app/enterprise/0.35-x/property-reference.md

Kong 0.35 changes the db_cache_ttl value to 0

---

.gitignore
app/_assets/css/hub.css
app/_assets/javascripts/app.js
app/_assets/stylesheets/page.less
app/_assets/stylesheets/pages/extension.less
app/_layouts/extension.html

Changes table layout on plugin / extension pages so it no longer overflows main body
Fixes Issue #835 
- In `extensions.html`, moves `default` column in Plugin data tables to be nested under the property name, this helps prevent overflowing content
- Fixes overlapping styles causing some table text sizes to exceed 14px 
- Adds zebra-stripping for readability
- Collapses tables on mobile for readability
- Hides table headers on mobile
- JQuery adds the `data-label` attribute to table elements
- CSS shows `data-label` attr on mobile to make mobile tables more readable.
- Forces all text-alignment to `left` only on mobile -- allows authors to still use Markdown content alignment on Desktop
Before:
After:

fix(styling): Fix table styling

---

app/_hub/kong-inc/serverless-functions/index.md

Code is not required to be wrapped in a function nor commas are
required to be escaped.
@Kong/team-core , could you review the upvalues part of the doc? is it still relevant? Feel free to add on this PR.

docs(serverless) update example code

---

app/_hub/kong-inc/jwt/index.md

Original: 403
Fixed: 401
Per FT-471 commented by @bungle , it appears that the status code of invalid verified claims should be 401 instead of 403.
* Original: 403
* Fixed: 401
* [app/_hub/kong-inc/jwt/index.md]: fix status code

docs(plugins) Status code correction

---

app/0.14.x/pdk/kong.request.md
app/1.0.x/pdk/kong.request.md
app/1.1.x/pdk/kong.request.md
app/1.2.x/pdk/kong.request.md

Since this has been the case since the first version in the PDK, this change updates thes fields manually (they are usually auto-generated, but the tags for the versions are fixed and can't be changed in order to auto-generate them correctly).

docs(pdk) kong.request.get_http_version() returns a number, not a string

---

app/enterprise/0.35-x/admin-api/admins/index.md

KM currently links to `/admin-api/admins`. There will eventually be an explanatory doc for this path. For now, it should redirect to the API reference since otherwise it 404s.

docs(admin-api) redirect index to ref

---

app/1.3.x/plugin-development/custom-entities.md
app/1.3.x/plugin-development/entities-cache.md

Describes following properties:
- `generate_admin_api`
- `admin_api_name`
- `admin_api_nested_name`

docs(*) add description to admin api related dao schema parameters

---

app/1.1.x/upgrading.md
app/1.2.x/upgrading.md

This PR changes the Upgrade Guide for 1.1.x and 1.2.x, which were mistakenly written for 1.0.x.
The changes consisted on replacing the 1.0.x text with instructions from https://github.com/Kong/kong/blob/next/UPGRADE.md .
Each individual commit has more details.

docs(1.1.x, 1.2.x) upgrading.md guide had 1.0.x instructions

---

app/_hub/kong-inc/canary/0.31-x.md
app/_hub/kong-inc/canary/0.32-x.md
app/_hub/kong-inc/canary/0.33-x.md
app/_hub/kong-inc/canary/0.34-x.md
app/_hub/kong-inc/canary/0.35-x.md
app/_hub/kong-inc/canary/index.md

- Removes erroneous configuration preventing several plugin parameters from displaying in all versions of plugin docs
- Adds new parameters applicable to 0.36-x 
- Adds missing usage details about white and black listing
- Adds and rewords missing information from plugin README

Update Canary Release Plugin docs

---

app/1.3.x/upgrading.md

Most changes from this commit are a straight replacement of the
text using https://github.com/Kong/kong/blob/next/UPGRADE.md .
There are two notable exceptions:
* Header levels have been changed
* The `Upgrade Path for Patch Releases` section does not exist in
Kong's `UPGRADE.md` file.
Related: #1436

docs(1.3.x) add upgrading.md instructions for 1.3.x

---

app/_hub/kong-inc/key-auth/index.md

because it no longer applies
See: https://github.com/Kong/kong/pull/4896

docs(key-auth) remove the underscore in key name restriction from doc

---

.travis.yml

Fixes issue where, as unused CSS is removed, the build hits a memory limit causing a failure.
Note the following:
- Netlify was fixed separately by adding `NODE_OPTIONS=--max_old_space_size=8192` to  https://app.netlify.com/sites/kongdocs/settings/deploys#environment
- With local development, writers still need to manually use `export NODE_OPTIONS=--max_old_space_size=8192`; ideally we can include this out of the box, but this PR only addresses Travis CI.

fix(travis-ci) expand memory limit for css removal

---

app/enterprise/0.35-x/index.md
app/enterprise/0.36-x/index.md

0.35 and 0.36 are the only versions affected.

docs(enterprise/*) fix typo on deployment page

---

app/install/aws-linux.md
app/install/centos.md
app/install/debian.md
app/install/redhat.md
app/install/ubuntu.md

When https://github.com/Kong/kong/pull/4868 is merged the next subsequent release will be tagged by architecture (ideally Kong@1.3.0)

feat(install) prepare for multi-arch releases

---

app/enterprise/0.35-x/kong-manager/reset-password.md
app/enterprise/0.36-x/kong-manager/reset-password.md

Fix Kong Manager password/token reset instructions to point to appropriate anchors within the page, rather than non-existent off-page links.

fix(passwords) use anchor links for page sections

---

app/1.2.x/proxy.md
app/1.3.x/proxy.md
app/enterprise/0.35-x/proxy.md
app/enterprise/0.36-x/proxy.md

(TD-373) Fix proxy router rule evaluation order documentation for newer versions. The router has evaluated regex path rules before prefix path rules for some time (if not always), and documentation has always stated the reverse. This applies to older versions also, but has not been beyond the most recent two versions for the sake of time.
Additionally add some additional example information for route shadowing, correct a broken anchor link, and make some minor phrasing changes.

Align route evaluation order in proxy documenation with actual behavior.

---

app/enterprise/changelog.md

Adds Changelog notes for all changes/features that 0.36 inherited from 1.1.0-1.2.1.
The main purpose of isolating Enterprise 0.36:
- some features in 1.2.1 such as DB-less are absent in 0.36
- since 0.35 is based on 1.0.3, there are many Core versions condensed into one upgrade
- reduces context-switching/confusion for users jumping to Core READMEs from the Changelog page

docs(ke/changelog) 

---

gulpfile.js
package.json

Removes `purifycss` as it is an unmaintained project causing memory leak issues in the repo. 
Looking into alternative packages, but lets remove this for now.

remove purifycss

---

gulpfile.js
jekyll-dev.yml

Creates dev only gulp tasks and config files to speed up local build and watch times

feat(jekyll): Speed up local builds

---

app/1.0.x/configuration.md
app/1.1.x/configuration.md
app/1.2.x/configuration.md
app/1.3.x/configuration.md
app/enterprise/0.34-x/property-reference.md
app/enterprise/0.35-x/property-reference.md
app/enterprise/0.36-x/property-reference.md

Add warning boxes instructing users to escape "#" characters in configuration. Though technically applicable everywhere, this typically comes up in the context of database and SMTP passwords.
See also: https://github.com/Kong/kong/commit/a185dd954c839e8830759efec2d769856e8842e3

docs(config) add warnings about character escaping

---

app/0.14.x/logging.md
app/1.0.x/logging.md
app/1.1.x/logging.md
app/1.2.x/logging.md
app/1.3.x/logging.md

This PR fix following problems in Logging Reference documentation:
- remove duplicated "Removing Certain Elements From Your Kong Logs"
- fix url to "custom NGINX template"

docs(ce/logging) fixes in Logging Reference doc

---

app/1.0.x/configuration.md
app/1.1.x/configuration.md
app/1.2.x/configuration.md
app/1.3.x/configuration.md
app/enterprise/0.34-x/property-reference.md
app/enterprise/0.35-x/property-reference.md
app/enterprise/0.36-x/property-reference.md

Aron was too quick for me on https://github.com/Kong/docs.konghq.com/pull/1499 and I hadn't checked formatting before it was merged.
Turns out you can't use Markdown inside warning boxes. Applying the appropriate code class manually instead.

fix(config) fix warning box formatting

---

app/enterprise/changelog.md

In order to avoid confusion, describe the Gateway version Enterprise is based on and mention the missing features.
**Note:** Once the messaging is approved, I will copy it for 0.36-1 and 0.36-2. I left them blank to avoid needing to make duplicate changes.

docs(changelog) note missing 1.2 features in 0.36

---

app/0.11.x/proxy.md
app/0.12.x/proxy.md
app/0.13.x/proxy.md
app/0.14.x/proxy.md
app/enterprise/0.34-x/proxy.md

link replaces to a source website link
https://www.ietf.org/rfc/rfc3986.txt

chores(links): broken links to rfc 1386

---

app/1.0.x/plugin-development/tests.md
app/1.3.x/plugin-development/tests.md
app/_hub/qnap/api-transformer/index.md
app/enterprise/0.35-x/plugin-development/tests.md
app/enterprise/0.36-x/plugin-development/tests.md

In addition to CI - broken links checker, a human one.
1) remove url to qnap github, with kong api in lua
2) changed spec reference broken by Kong/kong@5c24e507

chores(links) -  fix got github broken links

---

app/enterprise/0.35-x/deployment/installation/amazon-linux.md

After working with a customer, it seems that the package with the 95 suffix no longer exists in Amazon's Repo.

Update Amazon instructions

---

app/_hub/kong-inc/rate-limiting/0.1-x.md
app/_hub/kong-inc/rate-limiting/index.md

* made policy param semi-required
* added example value
* added explaination in description for semi-optional
Please refer Kong/kong#4965 for issues due to this.
The docs page for rate-limiting currently does not list policy in config in the examples which cause issues to people who are using the same declarative configuration file in DB-less mode.

docs(ce/rate-limiting) fix-config-policy

---

app/_layouts/extension.html

Updates Plugin Parameters template to use `.id` vs `_id` for service, route, and consumer parameters
This will change all the plugins to the correct params
Solves #1525

Update plugin params

---

app/_hub/kong-inc/aws-lambda/index.md

We accidentally added the 'Notes' section inside the 'Known issues' section: https://github.com/Kong/docs.konghq.com/pull/1549/files#diff-e1db400f86ea82db8db667114dd7927eL149-R181

style(aws-lambda) fix formatting issues

---

app/enterprise/1.3-x/deployment/migrations.md

Use correct target for Enterprise 1.3 migration links. Links previously targeted guides for versions older than the prerequisite version.

fix(migrations) correct 1.3 links

---

.github/CODEOWNERS

Goal is to ensure that Team Docs are the only ones who can
approve PRs.

chore(config) make Levi and Aron code owners for master (WIP)

---

.github/CODEOWNERS

chore(config) explain why CODEOWNERS = Team Docs

---

app/_data/docs_nav_ee_1.3-x.yml
app/enterprise/1.3-x/developer-portal/theme-customization/adding-javascript-assets.md
app/enterprise/1.3-x/developer-portal/theme-customization/single-page-app.md

This PR adds docs for SPA served out of portal, as well as how to add custom javascript assets.

doc(portal): add javascript asset docs

---

app/_data/docs_nav_studio_1.0.x.yml

Remove `/index` from Kong Studio navigation

remove link to index

---

app/1.4.x/clustering.md
app/1.4.x/loadbalancing.md

Added `upstream`'s new property `host_header` to load balancing guide.
Added `cassandra_refresh_frequency` to clustering guide.

docs(1.4.x) added `host_header` and `cassandra_refresh_frequency`

---

app/_hub/kong-inc/rate-limiting/index.md
app/_hub/kong-inc/response-transformer/index.md

docs(rate-limiting) new `limit_by` value (`service`)
docs(response-transformer) new `headers.rename` param

docs(*) missing docs for the 1.4.0 release

---

app/_data/docs_nav_1.3.x.yml
app/_data/docs_nav_1.4.x.yml

Add missing links to gRPC guide, currently unreachable - unless one uses the search feature.

docs(ce/nav) add link to grpc guide

---

app/1.4.x/admin-api.md
app/1.4.x/db-less-admin-api.md

* Includes `check_hash` query string in DB-less mode
* Includes endpoint-key based notation for foreign key arguments
(e.g. using `service.name` instead of `service.id`)
Companion Kong PR which generated these changes:
https://github.com/Kong/kong/pull/5245

docs(ce/1.4.x) update auto-generated docs

---

app/_assets/stylesheets/page.less
app/_assets/stylesheets/pages/docs.less
app/_layouts/docs.html

- Adds (2020) to Kong Enterprise version dropdown
This adds extra width so I increased the width of the dropdown and moved the Search bar up so they would both fit

add (2020) to 1.3 version dropdown

---

app/_hub/zillowgroup/kong-terraform/index.md

Currently, there are old links to this page that 404.

provide redirect to new terraform module page

---

app/enterprise/changelog.md

Clarifies the OpenResty security patch released in 0.35-4

Update 0.35-4 for HTTP/2 security fixes

---

app/_hub/kong-inc/statsd/index.md

documented namespaces for statsd metrics are mismatching current implementation
metrics for user request `.count`/`.status` and service `.status` have a prefix `.request` that is missing in the doc
References:
- ["%s.user.%s.request.count"](https://github.com/Kong/kong/blob/master/kong/plugins/statsd/handler.lua#L57)
- ["%s.user.%s.request.status"](https://github.com/Kong/kong/blob/master/kong/plugins/statsd/handler.lua#L68) 
- ["%s.request.status](https://github.com/Kong/kong/blob/master/kong/plugins/statsd/handler.lua#L33)

docs(statsd) fix mismatch in metric namespace

---

app/_hub/kong-inc/kong-terraform-aws/index.md

Update the support URL to use the Kong repository rather than the old third-party repository.

fix(hub) use Kong repo for Terraform

---

app/_assets/stylesheets/page.less

Adds CSS for a red alert box:
`<div class="alert alert-red">`

add red-alert box

---

app/_hub/kong-inc/kafka-upstream/index.md

Kafka Upstream is packaged with Kong Enterprise, and customers do not have access to the Git repo, so these instructions are purely internal for developers.

remove Kafka Upstream installation instructions

---

app/enterprise/1.3-x/developer-portal/configuration/authentication/oidc.md

Remove uris in () from the sample config object as it causes some confusion for users who copy the json exactly. Leaving the () will cause redirect_uri errors among other things from the IDP.

Remove urls in parenthesis which cause confusion

---

app/_layouts/extension.html

Updates the Plugin layout, `extensions.html` so route and service id use `.` instead of `_`

update service_id and route_id to .id

---

app/_assets/stylesheets/page.less
app/_data/docs_nav_ee_1.3-x.yml
app/enterprise/1.3-x/deployment/installation/amazon-linux-2.md
app/enterprise/1.3-x/deployment/installation/amazon-linux.md
app/enterprise/1.3-x/deployment/installation/overview.md

- Updates Amazon Linux 1 installation guide
- Creates Amazon Linux 2 installation guide
- Updates Enterprise installation overview page:

amazon linux 1&2 guide update

---

app/enterprise/1.3-x/kong-for-kubernetes/install.md

Removed URL that was pointing to a 404. It was pointing to some non-existing URL.

Fix URL that was pointing to a 404

---

app/_hub/kong-inc/serverless-functions/index.md

Remove wrapping function from serverless plugin code examples. This reapplies parts of 8cdcfd8c5e57aaa56d2ebf3d3fb50cd9ffa3072c that appear to have been accidentally clobbered by d55c2dbbda9b4eb020ba218b7e255e5ee4848998 for the 1.3 docs release.

fix(serverless) correct example code

---

app/enterprise/1.3-x/cli.md
app/enterprise/changelog.md

Warns against using `db_import` and mentions that we don't support `db_export` for Enterprise.

docs(cli/changelog) mention db_import limitations

---

app/_hub/kong-inc/ldap-auth-advanced/index.md
app/enterprise/1.3-x/kong-manager/service-directory-mapping.md

Provide descriptions for the new group properties in LDAP Advanced:
- `group_base_dn`
- `group_name_attribute`
- `group_member_attribute`

docs(ldap-adv) add new group mapping properties

---

app/enterprise/1.3-x/admin-api/vitals/vitals-influx-strategy.md

When following these docs, for [this spike](https://github.com/Kong/kong-collector/pull/382/files) I stumbled over the process of creating the initial influxdb kong database. It appears that adding an environment variable to the docker environment allows us to remove 10 lines of docs.

docs(vitals) simplify influx vitals docs

---

app/_hub/kong-inc/cors/index.md

As per: https://github.com/Kong/kong/blob/master/kong/plugins/cors/handler.lua#L218 , the defaults list has grown much larger.

docs(hub) update cors methods defaults

---

app/_hub/kong-inc/jwt/index.md

Adding documentation for custom header names for the JWT plugin via `config.header_names` (which was added in [this commit](https://github.com/Kong/kong/commit/25638a606186a4561a04d228c78b7c315a2dffc9#diff-c0d3a6670f6b464eda1575b4489b4bb4) back in June 2019).

Update JWT plugin docs

---

README.md

Shows the status of the Netlify build in the README.

add netlify status badge

---

app/2.0.x/go.md

Some users have raised issues after trying to write Go plugins by trying to match Go compiler versions.  As this is extremely difficult, the usual advise is to recompile the go-pluginserver executable; fortunately `go get` makes it a single line task.  This patch tries to make is more explicit by listing as a development prerequisite.
some affected issues: Kong/go-pdk#23, Kong/kong#5505

make more explicit the need to recompile go-pluginserver

---

app/_data/docs_nav_2.0.x.yml

Adds a link to the gRPC topic in the CE Getting Started section.

docs(ce/2.0/nav) add grpc getting started link

---

app/enterprise/1.3-x/admin-api/audit-log.md

This will be available in the next 1.3.0.2 enterprise release.

docs(ee/audit-log) add regex support for `audit_log_ignore_paths`

---

app/_hub/kong-inc/request-transformer-advanced/index.md
app/_hub/kong-inc/request-transformer/index.md

Add Kubernetes-specific guidance for the request-transformer-advanced plugin's capture group functionality.
See https://kubernetes.slack.com/archives/CDCA87FRD/p1581616660335200 for context.

docs(plugins) add Kubernetes info for request-transformer-advanced

---

app/_hub/kong-inc/prometheus/index.md

Assuming `app/_hub/kong-inc/prometheus/index.md` refers to the latest plugin version, the changes of #1227 should have been made to that file instead of `app/_hub/kong-inc/prometheus/0.1-x.md`

docs(prometheus) update the custom server block snippet

---

app/install/centos.md
app/install/debian.md
app/install/redhat.md
app/install/ubuntu.md

when we released 2.0 we pruned some EOL (or near EOL) distributions and added a few new options

fix(distributions) adjust the CE supported distributions install links

---

app/enterprise/1.3-x/admin-api/index.md

Marketing has requested that we use consistent terminology, so have changed "entities" to "objects"...for example, Service Object section title starts section with "Service Entities"...this is confusing, so have changed "entities" to "objects" for clarity and consistency.

Changed "entities" to "objects" for Service, Route and other descs

---

app/enterprise/1.3-x/getting-started/index.md

We now have a Concepts section in the front of the Getting Started Guide.

Removed KeyConcepts from GetStarted Overview

---

app/_assets/stylesheets/page.less
app/_includes/read_time.html
app/_layouts/docs.html
app/enterprise/1.3-x/deployment/installation/overview.md
app/enterprise/1.3-x/index.md
app/enterprise/1.3-x/property-reference.md

Testing out an estimated reading time property for the enterprise docs. Can also add to community docs if reviewers find value in it. 
Usage: estimated reading time will appear on all enterprise doc pages by default. If you don't want it to show up, set `skip_read_time: true`. For example, I set it on the enterprise docs landing page and on the "choose your own adventure" installation page.

(docs/enterprise) Adding reading time estimate to enterprise pages

---

autodoc-admin-api/data.lua

returned by `/status` endpoint does not reflect the status of
read-only database connections yet

docs(autodoc/api) make it clear that the database status info

---

app/enterprise/1.3-x/kong-for-kubernetes/install.md

Add instructions to create a secret for the `kong-enterprise-edition-docker` registry in addition to the existing `kong-enterprise-k8s` secret. We have a mix of customers using either image in practice, and it's not immediately obvious that they require separate secrets.
Several other changes in content to align the docs site example more closely with the example in https://github.com/Kong/charts/pull/65

Add secrets for both Kong registries to K8S documentation

---

app/_data/docs_nav_ee_1.3-x.yml

ToC has two entries for RBAC and workspaces just one space apart, and the links are the same. Looks like a holdover from a previous release. Removing the extras.

Removing duplicate entries for RBAC and workspaces

---

app/enterprise/changelog.md

Removed "alpha" tag for license report feature in 1.3.0.1 changelog, as it's not an alpha feature, and we now have a topic in the docs. https://docs.konghq.com/enterprise/1.3-x/deployment/licenses/report/. While the topic applies to 1.3.0.2, the 1.3.0.1 license report info is valid and works, so not considered alpha. Our only hesitation is how Kong helps the user to run this report, and how we track info.

Updated 1301 changelog, removed alpha tag

---

app/enterprise/1.3-x/deployment/installation/ubuntu.md

Hi team 👋 
I ran into an issue that `kong migrations bootstrap` command didn't seed a password properly for `kong_admin`.
I realized the issue is coming from that we need to make sure the `KONG_PASSWORD` envvar is attached to the user that runs `kong migrations bootstrap` command.
I've confirmed with @felderi to run through this fix will seed a password properly.
Thanks!

Fixing steps for ubuntu

---

app/enterprise/1.3-x/proxy.md

X-Kong-Debug is incorrect it doesn't work for returning the routeid in response header, correct name for header is Kong-Debug

Corrected the header for debugging route

---

app/enterprise/1.3-x/admin-api/audit-log.md

Made some small edits to audit log page.

Small edits to audit-log page

---

app/_hub/kong-inc/canary/index.md

@satwant17 mind having a look?

fix(canary) fix omissions in Canary plugin docs

---

app/_assets/css/hub.css
app/_assets/stylesheets/pages/extension.less

Plugin pages list versions in their sidebar, with a checkmark or an x to indicate support. Changing the checkmark to green to make it stand out from the x. 
Old doc example: https://docs.konghq.com/hub/okta/okta/
Preview: https://deploy-preview-1878--kongdocs.netlify.com/hub/okta/okta/

docs(plugins) Changing color of plugin version checkmark

---

app/_assets/stylesheets/pages/extension.less
app/_layouts/extension.html

Plugin parameter tables were pulling in two different styles depending on the source of the value. This change makes them consistent with the styling in the rest of the docs. 
Old table formatting: https://docs.konghq.com/hub/kong-inc/forward-proxy/#parameters
Fixed formatting preview: https://deploy-preview-1877--kongdocs.netlify.com/hub/kong-inc/forward-proxy/#parameters

docs (plugins) Fixing table styling in plugins

---

app/enterprise/1.3-x/cli.md

Moved the "db_export" note from after the table to before the table for the kong config param. Needed to make more visible.

Move db_export note in kong config doc

---

app/enterprise/1.3-x/deployment/installation/docker.md

Make the admin api listen a value that must be set instead of opening the API to the world by default.

doc(*) - Update KONG_ADMIN_LISTEN in example

---

app/enterprise/1.3-x/brain-immunity/install-configure.md

This link directs users to the publicly available repo for helm chart for Kubernetes installation.  The installation instructions are in the repo README

Add(Brain/Immunity) Add link to public repo for helm chart

---

app/2.0.x/loadbalancing.md

Updated to include that Kong will make a second TCP request if the standard truncated flag is returned by the name server indicating there are further entries to retrieve, these will then be gotten over TCP/DNS
Added clarification that Consul may be ran with truncate flag enabled.

Update DNS caveats

---

app/_hub/kong-inc/exit-transformer/index.md

Add a warning about possible nil arguments to exit-transformer functions, along with an example of how to handle them safely.
See Jira ticket FTI-1415 for previous internal discussion.

Add warning about nil args for Exit Transformer

---

app/_hub/kong-inc/response-transformer-advanced/index.md

docs(hub) Response transformer advanced rename option.

---

app/enterprise/1.3-x/developer-portal/configuration/authentication/oidc.md

missing closing quotes on the ODIC config
"login_redirect_uri": ["https://example.portal.com"],

updated oidc.md

---

app/2.0.x/admin-api.md

Added multipart as supported content type, and moved
JSON format to beginning of section.

docs(admin-api) Content types support multipart.

---

.github/workflows/algolia.yml

Adds gh-actions cron to update the indices. We need to add
`ALGOLIA_API_KEY`
`ALGOLIA_APPLICATION_ID`
to this repo's setting for this to work. I was not able to test this out so no idea if it actually works. Author of action is no longer maintaining it (https://github.com/Embraser01/docsearch-scraper-action/issues/1#issuecomment-584523791)

chore(gh): add actions to update indices

---

.github/workflows/algolia.yml
README.md

The gh action was failing because the author is not supporting it anymore. I've created a new custom gh action and updated our usage.
Custom action:
https://github.com/darrenjennings/algolia-docsearch-action

chore(algolia): add custom action

---

app/_hub/salt/salt/index.md

* Removing params from yaml header - since this is of `type: integration`, the plugin params table isn't autogenerated from the metadata
* Creating table to capture the same parameters
* Cleaning up header structure
* Various minor cleanup

docs(plugins) Salt Security plugin cleanup

---

.github/workflows/algolia.yml

@lena-larionova need to make `algolia_application_id` and `algolia_api_key` to be named lowercase in settings on this repo, as the custom action uses lowercase values

chore(algolia) debug index

---

app/2.0.x/index.md

Removed Community from Kong Gateway Community naming convention.

Removed Community from Kong Gateway Community

---

app/enterprise/1.5.x/plugin-development/custom-logic.md

👋 @Kong/team-docs 
I've checked the plugins execution order in the fresh Kong EE 1.5 installation.
```bash
$ kong version
Kong Enterprise 1.5.0.0
$ cd /usr/local/share/lua/5.1/kong/plugins/
$ find . | xargs grep  \.PRIORITY |  sort -k 3 -t " " -n -r
./correlation-id/handler.lua:CorrelationIdHandler.PRIORITY = 100001
./exit-transformer/handler.lua:_M.PRIORITY = 9999
./bot-detection/handler.lua:BotDetectionHandler.PRIORITY = 2500
./cors/handler.lua:CorsHandler.PRIORITY = 2000
./oauth2-introspection/handler.lua:OAuth2Introspection.PRIORITY = 1700
./application-registration/handler.lua:PortalAppHandler.PRIORITY = 1007
./mtls-auth/handler.lua:MtlsAuthHandler.PRIORITY = 1006
./jwt/handler.lua:JwtHandler.PRIORITY = 1005
./degraphql/handler.lua:_M.PRIORITY = 1005 …
```

Fixed the order for 1.5

---

app/_layouts/extension.html

Most plugin values are entered in backticks in the individual plugin pages, so having code formatting applied on top adds backticks to the output. Removing that formatting for cleaner output.

fix(plugin template) Removing code formatting from plugin default values

---

app/enterprise/1.3-x/deployment/installation/overview.md
app/enterprise/1.5.x/deployment/installation/overview.md

Links to RHEL installation point to Docker in 1.3-x and 1.5.x, fixing them to go to the right topic.

docs(ee-install) Fixing links to RHEL installation

---

app/getting-started-guide/latest/expose-services.md

* Switching the content under "Using cURL" and "Using HTTPie" - it was backwards
* Fixing port number for verifying route

docs(gsg/expose-services) Fixing port number and tab headings

---

app/_hub/kong-inc/exit-transformer/index.md

Add new `handle_` settings and usage guidance to exit-transformer documentation. See https://github.com/Kong/kong-plugin-enterprise-exit-transformer/pull/3 for reference.

Add new handle_ settings for exit-transformer

---

app/_data/extensions/kong-inc/datadog/versions.yml
app/_hub/kong-inc/datadog/1.0-x.md

Bumping Datadog plugin version to its current actual version 3.0. Also adding in missing 1.0.x file based on its state on February 14th, 2020 prior to the 3.0 updates done by a patch in https://github.com/Kong/docs.konghq.com/pull/1551. Skipping 2.0.x per Lena.
Direct link for review: https://deploy-preview-1988--kongdocs.netlify.app/hub/kong-inc/datadog/

Datatdog version updates

---

app/_hub/kong-inc/openid-connect/index.md

This commit updates information and links related to WSO2 Identity Server.
WSO2 Identity Server now supports `access_token` and `refresh_token` as values of `token_type_hint` thereby adhering to the OAuth 2.0 Introspection standard.

Update links and info about WSO2 IS

---

app/_hub/kong-inc/rate-limiting-advanced/index.md

Add new config to adv rate limiting plugin per tickets:
https://konghq.atlassian.net/browse/DOCS-963
https://konghq.atlassian.net/browse/FTI-1113
When a Sentinel node has auth enabled, this pw is required for successful auth between Kong and Sentinel nodes.
@kallecaco3 I took a stab at a description. Please review. Thank you for your assistance. I am also updating the GraphQL plugin per DOCS-998 GraphQL Rate Limiting Advanced errors https://konghq.atlassian.net/browse/DOCS-998; does this option needed to be added there as well? Answer is yes per Karl; will do.
Direct link to generated output for review:
https://deploy-preview-1993--kongdocs.netlify.app/hub/kong-inc/rate-limiting-advanced/#parameters

docs/add new param config.redis.sentinel_password

---

app/_hub/critical-blue/approov/index.md

Relates to https://konghq.atlassian.net/browse/DOCS-1021. 
* Removed from "security" category and left it in "authentication"; plugin template is misleading, plugin should only be in one category.
* Changed supported versions to versions that were actually tested by the plugin developer
Preview: https://deploy-preview-1998--kongdocs.netlify.app/hub/critical-blue/approov/

fix(plugins) Approov plugin fixes

---

.github/workflows/algolia.yml

Studio docs got moved into Enterprise so there's no need for a separate index anymore

Algolia workflow: removing Studio index

---

app/enterprise/1.5.x/developer-portal/structure-and-file-types.md

docs: fix misspelled templates link

---

app/getting-started-guide/latest/secure-services.md

* change mock to mocking in admin api calls

docs(ce/getting-started) typo in secure-services section

---

app/_hub/kong-inc/oauth2-introspection/index.md

I have been asked recently about how to limit access to a scope when using the OAuth 2.0 Introspection plugin. This is not possible, however, the OpenID Connect plugin supports OAuth 2.0 Token Introspection as well and can be used instead.
This adds a note with a link to the OpenID Connect plugin to the documentation for the OAuth 2.0 Introspection plugin.

docs(oauth2-introspection) Note and link to OpenID Connect plugin

---

app/_hub/kong-inc/oauth2-introspection/index.md

When configuring the `oauth2-introspection` plugin it took me a bit to figure out how to set the required `authorization_value` parameter properly.
This PR clarifies the most common use case of a Base64-encoded Basic Auth string that works with Okta and likely others.

docs(oauth2-introspection) Clarify authorization_value

---

.github/workflows/build-test.yml

Testing out another method of building previews: disabling the "review_requested" flag, as it's building every time you add a reviewer or re-request a review.

fix(build workflow) Removing review_requested

---

app/_data/docs_nav_ee_1.5.x.yml

Link is already fixed in 1.3-x

docs(nav) Fix link to CA certificate object in 1.5.x nav

---

app/_data/docs_nav_ee_1.5.x.yml
app/enterprise/1.5.x/rate-limiting.md

Rate limiting reference exists outside of the doc versioning structure, so it doesn't pick up the ToC and floats on its own. 
* Adding the rate limiting reference into ee-1.5.x and updating nav accordingly
* Leaving it as is for previous versions to avoid unnecessary topic duplication
* Changing the layout to the (new) default docs layout instead of a reference-specific one

docs(rate-limiting) Moving rate limiting reference 

---

app/_hub/kong-inc/session/index.md
app/enterprise/1.5.x/developer-portal/configuration/authentication/sessions.md

https://konghq.atlassian.net/browse/DOCS-1045
https://deploy-preview-2022--kongdocs.netlify.app/enterprise/1.5.x/developer-portal/configuration/authentication/sessions/#configuration-to-use-the-sessions-plugin-with-the-dev-portal
https://deploy-preview-2022--kongdocs.netlify.app/enterprise/1.5.x/developer-portal/configuration/authentication/sessions/#domains
Link in first paragraph of Session plugin back to Dev Portal auth session:
https://deploy-preview-2022--kongdocs.netlify.app/hub/kong-inc/session/

more info on cookie_domain in dev portal auth sessions

---

app/_data/docs_nav_ee_1.5.x.yml
app/enterprise/1.5.x/deployment/installation/overview.md
app/enterprise/1.5.x/kong-for-kubernetes/install-on-kubernetes.md
app/enterprise/1.5.x/kong-for-kubernetes/install.md

*  Adding descriptions of packages to intro based on https://github.com/Kong/docs.konghq.com/pull/2015
* Splitting out instructions for `kong-kubernetes-install` into separate section
* Rearranging topic to fit new instructions
Previews:
https://deploy-preview-2019--kongdocs.netlify.app/enterprise/1.5.x/kong-for-kubernetes/install/
https://deploy-preview-2019--kongdocs.netlify.app/enterprise/1.5.x/kong-for-kubernetes/install-on-kubernetes/

docs(install) Instructions for installing Kong Enterprise on Kubernetes

---

app/_data/docs_nav_ee_1.5.x.yml
app/enterprise/1.5.x/kong-for-kubernetes/deployment-options.md
app/enterprise/k8s-changelog.md

This document provides an overview of the two Enterprise image options for Kong for Kubernetes geared towards helping users decide which option fits their use case. It compares the features available in both, explains how database-backed Kong for Kubernetes deployments differ from non-controller-managed deployments, and provides basic information about migrating between the deployment types.

Add overview of Kong for Kubernetes deployment options

---

app/2.0.x/proxy.md
app/enterprise/1.5.x/proxy.md

Currently this tag is referenced at the end of https://docs.konghq.com/2.0.x/proxy/#3-proxying--upstream-timeouts (https://github.com/Kong/docs.konghq.com/blame/e94866bcd0ac3c3020a230803433947805308ae1/app/2.0.x/proxy.md#L959 in source), but was not present in the bottom matter.

fix(proxy) add missing link tag

---

app/_hub/critical-blue/approov/index.md

* Updates made by #1951 that do not reflect https://github.com/Kong/docs.konghq.com/pull/1951#issuecomment-623436650:
+ Title was not changed as requested.
+ The compatible versions list include versions listed as incompatible.
* Additional fix to the link for the ./bin/kong-admin.sh bash script.
Signed-off-by: Exadra37 <exadra37@gmail.com>

Fixes the updates made by #1951 to the Approov plugin docs.

---

app/enterprise/1.5.x/brain-immunity/auto-generated-specs.md

Fixes several bugs with https://docs.konghq.com/enterprise/1.5.x/brain-immunity/auto-generated-specs/:
1. The formatting of the last section is currently broken because of unescaped angle brackets that cause text to be interpreted as HTML tags
2. The URL at the end contains two `?` which would cause it to fail if used as-is
3. The parameter `openapi_version` is not explained (though it appears in the URL format).
In addition to fixing these, some general tidying up - using the same wording everywhere, aligning with other parts of the docs (e.g. using `<COLLECTOR_HOST>:<COLLECTOR_PORT>`).

docs(brain) Fixes for Auto-Generated Specs page

---

app/enterprise/changelog.md

Worked with Arturas M to update the changelog. 
**Release Date:** 2020/05/14
- Reverted some breaking changes introduced by [PR #3780](https://github.com/Kong/kong/pull/3780) involving the handling of slashes inside the router.
- Reverted service mesh changes affecting proxy_ssl_* directives.

Added 0.35-5 release

---

app/_hub/kong-inc/session/index.md

* Added KE 1.5.x version to "bundled-with" for Ldap Auth plugin
* This version info hasn't been updated since 1.3-x
* Confirmed with Rob S to look at https://konghq.atlassian.net/wiki/spaces/FTT/pages/8356124/Kong+Enterprise+-+Changelog+Features+Release+Schedule to confirm plugins bundled with release versions.

docs(plugins) Added KE 1.5.x to Sessions plugin bundle/version support

---

app/_hub/kong-inc/ldap-auth/index.md

- Added KE 1.5.x and 1.3-x versions to "bundled-with" for Ldap Auth plugin
- This version info hasn't been updated since 0.36-x
- Confirmed with Rob S to look at https://konghq.atlassian.net/wiki/spaces/FTT/pages/8356124/Kong+Enterprise+-+Changelog+Features+Release+Schedule to confirm plugins bundled with release versions.

docs(plugins) Added KE 1.5.x & 1.3-x to Ldap_auth plugin bundle/version support

---

app/_layouts/extension.html

The plugins layout doesn't account for a few different use-cases when it comes to db-less config. It also assumes that if a plugin is a core plugin, then it has db-less support.
* Changed example settings so that layout would look for other permutations of the dbless_compatibility setting, including times when the parameter doesn't exist. This fixes OAuth2, which isn't db-less compatible.
* Conditionalized the "Global Plugins" section to display info on db-less only when a plugin supports it.
* Removed info about enabling a plugin on a consumer through `http://localhost:8001/plugins`
Previews:
OAuth2: https://deploy-preview-2039--kongdocs.netlify.app/hub/kong-inc/oauth2/
Any Kong Inc plugin: https://deploy-preview-2039--kongdocs.netlify.app/hub/

docs(plugins) DB-less config cleanup for examples and global plugins

---

app/_hub/kong-inc/mtls-auth/index.md

- Added known issue for param "revocation_check_mode", as default IGNORE_CA_ERROR" does not work in version 1.5.0.0 and later. 
- Workaround is to set value to "SKIP"
- Did not want to change default value to Skip, so opted for known issue note. 
- See https://konghq.atlassian.net/browse/FTI-1509
- Need to remove this note when issue is fixed.

docs(plugin-mtls_auth) Added known issue for revocation_check_mode

---

app/enterprise/1.3-x/deployment/installation/overview.md
app/enterprise/1.3-x/getting-started/index.md
app/enterprise/1.3-x/kong-manager/administration/rbac/index.md
app/enterprise/1.3-x/kong-manager/overview.md
app/enterprise/1.5.x/deployment/installation/overview.md
app/getting-started-guide/latest/dev-portal.md
app/getting-started-guide/latest/manage-teams.md
app/getting-started-guide/latest/overview.md
app/getting-started-guide/latest/prepare.md
app/getting-started-guide/latest/protect-services.md

Issues: images are set to expand on click across the site, icons and linked images included. This PR disables that for Enterprise 1.3-x and 1.5.x and the getting started guide.
Current behavior: https://docs.konghq.com/enterprise/1.5.x/deployment/installation/overview/

docs(images) Disabling image expand on icons

---

app/enterprise/1.5.x/developer-portal/administration/developer-permissions.md
app/enterprise/1.5.x/developer-portal/administration/managing-developers.md
app/enterprise/1.5.x/developer-portal/configuration/authentication/adding-registration-fields.md
app/enterprise/1.5.x/developer-portal/configuration/authentication/basic-auth.md
app/enterprise/1.5.x/developer-portal/configuration/authentication/key-auth.md
app/enterprise/1.5.x/developer-portal/configuration/authentication/oidc.md
app/enterprise/1.5.x/developer-portal/configuration/authentication/sessions.md
app/enterprise/1.5.x/developer-portal/configuration/smtp.md
app/enterprise/1.5.x/developer-portal/configuration/workspaces.md
app/enterprise/1.5.x/developer-portal/structure-and-file-types.md
app/enterprise/1.5.x/developer-portal/theme-customization/adding-javascript-assets.md
app/enterprise/1.5.x/developer-portal/theme-customization/easy-theme-editing.md
app/enterprise/1.5.x/developer-portal/theme-customization/emails.md
app/enterprise/1.5.x/developer-portal/theme-customization/single-page-app.md
app/enterprise/1.5.x/developer-portal/using-the-editor.md
app/enterprise/1.5.x/developer-portal/working-with-templates.md

Quick copy edit to clean up dev portal content.
The landing pages and the migration topics are not included in this PR. App portal registration is also not included. Those will be separate PRs. There are some navigation issues that will be addressed with forthcoming site improvements.
Because much of the content was/is on one code line, it is sometimes difficult for git to show a proper diff. That also makes it difficult to make granular suggested edits.
Direct review link entry point:
https://deploy-preview-2075--kongdocs.netlify.app/enterprise/1.5.x/developer-portal/

Dev portal copy edits

---

app/_data/docs_nav_ee_0.35-x.yml
app/_data/docs_nav_ee_0.36-x.yml
app/_data/docs_nav_ee_1.3-x.yml
app/_data/docs_nav_ee_1.5.x.yml
app/enterprise/0.35-x/admin-api/workspaces/examples.md
app/enterprise/0.36-x/admin-api/workspaces/examples.md
app/enterprise/1.3-x/admin-api/rbac/examples.md
app/enterprise/1.3-x/admin-api/workspaces/examples.md
app/enterprise/1.5.x/admin-api/rbac/examples.md
app/enterprise/1.5.x/admin-api/workspaces/examples.md

I noticed there are a few documentation pages that do not appear in the navigation of the Enterprise docs. Some can be reached through links on other pages, but some only through the search. Some of these pages contain important information, e.g. about conflict resolution between workspaces.
This PR adds them to the navigation as far back as `0.35` (when it seems a lot of the docs were reorganized).
It also replaces the old `API(s)` with the new `Service(s)` on one of those pages.

docs(nav) Add missing navigation items to Admin API and Guides

---

app/enterprise/changelog.md

Added: 
* Mutual TLS Authentication Plugin
* For parameter, `config.revocation_check_mode`, the default value `IGNORE_CA_ERROR` has a known issue. As a workaround, manually set the value to `SKIP`.

docs(changelog_1.5.0.0) Added known issue for MTLS TLS Auth Plugin

---

app/enterprise/1.5.x/developer-portal/working-with-templates.md

This PR is a straight copy/paste. 
@tlblessing this page definitely needs reformatting, it's very hard to use right now. We can go one of two ways:
- The easy(ish) solution is to follow the styling we have in the Admin API docs. This is literally an API doc as well, and should be presented as such: https://docs.konghq.com/enterprise/1.5.x/admin-api/
- The tougher (but better in the long run) solution is to work with the DevX team to create API docs using our own product.  
Solution #1 is definitely a temp solution (though it might be necessary for now). The real solution would require a rework of all of our API docs, not just these.

docs(dev portal) Copying changes to template docs from 1.3-x to 1.5.x

---

app/1.2.x/db-less-and-declarative-config.md
app/1.3.x/db-less-and-declarative-config.md
app/1.4.x/db-less-and-declarative-config.md
app/1.5.x/db-less-and-declarative-config.md
app/2.0.x/db-less-and-declarative-config.md
app/_hub/kong-inc/proxy-cache/index.md

As an OSS plugin, proxy-cache has db-less support. 
* Added the plugin to db-less support lists going back to 1.2.x based on https://github.com/Kong/kong/blob/master/CHANGELOG.md
* Removed sidecar injector plugin from 2.0.x and 1.5.x lists as it was deprecated in 1.5.x (https://github.com/Kong/docs.konghq.com/pull/1817)  
* Set `dbless_compatibility` to true to generate examples and accurate descriptions
Previews: https://deploy-preview-2049--kongdocs.netlify.app/hub/kong-inc/proxy-cache
https://deploy-preview-2049--kongdocs.netlify.app/2.0.x/db-less-and-declarative-config/

docs(plugins) Proxy-cache supports db-less

---

renovate.json

Based on the docs found here: https://konghq.atlassian.net/wiki/spaces/KD/pages/1123156059/Renovate-bot
Particularly:
> The docs site currently runs on Jekyll 3.8.6 and Bootstrap 3 - updating these two packages will break the site, renovate-bot has been told not to try to update these but be on the lookout in-case it does!
Renovate-bot has recently tried to open PRs twice to update jekyll to 3.8.7, even though closing the PR should tell it to ignore the update. Changing settings to ignore both jekyll and bootstrap updates.

fix(renovate-bot) Setting bot to ignore jekyll and bootstrap dependency updates

---

app/_data/docs_nav_ee_1.5.x.yml
app/enterprise/1.5.x/kong-for-kubernetes/changelog.md
app/enterprise/1.5.x/kong-for-kubernetes/deployment-options.md
app/enterprise/1.5.x/kong-for-kubernetes/index.md
app/enterprise/1.5.x/kong-for-kubernetes/install-on-kubernetes.md
app/enterprise/1.5.x/kong-for-kubernetes/install.md
app/enterprise/1.5.x/kong-for-kubernetes/using-kong-for-kubernetes.md

* Adding a compatibility links section to "Using Kong for Kubernetes"
* Minor edits for typos, grammar, and header depth 
* Based on feedback from team, moving deployment topic up in the nav
* Rephrasing and some cleanup on intro page - @rainest can you look over the changes to /kong-for-kubernetes/index.md and let me know if this content is accurate? It doesn't seem to fully line up with your deployment topic.

docs(ee-kubernetes) Cleaning Kubernetes topics and nav tweak

---

app/_hub/kong-inc/request-validator/index.md

This brings the documentation of the Request Validator plugin in line with its current implementation.
Most importantly, it removes the notice that it does not support JSON Schema validation - it does now. This is an important capability.
Some minor cleanup as well.

docs(request-validator) Add docs for JSON Schema Draft 4 validation

---

app/_hub/kong-inc/request-validator/0.36-x.md

Backports changes from https://github.com/Kong/docs.konghq.com/pull/2093 to `0.36-x` since Draft 4 validation was originally [introduced in version 0.36](https://docs.konghq.com/enterprise/changelog/#plugins-16).

docs(request-validator) Backport draft4 to 0.36-x

---

app/_hub/kong-inc/request-validator/index.md

The Request Validator plugin gained a very useful `verbose_response` parameter [in version 1.3.0.2](https://docs.konghq.com/enterprise/changelog/#plugins-4).
This adds it to the plugin documentation.

docs(request-validator) Add verbose_response parameter

---

app/enterprise/1.5.x/developer-portal/configuration/authentication/oidc.md

Adds two important notes to the OIDC configuration for the Dev Portal on developer accounts and the IdP Redirect URI.
Especially without the hint on the `redirect_uri` pretty much the only way to know the correct configuration is to inspect the actual network requests and notice what's happening under the hood. I'm still not quite happy with it (still easy to overlook but essential for it to work) - but this is the best that I can come up with right now.
Some smaller fixes for spelling, replacing `Yahoo` with `Okta` as the much more common IdP, and removing the very Google-specific note on client id and secret with a pointer to the OIDC plugin docs that do a more thorough job.
Much of this is likely applicable to versions prior to 1.5, but it would take me a while to test this on those …

docs(portal-oidc) Notes on redirect_uri and developer accounts

---

app/enterprise/1.5.x/kong-for-kubernetes/install-on-kubernetes.md

Added a parameter (enterprise.enabled) that's needed to enable Enterprise to the table.

Added a parameter that's needed to enable Enterprise

---

app/_hub/kong-inc/openid-connect/index.md

Add links to Kong Enterprise detailed integration guides for providers where available, for improved discovery.
May have some rendering errors to start--I'm having issues with getting the local Docker compose image to start, so relying on netlify.
An aside, I've added these to https://docs.konghq.com/hub/kong-inc/openid-connect/#compatibility, but there's a duplicate of the compatibility list near the bottom of the intro section. I believe that's sourced from upstream, so I didn't modify it, but we should probably look at consolidating on or the other.

Add OIDC integration guide links to Hub

---

app/install/docker.md

We need to add the missing `KONG_PG_USER` for environment variables. Otherwise, we will encounter a `connection refused` error
> Error: [PostgreSQL error] failed to retrieve PostgreSQL server_version_num: connection refused

Add KONG_PG_USER

---

app/2.0.x/admin-api.md

This change was generated using an updated admin-api build script - see https://github.com/Kong/kong/pull/6027
Implements https://github.com/Kong/docs.konghq.com/pull/1874

docs(admin-api) use `id or name` instead of just `id`

---

app/_hub/kong-inc/upstream-tls/index.md

- Edited deprecated note to say "This plugin is deprecated in Kong Enterprise, version 1.3, and removed in version 1.5."

docs(upstream-tls-plugin) Added deprecated note

---

app/enterprise/changelog.md

- Updated changelog to add 0.36-6 fix "Fixed Kong PDK `get_method()` function to return a correct HTTP method when there are connectivity issues with the upstream."

docs(0.36-6 changelog) Updated changelog

---

app/enterprise/changelog.md

- Changed release date for 0.36-6 from 2020-06-15 to 2020-06-18

docs(changelog-update) Change release date for 0.36-6

---

app/_includes/docs-sidebar-item.html

Adding an exception for links with anchors. 
Looks like there's some weird behaviour remaining (ToC doesn't set anchor links to active when they're clicked), but that's more of a visual consistency issue and can try to fix that in the future.

fix(toc) Fixing broken links in Admin API ToC

---

app/enterprise/1.5.x/property-reference.md

update description and examples for `admin_gui_url`

docs(config) admin_gui_url does not support paths

---

app/install/ubuntu.md

Kong CE focal package won't be available at the linked location until 2.1.0 GA as such please do not merge / deploy this until after 2.1.0 final

fix(distributions) add focal link for Kong CE

---

app/_data/extensions/kong-inc/basic-auth/versions.yml
app/_data/extensions/kong-inc/hmac-auth/versions.yml
app/_data/extensions/kong-inc/jwt/versions.yml
app/_data/extensions/kong-inc/key-auth/versions.yml
app/_data/extensions/kong-inc/ldap-auth/versions.yml
app/_data/extensions/kong-inc/oauth2/versions.yml
app/_hub/kong-inc/basic-auth/2.1-x.md
app/_hub/kong-inc/hmac-auth/2.1-x.md
app/_hub/kong-inc/jwt/2.1-x.md
app/_hub/kong-inc/key-auth/2.1-x.md
app/_hub/kong-inc/ldap-auth/2.1-x.md
app/_hub/kong-inc/oauth2/2.1-x.md

X-Credential-Identifier is the new header name.
**Note**: in reviewing, please make sure to review `index.md` files, not the old plugin versions (e.g., 2.1-x in most plugins).

docs(hub) x credential username deprecation

---

app/enterprise/k8s-changelog.md

Add changelog entries for today's release of kong-enterprise-k8s 2.0.4.2.

release(k8s) add k8s 2.0.4.2 changelog info

---

app/_hub/kong-inc/jwt/index.md

Add warning for decK and KIC users to jwt-auth/JWT credential docs.
Please see https://github.com/hbagdi/deck/issues/181 and
https://github.com/Kong/kubernetes-ingress-controller/issues/750 for
background.

docs(jwt) add decK and KIC warnings to jwt-auth

---

app/_data/extensions/kong-inc/aws-lambda/versions.yml
app/_hub/kong-inc/aws-lambda/3.0-x.md

Add version 3.4.x of the plugin, along with new configurations. Please review `index.md`, which is the latest version of the docs.

docs(hub) update aws-lambda docs to match version 3.4.0

---

app/_hub/kong-inc/oauth2/index.md

Add new configs to oauth2 plugin docs. Note that the plugin's new version page has already been added, so the new configs were simply added to it.

docs(hub) add new oauth2 configs

---

app/_data/extensions/kong-inc/zipkin/versions.yml
app/_hub/kong-inc/zipkin/1.0.x.md

Add zipkin 1.1.0 docs.
**NOTE**: please focus review on `index.md`, which contains newly added docs.

docs(hub) add zipkin 1.1.0 docs

---

app/_data/extensions/kong-inc/prometheus/versions.yml
app/_hub/kong-inc/prometheus/0.8.x.md

Update Prometheus plugin docs to match current version (0.9.0). Please review `index.md`, which contains the latest version of the docs.

docs(hub) update prometheus docs to match version 0.9.0

---

app/_hub/kong-inc/deck/index.md

Very outdated link to 0.4 before - changed to 1.1.0
Please automate that it is always the latest link!

Updated download link to latest decK version

---

app/_hub/index.html
app/_includes/hub_cards.html

Based on slack thread in `#docs`, mainly:
> Our hub lists ACME as being bundled with Kong Enterprise https://docs.konghq.com/hub/ - but it is not in the package.
Also happens with grpc-web and grpc-gateway plugins.
Filter tweak fixes the Enterprise plugin selector. Test by clicking "Bundled with Kong Enterprise".
Preview: https://deploy-preview-2166--kongdocs.netlify.app/hub/

docs(plugins) Fixing filtering for enterprise plugins

---

app/_hub/kong-inc/grpc-gateway/index.md

grpc-gateway plugin: missing link in image credit

---

app/_hub/kong-inc/oauth2/index.md

This commit adds missing documentation for OAuth 2.0 plugin's `config.pkce` parameter.

docs(oauth2) add missing documentation for pkce parameter

---

app/_data/docs_nav_ee_2.1.x.yml

This PR updates the following obsolete TOC entry:
This TOC entry will eventually link to the content @Jlawlzz and I will produce for 2.1 Dev Portal migration https://konghq.atlassian.net/browse/DOCS-1139.
Direct review link: https://deploy-preview-2177--kongdocs.netlify.app/enterprise/2.1.x/deployment/migrations/

Update migrate/upgrade for Dev Portal to beta placeholder

---

app/_assets/stylesheets/page.less

Got feedback that it's distracting to have the button dead center. This adjustment will work for the majority of screens, though it isn't as well-positioned at very high resolutions.

docs(styles) Adjust scroll button position

---

app/_assets/stylesheets/page.less

Mobile banner was still defaulting to blue gradient. Adjusting CSS to use the banner on mobile as well.
To test, open the Netlify preview from a mobile device; or, in Chrome:
1. Open the dev tools (Right-click anywhere on the page > Inspect).
2. Turn on the device toolbar with Cmd+shift+M.
3. In the dropdown that appears, switch from "Responsive" to any mobile device.
The geometric banner should remain visible in all sizes.

docs(layout) Adjustment to mobile banner

---

app/_hub/kong-inc/grpc-gateway/index.md
app/_layouts/extension.html

- Fixing broken alpha banner
- Replacing alpha banner with beta for grpc-gateway plugin: Community 2.1 is GA, Enterprise 2.1 is in beta.
- Adding Enterprise 2.1 to "bundled with" versions
@fffonion is this plugin supposed to be available in Enterprise? I'm seeing it in Kong Manager in a 2.1.0.0 beta build, though the "bundled with" section on this page only mentions Community.
Preview: https://deploy-preview-2180--kongdocs.netlify.app/hub/kong-inc/grpc-gateway/

Docs(plugins) grpc-gateway alpha banner

---

app/getting-started-guide/2.1.x/manage-teams.md

Guide instructs users to set “enforce_rbac = off”, which is incorrect. Changed it to "on".

docs(gsg) Fix RBAC setting

---

app/_layouts/extension.html

Adding feedback widget to plugin doc pages.
Note: Widget will not appear on the Hub landing page, but will appear on anything under the /hub/ directory. This is to mirror the rest of the docs.
Sample preview: https://deploy-preview-2197--kongdocs.netlify.app/hub/kong-inc/application-registration/

docs(plugins) Feedback widget for plugin docs

---

app/enterprise/2.1.x/deployment/installation/docker.md

👋 
when pulling the docker image, the version should be explicitly set. Because currently, the `latest` tag points to 1.5.x, if you don't specify the version.

Make sure the image points to the 2.1

---

CONTRIBUTING.md
README.md
templates/how-to.md

Adding a bunch of missing info for creating docs. 
* https://github.com/Kong/docs.konghq.com/blob/docs/instructions/README.md
* https://github.com/Kong/docs.konghq.com/blob/docs/instructions/CONTRIBUTING.md#formatting-documentation
Note: None of these pages will build with Netlify, so don't refer to the to build preview.

docs(github) Updates to doc contribution instructions

---

app/enterprise/2.1.x/kong-for-kubernetes/deployment-options.md
app/enterprise/2.1.x/kong-for-kubernetes/index.md
app/enterprise/2.1.x/kong-for-kubernetes/install.md

Update K4K8S documentation to recommend the kong-enterprise-edition image for all deployments, DB-less or otherwise. See FT-1402 and DOCS-1166 for internal discussion of this change.

doc(k4k8s) add kong-enterprise-edition DB-less doc

---

app/_hub/kong-inc/oauth2/1.0-x.md

Plugin filename uses the incorrect version, so the version selector dropdown was throwing a 404 (check by selecting 1.0-x from the dropdown [here](https://docs.konghq.com/hub/kong-inc/oauth2/)).
This change fixes the filename and adds the version to the plugin metadata.
Preview: https://deploy-preview-2202--kongdocs.netlify.app/hub/kong-inc/oauth2/1.0-x.html

docs(plugins/oauth) Fix version

---

app/_hub/kong-inc/aws-lambda/index.md

fix typo of aws.key and aws.secret to aws_key and aws_secret. also added to aws_key and aws_secret param reference that if aws_key and aws_secret are not set, it'll use EC2 instance's IAM role. Although that's mentioned in the "Notes" section, that's easy to miss and would be something that a user would expect to find when looking at aws_key and aws_secret.

updates for aws_key, aws_secret

---

app/deck/installation.md
app/deck/overview.md

Adding content based on https://github.com/Kong/deck/tree/master#features and https://github.com/Kong/deck/tree/master#compatibility. This was missed in doc migration as it lives outside the deck/docs folder in the repo.
Rephrased feature section descriptions for clarity/grammar.
Preview: 
https://deploy-preview-2208--kongdocs.netlify.app/deck/overview/#features
https://deploy-preview-2208--kongdocs.netlify.app/deck/overview/#compatibility
https://deploy-preview-2208--kongdocs.netlify.app/deck/installation/

docs(decK) Adding missing info from decK repo readme

---

app/2.1.x/go.md
app/2.1.x/plugin-development/custom-logic.md

This reverts commit edc93f2d31282d56c538eacef4252304024229e3.
response phase is planned to land in kong 2.2, not 2.1

Revert "Document response phase. (#2200)"

---

app/enterprise/2.1.x/release-notes.md

* Removing "Coming Soon" section from release notes
* Adding entry for K4K8s based on note in https://docs.konghq.com/enterprise/2.1.x/kong-for-kubernetes/deployment-options/
Preview: https://deploy-preview-2210--kongdocs.netlify.app/enterprise/2.1.x/release-notes/

docs(release notes) K4K8s release note

---

app/deck/guides/getting-started.md

`yaml` was accidentally entered as `yamz`, fixing it.
Preview: https://deploy-preview-2216--kongdocs.netlify.app/deck/guides/getting-started/

docs(deck) Fix typo in export example

---

app/_assets/stylesheets/page.less

Hero image for docs site isn't picking up the gradient properly in Firefox. Adjusting CSS to fix that.
Broken banner:
Fixed banner:

fix(css) Add Firefox styling for hero image

---

app/enterprise/1.3-x/developer-portal/helpers/cli.md
app/enterprise/1.5.x/developer-portal/helpers/cli.md
app/enterprise/2.1.x/developer-portal/helpers/cli.md

https://konghq.atlassian.net/browse/DOCS-1244
Used information from readme https://github.com/Kong/kong-portal-cli per @HenriPro. Verfied it matches cli output v 3.1.0 per slack convo: https://kongstrong.slack.com/archives/CDSTDSG9J/p1597418866006800?thread_ts=1597415934.002200&cid=CDSTDSG9J.
Updated 2.1.x to readme with parameter descriptions.
1.3 and 1.5 only deleted serve command.
https://deploy-preview-2228--kongdocs.netlify.app/enterprise/2.1.x/developer-portal/helpers/cli/#usage
https://deploy-preview-2228--kongdocs.netlify.app/enterprise/1.5.x/developer-portal/helpers/cli/#usage
https://deploy-preview-2228--kongdocs.netlify.app/enterprise/1.3-x/developer-portal/helpers/cli/#usage

removed serve command; update params doc on latest version

---

app/_hub/kong-inc/acme/index.md
app/_hub/kong-inc/aws-lambda/index.md
app/_hub/kong-inc/azure-functions/index.md
app/_hub/kong-inc/canary/index.md
app/_hub/kong-inc/exit-transformer/index.md
app/_hub/kong-inc/forward-proxy/index.md
app/_hub/kong-inc/graphql-rate-limiting-advanced/index.md
app/_hub/kong-inc/kafka-upstream/index.md
app/_hub/kong-inc/ldap-auth-advanced/index.md
app/_hub/kong-inc/mtls-auth/index.md
app/_hub/kong-inc/oauth2-introspection/index.md
app/_hub/kong-inc/oauth2/0.1-x.md
app/_hub/kong-inc/oauth2/1.0-x.md
app/_hub/kong-inc/oauth2/index.md
app/_hub/kong-inc/rate-limiting-advanced/index.md
app/_hub/kong-inc/request-validator/index.md
app/_hub/kong-inc/response-transformer-advanced/index.md
app/_hub/kong-inc/response-transformer/index.md
app/_hub/kong-inc/statsd-advanced/index.md
app/_hub/kong-inc/vault-auth/index.md
app/_layouts/extension.html

This PR introduces declarative YAML examples for all plugins. 
To make these examples work required the following:
1. Adjustments to the plugin template in /app/_layouts/extensions.html to parse declarative yaml examples.
2. Adjustments to the plugin template to position DB-less as a mode of deployment and not as equal to declarative config.
DB-less compatibility now sits in the right-hand table along with other plugin info, and links to the plugin compatibility table.
3. Fixes of the plugin values for accuracy and to fit templates.
4. Removal of API entity examples.
5. For third party plugins only: as these plugins need to be installed from an external source before using, the install info is now moved above the examples and general config.
All Kong Inc plugin examples have been tested; …

docs(plugins) Plugin examples overhaul project, part 1

---

app/enterprise/2.1.x/deployment/default-ports.md

Based on changes in https://github.com/Kong/docs.konghq.com/pull/2246. 
Adding default port that Control Plane listens on for Vitals data.
Preview: https://deploy-preview-2247--kongdocs.netlify.app/enterprise/2.1.x/deployment/default-ports/

docs(ee-ports) Add telemetry port

---

app/2.1.x/hybrid-mode.md

Unless `cluster_key` is an undocumented property, this is a typo and should be `cluster_cert`.

docs(hybrid) Fix cluster_cert property name

---

app/2.1.x/proxy.md
app/2.1.x/secure-admin-api.md

These were removed in Kong 1.0, along with the "API" entity,
/apis endpoint and friends.
Fixes #2120

docs(ce/2.1.x) remove references to upstream_*_timeout properties

---

app/_hub/kong-inc/datadog/index.md

https://konghq.atlassian.net/browse/DOCS-1046
3.0 plugin version not supported until 2.1.x release (tomorrow). I had hoped somehow it would be backported to 1.3.x and 1.5.x but not going to happen.
Update: release slipped. Merge when GA release goes live.
https://deploy-preview-2237--kongdocs.netlify.app/hub/kong-inc/datadog/

Datadog plugin v3 remove unsupported ee versions

---

app/_hub/kong-inc/route-by-header/index.md

https://konghq.atlassian.net/browse/DOCS-1266
Pointed out by Aaron Miller. Note that this plugin is deprecated but will exist on the hub for older versions for some time until its removal.
https://deploy-preview-2257--kongdocs.netlify.app/hub/kong-inc/route-by-header/#example

fix typo in deprecated Route by Header plugin

---

app/enterprise/2.1.x/release-notes.md

-- updated version used in release notes from 2.1.3.0 to 2.1.x
-- removed "What's New in the Docs", as creating own page.

docs (release-notes) update version used in title

---

app/2.1.x/hybrid-mode.md

docs(hybrid-mode) use "database" instead of "storage" when enabling

---

app/enterprise/2.1.x/deployment/hybrid-mode-setup.md
app/enterprise/2.1.x/property-reference.md

* Adding PKI mode as a method to configure Kong Enterprise in Hybrid mode 
* Adding hybrid mode properties to Enterprise config reference
* Adding table with all hybrid mode properties as a reference in the Enterprise Hybrid mode deployment doc
Mainly, pulling in changes made in https://github.com/Kong/docs.konghq.com/pull/2246, https://github.com/Kong/docs.konghq.com/pull/2199, and https://github.com/Kong/docs.konghq.com/pull/2184, and reworking the instructions to fit a guide format.
Preview:
https://deploy-preview-2249--kongdocs.netlify.app/enterprise/2.1.x/deployment/hybrid-mode-setup/
https://deploy-preview-2249--kongdocs.netlify.app/enterprise/2.1.x/property-reference/#hybrid-mode

docs(ee-hybrid) Add PKI mode and telemetry properties to Enterprise docs

---

app/enterprise/2.1.x/brain-immunity/overview.md

-- added introduction heading so that right page toc doesn't land on brain.

docs(brain-immunity) added overview heading

---

app/getting-started-guide/2.1.x/expose-services.md
app/getting-started-guide/2.1.x/improve-performance.md
app/getting-started-guide/2.1.x/load-balancing.md
app/getting-started-guide/2.1.x/manage-teams.md
app/getting-started-guide/2.1.x/overview.md
app/getting-started-guide/2.1.x/prepare.md
app/getting-started-guide/2.1.x/protect-services.md
app/getting-started-guide/2.1.x/secure-services.md

Updating the getting started guide to include declarative config examples. 
Previews:
[Overview](https://deploy-preview-2279--kongdocs.netlify.app/getting-started-guide/2.1.x/overview/#using-this-guide): updated the Using this Guide section to include decK
New decK tabs:
* [Prepare to Administer Kong](https://deploy-preview-2279--kongdocs.netlify.app/getting-started-guide/2.1.x/prepare/#verify-the-kong-gateway-configuration)
* Expose your Services: 
* [Add a Service](https://deploy-preview-2279--kongdocs.netlify.app/getting-started-guide/2.1.x/expose-services/#add-a-service)
* [Add a Route](https://deploy-preview-2279--kongdocs.netlify.app/getting-started-guide/2.1.x/expose-services/#add-a-service) 
Note: also added a sample of a `deck dump` command to the Route section as part of the …

docs(getting started guide) Declarative config examples and instructions

---

app/enterprise/2.1.x/brain-immunity/auto-generated-specs.md
app/enterprise/2.1.x/brain-immunity/install-configure.md
app/enterprise/2.1.x/brain-immunity/overview.md

-- moving the version compatibility table for Brain and Immunity to the installation and config topic.

docs(2.1.x) moving version info from B&I

---

app/enterprise/2.1.x/kong-for-kubernetes/deployment-options.md

Removing most mentions of the `kong-enterprise-k8s` image and turning the topic into mainly a DB-backed vs DB-less comparison. 
@rainest I think this is a start towards working through https://konghq.atlassian.net/browse/DOCS-897. Will work through the install topics in a subsequent PR with your input.

docs(k8s) Update deployment options for 2.1.x

---

app/_layouts/extension.html

This PR introduces Kubernetes examples for (almost) all plugins.
Examples are based on docs for [Custom Resource Definitions](https://github.com/Kong/kubernetes-ingress-controller/blob/main/docs/references/custom-resources.md), the [Kong Plugin Resource](https://github.com/Kong/kubernetes-ingress-controller/blob/main/docs/guides/using-kongplugin-resource.md), and on existing examples for declarative config. 
Most plugins examples should now work, other than the small list below (same issues as in https://github.com/Kong/docs.konghq.com/pull/2238):
- Response Rate Limiting: unique syntax that isn't used in other plugins, this needs a non-templated example
- Kafka upstream and Kafka Log: template syntax still needs adjustment for mapping values
- Exit transformer: Needs both declarative …

docs(plugins) Create Kubernetes example tabs

---

app/mesh/1.0.x/gettingstarted.md
app/mesh/1.0.x/install.md
app/mesh/1.0.x/installation/amazonlinux.md
app/mesh/1.0.x/installation/centos.md
app/mesh/1.0.x/installation/debian.md
app/mesh/1.0.x/installation/docker.md
app/mesh/1.0.x/installation/helm.md
app/mesh/1.0.x/installation/kubernetes.md
app/mesh/1.0.x/installation/macos.md
app/mesh/1.0.x/installation/openshift.md
app/mesh/1.0.x/installation/redhat.md
app/mesh/1.0.x/installation/ubuntu.md

* Adjusting formatting, language, grammar
* For Docker install: fixing Docker image name to point to Kong Mesh instead of Kuma (tested pulling them, they should be correct now)
* Adding tabs to installation pages that were missing them to match other installation pages
* Removing link to Helm and Helm chart tab, as Helm install doesn't exist yet. Will re-add when that changes.
Previews:
- [Getting Started](https://deploy-preview-2290--kongdocs.netlify.app/mesh/1.0.x/gettingstarted/) - included this topic because it's mainly about installation
- [Install](https://deploy-preview-2290--kongdocs.netlify.app/mesh/1.0.x/install/) - see all installation topics under this section

docs(mesh) Formatting and image name fixes for installation

---

app/_hub/index.html

Changing filter label from "Community Published" to "Third-Party". The current label confuses people, who assume that it's referring to Kong Community/Kong Gateway.
Aligns with term in docs.konghq.com/hub/plugins/overview/#terminology.
Preview: https://deploy-preview-2299--kongdocs.netlify.app/hub/

docs(plugins) Change third-party plugins filter label on Hub page

---

app/getting-started-guide/2.1.x/dev-portal.md
app/getting-started-guide/2.1.x/expose-services.md
app/getting-started-guide/2.1.x/improve-performance.md
app/getting-started-guide/2.1.x/load-balancing.md
app/getting-started-guide/2.1.x/manage-teams.md
app/getting-started-guide/2.1.x/prepare.md
app/getting-started-guide/2.1.x/protect-services.md
app/getting-started-guide/2.1.x/secure-services.md

* Change tab labels from "Using decK" to "Using decK (YAML)" for a bit more clarity (per Reza)
* add `sh` to cURL and HTTPie examples for syntax highlighting
* adjust cURL example syntax to be more consistent between topics (tested to make sure it works)
* fix: ` to ' in example

docs(getting started guide) Example formatting and decK tab titles

---

app/enterprise/2.1.x/deployment/hybrid-mode-setup.md
app/enterprise/2.1.x/deployment/hybrid-mode.md

Updating docs based on 2.1 internal enablement session (see https://konghq.atlassian.net/browse/DOCS-1238) and change made in https://github.com/Kong/docs.konghq.com/pull/2266. 
* Clarify how often config gets synced between CP and DP and whether that's customizable 
* Clarify what happens when you add a new data plane
* Add limitation on load balancing between CP and DP
* Change `storage` property to `database`
Previews:
https://deploy-preview-2302--kongdocs.netlify.app/enterprise/2.1.x/deployment/hybrid-mode-setup/
https://deploy-preview-2302--kongdocs.netlify.app/enterprise/2.1.x/deployment/hybrid-mode/

docs(ee-hybrid) Clarify CP/DP connection behavior

---

app/enterprise/1.3-x/developer-portal/theme-customization/emails.md
app/enterprise/1.5.x/developer-portal/theme-customization/emails.md
app/enterprise/2.1.x/developer-portal/theme-customization/emails.md

As noted by Gayle:
https://docs.konghq.com/enterprise/2.1.x/developer-portal/theme-customization/emails/
1.5.x and 1.3-x are also malformed.
- https://deploy-preview-2309--kongdocs.netlify.app/enterprise/2.1.x/developer-portal/theme-customization/emails/
- https://deploy-preview-2309--kongdocs.netlify.app/enterprise/1.5.x/developer-portal/theme-customization/emails/
- https://deploy-preview-2309--kongdocs.netlify.app/enterprise/1.3-x/developer-portal/theme-customization/emails/
@Jlawlzz I realize you are OOO this week, but at what point can we deprecate instructions for migrating portal to 1.3, which is approaching EOS https://docs.konghq.com/enterprise/2.1.x/support-policy/?

Fix numbering in dev portal topic

---

app/_hub/kong-inc/acme/0.2.2.md
app/_hub/kong-inc/acme/index.md

https://konghq.atlassian.net/browse/DOCS-1267 logged from Shane's PR https://konghq.atlassian.net/browse/DOCS-1162
https://deploy-preview-2311--kongdocs.netlify.app/hub/kong-inc/acme/#enable-the-plugin
services replaced service, needs to be plural.
This area is not in the generated template section.

acme plugin fix endpoint

---

app/_layouts/extension.html

From Shane's ticket https://konghq.atlassian.net/browse/DOCS-1162, this fixes subtickets:
https://konghq.atlassian.net/browse/DOCS-1272
https://konghq.atlassian.net/browse/DOCS-1274
https://konghq.atlassian.net/browse/DOCS-1275
(dupe tickets, turns out due to template links-Lena would've spotted it right away--thanks for the links to the template areas, Lena)
Sample direct links to test:
Click on Consumer link:
https://deploy-preview-2312--kongdocs.netlify.app/hub/kong-inc/proxy-cache/#enabling-the-plugin-on-a-consumer
Click on Route link:
https://deploy-preview-2312--kongdocs.netlify.app/hub/kong-inc/canary/#enabling-the-plugin-on-a-route

fix consumer and route links in plugin template

---

app/_hub/kong-inc/acl/index.md

https://konghq.atlassian.net/browse/DOCS-1162 subticket of https://konghq.atlassian.net/browse/DOCS-1271 update ACL usage link per Shane, the FAQ anchor doesn't work and it's better just to to link to plugin auth section as Shane suggested.
https://deploy-preview-2314--kongdocs.netlify.app/hub/kong-inc/acl/ first paragraph addresses main ticket issue

ACL link update; other fixes and copy edits

---

app/_hub/kong-inc/azure-functions/0.1-x.md
app/_hub/kong-inc/azure-functions/index.md

https://konghq.atlassian.net/browse/DOCS-1278 fix placeholder function name per Shane's parent epic ticket https://konghq.atlassian.net/browse/DOCS-1162.
Now both versions of the plugin properly display the placeholder. At least it worked in my local build ...
https://deploy-preview-2319--kongdocs.netlify.app/hub/kong-inc/azure-functions/0.1-x.html

fix azure function name field

---

.github/workflows/build-test.yml

We've had a few cases in the recent past where a build fails due to errors, then retries until it reaches the max default time limit of 6 hours. Setting a 30 minute build time limit to avoid this.

docs(build) Set build action time limit

---

app/1.1.x/db-less-and-declarative-config.md
app/1.2.x/db-less-and-declarative-config.md
app/1.3.x/db-less-and-declarative-config.md
app/1.4.x/db-less-and-declarative-config.md
app/1.5.x/db-less-and-declarative-config.md
app/2.0.x/db-less-and-declarative-config.md
app/2.1.x/db-less-and-declarative-config.md

* fix typo in DB-less and Declarative Configuration guide
* docs versions: 1.1, 1.2, 1.3, 1.4, 1.5, 2.0, 2.1

docs(ee/guides) fix declarative typo

---

app/_assets/stylesheets/page.less
app/_assets/stylesheets/pages/extension.less

Our docs have varying designs for alerts based on who wrote the CSS when, and for what product. Aligning the styles to match the left-border style in Kongponents: https://kongponents.netlify.app/components/alert.html#left-border.
Examples of different styles currently existing in the docs: 
Previews of unified styles:
https://deploy-preview-2325--kongdocs.netlify.app/hub/peter-evans/paseto
https://deploy-preview-2325--kongdocs.netlify.app/2.1.x/getting-started/configuring-a-grpc-service/

docs(styles) Unifying alert styles across docs

---

app/enterprise/2.1.x/deployment/hybrid-mode-setup.md

lua_ssl_trusted_certificate needs to be set to the CA cert on the data plane. 
added /<path-to-file>/ to examples, especially for the kong.conf examples
changed examples of ca cert to use .pem extension to make clear those are typically PEM format certs.
when i was playing around with configs on the data node, it looked like cluster_ca_cert wasn't actually required; lua_ssl_trusted_certificate was. ideally this should be fixed so that cluster_ca_cert is where Kong looks for the CA cert because lua_ssl_trusted_certificate is buried in the MISCELLANEOUS section of kong.conf. but for now, i think the docs should just be fixed so it works and users don't get too confused. :)

Add required param to examples

---

app/_hub/kong-inc/kong-terraform-aws/index.md

https://konghq.atlassian.net/browse/DOCS-1280 make link to GitHub readme work. Part 1 of ticket to make the link to GitHub work. Part 2 pull readme docs into plugin hub. Subticket of Shane's plugins ticket https://konghq.atlassian.net/browse/DOCS-1162.
https://deploy-preview-2327--kongdocs.netlify.app/hub/kong-inc/kong-terraform-aws/#documentation

Terraform integration module 

---

app/_data/docs_nav_ee_2.1.x.yml

Extra dashes in `- items` entries were breaking the ToC structure.
Relates to: https://konghq.atlassian.net/browse/DOCS-1320

docs(ToC) Fix RBAC and Admins sections in Kong Manager

---

app/_hub/kong-inc/session/index.md

https://konghq.atlassian.net/browse/DOCS-1324
DOCS-1324 Document interdependency for Session Plugin cookie_samesite None and cookie_secure true
Added verbiage recommended by @aaronhmiller to description:
`None` requires the Secure attribute in latest browser versions.
https://deploy-preview-2334--kongdocs.netlify.app/hub/kong-inc/session/
Updates:
Make live links:

Clarify cookie_samesite None for Sessions plugin

---

app/_assets/stylesheets/navtabs.less

Remove awkward whitespace after navtab sections.
For comparison, see tab whitespace in the following install topic:
Old: https://docs.konghq.com/enterprise/2.1.x/kong-for-kubernetes/install/
New: https://deploy-preview-2331--kongdocs.netlify.app/enterprise/2.1.x/kong-for-kubernetes/install/

docs(style) Adjust padding for navtabs

---

app/_assets/stylesheets/pages/docs.less

The H2 headers are especially intense in the docs. This is only a slight adjustment, to make sure the Admin API docs don't get  confusing, however, it should help the rest of the doc site - EE installation topics in particular.

docs(style) Adjust headers to less imposing size

---

app/_assets/stylesheets/page.less
app/_assets/stylesheets/pages/docs.less

Currently, the docs site has a problem with nested lists, in that unordered lists are implicitly counted as part of the step count. For example:
```
1. Example
2. List
* Here's a point
* And another one
5. List count doesn't continue at 3, but instead assumes the bullet points were part of it.
```
With this fix, it should all work as intended:
```
1. Example
2. List
* Point
* Point
3. Proper numbering continues
```
Also fixing font size to match across lists, whether the `<li>` has a `<p>` tag or not. Previous behaviour with two different font sizes:
https://docs.konghq.com/getting-started-guide/2.1.x/manage-teams/

docs(styles) Fixing numbering issue with nested unordered lists 

---

app/_assets/stylesheets/page.less

Adjusting links for visibility/accessibility.
* Changed links in body text to lighter blue to match existing headers on landing pages
* Adjusted plugin hub page nav for cleaner look with blue for off-page links, grey for on-page links (same colors/weights as nav on main docs)
Old:
New:

docs(styles) Adjust link contrast

---

app/_hub/kong-inc/response-ratelimiting/index.md

https://konghq.atlassian.net/browse/DOCS-1277 from Shane's parent ticket https://konghq.atlassian.net/browse/DOCS-1162
Description: It'd be nice to add a curl example at https://docs.konghq.com/hub/kong-inc/response-ratelimiting/#configuring-quotas
https://deploy-preview-2328--kongdocs.netlify.app/hub/kong-inc/response-ratelimiting/#configuring-quotas
Requested syntax verification from reviewers. Links not jumping to proper location, so screenshot:

Add curl example for quotas Response Rate Limiting plugin 

---

app/_layouts/extension.html

Add `kubernetes.io/ingress.class: kong` annotations to Ingress, KongConsumer, and global KongClusterPlugin examples. [As of controller 0.10.0](https://github.com/Kong/kubernetes-ingress-controller/blob/master/CHANGELOG.md#0100---20200915), this annotation is required by default on these resources, and our examples should include them as such. Adding this annotation
does not create issues for older versions--they were simply more permissive about when they permitted resources that lacked them by default, but still work fine when the annotation is present.
Minor note is that this annotation should have a different value when using [a non-standard class](https://github.com/Kong/kubernetes-ingress-controller/blob/main/docs/concepts/ingress-classes.md#when-to-use-a-custom-class), e.g. …

Add class annotations to K8S plugin examples

---

app/enterprise/2.1.x/developer-portal/administration/application-registration/enable-application-registration.md
app/enterprise/2.1.x/developer-portal/administration/application-registration/index.md
app/enterprise/2.1.x/developer-portal/administration/application-registration/okta-config.md
app/enterprise/2.1.x/plugins/oidc-okta.md

https://konghq.atlassian.net/browse/DOCS-1281 See Fel's comments linked in the ticket
Need to provide standalone config instructions for auth plugins (configured in conjunction with app reg plugin).
Part 1 PR make clear OAuth2 plugin does not support hybrid mode. Part 2 will provide OAuth2-specific instructions.
https://deploy-preview-2276--kongdocs.netlify.app/enterprise/2.1.x/developer-portal/administration/application-registration/
Also need to make clear OAuth2 plugin does not support hybrid mode. See highlighted updates:
^ Outdated above but better now after Lena's feedback
Added more links in next steps area of app reg plugin (Kong Manager, not hub) docs:
https://deploy-preview-2276--kongdocs.netlify.app/enterprise/2.1.x/developer-portal/administration/applicatio …

Application Registration Documentation Enhancements Part 1

---

app/enterprise/2.1.x/release-notes.md

-- changed in intro paragraph 2.1.3.0 to 2.1.x, to be more generic, as the versioning is getting confusing with patch releases (for example 2.1.4.0 just released).

docs(release notes) update 2.1.x release info in intro

---

app/_hub/kong-inc/exit-transformer/index.md

https://konghq.atlassian.net/browse/DOCS-1279 subticket in Shane's epic https://konghq.atlassian.net/browse/DOCS-1162 add curl examples in demo section, currently only httpie
Other tickets in this PR:
https://konghq.atlassian.net/browse/DOCS-1323 update docs for MIMEtype example
https://konghq.atlassian.net/browse/DOCS-1322 per https://konghq.atlassian.net/browse/FTI-1743
- remove config.handle_admin was removed 1.5.3. 
Before: 
(Current plugin version indicates 1.5.x. Actual internal plugin version is 0.2.3. Plugin versions policy TBD.)
- clarify 4xx and 5xx response codes. Legacy content implies only 404 and 400 responses are transformed. List responses as requested by Karl K. 
https://deploy-preview-2332--kongdocs.netlify.app/hub/kong-inc/exit-transformer/#transforming-4xx-and-5xx-respo …

Exit Transformer cURL examples in demo section; remove obsolete handle_admin field; update for errs by mimetype

---

app/_hub/kong-inc/response-transformer-advanced/1.3-x.md

https://konghq.atlassian.net/browse/DOCS-1351 ticket moved from FTI-1531
This PR removes the rename header field from version 1.3-x since it wasn't available in that version.
Schema link: https://github.com/Kong/kong-plugin-response-transformer-advanced/blob/master/kong/plugins/response-transformer-advanced/schema.lua
Ticket summary:
> Problem Statement:
> 
> The documentation lists version 1.3-x as the latest version of the plugin but that is actually incorrect because 0.3.3 seems to have been released with Kong 1.5.0.0:
> 
> https://konghq.atlassian.net/wiki/spaces/FTT/pages/8356124/Kong+Enterprise+-+Changelog+Features+Release+Schedule#KongEnterprise-Changelog,Features&ReleaseSchedule-KongEnterprise1.5.0.0
> 
> The latest version introduced the header rename feature which incorrectly is …

Response Transformer Advanced plugin correction

---

app/_hub/kong-inc/ldap-auth-advanced/index.md

https://konghq.atlassian.net/browse/DOCS-1269 Shane requested more information and an example for LDAP auth header. This ticket was a subticket of https://konghq.atlassian.net/browse/DOCS-1162.
While I was in there, also did some copy editing and added in missing defaults and examples to match the schema and whatever the basic LDAP plugin has. The copy edits from this PR can be ported to the community LDAP plugin after this one is reviewed and approved.
Direct link main entry point:
https://deploy-preview-2357--kongdocs.netlify.app/hub/kong-inc/ldap-auth-advanced/
Auth header example (added text highlighted in yellow):
See https://deploy-preview-2357--kongdocs.netlify.app/hub/kong-inc/ldap-auth-advanced/#usage.
Additional ticket: https://konghq.atlassian.net/browse/DOCS-1348 Added more …

LDAP Auth Header & Ports updates

---

app/_hub/kong-inc/mtls-auth/1.3-x.md
app/_hub/kong-inc/mtls-auth/index.md

Based on issue in https://konghq.atlassian.net/browse/FTI-1521 and https://konghq.atlassian.net/browse/DOCS-1043. 
* Providing declarative config instructions by segmenting mapping section into tabs
* Expanding the parameter table below it to include the `id` field required in declarative config
* Removing unused links and linking to Enterprise instead of Community doc
* Minor formatting cleanup
(Formatting cleanup has to happen along the way, as there's no real other way for docs team to catch up on all of the content that needs cleanup)
Preview (no difference between versions): 
https://deploy-preview-2365--kongdocs.netlify.app/hub/kong-inc/mtls-auth/
https://deploy-preview-2365--kongdocs.netlify.app/hub/kong-inc/mtls-auth/1.3-x.html

docs(plugins/mtls-auth) Configuring mtls-auth-credentials with declarative config

---

app/enterprise/1.5.x/deployment/installation/centos.md
app/enterprise/1.5.x/deployment/installation/rhel.md
app/enterprise/1.5.x/deployment/installation/ubuntu.md

Backporting the EE 2.1 yum docs changes to EE 1.5: https://github.com/Kong/docs.konghq.com/pull/2321

docs(ee/yum-install) remove epel-release install instruction

---

app/_layouts/extension.html

Based on https://konghq.atlassian.net/browse/DOCS-1358.
The `plugins.konghq.com` annotation has been replaced with `konghq.com/plugins`, back in 0.8. 
No doc versioning needed, this annotation should've been used originally.
For reference, see https://github.com/Kong/kubernetes-ingress-controller/pull/873/files#diff-ab7186fbfc65b74973321a0a1d7f0e7c3080bffcf3fa4d3a91eb1555b072d3e0

docs(plugins) Update plugin annotations in k8s examples

---

app/2.2.x/loadbalancing.md

2.2 now allows updating and removing targets via the admin-api.  Remove notes about previous caveats and document new method.

feat(balancer) target objects can now be PATCHed and DELETEd

---

app/_includes/md/1.5.x/bintray-and-license.md
app/_includes/md/2.1.x/bintray-and-license.md
app/enterprise/1.5.x/deployment/access-license.md
app/enterprise/1.5.x/deployment/installation/amazon-linux-2.md
app/enterprise/1.5.x/deployment/installation/amazon-linux.md
app/enterprise/1.5.x/deployment/installation/centos.md
app/enterprise/1.5.x/deployment/installation/docker.md
app/enterprise/1.5.x/deployment/installation/rhel.md
app/enterprise/1.5.x/deployment/installation/ubuntu.md
app/enterprise/1.5.x/introduction.md
app/enterprise/1.5.x/kong-for-kubernetes/install-on-kubernetes.md
app/enterprise/1.5.x/kong-for-kubernetes/install.md
app/enterprise/2.1.x/deployment/access-license.md
app/enterprise/2.1.x/deployment/installation/amazon-linux-2.md
app/enterprise/2.1.x/deployment/installation/amazon-linux.md
app/enterprise/2.1.x/deployment/installation/centos.md
app/enterprise/2.1.x/deployment/installation/docker.md
app/enterprise/2.1.x/deployment/installation/rhel.md
app/enterprise/2.1.x/deployment/installation/ubuntu.md
app/enterprise/2.1.x/introduction.md
app/enterprise/2.1.x/kong-for-kubernetes/install-on-kubernetes.md
app/enterprise/2.1.x/kong-for-kubernetes/install.md

Based on https://konghq.atlassian.net/browse/DOCS-1252.
Trying to settle some of the confusion about where to find your license. The main culprit was the mention of Bintray and licenses with no context in the installation steps (people tend to ignore the prereqs). 
* Turned license prereq into an include file that's now reused for every installation doc.
* Updated "Accessing your License" with a prereq section and a link to trial/demo info.
* Updated trial section of the Introduction to Kong Enterprise topic.
* Some cleanup to installation docs - typos, formatting of the license and Bintray sections, turning URLs into actual links, turning notes into note-formatted content. 
Will backport into 1.5.x (and maybe into 1.3.x) once phrasing is reviewed and finalized.
Preview:
* [Introduction > …

docs(ee-license) Clarify and update license and Bintray doc

---

app/enterprise/2.1.x/developer-portal/configuration/authentication/sessions.md

docs(ee/dev-portal) clarify sessions instructions
* The docs mention tell you to use cookie_samesite when using different domains. 
* Rather you should be using cookie_domain using the instruction in the domain section further below. And only subdomains are supported, do not believe completely different domain would work. 
* Slack conversation outlining this configuration: https://kongstrong.slack.com/archives/CAW1MAFLZ/p1585170652026600

Update sessions.md in docs for kong-ee 2.1.x

---

app/_assets/stylesheets/base.less
app/_assets/stylesheets/page.less
app/_assets/stylesheets/syntax.less
app/_assets/stylesheets/variables.less
jekyll-dev.yml

Two main goals here: update our variables with colours from [Kongponents](https://kongponents.netlify.app/style-guide/colors.html), and make the syntax highlighting less red.
* Change inline text highlighting from red to grey
* Add Kong colour variables
* Using the Kong colour variables as much as possible, redo syntax highlighting theme for codeblocks
* Change codeblock background to white for contrast in alert blocks
* Enable syntax highlighter for jekyll-dev
Previews - anywhere with codeblocks or inline code, e.g.:
https://deploy-preview-2381--kongdocs.netlify.app/hub/kong-inc/application-registration/
https://deploy-preview-2381--kongdocs.netlify.app/enterprise/2.1.x/admin-api/
https://deploy-preview-2381--kongdocs.netlify.app/getting-started-guide/2.1.x/prepare/ - see codeblocks …

docs(styles) Code syntax highlighting

---

app/_hub/kong-inc/ldap-auth-advanced/index.md
app/_hub/kong-inc/ldap-auth/index.md

https://konghq.atlassian.net/browse/DOCS-1353
Per https://konghq.atlassian.net/browse/DOCS-1269 as part of Shane's epic ticket https://konghq.atlassian.net/browse/DOCS-1162
This content was already approved by Darren and Lena in the advanced ldap plugin.
Parity as much as possible between community and enterprise docs.
https://deploy-preview-2380--kongdocs.netlify.app/hub/kong-inc/ldap-auth/

port LDAP advanced plugin hub improvements to community plugin

---

app/_hub/kong-inc/file-log/0.1-x.md
app/_hub/kong-inc/file-log/index.md

Speaking to a number of people and hearing from users the consensus seems to be that the current warning against the file-log plugin is too strong. In most deployment scenarios it does not affect performance.
Additionally, it only applies when writing to actual files on a slow (e.g. spinning) disk. Many times, logs might be written to virtual files, e.g. stdout/stderr - especially in Kubernetes. In those cases, blocking I/O is not a concern.
So I think it is appropriate to soften - but not remove - the warning and add a note about streams.

fix(file-log) Soften performance warning

---

app/_assets/stylesheets/pages/docs.less
app/_assets/stylesheets/pages/extension.less

* Change list style to bullets instead of circles
* Set paragraph font size to inherit from the list element above it to avoid awkward font size changes between lines
Previously, I had changed the list font size to match the rest of the content; this was overwritten in another PR. This solution ends up being a better one, as it doesn't set an explicit size, and instead nested paragraph elements pick up the font sizes they're supposed to have.
**Preview:** any page with a list. 
Here's a sample doc with both ordered and unordered lists:
https://deploy-preview-2387--kongdocs.netlify.app/getting-started-guide/2.1.x/manage-teams/
Plugin doc samples:
https://deploy-preview-2387--kongdocs.netlify.app/hub/yesinteractive/kong-jwt2header/

docs(style) List adjustments part 2

---

app/_assets/stylesheets/page.less

At some point, this started happening:
* Fixing it so that they're at least side-by-side.
* Adjusting media screen size to match the size set for the feedback widget, so they shift at the same screen size.

docs(styles) Fix scroll-to-top button overlap with feedback widget

---

app/_data/extensions/kong-inc/ip-restriction/versions.yml
app/_hub/kong-inc/ip-restriction/1.0-x.md
app/_hub/kong-inc/ip-restriction/index.md

https://konghq.atlassian.net/browse/DOCS-1356
- New index file for 2.0.x allow/deny https://deploy-preview-2385--kongdocs.netlify.app/hub/kong-inc/ip-restriction/
- Reconstructed version for 1.0.x that uses whitelist/blacklist instead of allow/deny https://deploy-preview-2385--kongdocs.netlify.app/hub/kong-inc/ip-restriction/1.0-x.html
- first version of the plugin  https://deploy-preview-2385--kongdocs.netlify.app/hub/kong-inc/ip-restriction/0.1-x.html

IP Restriction plugin fixes for whitelist/blacklist allow/deny versions

---

app/mesh/1.0.x/installation/helm.md

Adding installation docs for Kong Mesh using Helm. 
Ticket: https://konghq.atlassian.net/browse/DOCS-1364
References: 
https://kong.github.io/kong-mesh-charts/
https://kuma.io/docs/0.7.2/installation/helm/
Preview: https://deploy-preview-2398--kongdocs.netlify.app/mesh/1.0.x/installation/helm/

docs(mesh) Install documentation for Helm

---

app/_includes/md/mesh/1.0.x/install-universal-quickstart.md
app/_includes/md/mesh/1.0.x/install-universal-run.md
app/_includes/md/mesh/1.0.x/install-universal-verify.md
app/mesh/1.0.x/installation/amazonlinux.md
app/mesh/1.0.x/installation/centos.md
app/mesh/1.0.x/installation/debian.md
app/mesh/1.0.x/installation/docker.md
app/mesh/1.0.x/installation/kubernetes.md
app/mesh/1.0.x/installation/macos.md
app/mesh/1.0.x/installation/openshift.md
app/mesh/1.0.x/installation/redhat.md
app/mesh/1.0.x/installation/ubuntu.md

Issue tracked in https://konghq.atlassian.net/browse/DOCS-1304.
Previous state of the install docs: we gave users some vague instructions, expecting them to cross-reference the Kuma docs. For a better (less confusing) user experience, this PR brings all the installation instructions over from the Kuma doc site and adjusts them for Kong Mesh. 
For reference, see each topic in Kuma docs, eg https://kuma.io/docs/0.7.2/installation/kubernetes/.
**Preview:** all topics under https://deploy-preview-2368--kongdocs.netlify.app/mesh/1.0.x/install/ except Helm.
Ubuntu, CentOS, MacOS, Debian, Amazon Linux, and Redhat installation instructions are exactly the same after downloading the binaries. Therefore, they're documented through `include` sections. 
These installation topics have some differences …

Kong Mesh installation docs

---

app/enterprise/1.5.x/kong-for-kubernetes/install-on-kubernetes.md
app/enterprise/2.1.x/kong-for-kubernetes/install-on-kubernetes.md

Fixes the command to create the session config secret. `admin_gui_session_conf` and `portal_session_conf` are actually files that have been created in the instructions just before.

fix(k8s) Improvements to enterprise K8s installation page

---

app/_hub/kong-inc/forward-proxy/index.md

https://konghq.atlassian.net/browse/DOCS-869
https://deploy-preview-2401--kongdocs.netlify.app/hub/kong-inc/forward-proxy/#parameters
Question for reviewers (@gszr or @RobSerafini): I'm not sure which doc versions this field should be in? It looks like it was added 2 years ago per blame. Also, is port 80 appropriate for the existing port example?

Forward proxy plugin missing https_verify field description

---

app/_assets/stylesheets/cookie-policy.less
app/_layouts/docs-v2.html

* Fix issue of cookie banner appearing underneath other elements:
* Remove scroll-to-top button from landing pages, positioning is off without the feedback widget there.
Preview:
* Scroll down any landing page, only the cookie banner should be there: https://deploy-preview-2406--kongdocs.netlify.app
* Without dismissing the cookie banner, also scroll down on any page one level down, eg https://deploy-preview-2406--kongdocs.netlify.app/2.1.x/admin-api/. Cookie banner should appear overtop other icons.

fix(styles) Bring cookie banner to top

---

app/_assets/stylesheets/page.less
app/_hub/plugins/compatibility/index.md

Issue: code blends into table rows, now that it's no longer bright red. (https://konghq.atlassian.net/browse/DOCS-1370)
* Remove zebra striping from tables and simplify.
* Adjust headers of plugin compat table
Previews:
* Table without code: https://deploy-preview-2407--kongdocs.netlify.app/getting-started-guide/2.1.x/overview/
* Table with code: https://deploy-preview-2407--kongdocs.netlify.app/hub/kong-inc/basic-auth/
* Table inside a step: https://deploy-preview-2407--kongdocs.netlify.app/enterprise/2.1.x/kong-for-kubernetes/install-on-kubernetes/#step-7-prepare-kongs-configuration-file

docs(styles) Adjust table styling for better contrast with code

---

app/enterprise/2.1.x/support-policy.md

-- changing supported version 2.1.3.x to 2.1.x in table, as we now have 2.1.4.0 released
-- in 2.2, this page will most likely be updated by Shane with current Support policies

docs(version support) change 2.1.3.x to 2.1.x

---

app/enterprise/2.1.x/brain-immunity/auto-generated-specs.md
app/enterprise/2.1.x/brain-immunity/changelog.md
app/enterprise/2.1.x/brain-immunity/install-configure.md
app/enterprise/2.1.x/brain-immunity/overview.md
app/enterprise/2.1.x/brain-immunity/service-map.md
app/enterprise/2.1.x/brain-immunity/troubleshooting.md

* added Important note that Kong Brain is deprecated and not available in Kong Enterprise 2.1.4.0.
See:
https://deploy-preview-2399--kongdocs.netlify.app/enterprise/2.1.x/brain-immunity/overview/
https://deploy-preview-2399--kongdocs.netlify.app/enterprise/2.1.x/brain-immunity/install-configure/
https://deploy-preview-2399--kongdocs.netlify.app/enterprise/2.1.x/brain-immunity/service-map/
https://deploy-preview-2399--kongdocs.netlify.app/enterprise/2.1.x/brain-immunity/auto-generated-specs/
https://deploy-preview-2399--kongdocs.netlify.app/enterprise/2.1.x/brain-immunity/troubleshooting/
https://deploy-preview-2399--kongdocs.netlify.app/enterprise/2.1.x/brain-immunity/changelog/

docs(brain) added important brain deprecated

---

app/enterprise/2.1.x/release-notes.md

-- added Deprecated section to indicate "Kong Brain is deprecated and not available in Kong Enterprise version 2.1.4.0 and later."
-- in Changelog section, changed 2.1.3.0 to 2.1.x to keep consistent with other references of this version.
See https://deploy-preview-2397--kongdocs.netlify.app/enterprise/2.1.x/release-notes/#deprecated-features

docs(release notes) added "Deprecated" section

---

app/enterprise/changelog.md

* Update changelog that Kong Brain is deprecated and not available in Kong Enterprise 2.1.4.0 and later.
See preview: https://deploy-preview-2395--kongdocs.netlify.app/enterprise/changelog/#deprecated-features

docs(changelog) Kong Brain deprecated in 2.1.4.0

---

app/_data/kong_versions.yml

Updating version for installations.
Preview: https://deploy-preview-2412--kongdocs.netlify.app/mesh/latest_version/ - should just see the new version number and nothing else.

Release: Kong Mesh 1.0.4

---

app/_hub/kong-inc/proxy-cache-advanced/index.md
app/_hub/kong-inc/proxy-cache/index.md

https://konghq.atlassian.net/browse/DOCS-335
Added extra warning underneath params table. 
Direct review links (see the warning underneath the parameters table):
- https://deploy-preview-2402--kongdocs.netlify.app/hub/kong-inc/proxy-cache/#parameters
- https://deploy-preview-2402--kongdocs.netlify.app/hub/kong-inc/proxy-cache-advanced/#parameters

Proxy Cache plugins: add extra warning about exact content type matches

---

app/2.2.x/hybrid-mode.md
app/_data/extensions/kong-inc/correlation-id/versions.yml
app/_data/extensions/kong-inc/grpc-web/versions.yml
app/_hub/kong-inc/correlation-id/0.1.x.md
app/_hub/kong-inc/correlation-id/1.0.0.md
app/_hub/kong-inc/correlation-id/1.0.x.md
app/_hub/kong-inc/correlation-id/index.md
app/_hub/kong-inc/grpc-web/0.1.x.md
app/_hub/kong-inc/grpc-web/index.md
app/_hub/kong-inc/rate-limiting/index.md

- Updated hybrid-mode docs with new data_planes path
- Update correlation-id plugin version
- Added grpc-web new config param
- Added new possible value to limit_by config param

docs(*) missing docs for 2.2 release

---

app/_data/extensions/kong-inc/grpc-gateway/versions.yml
app/_hub/kong-inc/grpc-gateway/index.md
app/_hub/kong-inc/grpc-web/0.1.x.md
app/_hub/kong-inc/grpc-web/index.md

https://konghq.atlassian.net/browse/DOCS-1392 per slack convo, plugins not released until version 2.1 both KE/CE
https://konghq.atlassian.net/browse/DOCS-1376 menu should be 0.1.x
https://deploy-preview-2424--kongdocs.netlify.app/hub/kong-inc/grpc-gateway/
https://deploy-preview-2424--kongdocs.netlify.app/hub/kong-inc/grpc-web/
https://deploy-preview-2424--kongdocs.netlify.app/hub/kong-inc/grpc-web/0.1.x.html

Correct version compatibility for gRPC plugins

---

app/2.2.x/configuration.md

There were some changes on the generated configuration.md file for 2.2.0

regenerate configuration.md for 2.2

---

app/enterprise/changelog.md

* Add warning to say we're not providing beta docs, only docs for GA.
* Remove links to Enterprise docs, as those docs aren't updated.
Preview: https://deploy-preview-2426--kongdocs.netlify.app/enterprise/changelog/

docs(changelog) Add note about no docs for 2.2 beta

---

app/getting-started-guide/2.1.x/dev-portal.md
app/getting-started-guide/2.1.x/expose-services.md
app/getting-started-guide/2.1.x/improve-performance.md
app/getting-started-guide/2.1.x/load-balancing.md
app/getting-started-guide/2.1.x/overview.md
app/getting-started-guide/2.1.x/prepare.md
app/getting-started-guide/2.1.x/protect-services.md
app/getting-started-guide/2.1.x/secure-services.md

Based on issue https://konghq.atlassian.net/browse/DOCS-1388.
The getting started guide does not sufficiently explain how to follow Admin API instructions and use provided endpoints for free trial users. This is a big problem, as users are constantly getting lost and having to go back and forth with support for the same questions, over and over.
I tried out a couple of suggestions to restructure and clear up this content, including moving the instructions for setting up for free trials into [Expose your Services](https://docs.konghq.com/getting-started-guide/2.1.x/expose-services/). It ended up obscuring the content and not really fitting into the theme of the topic, so I left it in [Prepare to Administer Kong Gateway](https://docs.konghq.com/getting-started-guide/2.1.x/prepare/), but …

docs(getting-started) Rework instructions for free trials

---

app/_hub/_init/my-extension/index.md
app/_hub/kong-inc/basic-auth/index.md
app/_layouts/extension.html

Plugin docs don't list config parameter datatypes, which is a standard piece of information in config reference documentation.
* Adding "datatype" field to plugin template and doc layout, so that if a datatype is specified for a parameter, it'll appear below the config parameter name.
* Testing this out with the Basic Auth plugin
[Basic Auth](https://deploy-preview-2428--kongdocs.netlify.app/hub/kong-inc/basic-auth/) plugin - see parameter table
* Based the `name` and `id` datatypes on our PDK doc: 
https://docs.konghq.com/2.2.x/plugin-development/plugin-configuration/#schemalua-specifications
* There's a lot of work to do to actually add the datatype field to the doc for each plugin; ideally, it should be automated.
* Will also update autogenerated example parser once this is applied to …

docs(plugins) Introduce datatype field for plugin template

---

app/_hub/kong-inc/prometheus/index.md

Using the status API is probably the preferred way of scraping metrics, and it was not documented, so added.

plugin(prometheus) document status api endpoint

---

app/sitemap.xml

* sitemap priority levels updated from 2.0/1.0 (for latest vs previous version pages) to 1.0/0.5 (as priority should be set at a maximum of 1.0)- this should help balance SEO results to prioritize most recent versions

update sitemap priority levels

---

app/_includes/nav.html

Docs ticket: https://konghq.atlassian.net/browse/DOCS-1133
There's no reason that docs should open in a new window or tab - might make sense on the main konghq.com site, but for the docs subdomain, it's logical to keep the user in the same tab as they navigate through the docs.

fix(docs-nav) Stop links to docs from opening in new window/tab

---

app/_data/extensions/kong-inc/aws-lambda/versions.yml
app/_hub/kong-inc/aws-lambda/3.4.x.md

https://konghq.atlassian.net/browse/DOCS-1412
This was in the 2.2 CE changelog https://github.com/Kong/kong/pull/6379 so some updates have been missed. 
This PR removes the statement that isBased64Encoded flag is not supported/implemented, and bumps the version to match 3.5.x. This plugin consistently is versioned by its internal handler version.
Since CE is already released, and EE beta released, and this is a minor change, I just made the PR off of master rather than the private repo.
```
aws-lambda 3.5.0 22-Sep-2020
feat: adding support for 'isBase64Encoded' flag in Lambda function responses
fix: respect skip_large_bodies config setting even when not using
AWS API Gateway compatibility
```
https://deploy-preview-2443--kongdocs.netlify.app/hub/kong-inc/aws-lambda/ …

Update AWS Lambda CE/EE 2.2 

---

app/_assets/stylesheets/page.less

Mirroring a more standard style; also, feedback from Marco P is that he doesn't like the tiny font used in alert panels.
Adjusting the font size to match nested list size - 1 point smaller than body text instead of 4 points.

docs(styles) Adjust font to more readable size (matching nested lists)

---

app/getting-started-guide/2.1.x/manage-teams.md

If you run the command as-is, you get the following error:
```
"docker exec" requires at least 2 arguments.
```
Fixing it, and formatting the codeblock for readability.
Preview:
https://deploy-preview-2441--kongdocs.netlify.app/getting-started-guide/2.1.x/manage-teams/#turn-on-rbac

fix(getting-started) Add missing argument for enabling RBAC with Docker

---

app/_data/docs_nav_2.1.x.yml
app/_data/docs_nav_2.2.x.yml
autodoc-nav/docs_nav_2.1.x.yml.head.in

This error was introduced in 2.1.x; before that, the nav was correctly indented (see [2.0.x](https://docs.konghq.com/2.0.x/getting-started/introduction/) vs [2.1.x](https://docs.konghq.com/2.1.x/getting-started/introduction/)). 
I'm guessing that we missed something on the autodoc side when updating the nav originally, but I couldn't figure out how the
`.yml.head.in` file gets generated - and, I noticed that the file is also missing for 2.2? @kikito, what's the role of this file, and is there somewhere else that we need to update anytime nav changes are made (not including Admin API and PDK)?
Preview: 
Look at the CE table of contents under Guides & References. Quickstart should have five nested topics:
https://deploy-preview-2444--kongdocs.netlify.app/2.2.x/getting-started/introduction/ …

fix(toc) Nest quickstart topics into quickstart guide section

---

app/_assets/stylesheets/copy-code-snippet.less
app/_assets/stylesheets/navtabs.less
app/_assets/stylesheets/page.less
app/enterprise/2.1.x/deployment/installation/kong-for-kubernetes.md

- Add support for tabbed codeblocks
- make copy icon transparent so it doesn't obscure code in longer lines
Same as current navtabs, except you can only include codeblocks in them. Use `navtabs` with the `codeblock` class, eg:
Output:
I'm not sure what to do with the copy-code icon when there's no header. Should I force a header on every codeblock? There's probably a more elegant solution than that...
Current behaviour:
@adamjkuhn I think this PR definitely needs your expertise - I doubt my attempts are the most efficient or clean.
Test topic: https://deploy-preview-2442--kongdocs.netlify.app/enterprise/2.1.x/deployment/installation/kong-for-kubernetes/

Docs(styles) Add support for tabbed codeblocks and make copy icon transparent

---

app/_hub/kong-inc/oauth2-introspection/0.31-x.md
app/_hub/kong-inc/oauth2-introspection/0.32-x.md
app/_hub/kong-inc/oauth2-introspection/0.33-x.md
app/_hub/kong-inc/oauth2-introspection/0.34-x.md
app/_hub/kong-inc/oauth2-introspection/0.35-x.md
app/_hub/kong-inc/oauth2-introspection/0.36-x.md
app/_hub/kong-inc/oauth2-introspection/index.md

See https://konghq.atlassian.net/browse/DOCS-1418 and https://konghq.atlassian.net/browse/FTI-2072
You cannot set this on Consumer entity, so removed autogen examples from template.
https://deploy-preview-2448--kongdocs.netlify.app/hub/kong-inc/oauth2-introspection/ 
Note autogenerated Consumer examples are removed from all versions of the plugin

Schema error OAuth2 Introspection plugin Consumer entity not supported

---

app/enterprise/changelog.md

-- edited the intro note about 2.2.0.0 changelog only being the diff between 2.2.0.0 and 2.2.0.0 (beta)

docs(changelog-ee-2.2) update 2.2.0.0 vs 2.2 beta note

---

app/enterprise/changelog.md

-- added the following to 2.1.4.2, 1.5.0.8 and 1.3.0.3. 
- [OpenID Connect](/hub/kong-inc/openid-connect) (`openid-connect`)
- HS-signature verification is now disabled by default.
- Changed to use `client_secret` as a fallback secret for HS-signature verification only when it is a string and has more than one character in it.
- Updated `lua-resty-session` dependency to 3.7. 
- [JWT Signer](/hub/kong-inc/jwt-signer) (`jwt-signer`)
- HS-signature verification is now disabled by default.
-- will add following and edit content when I get approval from Jimmy Maher
- Fixes vulnerability in the OpenID Connect and JWT Signer Plugins. See [Kong Enterprise Support Portal](https://support.konghq.com/support/s/) for [advisory](https://support.konghq.com/support/s/article/Kong-Security-Advisory-OIDC-P …

docs(changelog-ee) add fix for OIDC and JWT plugins

---

app/_hub/kong-inc/vault-auth/index.md

https://konghq.atlassian.net/browse/FTI-2082
https://konghq.atlassian.net/browse/DOCS-1436
https://deploy-preview-2467--kongdocs.netlify.app/hub/kong-inc/vault-auth/#create-a-vault
This plugin is not on the latest Kong Manager UI https://manager-reference.kong-cloud.com/default/plugins/select/.

Update Vault plugin create vault example, outdated token 

---

algolia/config-kic.json
app/_layouts/docs-v2.html

Temporary configuration to make search work for this release. 
For the future: not sure that giving KIC its own search bar makes sense; should probably integrate the index into both CE and EE.
Preview: go to any KIC doc page (https://deploy-preview-2469--kongdocs.netlify.app/kubernetes-ingress-controller/1.0.x/introduction/) and test out the search bar. Should only give you results for KIC topics.

fix(kic-search) KIC Algolia config

---

app/2.2.x/kong-user.md
app/_data/docs_nav_2.2.x.yml
app/_includes/md/2.2.x/ee-kong-user.md
app/_includes/md/ce-kong-user.md
app/install/aws-linux.md
app/install/centos.md
app/install/debian.md
app/install/redhat.md
app/install/ubuntu.md

Docs ticket: https://konghq.atlassian.net/browse/DOCS-1385
Creating an unversioned include file for the note, and adding a CE topic for switching to the `kong` user and group.
Added the note to step 3 in the following docs:
https://deploy-preview-2462--kongdocs.netlify.app/install/ubuntu/
https://deploy-preview-2462--kongdocs.netlify.app/install/redhat/
https://deploy-preview-2462--kongdocs.netlify.app/install/centos/
https://deploy-preview-2462--kongdocs.netlify.app/install/aws-linux/
https://deploy-preview-2462--kongdocs.netlify.app/install/debian/
And the instructions themselves:
https://deploy-preview-2462--kongdocs.netlify.app/2.2.x/kong-user/

docs(install) Add instructions for switching to kong user on CE

---

app/enterprise/changelog.md

For 2.2.0.0 and 2.1.4.2 the following is listed for OIDC/JWT vulnerability issue:
- Changed to disable HS-signature verification by default.
- Changed to use `client_secret` as a fallback secret for HS-signature verification only when it is a string and has more than one character in it.
- Fixes vulnerability in the OpenID Connect and JWT Signer Plugins. See [Kong Enterprise Support Portal](https://support.konghq.com/support/s/) for [OIDC advisory](https://support.konghq.com/support/s/article/Kong-Security-Advisory-OIDC-Plugin) and [JWT advisory](https://support.konghq.com/support/s/article/Kong-Security-Advisory-JWT-Signer-Plugin).
- [OpenID Connect](/hub/kong-inc/openid-connect) (`openid-connect`)
- HS-signature verification is now disabled by default.
- Changed to use `client_secret` …

docs(changelog-ee) updates for OIDC/JWT security issue

---

app/_data/docs_nav_2.1.x.yml
app/_data/docs_nav_2.2.x.yml
app/_data/docs_nav_ee_2.1.x.yml
app/_data/docs_nav_ee_2.2.x.yml
app/_data/docs_nav_kic_1.0.x.yml
app/kubernetes-ingress-controller/1.0.x/concepts/ingress-versions.md

Add a concept document that covers the differences between v1beta1 and v1 versions of the Ingress resource.
Converted from https://github.com/Kong/kubernetes-ingress-controller/pull/950/
Open question regarding matching between `metadata.name` in IngressClass resources and `ingressClassName` in Ingress resources remains open, but I believe it's correct as written based on what info I can find. I can't test that in our GKE cluster, as GKE 1.18 still rejects v1 Ingresses and 1.19 isn't yet available. Not sure why this is, as [their release notes suggest otherwise](https://cloud.google.com/kubernetes-engine/docs/release-notes#known-20200908), but I can't find other documentation related to it. IMO better to go ahead and publish this with what we know, as we can always correct it if needed …

docs(k8s) add ingress version documentation

---

app/_assets/stylesheets/pages/docs.less

Issue: when no tab is highlighted at the top of the site (for KIC, decK, and eventually Getting Started), hovering over any tab makes the nav jump down a couple of pixels (see https://docs.konghq.com/kubernetes-ingress-controller/1.0.x/introduction/).
Fix: adjust margins to account for border.
Preview: compare [current problem](https://docs.konghq.com/kubernetes-ingress-controller/1.0.x/introduction/) with [proposed solution](https://deploy-preview-2471--kongdocs.netlify.app/kubernetes-ingress-controller/1.0.x/introduction/). Hover over top nav tabs (Kong Gateway, Kong Enterprise, etc) to test.

fix(nav-style) Fix border displacement on top site nav

---

app/_assets/stylesheets/page.less

Fixing the gradient issue:
To preview fix, open preview link in Safari.

fix(banner) Fix docs site banner in safari

---

app/kubernetes-ingress-controller/1.0.x/guides/using-kongingress-resource.md
app/kubernetes-ingress-controller/1.0.x/references/custom-resources.md

Several locations in the docs still used the outdated `configuration.konghq.com` annotation for applying KongIngress resources. Support for that was removed in 1.0.0; it was replaced with the `konghq.com/override` annotation.
Thought those were all fixed before the migration from the old repo docs, but it looks like a few got missed :woman_shrugging:

fix(kic) update outdated KongIngress annotations

---

app/enterprise/1.3-x/deployment/installation/docker.md
app/enterprise/1.5.x/deployment/installation/docker.md
app/enterprise/2.1.x/deployment/installation/docker.md
app/enterprise/2.2.x/deployment/installation/docker.md

Based on docs ticket: https://konghq.atlassian.net/browse/DOCS-1435
Changed only Docker installation pages, as none of the other install topics include a license sample.

docs(ee-license) Add note to use your own license for Docker installs

---

app/_data/docs_nav_ee_2.2.x.yml
app/enterprise/2.2.x/deployment/installation/overview.md

Based on https://konghq.atlassian.net/wiki/spaces/CP/pages/1299481287/Marketplace+Integrations.
Note: Azure has also been updated to a Kong Enterprise 2.2 image, but that link doesn't change. 
Preview: https://deploy-preview-2488--kongdocs.netlify.app/enterprise/2.2.x/deployment/installation/overview/ > Marketplaces tab

docs(ee-install) Update AWS AMI links for 2.2

---

app/_hub/kong-inc/exit-transformer/index.md

https://konghq.atlassian.net/browse/DOCS-1456
Per Lluis:
It does need brackets and "
the logic goes as:
foo = { some = "this is ok" }
foo = { ["some-thing"] = "this is ok too" }
foo = { some-thing = "this is not ok and does not work" }
headers = { some = "thing", ["some-other"] = "thingie" }
...
print(headers.some)
print(headers["some"])
print(headers["some-other"])
...
headers.foo = "bar"
headers["bar"] = "baz"
headers["foo-bar-baz"] = "fuzz"
...
See: 
https://github.com/Kong/docs.konghq.com/blame/70847c2447fe467b99830a7d343c3672d2274d0b/app/_hub/kong-inc/exit-transformer/index.md#L273

Bracket issues Exit Transformer example (need SME review before DOCS review)

---

app/kubernetes-ingress-controller/1.0.x/guides/configuring-custom-entities.md

This example was not correct. For `port-forward` commands, the `class/instance` syntax allows you to switch from forwarding to a 
>  Use resource type/name such as deployment/mydeployment to select a pod. Resource type defaults to 'pod' if omitted.
Converted to `-n`, which is correct for the namespace.

fix(k8s) correct port-forward example

---

app/deck/overview.md
app/kubernetes-ingress-controller/1.0.x/deployment/gke.md

Based on slack convo, and also common sense: shouldn't have any personal emails in the docs. 
Preview: 
https://deploy-preview-2495--kongdocs.netlify.app/deck/overview/#security
https://deploy-preview-2495--kongdocs.netlify.app/kubernetes-ingress-controller/1.0.x/deployment/gke/#update-user-permissions

fix(decK+KIC) Remove Harry's email from docs

---

app/_hub/kong-inc/datadog/0.1-x.md
app/_hub/kong-inc/datadog/1.0-x.md
app/_hub/kong-inc/datadog/index.md

The optional Metrics field is incorrectly documented as
`customer_identifier`. It should in fact be `consumer_identifier` [1].
[1] https://github.com/Kong/kong/blob/72821447ede25a86709ee6d7af29424f9a841725/kong/plugins/datadog/schema.lua#L90
Signed-off-by: Jeremy J. Miller <jeremy.miller@konghq.com>

docs(datadog) corrects metrics field name in docs (FTI-2131)

---

app/_includes/md/2.2.x/ee-kong-user.md
app/_includes/md/ce-kong-user.md

Now that https://github.com/Kong/kong/pull/6421 is merged, this part of the docs need to be updated.

docs(kong-user) fix install notes to switch users

---

app/2.2.x/hybrid-mode.md
app/enterprise/2.2.x/deployment/hybrid-mode-setup.md
app/enterprise/2.2.x/release-notes.md
app/getting-started-guide/2.2.x/prepare.md

Based on issue brought up on slack: https://kongstrong.slack.com/archives/CDSTDSG9J/p1607928995184600
Documentation lists the hybrid mode status endpoint as `/clustering/data_planes/` but the real endpoint (from testing) is `/clustering/data-planes/`.

Fix syntax for hybrid mode status endpoint

---

app/_assets/images/icons/documentation/icn-immunity-color.svg
app/_data/docs_nav_ee_2.2.x.yml

Docs ticket: https://konghq.atlassian.net/browse/DOCS-1339
Preview: see Immunity section in the 2.2.x nav: https://deploy-preview-2503--kongdocs.netlify.app/enterprise/
Brain was still available in earlier versions of 2.1.3.x, so none of the navs before 2.2.x need to change.

docs(ee-immunity) Add icon for immunity and replace brain icon in nav

---

app/_hub/api-fortress/api-fortress-http-log/index.md
app/_redirects
app/deck/index.md
jekyll-dev.yml
jekyll.yml
package.json

Docs ticket: https://konghq.atlassian.net/browse/DOCS-1241
**Goal and approach:**
Testing out a central redirect config file. Goal is to get rid of all blank files that just hang around for redirect reasons and get cloned with every release. 
File syntax is very simple: each line contains a "from" path and a "to" path. These can be either relative or absolute, though relative paths are preferred. The number of spaces or tabs between the paths does not matter, as long as there is at least one space to distinguish them as separate paths.
**Changes:**
For this PR, I'm just introducing the file and testing removing `redirect_from` and `redirect_to` in one file each, then replacing them with entries in the `_redirects` file. 
There are a few other config options if needed (see …

feat(redirects) Introduce _redirects file as central location for all redirects

---

app/kubernetes-ingress-controller/1.1.x/deployment/aks.md
app/kubernetes-ingress-controller/1.1.x/deployment/eks.md
app/kubernetes-ingress-controller/1.1.x/deployment/gke.md
app/kubernetes-ingress-controller/1.1.x/deployment/k4k8s-enterprise.md
app/kubernetes-ingress-controller/1.1.x/deployment/k4k8s.md
app/kubernetes-ingress-controller/1.1.x/deployment/minikube.md

Remove about Helm v2 due to is't deprecation.
After November 13, 2020,No further Helm v2 releases.
[ref. helm-v2-deprecation-timeline](https://helm.sh/blog/helm-v2-deprecation-timeline/)
Related documents:
* app/kubernetes-ingress-controller/1.1.x/deployment/aks.md
* app/kubernetes-ingress-controller/1.1.x/deployment/eks.md
* app/kubernetes-ingress-controller/1.1.x/deployment/gke.md
* app/kubernetes-ingress-controller/1.1.x/deployment/k4k8s-enterprise.md
* app/kubernetes-ingress-controller/1.1.x/deployment/k4k8s.md
* app/kubernetes-ingress-controller/1.1.x/deployment/minikube.md

Remove the description about Helm v2 due to it's deprecation.

---

app/getting-started-guide/2.2.x/dev-portal.md
app/getting-started-guide/2.2.x/expose-services.md
app/getting-started-guide/2.2.x/improve-performance.md
app/getting-started-guide/2.2.x/load-balancing.md
app/getting-started-guide/2.2.x/manage-teams.md
app/getting-started-guide/2.2.x/prepare.md
app/getting-started-guide/2.2.x/protect-services.md
app/getting-started-guide/2.2.x/secure-services.md

Changes:
* Combining cURL and HTTPie examples into tabbed codeblocks
* Fixing some of the examples along the way
* Making formatting of examples consistent
Notes to reviewers: 
* This PR looks bigger than it is. The majority of the work is simply to replace any instances of separate cURL and HTTPie examples with a tabbed view, saving a potentially huge amount of space on the screen (best example of this is the Kong Admin API tab here: https://docs.konghq.com/getting-started-guide/2.2.x/manage-teams/#create-an-admin). 
* I had to remove numbered lists, whenever these codeblocks were part of them. The output breaks when you try to nest a tab into a list. I found the utility/UX improvement of the tabs to be great enough to still go ahead with the change anyway.
Previews:
Tabs for cURL/HTTPie …

docs(gsg) Add tabs for cURL and HTTPie example pairs and fix examples

---

app/kubernetes-ingress-controller/1.0.x/guides/cert-manager.md
app/kubernetes-ingress-controller/1.1.x/guides/cert-manager.md

Based on: https://konghq.atlassian.net/browse/DOCS-1484
Feedback came in from a very unhappy user (logged through thumbs up/down widget on docs site) that spent a long time trying to figure out why the example didn't work as documented.
This syntax is the user's suggestion.

docs(kic) Fix syntax for TLS certs

---

app/enterprise/1.5.x/deployment/installation/amazon-linux-2.md
app/enterprise/1.5.x/deployment/installation/amazon-linux.md
app/enterprise/1.5.x/deployment/installation/centos.md
app/enterprise/1.5.x/deployment/installation/rhel.md
app/enterprise/1.5.x/deployment/installation/ubuntu.md
app/enterprise/2.1.x/deployment/installation/amazon-linux-2.md
app/enterprise/2.1.x/deployment/installation/amazon-linux.md
app/enterprise/2.1.x/deployment/installation/centos.md
app/enterprise/2.1.x/deployment/installation/docker.md
app/enterprise/2.1.x/deployment/installation/kong-on-kubernetes.md
app/enterprise/2.1.x/deployment/installation/rhel.md
app/enterprise/2.1.x/deployment/installation/ubuntu.md
app/enterprise/2.2.x/deployment/installation/amazon-linux-2.md
app/enterprise/2.2.x/deployment/installation/amazon-linux.md
app/enterprise/2.2.x/deployment/installation/centos.md
app/enterprise/2.2.x/deployment/installation/docker.md
app/enterprise/2.2.x/deployment/installation/kong-on-kubernetes.md
app/enterprise/2.2.x/deployment/installation/rhel.md
app/enterprise/2.2.x/deployment/installation/ubuntu.md

Installation topics were pulling the latest real version of Enterprise. Instead, each version should be pulling its own most recent patch version number. Fixing 2.2.x, 2.1.x, and 1.5.x (versions that are still being actively maintained in patches).

docs(ee-install) Change version variables to pull correct versions

---

app/_layouts/docs-v2.html

Based on docs ticket: https://konghq.atlassian.net/browse/DOCS-1518
**Issue:** Doc "browsing older version" banner links to the the landing page of the latest doc, while it should point to the same topic (if the topic exists).
(eg see https://docs.konghq.com/1.5.x/proxy/)
**Changes:** 
* Instead of pointing to the doc landing page of the latest version, changing the link in the banner to check if a parallel page exists under `/latest/`. If the page exists, the link points to that page; if not, the link points to the doc landing page as before. 
* Rephrased the text to avoid calling out the product name, and shortened it to avoid banner wrapping onto a second line.
**Preview:**
Test by opening an older topic, then clicking on the link in the banner: …

docs(old versions) Adjust older versions banner

---

app/_data/extensions/kong-inc/request-size-limiting/versions.yml
app/_hub/kong-inc/request-size-limiting/1.0.x.md
app/_hub/kong-inc/request-size-limiting/index.md

https://konghq.atlassian.net/browse/DOCS-1536
See PR for code: https://github.com/Kong/kong/pull/6660/commits/65ab975eda1e374d93679a5b02bc9de8cb6420f4
Update plugin for new require_content_length field for 2.3. Added data types, copy edited, and bumped the version. 
Direct review link: https://deploy-preview-2547--kongdocs.netlify.app/hub/kong-inc/request-size-limiting/
Reviewers: Do we need to mention 411 error for chunked content (transfer encoding)? (I guess not.)
Does the open source now support the size  field (Yes, adjusted per Thij's feedback)? See legacy content: 
> Size unit can be set either in `bytes`, `kilobytes`, or `megabytes` (default). **Note:** This configuration is only
supported in Kong Enterprise 1.3 and above, and may eventually extend to Kong Gateway (OSS).

CE 2.3: Update request-size-limiting plugin for new field that requires valid content-length-header

---

app/2.3.x/external-plugins.md
app/_data/docs_nav_2.3.x.yml

replace Go plugins with the new, generic "External plugins" concept.
- multiple plugin servers
- embedded server on go-pdk

new external-plugins page (not ready to merge for CE 2.3 release)

---

app/_data/kong_versions.yml

Catching up, as this version was released 12 days ago: https://github.com/Kong/deck/releases/tag/v1.3.0
This updates version strings in the installation topic.

Update decK version metadata for 1.3.0

---

app/enterprise/changelog.md

Creating changelog for Kong Enterprise 2.3.0.0 (beta) by adding 2.3.0 Kong Gateway (OSS) information. 
No feature documentation is included in this beta release. 
Preview: https://deploy-preview-2542--kongdocs.netlify.app/enterprise/changelog/#2300beta
Question: Do we want to include PR links, being this is a beta release with no documentation? PR's will give users some information about items listed in this release.

docs(ee-changelog)Updated 2.3.0 KE beta w/2.3.0 CE info

---

algolia/config-ee.json
app/_assets/stylesheets/base.less
app/_includes/search-selector.html
app/_layouts/default.html

With Kong Enterprise getting removed from the tabs for Konnect, there's no top-level selector for Enterprise pages. 
Adding a selector and adjusting EE config file to match. Will be switching all content to this top-level hidden selector in the future.

Update algolia config for KE

---

app/_data/docs_nav_konnect.yml
app/konnect/dev-portal/developers/dev-reg.md
app/konnect/dev-portal/index.md
app/konnect/reference/konnect-api.md

Removing straggling instances of `khcp` in URLs that got missed in the launch.

docs(konnect) Removing khcp, replacing with konnect

---

app/kubernetes-ingress-controller/1.0.x/concepts/ingress-classes.md
app/kubernetes-ingress-controller/1.1.x/concepts/ingress-classes.md

`apiVersion` missed in kubernetes manifest.

fix syntax error of kubernetes manifest in example

---

app/kubernetes-ingress-controller/1.0.x/guides/using-oidc-plugin.md
app/kubernetes-ingress-controller/1.1.x/guides/using-oidc-plugin.md

Docs ticket: https://konghq.atlassian.net/browse/DOCS-1556
This is already correct in the OIDC plugin docs, for example: https://docs.konghq.com/hub/kong-inc/openid-connect/#configclient_jwk

Fix OIDC issuer url syntax

---

app/_includes/search-selector.html

Minor adjustments, as currently the "Plugin Hub" label isn't being picked up properly, and the plugins get categorized as "Kong" instead.

fix(search) Adjust plugin hub value for algolia

---

app/_data/extensions/kong-inc/serverless-functions/versions.yml
app/_hub/kong-inc/serverless-functions/1.0-x.md
app/_hub/kong-inc/serverless-functions/index.md

This PR adds a new version of the serverless plugin (which starts in Kong 2.3).
The main difference between serverless plugin 1.0 and 2.0 is the sandboxing feature, for which I am also attaching some docs.

docs(serverless) document sandboxing in serverless functions 2.0

---

app/_includes/nav-v2.html

Edit link in navbar to point at a community overview page instead of discuss, which is just one piece.

Update link for community

---

app/konnect/updates.md

Docs ticket: https://konghq.atlassian.net/browse/DOCS-1573
Note for reviewers: the broken link is going to `/konnect/dev-portal/administrators/public-portal/`, which is a new topic added in https://github.com/Kong/docs.konghq.com/pull/2574. This PR can still be merged if that is the only broken link.
Preview: https://deploy-preview-2577--kongdocs.netlify.app/konnect/updates/

Konnect updates: deployment week 2021-02-08

---

app/kubernetes-ingress-controller/1.1.x/references/version-compatibility.md

Add Kubernetes 1.20 and 1.21 to the supported version matrix.
cc @Kong/team-k8s @eskibars

KIC: Support Kubernetes 1.20 and 1.21

---

README.md

The instructions regarding autodocs have changed significantly. The
generation is now done on the kong repo.
Depends on https://github.com/Kong/kong/pull/6756 , since until now we
generate the docs on kong but then copy them manually afterwards.

docs(README) update autodocs instructions

---

app/_assets/stylesheets/pages/extension.less

Sometime around the release of Konnect, an errant CSS change broke the display of ordered lists in the plugin hub. 
Exhibit A: https://docs.konghq.com/hub/kong-inc/openid-connect/#important-configuration-parameters
Fixing that, matching the numbering style to the rest of the site.
Preview:
https://deploy-preview-2584--kongdocs.netlify.app/hub/kong-inc/openid-connect/#important-configuration-parameters

fix(styles) Plugin numbering display issue

---

jekyll-dev.yml
jekyll.yml

Something is messing with our analytics data. It might be this, as this was the only metadata change to occur on April 6th last year, the day before analytics went messy.
Changes: setting a scope for the /enterprise path and removing an obsolete docs/ee path.
No preview, just check that nothing's broken.

fix(jekyll) Adding a scope for the enterprise directory

---

app/kubernetes-ingress-controller/1.0.x/guides/configuring-https-redirect.md
app/kubernetes-ingress-controller/1.1.x/guides/configuring-https-redirect.md

Replace the KongIngress override binding with the equivalent dedicated
annotations in the ingress controller HTTPS redirect guide. While the
KongIngress method is still supported, the dedicated annotations are
more modern, and are supported in all KIC versions we cover on the docs
site.
Additionally, use a 301 rather than a 302. HTTP->HTTPS redirects are
typically permanent, so a 301 is more appropriate.

Use dedicated annotations for HTTPS redirect guide

---

app/_hub/kong-inc/hmac-auth/index.md

There are more improvements that could be made, but the main purpose of this PR is to add missing data types. Fixed broken nav tab syntax and removed ancient version notes per Gayle.
Reviewers: Please compare the datatypes added to the doc with the datatypes shown in the schema.
Schema link:
https://github.com/Kong/kong-ee/blob/master/kong/plugins/hmac-auth/schema.lua
https://deploy-preview-2601--kongdocs.netlify.app/hub/kong-inc/hmac-auth/

HMAC plugin add datatypes, fix nav tabs

---

app/enterprise/2.3.x/release-notes.md
app/enterprise/2.3.x/studio/dec-conf-studio.md
app/enterprise/2.3.x/studio/deploy-to-dev-portal.md
app/enterprise/2.3.x/studio/download-install.md
app/enterprise/2.3.x/studio/index.md
app/enterprise/2.3.x/studio/using-insomnia-designer.md

Studio plugin bundle is being deprecated. See docs ticket for more detail: https://konghq.atlassian.net/browse/DOCS-1543
Added the note to studio docs for now; will remove docs entirely when the next Insomnia release comes out.
Preview: https://deploy-preview-2600--kongdocs.netlify.app/enterprise/2.3.x/studio/

docs(studio) Note for deprecating Kong Studio bundle

---

app/enterprise/2.3.x/support-policy.md

Note that the support EOL dates don't change. This is on purpose: all 2.x releases have the same support period, starting from the release of the first 2.x version. 
Considered combining all 2.x versions into one table entry, but then we lose release dates.

Add 2.3 to list of supported gateway versions

---

app/konnect/getting-started/configure-runtime.md
app/konnect/runtime-manager/kong-gateway-runtime.md

Docs ticket: https://konghq.atlassian.net/browse/DOCS-1594
Issue raised on slack. Including the minimum required version number for HTTPie to avoid authentication errors.

[Konnect] Version number for httpie prereq

---

app/_hub/kong-inc/request-termination/index.md

Schema link:
https://github.com/Kong/kong-ee/blob/master/kong/plugins/request-termination/schema.lua
https://deploy-preview-2614--kongdocs.netlify.app/hub/kong-inc/request-termination/

Request Termination plugin add datatypes

---

app/_hub/kong-inc/acl/index.md

Schema link:
https://github.com/Kong/kong-ee/blob/master/kong/plugins/acl/schema.lua
https://deploy-preview-2606--kongdocs.netlify.app/hub/kong-inc/acl/

ACL plugin datatypes

---

app/_hub/kong-inc/exit-transformer/index.md

Schema link:
https://github.com/Kong/kong-plugin-enterprise-exit-transformer/blob/master/kong/plugins/exit-transformer/schema.lua
https://deploy-preview-2603--kongdocs.netlify.app/hub/kong-inc/exit-transformer/

Exit Transformer datatypes

---

app/_hub/kong-inc/ip-restriction/index.md

Schema link:
https://github.com/Kong/kong-ee/blob/master/kong/plugins/ip-restriction/schema.lua
https://deploy-preview-2612--kongdocs.netlify.app/hub/kong-inc/ip-restriction/

IP Restriction plugin add datatypes

---

app/_hub/kong-inc/grpc-gateway/index.md

Schema link:
https://github.com/Kong/kong-plugin-grpc-gateway/blob/master/kong/plugins/grpc-gateway/schema.lua
https://deploy-preview-2608--kongdocs.netlify.app/hub/kong-inc/grpc-gateway/

grpc-gateway plugin add datatype

---

app/enterprise/2.2.x/immunity/install-configure.md
app/enterprise/2.3.x/immunity/install-configure.md

Docs ticket: https://konghq.atlassian.net/browse/DOCS-1602
Fixing URL for Immunity Docker image in 2.2.x and 2.3.x. Checked with a quick `docker pull` to make sure this one works.
This image didn't exist before 2.2.x, it was Brain&Immunity before that.

Fix Immunity docker URLs

---

app/_hub/kong-inc/forward-proxy/index.md

Schema links:
https://github.com/Kong/kong-plugin-enterprise-forward-proxy/blob/master/kong/plugins/forward-proxy/schema.lua
https://github.com/Kong/kong/blob/master/kong/db/schema/typedefs.lua (host and port)
https://deploy-preview-2613--kongdocs.netlify.app/hub/kong-inc/forward-proxy/

Forward Proxy plugin add datatypes

---

app/konnect/servicehub/index.md

Docs ticket: https://konghq.atlassian.net/browse/DOCS-1574 (see ticket for source)
* Listing out unsupported plugins in Konnect SaaS.
* Adding serverless plugins as something you have to request from Kong Support.
Logging plugins not included as they will be available shortly.
https://deploy-preview-2576--kongdocs.netlify.app/konnect/servicehub/#plugin-limitations

docs(konnect) List unsupported plugins

---

app/kubernetes-ingress-controller/1.0.x/deployment/admission-webhook.md
app/kubernetes-ingress-controller/1.1.x/deployment/admission-webhook.md

As of Go 1.15, certificates that use a CN hostname in their subject but do not have a SAN are not supported. We use Go 1.15 for controller versions 0.10 and onward.
This change updates our example certificate creation command to include a SAN.
Originally reported in DOCS-1560

fix(kic) add SANs to example certificate command

---

app/_hub/kong-inc/cors/index.md

Schema link:
https://github.com/Kong/kong-ee/blob/master/kong/plugins/cors/schema.lua
https://deploy-preview-2605--kongdocs.netlify.app/hub/kong-inc/cors/

CORS plugin datatypes

---

app/_hub/kong-inc/syslog/index.md

Schema link:
https://github.com/Kong/kong-ee/blob/master/kong/plugins/syslog/schema.lua
https://deploy-preview-2623--kongdocs.netlify.app/hub/kong-inc/syslog/
Reviewers: Some of these older plugins don't like colons within description text. It causes yaml errors. @lena-larionova do you know of any fix or workaround for that? It's not happy even with text after the colon. Why is it misinterpreting it here?
Errors like I saw for CORS:
`[15:36:11]              Error: YAML Exception reading /Users/terryblessing/github/docs.konghq.com/app/_hub/kong-inc/cors/index.md: (<unknown>): …

Syslog plugin add datatypes and one_of options from schema

---

app/_hub/kong-inc/route-transformer-advanced/index.md

Schema link:
https://github.com/Kong/kong-plugin-route-transformer-advanced/blob/master/kong/plugins/route-transformer-advanced/schema.lua
https://deploy-preview-2615--kongdocs.netlify.app/hub/kong-inc/route-transformer-advanced/

Route Transformer Advanced plugin add datatypes

---

app/_hub/kong-inc/tcp-log/index.md

Schema links:
https://github.com/Kong/kong-ee/blame/master/kong/plugins/tcp-log/schema.lua
https://github.com/Kong/kong/blob/master/kong/db/schema/typedefs.lua
https://deploy-preview-2624--kongdocs.netlify.app/hub/kong-inc/tcp-log/
REVIEWERS: I noticed some fields in the schema that aren't present in the docs. There isn't a readme to go by that I can find either. Can you please assist? Update: Murillo to the rescue.

TCP Log plugin  add datatypes, missing TLS params

---

.github/workflows/build-test.yml

Attempting to adjust our build/test github action once again. That is, only this check:
Instead of building on push, it should build on changes to PRs:
* `opened`  (does not apply to draft PRs)
* marked `ready_for_review`
* `synchronized `: commits were pushed to the branch. This means that a push will still trigger a build, but only if you have an open PR.
Any PRs marked as “draft” will not be built. The build kicks off once you mark it “ready for review”. 
Tested this in a bunch of situations:
* No PR = no build
* Open draft PR = no build
* Push to draft PR = no build
* Create PR from a branch with multiple commits: build/test runs on the latest commit only
* Push a bunch of commits to an open PR, not in draft mode: build/test runs on the latest commit only
Am I missing anything?
N/A - …

[DOCS-1606] Build/test action adjustments

---

README.md

With our incremental changes, the latest being the new landing page, the process for updating the community docs has changed over time. Updating the instructions so that anyone on the open-source team can make a new doc version when needed.

[DOCS-1581] README: Add instructions for creating a new version

---

app/enterprise/2.3.x/admin-api/licenses/examples.md
app/enterprise/2.3.x/admin-api/licenses/reference.md
app/enterprise/2.3.x/deployment/licenses/deploy-license.md
app/enterprise/2.3.x/deployment/licensing.md

Docs ticket: https://konghq.atlassian.net/browse/DOCS-1593
* Changing double quotes (`" "`) around licenses to single quotes (`' '`)
* Link to deploy a license from license overview
* Cleaning up the Admin API reference and examples for clarity, formatting, flow
[Licenses Admin API reference](https://deploy-preview-2607--kongdocs.netlify.app/enterprise/2.3.x/admin-api/licenses/reference/)
[Licenses examples](https://deploy-preview-2607--kongdocs.netlify.app/enterprise/2.3.x/admin-api/licenses/examples/)

docs(admin-api/license) Rework licenses admin api doc

---

app/_layouts/extension.html

After getting frustrated with the OpenID Connect plugin doc for the umpteenth time, realized that the plugin docs don't have a scroll-to-top button. Adding that.
https://docs.konghq.com/hub/kong-inc/openid-connect/ - this. this is the reason.
But seriously: the plugin docs arguably have more need for a scroll-to-top button than the main site, as plugin references are often lengthy and the page nav doesn't follow the reader down the page.
https://deploy-preview-2635--kongdocs.netlify.app/hub/kong-inc/openid-connect/ - scroll some ways down the page, close the cookie banner, and click the `^` button in the bottom right corner.

[no ticket] Add scroll to top button for plugins

---

app/_hub/kong-inc/udp-log/index.md

Schema links:
https://github.com/Kong/kong-ee/blob/master/kong/plugins/udp-log/schema.lua
https://github.com/Kong/kong/blob/master/kong/db/schema/typedefs.lua (host and port)
https://deploy-preview-2629--kongdocs.netlify.app/hub/kong-inc/udp-log/

UDP Log plugin add datatypes from schemas

---

app/_hub/kong-inc/file-log/index.md

Schema link:
https://github.com/Kong/kong-ee/blob/master/kong/plugins/file-log/schema.lua
https://deploy-preview-2634--kongdocs.netlify.app/hub/kong-inc/file-log/

File Log logging plugin, add datatype, remove ancient notes

---

app/_hub/kong-inc/loggly/index.md

Schema link:
https://github.com/Kong/kong-ee/blob/master/kong/plugins/loggly/schema.lua
https://deploy-preview-2633--kongdocs.netlify.app/hub/kong-inc/loggly/

Loggly logging plugin add datatypes, grammar edits

---

app/_layouts/extension.html

Fixing plugin compatibility list.
Compatibility list is listing all product versions, for every single product.
Check that the listed versions under Kong Gateway aren't duplicated (bottom right in the page sidebar). For example: https://deploy-preview-2640--kongdocs.netlify.app/hub/kong-inc/basic-auth/

[DOCS-1614] Fix Plugin compatibility list for community versions

---

app/_hub/kong-inc/http-log/index.md

Schema links:
- https://github.com/Kong/kong-ee/blob/master/kong/plugins/http-log/schema.lua
- typedefs.url-where is this schema @Murillo? Answer: https://github.com/Kong/kong-ee/blob/master/kong/db/schema/typedefs.lua#L295-L298
- Also, need a description for content_type, which was missing from doc.  (Update: @javierguerragiraldez had said not to doc content_type in PR 2393 but I think that time has come now). Schemas do not contain descriptions of fields. And there isn't a readme either. Attempted a description in commit 46f3758. …

HTTP log logging plugin add datatypes, missing param

---

app/enterprise/changelog.md

@GayleNeumann - I did not include the Jira issue number bc we discussed they shouldn't be added, but I noticed the other fix under Enterprise includes Jiras . . . Wasn't sure if I should remove those or not . . .
Added FTI-2038 fix to KE 2.3.2.0 changelog per @jeremymv2 's request in Slack.
DOCS-1617
[Sample build link](https://deploy-preview-2643--kongdocs.netlify.app/enterprise/changelog/#enterprise-1)

[DOCS-1617] added update to KE 2.3.2.0 changelog

---

app/_hub/kong-inc/openid-connect/0.31-x.md
app/_hub/kong-inc/openid-connect/0.32-x.md
app/_hub/kong-inc/openid-connect/0.33-x.md
app/_hub/kong-inc/openid-connect/0.34-x.md
app/_hub/kong-inc/openid-connect/0.35-x.md
app/_hub/kong-inc/openid-connect/1.3-x.md
app/_hub/kong-inc/openid-connect/1.5.x.md
app/_hub/kong-inc/openid-connect/index.md

@reviewer
Updates an outdated link in the OIDC plugin reference for Keycloak.
Current link is generating a 404.
Validate that the link is no longer generating 404s.

Update OIDC plugin reference with corrected Keycloak docs link

---

app/enterprise/2.2.x/property-reference.md
app/enterprise/2.3.x/property-reference.md

Copied the doc section from 2.3.x version docs.
The additional configuration was added in 2.2.1.0 to match 2.3.0.0. The default value for `untrusted_lua` is different from 2.3.0.0.
FT-1688

add info on new config properties introduced in 2.2.1.0

---

app/_hub/kong-inc/openid-connect/index.md

@reviewer
https://konghq.atlassian.net/browse/DOCS-1604 Update OIDC plugin TLS now supported with Redis cluster
See slack convo https://kongstrong.slack.com/archives/C4CA2EP1S/p1613693676119600
This was brought up by @morals415 in the # open_id_connect_idp channel.
I did not test this. It was confirmed as working by Murillo and Aapo. Aapo updated the readme but not the plugin hub docs.
I'm not sure which version this was updated, so the change was made directly to the index file (2.2.x). Reviewers: If that is not correct, please let me know.

[DOCS-1604] remove erroneous statements Redis not supported

---

app/gateway-oss/2.1.x/pdk/kong.response.md
app/gateway-oss/2.2.x/pdk/kong.response.md

Follow up to public contributor PR https://github.com/Kong/docs.konghq.com/pull/2642.
Minor format error also in versions 2.2 and 2.1.
https://deploy-preview-2646--kongdocs.netlify.app/gateway-oss/2.2.x/pdk/kong.response/#kongresponseexitstatus-body-headers
https://deploy-preview-2646--kongdocs.netlify.app/gateway-oss/2.1.x/pdk/kong.response/#kongresponseexitstatus-body-headers
> The second half of the problem is in line 499, where it starts a `lua` codeblock. That line should be removed - someone accidentally formatted a codeblock inside a codeblock.
> 
> Since this doc is generated from the code, can you also open a PR against the source file in kong/kong: https://github.com/Kong/kong/blob/master/kong/pdk/response.lua#L773 - this line and line 776 should be removed, …

follow up to public contributor PR, fix other versions

---

app/enterprise/2.1.x/secure-admin-api.md
app/enterprise/2.2.x/secure-admin-api.md
app/enterprise/2.3.x/secure-admin-api.md
app/gateway-oss/2.0.x/secure-admin-api.md
app/gateway-oss/2.1.x/secure-admin-api.md
app/gateway-oss/2.2.x/secure-admin-api.md
app/gateway-oss/2.3.x/secure-admin-api.md

@reviewer
This change fixes several problems in the Admin API loopback
instructions.
* The example uses Routes and Services instead of the deprecated Apis
examples
* It differentiates more clearly which operations need to happen in
127.0.0.1 in contrast to the ones which can be applied outside.
* It explains how to set up dbless kong using Docker and a declarative
configuration
* It explains how to set up a PostgreSQL kong using Docker and a
start configuration
https://kongstrong.slack.com/archives/CDSTDSG9J/p1614186873017300

docs(2.3.x) improve Admin API loopback instructions

---

app/_hub/kong-inc/kafka-log/1.3-x.md
app/_hub/kong-inc/kafka-log/index.md

https://konghq.atlassian.net/browse/DOCS-1396
Adding for most current version only. 
I had wanted to change the doc versions to match the handler versions but they are 0.1.0 and 0.1.1 respectively, so essentially 0.1.x. I did a diff on the doc source files and there are significant differences between the index and 1.3-x (api versions, protocols). 
Note: Kafka Upstream plugin had its install info removed as it is bundled with Enterprise. I think the same is true for this plugin. Will log another ticket after verifying. Logged follow-up ticket https://konghq.atlassian.net/browse/DOCS-1591.
Schema link:
https://github.com/Kong/kong-plugin-kafka-log/blob/master/kong/plugins/kafka-log/schema.lua
https://deploy-preview-2595--kongdocs.netlify.app/hub/kong-inc/kafka-log/

Kafka Logging plugin datatypes

---

app/enterprise/2.3.x/external-plugins.md
app/gateway-oss/2.3.x/external-plugins.md

https://konghq.atlassian.net/browse/DOCS-1601 Customer corrections to syntax as reported to @lchari77.  Ticket details:
> Simon Markets submitted this request via email:
> 
> Recently I've been working on configuring local environment for developing plugins for Kong. While doing this, I found a couple errors in documentation that I would like share.
> 
> https://docs.konghq.com/enterprise/2.3.x/external-plugins/#kong-gateway-plugin-server-configuration
> 
> Documentation provides this example of config for Go serverpluginserver_go_socket = /usr/local/kong/go_pluginserver.socketpluginserver_go_start_cmd = go-pluginserver -kong-prefix /usr/local/kong/ -plugins-dir /usr/local/kong/go-pluginspluginserver_go_query_cmd = go-pluginserver -dump-all-plugins -plugins-dir …

[DOCS-1601] Go plugin doc corrections per customer issues

---

app/_hub/kong-inc/statsd-advanced/index.md

This PR also is part of https://konghq.atlassian.net/browse/DOCS-1417.
Schema link:
https://github.com/Kong/kong-plugin-statsd-advanced/blob/master/kong/plugins/statsd-advanced/schema.lua
https://deploy-preview-2647--kongdocs.netlify.app/hub/kong-inc/statsd-advanced/

StatsD Advanced plugin add datatypes 

---

app/_hub/kong-inc/request-validator/index.md

Schema link:
https://github.com/Kong/kong-plugin-enterprise-request-validator
https://deploy-preview-2650--kongdocs.netlify.app/hub/kong-inc/request-validator/

Request Validator plugin add datatypes

---

app/_hub/kong-inc/response-transformer/index.md

Ported the datatypes from the advanced version of the plugin that Murillo and I worked on.
Schema link:
https://github.com/Kong/kong-ee/blob/master/kong/plugins/response-transformer/schema.lua
https://deploy-preview-2604--kongdocs.netlify.app/hub/kong-inc/response-transformer/

Response Transformer datatypes

---

app/_hub/kong-inc/response-ratelimiting/index.md

Schema link:
https://github.com/Kong/kong-ee/blob/master/kong/plugins/response-ratelimiting/schema.lua
@murillopaula not clear on how to phrase datatype for limits. Map of key:values? Went with string, please let me know if that is correct.
https://deploy-preview-2617--kongdocs.netlify.app/hub/kong-inc/response-ratelimiting/

Response Rate Limiting plugin add datatypes

---

app/enterprise/changelog.md

@kallecaco3 
Remove any mention of a non-existent/unsupported config option from changelog, point changelog to property reference for details.
https://konghq.atlassian.net/browse/DOCS-1631
Tested locally, reviewers see https://deploy-preview-2657--kongdocs.netlify.app/enterprise/changelog/#enterprise-3

[DOCS-1631] remove unsupported config option from changelog

---

app/_assets/javascripts/app.js

Removing an event that triggers on every single page view in docs, giving us a really weird bounce rate.
To remove a duplicate google analytics event:
TBA

fix(analytics) Remove duplicate event tracker

---

app/enterprise/2.2.x/property-reference.md
app/enterprise/2.3.x/property-reference.md
app/gateway-oss/2.2.x/configuration.md
app/gateway-oss/2.3.x/configuration.md

Updating `unstrusted_lua` properties with doc recently updated in the kong/kong repo: https://github.com/Kong/kong/pull/6881
**Note to reviewers:** The content in this doc is autogenerated and was already reviewed in the original PR. This is simply generating the markdown version of said doc.
Properties were lacking information and examples, plus the formatting was broken.
Changes have also been backported into 2.2, where they got missed originally. 
https://deploy-preview-2661--kongdocs.netlify.app/enterprise/2.3.x/property-reference/#untrusted_lua
https://deploy-preview-2661--kongdocs.netlify.app/enterprise/2.2.x/property-reference/#untrusted_lua
https://deploy-preview-2661--kongdocs.netlify.app/gateway-oss/2.3.x/configuration/#untrusted_lua …

[DOCS-1627] Update untrusted_lua config properties

---

app/_layouts/landing-page.html

Adding docs feedback widget to landing page.
Suggested by Dragos, so that we could gather feedback on the new landing page.
https://deploy-preview-2665--kongdocs.netlify.app/ - see thumbs up icon in the bottom right

(no ticket) Add feedback widget to landing page

---

app/enterprise/2.3.x/deployment/installation/kong-on-kubernetes.md

@cwurm, @rainest, @Bradamant3 
Updating the installation doc for Kong Gateway (Enterprise) on Kubernetes (final name TBD).
**Note to reviewers:** I only updated db-backed install topic, as the db-less topic uses a YAML manifest and those are not yet updated: https://github.com/Kong/kubernetes-ingress-controller/issues/1041
* Removing mention of bintray licenses - users should only get them from sales rep at the moment
* Went with suggested dummy license secret route - @rainest Ideally we could get a license-less chart and let people patch it in the future, but that's also not currently set up?
* General topic clean up and consistency
* Labelling Dev Portal as enterprise/optional feature throughout
* Use public `kong-docker-kong-gateway-docker.bintray.io/kong-enterprise-edition` instead of …

[DOCS-1605] Optional license, new image for k8s db-backed installation

---

app/enterprise/2.3.x/deployment/hybrid-mode-setup.md

@srAtKong 
According to a Slack message -  @srAtKong - was attempting to setup Kong in hybrid mode with one cp and one dp, using the docs and in step 4, the DP could not see the CP. He was getting a 404 not found when he did an http on `<control-plane>:8001/clustering/data_planes` . He says it was fixed by updating `<control-plane>:8001/clustering/data_planes` to `<control-plane>:8001/clustering/data-planes` - so the docs should be updated.
[Slack message](https://kongstrong.slack.com/archives/C0DSXDXV1/p1615266321220000?thread_ts=1615264229.219500&cid=C0DSXDXV1)
[Link to corrected step](https://deploy-preview-2673--kongdocs.netlify.app/enterprise/2.3.x/deployment/hybrid-mode-setup/#step-4-verify-that-nodes-are-connected)

Minor edit to setup Kong in hybrid mode docs

---

app/_hub/kong-inc/openid-connect/index.md

@tlblessing 
Adding:
* config.groups_required
* config.groups_claim
* config.roles_required 
* config.roles_claim
Straight copy/paste from https://github.com/Kong/kong-plugin-enterprise-openid-connect/blob/master/README.md
Parameters were added in 2.1 but never documented.
https://deploy-preview-2676--kongdocs.netlify.app/hub/kong-inc/openid-connect/

[DOCS-1463] Add group and roles parameters

---

app/konnect/getting-started/implement-service.md
app/konnect/servicehub/manage-services.md

Adding a step to configure the HTTP method for a Route during implementation, or when adding a Route separately in the ServiceHub.
User pointed out that not setting a method during Route configuration could cause jumbled output.
https://deploy-preview-2677--kongdocs.netlify.app/konnect/getting-started/implement-service/
https://deploy-preview-2677--kongdocs.netlify.app/konnect/servicehub/manage-services/#implement-service-version

[DOCS-1625] Konnect: Add step for HTTP method when adding a route

---

app/_hub/kong-inc/statsd-advanced/index.md
app/_hub/kong-inc/statsd/index.md

This PR also is part of https://konghq.atlassian.net/browse/DOCS-1417.
Schema link:
https://github.com/Kong/kong-ee/blob/master/kong/plugins/statsd/schema.lua
https://deploy-preview-2678--kongdocs.netlify.app/hub/kong-inc/statsd/
Reviewers: see old PR https://github.com/Kong/docs.konghq.com/pull/2648 for incorporated feedback.

Stats d take2

---

app/kubernetes-ingress-controller/1.0.x/deployment/k4k8s-enterprise.md
app/kubernetes-ingress-controller/1.0.x/guides/cert-manager.md
app/kubernetes-ingress-controller/1.1.x/deployment/k4k8s-enterprise.md
app/kubernetes-ingress-controller/1.1.x/guides/cert-manager.md

@reviewer
Remove reference to 3rd party domain for helm chart values
Security risk of fetching helm chart values from a third party domain, it's unnecessary, they should be created locally

Remove references to the 3rd party for helm chart values and docs

---

app/kubernetes-ingress-controller/1.0.x/guides/configuring-fallback-service.md
app/kubernetes-ingress-controller/1.1.x/guides/configuring-fallback-service.md

Pull fallback-svc example out of bit.ly/fallback-svc and correct the apiVersion for its Deployment.
The original link was a specific gist version with an error, and can't be modified without creating a new link. The example here is short enough that we can pull it out.
Originally reported by https://twitter.com/SixteenOne/status/1368510931211259921

Correct invalid Deployment apiVersion

---

app/enterprise/2.3.x/deployment/installation/amazon-linux-2.md
app/enterprise/2.3.x/deployment/installation/amazon-linux.md
app/enterprise/2.3.x/deployment/installation/centos.md
app/enterprise/2.3.x/deployment/installation/docker.md
app/enterprise/2.3.x/deployment/installation/kong-on-kubernetes.md
app/enterprise/2.3.x/deployment/installation/rhel.md
app/enterprise/2.3.x/deployment/installation/ubuntu.md
app/enterprise/2.3.x/deployment/licenses/deploy-license.md

@liyangau 
* Fix curl command for adding a license
* Add step to Dev Portal instructions to set up a license before enabling the Portal
* Clean up Dev Portal sections
* For Docker install: move Dev Portal URL env variable into Dev Portal section and split note
Doc ticket filed about incorrect curl command and confusing order of instructions causing errors.
[Deploy license ](https://deploy-preview-2681--kongdocs.netlify.app/enterprise/2.3.x/deployment/licenses/deploy-license/ )- curl command here
Dev Portal sections:
[Docker](https://deploy-preview-2681--kongdocs.netlify.app/enterprise/2.3.x/deployment/installation/docker/#step-7-optional-enable-the-dev-portal) 
[K8s](https://deploy-preview-2681--kongdocs.netlify.app/enterprise/2.3.x/deployment/installation/kong-on-kubernetes/#step-5-prepar …

[DOCS-1665] Fix license command and clean up Dev Portal setup

---

app/_data/docs_nav_ee_2.3.x.yml
app/enterprise/2.3.x/deployment/upgrades/migrate-ce-to-ke.md
app/enterprise/2.3.x/deployment/upgrades/migrations.md

@reviewer - TBD
@rainest @kallecaco3 suggested the Kong for kubernetes content be added to this doc for users upgrading to the next version of Kong. I selected some of the text from the [README.md](https://github.com/Kong/charts/blob/main/charts/kong/README.md#separate-admin-and-proxy-nodes) and [Upgrade.md](https://github.com/Kong/charts/blob/main/charts/kong/UPGRADE.md) docs that I think is relevant. Can you take a look and tell me if what I selected is appropriate or if more/less needs to be in this guide to help users upgrading on kubernetes? Thanks!
The upgrade guides for upgrading from 2.2.x to 2.3.x and 2.3.x OSS to 2.3.x Enterprise need updating after the 2.3.x release.
[DOCS-1582](https://konghq.atlassian.net/browse/DOCS-1582?focusedCommentId=38123&page=com.atlassian.jira.plugin.s …

[DOCS-1582] updated titles, version numbers, and minor formatting issues for 2.3.x

---

app/kubernetes-ingress-controller/1.0.x/guides/configuring-https-redirect.md
app/kubernetes-ingress-controller/1.1.x/guides/configuring-https-redirect.md

Like all our annotations, the [HTTPS redirect annotation](https://docs.konghq.com/kubernetes-ingress-controller/1.1.x/references/annotations/#konghqcomhttps-redirect-status-code) uses dashes, not underscores.
Community report from https://discuss.konghq.com/t/404-error-while-creating-kongconsumer-using-kubernetes-api-with-python/8038

Correct K8S HTTPS redirect annotation name

---

app/_data/docs_nav_konnect.yml
app/konnect/updates.md

@GayleNeumann 
* Moving Konnect SaaS Updates to a new Release Notes section; went with "Release Notes" instead of Updates for consistency with the rest of the docs - @GayleNeumann what do you think?
* Add a heading for the month and change subheading to international standard date format 
* Went back and forth between the ISO format (YYYY-MM-DD) or an abbreviated Month Day (Feb 28). Went with the ISO format, but could be convinced otherwise. 
* Entry for March 16th deploy
* New deploy of Konnect
* Getting feedback that updates are currently hard to find.
https://deploy-preview-2682--kongdocs.netlify.app/konnect/updates/

[DOCS-1673] Konnect updates 2021-03-16

---

app/enterprise/2.1.x/release-notes.md

https://konghq.atlassian.net/browse/DOCS-1684
https://deploy-preview-2694--kongdocs.netlify.app/enterprise/2.1.x/release-notes/#breaking-changes

[DOCS-1684]  legacy portal no longer supported 2.1 release notes

---

app/enterprise/2.1.x/deployment/classic-deployment.md
app/enterprise/2.2.x/deployment/classic-deployment.md
app/enterprise/2.3.x/deployment/classic-deployment.md

Anyone on the docs team can take a look at this. It is just a link fix.
Someone noticed that the link on the Classic Install page was redirecting to the wrong version. I noticed that part of the link was missing and it seems to have fixed it locally for me anyway. I looked and it was affecting all versions following 1.5 - seems like there was some rework.
DOCS-1674
Will include link to sample build when available.

[DOCS-1674] fixed link issue redirecting to wrong version

---

app/_includes/head.html

* conditionally add <link rel=“canonical”> in head of URL paths with versions directing to latest versioned pages for improved search indexing
Sample output:
* I've chosen to leave in self-referencing canonicals as this is acceptable practice and some argue it improves indexing structures.
* In order to fully ensure proper indexing after each version update it may be necessary to manually force a recrawl via Google Webmaster Tools

[DOCS-1564] Add canonical links for all version URLs

---

app/mesh/1.2.x/installation/helm.md
app/mesh/1.2.x/installation/kubernetes.md
app/mesh/1.2.x/installation/openshift.md

@subnetmarco lmk if older versions also need to be changed. This PR addresses only v1.2. These are the only instances grep found ...
BUT note also that the Helm instructions include a user-provided namespace, and we currently suggest `kong-mesh-system` ... potential new confusion?
Update names of mesh components
Inaccurate names currently published
Will post link to netlify preview after it builds

update names of mesh components

---

app/_hub/kong-inc/grpc-web/index.md

https://konghq.atlassian.net/browse/DOCS-1646 part of epic https://konghq.atlassian.net/browse/DOCS-1396.
Schema:
https://github.com/Kong/kong-plugin-grpc-web/blob/master/kong/plugins/grpc-web/schema.lua
https://deploy-preview-2705--kongdocs.netlify.app/hub/kong-inc/grpc-web/

[DOCS-1646] gRPC Web plugin add datatypes

---

app/getting-started-guide/2.3.x/dev-portal.md
app/getting-started-guide/2.3.x/expose-services.md
app/getting-started-guide/2.3.x/improve-performance.md
app/getting-started-guide/2.3.x/load-balancing.md
app/getting-started-guide/2.3.x/prepare.md
app/getting-started-guide/2.3.x/protect-services.md
app/getting-started-guide/2.3.x/secure-services.md

Switching Manager and Admin API tabs around.
Manager is available in free mode, and we want to promote it. 
https://konghq.atlassian.net/browse/DOCS-1690
https://deploy-preview-2707--kongdocs.netlify.app/getting-started-guide/2.3.x/prepare/ - sample topic in getting started guide, just flip through the pages to make sure Manager comes up as the first tab wherever it appears

[DOCS-1690] Switch Manager and Admin API tab order for 2.3.x

---

app/enterprise/1.5.x/admin-api/index.md
app/enterprise/2.1.x/admin-api/index.md
app/enterprise/2.2.x/admin-api/index.md
app/enterprise/2.3.x/admin-api/index.md

@reviewer
Add information about path_handling in the enterprise docs
Gaps in the docs between enterprise/OSS, got caught out during an upgrade from 0.x

Update enterprise docs with information on path_handling

---

app/_data/extensions/kong-inc/ldap-auth-advanced/versions.yml
app/_hub/kong-inc/ldap-auth-advanced/2.2.x.md
app/_hub/kong-inc/ldap-auth-advanced/index.md

https://konghq.atlassian.net/browse/DOCS-1636 part of epic https://konghq.atlassian.net/browse/DOCS-1396.
Schema:
https://github.com/Kong/kong-plugin-enterprise-ldap-auth/blob/master/kong/plugins/ldap-auth-advanced/schema.lua
https://deploy-preview-2708--kongdocs.netlify.app/hub/kong-inc/ldap-auth-advanced/
I noticed that the index file listed 1.3.x as the version, and there was also a 1.3.x file. I did a diff and ended up making the current index 2.2.x and then the current index is 2.3.x. @Murillo, please let me know if I should just delete 2.2.x. Also, can we skip the scope creep for required fields in this PR? There are multiple descriptions that state optional in the descriptions even though they have a default, and the schema does not explicitly say required:
- …

[DOCS-1636] ldap adv plugin datatypes

---

app/_assets/stylesheets/pages/docs.less
app/_layouts/docs-v2.html
app/_layouts/extension.html

Adding links to edit this page and open an issue to the right sidebar, above "On this page". 
Changing the existing links on the plugins layout to open in a new tab and directly to editing status.
Link to github was removed and overlooked during site redesign. Issue was recently brought up on Slack.
Netlify links TBA.

(no ticket) Add links to github from main doc set

---

app/_hub/kong-inc/datadog/index.md

https://konghq.atlassian.net/browse/DOCS-1647 part of epic https://konghq.atlassian.net/browse/DOCS-1396.
Schema:
https://github.com/Kong/kong-ee/blob/master/kong/plugins/datadog/schema.lua
This also references the typedefs schema.
https://deploy-preview-2711--kongdocs.netlify.app/hub/kong-inc/datadog/#parameters

[DOCS-1647] Datadog add datatypes

---

app/_hub/kong-inc/ldap-auth-advanced/index.md
app/_hub/kong-inc/ldap-auth/index.md

https://konghq.atlassian.net/browse/DOCS-1637  part of epic https://konghq.atlassian.net/browse/DOCS-1396.
This PR also adds xrefs and advertising of enterprise plugins per @eskibars request  https://konghq.atlassian.net/browse/DOCS-1417 (still in progress):
If anyone has better copy than the items above from the spreadsheets attached to that ticket, that would be most appreciated.
Schema:
https://github.com/Kong/kong-ee/blob/master/kong/plugins/ldap-auth/schema.lua
https://deploy-preview-2715--kongdocs.netlify.app/hub/kong-inc/ldap-auth/

[DOCS-1637] LDAP plugin datatypes; advertise enterprise version of plugin

---

app/enterprise/0.35-x/README.md
app/enterprise/0.36-x/README.md
app/enterprise/1.3-x/README.md
app/enterprise/1.5.x/README.md
app/enterprise/2.1.x/README.md
app/enterprise/2.2.x/README.md
app/enterprise/2.3.x/README.md

Removing empty readme files from enterprise pages.
These files aren't used for anything. Mostly, they just cause confusion when someone links to the source folder on github: for example, the README in 2.3.x says "Enterprise 1.5 Release; add your 1.5 documents to this folder".
Noticed this when someone on Slack said they were sending doc source links to customers.
N/A (purposely skipping netlify build on this as these files are not built with the site)

(no ticket) Remove empty readmes from ee docs [skip ci]

---

app/_hub/kong-inc/oauth2-introspection/index.md

https://konghq.atlassian.net/browse/DOCS-1640 part of epic https://konghq.atlassian.net/browse/DOCS-1396.
Schema links:
- https://github.com/Kong/kong-plugin-enterprise-oauth2-introspection/blob/master/kong/plugins/oauth2-introspection/schema.lua
- https://github.com/Kong/kong/blob/master/kong/db/schema/typedefs.lua (URL)
https://deploy-preview-2718--kongdocs.netlify.app/hub/kong-inc/oauth2-introspection/

[DOCS-1640] OAuth2 Introspection plugin add datatypes per schema

---

app/_hub/kong-inc/vault-auth/index.md

https://konghq.atlassian.net/browse/DOCS-1660 part of epic https://konghq.atlassian.net/browse/DOCS-1396.
Schema:
https://github.com/Kong/kong-plugin-vault-auth/blob/master/kong/plugins/vault-auth/schema.lua
https://deploy-preview-2706--kongdocs.netlify.app/hub/kong-inc/vault-auth/
@murillopaula i'm not sure about the vault.id:
>      { vault = { type = "foreign", reference = "vaults", required = true } },
what is foreign? I just think of a foreign key in relational db.

[DOCS-1660] Vault plugin add datatypes

---

app/_data/extensions/kong-inc/zipkin/versions.yml
app/_hub/kong-inc/zipkin/1.0.x.md
app/_hub/kong-inc/zipkin/1.1.x.md
app/_hub/kong-inc/zipkin/1.2.x.md
app/_hub/kong-inc/zipkin/index.md

https://konghq.atlassian.net/browse/DOCS-1653 part of epic https://konghq.atlassian.net/browse/DOCS-1396.
Schema link:
https://github.com/Kong/kong-plugin-zipkin/blob/master/kong/plugins/zipkin/schema.lua
https://deploy-preview-2713--kongdocs.netlify.app/hub/kong-inc/zipkin/ 
Doc reviewers: focus mainly on the index.md file for review. The older versions had some feedback applied as requested by the SME.
Reviewers: @gszr and @kikito I noticed that this plugin was recently updated to 1.3.x, so I bumped the version while I'm adding datatypes. I noticed some fields in the schema not in the docs, and some fields in the docs not in the schema. I noted that in the index file. I'll need new descriptions as I requested directly in the source. If you were planning to update the …

[DOCS-1653] Zipkin tracing plugin bump version, add missing configs (2.4 CE beta/GA), add datatypes

---

app/enterprise/changelog.md

I added the release notes for the [2.1.4.4](https://konghq.atlassian.net/wiki/spaces/FTT/pages/8356124/Kong+Enterprise+-+Changelog+Features+Release+Schedule#KongEnterprise-Changelog,Features&ReleaseSchedule-KongEnterprise2.1.4.4) and [2.2.1.1](https://konghq.atlassian.net/wiki/spaces/FTT/pages/8356124/Kong+Enterprise+-+Changelog+Features+Release+Schedule#KongEnterprise-Changelog,Features&ReleaseSchedule-KongEnterprise2.2.1.1) patch releases based on the Confluence changelog.
I have also added [1.5.0.10](https://konghq.atlassian.net/wiki/spaces/FTT/pages/8356124/Kong+Enterprise+-+Changelog+Features+Release+Schedule#KongEnterprise-Changelog%2CFeatures%26ReleaseSchedule-KongEnterprise1.5.0.10) and [2.3.3.0](https://konghq.atlassian.net/wiki/spaces/FTT/pages/8356124/Kong+Enterprise+-+Changelog …

[DOCS-1608][DOCS-1609] Patch release notes for 2.1.4.4, 2.2.1.1, and 1.5.0.10

---

.github/workflows/algolia.yml
.github/workflows/build-test.yml

Setting an if condition on the build/test and algolia index workflows so that they will only run in the public repo.
Working on introducing repo sync, which means I'll need to re-enable github actions on the docs private repo. Don't want every single action running in both repos.
N/A

(no ticket) Limit existing GH actions to public repo only

---

Gemfile.lock
package-lock.json

Update kramdown from 2.3.0 to 2.3.1.
https://kramdown.gettalong.org/news.html
Just check that nothing's broken anywhere. Kramdown is our markdown parser; if it's broken, you'll notice.
https://deploy-preview-2725--kongdocs.netlify.app/

(chore) Update kramdown

---

CONTRIBUTING.md
app/_assets/javascripts/app.js
app/_assets/stylesheets/page.less
app/_assets/stylesheets/pages/docs.less
app/enterprise/2.3.x/deployment/installation/docker.md
jekyll-dev.yml
jekyll.yml

Adding line numbers to codeblocks by default. 
With this feature, all codeblocks in the docs will have numbered lines. This will help authors call out specific content in the docs, and when referencing code examples externally (for support, for example). 
One-line codeblocks will also be numbered. This is mainly for visual consistency and alignment; it would also be a decent chunk of work to get one-liners to pick up a different style by default, so ideally we won't be doing that. 
You can disable line numbers for a codeblock by using liquid tags instead of fenced codeblocks.
Default (fenced code blocks):
\```bash
some code here
\```
To remove line numbers, use the `{% highlight %}` tag with an optional language class:
{% highlight bash %}
some code here
{% endhighlight %} …

[DOCS-1361] Line numbers for codeblocks

---

app/_assets/stylesheets/pages/docs.less
app/_layouts/docs-v2.html
app/_layouts/extension.html

Fixing links to edit this page and making a minor adjustment to line spacing.
Links to "edit this page" are going to the now non-existent `master` branch and not getting redirected to `main`.
Spot-check a couple of "edit this page" links and make sure they don't 404: 
https://deploy-preview-2732--kongdocs.netlify.app/enterprise/2.3.x/introduction/
https://deploy-preview-2732--kongdocs.netlify.app/hub/kong-inc/application-registration/

(no ticket) Fix edit this page links and adjust spacing

---

app/enterprise/changelog.md

@tyler-ball 
The Fast Track team released a patch release yesterday to fix an issue users were having when migrating from 1.5 to 2.1.
Need to add 2.1.4.5 patch release note to inform users of the fix.
[2.1.4.5 changelog](https://deploy-preview-2735--kongdocs.netlify.app/enterprise/changelog/#2145)

added ee 2.1.4.5 changelog entry

---

app/_hub/kong-inc/key-auth-enc/1.0.x.md
app/_hub/kong-inc/key-auth-enc/index.md
app/_hub/kong-inc/key-auth/0.2.x.md
app/_hub/kong-inc/key-auth/2.1.x.md
app/_hub/kong-inc/key-auth/2.2.x.md
app/_hub/kong-inc/key-auth/index.md
app/_includes/hub-examples.html

@ashosborne 
Add `value_in_examples` to display the desired array syntax for the `key_name` value in the key auth plugins.
Also fixing the extra blank space that appears before declarative config example arrays.
The `key_name` value is not displaying correctly in declarative examples. It should be an array.
See the declarative tab in
https://deploy-preview-2733--kongdocs.netlify.app/hub/kong-inc/key-auth-enc/ and
https://deploy-preview-2733--kongdocs.netlify.app/hub/kong-inc/key-auth/

(no ticket) Fix key_name syntax for key auth plugins

---

app/_hub/kong-inc/file-log/2.0.x.md
app/_hub/kong-inc/file-log/index.md
app/_hub/kong-inc/http-log/2.0.x.md
app/_hub/kong-inc/http-log/index.md
app/_hub/kong-inc/loggly/2.0.x.md
app/_hub/kong-inc/loggly/index.md
app/_hub/kong-inc/serverless-functions/index.md
app/_hub/kong-inc/syslog/2.0.x.md
app/_hub/kong-inc/syslog/index.md
app/_hub/kong-inc/tcp-log/2.0.x.md
app/_hub/kong-inc/tcp-log/index.md
app/_hub/kong-inc/udp-log/2.0.x.md
app/_hub/kong-inc/udp-log/index.md
app/_includes/md/plugins-hub/log_custom_fields_by_lua.md
app/_includes/md/plugins-hub/sandbox.md

@reviewer @Kong/team-docs 
- Create a `sandbox.md` include (with contents currently present in serverless-plugin sandbox section), to be shared among plugins that leverage Kong's sandbox
- Add new version to logging plugins - http-log, tcp-log, udp-log, file-log, syslog, loggly
- Add docs for "custom fields by lua" feature to logging plugins

docs(plugins) logging customizability

---

app/_hub/okta/okta/index.md

The Okta integration guide requires a Kong Enterprise license, as it makes use of the Kong OIDC Enterprise plugin
Document Okta integration guide as "enterprise" 
The Okta integration guide is not marked as enterprise, however the instructions in the guide requires you to have an enterprise account

Mark Okta as an enterprise integration

---

app/kubernetes-ingress-controller/1.0.x/concepts/ingress-versions.md
app/kubernetes-ingress-controller/1.1.x/concepts/ingress-versions.md
app/kubernetes-ingress-controller/1.2.x/concepts/ingress-versions.md

Add a controller field to the IngressClass example. Although we don't yet make use of this value in our implementation, Kubernetes requires it.
Fix #2585

fix(kic) correct IngressClass example

---

app/_hub/kong-inc/session/index.md

https://konghq.atlassian.net/browse/DOCU-679 part of epic https://konghq.atlassian.net/browse/DOCS-1396.
Schema link:
https://github.com/Kong/kong-plugin-session/blob/master/kong/plugins/session/schema.lua
Reviewer question: @murillopaula the default for cookie samesite is strict but there is no info in the schema really. The description is pretty thorough.
{ cookie_samesite = samesite },
https://github.com/Kong/kong-plugin-session/blob/61c23944a1beaf67fd3f752c70eac4cb6d5e1767/kong/plugins/session/schema.lua#L53
Actually nvm it is defined above
https://github.com/Kong/kong-plugin-session/blob/61c23944a1beaf67fd3f752c70eac4cb6d5e1767/kong/plugins/session/schema.lua#L11
https://deploy-preview-2746--kongdocs.netlify.app/hub/kong-inc/session/

[DOCU-679] Session plugin add datatypes

---

app/_hub/kong-inc/mtls-auth/index.md

https://konghq.atlassian.net/browse/DOCU-685 as part of epic https://konghq.atlassian.net/browse/DOCU-301. The doc jira board shuffling/renaming has deleted links to child tickets.
Schema link:
https://github.com/Kong/kong-plugin-mtls-auth/blob/master/kong/plugins/mtls-auth/schema.lua
https://deploy-preview-2751--kongdocs.netlify.app/hub/kong-inc/mtls-auth/

[DOCU-685] mTLS plugin add datatypes, formatting, editing

---

app/_data/docs_nav_ce_2.3.x.yml

Removing duplicate entry for kong.node.
Doing this manually, as we don't normally regenerate older docs.
https://github.com/Kong/docs.konghq.com/issues/2679
Fixed in 2.4.x (was an autodoc error).
TBA

Remove duplicate ToC entry
