Kong/docs.konghq.com

app/_includes/beta-banner.html, app/_includes/pages/download/docker.md, app/_includes/pages/download/osx.md, app/_includes/pages/download/other.md, app/docs/0.1.1beta-2/tutorials/installing-plugin.md, app/download/index.html, app/plugins/basic-authentication.md, app/plugins/file-log.md, app/plugins/key-authentication.md, app/plugins/rate-limiting.md, app/plugins/tcp-log.md, app/plugins/udp-log.md
or, can change the plugin to output to `{{site.latest}}`, but that felt wrong.
=> seems like the proper variable name here is {{site.data.kong_latest}}

app/_assets/stylesheets/base.less, app/_assets/stylesheets/page.less, app/plugins/basic-authentication.md, app/plugins/file-log.md, app/plugins/key-authentication.md, app/plugins/rate-limiting.md, app/plugins/tcp-log.md, app/plugins/udp-log.md
- Solidify and make tables consistent with those in documentation.
- Better describe auth parameters
=> chore(plugins): Fix parameter styles, fix code padding

app/_data/kong_versions.yml, app/_includes/pages/download/centos.md, app/_includes/pages/download/debian.md, app/_includes/pages/download/docker.md, app/_includes/pages/download/osx.md, app/_includes/pages/download/other.md, app/_includes/pages/download/ubuntu.md, app/_jekyll_plugins/versions.rb, app/docs/0.1.1beta-2/tutorials/installing-plugin.md, app/download/index.html, app/plugins/basic-authentication.md, app/plugins/file-log.md, app/plugins/key-authentication.md, app/plugins/rate-limiting.md, app/plugins/tcp-log.md, app/plugins/udp-log.md, gulpfile.js
Versions come from Mashape/kong `versions.sh` file, referencing all
dependencies versions for unit tests and packages.
=> [chore] add each dependency version in kong_versions.yml

app/_layouts/docs.html, app/docs/0.2.0-2/admin-api.md
=> Update admin-api.md with more details for PUT admin endpoint

app/_assets/javascripts/dropdown.js, app/_assets/stylesheets/dropdown.less, app/_assets/stylesheets/header.less, app/_assets/stylesheets/index.less, app/_assets/stylesheets/page.less, app/_includes/nav.html, app/_jekyll_plugins/versions.rb, app/_layouts/docs.html, app/docs/0.2.0-2/about/how.md, app/docs/0.2.0-2/about/plugins.md, app/docs/0.2.0-2/about/scaling.md, app/docs/0.2.0-2/about/what.md, app/docs/0.2.0-2/admin-api.md, app/docs/0.2.0-2/cli.md, app/docs/0.2.0-2/configuration.md, app/docs/0.2.0-2/getting-started/adding-consumers.md, app/docs/0.2.0-2/getting-started/adding-your-api.md, app/docs/0.2.0-2/getting-started/enabling-plugins.md, app/docs/0.2.0-2/getting-started/introduction.md, app/docs/0.2.0-2/getting-started/quickstart.md, app/docs/0.2.0-2/index.md, app/docs/0.2.0-2/tutorials/hello-world.md, app/docs/0.2.0-2/tutorials/installing-plugin.md, app/docs/0.2.0-2/tutorials/introduction.md, gulpfile.js
=> Docs versioning

app/docs/0.2.1/getting-started/enabling-plugins.md
=> chore(documentation): Change direction to statement

app/_jekyll_plugins/versions.rb, app/docs/0.2.1/about/how.md, app/docs/0.2.1/about/plugins.md, app/docs/0.2.1/about/scaling.md, app/docs/0.2.1/about/what.md, app/docs/0.2.1/admin-api.md, app/docs/0.2.1/cli.md, app/docs/0.2.1/configuration.md, app/docs/0.2.1/getting-started/adding-consumers.md, app/docs/0.2.1/getting-started/adding-your-api.md, app/docs/0.2.1/getting-started/enabling-plugins.md, app/docs/0.2.1/getting-started/introduction.md, app/docs/0.2.1/getting-started/quickstart.md, app/docs/0.2.1/index.md, app/docs/0.2.1/tutorials/hello-world.md, app/docs/0.2.1/tutorials/installing-plugin.md, app/docs/0.2.1/tutorials/introduction.md
- assumed latest, `/docs/` can also be accessed via `/docs/latest` and `/docs/x.x.x`
- assumed latest, `/docs/x.x.x/thing` can also be accessed via
`/docs/latest/thing`
=> [feature] true automatic versioning

app/_includes/pages/download/osx.md
Documentation for the upcoming release `0.3.0`.
=> Website for version 0.3.0

app/_includes/pages/download/osx.md, app/download/index.html
=> Add a link to the updating guide on /download

app/plugins/index.html
=> update rate limintg

app/plugins/index.html
Reverts Mashape/getkong.org#92
=> Revert "update rate limintg"

app/enterprise/index.html
=> enterprise plan  

app/_data/plugins.yml, app/docs/0.4.x/proxy.md, app/plugins/hmac-authentication.md, app/plugins/jwt.md, gulpfile.js
=> [docs/0.5.0] JWT plugin

app/_assets/stylesheets/footer.less, app/_layouts/default.html
Fix for a66946e9d181b9caf08d2f5a84de46ca7db3d120 making the footer overlap content.
=> fix(layout) footer overlapping content since

app/plugins/hmac-authentication.md
added details about `Clock Skew` in HMAC plugin doc
=> Added clock skew details for hmac plugin

app/_data/kong_versions.yml, app/install/index.html, app/plugins/galileo.md
- Galileo new how-it-works section
- document Galileo's new options
- UPDATE.md -> UPGRADE.md
- bump to Kong `0.5.4`
=> release: 0.5.4

app/docs/0.5.x/admin-api.md, app/docs/0.5.x/configuration.md
=> Improve documentation.

app/plugins/response-transformer.md
Updated doc to add details about append and replace
=> [docs/response-transformer] new config added

app/plugins/request-transformer.md
Updated doc to add details about append and replace
=> [docs/request-transformer] new config added

app/docs/0.8.x/plugin-development/custom-entities.md
Fixed markdown formatting issue.
https://getkong.org/docs/0.8.x/plugin-development/custom-entities/
@thefosk
=> Markdown formatting issue with docs

app/plugins/jwt.md
And slight rewording of the overall doc.
=> docs(jwt) spec support for RS256 verified tokens

app/plugins/correlation-id.md
I noticed this while reading and figured I'd file the PR.
=> Tiny typo update: too -> to

app/plugins/galileo.md
- Rename the plugin
- New config options
- New documentation and FAQ sections
**Opened against `master` but to be merged after `release/0.8.0`.**
=> docs(galileo) new plugin

app/community/index.html
@thibaultCha pls review and merge.
=> Updated community

app/enterprise/index.html
@thibaultCha pls review, merge and deploy.
=> enterprise update

app/community/index.html
This brings the list to 24 meetups around the world. Right now they're listed alphabetically, but we may want to consider grouping them by continent in the future.
=> feat(community): update meetup list

app/_includes/nav.html
- Add 'Sales:' to phone number link
- Change 'Contact Sales' to 'Request Demo'
=> feat(header): add descriptive text for sales phone number

app/_assets/stylesheets/page.less
Add hover effect, change tooltip to 'Chat with Kong Developers'.
=> feat(gitter): update sidecar button

app/docs/0.6.x/plugin-development/custom-logic.md, app/docs/0.7.x/plugin-development/custom-logic.md, app/docs/0.8.x/plugin-development/custom-logic.md
=> Fix typos in docs

Gemfile, app/_includes/footer.html
=> Removed Producthunt button from footer

app/plugins/oauth2-authentication.md
=> Fix minor typo

app/docs/0.9.x/plugin-development/admin-api.md
Hi!
When creating a plugin using the documentation I found the following error.
Cheers
Ruwen
=> Fixed broken example

app/plugins/statsd.md
Fixed namespace value for `response_size` metric
=> Fix response_size metric namespace

app/docs/0.10.x/admin-api.md, app/docs/0.10.x/loadbalancing.md
also added a loadbalancing reference.
Only added the file, as I couldn't figure out how those reference files are hooked into the site.
=> 0.10 Upstreams API reference

app/docs/0.10.x/admin-api.md, app/docs/0.10.x/configuration.md
Includes dns settings and the new `retries` property for apis.
=> 0.10 dns feature doc updates

app/docs/0.10.x/plugin-development/custom-entities.md, app/docs/0.10.x/plugin-development/plugin-configuration.md
=> document the unique constraint

app/docs/0.10.x/proxy.md
I plan to propose more changes... have to get on a call now... feel free to teach me how to do this better ;)
=> Updating proxy doc for clarity and grammar

app/_data/docs_nav_0.10.x.yml
Correct typo in sidebar navigation
=> docs(typo) - Sidebar navigation

app/plugins/hmac-authentication.md
=> docs(plugins) behavior change in HMAC plugin secret generation

app/plugins/cors.md
Documentation PR for https://github.com/Mashape/kong/pull/2203
=> docs(cors) update with multiple origins support

app/_includes/head.html
- fix code that fails echint test
=> fix(head): pass echint

app/_assets/stylesheets/footer.less, app/_includes/footer.html, app/enterprise/index.html
- also use https for meetup.com
=> fix(footer): add responsive fixes to lower footer

app/_data/docs_nav_0.10.x.yml, app/docs/0.10.x/auth.md
=> docs(auth) new auth reference

app/docs/0.10.x/admin-api.md
Clarify uniqueness requirement for consumer username and custom_id
=> docs(admin-api): clarify uniqueness requirement

app/plugins/jwt.md
As the title suggest, documenting how to delete a JWT credential for a consumer.
=> document how to delete a JWT credential for a consumer

.travis.yml
=> feat(travis): add travis build file

.editorconfig, .travis.yml, app/docs/0.10.x/plugin-development/distribution.md
=> fix(distribution): pass echint

app/_assets/stylesheets/page.less, app/_includes/footer.html
- Bring back subscribe form in footer area:
=> fix(footer): restore subscribe form

app/plugins/oauth2-authentication.md
=> specify time units for OAuth 2.0 plugin params

app/plugins/openwhisk.md
Note: merge once PR https://github.com/Mashape/kong-plugin-openwhisk/pull/3 is merged.
=> Fix(openwhisk) updated plugin rock name

app/_data/docs_nav_0.10.x.yml, app/plugins/aws-lambda.md
Generic doc improvements (Lambda plugin and Admin API)
=> fix(docs) improving docs

app/plugins/openwhisk.md
- Updated `timeout` description 
- Updated `keepalive` description
- Fixed some typo
=> docs(plugin/openwhisk) fix grammar and config description

app/_includes/head.html, gulpfile.js, package.json
Add my new npm package "gulp-resource-hints" to simplify resource hints building.
=> feat(gulp): add new gulp-resource-hints package

app/docs/0.10.x/plugin-development/entities-cache.md
The in lua-memory cache documentation is added as well as a problem
regarding the locking mechanism.
=> docs(cache) update the cache documentation

app/docs/0.10.x/plugin-development/custom-logic.md, app/docs/0.10.x/plugin-development/plugin-configuration.md
Goes in hand with https://github.com/Mashape/kong/pull/2354
=> docs(plugin-dev) added docs for rewrite_by_lua_block

app/docs/0.10.x/admin-api.md
- targets: delete by id see https://github.com/Mashape/kong/pull/2304
- api specific plugins: delete/patch by plugin name, see https://github.com/Mashape/kong/pull/2252
=> docs(routes) name or id updates

app/plugins/file-log.md, app/plugins/http-log.md, app/plugins/loggly.md, app/plugins/syslog.md, app/plugins/tcp-log.md, app/plugins/udp-log.md
Goes in hand with https://github.com/Mashape/kong/pull/2367
=> docs(log) logging plugins now also log the consumer

app/docs/0.10.x/admin-api.md
=> Updated supported content-type

app/plugins/rate-limiting.md
Add mention of Redis Sentinel support in Kong Enterprise
=> docs(rate-limiting) Redis Sentinel support

app/about/advantages.md, app/about/faq.md, app/about/pci-dss.md, app/about/who.html, app/community/index.html, app/docs/0.10.x/clustering.md, app/install/aws-linux.md, app/install/aws-marketplace.md, app/install/docker.md, app/install/heroku.md, app/install/vagrant.md
Fix some typos and suggest small changes.
=> fix(docs) fix typos

app/plugins/file-log.md, app/plugins/http-log.md, app/plugins/loggly.md, app/plugins/syslog.md, app/plugins/tcp-log.md, app/plugins/udp-log.md
=> docs(*) add blank lines

app/about/faq.md, app/docs/0.11.x/cli.md, app/docs/0.11.x/clustering.md, app/docs/0.11.x/configuration.md, app/docs/0.11.x/network.md, app/install/source.md
Decouples #448. This PR is only the Serf removal part. New Clustering Guide will be a separate PR.
=> docs(*) remove Serf references from 0.11.x docs

app/_layouts/default.html
Added Pardot tracking pixel per Maria request
=> Add SF Pardot tracking code to footer

app/docs/0.11.x/getting-started/enabling-plugins.md
Make the documented response match the behavior observed when running the commands with Kong 0.11.0rc2.
=> docs(enable-plugins) fix response in example

app/docs/0.11.x/configuration.md, app/docs/0.11.x/proxy.md
=> docs(*) new realip_module conf directives and proxied hop-to-hop

app/install/dcos.md
Merge will be on hold till the [Universe](https://github.com/mesosphere/universe/pull/1355) package for Kong is released.
=> docs(dcos) support for Kong v0.11.0

app/docs/0.11.x/plugin-development/plugin-configuration.md
When building a schema according to the example before my fix, the schema always fails validation.
=> fixed documentation for complex schemas

app/plugins/jwt.md, app/plugins/key-authentication.md
goes with https://github.com/Mashape/kong/pull/2857 and https://github.com/Mashape/kong/pull/2744
=> doc(plugin) add run_on_preflight option for JWT and Key_Auth

app/docs/0.11.x/configuration.md
goes with https://github.com/Mashape/kong/pull/2854
=> fix(conf) drop usage of lua_code_cache

app/docs/0.12.x/admin-api.md, app/docs/0.12.x/loadbalancing.md
goes with https://github.com/Mashape/kong/pull/2748
=> doc(balancer) drop the orderlist property

app/docs/0.11.x/configuration.md
Port of 91794b278c23187d2d1b7941c17a73275fe843a3 for the 0.11 version of
the configuration reference.
=> docs(configuration) serve assets alongside APIs for 0.11

app/install/docker.md
Setting environment variables to properly forward Kong logs to docker log collector.
=> docs(docker) adding log forwarding env variables

app/plugins/openwhisk.md
fix https://github.com/Mashape/kong/issues/2886.
=> fix(openwhisk) fix wrong host in example

app/install/docker.md
@shashiranjan84 if you are using interactive mode somewhere, please remove it.
=> fix(docker) removing interactive mode

app/docs/0.10.x/secure-admin-api.md, app/docs/0.11.x/secure-admin-api.md
update title for consistency with other docs pages
=> fix(docs) update title for consistency

app/_includes/subscribe.html
=> fix(newsletter subscribe): update form to pardot form

app/plugins/openwhisk.md
Just removes an extraneous "the" from a sentence.
=> Removed unnecessary word

app/_data/kong_versions.yml, app/docs/0.11.x/configuration.md, app/index.html, app/plugins/aws-lambda.md, app/plugins/jwt.md, app/plugins/key-authentication.md
Changelog: https://github.com/Kong/kong/blob/release/0.11.1/CHANGELOG.md#0111---20170824
=> Release: 0.11.1

app/_includes/footer.html, app/_includes/nav.html, app/install/index.html, app/plugins/index.html
Add redirects to plugins, install and footer links
=> refactor(urls): add redirects to konghq.com 

app/_includes/footer.html
Correct 2 urls and remove comment
=> fix(footer): Fix incorrect URLs and remove commented out image

app/docs/0.12.x/plugin-development/custom-logic.md
=> docs(*) invert tcp-log and request-termination priority

app/docs/0.10.x/plugin-development/custom-logic.md, app/docs/0.11.x/plugin-development/custom-logic.md, app/docs/0.12.x/plugin-development/custom-logic.md, app/docs/0.9.x/plugin-development/custom-logic.md
removed config from init_worker signature as it's not available at this point (nil value)
=> removed config from init_worker signature 

app/docs/0.13.x/proxy.md
First pass at updating the proxy guide. It is becoming clear that ideally, the information could now be organized in a more optimized way (this doc was written around a monolithic entity, "API"), but delaying such a rewrite for a later time.
=> docs(proxy) update proxy guide for Routes & Services

app/docs/0.12.x/admin-api.md
=> docs(0.12.x/admin-api) fix "Set target as unhealthy" endpoint

README.md, app/_assets/stylesheets/base.less, app/_assets/stylesheets/dropdown.less, app/_assets/stylesheets/page.less, app/_assets/stylesheets/pages/docs.less, app/_assets/stylesheets/variables.less, app/_includes/anchor_links.html, app/_includes/head.html, app/_layouts/docs.html
=> Add algolia 📃🔍docsearch to kong docs

app/docs/enterprise/0.31-x/installation/docker.md
Needed to update install doc to more easily enable Dev Portal.
=> Patch install guide for new Dev Portal

app/docs/0.12.x/health-checks-circuit-breakers.md
=> docs(healthchecks) correct Admin API health endpoint

app/docs/enterprise/0.31-x/plugins/rate-limiting.md
Cleaning up formatting after Zendesk export.
=> docs(ee) cleaning up formatting in EE rate-limiting

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md
Added github pull request/issue templates as well as contributing document.
* chore(git) add contributing/issue/pr templates
=> Add git contributing files

app/docs/enterprise/0.31-x/vitals.md, app/docs/enterprise/0.31-x/vitalsSpec_v0.31.yaml
This adds the Kong Vitals OpenAPI spec file for Kong EE 0.31.
=> docs(ee/vitals) add vitals 0.31 OAS file

CONTRIBUTING.md
Binary files should not be included in Pull Requests to this repo. This PR documents how to contribute binary files.
* [Edited contributing.md to warn against PR'ing binary files, and to detail how to contribute such files
=> Doc/contributing - add instructions for contributing binaries

app/docs/0.12.x/secure-admin-api.md, app/docs/0.13.x/secure-admin-api.md
Fix minor typo in `secure-admin-api.md`
=> docs(fix) fix typo in secure-admin-api.md

app/docs/enterprise/0.31-x/developer-portal/authentication.md
=> minor URL problem

app/docs/0.13.x/proxy.md
Fixing Typos on Proxy Reference to make sure formatting is working
Minor change on proxy documentation. Just two characters were added.
=> Missing two commas which were screwing up with formatting

app/docs/enterprise/0.31-x/developer-portal/introduction.md, app/docs/enterprise/0.31-x/kong-implementation-checklist.md
=> Aaronhmiller patch 1

app/docs/enterprise/0.31-x/vitals.md
Adds to know issues - upgrading 0.31 - Postgres - warning in logs
=> docs(ee/vitals) Adds 0.31 upgrade Postgres to known issues

app/docs/enterprise/0.31-x/getting-started/adding-consumers.md, app/docs/enterprise/0.31-x/getting-started/adding-your-api.md, app/docs/enterprise/0.31-x/getting-started/enabling-plugins.md
Fixes https://github.com/Kong/getkong.org/issues/668
=> docs(ee) responsive video width

app/plugins/openwhisk.md
=> docs(ee) typo

app/plugins/datadog.md, app/plugins/statsd.md
=> docs(plugin) typo fix

app/docs/enterprise/0.31-x/developer-portal/getting-started.md
with Jordan/Nick fixes --the guinea pig
Update link to tested Jordan/Nick fixes
* Updated link to 0.0.2 from 0.0.1
* Removed button
* Added "Preview"
Fix misleading guidance
=> bumping to 0.0.2

app/_data/kong_versions.yml, app/docs/0.13.x/network.md, app/index.html, app/plugins/jwt.md
=> release: 0.13.1

app/plugins/ee-forward-proxy.md
Update icon to existing icon that is not cut off.
=> fix(ee/plugins) update forward proxy icon

app/plugins/jwt.md
the url of verified claims was wrong.
=> modify jwt's doc--verified claims

app/plugins/jwt.md
Typo in one of the examples servies instead of services
* [Edited docs to fix the endpoint name in one of the examples]
=> Typo in one of the examples servies instead of services

app/docs/0.14.x/admin-api.md
Port of #698 to new `release/ce-0.14.0` branch
=> docs(admin) reflect SSL/SNI endpoint changes (params + PUT support)

app/docs/enterprise/0.31-x/installation/centos.md
Added additional information to clarify enterprise documentation.
=> Made enterprise docs more specific

app/install/kubernetes.md
=> docs(install) kubernetes

app/plugins/hmac-authentication.md
add documentation for pull request https://github.com/Kong/kong/pull/3347
* improved body validation section.
=> added documentation for pull request 3347

app/_data/docs_nav_ee_0.31-x.yml, app/docs/enterprise/0.31-x/kong-architecture-patterns.md
This document is ready to be published. There are graphics forthcoming.
=> Adding Architectural Pattern doc

app/docs/enterprise/changelog.md
* added new dev management features to the Admin GUI features section
=> docs(changelog) update Admin GUI changelog

app/install/docker.md
- Updated instructions to use the docker networking instead of the
deprecated --link flag
=> Updating Kong Docker installation docs

app/docs/0.13.x/getting-started/enabling-plugins.md
Fixing broken link in Enabling Plugins under Getting Started
=> fix(getting-started) correcting broken link

app/_data/docs_nav_ee_0.31-x.yml, app/docs/enterprise/0.31-x/kong-architecture-patterns.md
Updated html page's title tag.
=> UDS arch patterns

app/_assets/javascripts/app.js, app/_assets/stylesheets/header.less, app/_includes/nav.html
Adds cookie policy notification bar
=> feat(cookie-policy): Adds cookie policy acceptance header

app/_assets/javascripts/app.js, app/_assets/stylesheets/header.less
- Added margin to body when cookie policy bar is showing so it doesn't cover navigation. 
- Adjust cookie expiration
=> fix(cookie-policy): Adjust styling

app/docs/enterprise/0.32-x/installation/docker.md
Removed link for Dev Portal getting started. It was dead and isn't really necessary on 0.32, as you can view a working example immediately after install. Condensed instructions for visiting web GUIs as both work out of the box
=> docs(ee/docker-install) update Dev Portal steps for 0.32

app/docs/0.14.x/plugin-development/custom-logic.md
See https://github.com/Kong/kong/pull/3516 for more details
=> docs(ce/plugins) raise ip-restriction priority to 3000

app/_assets/javascripts/app.js
Fixes a typo in the function checking if the cookie policy cookie is set
=> fix(cookie-policy) Typo in check function

app/_data/docs_nav_ee_0.32-x.yml, app/docs/enterprise/0.31-x/installation/ubuntu.md, app/docs/enterprise/0.32-x/installation/ubuntu.md
Saw that Ubuntu was missing from right-hand install menu
* ported 0.31.x info into 0.32
missing install doc
- [/] [Commit message & atomicity](https://github.com/Kong/getkong.org/blob/master/CONTRIBUTING.md#commit-atomicity) checked
- [/] Documentation 
- [/] Spellchecked my updates. Plus I rarely mis-spell
- [/] Ready to be merged
=> re-adding Ubuntu install

app/_layouts/docs.html
Hide algolia search until their config is updated
=> fix(search) Temporarily hide algolia search

app/_layouts/plugin.html, app/plugins/ee-canary-release.md, app/plugins/ee-forward-proxy.md, app/plugins/ee-oauth2-introspection.md, app/plugins/ee-openid-connect-rp.md, app/plugins/ee-openid-connect.md, app/plugins/ee-proxy-caching.md, app/plugins/ee-rate-limiting.md, app/plugins/ee-request-transformer.md
Remove un-used "Report bug" buttons from EE plugin docs
=> docs(plugin) remove bug button

app/plugins/serverless-functions.md
Adds documentation for the Serverless Function plugins.
=> Serverless Functions

app/enterprise/0.32-x/getting-started/accessing-your-license.md
Update the 0.32 Accessing Your License doc
* Removed references to Gelato
* Removed references to older versions of Kong
* Add instructions for Free Trials Users
* Grammar adjustments
DEVX-175
=> DEVX-175: docs(ee-0.32): Update license doc and add Free Trials

app/googled7a99b1cae8a33d6.html
Google verification code needed to claim property in Google Search Console
* Created new html file app/googled7a99b1cae8a33d6.html
- [N/A] Documentation 
- [ N/A] Spellchecked my updates
- [ X] Ready to be merged 
#763
=> Add google verification for search console

app/googled7a99b1cae8a33d6.html
Fix content in google site verification file
google verification file was missing content. 
* edited app/googled7a99b1cae8a33d6.html
- [N/A] Documentation 
- [N/A] Spellchecked my updates
=> fix(google verification file)

app/docs/0.14.x/configuration.md
Documentation of the new method for injecting Nginx directives introduced in
Kong CE 0.14.
=> docs(ce/configuration) Injecting Nginx directives

app/plugins/ee-openid-connect.md
[x] Fixed annoying "Salesfoce" typo
* [Edited docs to fix typo on Salesforce's name that a prospect noticed]
typo
I know it's tiny, but it's little things that annoy me most sometimes.
=> Spell Salesforce properly

app/_layouts/plugin.html
=> Updated invalid link.

app/plugins/serverless-functions.md
- Escape comma in code sample
- Prefer form-data when submitting files
- Cleanup head-matter content
=> fix(serverless) address code snippet issues

app/0.14.x/configuration.md
Mention the newest C* LB policy.
Mention the newest C* LB policy in the docs, its lacking.
=> Update configuration.md with new C* lb policy info

app/enterprise/0.33-x/installation/docker.md
Update the Kong Enterprise Docker install page.
=> docs(ee/install) update docker install page

app/_data/docs_nav_ee_0.33-x.yml, app/enterprise/0.33-x/admin-gui/configuration/authentication.md, app/enterprise/0.33-x/admin-gui/configuration/managing-admins.md, app/enterprise/0.33-x/admin-gui/configuration/networking.md, app/enterprise/0.33-x/admin-gui/configuration/property-reference.md, package-lock.json
Add chapter on networking for the Admin GUI.
Please review the changes to `package-lock.json`: Are these expected and correct?
=> docs(admin-gui) add chapter on networking (INTF-187)

app/install/kubernetes.md
Mentioning K8S Ingress Controller in a better way.
=> docs(install) kubernetes ingress controller

app/plugins/acl.md
fix broken link for faq-authentication in acl plugin doc
fixes broken link to faq-authentication in acl-plugin documentation
* ...
Fix #XXX
=> docs(plugins) fix broken link

app/_includes/nav.html
PR for Issue https://github.com/Kong/docs.konghq.com/issues/806
Change Kong logo on docs.konghq.com to redirect to konghq.com
=> fix(url): Update logo url to homepage

app/enterprise/0.33-x/developer-portal/developer-access.md
Added clarification and link to the Developer Portal authentication page
=> fix(docs): Add note to developer access page

app/_assets/javascripts/app.js, app/_assets/stylesheets/cookie-policy.less, app/_assets/stylesheets/header.less, app/_assets/stylesheets/index.less, app/_includes/cookie-policy.html, app/_includes/head.html, app/_includes/nav.html
Move cookie policy from fixed header to floating card at bottom of screen
=> feat(cookie-policy) restyle cookie policy pop-out

app/enterprise/0.33-x/developer-portal/faq.md, app/enterprise/0.33-x/installation/docker.md
Add --volumes instructions to map license when using Docker on Windows.
* Edited docs to add guidance for Docker for Windows users based on user input
=> Add volume

app/enterprise/0.33-x/developer-portal/faq.md
Added a FAQ indicating when and how to configure CORS plugin for use with Dev Portal
* Edited docs to include CORS FAQ
=> added CORS FAQ

app/enterprise/0.33-x/plugins/rate-limiting-advanced.md
=> Fixing name of plugin in examples

app/enterprise/changelog.md
Update database version requirement in the Enterprise changelog.
=> docs(ee/readme) database version requirement

app/install/kubernetes.md
Kubernetes docs clarifications.
=> docs(install) Kubernetes clarifications

app/_assets/javascripts/app.js, app/_assets/stylesheets/base.less, app/_assets/stylesheets/header.less, app/_assets/stylesheets/kong-summit.less, app/_includes/nav.html, app/_includes/summit-banner.html
=> Fixed header and announcement section

app/enterprise/changelog.md
Add changes/fixes present in our upcoming release, 0.33-1.
=> docs(ee/changelog) 0.33-1 release

app/enterprise/0.33-x/admin-gui/configuration/authentication.md
The update makes it more specific the steps that need to be taken to get
the Admin GUI protected.
=> docs(ee/admin-gui) clarify Admin GUI auth config prerequisite 

app/_includes/fullstory.html, app/_includes/head.html
Add FullStory analytics to see where our website visitors are having trouble or not getting what they expect. 
* Adds FullStory JS
=> feat(*) add FullStory analytics

app/_data/docs_nav_ee_0.33-x.yml, app/enterprise/0.31-x/kong-architecture-patterns.md, app/enterprise/0.32-x/kong-architecture-patterns.md, app/enterprise/0.33-x/kong-architecture-patterns.md
Added images, updated page title.
=> docs(ee) Adding images to Arch patterns doc

app/_hub/wallarm/wallarm/index.md
Some issues were caused by the wallarm folder being capitalized, need a special git config setting locally to let git notice capitalization changes
=> fix(wallarm): Changed Wallarm folder capitalization

app/enterprise/0.32-x/developer-portal/customization.md, app/enterprise/0.33-x/developer-portal/customization.md
The word frequently was incorrectly spelled as Fequently
Corrected minor spelling mistake
* ...
Fix #XXX
=> fixed small spelling error

app/enterprise/0.33-x/admin-gui/configuration/authentication.md
Updated the curl command on the admin GUI auth page for adding the super-admin role to the ui user
* [Edited docs with correct curl]
=> docs(ee/admin-gui) update add role to ui user command

app/_assets/javascripts/app.js, app/_assets/stylesheets/index.less, app/_includes/nav.html
Remove announcement banner from all pages
* Removed announcement banner from nav.php
* Modified JS so that Installation button turns green on scrolling down 38px instead of 50px.
=> Remove announcement banner from all pages

app/0.10.x/admin-api.md, app/0.11.x/admin-api.md, app/0.12.x/admin-api.md, app/0.13.x/admin-api.md, app/0.14.x/admin-api.md, app/0.2.x/admin-api.md, app/0.3.x/admin-api.md, app/0.4.x/admin-api.md, app/0.4.x/tutorials/installing-plugin.md, app/0.5.x/admin-api.md, app/0.6.x/admin-api.md, app/0.7.x/admin-api.md, app/0.8.x/admin-api.md, app/0.9.x/admin-api.md, app/about/faq.md
=> docs(*) gallery to hub

app/0.14.x/logging.md, app/_data/docs_nav_0.14.x.yml
=> Docs(logging) reference

app/_hub/index.html
Make it easier to find out how to contribute to Kong Hub
=> docs(hub) link directly to contributing docs

app/_hub/index.html, app/_includes/head.html, app/_layouts/extension.html
Intercom (website chat) and Fullstory (website analytics) are no longer needed - but may be needed again in the future, hence the commenting out rather than deleting.
=> feat(*) remove Intercom and Fullstory

app/0.14.x/logging.md
Even though it looked fine in the preview, all the code blocks were not displaying properly. I think the reason is I did not skip a line before starting the ```
Added a line break at the start of each code bock
Should make the page usable which it is not in it's current form
=> fixed markdown

CONTRIBUTING.md
Add contributor t-shirt section to docs contrib guidelines
* Copied the t-shirt section from Kong/kong and added it in a similar location to CONTRIBUTING.md here
* Made minor edits to account for different repo
=> docs(contributing) Add t-shirt section

app/_data/extensions/kong-inc/rate-limiting-advanced/versions.yml, app/_hub/kong-inc/rate-limiting-advanced/0.31-x.md
Ports doc for EE 0.31 rate-limiting from old Plugins to new Hub.
=> Docs/rate limiting add EE 0.31

app/enterprise/changelog.md
=> fix(0.33-2): update changelog to include code snippets for portal

app/0.14.x/plugin-development/tests.md
=> Fixed typo

app/_hub/kong-inc/prometheus/index.md
=> docs(prometheus) typos and wording improvement

app/0.13.x/proxy.md, app/0.14.x/proxy.md, app/_hub/kong-inc/canary/0.31-x.md, app/_hub/kong-inc/canary/0.32-x.md, app/_hub/kong-inc/canary/index.md, app/_hub/kong-inc/jwt/index.md, app/_hub/kong-inc/oauth2/index.md, app/_hub/kong-inc/openid-connect/0.31-x.md, app/_hub/kong-inc/openid-connect/0.32-x.md, app/_hub/kong-inc/openid-connect/index.md, app/_hub/kong-inc/response-transformer/index.md, app/_hub/kong-inc/serverless-functions/index.md, app/_hub/optum/kong-upstream-jwt/index.md, app/_hub/zillowgroup/kong-terraform/index.md
Fix spelling
* Edited docs to fix spelling
- [N/A] Documentation
=> docs(*) Fix some typos

app/enterprise/0.31-x/plugins/rbac-api.md, app/enterprise/0.32-x/plugins/rbac-api.md, app/enterprise/0.33-x/rbac/admin-api.md
Adding needed blank line to display tables as such.
=> fix(rbac) display tables correctly

README.md
=> Update links to use secure https

app/0.14.x/plugin-development/index.md
=> Fixed Typos

app/about/advantages.md, app/about/benchmark.md, app/about/faq.md, app/about/index.md, app/about/pci-dss.md, app/about/who.html, app/community/index.html, app/license/index.md
=> chore(*) add dead code warning

app/0.14.x/plugin-development/custom-logic.md
There was a small typo in the file.
* Fix the small typo
=> docs: fix typo

app/_hub/peter-evans/paseto/index.md
I edited markdown in order to render tables appropriately 
* Removed some pipes `|` and spaces to make tables looks good
Fix #906
=> Fix akward formatting in tables in Hub pages

app/0.10.x/getting-started/quickstart.md, app/0.11.x/getting-started/quickstart.md, app/0.12.x/getting-started/quickstart.md, app/0.13.x/getting-started/quickstart.md, app/0.14.x/getting-started/quickstart.md, app/0.8.x/getting-started/quickstart.md, app/0.9.x/getting-started/quickstart.md
Great project! While reading the quickstart, I noticed this grammatical error that could be improved.
* Improve wording in quickstart.md
No pertaining issue
- [ X ] [Commit message & atomicity](https://github.com/Kong/docs.konghq.com/blob/master/CONTRIBUTING.md#commit-atomicity) checked
- [ X ] Documentation 
- [ X ] Spellchecked my updates
- [ X ] Ready to be merged
=> docs(ce/quickstart) improve wording in quickstart

app/0.14.x/admin-api.md, app/0.14.x/auth.md, app/0.14.x/configuration.md, app/0.14.x/getting-started/adding-consumers.md, app/0.14.x/getting-started/configuring-a-service.md, app/0.14.x/getting-started/enabling-plugins.md, app/0.14.x/getting-started/introduction.md, app/0.14.x/getting-started/quickstart.md, app/0.14.x/health-checks-circuit-breakers.md, app/0.14.x/logging.md, app/0.14.x/network.md, app/0.14.x/plugin-development/access-the-datastore.md, app/0.14.x/plugin-development/admin-api.md, app/0.14.x/plugin-development/custom-entities.md, app/0.14.x/plugin-development/custom-logic.md, app/0.14.x/plugin-development/entities-cache.md, app/0.14.x/plugin-development/file-structure.md, app/0.14.x/plugin-development/plugin-configuration.md, app/0.14.x/plugin-development/tests.md
This PR follows from #984. Here, I have added Back to TOC link to all sections in all markdown files of app/0.14.x
* ...
Fix #XXX
=> Add Back to TOC link to all files of 0.14.x

app/install/vagrant.md
Fix formatting for host ports
* ...
Fix #XXX
=> vagrant.md: Fix formatting

app/_hub/tomkerkhove/microsoft_azure/index.md
Improve Bitnami information for Azure Kong Single-VM and Cluster solutions.
=> Improve Bitnami information for Kong in Azure

app/enterprise/0.34-x/deployment-guide.md
Prioritizes the change from Key Authentication to Basic Authentication on the list of considerations before upgrading to 0.34
* Moved the bullet point about Key Authentication to the top of the list
=> docs(ee/upgrade) prioritize note about key auth

app/enterprise/0.34-x/installation/docker.md
Updates Docker installation guide for EE 0.34
- Updates env variables for Dev Portal
- Adds clarification for Kong Manager in Enabling RBAC
- Reformats the file to adhere to the 80 character line limit.
=> fix(docs): Update 0.34 Docker Install Guide"

app/enterprise/0.34-x/kong-manager/configuration/authentication.md
Corrects the step referred to from "2" to "1".
=> docs(ee/auth) correct step in how-to guide

app/enterprise/0.34-x/getting-started/quickstart.md, app/enterprise/0.34-x/kong-manager/configuration/authentication.md
Move the migrations step from Kong Manager authentication to
the Quick Start guide. Describe how to create a super admin
via KM if you didn't do it via migrations.
Note: I didn't find any documentation about creating admins from the Organization page. Ideally this PR would include a link to such a doc, maybe with screenshots. For now, I've just described the steps here.
=> docs(admins) update instructions for creating super admins

app/enterprise/changelog.md
All features, changes, and fixes for Kong Enterprise v 0.34-1
=> docs(changes) changelog for 34-1

app/enterprise/0.34-x/kong-manager/organization-management/managing-admins.md
Provides instructions for how to invite an Admin from the Organization page
=> docs(organization) invite admin inst.

app/1.0.x/index.md, app/1.0.x/streams-and-service-mesh.md
Adds `Streams and Service Mesh` tutorial.
=> docs(*) add streams and service mesh tutorial

app/1.0.x/configuration.md
Adding docs for [kong:3716](https://github.com/Kong/kong/pull/3716l)
* Added docs for keepalive disable
- [Y] [Commit message & atomicity](https://github.com/Kong/docs.konghq.com/blob/master/CONTRIBUTING.md#commit-atomicity) checked
- [Y] Documentation
- [Y] Spellchecked my updates:
- [IDK] Ready to be merged <
First PR on docs. Lemmeno if I missed anything.
=> feat(conf) Adding documentation for keepalive disable

app/_hub/heroku/kong-app/index.md
Heroku deployment upgraded to Kong 1.0.
* Update "Kong Heroku app" Hub article for current release.
=> Heroku deployment upgraded to Kong 1.0

app/_hub/kong-inc/key-auth/index.md
=> docs(key-auth) fix endpoint in example

app/enterprise/0.34-x/kong-manager/overview.md
Fix the links on the overview page.
*  Add `/kong-manager/` to the path
Fix #1110
=> fix(ee/links) fix links on manager overview page

app/_assets/css/hub.css, app/_includes/nav.html
-update hover states/pseudo elements to avoid overlap
-update mobile nav to remove redundancies
-adjust spacing on mobile nav for hub.css
=> (fix) hover updates to full width subnav

app/_hub/apifortress/index.md
Kong Hub page for the API Fortress Kong Plugin
Added app/_hub/apifortress/index.md
N/A
=> Added API Fortress Hub Contribution

app/_assets/css/hub.css, app/_assets/stylesheets/footer.less, app/_includes/footer.html, app/_includes/head.html, app/_includes/subscribe.html
Update footer for consistency with konghq.com
* strip newsletter bar from internal pages and place in footer column
* adjust column widths & breakpoints
* update footer styles for consistency
* add reCaptcha to footer form
=> feat(footer) update

app/enterprise/0.34-x/property-reference.md
=> docs(ref-prop) fix header

app/_assets/stylesheets/footer.less, app/_assets/stylesheets/header.less, app/_assets/stylesheets/pages/docs.less
Kong / Kong Enterprise toggle required padding for visibility on breakpoints lower than 1080px
* Update padding on navigation toggle
* Update absolute positioning on edit button
- [x ] [Commit message & atomicity]
- [x ] Documentation 
- [x ] Spellchecked my updates
- [ x] Ready to be merged <!-- In your opinion, is this ready to be merged as soon as it's reviewed?
=> update header padding on mobile

app/_hub/kong-inc/ldap-auth-advanced/0.33-x.md, app/_hub/kong-inc/ldap-auth-advanced/index.md, app/enterprise/0.33-x/admin-gui/configuration/authentication.md, app/enterprise/0.34-x/kong-manager/configuration/authentication.md
* truncate relevant line to 80chars
* add search/bind_dn section to hub plugin page
* add bind_dn config to kong manager ee example/instructions
=> docs(ee/manager) add more context around bind_dn/search INTF-651

app/_assets/stylesheets/pages/docs.less, app/_includes/footer.html, app/_includes/head.html
* update edit button positioning for tablet and mobile widths
* add simple JS alert message for reCaptcha failure
* edited styles to reposition error message\
- [x ] [Commit message & atomicity](https://github.com/Kong/docs.konghq.com/blob/master/CONTRIBUTING.md#commit-atomicity) checked
- [ N/A] Documentation 
- [x ] Spellchecked my updates
- [ x] Ready to be merged 
]
=> (fix) update edit button positioning

app/enterprise/0.31-x/installation/amazon-linux.md, app/enterprise/0.31-x/installation/centos.md, app/enterprise/0.32-x/installation/amazon-linux.md, app/enterprise/0.32-x/installation/centos.md, app/enterprise/0.33-x/installation/amazon-linux.md, app/enterprise/0.33-x/installation/centos.md, app/enterprise/0.34-x/installation/amazon-linux.md, app/enterprise/0.34-x/installation/centos.md
Clarify how to obtain a Bintray username from an access key.
=> docs(ee/install) clarify centos/amazon linux instructions

app/_includes/nav.html, app/enterprise/0.34-x/rbac/admin-api.md
Typos in Nav and RBAC admin-api broken tables
* [Edited app/_includes/nav.html]
* [app/enterprise/0.34-x/rbac/admin-api.md]
Support ticket 3172
=> docs(ee/*) fix typos and broken tables

app/_includes/footer.html, app/_includes/nav.html
* add Community items to header & footer nav for consistency with KongHQ
* update to header nav verbiage per Marco
* edit header.html & footer.html
- [N/A] Documentation
=> update header and footer nav items

app/enterprise/0.33-x/deployment-guide.md, app/enterprise/0.34-x/deployment-guide.md
Add ports for Dev Portal over HTTP and HTTPS.
* Add ports for Dev Portal HTTP and HTTPS
* Update formatting and links of other references.
(internal)
=> docs(ports) add dev portal ports, update format

app/enterprise/0.34-x/rbac/examples.md
Since a user may have already created the Super Admin during migration in the Getting Started guide, and since the process is less involved, we should provide a note with a link before these steps.
* Provide note with a link to Getting Started guide
* Divide section for Enforcing RBAC to allow the reader to skip ahead if needed
**Work in Progress**
Questions:
Do we want to keep the old section below the note at all? (lines 36-81)
=> docs(ee/rbac-ex) link to getting started guide

app/enterprise/0.34-x/getting-started/adding-your-api.md
Update the video for creating a new service and route so that it uses the Kong Manager interface for Enterprise 0.34.
To test, watch the video here: https://5c5b69241e33d7000c381596--kongdocs.netlify.com/enterprise/0.34-x/getting-started/adding-your-api/
=> docs(ee/34/add-service) update video for 34

app/enterprise/0.34-x/getting-started/adding-consumers.md
Update video in Getting Started: Creating Consumers to use 0.34 UI.
=> docs(ee/34/plugins) update video for consumers

app/enterprise/0.34-x/kong-manager/configuration/authentication.md
Add a video for creating a Super Admin in Kong Manager using the Organization page
See the video here: https://5c5b859a18afcf0008ddcb60--kongdocs.netlify.com/enterprise/0.34-x/kong-manager/configuration/authentication/#how-to-set-up-a-super-admin
=> docs(ee/34/auth) add video for creating super admin

app/1.0.x/plugin-development/distribution.md
It's confusing to know when the plugin will take effect util I have read the message [Kong](https://discuss.konghq.com/t/when-is-the-kong-plugin-take-effect/2515/4). 
Make it more clear for people to understand when the plugin will take effect.
Nothing
=> describe load plugin with more detail.

app/enterprise/0.34-x/kong-manager/organization-management/workspaces.md
Add a video demonstrating how to create a workspace from the Overview dashboard, as well as the resulting default Roles that are visible in the Admins section.
=> docs(ee/34/km) add video for workspaces creation

app/enterprise/0.34-x/kong-manager/configuration/authentication.md
Adds a video to show the logout/login flow.
=> docs(ee/34/manager) add video for logout and login

app/enterprise/0.34-x/kong-manager/organization-management/rbac-and-perms.md
Add a video depicting RBAC Role creation, along with adding negative permissions
=> docs(ee/34/rbac) add video for rbac role creation

app/_assets/stylesheets/pages/docs.less
- N/A Documentation 
- N/A Spellchecked my updates
=> style(algolia) remove terrible styling

app/_assets/stylesheets/footer.less, app/_includes/footer.html
Very simple replacement form embed generated directly from Pardot for better spam protection via reCaptcha (no need to validate responses as with manual forms)
* better prohibit spam signups using pardot’s baked-in recaptcha validation
* update form styles and social icon positioning, with minor responsive adujstments
Fix #XXX
=> add pardot iframe form to footer

gulpfile.js
Adds the hub css gulp task to the general gulp build task to ensure hub updates always take effect
* gulpfile.js
=> fix(Gulpfile) Add hub task to build task

app/enterprise/0.34-x/kong-manager/organization-management/workspaces.md
Add video to delete a workspace.
=> docs(ee/34/ws) add video for deleting a workspace

app/enterprise/0.34-x/kong-manager/organization-management/managing-admins.md
Reuse a video of adding an Admin from the Organization tab.
=> docs(ee/34/admins) use video: add admin on org pg

app/0.10.x/loadbalancing.md, app/0.11.x/loadbalancing.md, app/0.12.x/loadbalancing.md, app/0.13.x/loadbalancing.md, app/0.14.x/loadbalancing.md, app/1.0.x/loadbalancing.md
Fixes typo and casing in the **Load Balancing Reference** title.
=> docs(ce/load-balancing) fix title

app/1.0.x/plugin-development/tests.md
The documentation for spec/kong_tests.conf is not clear.
* Fixed documentation for spec/kong_tests.conf
Fix #1165
=> docs(ce/plugin-development) fix documentation

app/1.0.x/configuration.md
=> Corrected markdown, links

app/_hub/kong-inc/jwt/0.1-x.md
Stumbled across a really ugly typo during a demo today that I cannot live another minute without fixing!
* Edited docs to fix misspelling of value and removed repetition
n/a
=> fixed ugly typo

app/_hub/kong-inc/jwt/index.md
Updated current version to fix spelling
* Edited doc to fix spelling error
=> fix mispelling

app/_assets/stylesheets/page.less, app/_hub/kong-inc/request-transformer/0.1-x.md, app/_hub/kong-inc/request-transformer/index.md
Fixes table formatting in Request Transformer plugin that was causing unstyled tables and accidental header in navigation.
* Add spaces after each table row
* Add | before each row in a table with an empty cell
* Mirror changes in all versions
=> style(reqtran) fix broken tables

app/enterprise/0.34-x/kong-manager/organization-management/managing-admins.md
Fixed incorrect instructions. Username and email do not need to be the same. 
Removed incorrect instructions.
=> fix(docs) updated inaccurate instructions

app/_hub/kong-inc/rate-limiting-advanced/index.md
Added a link for betting understanding of how rate limiting works.
I added this link to the rate-limiting advanced plugin page: https://docs.konghq.com/enterprise/0.34-x/rate-limiting/
Added link (https://docs.konghq.com/enterprise/0.34-x/rate-limiting/) to rate limiting advanced documentation page.
=> Added link to advanced rate limiting plugin documentation page

README.md, app/1.1.x/admin-api.md, app/1.1.x/configuration.md, autodoc-admin-api/data.lua, autodoc-admin-api/run.lua, autodoc-conf/data.lua, autodoc-conf/parser.lua, autodoc-conf/run.lua, gulpfile.js, package.json
This PR includes:
* A regeneration of the Admin API docs for 1.1.x
* A new autodoc module for configuration.md
* Regeneration of configuration.md file using the new autodoc module
=> docs (1.1.x) admin api and conf

.github/PULL_REQUEST_TEMPLATE.md
Adds style guide adherence to PR template checklist
* ...
Fix #XXX
=> Add Style Guide to PR template

app/0.13.x/getting-started/adding-consumers.md
=> Grammar Correction

STYLEGUIDE.md
=> docs(style) remove duplicate sentence fragment

STYLEGUIDE.md
see "explanatory guides" above
The section title should be lowercase; I missed this one in PR review.
=> docs(style) lowercase section

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md
I created "Team Docs" as a new Kong team for the purpose of being tagged as reviewers on doc PRs. This should help speed up reviewing as PRs are less likely to be submitted without any reviewers designated.
* Added check to PR template checklist
* Added check to CONTRIBUTING PR guidelines
Fix #XXX
- [X ] [Commit message & atomicity](https://github.com/Kong/docs.konghq.com/blob/master/CONTRIBUTING.md#commit-atomicity) checked
=> fix(docs) - add team docs

app/enterprise/0.34-x/installation/docker.md
The Docker guide contains RBAC steps that are outdated/confusing. It also references other guides and links that do not help in installation. Since users will still need to be following the guide, external links (e.g., to bintray) should open in a separate window. Otherwise, readers will get lost/frustrated with navigating back and forth.
* Removed unneeded / broken links and steps
* Clarified order and separation of steps
* Reworded confusing segments
Pending review from @levfishbluefish and responses on any remaining comments/concerns
=> docs(docker-install) revise docker installation guide

app/1.0.x/plugin-development/custom-entities.md
This change includes updates on both the Upgrade Guide and the Plugin
Development Guide for Kong 1.0.x
=> docs(1.0.x) document how to use the new migrations

app/1.1.x/plugin-development/custom-entities.md
This change includes modifications to the Upgrade Guide and the Plugin Generation Guide.
Reproduces #1200 for the 1.1.x release.
=> docs(1.1.x) new migrations

app/_assets/stylesheets/header.less, app/_includes/nav.html, app/_layouts/default.html
Add double nav/OSS nav for consistency w/ konghq.com
* add OSS nav & necessary styles (desktop width only)
* add scripts to collapse nav on scroll
* adjust nav breakpoints
* adjust page padding to accomodate nav
=> Add OSS nav

app/_includes/header.html
Added missing alt text to header logo
=> added missing alt text

app/1.1.x/network.md
Small update to network and firewall guide about `stream` proxying.
=> docs(*) update network and firewall tutorial with stream proxying

app/1.1.x/streams-and-service-mesh.md
Updates Streams and Service Mesh docs with changes from Kong `1.1`.
=> docs(*) update streams and service mesh to 1.1

STYLEGUIDE.md
Following @nijikokun's [comment](https://github.com/Kong/docs.konghq.com/pull/1202#discussion_r270528764) on using line-level formatting, this PR adds entries for bold text and code formatting. 
* Add entry for bold text
* Add entry for headings
* Add entry for in-line code
* Add entry for code blocks
* Reformat examples to match new rules
* Bonus: break lines of existing entries
=> docs(styleguide) entries on formatting

app/enterprise/0.34-x/kong-manager/organization-management/managing-admins.md
Fixes the verb tense of 'send'
=> docs(org-man) fix typo

app/enterprise/0.34-x/kong-manager/organization-management/managing-admins.md
Removes inaccurate warning; @UkiahSmith made a similar fix recently.
=> docs(ee/man-admins) remove obsolete warning

app/1.1.x/db-less-and-declarative-config.md
=> fix(core/db-less) change `to` -> `write`

app/1.0.x/admin-api.md
The formatting is incorrect for the table of contents.
* ...
Fix #XXX
=> docs(ce/admin-api) turn off table of contents

STYLEGUIDE.md
Changes the rule for numbering to reflect what is more consistent and easy to read. After examining many different contexts in our docs and exchanging feedback with a copyeditor, using digits instead of written-out numbers seemed like the better course.
There were also some lingering inconsistencies, both in rules and in examples, that are updated.
* Alters **numbering** rules to use digits instead of written-out words.
* Fixes punctuation, formatting, and sentence structure for many rules.
* Enforces consistency with the latest rules, especially for entity names in bold text.
Fix #XXX
=> docs(styleguide) update numbering rule and all rule formatting

CONTRIBUTING.md, TECHNICAL-WRITING-GUIDE.md
Add Kong's Technical Writing Guide to the docs repo
* Adds "TECHNICAL-WRITING-GUIDE"
Fix #XXX
=> docs(feat): Add Technical Writing Guide

app/enterprise/0.34-x/kong-manager/configuration/authentication.md
Clarifies configuration, what *not* to do (i.e. to not rely on or point to the Plugin doc), and how users will be mapped to the AD after the configuration is set.
Clarifies configuration, what *not* to do (i.e. to not rely on or point to the Plugin doc), and how users will be mapped to the AD after the configuration is set.
=> docs(ee/34/km-ldap) clarify LDAP auth for Manager

templates/how-to.md
Creates the `template` directory and adds the `how-to` guide template
* Creates `/templates`
* Adds `/templates/how-to.md`
Fix #XXX
=> docs(feat): How To Template

app/1.1.x/plugin-development/custom-entities.md
This replicates #1205 for 1.1.x
=> docs(1.1.x) document new schema in Plugin Development Guide

app/_includes/nav.html
* display /install/ or /request-demo/ conditionally based on user’s current location, for Kong/Kong Enterprise respectively
* edited nav.html only
- [N/A] Documentation
=> conditionally display alternate header CTA

app/_hub/kong-inc/prometheus/0.1-x.md
=> docs(prometheus) update the custom server block snippet

app/install/aws-linux.md
internal development copy-pasta mistake
=> fix(aws) made a typo in the aws installation instructions

.travis.yml
=> Bump node version

app/_data/docs_nav_ee_0.34-x.yml, app/enterprise/0.34-x/kong-aws.md
Provides a guide to make it easier for AWS customers to use Kong. 
* Add AWS Deployment guide to Guides and References
* Add navigation
=> docs(ee/34/aws-deployment) add AWS guide and best practices

app/install/aws-cloudformation.md
Add guide for stack creation in db-less mode
* Updated installation guide for cloudformation
=> docs(installation/cloudformation) guide for db-less mode

app/1.0.x/plugin-development/access-the-datastore.md, app/1.0.x/plugin-development/custom-entities.md, app/1.0.x/plugin-development/custom-logic.md, app/1.0.x/plugin-development/distribution.md, app/1.0.x/plugin-development/entities-cache.md, app/1.0.x/plugin-development/file-structure.md, app/1.0.x/plugin-development/index.md, app/1.0.x/plugin-development/plugin-configuration.md, app/1.0.x/plugin-development/tests.md, app/1.1.x/plugin-development/access-the-datastore.md, app/1.1.x/plugin-development/custom-entities.md, app/1.1.x/plugin-development/custom-logic.md, app/1.1.x/plugin-development/distribution.md, app/1.1.x/plugin-development/entities-cache.md, app/1.1.x/plugin-development/file-structure.md, app/1.1.x/plugin-development/index.md, app/1.1.x/plugin-development/plugin-configuration.md
Updates the plugin development guide to `1.x`.
=> docs(*) update plugin development guide to 1.x

README.md, templates/how-to.md
This reverts commit 32baa48573f9f6bf2f5e2b4fdbb44651ba923ff6.
* ...
Fix #XXX
=> docs(*) retract new grammatical/stylistic errors

app/_hub/kong-inc/request-validator/index.md, app/_hub/kong-inc/response-transformer-advanced/index.md
- Add docs for the request-validator plugin
- Minor fixes in response-transformer-advanced plugin docs
=> docs(plugins) new plugins docs

app/enterprise/changelog.md
=> docs(changelog) list changes for 35

app/_data/docs_nav_ee_0.35-x.yml
=> docs(35/nav) remove unused links

app/_data/docs_nav_ee_0.35-x.yml, app/enterprise/0.35-x/kong-manager/overview.md
(Needs to go in before next deploy)
* ...
Fix #XXX
=> docs(35/nav) remove unused admins page from nav

app/_data/docs_nav_ee_0.35-x.yml, app/enterprise/0.35-x/plugins/vault-auth.md
=> fix(plugin/vault) add redirect page

app/_data/docs_nav_ee_0.35-x.yml, app/enterprise/0.35-x/plugins/route-by-header.md, app/enterprise/0.35-x/plugins/route-by-headers.md
=> fix(35/nav) off-by-one fix for "route by header"

app/_hub/tomkerkhove/microsoft_azure/index.md, app/_hub/tomkerkhove/microsoft_azure_container_instances/index.md
Support 0.13, 0.15, 1.0 & 1.1 for `Microsoft Azure Container Instances` & ` 
Microsoft Azure` Deployment Plugins.
* Added support for Kong 0.13, 0.15, 1.0 & 1.1
N/A
Relates to https://github.com/tomkerkhove/kong-deployment-on-azure/issues/5
=> Microsoft Azure Deployments - Support 0.13, 0.15, 1.0 & 1.1

app/enterprise/0.35-x/kong-manager/administration/rbac/new-role.md
=> docs(35/km/new-role) fix links in "prerequisites"

app/_data/docs_nav_ee_0.35-x.yml
Updates url for managing developers and adding new registration field docs
=> Fix Dev Portal navigation 404s

app/enterprise/0.34-x/getting-started/quickstart.md, app/enterprise/0.35-x/getting-started/start-kong.md
=> docs(*/start) clarify kong_admin migration limits

app/_data/docs_nav_ee_0.35-x.yml, app/enterprise/0.35-x/plugins/allowing-multiple-authentication-methods.md, app/enterprise/0.35-x/plugins/oidc-auth0.md, app/enterprise/0.35-x/plugins/oidc-google.md
Resolves missing page errors from navigation links
=> fix(35/*) fix all navigation 404s

app/_hub/kong-inc/file-log/0.1-x.md, app/_hub/kong-inc/http-log/0.1-x.md, app/_hub/kong-inc/syslog/0.1-x.md, app/_hub/kong-inc/tcp-log/0.1-x.md, app/_hub/kong-inc/udp-log/0.1-x.md
Goes in hand with https://github.com/Kong/kong/pull/4581 and https://github.com/Kong/kong/pull/4626
=> docs(plugins) adding new tls field

app/enterprise/0.35-x/getting-started/start-kong.md, app/enterprise/0.35-x/kong-manager/authentication/super-admin.md
Instructions on how to create a super admin and enable kong manager gui auth after Kong installation where kong password is not set (no default kong-admin created). Customers are frequently starting evaluations w/out setting up a default kong super admin and are struggling creating and enabling a super admin post installation. This update provides more specific details on how to do so that we can send to evaluators when needed.
Customers are frequently starting evaluations w/out setting up a default kong super admin and are struggling creating and enabling a super admin post installation. This update …
=> docs(35/km/super-admin) create super admin post installation

app/enterprise/0.35-x/admin-api/vitals/index.md, app/enterprise/0.35-x/admin-api/vitals/vitalsSpec.yaml
Adds missing `vitalsSpec.yaml` file for Vitals and fixes the link to access it.
=> docs(35/vitals) add vitals yaml spec

app/install/aws-linux.md, app/install/centos.md, app/install/debian.md, app/install/docker.md, app/install/macos.md, app/install/redhat.md, app/install/source.md, app/install/ubuntu.md, app/install/vagrant.md
This PR adds DB-Less / declarative config instructions for:
* aws-linux
* CentOS
* Debian
* Docker
* macOS
* Redhat
* Ubuntu
* Vagrant
* source
It does *not* include instructions for these other platforms:
* Kubernetes
* DC/OS
* Google Platform
As that requires additional changes on external repos before the docs can be written.
* ...
Fix #XXX
=> docs(install) add DB-Less / declarative config install steps

app/enterprise/0.35-x/getting-started/index.md
Here, "series" is in the singular form.
From http://www.thefreedictionary.com/series
Usage Note: Series is both a singular and a plural form. When it has the singular sense of "one set," it takes a singular verb, even when series is followed by of and a plural noun: A series of lectures is scheduled. When it has the plural sense of "two or more sets," it takes a plural verb: Two series of lectures are scheduled: one for experts and one for laypeople.
=> docs(35/start) subject-verb agreement

Dockerfile, Gemfile, jekyll.yml, package-lock.json
Update all gems and related files at once 
* Updates Jekyll
* Updates rouge gem
* Updates Dockerfile with new Jekyll
* Updates jekyll config file to use `plugins` vs deprecated `gems`
Fix #XXX
=> chore: update jekyll

app/enterprise/0.35-x/kong-manager/authentication/oidc.md
Adds protocols to `uri` parameters to avoid schema error.
=> docs(35/km/oidc) add protocols to URIs in examples

app/_data/docs_nav_ee_0.35-x.yml, app/enterprise/0.35-x/admin-api/index.md, app/enterprise/0.35-x/index.md
Adds an overview page for the Admin API section
=> Adds Admin API overview page

STYLEGUIDE.md
Adds guidelines for:
- images
- screenshots
- videos
=> Update STYLEGUIDE to include images

app/_data/docs_nav_ee_0.35-x.yml
=> fix(link) fix the broken install link on 0.35

TECHNICAL-WRITING-GUIDE.md
Based on @kinman 's feedback for another doc; this problem is prevalent in some of the older docs.
=> docs(twg) a note about "simple", "trivial", "easy"

app/_hub/kong-inc/serverless-functions/0.2-x.md
I don't know exactly what branch to target for 1.2 docs, hence here the input. Please advice.
=> Update for 0.3.0, first shipped with Kong 1.2

app/enterprise/0.35-x/deployment/migrations.md
This PR adds steps necessary portal template changes to migrate from 0.34x to 0.35.
=> docs(35/migrations) add portal templates breaking changes

app/enterprise/0.35-x/getting-started/add-service.md
Overhauls the Getting Started "Add a Service and Route" guide
- Updates from deprecated API to Service and Routes for 0.35
- Adds UI images
- Removes outdate video walkthrough (until a new one is recorded)
=> update(getting-started): Update Add Service

app/1.2.x/plugin-development/custom-logic.md, app/_hub/kong-inc/session/1.0-x.md
Blocked by:
https://github.com/Kong/kong/pull/4685
https://github.com/Kong/kong-plugin-session/pull/9
=> docs(plugin/order) add session plugin

app/enterprise/0.35-x/getting-started/enable-plugin.md
Updates 0.35 Getting Started's "Add a Plugin" guide to show step by step examples in Kong Manager, using the Rate Limiting Advanced plugin.
* Remove outdated instructions for Basic Auth
* Change to instructions to Rate Limiting Advanced plugin
* Remove outdated video (until video is updated)
=> update(0.35): Update Add a Plugin guide

app/_data/kong_versions.yml
Add Kong 1.2.1 metadata.
**Please hold on merging.**
=> release: 1.2.1

app/_assets/stylesheets/pages/install-method.less
* install method icon was being horizontally squished by flexbox - one line CSS fix
from this: 
to this:
=> adjusting install method icon

app/1.2.x/admin-api.md
This PR documents SNI wildcard name matching introduced in 1.2
=> docs(snis) document SNI wildcard name matching

app/_hub/kong-inc/prometheus/index.md
Adds callout warning users with high throughputs to refer to the StatsD plugin
=> hub(prometheus): Add callout to StatsD

app/enterprise/0.35-x/deployment/migrations.md
Proposed changes add instructions on how to upgrade from Kong 1.0 to Kong Enterprise 0.35
=> docs(35/migrations) add community upgrade steps

app/enterprise/0.35-x/deployment/installation/docker.md
Update Kong Enterprise on Docker page, adding Cassandra db alternative.
=> docs(ee/install) update docker install

app/enterprise/0.35-x/deployment/installation/docker.md
=> docs(35/docker) fix database name

app/_includes/toc.html, app/_layouts/docs.html, app/enterprise/0.35-x/deployment/installation/centos.md
I worked my way through this guide and set up Kong on a CentOS VM -- here are my suggested changes based on my experience.
=> docs(35/centos): Suggested updates to CentOS Guide PR #1367

app/enterprise/changelog.md
Clarify request validator schema support.
=> docs(enterprise/changelog) clarify request-validator

app/_includes/nav.html
* simple text update to nav from Hub -> Plugins
=> nav A/B test setup

app/enterprise/0.35-x/deployment/installation/docker.md
=> docs(35/docker) fix network instructions

app/_includes/nav.html
=> Revert Plugins to Hub in main site nav

app/enterprise/0.35-x/kong-manager/reset-password.md
Add long-awaited screenshots to the Reset Password and RBAC Token page.
=> docs(35/km/reset-password) add screenshots

app/_includes/nav.html
* Simple text update based on outcome of recent A/B test
=> Update main nav verbiage from Hub to Plugins

app/1.1.x/upgrading.md, app/1.2.x/upgrading.md
=> docs(1.x.x/upgrading) fix copy-n-paste error from previous version

.gitignore, algolia/config.json, app/_layouts/docs.html
Adds search support for Kong Enterprise docs
=> Search support for Enterprise documentation

app/enterprise/0.35-x/deployment/migrate-apis-cli.md
=> update 0.35 CLI entity migration guide

app/enterprise/0.35-x/getting-started/add-service.md
=> fix broken link

app/_hub/kong-inc/kubernetes-sidecar-injector/index.md
=> Sidecar Injector - Add EE compatibility

app/enterprise/0.36-x/kong-manager/reset-password.md
=> KM Reset Password - Add missing images

app/_assets/stylesheets/page.less, app/_layouts/changelog.html, app/_layouts/docs.html, app/_layouts/reference.html
=> style(*) remove enterprise header styling

app/1.3.x/proxy.md
=> docs(proxy) add more description text for SNI matcher in Route entity

app/_hub/kong-inc/canary/index.md
=> updated old "api" based docs to "service/route" based

app/enterprise/changelog.md
Changelog for 0.36-1 and 0.35-4
=> docs(ee-changelog) add notes for 0.36-1 and 0.35-4

app/enterprise/0.36-x/property-reference.md
Add details for portal_email_verification
=> Update portal property reference

app/enterprise/0.35-x/plugins/oidc-okta.md, app/enterprise/0.36-x/plugins/oidc-okta.md
Add images and configuration steps for Okta IDP based off SE's internal guides.
=> docs(oidc-okta) add Okta configuration steps and images

app/1.3.x/admin-api.md, app/1.3.x/db-less-admin-api.md
=> docs(1.3.x/admin-api) fix Routes header example

app/0.14.x/plugin-development/tests.md
=> update broken link

app/enterprise/changelog.md
=> docs(changelog) add missing notifications to 36-1 and 36-2

CONTRIBUTING.md
I have updated the CONTRIBUTING.md file, fixed all the grammatical typos I encountered in the file. So, now it will increase the readability for new contributors.
Please merge this
=> Fixed Typos and grammatical mistakes in CONTRIBUTING.md file

app/enterprise/0.36-x/deployment/licensing.md
=> Updated slack time from 1-2 days to 30 days.

app/_includes/nav.html
* nav buttons were directing to docs 404s
=> quick update to relative links in nav buttons

app/1.2.x/pdk/kong.client.md
=> (docs) Modified url to use secure link

app/enterprise/0.35-x/getting-started/add-admin.md, app/enterprise/0.36-x/getting-started/add-admin.md
=> docs(35, 36/add-admin) remove unused steps in ToC

app/enterprise/0.36-x/property-reference.md
* updated the property description for stream_listen in ee/0.36-x
=> docs(ee/conf) fix stream_listen config

app/enterprise/0.36-x/deployment/migrations.md
=> docs: fix ref to kong ee 0.35

app/enterprise/0.35-x/getting-started/enable-plugin.md
Changes Rate Limiting EE to Rate Limiting Advanced in 0.35 docs
=> Update enable-plugin.md 0.35

app/0.5.x/plugin-development/custom-entities.md, app/0.6.x/plugin-development/custom-entities.md, app/0.7.x/plugin-development/custom-entities.md
Cassandra documentation has broken link, which is fixed by this PR.
=> chores(links) - broken external links

app/enterprise/0.33-x/installation/amazon-linux.md, app/enterprise/0.34-x/installation/amazon-linux.md, app/enterprise/0.35-x/deployment/installation/amazon-linux.md, app/enterprise/0.36-x/deployment/installation/amazon-linux.md
Changes:
- Updates `Postgresql` commands in 0.34, 0.35, 0.36 
- Removes HTTPIE and changes /apis to /services
This doc still needs a lot of work but this fixes incorrect instructions. Rewrite PR will be created separately.
=> update(aws): Update postgres commands

app/_includes/footer.html, app/_includes/nav.html
* simple add of customers to header and footer nav
=> update Company nav to include new customers page

app/0.14.x/plugin-development/admin-api.md, app/1.0.x/plugin-development/admin-api.md, app/1.1.x/plugin-development/admin-api.md, app/1.2.x/plugin-development/admin-api.md, app/1.3.x/plugin-development/admin-api.md, app/enterprise/0.35-x/plugin-development/admin-api.md, app/enterprise/0.36-x/plugin-development/admin-api.md
=> fix: updated outdated example for api.lua

app/_hub/kong-inc/aws-lambda/index.md, app/_hub/kong-inc/oauth2/index.md, app/_layouts/extension.html
New plugin repository: https://github.com/Kong/kong-plugin-aws-lambda
Changelog: https://github.com/Kong/kong-plugin-aws-lambda/blob/master/CHANGELOG.md
=> docs(aws-lambda) update docs for 3.0.0

app/enterprise/0.34-x/vitals-prometheus-strategy.md, app/enterprise/0.35-x/admin-api/vitals/vitals-prometheus-strategy.md, app/enterprise/0.36-x/admin-api/vitals/vitals-prometheus-strategy.md
=> doc(vitals-prometheus) add guide to relabel instance in prometheus

app/enterprise/0.36-x/admin-api/rbac/examples.md
docs(ee/admin-api) fix broken links
* ee 0.36
* replacing links path from ./rbac/ path to ./admin-api/rbac/
From #1509
=> docs(ee) fix broken links

app/enterprise/1.3-x/deployment/migrations.md
Update migration guide for Kong Enterprise 1.3
=> update migration guide

app/_data/docs_nav_ee_1.3-x.yml, app/enterprise/1.3-x/plugins/exit-transformer.md, app/enterprise/1.3-x/plugins/kafka-log.md, app/enterprise/1.3-x/plugins/proxy-cache-advanced.md, app/enterprise/1.3-x/plugins/response-transformer-advanced.md
Test all plugin links in staging before merging.
=> docs(1.3/nav) update plugin navigation

app/_includes/nav.html
Replace “On-Prem” & “SaaS” w/ “Demo” & “Free Trial”
=> update Product nav buttons

app/_includes/nav.html
Remove "Try" label from Product nav
=> Remove label from nav

Gemfile.lock
=> fix(gemlock) netlify previews

app/enterprise/changelog.md
=> remove unusual numbering from changelog

app/enterprise/1.3-x/auth.md
=> docs(typo): behaviour

app/studio/1.0.x/release-notes.md
- Adds GraphQL video from GraphQL page.
- Changed GraphQL description to better describe the feature set
- Adds GraphQL section to TOC
=> docs(studio) update 1.0.x release notes

app/studio/1.0.x/git-sync.md
=> Update git sync doc to mention non-studio files

app/_data/kong_versions.yml, app/_plugins/versions.rb
Fixes a bug introduced by adding Kong Studio versioning, adds "community" as a version edition
=> fix ce versioning

app/_data/docs_nav_ee_1.3-x.yml
adds a navigation link for @murillopaula 's awesome systemd page.
=> docs(1.3-x) add navigation item for systemd page

app/_data/docs_nav_ee_1.3-x.yml, app/enterprise/1.3-x/plugins/oidc-cognito.md
Drafted a clean version of the existing Cognito Guide.
=> docs(1.3-x/oidc) add Amazon Cognito OIDC guide

app/free-trial/guide/index.html
=> Change to parameters and curl

app/studio/1.0.x/release-notes.md
=> docs(studio) update download information

app/free-trial/guide/index.html
=> removed extraneous command from example curl

.gitignore
=> chore(gitignore) ignore package-lock

app/_hub/kong-inc/openid-connect/index.md
- adds missing config parameters
- reorders parameters for better readability
- adds section about important configuration parameters
=> docs(openid-connect) update OpenID Connect docs

app/enterprise/1.3-x/kong-kubernetes/using-kong-for-kubernetes.md
=> Added toc for Concepts section

app/enterprise/1.3-x/kong-kubernetes/install.md
=> Added Enterprise to Kubernetes

app/_data/docs_nav_ee_1.3-x.yml
=> K8s install

app/enterprise/1.3-x/deployment/installation/overview.md
=> make ubuntu guide available on install overview

app/1.4.x/kong-kubernetes/using-kong-for-kubernetes.md
=> K8s Concepts nav

app/1.4.x/kong-kubernetes/index.md
=> fix typo in title

app/enterprise/1.3-x/deployment/access-license.md
=> Update first sentence about license file

app/studio/changelog.md
=> Studio: Updated with 1.0.1 Changelog

app/studio/1.0.x/download-install.md
=> Added Bintray access for Studio

app/studio/1.0.x/download-install.md
=> Edited Bintray access requirements for Studio

app/studio/1.0.x/download-install.md
=> Added Sign in to Bintray to each download

app/enterprise/1.3-x/kong-kubernetes/install.md
=> Update Prerequisites with license info

app/studio/1.0.x/download-install.md
=> docs(studio) update installation page

app/_hub/kong-inc/degraphql/index.md
=> docs(degraphql) use curl instead of httpie

app/enterprise/1.3-x/brain-immunity/service-map.md
=> Brain/Immunity: Updated screenshots

app/enterprise/1.3-x/kong-kubernetes/install.md
=> Updated license file information

app/enterprise/1.3-x/kong-kubernetes/install.md
=> Changed link for license info to Step 1

app/1.3.x/getting-started/configuring-a-grpc-service.md, app/1.4.x/getting-started/configuring-a-grpc-service.md
Clarify gRPC reflection requests routing.
=> docs(ce/grpc) clarify reflection requests proxying

app/enterprise/1.3-x/developer-portal/overview.md
=> Changed "will supported" to "will be supported"

app/enterprise/1.3-x/developer-portal/legacy-migration.md
=> Changed "me" to "be"

app/enterprise/1.3-x/brain-immunity/install-configure.md
=> Docs: Brain/Immunity Update install-configure.md

app/enterprise/1.3-x/brain-immunity/install-configure.md
=> Docs: Brain/Immunity update links

app/enterprise/1.3-x/kong-kubernetes/install.md
=> Kubernetes Docs: Removed Enterprise from live demo

app/_data/docs_nav_studio_1.1.x.yml, app/_data/kong_versions.yml, app/_layouts/changelog.html, app/studio/1.0.x/overview.md, app/studio/1.1.x/debugging-with-insomnia.md, app/studio/1.1.x/deploy-to-dev-portal.md, app/studio/1.1.x/download-install.md, app/studio/1.1.x/editing-specs.md, app/studio/1.1.x/git-sync.md, app/studio/1.1.x/graphql.md, app/studio/1.1.x/index.md, app/studio/1.1.x/live-preview.md, app/studio/1.1.x/overview.md, app/studio/1.1.x/release-notes.md, app/studio/changelog.md, package-lock.json
Add documentation for Kong Studio 1.1.x
=> feat(studio) 1.1.0 docs

app/enterprise/1.3-x/kong-kubernetes/install.md
Fix Enterprise Docker registry in k8s guide.
=> docs(enterprise/k8s) fix docker registry

app/enterprise/1.3-x/kong-kubernetes/install.md
=> Kubernetes: Made links for Request Demo

app/1.4.x/proxy.md
More details per: https://github.com/Kong/kong/issues/5213
=> docs(proxy) notes on route headers

app/_assets/images/nav/icn-enterprise-plugins.svg, app/_assets/images/nav/icn-kubernetes.svg, app/_assets/images/nav/icn-vitals.svg, app/_assets/stylesheets/header.less, app/_includes/nav.html, package-lock.json
* Add Kong for Kubernetes, Enterprise Plugins & Vitals to subnav
* Add vertical media query to compress subnav on small screens
* Adjust mobile nav overflow-x
=> add 3 additional subnav items w/ vertical media query

app/enterprise/0.36-x/admin-api/rbac/reference.md, app/enterprise/1.3-x/admin-api/rbac/reference.md
The endpoints for PUT are entity endpoints, not collection.
Fix documentation to reflect the app behavior.
=> fix(rbac) fix PUT endpoint for roles

app/_hub/hbagdi/deck.md
=> add redirect for deck

app/enterprise/changelog.md
Fixes #1523 
(Still need to add missing properties and link to them; will do in a separate PR.)
=> docs(changelog) state directives for upstream TLS

app/enterprise/1.3-x/kong-for-kubernetes/install.md
=> Changed link to Kubernetesgetting started guide

Dockerfile, Gemfile, Gemfile.lock, package-lock.json
Resolve NPM issue https://github.com/npm/uid-number/issues/7
=> resolve breaking tests

app/1.2.x/db-less-and-declarative-config.md
=> remove straggler redirect loop

app/enterprise/changelog.md
Add changelog for Kong EE 0.36-3 version
=> docs(changelog) add changelog for 0.36-3

app/enterprise/changelog.md
Added a changelog for release `0.36-4`
=> docs(changelog) add changelog for 0.36-4

app/studio/changelog.md
Adds Kong Studio Changelog for 1.1.1 release
=> Add Studio changelog for 1.1.1

app/enterprise/1.3-x/brain-immunity/install-configure.md
=> Fix formatting issues on Brain and Immunity doc page

app/_data/docs_nav_ee_1.3-x.yml
=> add links to plugin headers

app/enterprise/1.3-x/kong-for-kubernetes/install.md
=> Add kong for kubernetes image to install page

app/_hub/kong-inc/statsd-advanced/index.md
Recent changes to StatsD led to a review of the same parameters in StatsD advanced. 
For review, I need an SME to: 
1) confirm all changes are accurate,
2) do a once-over for any other changes that may be needed (specifically lines 87-89)
3) share a way to ensure future syncs with StatsD plugin docs to avoid disparity.
=> sync statsd advanced with statsd

app/enterprise/changelog.md
=> docs(changelog) add mtls-auth changes

app/_includes/nav.html
* add itm_source and itm_medium query strings to all nav URLs
=> add ITM query parameters to all nav items

app/_hub/kong-inc/key-auth-enc/index.md
=> fix(key-auth-enc) fix broken link to DB encryption and keyring docs

app/enterprise/1.3-x/kong-manager/service-directory-mapping.md
Update bullet points in Service Directory Mapping doc
=> Update bullet points in Service Directory Mapping

app/enterprise/1.3-x/db-encryption.md, app/enterprise/changelog.md
=> docs(keyring) additional notes regarding keyring behavior

app/_layouts/extension.html
the conditional should check for the underscored value, whereas the description should have dot notation; these were reversed.
also improved the definition of "consumer" and style.
=> docs(extension) add description for consumer.id

app/enterprise/1.3-x/developer-portal/configuration/authentication/index.md
=> docs(dp-auth) remove duplicate OIDC card

app/enterprise/1.3-x/kong-cloud.md
Updated information for Kong Cloud docs.
=> Kong Cloud update

app/enterprise/1.3-x/kong-for-kubernetes/index.md
=> K4K8s Enterprise Intro Update

app/1.4.x/plugin-development/custom-entities.md
=> lua syntax error

app/1.4.x/kong-for-kubernetes/index.md
=> Update to K4K8s Intro

app/free-trial/guide/index.html
=> docs(free-trial) add contact email

app/enterprise/1.3-x/kong-for-kubernetes/install.md
=> Fix broken link in install.md

app/_hub/kong-inc/kafka-upstream/index.md
=> docs(upstream) remove duplicate configuration

CONTRIBUTING.md
These details elaborate on how to:
1) Create a separate branch from within the local repo
2) Push that branch, rather than master, to GitHub
3) Create a PR from that branch
Please let me know any other details we need to add and if it helps the user with their current issue.
=> docs(contribution) clarify steps for PRing to Hub

app/2.0.x/proxy.md
=> docs(proxy) make the proxy doc L4 proxy aware and replaced a few legacy

app/1.4.x/kong-for-kubernetes/install.md
=> update helm installation to use the new repository

app/2.0.x/systemd.md, app/_data/docs_nav_2.0.x.yml
shamelessly copied from Kong EE
=> docs(2.0.0) document Kong via systemd

app/_hub/kong-inc/rate-limiting/1.0-x.md
- docs for RateLimit, RateLimit-Remaining and RateLimit-Reset headers.
- version updated, added file for previous version.
=> docs(rate-limiting) docs for RateLimit headers

app/2.0.x/hybrid-mode.md
Fix broken link in Hybrid Mode guide.
=> docs(ce/hybrid) fix broken link

app/_hub/signal_sciences/signal-sciences/index.md
Changed link to installation guide at the bottom of the page
=> Updated link in Signal Sciences plugin docs

app/_hub/kong-inc/acme/index.md
=> docs(hub/acme) fix typo

app/enterprise/1.3-x/kong-for-kubernetes/install.md
Anchor was set to "Introduction" rather than "introduction"
=> Update Install with the correct anchor

app/enterprise/1.3-x/kong-manager/service-directory-mapping.md
Fixing URL that was giving a 404 to consumers
=> Fixing URL that was giving a 404 to consumers

app/enterprise/1.3-x/deployment/installation/ubuntu.md
Update Ubuntu install docs to align with other install docs
=> Update Ubuntu installation docs

app/enterprise/1.3-x/deployment/installation/amazon-linux.md
=> updated doc to standardize steps across other install docs.

app/enterprise/1.3-x/deployment/installation/amazon-linux-2.md
=> Updated Amazon Linux 2 instructions

app/enterprise/1.3-x/deployment/installation/centos.md
=> Akoshok1 - Updated Centos install

app/enterprise/1.3-x/deployment/installation/docker.md
=> docs(docker) update docker installation guide

app/_data/docs_nav_ee_1.3-x.yml, app/enterprise/1.3-x/deployment/installation/overview.md, app/enterprise/1.3-x/deployment/installation/rhel.md
=> Created rhel.md file with installation instructions for RHEL which are missing

TECHNICAL-WRITING-GUIDE.md
=> clarify how-to titles

app/_includes/nav.html
* quick and simple addition of itm query strings to header navigation
=> add itm query strings to Solutions urls - main nav

STYLEGUIDE.md
=> add spaces after period and indentation guidelines

app/2.0.x/sizing-guidelines.md, app/_data/docs_nav_2.0.x.yml
=> docs(sizing) resource sizing guidelines documentation

app/enterprise/1.3-x/admin-api/workspaces/examples.md, app/enterprise/1.3-x/property-reference.md
carrying over @StuAtKong 's fix for missing links from #1766
=> docs(ee/1.3/prop-ref) fix missing links

app/_data/docs_nav_ee_1.3-x.yml, app/enterprise/1.3-x/admin-api/index.md, app/enterprise/1.3-x/admin-api/rbac/examples.md
Brings Enterprise 1.3 API reference up to date with CE 1.3.
@jmaher31 , @RobSerafini , n.b.
=> docs(1.3/ee) match admin API ee 1.3 to ce 1.3

app/_includes/nav.html
* add Kong U and Kong Professional Services to Support subnav
=> add Kong U and Prof Services to support nav

app/enterprise/1.3-x/admin-api/audit-log.md
=> docs(audit-log) improve signature verification documentation

app/enterprise/1.3-x/deployment/installation/docker.md
Fix some spelling errors and minor typos
=> Fix minor typos

app/enterprise/1.3-x/admin-api/audit-log.md
=> docs(audit-log) clarify signature implementation pitfalls

app/enterprise/1.3-x/deployment/installation/amazon-linux-2.md
=> Add links, try to fix numbering+formatting issues

app/enterprise/1.3-x/admin-api/audit-log.md
=> Fix minor typos for audit log docs

app/enterprise/1.3-x/logging.md
Fixed some minor typos and formatting issues. Also removed a duplicated section.
=> fix minor typos/formatting in Logging Reference

app/enterprise/0.31-x/installation/docker.md, app/enterprise/0.32-x/installation/docker.md, app/enterprise/0.33-x/installation/docker.md, app/enterprise/0.34-x/installation/docker.md, app/enterprise/0.35-x/deployment/installation/docker.md, app/enterprise/0.36-x/deployment/installation/docker.md, app/enterprise/1.3-x/deployment/installation/docker.md
Postgres has updated all docker images to require password. This change adds the newly required field.
Background: https://github.com/Kong/docs.konghq.com/pull/1794
=> fix(docs) add postgres password

app/enterprise/1.3-x/admin-api/db-encryption.md, app/enterprise/1.3-x/db-encryption.md, app/enterprise/changelog.md
=> 1.3.0.2 Release

app/enterprise/changelog.md
=> docs(ee/changelog) update the 1.3.0.2 changelog

app/_hub/kong-inc/response-transformer-advanced/index.md
This will be available in the next 1.3.0.2 enterprise release.
=> docs(response_transformer_advanced) update remove.headers

app/enterprise/changelog.md
=> correct release date, fix grammar

app/0.14.x/logging.md, app/1.0.x/logging.md, app/1.1.x/logging.md, app/1.2.x/logging.md, app/1.3.x/logging.md, app/1.4.x/logging.md, app/1.5.x/logging.md, app/2.0.x/logging.md, app/enterprise/0.35-x/logging.md, app/enterprise/0.36-x/logging.md, app/enterprise/1.3-x/logging.md
=> docs(logging) fix a couple of typos

app/enterprise/1.3-x/brain-immunity/install-configure.md
Two problems were fixed:
1. alerts/config description was incorrect
2. Setup instructions out of order and not in-depth enough.
=> Fix (Collector App) Fix Collector App docs to match 1.1.0

app/_data/docs_nav_ee_1.3-x.yml, app/enterprise/1.3-x/deployment/licenses/report.md
=> New Monitor License Usage topic

app/0.14.x/pdk/kong.service.md, app/1.0.x/pdk/kong.service.md, app/1.1.x/pdk/kong.service.md, app/1.2.x/pdk/kong.service.md, app/1.3.x/pdk/kong.service.md, app/1.4.x/pdk/kong.service.md, app/1.5.x/pdk/kong.service.md, app/2.0.x/pdk/kong.service.md, app/enterprise/0.35-x/pdk/kong.service.md, app/enterprise/0.36-x/pdk/kong.service.md, app/enterprise/1.3-x/pdk/kong.service.md
=> docs(pdk) fix a couple of typos

app/_hub/kong-inc/vault-auth/0.35-x.md, app/_hub/kong-inc/vault-auth/0.36-x.md, app/_hub/kong-inc/vault-auth/index.md
=> fix typo in vault doc

algolia/config-ee.json
update replacement regex to account for string
=> fix broken search on Enterprise

app/_hub/signal_sciences/signal-sciences/index.md
Changed from current copy:
"Installation is simple, using a NGINX lua module and a local agent that feed data into Signal Sciences Cloud Engine."
To new copy:
"Installation is simple, using a native NGINX module and a local agent that feed data into the Signal Sciences Cloud Engine."
=> Updated Signal Science Plugin text

algolia/config-ee.json
there is no need for regex with the replace method, a string is sufficient.
=> fix Enterprise search

app/enterprise/1.3-x/kong-for-kubernetes/install.md
=> fix: add missing step to create a namespace

app/enterprise/1.3-x/getting-started/add-service.md
=> Updated broken image

app/enterprise/1.3-x/deployment/installation/docker.md
I've fixed the issues raised in the bug and validated the install steps.
=> fixing DOCS-899

app/enterprise/1.3-x/getting-started/key-concepts.md
Fixed new key-concepts.md file (flipping header to top of file) and ran local build and link checker
├───OK─── http://localhost:3000/enterprise/1.3-x/getting-started/key-concepts
=> fixing 404

app/enterprise/1.3-x/getting-started/key-concepts.md
=> Changing title to match ToC entry

app/enterprise/1.3-x/getting-started/add-service.md
=> Updated Getting Started Create Service page

app/enterprise/1.3-x/brain-immunity/install-configure.md
Add kong.conf changes needed to show GUI changes in Kong Manager
=> Add(Immunity) Add install instructions for kong.conf

app/_includes/footer.html
=> fix(iframe) adjust the iframe so it doesn't show a scrollbar

app/enterprise/1.3-x/brain-immunity/install-configure.md
Updated broken links on Brain and Immunity page.
=> Update Brain/Immunity broken links

app/_hub/kong-inc/request-transformer-advanced/index.md
Fixing the ToC as per issue https://github.com/Kong/docs.konghq.com/issues/1508.
=> (docs/plugins) Fixing ToC formatting in the Request Transformer Advanced plugin

app/_hub/kong-inc/acme/index.md
=> docs(plugins/acme) add doc for dummy route setup and staging cleaning

app/enterprise/0.34-x/vitals-prometheus-strategy.md, app/enterprise/0.35-x/admin-api/vitals/vitals-prometheus-strategy.md, app/enterprise/0.36-x/admin-api/vitals/vitals-prometheus-strategy.md, app/enterprise/1.3-x/admin-api/vitals/vitals-prometheus-strategy.md
=> doc(vitals-prometheus) add grafana dashboard for vitals prometheus

app/_includes/head.html
Clearbit X script added(in lieu of Tag Manager injection) for marketing prospect visibility
=> add Clearbit X script

app/enterprise/1.3-x/deployment/installation/docker.md
Ran through the Docker installation, caught some minor things that needed fixing.
=> docs (installation/docker) Minor fixes, rewording, formatting to the Docker install

app/enterprise/1.3-x/getting-started/key-concepts.md
Updated with Role-Based Access Control (RBAC)
=> Updated RBAC naming

app/enterprise/1.3-x/kong-manager/authentication/super-admin.md
Hi there 👋 
I've noticed some of the names in the doc is not necessarily aligning to the actual menu/button on the UI.
This fix might help users navigate easier.
=> Fixed the names align to the UI

app/enterprise/1.3-x/admin-api/rbac/reference.md
=> docs (admin-api/rbac) Replacing link placeholders with actual links

app/enterprise/1.3-x/deployment/installation/amazon-linux-2.md, app/enterprise/1.3-x/deployment/installation/amazon-linux.md, app/enterprise/1.3-x/deployment/installation/centos.md, app/enterprise/1.3-x/deployment/installation/rhel.md
Based on changes in https://github.com/Kong/docs.konghq.com/pull/1849.
=> docs (enterprise/install) Combining two steps in the super admin and bootstrap section

app/enterprise/1.3-x/admin-api/audit-log.md
=> docs(audit) describe audit_log_record_ttl behavior

app/_hub/signal_sciences/signal-sciences/index.md
=> Signal Science Plugin Update

app/_layouts/extension.html
Edited Plugin third-party contributor banner to: This plugin is developed, maintained and tested by a third-party contributor, not by Kong Inc."
=> Edited Plugin third-party contributor banner

app/enterprise/1.3-x/deployment/access-license.md
=> fix(license) fix instructions for license

app/enterprise/0.34-x/kong-manager/organization-management/workspaces.md
There was one image that was broken for some reason (seems like indentation was incorrect)
=> Fix image that wasn't working

app/2.0.x/admin-api.md, app/2.0.x/db-less-admin-api.md, app/_assets/stylesheets/base.less, app/_assets/stylesheets/pages/docs.less
Related with https://github.com/Kong/kong/pull/5662
Before:
After:
=> fix(2.0.0) admin api headers

app/2.0.x/admin-api.md, app/2.0.x/db-less-admin-api.md
...and remove a deprecated one
=> docs(2.0.x/ce) add missing endpoints in Admin API docs

app/enterprise/1.3-x/brain-immunity/install-configure.md
Details global variables for Collector App that can be/should be modified and what they do
=> Describe Collector App global variables

app/_hub/cleafy/cleafy/index.md
updated to latest support matrix and description
=> updated to latest support matrix and description

app/_hub/kong-inc/key-auth-enc/index.md, app/_hub/kong-inc/key-auth/index.md
Preview: https://deploy-preview-1876--kongdocs.netlify.com/hub/kong-inc/key-auth-enc/
=> docs (plugins/key-auth) Fixing minor errors and formatting

README.md
=> A few minor changes

app/2.0.x/admin-api.md, app/2.0.x/db-less-admin-api.md
A link was not rendered (so removed)
=> fix(api) update healthcheck endpoint

app/enterprise/1.3-x/developer-portal/helpers/cli.md
This doc is based on readme of repo, however changes made did not get reflected here.
=> docs(portal-cli): update to match readme

app/enterprise/1.3-x/health-checks-circuit-breakers.md
this is for a single release, but should be in other versions as well
=> fix(health) add upstream health to the reference doc

app/enterprise/k8s-changelog.md
=> add changelog for kong-enterprise-k8s 2.0.2.0 release

app/enterprise/1.3-x/brain-immunity/install-configure.md
Brain/Immunity: Changed to "Restart Kong". Removed "...to see changes take effect/affect".
=> Brain/Immunity: Changed to "Restart Kong"

app/_hub/signalfx/signalfx/index.md
=> docs (plugins/signalfx) Fixing formatting and links

app/enterprise/1.3-x/brain-immunity/install-configure.md
=> Brain/Immunity: fixed links

app/enterprise/1.3-x/db-encryption.md
=> Removed Alpha tag

app/_layouts/getting-started-guide.html
=> Changing name of Kong tab on the GSG page

app/_data/docs_nav_ee_1.5.x.yml, app/enterprise/1.5.x/developer-portal/administration/application-registration.md
=> App registration

app/_hub/signalfx/signalfx/index.md
=> fixing links and code formatting

app/_data/docs_nav_ee_1.3-x.yml
=> fix(navigation) typo in the url link breaks navigation

app/_hub/kong-inc/key-auth-enc/index.md
=> Removed Alpha Tag from Key Auth Enc plugin

app/_assets/stylesheets/accordion.less, app/_assets/stylesheets/pages/docs.less
* Update sidebar accordions to make overflow content accessible
* Update scrollbar appearance on webkit browsers
=> allow overflow for sidebar accordions

app/getting-started-guide/latest/overview.md, jekyll-dev.yml, jekyll.yml
Creating variables as branding continues to change.
=> Product name variables

app/enterprise/1.5.x/developer-portal/administration/application-registration.md
=> App Reg: Added redirect_from

app/enterprise/changelog.md
=> Updated 1.5 to 1.5.0.0

app/enterprise/1.5.x/brain-immunity/install-configure.md
=> Fix(brain/immunity) Remove incorrect and redundant curl instructions.

app/_data/docs_nav_ee_1.3-x.yml, app/_layouts/docs-v2.html, app/_layouts/docs.html, app/enterprise/1.3-x/index.md
=> Fixing 1.3-x nav and landing page +dropdown

app/_data/docs_nav_2.0.x.yml, app/_data/docs_nav_ee_1.5.x.yml, app/_layouts/getting-started-guide.html, app/getting-started-guide/latest/overview.md
- Adding the guide to the community and enterprise navs for latest releases
- Turning landing page into a regular page with right hand nav
- Adding banner for guide to call out that it applies to both community and enterprise (phrasing WIP)
=> Getting started guide nav-related edits

app/enterprise/1.5.x/brain-immunity/install-configure.md
=> Brain/Immunity: edits

app/enterprise/1.3-x/kong-for-kubernetes/install.md
=> Fel Openshift update

app/enterprise/changelog.md
=> Updates to Changelog; added 0.36-5

app/enterprise/1.5.x/brain-immunity/install-configure.md
BrainImmunity: removed trailing /
=> BrainImmunity: removed trailing /

app/enterprise/1.5.x/kong-for-kubernetes/install.md
Based on changes made in https://github.com/Kong/docs.konghq.com/pull/1910
* Commands for openshift method
* Adding tabs for better readability
=> Adding OpenShift commands to K8S install in 1.5.x

app/install/redhat.md
=> Fix RHEL 8 download link typo

app/_hub/kong-inc/ip-restriction/index.md
=> docs(ip-restriction) IPv6 support and remove mutual exclusivity restriction on whitelist and blacklist

app/enterprise/1.3-x/systemd.md, app/enterprise/1.5.x/systemd.md
=> docs(systemd) update the default locations

app/enterprise/1.5.x/deployment/installation/ubuntu.md
👋  @Kong/team-docs 
I noticed the version number in this doc is out-dated.
=> Bumped up the version number for ubuntu

CONTRIBUTING.md
* Adding guidelines for using tabs
* Updating page ToC usage guidelines
=> docs(contributing) Updates to repo contribution guidelines

app/_hub/kong-inc/request-transformer-advanced/index.md, app/_hub/kong-inc/request-transformer/index.md
=> doc(request-transformer) note about X-Forwarded-* headers

app/enterprise/changelog.md
=> Added 1.5.0.1 change log info

jekyll-dev.yml, jekyll.yml
=> docs(config) Updating product name variables

app/enterprise/1.5.x/introduction.md
=> Intro: Update "add-on" to "module"

app/_assets/javascripts/app.js, app/_assets/stylesheets/copy-code-snippet.less, app/_assets/stylesheets/index.less
Copy code snippet functionality
=> Copy code snippet functionality

app/_hub/kong-inc/aws-lambda/index.md
* Updated configuration info to indicate example showing python is only an example of runtime. 
* Runtimes supported by AWS are listed in dialog.
=> AWS Lambda update

app/enterprise/1.5.x/developer-portal/administration/index.md
Adds application registration to Portal Administration landing page for 1.5
=> docs(portal): add app registration to page

app/enterprise/1.3-x/developer-portal/configuration/authentication/adding-registration-fields.md, app/enterprise/1.5.x/developer-portal/configuration/authentication/adding-registration-fields.md
This edit should apply to 1.3 and 1.5
=> docs(portal): correct warning

app/_assets/css/hub.css, app/_assets/javascripts/app.js, app/_assets/stylesheets/accordion.less, app/_assets/stylesheets/pages/docs.less
- fixes for sidebar scrolling
- hover states over nav sidebar
=> Fixes for sidebar scrolling

app/_layouts/extension.html
* Fixing tab syntax to pick up new navtabs format
* Removing "Other Versions" section from sidebar to lower confusion - it's often conflated with the _compatibility/bundled with_ section right above
See any Kong plugin for preview of changes, eg: https://deploy-preview-1984--kongdocs.netlify.app/hub/kong-inc/basic-auth/
=> Doc(plugins) Layout improvements

app/_data/extensions/kong-inc/kafka-log/versions.yml, app/_hub/kong-inc/kafka-log/1.3-x.md, app/_hub/kong-inc/kafka-log/index.md
=> docs(kafka-log) add support for api_version config

app/2.0.x/health-checks-circuit-breakers.md
=> fix(health) update CE according to EE

app/_layouts/docs-v2.html, app/_layouts/getting-started-guide.html
Adding image expand functionality to community docs and getting started guide.
Example links:
https://deploy-preview-1985--kongdocs.netlify.app/getting-started-guide/latest/overview
https://deploy-preview-1985--kongdocs.netlify.app/2.0.x/hybrid-mode/
=> Docs(layouts) Image expand functionality

app/enterprise/1.3-x/getting-started/start-kong.md
Added proper name section to Steps section
- [Step 1: Set-up Super Admin](#step-1)
- [Step 2: Set-up Datastore](#step-2)
- [Step 3: Start Kong](#step-3)
- [Step 4: Test Kong](#step-4)
=> Adding proper section names to Steps section

app/enterprise/1.5.x/brain-immunity/install-configure.md
=> fix(brain&immunity) Slack config link

app/enterprise/1.5.x/health-checks-circuit-breakers.md
Based on https://github.com/Kong/docs.konghq.com/pull/1893.
=> docs(healthcheck reference) Adding threshold feature to 1.5.x

app/enterprise/changelog.md
=> changelog - added db_export fix - see FTI-1272

app/_layouts/changelog.html
Removing icon to align with new doc style.
=> docs(changelog) Removing icon from header

app/enterprise/changelog.md
* Changelog update for 1.5.0.2 release
* Patch/Fix release only; no feature updates
* Scheduled for 4/28/20
=> docs/(changelog) 1.5.0.2 release

app/enterprise/1.5.x/deployment/installation/amazon-linux.md
* Turning URLs into real links
* Removing an extra header that doesn't contain anything
* minor formatting
=> docs(ee-install) Links and formatting for AWS install topic

app/_layouts/changelog.html, app/_layouts/docs-v2.html, app/_layouts/docs.html, app/_layouts/getting-started-guide.html
Replacing tab text with variables, which also updates the Community name to the correct current product name
=> docs(layouts) Updating top nav with product name variables

app/_includes/accordion-item.html, app/_includes/docs-sidebar.html
- support for empty sidebar items (no arrow, not expandable)
=> Support for empty sidebar item

app/_assets/images/icons/documentation/icn-support.svg, app/_assets/javascripts/app.js, app/_assets/stylesheets/dropdown.less, app/_assets/stylesheets/feedback-widget.less, app/_assets/stylesheets/page.less, app/_assets/stylesheets/pages/docs.less, app/_includes/docs-sidebar.html, app/_layouts/docs-v2.html, app/_layouts/docs.html, app/_layouts/getting-started-guide.html
- fixing the top navigation (Community/Enterprise/Getting Started /Studio)
- making the table contents accessible.
- icon sizing on home page (eg. support)
- alignment of the search bar and the version selector
=> Fix mobile related layout issues

app/_hub/kong-inc/graphql-rate-limiting-advanced/index.md
https://konghq.atlassian.net/browse/DOCS-998
Direct link to generated PR output:
https://deploy-preview-1994--kongdocs.netlify.app/hub/kong-inc/graphql-rate-limiting-advanced/
=> docs/Fix GraphQL adv rate limiting plugin errors and inconsistencies

app/_hub/kong-inc/mtls-auth/index.md
=> doc(plugins) fix correct default value for revocation_check_mode of

app/_hub/kong-inc/rate-limiting-advanced/index.md
Updated curl command and other minor comments
=> Updated curl command and other minor comments

README.md
=> docs(README) update automation guide

.github/workflows/build-test.yml
=> fix(build/test) Adjusting build/test workflow to exclude drafts

app/_hub/kong-inc/mtls-auth/index.md
Update skip_consumer_lookup default to false
=> docs(mtls_auth_plugin) Update skip_consumer_lookup default to false

.github/workflows/build-test.yml
=> fix(build workflow) Testing out [skip ci]

templates/how-to.md
=> docs (templates) Updating how-to template

.github/workflows/build-test.yml
=> fix(build/test) Switching back to build on push

jekyll.yml
Working on cutting down build time.
=> docs(config) Setting incremental builds

app/enterprise/1.5.x/deployment/installation/docker.md
One instance of localhost was missed when this topic was created.
=> docs(docker-install) Switch localhost to variable

app/enterprise/1.5.x/plugins/oidc-use-case.md
I require approval from my company before I can merge this PR. I should receive it within a day or two.
=> docs(oidc-use-case): italicize identity provider

app/_hub/_init/my-extension/index.md
* Removing contact info for Cooper
* Removing "incompatible versions"
* Changing the "categories" section to ask authors to use only one category
=> docs(plugins) Update plugin template

app/enterprise/1.5.x/kong-for-kubernetes/deployment-options.md
Preview: https://deploy-preview-2048--kongdocs.netlify.app/enterprise/1.5.x/kong-for-kubernetes/deployment-options/
=> docs(install) Fixing links in Kubernetes deployment

app/_hub/kong-inc/vault-auth/index.md
According to changelog https://konghq.atlassian.net/wiki/spaces/FTT/pages/8356124/Kong+Enterprise+-+Changelog+Features+Release+Schedule#KongEnterprise-Changelog,Features&ReleaseSchedule-KongEnterprise1.3
- Added 1.5.x support
- Changed 1.3.x to 1.3-x
=> plugin(vault_plugin) Added 1.5.x support; changed 1.3.x to 1.3-x

app/_layouts/docs-v2.html, app/_layouts/docs.html, app/_layouts/getting-started-guide.html, app/_plugins/page_exists.rb, app/enterprise/0.35-x/admin-api/workspaces/examples.md, app/enterprise/0.36-x/admin-api/workspaces/examples.md, app/enterprise/1.3-x/kong-manager/administration/workspaces/create-workspace.md, app/enterprise/1.3-x/kong-manager/administration/workspaces/update-workspace.md, app/enterprise/1.5.x/kong-manager/administration/workspaces/create-workspace.md, app/enterprise/1.5.x/kong-manager/administration/workspaces/update-workspace.md
Adding ability to stay on the same topic when navigating between versions
=> Adding ability to stay on the same topic when navigating between versions

app/_assets/css/hub.css, app/_assets/stylesheets/page.less
=> Nesting unordered lists into ordered lists in a topic

app/2.0.x/go.md
=> need and use of the go compiler image

app/enterprise/1.5.x/brain-immunity/troubleshooting.md
- duplicating 1.3.x updates to the 1.5.x version
- these edits have been approved for 1.3.x, with no changes
=> docs(brain_immunity) Update 1.5.x version with 1.3.x updates

app/enterprise/1.5.x/brain-immunity/install-configure.md
- Link to helm chart was not live. Edited file to make link active.
=> docs(brain_immunity) Updated link to helm chart

app/_hub/kong-inc/serverless-functions/0.3-x.md, app/_hub/kong-inc/serverless-functions/index.md
Update of serverless docs
- add version 1.0, functions in every phase
- fixing the examples to show how to actually upload Lua code in arrays
=> fix(serverless) update examples, add version 1.0

app/_assets/javascripts/app.js, app/_assets/stylesheets/page.less, app/_assets/stylesheets/pages/docs.less, app/_layouts/docs-v2.html, app/_layouts/getting-started-guide.html
- close/reopen right-hand nav on desktop
- add lines to right-nav tree for nested headings
=> Right TOC sidebar changes

app/enterprise/1.5.x/support-policy.md
- Per Reza, he asked that we include the Support Policy in the Docs
- Including info in this doc: https://docs.google.com/document/d/1OhDhIHGuIvgh_Ac9JrN_KgHuSdRODYEiZtwJEQXO7xs/edit?ts=5e438d35
=> docs(support_policy) Created new topic for Support Policy

app/_data/docs_nav_ee_1.5.x.yml
=> docs(ToC) Adding release notes to ToC

app/_data/docs_nav_ee_1.5.x.yml, app/enterprise/1.5.x/brain-immunity/changelog.md
- Created a simple changelog topic linking to Collector github repo for Brain and Immunity release info.
=> docs(brain_immunity) Changelog topic

app/enterprise/1.5.x/support-policy.md
-- Updated content per Tom's input
-- Need to add link to Support and Maintenace Policy
=> docs(version-support) Updated content per Legal's input

app/enterprise/changelog.md
Added info to changelog for 1.5.0.3 release
=> docs(KE changelog) Update Changelog for KE 1.5.0.3 Release

app/_data/docs_nav_ee_1.5.x.yml
- Removed "Policy" from TOC, and now is only "Version Support"
=> docs(nav-toc) Changed "Version Support Policy" to "Version Support"

app/_assets/stylesheets/header.less, app/_includes/nav.html
* fix icon positioning for Docs subnav items
=> update icon positioning

app/_assets/stylesheets/footer.less, app/_assets/stylesheets/header.less, app/_includes/footer.html, app/_includes/nav.html
* add Get Started buttons to header nav
* add Get Started link to footer
* update remaining footer links for consistency
=> add Get Started CTAs to header & footer nav

app/_hub/kong-inc/rate-limiting/0.1-x.md, app/_hub/kong-inc/rate-limiting/1.0-x.md, app/_hub/kong-inc/rate-limiting/index.md, app/enterprise/0.31-x/kong-implementation-checklist.md, app/enterprise/0.32-x/kong-implementation-checklist.md, app/enterprise/0.33-x/deployment-guide.md, app/enterprise/0.34-x/deployment-guide.md
Black tech leaders are calling for action to replace usage of many phrases. There are ongoing efforts that will require code changes and coordinated documentation updates. This is
a first small step of replacing master-slave with primary-replica.
=> Our words matter. 

app/_hub/kong-inc/vault-auth/0.35-x.md, app/_hub/kong-inc/vault-auth/0.36-x.md, app/_hub/kong-inc/vault-auth/index.md
=> doc(vault-auth) fix typo

app/enterprise/1.5.x/deployment/installation/centos.md
Fix typo, hyperlinks, update version numbers
=> Minor fixes in centos install guide

app/_hub/kong-inc/acl/index.md, app/_hub/kong-inc/basic-auth/index.md, app/_hub/kong-inc/bot-detection/index.md, app/_hub/kong-inc/hmac-auth/index.md, app/_hub/kong-inc/ip-restriction/index.md, app/_hub/kong-inc/jwt-signer/index.md, app/_hub/kong-inc/key-auth-enc/index.md, app/_hub/kong-inc/key-auth/index.md, app/_hub/kong-inc/mtls-auth/index.md, app/_hub/kong-inc/oauth2/index.md, app/_hub/kong-inc/openid-connect/index.md
=> docs(*) use current properties names.

app/enterprise/1.5.x/deployment/installation/amazon-linux-2.md, app/enterprise/1.5.x/deployment/installation/amazon-linux.md, app/enterprise/1.5.x/deployment/installation/rhel.md
* Updating examples to current main version
* Adding hyperlinks
* Typo fix
=> docs(ee-install) Updating links to 1.5 and minor fixes

app/enterprise/changelog.md
=> Update changelog for 1.5.0.4 version

app/enterprise/changelog.md
=> docs(changelog) added service_count issue to 1.5.0.4

app/enterprise/1.5.x/deployment/licenses/report.md
=> docs(licensing) Added Overview to Licensing page

app/enterprise/1.5.x/introduction/key-concepts.md
-- Updated Beta definitions and added Stable definition.
-- These definitions have been reviewed by Reza, Jimmy/Customer Support and Steven C.
=> docs(key-concepts-update) Updated Beta and added Stable

app/_hub/kong-inc/acme/index.md, app/_hub/kong-inc/session/1.0-x.md, app/_hub/kong-inc/session/1.2-x.md, app/_hub/kong-inc/session/index.md, app/enterprise/1.5.x/developer-portal/configuration/authentication/key-auth.md, app/enterprise/1.5.x/developer-portal/configuration/workspaces.md, app/enterprise/1.5.x/health-checks-circuit-breakers.md, app/enterprise/1.5.x/pdk/index.md, app/enterprise/1.5.x/start-kong-securely.md
* Fixing broken anchor links all over the place
* In "Start Kong Enterprise Securely", removing the links instead and adjusting topic to fit
* Minor typo fixes
=> docs(various) Fixing anchor links

app/_hub/kong-inc/basic-auth/index.md, app/_hub/kong-inc/key-auth-enc/index.md, app/_hub/kong-inc/key-auth/index.md, app/_hub/tomkerkhove/microsoft_azure/index.md
=> chore(hub) fix allow/deny nomenclature

app/_data/extensions/kong-inc/openid-connect/versions.yml, app/_hub/kong-inc/openid-connect/1.3-x.md, app/_hub/kong-inc/openid-connect/index.md
Docs update for OpenID Connect plugin.
=> docs(openid-connect) update docs to match 1.5 release

app/install/kubernetes.md
=> chore(kubernetes) make redirect point to latest version of the document

app/_data/extensions/kong-inc/rate-limiting/versions.yml, app/_hub/kong-inc/rate-limiting/2.1-x.md, app/_hub/kong-inc/rate-limiting/index.md
New version: 2.2.0
New feature: rate-limiting by header
=> docs(hub) update rate-limiting docs

app/enterprise/1.5.x/kong-cloud.md
Doc is currently using h1s, which is causing problems with display and the right-hand nav. Fixing the headers.
Preview: https://deploy-preview-2146--kongdocs.netlify.app/enterprise/1.5.x/kong-cloud/
=> docs(cloud) Fixing header levels

app/install/kubernetes.md
I tried to use variable in #2147 but it just caused link-checker fail. Here back to static one.
=> fix(kubernetes) install redirect page

app/install/kubernetes.md
After merging #2153, @lena-larionova gave this comment:
https://github.com/Kong/docs.konghq.com/pull/2153#issuecomment-652565493
And here we are, fixing the same page for the 3rd time. Hopefully this time it is final.
=> fix(kubernetes) install redirect page, part 2

app/enterprise/1.5.x/deployment/installation/rhel.md
Update RHEL documentation to add a small note for RHEL 7.0
=> Update RHEL documentation

app/0.12.x/health-checks-circuit-breakers.md, app/0.13.x/health-checks-circuit-breakers.md, app/0.14.x/health-checks-circuit-breakers.md, app/1.0.x/health-checks-circuit-breakers.md, app/1.1.x/health-checks-circuit-breakers.md, app/1.2.x/health-checks-circuit-breakers.md, app/1.3.x/health-checks-circuit-breakers.md, app/1.4.x/health-checks-circuit-breakers.md, app/1.5.x/health-checks-circuit-breakers.md, app/2.0.x/health-checks-circuit-breakers.md, app/enterprise/0.34-x/health-checks-circuit-breakers.md, app/enterprise/0.35-x/health-checks-circuit-breakers.md, app/enterprise/0.36-x/health-checks-circuit-breakers.md, app/enterprise/1.3-x/health-checks-circuit-breakers.md, app/enterprise/1.5.x/health-checks-circuit-breakers.md
Today @hbagdi pointed me to this paragraph and asked me this question,
so I'm clarifying the docs. :)
=> docs(ce/*) clarify how to mix active and passive healthchecks

app/_hub/kong-inc/basic-auth/index.md, app/_hub/kong-inc/hmac-auth/index.md, app/_hub/kong-inc/jwt/index.md, app/_hub/kong-inc/key-auth/index.md, app/_hub/kong-inc/ldap-auth/index.md, app/_hub/kong-inc/oauth2/index.md
authentication plugins support gRPC clients.
=> Add grpc/gprcs to supported protocols, request examples with `grpcurl`

app/_data/extensions/kong-inc/session/versions.yml, app/_hub/kong-inc/session/2.2-x.md
~Note: this plugin does not have a `app/_data/extensions/kong-inc/session/versions.yml` file~ (edit: versions file was added)
=> docs(hub) update session plugin features (2.4.x)
