Kong/docs.konghq.com

app/_hub/kong-inc/grpc-web/index.md
=> grpc-web plugin: missing links in description

app/_data/extensions/kong-inc/acme/versions.yml, app/_hub/kong-inc/acme/0.2.2.md, app/_hub/kong-inc/acme/index.md
=> doc(plugin/acme) update acme plugin document with new features in 0.2.7

app/_includes/footer.html, app/_includes/nav.html
* Update Install path for newly revised Get Started page
* Adjust mobile CTAs
=> Header and footer navigation updates

app/_hub/kong-inc/request-transformer-advanced/index.md
=> fix(transformer) fix table + advanced templates

app/0.10.x/proxy.md, app/0.11.x/proxy.md, app/0.12.x/proxy.md, app/0.13.x/proxy.md, app/0.14.x/proxy.md, app/1.0.x/proxy.md, app/1.1.x/proxy.md, app/1.2.x/proxy.md, app/1.3.x/proxy.md, app/1.4.x/proxy.md, app/1.5.x/proxy.md, app/2.0.x/proxy.md, app/enterprise/0.34-x/proxy.md, app/enterprise/0.35-x/proxy.md, app/enterprise/0.36-x/proxy.md, app/enterprise/1.3-x/proxy.md, app/enterprise/1.5.x/proxy.md
=> fix(proxy-reference) add missing reference link

app/enterprise/2.1.x/deployment/deployment-options.md
Removing (beta) from section header per Reza's feedback.
=> docs(hybrid mode) Removing beta label

app/enterprise/2.1.x/vitals/vitals-reports.md
=> update vitals reports intro line

app/1.3.x/loadbalancing.md, app/1.4.x/loadbalancing.md, app/1.5.x/loadbalancing.md, app/2.0.x/loadbalancing.md, app/2.1.x/loadbalancing.md, app/enterprise/1.3-x/loadbalancing.md, app/enterprise/1.5.x/loadbalancing.md, app/enterprise/2.1.x/loadbalancing.md
Improve clarity and mention `least-connections`.
⚠️  **NOTE**:  once the review is done, I will propagate the changes in Kong versions > 1.3.
=> docs(load-balancing) update load-balancing algorithms

app/getting-started-guide/2.1.x/overview.md
* Adding a section on Enterprise features covered in the guide - otherwise they look like they're missing.
* Fixing some commas
Preview: https://deploy-preview-2196--kongdocs.netlify.app/getting-started-guide/2.1.x/overview/
=> docs(gsg) Minor updates to overview

app/enterprise/1.5.x/admin-api/rbac/reference.md, app/enterprise/2.1.x/admin-api/rbac/reference.md
-- spelled as permisson, corrected to permission
=> correct spelling of permission

app/2.1.x/go.md, app/2.1.x/plugin-development/custom-logic.md
New `:response()` plugin method.
=> Document response phase.

app/2.1.x/hybrid-mode.md
=> doc(hybrid) add documents for pki mode

app/_assets/stylesheets/navtabs.less
Changing color of tabs to make them more obvious and to match Kongponents styling (https://kongponents.netlify.app/components/tabs.html).
=> docs(stylesheet) Adjusting navtab font color

app/_data/docs_nav_ee_2.1.x.yml
* Added Brain section to TOC; sub-section Service Map 
* Added Immunity section to TOC; sub-section Alerts
=> docs(TOC)Added Brain and Immunity section

app/enterprise/2.1.x/vitals/overview.md
* Removed "Viewing the..." from a couple of sub-sections
=> docs(vitals) update section titles

app/enterprise/changelog.md
-- added 1.5.0.5 release to changelog
-- consists of fixes for Core, Manager, and Dev Portal
=> docs(changelog) add 1.5.0.5 release to changelog

app/enterprise/1.3-x/developer-portal/working-with-templates.md, app/enterprise/1.5.x/developer-portal/working-with-templates.md, app/enterprise/2.1.x/developer-portal/working-with-templates.md
https://konghq.atlassian.net/browse/DOCS-1243 change paren to curly brace in code example
https://deploy-preview-2226--kongdocs.netlify.app/enterprise/2.1.x/developer-portal/working-with-templates/#template-content-val-as-arg
https://deploy-preview-2226--kongdocs.netlify.app/enterprise/1.5.x/developer-portal/working-with-templates/#template-content-val-as-arg
https://deploy-preview-2226--kongdocs.netlify.app/enterprise/1.3-x/developer-portal/working-with-templates/#template-content-val-as-arg
=> DOCS-1243 fix end curly brace (customer issue)

app/enterprise/2.1.x/deployment/installation/overview.md
Minor edit to installation overview page to remove inaccurate text.
Preview: https://deploy-preview-2242--kongdocs.netlify.app/enterprise/2.1.x/deployment/installation/overview/
=> docs(ee-install) Remove inaccurate text from installation overview

app/enterprise/2.1.x/deployment/hybrid-mode.md
* Remove note about nodes not being visible in Kong Manager
* Move Kubernetes section out of Limitations into Platform Compatibility
Preview: https://deploy-preview-2239--kongdocs.netlify.app/enterprise/2.1.x/deployment/hybrid-mode/
=> docs(ee-hybrid) Remove incorrect kubernetes info and add note about manager

app/_hub/kong-inc/openid-connect/index.md
=> OIDC add display_errors param

app/_data/docs_nav_ee_2.1.x.yml
- added Deployment Guidelines section
- rearranged topics in Deployment section
- starts with Installation section
- moved "Network & Firewall" from References section
=> docs(2.1.x TOC) add deployment guidelines section

app/enterprise/changelog.md
=> docs(changelog) 2.1.3.0

app/enterprise/2.1.x/release-notes.md
-- 2.1.3.0 release notes, which include the 2.1.0.0-beta features.
=> docs(release-notes) 2.1.3.0 Release Notes update

app/_hub/kong-inc/zipkin/index.md
I noticed @kikito 's great new blog post on Zipkin, so I added a link to the docs.
https://konghq.atlassian.net/browse/DOCS-1262
https://deploy-preview-2259--kongdocs.netlify.app/hub/kong-inc/zipkin/#see-also
=> add link to Enrique's new blog post on Zipkin

app/enterprise/2.1.x/vitals/vitals-reports.md
- Changed title to initial cap "Report" in topic and section titles.
=> docs(vitals) Changed title to initial cap report

app/enterprise/2.1.x/support-policy.md
-- Update the support policy table with 2.1.3.x information
=> docs(support-policy) Update support table 2.1.3.x

app/_hub/kong-inc/upstream-tls/index.md
Updating Upstream TLS plugin view to include instructions on how to add NGINX directives into Kong
=> minor update to Upstream TLS plugin page

app/enterprise/2.1.x/brain-immunity/model-training.md, app/enterprise/2.1.x/brain-immunity/slack-integration.md
- did some minor heading formatting
=> docs(brain-immunity) formatting updates

app/2.1.x/upgrading.md, app/_data/docs_nav_2.1.x.yml
=> docs(ce/2.1) clone UPGRADE.md from the kong/kong repo

app/_data/docs_nav_ee_2.1.x.yml, app/enterprise/2.1.x/deployment/classic-deployment.md, app/enterprise/2.1.x/deployment/classic-mode.md
-- Adding topic for Classic Deployment modes
-- including Embedded and Distributed
=> docs (deployment) Classic deployment mode

app/_data/docs_nav_ee_2.1.x.yml, app/enterprise/2.1.x/doc-updates.md
-- New section "What's New in the Docs
-- Removed this section from the Release Notes
=> docs(docs-updates) What's New in the Docs

app/getting-started-guide/2.1.x/improve-performance.md
Updated the caching content type to application/json; charset=utf-8 which is the correct content type.
=> Updated the caching content type

app/_data/docs_nav_ee_2.1.x.yml, app/enterprise/2.1.x/deployment/upgrades/migrate-ce-to-ke.md, app/enterprise/2.1.x/deployment/upgrades/migrations.md
Post-release reorg at request of Shane and Gayle. See:
https://konghq.atlassian.net/browse/DOCS-1265
-make breaking changes a subitem of main migration topic
-move dev portal migration out of main migrate topic
-Break out migrate CE to KE
https://deploy-preview-2271--kongdocs.netlify.app/enterprise/2.1.x/deployment/upgrades/migrations/
=> decompose migrations topics 

app/_hub/optum/kong-splunk-log/index.md
Fixes: https://github.com/Kong/kong/issues/6285
=> (plugins) add splunk endpoint conf to docs

app/getting-started-guide/2.1.x/expose-services.md
Adding request to the curl and http validation step to improve how the output is displayed.
=> Adding request to the curl and http validation step

app/enterprise/changelog.md
-- added fixes including:
Core:
* Properly migrate the workspaces associated with ACL groups. (FTI-1821)
* Improved the amount of logging in the migrations framework. (FT-1472)
Kong Manager: 
* Fixed docs link and messaging on Dev Portals page. (TDX-1029)
=> docs(changelog) update for 2.1.3.1

app/enterprise/2.1.x/brain-immunity/overview.md
-- added version compatibility table
=> docs (brain-immunity) version compatibility update

app/enterprise/2.1.x/doc-updates.md
-- Added Upgrades and Migrations section
-- Changed H1 title
-- Added release notes, changelog, what's new in docs, and version links
-- Added link to declarative config YAML example
=> docs(2.1.x) doc-updates

app/enterprise/1.5.x/kong-for-kubernetes/install-on-kubernetes.md, app/enterprise/2.1.x/kong-for-kubernetes/install-on-kubernetes.md
Updating K4K8s Enterprise instructions to add warning about deleting Postgres PV and enabling admin's API
=> Adding clarifications to avoid common issues our users currently encounter 

app/_data/docs_nav_ee_1.5.x.yml, app/enterprise/1.5.x/brain-immunity/alerts.md, app/enterprise/1.5.x/brain-immunity/auto-generated-specs.md, app/enterprise/1.5.x/brain-immunity/install-configure.md, app/enterprise/1.5.x/brain-immunity/model-training.md, app/enterprise/1.5.x/brain-immunity/overview.md, app/enterprise/1.5.x/brain-immunity/service-map.md, app/enterprise/1.5.x/brain-immunity/slack-integration.md
-- made changes to 1.5.x Brain and Immunity TOC to match 2.1.x
=> docs(1.5.x) update TOC/topics for brain & immunity

app/enterprise/1.5.x/brain-immunity/install-configure.md
-- replaced 2.1.x with 1.5.x in install instructions
-- updated version information
=> docs(1.5.x) update install & version info for B&I

app/_hub/kong-inc/response-transformer/index.md
=> docs(response-transformer) add the json_types feature

app/enterprise/1.5.x/brain-immunity/install-configure.md
-- updated version section for Brain and Immunity 1.5.x
=> docs(1.5.x) version update B&I

app/enterprise/2.1.x/brain-immunity/install-configure.md
-- updated versioning table for Brain and Immunity
=> docs (2.1.x) update version info for B&I

app/_hub/kong-inc/response-transformer-advanced/index.md
=> docs(response-transformer-advanced) normalize the json_types example

app/mesh/1.0.x/index.md, app/mesh/1.0.x/overview.md
Cleaning up doc for language and formatting, as there was no time for review before publishing the first version of this doc.
Previews:
[Landing page](https://deploy-preview-2289--kongdocs.netlify.app/mesh/)
[Overview](https://deploy-preview-2289--kongdocs.netlify.app/mesh/1.0.x/overview)
=> docs(mesh) Landing page and overview

app/mesh/1.0.x/features/vault.md
* Reorganized the usage and auth sections for better flow
* Edits for grammar, clarity, etc.
Preview: https://deploy-preview-2297--kongdocs.netlify.app/mesh/1.0.x/features/vault/
=> docs(mesh) Vault doc improvements

app/_layouts/extension.html
Title says it all. Fixing copy/paste error in plugin examples.
=> docs(plugins) Fixing kubernetes API versions

app/_hub/kong-inc/serverless-functions/index.md
https://konghq.atlassian.net/browse/DOCS-1302
https://konghq.atlassian.net/browse/FTI-1864
https://deploy-preview-2307--kongdocs.netlify.app/hub/kong-inc/serverless-functions/
=> add security warning

app/mesh/1.0.x/installation/amazonlinux.md, app/mesh/1.0.x/installation/centos.md, app/mesh/1.0.x/installation/debian.md, app/mesh/1.0.x/installation/docker.md, app/mesh/1.0.x/installation/kubernetes.md, app/mesh/1.0.x/installation/macos.md, app/mesh/1.0.x/installation/openshift.md, app/mesh/1.0.x/installation/redhat.md, app/mesh/1.0.x/installation/ubuntu.md, package-lock.json
Adding licensing docs to Kong Mesh.
=> docs(mesh): adding licensing instructions

app/_hub/kong-inc/acme/0.2.7.md
=> doc(plugin/acme) update plugin version and add new config key

app/_hub/kong-inc/request-validator/index.md
https://konghq.atlassian.net/browse/DOCS-1276 subticket of Shane's plugin issues in https://konghq.atlassian.net/browse/DOCS-1162.
https://deploy-preview-2313--kongdocs.netlify.app/hub/kong-inc/request-validator/#further-references
Now goes to latest
=> update link to schema topic

app/_hub/kong-inc/jwt/0.1-x.md, app/_hub/kong-inc/jwt/2.1-x.md, app/_hub/kong-inc/jwt/index.md
https://konghq.atlassian.net/browse/DOCS-1268 from Shane's ticket https://konghq.atlassian.net/browse/DOCS-1162
Fixed a few example syntax noted in the ticket (see line diffs https://github.com/Kong/docs.konghq.com/pull/2318/files#diff-c860afd4d48dd18fb2764c0180bdc42dR461 and https://github.com/Kong/docs.konghq.com/pull/2318/files#diff-c860afd4d48dd18fb2764c0180bdc42dR517) and copy edited source.
https://deploy-preview-2318--kongdocs.netlify.app/hub/kong-inc/jwt/
=> JWT plugin doc fixes

app/_data/kong_versions.yml
=> Release: Kong Mesh 1.0.2

app/_data/kong_versions.yml
This updates all Enterprise install topics.
=> docs(ee-versions) Update to latest version of kong enterprise

app/_hub/kong-inc/jwt/index.md
https://konghq.atlassian.net/browse/DOCS-1326 auth0 doc update for JWT plugin
https://deploy-preview-2338--kongdocs.netlify.app/hub/kong-inc/jwt/#using-the-jwt-plugin-with-auth0
=> JWT w/auth0 add regions id in download pem cert url

app/_assets/stylesheets/header.less, app/_assets/stylesheets/page.less, app/_includes/nav.html
* add Kong Mesh to nav
* remove Kong Brain from product nav
* adjust tablet width content overflow in page header
=> update nav & page overflow

app/_assets/javascripts/app.js, app/_assets/stylesheets/header.less, app/_includes/nav.html
* narrow promo banner for Kong Summit above nav
* close & scroll collapse functions w/ localStorage to preserve dismissed state
* dynamic JS countdown timer including alternate content for day of event
* updated styles for compressed states and mobile views
=> add Summit promo banner to site header

app/enterprise/1.3-x/developer-portal/working-with-templates.md, app/enterprise/1.5.x/developer-portal/working-with-templates.md, app/enterprise/2.1.x/developer-portal/working-with-templates.md
=> docs(ee/dev-portal) link to lua-resty-template

app/_assets/stylesheets/page.less
Preview (switch to PKI tab): https://deploy-preview-2346--kongdocs.netlify.app/enterprise/2.1.x/deployment/hybrid-mode-setup/#step-1-generate-a-certificatekey-pair
=> docs(style) Adding vertical scroll to codeblocks

app/enterprise/2.1.x/deployment/installation/amazon-linux-2.md, app/enterprise/2.1.x/deployment/installation/amazon-linux.md, app/enterprise/2.1.x/deployment/installation/centos.md, app/enterprise/2.1.x/deployment/installation/rhel.md, app/enterprise/2.1.x/deployment/installation/ubuntu.md, app/install/aws-linux.md, app/install/centos.md, app/install/debian.md, app/install/redhat.md, app/install/ubuntu.md
See individual commits for details.
=> Improve the CE and EE installation docs

app/enterprise/1.5.x/kong-manager/administration/workspaces/workspaces.md, app/enterprise/2.1.x/kong-manager/administration/rbac/rbac.md, app/enterprise/2.1.x/kong-manager/administration/workspaces/workspaces.md
Temporary solution for a wider problem with versioned redirects.
=> docs(manager) Fix redirect and update link

app/_data/kong_versions.yml
Companion update to https://github.com/Kong/docs.konghq.com/pull/2348.
=> docs(release) Update EE versions based on new 2.1 and 1.5 releases

app/enterprise/changelog.md
-- added info for 2.1.4.0 and 1.5.0.6 Enterprise patch releases
=> Updated changelog to include 2.1.4.0 and 1.5.0.6

app/enterprise/2.1.x/cli.md
`kong migrations` has some changes that are currently undocumented.
=> docs(ee-cli) Update Enterprise CLI doc for 2.1

app/_assets/stylesheets/page.less, app/_includes/nav.html
* fix max-width on page header background to avoid horizontal overflow
* update Summit promo banner text for 1 day remaining
=> adjust page header overflow, Summit banner text

app/_data/kong_versions.yml
Update version for installer script.
=> Release: Kong Mesh 1.0.3

app/_data/kong_versions.yml, app/deck/installation.md
* update version to 1.2.1
* set variables so we only have to update one place (same as other install docs)
Preview: https://deploy-preview-2364--kongdocs.netlify.app/deck/installation/#linux
=> docs(deck) Change version in install topic to variable

app/2.1.x/proxy.md
=> docs(proxy) fix minor styling issues

app/_assets/javascripts/app.js, app/_includes/nav.html
* remove narrow top promo banner & related scripts
=> remove Summit promo banner

app/_data/docs_nav_ee_2.1.x.yml, app/enterprise/2.1.x/developer-portal/files-api.md, app/enterprise/2.1.x/developer-portal/structure-and-file-types.md
https://konghq.atlassian.net/browse/DOCS-1349 per associated ticket https://konghq.atlassian.net/browse/FTI-1931
https://deploy-preview-2367--kongdocs.netlify.app/enterprise/2.1.x/developer-portal/files-api/
After the content for 2.1.x is approved, will backport to 1.3-x and 1.5.x.
=> docs(files) add doc for files API

LICENSE
=> Updated LICENSE from (C) to ©

app/_data/docs_nav_ee_1.3-x.yml, app/_data/docs_nav_ee_1.5.x.yml, app/enterprise/1.3-x/developer-portal/files-api.md, app/enterprise/1.5.x/developer-portal/files-api.md
https://konghq.atlassian.net/browse/DOCS-1349 per associated ticket https://konghq.atlassian.net/browse/FTI-1931
This PR backports content approved by @Jlawlzz and @lena-larionova into 1.5.x and 1.3-x as directed by @GayleNeumann.
https://deploy-preview-2379--kongdocs.netlify.app/enterprise/1.5.x/developer-portal/files-api/
https://deploy-preview-2379--kongdocs.netlify.app/enterprise/1.3-x/developer-portal/files-api/
=> Backport dev portal files api to 1.5.x and 1.3-x

app/2.1.x/clustering.md, app/enterprise/2.1.x/clustering.md
clustering guide and link to the configuration guide for it
=> docs(clustering) mention about the read-only replica support in the

app/mesh/1.0.x/installation/openshift.md
Based on updates in https://github.com/kumahq/kuma-website/pull/288/files.
Preview: https://deploy-preview-2405--kongdocs.netlify.app/mesh/1.0.x/installation/openshift/
Ignore the floating copy-code icon, that's only an issue in the preview
=> docs(mesh) Update openshift install doc

app/enterprise/2.1.x/doc-updates.md
-- updating version number in "What's New in the Docs" from 2.1.3.0 to 2.1.x so that it matches the dropdown and URL version in docs.
See preview: https://deploy-preview-2396--kongdocs.netlify.app/enterprise/2.1.x/doc-updates/#kong-enterprise-21x-docs
=> docs(new-in-docs) update version number

app/enterprise/2.1.x/kong-for-kubernetes/install.md
=> Update bitly link

app/_data/kong_versions.yml
Added new entry for 2.2 CE series
=> doc(kong_versions) updated for 2.2.0 release

app/getting-started-guide/2.1.x/prepare.md
Minor edit for consistency with the request a couple of lines above it.
=> docs(getting-started) Fix request for consistency

app/_data/kong_versions.yml, app/enterprise/changelog.md
Update version for installation topics and add changelog entry.
=> Release: EE 2.1.4.1

app/enterprise/2.1.x/vitals/vitals-reports.md
-- added link in prerequisites section to Vitals with InfluxDB topic.
=> docs(vitals) add link to InfluxDB topic

app/enterprise/2.1.x/developer-portal/configuration/authentication/oidc.md
Mainly fixing a link, adjusting header titles and typos along the way.
=> fix(oidc/portal) Fix link and adjust header titles

app/_hub/moesif/kong-plugin-moesif/index.md
- Fix incorrect plugin name
- Validated against latest versions
- Reduce intro text
- Add extra options
=> Update: Moesif Plugin Docs. Fixed Plugin Name

app/_data/extensions/kong-inc/zipkin/versions.yml, app/_hub/kong-inc/zipkin/1.1.x.md, app/_hub/kong-inc/zipkin/index.md
=> docs(zipkin) add docs for zipkin 1.2.0 plugin

app/enterprise/changelog.md
-- updated changelog with 1.5.0.7 Fix information.
=> docs(changelog-1.5.0.7) update changelog

app/enterprise/2.1.x/brain-immunity/auto-generated-specs.md, app/enterprise/2.1.x/brain-immunity/changelog.md, app/enterprise/2.1.x/brain-immunity/install-configure.md, app/enterprise/2.1.x/brain-immunity/overview.md, app/enterprise/2.1.x/brain-immunity/service-map.md, app/enterprise/2.1.x/brain-immunity/troubleshooting.md
-- changed the deprecated note to verision 2.1.5.0
-- other minor edits
=> docs(brain-immunity) changed brain deprecated note to 2.1.4.2

CONTRIBUTING.md
Based on changes introduced in #2442.
=> docs(contribution guidelines) Add instructions for using tabbed codeblocks

app/enterprise/2.2.x/admin-api/index.md
https://konghq.atlassian.net/browse/DOCS-1434
https://deploy-preview-2461--kongdocs.netlify.app/enterprise/2.2.x/admin-api/#service-object
All service sections now have this update:
=> Admin API update protocols for service object 2.2 EE

algolia/config-kic.json, app/_layouts/docs-v2.html
As title says. Create config file and add to layout.
=> Create Algolia config for KIC

app/_data/docs_nav_ee_2.2.x.yml, app/_data/docs_nav_kic_1.0.x.yml
Align KIC nav with new nav file for Enterprise 2.2.
=> docs(kic) Nav alignment

app/enterprise/2.2.x/admin-api/index.md
https://konghq.atlassian.net/browse/DOCS-1432
https://deploy-preview-2466--kongdocs.netlify.app/enterprise/2.2.x/admin-api/#route-object
Compare with community:
https://docs.konghq.com/2.2.x/admin-api/#route-object
This should be autogenerated and single-sourced
=> Add request and response buffering Admin API route properties to 2.2 enterprise topic

app/enterprise/2.2.x/vitals/vitals-influx-strategy.md
=> fix(vitals) Update redirect to 2.2

algolia/config-mesh.json, app/_layouts/docs-v2.html, app/mesh/1.0.x/features/vault.md, app/mesh/1.0.x/gettingstarted.md, app/mesh/1.0.x/index.md, app/mesh/1.0.x/install.md, app/mesh/1.0.x/installation/amazonlinux.md, app/mesh/1.0.x/installation/centos.md, app/mesh/1.0.x/installation/debian.md, app/mesh/1.0.x/installation/docker.md, app/mesh/1.0.x/installation/helm.md, app/mesh/1.0.x/installation/kubernetes.md, app/mesh/1.0.x/installation/macos.md, app/mesh/1.0.x/installation/openshift.md, app/mesh/1.0.x/installation/redhat.md, app/mesh/1.0.x/installation/ubuntu.md
Docs ticket: https://konghq.atlassian.net/browse/DOCS-1299
Adding a search bar for Kong Mesh.
Preview: https://deploy-preview-2472--kongdocs.netlify.app/mesh/
=> feat(mesh-search) Add algolia search index for mesh

algolia/config-deck.json, app/_layouts/docs-v2.html, app/deck/commands.md, app/deck/compatibility-promise.md, app/deck/design-architecture.md, app/deck/faqs.md, app/deck/guides/backup-restore.md, app/deck/guides/best-practices.md, app/deck/guides/ci-driven-configuration.md, app/deck/guides/deduplicate-plugin-configuration.md, app/deck/guides/distributed-configuration.md, app/deck/guides/getting-started.md, app/deck/guides/kong-enterprise.md, app/deck/guides/multi-file-state.md, app/deck/index.md, app/deck/installation.md, app/deck/overview.md, app/deck/terminology.md
Docs ticket: https://konghq.atlassian.net/browse/DOCS-1249
* Adding decK config for algolia
* Adding search script to docs layout
* Removing `no_search` setting from decK pages
Preview: https://deploy-preview-2474--kongdocs.netlify.app/deck/overview/ - search for anything, only decK related results should appear
=> feat(deck-search) Add algolia search bar for decK

app/enterprise/2.2.x/deployment/licenses/report.md
Update license report to include services
=> Update license report to include services

app/enterprise/2.2.x/support-policy.md
-- Updated content to new Support Policy, per Shane's doc: https://docs.google.com/document/d/1mCe3gX-3r3QaSLLMhj_vZU1Bn-Yu6SUVXQPwAbvhFp4/edit#
-- This update to be released on Monday, Nov 30, 2020, per Tom in Legal. 
-- Coordinate this doc with Shane/Product, Jimmy/Customer Support, and Tom/Legal.
See https://deploy-preview-2476--kongdocs.netlify.app/enterprise/2.2.x/support-policy/
=> doc(support-policy) update to new support policy

app/404.html
Related docs ticket: https://konghq.atlassian.net/browse/DOCS-1452
Removing a bunch of extra content and metadata from the 404 page:
- feedback widget
- reading time
- search bar (ideally it should have a search bar, but in the current search implementation search doesn't work on this page, as it requires a base product index)
- version dropdown
Preview: https://deploy-preview-2484--kongdocs.netlify.app/404.html
=> fix(404) Remove unnecessary content from 404 page

app/_data/kong_versions.yml
Updating metadata.
Preview: https://deploy-preview-2486--kongdocs.netlify.app/mesh/1.1.x/install/
=> Update Kong Mesh version for 1.1.1

app/_data/extensions/kong-inc/acme/versions.yml, app/_hub/kong-inc/acme/0.2.11.md, app/_hub/kong-inc/acme/0.2.2.md, app/_hub/kong-inc/acme/index.md
=> plugins(acme) add document for external account binding

app/_hub/kong-inc/ldap-auth-advanced/index.md, app/_hub/kong-inc/ldap-auth/index.md
https://konghq.atlassian.net/browse/DOCS-1482 port 636 not 686
=> LDAPs port fix 

app/2.2.x/kong-user.md, app/enterprise/2.2.x/deployment/kong-user.md
@lena-larionova I forgot to do these changes in that previous PR.
=> docs(kong-user) minor adjustments

app/getting-started-guide/2.2.x/expose-services.md
The button on the services overview page says "Add Route".
=> Click on Add Route

app/getting-started-guide/2.1.x/secure-services.md, app/getting-started-guide/2.2.x/secure-services.md, app/getting-started-guide/CE-2.0.x_KE-1.5.x/secure-services.md
=> click edit to disable plugin

app/_data/kong_versions.yml
=> Update Kong Mesh version for 1.1.2

app/_hub/reedelk/reedelk-transformer/index.md
=> Changed url due to a maintainer change

app/_hub/kong-inc/oauth2/index.md
Said field is a DAO field, not a plugin configuration.
Relevant PR: https://github.com/Kong/kong/pull/5610
=> docs(hub/oauth2) fix hash_secret docs

app/enterprise/changelog.md
See Changelog for details added for 2.2.1.0 and 2.1.4.3: https://konghq.atlassian.net/wiki/spaces/FTT/pages/8356124/Kong+Enterprise+-+Changelog+Features+Release+Schedule
=> docs(changelog) added 2.2.1.0, 2.1.4.3, and 1.5.0.9 patch releases

app/_data/kong_versions.yml
Updating 2.2.x, 2.1.x, and 1.5.x based on releases that came out on December 31st.
https://docs.konghq.com/enterprise/changelog/
=> docs(ee) Update patch versions

app/_hub/kong-inc/application-registration/index.md, app/_hub/kong-inc/key-auth/index.md
Fixing my own mistake @tlblessing
=> docs(plugins) Remove variables from front matter

app/2.3.x/admin-api.md, app/2.3.x/configuration.md, app/2.3.x/db-less-admin-api.md, app/2.3.x/pdk/kong.log.md, app/2.3.x/pdk/kong.node.md, app/_data/docs_nav_2.3.x.yml, app/_data/kong_versions.yml, autodoc-nav/docs_nav_2.3.x.yml.head.in
Adds autodocs generated from Kong 2.3
=> docs(2.3.x) create the 2.3.x doc tree by copying over 2.2.x directory

app/2.3.x/hybrid-mode.md
modified the Admin API output to reflect the actual output from Kong
=> docs(hybrid-mode) add descriptions of the Hybrid mode version check and

app/_data/kong_versions.yml
=> Update mesh version

app/kubernetes-ingress-controller/1.0.x/guides/using-oidc-plugin.md, app/kubernetes-ingress-controller/1.1.x/guides/using-oidc-plugin.md
Fixing typo reported on Slack.
=> docs(kic) Fixing typo in OIDC plugin example

app/enterprise/2.1.x/deployment/upgrades/migrations.md
=> fix small typo in rate-limiting-advanced section

app/_hub/plugins/overview/index.md, app/_layouts/extension.html, app/_redirects
=> fix(links) Add a missed redirect

app/enterprise/changelog.md
updating 2.3.x changelog for Kong Gateway (Enterprise)
=> docs(changelog) update KE 2.3.x changelog

algolia/config-full-docs.json
Update version so that algolia searches the most recently published doc.
=> chore(algolia) Update Enterprise version for full site search

app/_data/kong_versions.yml
Updating metadata for CE 2.3.2 release.
=> chore(versions) Update release metadata for 2.3

app/enterprise/2.3.x/release-notes.md
=> Fix link in release notes

app/_data/kong_versions.yml, app/mesh/1.1.x/gettingstarted.md, app/mesh/1.1.x/install.md
Add information about license behavior for Mesh to Mesh install overview; clean up a bit of related getting started content.
Fixes https://konghq.atlassian.net/browse/DOCS-1575
=> Add details about mesh licensing, clean up a bit of getting started page

app/_includes/footer.html
Updating links in the footer to match the marketing site.
Preview: scroll to the bottom of any docs page in https://deploy-preview-2589--kongdocs.netlify.app
=> docs(footer) Update product links

app/_hub/kong-inc/application-registration/index.md
https://konghq.atlassian.net/browse/DOCS-1396
Adding for most current version only.
Schema:
https://github.com/Kong/kong-ee/blob/master/kong/plugins/application-registration/schema.lua
https://deploy-preview-2592--kongdocs.netlify.app/hub/kong-inc/application-registration/
=> App reg plugin datatypes

app/enterprise/2.3.x/plugin-development/custom-entities.md, app/gateway-oss/2.3.x/plugin-development/custom-entities.md
Remove curly brackets around id. The signature is the same as the select.
=> Update entity delete example

app/_hub/kong-inc/rate-limiting/index.md
https://konghq.atlassian.net/browse/DOCS-1396
Adding for most current version only. Murillo and I already added to advanced plugin, so double-checked against that and schema (which is quite different from Enterprise).
Schema link:
https://github.com/Kong/kong-ee/blob/master/kong/plugins/rate-limiting/schema.lua
https://deploy-preview-2594--kongdocs.netlify.app/hub/kong-inc/rate-limiting/
=> Rate Limiting plugin datatypes

app/_hub/kong-inc/proxy-cache/index.md
https://konghq.atlassian.net/browse/DOCS-1396
Adding for most current version only. Murillo and I already updated advanced version of this plugin so just copied that over.
Schema link:
https://github.com/Kong/kong-plugin-proxy-cache/blob/master/kong/plugins/proxy-cache/schema.lua
https://deploy-preview-2593--kongdocs.netlify.app/hub/kong-inc/proxy-cache/
=> Proxy Cache plugin datatypes

app/enterprise/2.3.x/deployment/installation/docker.md
=> fixed a small typo on the code

app/konnect/updates.md
Docs ticket: https://konghq.atlassian.net/browse/DOCS-1596
Release notes for Konnect deployment on February 23rd.
Release notes for:
* Logging plugins
* 2.3 support
* advanced runtime config
https://deploy-preview-2620--kongdocs.netlify.app/konnect/updates/
=> Konnect update for 2021-02-23

app/_hub/kong-inc/response-transformer-advanced/index.md
Add paragraph on the usage of new nested JSON and array navigation feature. Also addressing various small things, e.g. fix formatting and consistent naming.
=> Response Transformer Advanced: Complete docs for 2.3 and cleanup

app/_hub/kong-inc/bot-detection/index.md
Schema link:
https://github.com/Kong/kong-ee/blob/master/kong/plugins/bot-detection/schema.lua
https://deploy-preview-2616--kongdocs.netlify.app/hub/kong-inc/bot-detection/
=> Bot Detection plugin add datatypes

.github/PULL_REQUEST_TEMPLATE.md
Updating github PR template with new/more useful structure.
See https://docs.google.com/document/d/1j0XK5eUHwKzpe-DScndL6ApIsARZZgclFs009QqlJEo/edit#.
N/A
=> Update PR template with real structure [skip ci]

app/konnect/runtime-manager/kong-gateway-runtime.md
Updating KE version to real version, as 2.3.0.0 doesn't exist.
=> [no ticket] Konnect: Fix KE version number

app/gateway-oss/2.3.x/pdk/kong.response.md
@reviewer
Fix broken rendering of `kong.response.error` section
=> Fix Markdown markup in kong.response.md

app/_includes/delighted.html, app/_includes/head.html
Removing very old feedback widget, which still loads on each page but does nothing.
We don't use it, and haven't for a very long time.
N/A
=> [DOCS-1357] Remove old feedback widget

app/_data/docs_nav_mesh_1.2.x.yml, app/_includes/breadcrumbs.html, app/mesh/1.2.x/patches/opa-policy.yaml, app/mesh/changelog.md
Add changelog, edit, add to left nav, fix breadcrumbs
Release! https://konghq.atlassian.net/browse/DOCS-1649
https://deploy-preview-2672--kongdocs.netlify.app/mesh/changelog/
check left nav and breadcrumb navigation, pls&tysm!
=> docs(*) add Kong Mesh changelog with upgrade instructions

app/mesh/installer.sh
* support rhel7 distro
* fix shellcheck
@reviewer
=> chore(*) mesh installer updates

app/_data/kong_versions.yml, app/mesh/changelog.md
=> docs(mesh) release 1.2.1

app/enterprise/changelog.md
Terry approved. 
Release date year is incorrect. Changed from 2020 to 2021.
Corrected date. 
No need for testing.
=> docs(changelog) update release date

app/_hub/reedelk/reedelk-transformer/index.md
=> Changed publisher

app/konnect/getting-started/configure-runtime.md, app/konnect/runtime-manager/kong-gateway-runtime.md
@skibum 
Remove HTTPie from a requirements list. New updated version of the runtimes script won't require to have it preinstalled.
New updated version of the runtimes script won't require to have it preinstalled.
N/A
=> docs(konnect-runtimes) remove httpie from a requirements list

app/mesh/1.2.x/features/opa.md
Include example how to use OPA.
Not sure if this is the right place to show it. Back in the days we were expanding Kuma Demo with examples https://github.com/kumahq/kuma-demo but I feel like it's important to show an example of OPA, because it's harder to use after reading than for example TrafficPermission or TrafficRoute
=> Provide example for OPA

app/mesh/1.2.x/features/kds-auth.md
* Fix missing `\`
* Add an annotation that when you are starting from scratch you can enable auth on global first
=> fix new lines in auth kds and add annotation about starting from scratch

app/_hub/kong-inc/correlation-id/index.md
https://konghq.atlassian.net/browse/DOCS-1654 part of epic https://konghq.atlassian.net/browse/DOCS-1396.
Schema:
https://github.com/Kong/kong-ee/blob/master/kong/plugins/correlation-id/schema.lua
https://deploy-preview-2704--kongdocs.netlify.app/hub/kong-inc/correlation-id/#parameters
=> [DOCS-1654] Correlation ID plugin add datatypes; corrections

app/konnect/runtime-manager/kong-gateway-runtime.md
@nikirago, @rainest 
Adding Helm option when setting up a Konnect runtime through Runtime Manager's advanced config.
Questions for reviewers:
* The [sample values.yaml](https://github.com/Kong/charts/blob/main/charts/kong/example-values/minimal-kong-hybrid-data.yaml) file I based this on has `postgres: enabled` for the data plane, which can't be right - and in fact, I couldn't get it to launch until I set it to `postgres: disabled`. Was I missing something, or does the sample file need correcting? Or is it just different for `pki` mode?
* How do you add/specify the CA cert? In the doc for kubernetes tls secrets, I couldn't find any info on adding anything beyond one cert and key: https://kubernetes.io/docs/concepts/configuration/secret/#tls-secrets
* Any other steps or instructions …
=> [DOCS-1650] Konnect runtime manager: Helm config instructions

app/_hub/kong-inc/serverless-functions/index.md
https://konghq.atlassian.net/browse/DOCS-1692
Direct review link: 
https://deploy-preview-2709--kongdocs.netlify.app/hub/kong-inc/serverless-functions/#sandboxing
=> [DOCS-1692] Serverless functions plugin sandbox *.os clarification

.github/workflows/algolia.yml
Changing the branch that the algolia action targets to `main`.
Master branch was renamed to `main`.
N/A
=> (no ticket) Update algolia action to use main branch

app/enterprise/changelog.md
@GayleNeumann - here are the fixes to the changelog per Shane's notes
Shane found some typos/issues with the 2.3.3.0 changelog that need addressing.
Will add Netlify link once available.
[2.3.3.0 changelog](https://deploy-preview-2723--kongdocs.netlify.app/enterprise/changelog/#2330)
=> Fixing issues with the 2.3.3.0 changelog

app/gateway-oss/2.3.x/kong-for-kubernetes/install.md
@reviewer @Kong/team-docs
IMHO, in the section "Using a database for Kong for Kubernetes", there would be 2 cases: the first case is that user does not want to run Kong with the DB, and the other case is "decide to use a DB".
Please decline this PR, if my understanding is incorrect
=> update wording using a database for Kong

app/gateway-oss/2.4.x/hybrid-mode.md
@HCloward @fffonion 
(PR description copied from https://github.com/Kong/docs.konghq.com/pull/2738).
Kong now has relaxed version check in hybrid mode between Control Planes and Data Planes, allowing
Data Planes that are missing minor updates (up to two) to still connect to the Control Plane. Also, now Data
Planes are allowed to have a superset of plugins in addition to the Control
Plane plugins.[6932](https://github.com/Kong/kong/pull/6932)
Also lowercasing all control plane/data plane instances while I'm in this topic.
new update for CE 2.4 beta - originally @fffonion opened a PR to update this content, but I messed up the PR and needed to recreate it
=> Hybrid mode relaxed version checks

app/enterprise/2.1.x/deployment/upgrades/migrations.md
The 1.5.x to 2.1.x migration cannot be performed without downtime like
most upgrades can. Instead, the user must take steps to cache all
entities on the 1.5 cluster to ensure it does not attempt to modify the
database while the 2.1 cluster is being brought up.
Existing docs: https://docs.konghq.com/enterprise/2.1.x/deployment/upgrades/migrations/#migrating-from-15x-or-21x-beta-to-21x
Signed-off-by: Tyler Ball <tyler.ball@konghq.com>
=> docs(ee/migrations) Fixing the 1.5.x to 2.1.x migration instructions

app/_hub/plugins/overview/index.md, app/gateway-oss/2.3.x/external-plugins.md, app/gateway-oss/2.4.x/external-plugins.md, app/gateway-oss/2.4.x/go.md, app/gateway-oss/2.4.x/index.md, app/install/source.md
@reviewer
TODO:
copy to app/enterprise/2.4.x/external-plugins.md as well
Logged https://konghq.atlassian.net/browse/DT-1390 to port this to EE for 2.4 release.
=> feat(pdk) add documents for JavaScript and Python PDK (2.4)

app/_hub/kong-inc/jwt/index.md
https://konghq.atlassian.net/browse/DOCS-1644 part of epic https://konghq.atlassian.net/browse/DOCS-1396.
JIRA Board has been renamed a few times...
Schema links:
https://github.com/Kong/kong-ee/blob/master/kong/plugins/jwt/schema.lua
https://deploy-preview-2719--kongdocs.netlify.app/hub/kong-inc/jwt/
=> [DOCU-678] JWT plugin datatypes

app/_hub/optum/kong-spec-expose/index.md
=> Optum 3rd party plugin expose specs

app/_hub/optum/kong-upstream-jwt/index.md
=> Optum 3rd party plugin JWT

app/_hub/optum/kong-service-virtualization/index.md
=> Optum 3rd party plugin

app/_hub/inspur/apig-request-transformer/index.md
apig req transform remove unsupported versions
=> Inspur 3rd party plugin

app/_hub/justeat/kongverge/index.md
=> Kongverge 3rd party plugin

app/_hub/qnap/api-transformer/index.md
=> API Transformer 3rd party plugin

app/gateway-oss/2.4.x/external-plugins.md
=> fix(external-plugins) add note for extra dependencies for JS plugins

app/konnect/deployment/index.md
=> Modified text to indicate that data planes route traffic (not the control plane)

app/_data/kong_versions.yml, app/mesh/changelog.md
@subnetmarco 
Bump Mesh version, add changelog entries
New release
https://deploy-preview-2784--kongdocs.netlify.app/mesh/changelog/
https://deploy-preview-2784--kongdocs.netlify.app/mesh/1.2.x/installation/kubernetes/ or any other install topic
=> Docs/mesh 1.2.2

app/enterprise/changelog.md
@tyler-ball - please take a look and make everything is still technically accurate - thanks!
Adding changelog entries to the ee changelog for the 2.2.1.2 and 2.3.3.1 patch releases. 
[DOCU-1400](https://konghq.atlassian.net/browse/DOCU-1400) 
[2.3.3.1](https://deploy-preview-2780--kongdocs.netlify.app/enterprise/changelog/#2331)
[2.2.1.2](https://deploy-preview-2780--kongdocs.netlify.app/enterprise/changelog/#2331)
=> [DOCU-1400] updates the changelog for ee with 2.2.1.2 and 2.3.3.1 patches

app/enterprise/2.1.x/go.md, app/enterprise/2.2.x/go.md, app/gateway-oss/2.1.x/go.md, app/gateway-oss/2.2.x/go.md
@reviewer
From https://github.com/Kong/docker-kong/issues/458
=> fix(go) update doc to use go mod when installing go-pluginserver

app/gateway-oss/2.4.x/admin-api.md
This change was done by regenerating the docs in the kong/kong repo with the https://github.com/Kong/kong/pull/7047 branch
@reviewer
=> docs(admin-api) mention utf-8 in Tags

app/enterprise/2.3.x/kong-manager/service-directory-mapping.md
=> Added note about using the global catalog port for Active Directory

app/gateway-oss/2.4.x/hybrid-mode.md
=> fix(hybrid) correct example for compatibility check

app/enterprise/changelog.md
Two items were included in this patch release:
* fixing hybrid mode issue
* solving an issue with mtls client certificates
@artomal - please review the text for the fix to hybrid mode to be sure it is accurate - thanks!
@fffonion - please review the text for the fix with mtls authentication to be sure it is accurate - thanks!
[2.3.3.2 changelog](https://60808d30e4d44200072bc557--kongdocs.netlify.app/enterprise/changelog/#2332)
=> [DOCU-1417]Adds changelog release notes for 2.3.3.2 patch

app/enterprise/changelog.md
* v1.5.0.11 and v.2.1.4.6 include minor fixes and internal updates
* v2.2.1.3 only includes internal updates
@tyler-ball - please check my wording for accuracy - thanks!
- [v1.5.0.11](https://deploy-preview-2806--kongdocs.netlify.app/enterprise/changelog/#15011)
- [v2.1.4.6](https://deploy-preview-2806--kongdocs.netlify.app/enterprise/changelog/#2146)
- [v.2.2.1.3](https://deploy-preview-2806--kongdocs.netlify.app/enterprise/changelog/#2213)
=> [DOCU-1422]Adds changelog entries for multiple patch releases

README.md, app/_data/kong_versions.yml
=> fix(2.4.0) kong version dependencies

app/kubernetes-ingress-controller/1.0.x/concepts/deployment.md, app/kubernetes-ingress-controller/1.1.x/concepts/deployment.md, app/kubernetes-ingress-controller/1.2.x/concepts/deployment.md
@reviewer
Typo under Kubernetes ingress controller deployment methods section
Fix typo `coorrectly` to `correctly`.
1. Ran locally and built using docker
=> Fix typo under kubernetes-ingress-controller deployment concepts

CONTRIBUTING.md
Update contributing guidelines to include required custom plugin logo, size, and sans transparency guidelines. 
https://konghq.atlassian.net/browse/DOCU-1455
=> [DOCU-1445] plugin custom logos now required, size guidelines

app/enterprise/2.3.x/developer-portal/theme-customization/markdown-extended.md
Expand example content for extended markdown usage for clarity.
@reviewer
=> Expand example content for extended markdown usage

app/gateway-oss/2.4.x/admin-api.md, app/gateway-oss/2.4.x/db-less-admin-api.md, app/gateway-oss/2.4.x/loadbalancing.md
Also, a lot of ending spaces were auto-removed.
=> docs(gateway-oss) update load balancer  description

app/_hub/kong-inc/statsd-advanced/1.3-x.md, app/_hub/kong-inc/statsd-advanced/index.md, app/_hub/kong-inc/statsd/0.1-x.md, app/_hub/kong-inc/statsd/index.md
https://konghq.atlassian.net/browse/DOCU-1402
OSS https://deploy-preview-2840--kongdocs.netlify.app/hub/kong-inc/statsd/#metrics
EE https://deploy-preview-2840--kongdocs.netlify.app/hub/kong-inc/statsd-advanced/#metrics
Only added to currently supported versions.
@aaronhmiller can you please review when you get a chance? Thanks for logging the ticket.
=> [DOCU-1402] StatsD plugins add ms uom for latency

app/mesh/installer.sh
=> chore(*) installer.sh support HTTP1/HTTP2 downloads

app/_hub/kong-inc/azure-functions/index.md
https://konghq.atlassian.net/browse/DOCU-672
Schema link:
https://github.com/Kong/kong-plugin-azure-functions/blob/master/kong/plugins/azure-functions/schema.lua
https://deploy-preview-2853--kongdocs.netlify.app/hub/kong-inc/azure-functions/
=> [DOCU-672] Azure Functions plugin add datatypes from schema

app/_hub/kong-inc/opa/index.md
https://konghq.atlassian.net/browse/DOCU-1502 See convo in docs slack from Li Yang confirmed by Harry Bagdi:
https://kongstrong.slack.com/archives/CDSTDSG9J/p1621423006007100
https://deploy-preview-2871--kongdocs.netlify.app/hub/kong-inc/opa/
=> [DOCU-1502] OPA plugin correct config rather than package example

app/_data/extensions/kong-inc/acme/versions.yml, app/_hub/kong-inc/acme/0.2.13.md, app/_hub/kong-inc/acme/index.md
**Docs ticket link:**
https://konghq.atlassian.net/browse/DOCU-668 part of epic https://konghq.atlassian.net/browse/DOCU-301
**Schema link:**
https://github.com/Kong/kong-plugin-acme/blob/master/kong/plugins/acme/schema.lua
**Handler link:**
https://github.com/Kong/kong-plugin-acme/blame/master/kong/plugins/acme/handler.lua 
Also see https://konghq.atlassian.net/browse/DOCU-473. This plugin has a version scheme that is an anomaly.
**Direct review link:**
https://deploy-preview-2874--kongdocs.netlify.app/hub/kong-inc/acme/
=> [DOCU-668] ACME plugin add datatypes

app/_hub/kong-inc/openwhisk/index.md
https://konghq.atlassian.net/browse/DOCU-668 part of epic https://konghq.atlassian.net/browse/DOCU-301
Schema link:
https://github.com/Kong/kong-plugin-openwhisk/blob/master/kong/plugins/openwhisk/schema.lua
https://deploy-preview-2870--kongdocs.netlify.app/hub/kong-inc/openwhisk/
=> [DOCU-668] Apache OpenWhisk plugin add datatypes; cleanup

app/enterprise/2.4.x/external-plugins.md, app/gateway-oss/2.4.x/external-plugins.md
@reviewer
Add guide on how to test JS plugins
=> feat(external-plugins) add guide on testing with js plugins

app/_includes/md/mesh/install-universal-quickstart.md, app/_includes/md/mesh/install-universal-run.md, app/mesh/1.2.x/installation/amazonlinux.md, app/mesh/1.2.x/installation/centos.md, app/mesh/1.2.x/installation/debian.md, app/mesh/1.2.x/installation/docker.md, app/mesh/1.2.x/installation/helm.md, app/mesh/1.2.x/installation/kubernetes.md, app/mesh/1.2.x/installation/macos.md, app/mesh/1.2.x/installation/openshift.md, app/mesh/1.2.x/installation/redhat.md, app/mesh/1.2.x/installation/ubuntu.md
Clean up Mesh install content for usability:
- removed all alerts
- also removed redundant content about needing a license
- changes only for v1.2
UX
Will post netlify links here when deploy preview ready
=> remove alerts and redundant content, light copyedits

app/_includes/head.html, app/_layouts/default.html
Adding google tag manager script.
Marketing request: https://konghq.atlassian.net/browse/DOCU-1499
TBA
=> [DOCU-1499] Add google tag manager to docs

app/enterprise/2.2.x/vitals/vitalsSpec.yaml, app/enterprise/2.3.x/vitals/vitalsSpec.yaml, app/enterprise/2.4.x/vitals/vitalsSpec.yaml
[DOCU-1496](https://konghq.atlassian.net/browse/DOCU-1496)
=> [DOCU-1496]Updates vitalsSpec.yaml files for Kong versions 2.2, 2.3, and 2.4

app/enterprise/1.3-x/getting-started/configuring-a-grpc-service.md, app/gateway-oss/0.10.x/proxy.md, app/gateway-oss/0.13.x/proxy.md, app/gateway-oss/0.14.x/proxy.md, app/gateway-oss/1.3.x/getting-started/configuring-a-grpc-service.md, app/gateway-oss/1.4.x/getting-started/configuring-a-grpc-service.md, app/gateway-oss/1.5.x/getting-started/configuring-a-grpc-service.md, app/gateway-oss/2.0.x/getting-started/configuring-a-grpc-service.md, app/gateway-oss/2.1.x/getting-started/configuring-a-grpc-service.md, app/gateway-oss/2.2.x/getting-started/configuring-a-grpc-service.md, app/gateway-oss/2.3.x/getting-started/configuring-a-grpc-service.md, app/gateway-oss/2.4.x/getting-started/configuring-a-grpc-service.md
=> Fix typo causing broken link

app/_includes/nav-v2.html
Updating the promo banner with new text and link.
https://konghq.atlassian.net/browse/DOCU-1545
Check the promo banner at the top of any page: https://deploy-preview-2927--kongdocs.netlify.app/ - should have the new text and link.
=> [DOCU-1545] Update promo banner

algolia/config-full-docs.json, app/_includes/search-selector.html, app/_layouts/default.html, app/_layouts/extension.html
* Adding changelogs to index
* Adding an entry for Konnect Platform
* Excluding summary/next steps sections from polluting search results
* Delete old search selector in favor of better config
Q for reviewers: should we also add the contributing guide to the search? 
Missing content from search indices and old search selector adding slightly to longer site build times.
Check that changelogs and Konnect Platform appear in search (it should already work, I ran the indexer locally).
https://deploy-preview-2930--kongdocs.netlify.app/
=> Algolia search index improvements

app/_data/tables/plugin_index.yml, app/_hub/kong-inc/datadog/index.md, app/_hub/kong-inc/exit-transformer/index.md, app/_hub/kong-inc/key-auth-enc/index.md, app/_hub/kong-inc/mocking/index.md, app/_hub/kong-inc/opa/index.md, app/_hub/kong-inc/request-size-limiting/index.md, app/_hub/kong-inc/request-transformer-advanced/index.md, app/_hub/kong-inc/request-transformer/index.md, app/_hub/kong-inc/response-transformer-advanced/index.md, app/_hub/kong-inc/serverless-functions/index.md, app/_hub/kong-inc/zipkin/index.md, app/konnect/deployment/index.md, app/konnect/runtime-manager/gateway-runtime-docker.md, app/konnect/runtime-manager/gateway-runtime-kubernetes.md, app/konnect/updates.md
@skibum 
* Updating language for upgrades
* Updating versions in install topics
* Adding list of plugins and updating compat table + plugin metadata
Some missed content from yesterday.
https://deploy-preview-2958--kongdocs.netlify.app/konnect/updates/
https://deploy-preview-2958--kongdocs.netlify.app/konnect-platform/compatibility/plugins/
=> [DOCU-1557] Konnect cloud 2.4.1.1 support: fixes and new plugins

app/_hub/kong-inc/mocking/index.md
Adding links to extra resources.
Request from Slack: https://kongstrong.slack.com/archives/CDSTDSG9J/p1624360435103500
https://deploy-preview-2960--kongdocs.netlify.app/hub/kong-inc/mocking/#see-also
=> Mocking plugin: links to more resources

app/konnect/updates.md
Adding update on global plugins.
Deploy went out last week. Bigger docs update in progress, but release notes should at least be updated to say that this is available. 
Link TBA
=> Konnect update 06/24

app/enterprise/2.4.x/plugins/oidc-cognito.md
@reviewer
Fixing overflow code snippets.
Text in inline code snippet was not wrapping, so it was widening the page and causing overflow issues.
https://deploy-preview-2971--kongdocs.netlify.app/enterprise/2.4.x/plugins/oidc-cognito/
=> OIDC with Amazon Cognito overflow bug

app/kubernetes-ingress-controller/1.3.x/concepts/deployment.md
=> fix: typo in database section

app/_hub/kong-inc/acl/index.md, app/_includes/hub-examples.html
* Add `DELETE` endpoint as per issue #855
* Add `PUT` endpoint
* Add `PATCH` endpoint
* Add `tags` as optional body param for `POST` endpoint
* Update -ing words and rm $ to match new style guide 
Missing endpoints. Addresses Issue [#855](https://github.com/Kong/docs.konghq.com/issues/855)
Tested locally. 
https://deploy-preview-2982--kongdocs.netlify.app/hub/kong-inc/acl/
=> [DOCU-1575] Add Missing Endpoints to ACL Plugin Docs

app/gateway-oss/2.4.x/secure-admin-api.md
* Add note to top of file about sending important data via https. 
* rm $ and minor text changes
Addresses Issue #585 
Link TBA
=> [DOCU-1589] add note to Secure Admin API guide about https

app/mesh/1.3.x/features/vault.md
Do not merge yet. This will be released in the next minor version of Kong Mesh
=> new parametrs for Vault integration in Kong Mesh

app/_includes/md/2.4.x/docker-install-steps.md, app/enterprise/2.4.x/deployment/installation/docker.md
* update tag image section
* text changes
Addresses Issue #2911 
TBA
=> [DOCU-1590] Update Docker Installation docs

.github/ISSUE_TEMPLATE.md
* Update front matter
* Update form
* Improve community ease of contribution
* Be more specific to increase clear communication
* Refer contributors to troubleshooting community
Local testing.
=> [DOCU-1567] issue template updates

app/kubernetes-ingress-controller/1.3.x/troubleshooting.md
Adds a KIC troubleshooting section covering basic usage of a tcpdump sidecar.
This is a useful debugging tool and instructions for it should live somewhere more accessible than the internal Slack conversation I keep linking people to.
=> doc(kic) add section on using tcdpump sidecars

app/_assets/stylesheets/base.less, app/_layouts/default.html, renovate.json
Remove three Bootstrap references. 
We have removed Bootstrap usage. 
Local testing.
=> [DOCU-1600] rm Bootstrap references

app/kubernetes-ingress-controller/1.3.x/guides/using-ingress-with-grpc.md
* update `apiVersion` value
* fix numbering and indentation on steps
* use active voice 
* take out `$` symbols on bash commands
* Pre-requisite -> Prerequisite
* Issue reported on docs, see more information on [DOCU-1593](https://konghq.atlassian.net/browse/DOCU-1593) task. 
* Update to conform to style guide
Tested locally
=> [DOCU-1593] Update K8s Ingress Controller with gRPC guide

app/kubernetes-ingress-controller/1.3.x/concepts/deployment.md
@reviewer
Fix typos: `databse` -> `database`
=> docs(deployment): fix typo in database section

app/enterprise/2.4.x/property-reference.md
=> fix: add tls 1.3 to pg supported versions

app/gateway-oss/2.5.x/performance-testing-framework.md
=> docs(perf-test) add docs for the performance testing framework

app/_hub/kong-inc/prometheus/0.9.x.md, app/_hub/kong-inc/prometheus/index.md
=> plugins(prometheus) add new metrics since 0.9.x

app/_assets/javascripts/subscribe.js, app/_assets/stylesheets/footer.less, app/_assets/stylesheets/pages/landing-page.less, app/_includes/footer.html, gulpfile.js, package.json, pdf-generation/create-pdf.js
* Refactor footer subscribe form, remove iFrame
* Style form to dube same form on konghq.com
* Write ajax request to handle input, success message, and error message
* rm iFrame
* match styling from konghq.com
Tested locally and verified that the email address submissions were being received by Pardot (via @adamjkuhn). 
* Input and submit a sample email to test
=> [DOCU-1580] Refactor footer subscribe form

app/_hub/kong-inc/zipkin/1.3.x.md
=> docs(zipkin-oss) describe spans, tags and annotations for zipkin 1.3 & 1.4

app/gateway-oss/2.5.x/hybrid-mode.md
https://github.com/Kong/kong/pull/7429
@reviewer
=> docs(hybrid) add status API docs for hybrid data plane

app/contributing/style-guide.md
Add to Style Guide:
* Quick fix in Content best practices table
* Add Links section
* Add content to Images section
Add info that will make our site more accessible. 
Tested locally. 
https://deploy-preview-3026--kongdocs.netlify.app/contributing/style-guide/
=> [DOCU-1604] add links section

app/_assets/javascripts/app.js, app/_assets/javascripts/editable-code-snippet.js, app/_assets/javascripts/navbar.js, app/_includes/nav-v2.html, gulpfile.js, package.json
Created the following new js files:
* editable-code-snippet
* navbar
Make the project more manageable. 
Tested locally. Note that due to caching, to see the blue banner, you need to go to incognito and clear it.
=> Refactor app.js

app/_includes/footer.html
Add `required` attribute to footer subscribe form. 
Prevent form submit when the input field is empty. 
Tested locally. Try submitting the empty form.
=> [DOCU-1608] add req attr to footer form

app/_assets/javascripts/app.js, app/_assets/javascripts/copy-code-snippet-support.js, app/_assets/javascripts/editable-code-snippet.js, app/_assets/javascripts/promo-banner.js, gulpfile.js
* rm unused app.js code
* create copy-code-snippet-support.js
* create promo-banner.js
Easier code manageability. 
=> [DOCU-1613] refactor js

app/_data/kong_versions.yml, app/mesh/changelog.md
@Bradamant3 
* Update `kong_versions.yml` to new version. 
* Update Mesh CHANGELOG.md
Mesh minor release. 
N/A
=> Minor Version Release: Mesh 1.3.2

app/_assets/javascripts/navbar.js, app/_assets/stylesheets/header-v2.less, app/_includes/nav-v2.html
* Docs submenu now opens upon "enter"
* Tab through opened menu
* Close menu upon tabbing to Support menu item
Improve accessibility for users using keyboards w/o mouse. 
Tab through to the main navigation.
=> [DOCU-1620] enable tabbing through Docs menu item

app/_assets/stylesheets/cookie-policy.less, app/_includes/cookie-policy.html
All changes to cookie modal. Test on incognito due to caching. 
* Add focus on tabbing to "I agree" button
* Add hover styling change to "I agree" button
* Update text
Increase accessibility and clear up confusing interface. 
Use an incognito window and hover over the modal button. Also, tab through and check that the modal button is focusing.
=> [DOCU-1627] add focus styling to agree button

app/_assets/stylesheets/header-v2.less
Add underlining on hover to main nav items. 
Increase accessibility
Hover over the main nav items and check that they are underlined
=> [DOCU-1626] add underlining to main nav items

app/_assets/javascripts/app.js
Add smooth scroll code back. 
Content was linking without smooth scrolling. 
Click on right-side menu items and see that it's scrolling smoothly.
=> [DOCU-1623] add smooth scrolling from side menu back

app/mesh/1.3.x/features/opa.md
@reviewer
There's a few new configuration options in the OPA plugin. This documents them.
See feature: https://github.com/Kong/kong-mesh/pull/171/files
=> Document new options in kong-mesh OPA plugin

app/_assets/stylesheets/header-v2.less
Increase z-index on navbar. 
Created menu overlap. 
Go to /hub/kong-inc/application-registration/, open the right-side bar menu and scroll up.
=> fix z-index

app/_data/kong_versions.yml, app/mesh/changelog.md
@Bradamant3 
Mesh 1.3.3 release
=> Release: Mesh 1.3.3 

app/enterprise/2.1.x/deployment/hybrid-mode-setup.md, app/enterprise/2.2.x/deployment/hybrid-mode-setup.md, app/enterprise/2.3.x/deployment/hybrid-mode-setup.md, app/enterprise/2.4.x/deployment/hybrid-mode-setup.md, app/gateway-oss/2.1.x/hybrid-mode.md, app/gateway-oss/2.2.x/hybrid-mode.md, app/gateway-oss/2.3.x/hybrid-mode.md, app/gateway-oss/2.4.x/hybrid-mode.md, app/gateway-oss/2.5.x/hybrid-mode.md
=> fix(hybrid) correct descrption for PKI mode to validate from configured

app/enterprise/changelog.md
@HCloward 
This PR adds the missing ACME plugin changes for 0.2.15 that was added in 2.5.0.0 GA
**Note**: This also trims spaces that were in the document.
=> fix(changelog) add ACME plugin changes for 0.2.15

README.md, app/contributing/index.md
Add plugin contributor message. 
Increase community transparency. 
Local
=> [DOCU-1652] add plugin contribution message

app/mesh/1.3.x/installation/openshift.md
Fixing a link.
Broken formatting.
TBA
=> Mesh: Fix link that isn't displaying as a link

app/_redirects
Adjusting so that they redirect to the correct doc set.
https://deploy-preview-3102--kongdocs.netlify.app/kubernetes-ingress-controller-beta
=> KIC beta: Adjust redirects

app/_assets/stylesheets/footer.less, app/_includes/footer.html
The subscribe button was supposed to be in the footer, but instead was floating up near or under the top main nav. I fixed this. 
It was broken. 
https://deploy-preview-3104--kongdocs.netlify.app
Check that the subscribe button appears in the footer next to the email input form.
=> Fix subscribe button in footer

app/konnect/reference/konnect-api.md
Adding "Run in Insomnia" button, generated with https://insomnia.rest/create-run-button. 
To make it easier to use the Konnect API, and to cross-advertise Insomnia.
https://deploy-preview-3116--kongdocs.netlify.app/konnect/reference/konnect-api/
=> [DOCU-536] Add Run in Insomnia button for Konnect

app/enterprise/changelog.md
=> Updates release date for hotfixes

app/_hub/kong-inc/kafka-upstream/0.1.0.md
I updated some of the wording and made some punctuation and grammar edits. I attempted to push my edits up and it is a protected branch. Please review and merge if you approve. Thanks!
=> [DOCU-1734]minor wording updates

app/_hub/kong-inc/kafka-upstream/index.md
This commit includes updates to the index.md file. I can't push these updates up to the branch bc it is a protected branch.
=> [DOCU-1734]Minor wording, grammar, and formatting updates

app/kubernetes-ingress-controller/2.0.x/references/version-compatibility.md
@reviewer
Update Kong Enterprise compatibility
Tested between kic-2.0.0.beta.2 and kong 2.5
=> add kong enterprise 2.5.x support

app/mesh/1.4.x/installation/helm.md
@Bradamant3 
Copy of https://github.com/Kong/docs.konghq.com/pull/3131, with minor adjustments to grammar for readability.
The original PR was created before 1.4 was released, and so the changes weren't picked up in the latest version.
TBA
=> chore: Copy changes to Mesh 1.4

app/enterprise/2.5.x/developer-portal/index.md
Missed a page! 
Growth team changing Developer Portal to Dev Portal. 
Local.
=> [DOCU-1801] add Dev Portal entry page missed swaps

app/_assets/javascripts/app.js, app/_assets/javascripts/promo-banner.js, app/_includes/nav-v2.html
Update preheader promotional banner to highlight Kong Summit
Ask from marketing direct via Slack.
=> update promotional banner

app/enterprise/1.3-x/admin-api/rbac/reference.md, app/enterprise/1.5.x/admin-api/rbac/reference.md, app/enterprise/2.1.x/admin-api/rbac/reference.md, app/enterprise/2.2.x/admin-api/rbac/reference.md, app/enterprise/2.3.x/admin-api/rbac/reference.md, app/enterprise/2.4.x/admin-api/rbac/reference.md, app/enterprise/2.5.x/admin-api/rbac/reference.md
=> fix(admin-api) fix typo of worspace to workspace

app/enterprise/2.5.x/proxy.md
Removed all of the "Back to Top" links from the document
Issue #3156 
@reviewer
=> Removed "Back to Top" Links

app/enterprise/2.5.x/proxy.md
Fixed all of the grammatical errors and typos and cleaned the content.
Issue #3156 is resolved now
@reviewer
=> Copy Edited the entire doc

app/_assets/javascripts/app.js, app/_assets/javascripts/promo-banner.js, app/_includes/nav-v2.html
Updating promo banner to point to Summit Hackathon landing page.
Also updating the JS for the banner so that it's treated as a new banner by browsers.
Request from product web team.
https://deploy-preview-3217--kongdocs.netlify.app
=> [GROW-347] Update promo banner for hackathon

app/kubernetes-ingress-controller/1.3.x/guides/using-kong-with-knative.md
knative 0.24.0 confirmed working with KIC v1.3 in 1.19 EKS based dev cluster
@reviewer
=> updates knative version to latest released

app/kubernetes-ingress-controller/2.0.x/concepts/deployment.md, app/kubernetes-ingress-controller/2.0.x/concepts/design.md, app/kubernetes-ingress-controller/2.0.x/concepts/ha-and-scaling.md, app/kubernetes-ingress-controller/2.0.x/concepts/ingress-classes.md, app/kubernetes-ingress-controller/2.0.x/concepts/ingress-versions.md, app/kubernetes-ingress-controller/2.0.x/concepts/k4k8s-with-kong-enterprise.md
I did a re-read of the "concepts" pages just to check for typos, inaccuracies, e.t.c. This patch includes some fixes.
Resolves https://github.com/Kong/kubernetes-ingress-controller/issues/1789
=> docs: cleaning up KIC 2.0 docs "concepts" pages

app/enterprise/2.5.x/plugin-development/admin-api.md
=> docs(2.5.x gateway) expand endpoints.lua docs

app/_data/kong_versions.yml
pr/please review,pr/do not merge
=> Release: 2.5.1

app/getting-started-guide/2.5.x/prepare.md
=> typo lyfe in prepare.md

app/_hub/kong-inc/rate-limiting/index.md
This MR is for [https://github.com/Kong/docs.konghq.com/issues/3206](https://github.com/Kong/docs.konghq.com/issues/3206).  I made the following changes:
-  Changed HTML code to Markdown.
-  Init-capped Redis wherever it's used as a product name.
-  Made the language simpler.
Two reasons:
-  The belief that Docs Are Important.
-  The Kong Summit 2021 special edition Tshirt
I reviewed the GitHub preview pane.
=> Fix issue 3206: Copyedit Rate Limiting plugin documentation

app/404.html, app/_assets/stylesheets/pages/404.less
This PR modifies the existing Error 404 Page and tries to bring in some animation that enhances the user experience.
Resolves this issue: https://github.com/Kong/docs.konghq.com/issues/3154
This PR is complete. The preview build looks good.
https://deploy-preview-3248--kongdocs.netlify.app/404
=> Modify the Error 404 Page

app/_hub/kong-inc/correlation-id/index.md
This PR aims to align the documentation with the style guide and unnecessary complexities and grammatical errors have been fixed.
To resolve the issue - https://github.com/Kong/docs.konghq.com/issues/3202
The Preview page looks good.
=> Copyedit Correlation ID plugin documentation #3202

app/deck/1.8.x/guides/best-practices.md
This PR refactors the decK best practices documentation. 
Resolves the issue - https://github.com/Kong/docs.konghq.com/issues/3247
The page preview looks good.
=> Copyedit and organize decK best practices documentation #3247

app/_data/extensions/kong-inc/aws-lambda/versions.yml, app/_hub/kong-inc/aws-lambda/3.5.x.md, app/_hub/kong-inc/aws-lambda/index.md
Add docs for AWS region detection with environment variables. This feature comes from a community request. See https://github.com/Kong/kong/pull/7765 for context.
Related GH issue: https://github.com/Kong/kong/issues/7697
=> docs(hub/aws-lambda) region detection by environment variable

app/_hub/kong-inc/aws-lambda/3.5.x.md, app/_hub/kong-inc/aws-lambda/index.md
Relates to: https://github.com/Kong/kong/pull/7765
=> docs(aws-lambda) update aws lambda docs to match the latest plugin version

app/_hub/kong-inc/prometheus/index.md
Add docs for https://github.com/Kong/kong/pull/7802/files.
=> docs(hub/prometheus) add prometheus health subsystem label

app/_hub/kong-inc/grpc-gateway/0.1.x.md, app/_hub/kong-inc/grpc-gateway/index.md
structured URL args and timestamp transcoding
=> grpc gateway decoding

app/konnect/servicehub/manage-services.md
* Keeps documentation on how to delete a Service version. 
* Removes how to archive a Service version. 
Addresses request for revision: https://github.com/Kong/docs.konghq.com/pull/3259#issuecomment-930452897
https://deploy-preview-3284--kongdocs.netlify.app/konnect/servicehub/manage-services/#delete-a-service-version
=> Revise TDX-1370 Konnect ServiceHub: rm Archive version

app/_hub/kong-inc/application-registration/index.md
Addresses [DOCU-1849](https://konghq.atlassian.net/browse/DOCU-1849). 
User was looking for this information and couldn't find it.
=> [DOCU-1849] Application Registration Plugin: add link to enable Key Auth

Gemfile.lock
A security update indicated that the `rack` gem should be updated. 
This will require contributors to `make clean` and `make install` to update the gem. 
Security. 
Click around and see if everything functions as expected. Tested locally.
https://deploy-preview-3301--kongdocs.netlify.app
=> Site maintenance (security risk): update rack dependency

app/mesh/1.4.x/features/vault.md
Add docs about Vault Common Name support. This will land in Kong Mesh 1.4.1
=> Vault Common Name support

app/enterprise/changelog.md
Updates 2.6 GA changelog
Will include sample build link when available
=> [DOCU-1731]Updates ee-2.6-changelog

app/enterprise/2.6.x/developer-portal/configuration/workspaces.md
* Add a line about having to enable each new Dev Portal within a new Workspace. 
* Minor content edits
[TDX-650](https://konghq.atlassian.net/browse/TDX-650)
=> [TDX-650] reduce ambiguity about Dev Portal enablement

app/mesh/1.5.x/features/rbac.md
Role Based Access Control documentation for Kong Mesh
Describe new feature in Kong Mesh
Waiting for netlify preview...
=> docs: RBAC for Kong Mesh

app/mesh/1.4.x/features/vault.md
Add blurb about automatic token renewal, this will land in the next 1.4.x Kong Mesh release.
=> docs(mesh) add info about Vault token renewal

app/gateway/2.6.x/install-and-run/helm.md
=> Fix missing namespace flag hyphen

app/gateway/changelog.md
Changelog for patch releases.
Went through tickets for a bit more info on some of the entries, and to phrase them in a user-centric way. Please check that I didn't miss the point of some of these fixes.
Patch releases.
https://deploy-preview-3383--kongdocs.netlify.app/gateway/changelog/
=> [DOCU-2031] Changelog for 2.5.1.2 and 2.6.0.1 patch releases

app/_assets/javascripts/navbar.js, app/_assets/stylesheets/header-v2.less, app/_includes/nav-v2.html
Adding plugin hub to navbar upon request, and updating very outdated "Get Started" button.
https://konghq.atlassian.net/browse/DOCU-1827
https://deploy-preview-3379--kongdocs.netlify.app/
=> [DOCU-1827] Navbar adjustments

app/_redirects
Fixing dev portal redirects.
Noticed some redirects not leading to the right places.
TBA, test when Netlify preview is ready.
=> Fix dev portal directs

app/gateway/2.6.x/install-and-run/docker.md
Add text inputs to address confusing around what the user names, versus what's a hard value. 
Addresses [Issues 3384](https://github.com/Kong/docs.konghq.com/issues/3384)
Adds clarity to users
Link TBA
=> [DOCU-2049] Gateway Docker Install: add text inputs

app/mesh/changelog.md
[Add upgrade instructions for 1.5.0](https://deploy-preview-3407--kongdocs.netlify.app/mesh/changelog/)
https://github.com/kumahq/kuma/blob/master/UPGRADE.md
=> docs(mesh) Add upgrade instructions for 1.5.0

app/_assets/stylesheets/header-v2.less
Increasing padding on nav dropdown.
Awkward spacing, see https://konghq.atlassian.net/browse/DOCU-2058.
Hover over the Docs dropdown at the top of the page: https://docs.konghq.com/
TBA
=> [DOCU-2058] Increase padding on top of submenu

app/gateway/2.6.x/install-and-run/docker.md
Includes changes from this PR: https://github.com/Kong/docs.konghq.com/pull/3404 and some formatting fixes I made.
Sorry, made a mistake on the merge because of the new forking workflow. 
https://deploy-preview-3419--kongdocs.netlify.app/gateway/2.6.x/install-and-run/docker/#install-gateway-in-db-less-mode
=> Docker database-less instructions

app/kubernetes-ingress-controller/1.0.x/guides/setting-up-custom-plugins.md, app/kubernetes-ingress-controller/1.1.x/guides/setting-up-custom-plugins.md, app/kubernetes-ingress-controller/1.2.x/guides/setting-up-custom-plugins.md, app/kubernetes-ingress-controller/1.3.x/guides/setting-up-custom-plugins.md, app/kubernetes-ingress-controller/2.0.x/guides/setting-up-custom-plugins.md
k8s
Fix https://github.com/Kong/kong/issues/8007
=> docs(kic) add notes and link of setting up plugins in other language in

app/mesh/1.5.x/features/rbac.md
Fixes YAML resource identation and consistency
=> docs(mesh/rbac) fix YAML indentation

app/_data/extensions/kong-inc/datadog/versions.yml, app/_hub/kong-inc/datadog/3.1.x.md, app/_hub/kong-inc/datadog/index.md
Documents these two changes on the Datadog plugin:
* https://github.com/Kong/kong/pull/6231
* https://github.com/Kong/kong/pull/6230
=> oss-gateway(2.7.0) document new Datadog plugin

app/_data/extensions/kong-inc/ip-restriction/versions.yml, app/_hub/kong-inc/ip-restriction/2.0.x.md, app/_hub/kong-inc/ip-restriction/index.md
Document changes in https://github.com/Kong/kong/pull/7728
=> docs(hub) document new ip-restriction plugin

app/konnect/org-management/okta-idp.md, app/konnect/updates.md
* Removing beta banner from Okta doc
* Adding a release note to Konnect Updates
Planned GA of the Okta feature.
Changelog: https://deploy-preview-3431--kongdocs.netlify.app/konnect/updates/
Removed beta banner: https://deploy-preview-3431--kongdocs.netlify.app/konnect/org-management/okta-idp
=> [DOCU-2055] Prepare Konnect Okta doc for GA

app/_hub/kong-inc/openid-connect/index.md
Clarify what value should be set in config.issuer.
I know this might seem obvious to some, but having this note would have saved me a week of running in circles.
N/A
=> Clarify requirements for config.issuer value

app/konnect/servicehub/manage-services.md
* Add Archive a Service version to ServiceHub documentation
New feature enables archiving a Service version. 
https://deploy-preview-3367--kongdocs.netlify.app/konnect/servicehub/manage-services/#archive-a-service-version
=> [TDX-1628] Dev Portal: Archive a Service Version

app/konnect/servicehub/manage-services.md
This reverts commit 32a389e266b9205ae7e4c2d6aa9d95813d56f7fa.
=> Revert "[TDX-1628] Dev Portal: Archive a Service Version (#3367)"

app/_redirects
Closes [DOCU-2086](https://konghq.atlassian.net/browse/DOCU-2086)
Missing Dev Portal redirect
=> [DOCU-2086] Add Dev Portal redirect

app/gateway/2.6.x/plugin-development/custom-logic.md, app/gateway/2.7.x/plugin-development/custom-logic.md
Fixed a typo in latest docs (2.6.x and 2.7.x)
=> Fix(plugin development docs)

app/_hub/kong-inc/acl/index.md
Multiple part of the document are wrong probably from copy/past of another documentation
=> ACL Doc - Fix error on doc from probably copy/past

app/kubernetes-ingress-controller/2.1.x/guides/getting-started.md
Separated commands from output to allow copying commands without output and giving a better experience following the guide
Cant copy, paste and run command(s) without errors when you copy command + output
Copy command and run in bash, if there are no errors from bash containing "No such file or directory" or "command not found" - it works.
=> Copying commands without output

broken-link-checker/run.js
Followup on #3532 as it will currently try and link check deleted pages.
The `process.argv[2]` is to enable local testing (docs coming with the full site link checker PR)
=> Filter broken links to added/modified pages only

broken-link-checker/run.js
Allows us to exclude pages from link checking using a regular expression.
The /changelog/ page was getting rate limited by GitHub due to checking so many links. This PR excludes that page specifically, and we will run a separate check for that page with a lower rate limit
Tested locally against #3539 (where the issue first showed up)
=> Allow pages to be excluded from link checking

app/_data/docs_nav_gateway_2.7.x.yml, app/gateway/2.7.x/vitals/vitals-estimates.md
Add Vitals Estimates page authored by @hhoover and edited by @falondarville.
Editing: sentence case for titles, group content into list, capitalize Gateway-specific terms, add codeblock types, add page to TOC
https://deploy-preview-3544--kongdocs.netlify.app/gateway/2.7.x/vitals/vitals-estimates/
**Note that this content came from the original PR: https://github.com/Kong/docs.konghq.com/pull/3438. Attribution has been given to the original author @hhoover
=> Add Vitals Estimates page

app/konnect/updates.md
* Add Custom Domain entry to Konnect Cloud changelog
https://deploy-preview-3555--kongdocs.netlify.app/konnect/updates/#main
=> Add Custom Domain entry to Konnect Cloud changelog

app/kubernetes-ingress-controller/2.1.x/references/custom-resources.md
For reference there is a complete spec for KongIngress but it's not that clear at that point of reading where to find more information about the described attributes (slots, hash_on, hash_fallback, etc`...) even though links are provided few lines before that. 
Explicitly providing source of information just as full spec is shown should reduce confusion.
additional prove that its not clear:
https://discuss.konghq.com/t/what-is-slots-in-kong-upstreams/665
=> explicit guide to attributes descriptions

app/konnect/updates.md
Add that headers are modifiable to the Konnect changelog.
Request from PM.
Local, text change only.
=> [DOCU-2151] add headers are modifiable

app/_assets/javascripts/app.js, app/_assets/javascripts/promo-banner.js, app/_includes/nav-v2.html
Updating the promo banner based on web team's request.
* Cleaning up duplicate promo banner function - there was a copy in `promo-banner.js` and one in `app.js`, with the exact same code. Removed the `app.js` copy and moved the  accordion active function to where it actually belongs (it was nested in the promo banner previously)
Update requested in https://konghq.atlassian.net/browse/DOCU-2149.
TBA
=> [DOCU-2149] chore: Promo banner for webinar

app/_data/docs_nav_konnect.yml, app/konnect/org-management/deactivation.md
Adding a doc that explains how an org might get deactivated and what the results of deactivation are.
Note that all of this doc is _external_. Therefore, all information in this doc applies to any average person using Konnect and not an internal developer. 
Need to be transparent about our account/org management. Also, ticket has been around for a while.
Doc preview: https://deploy-preview-3561--kongdocs.netlify.app/konnect/org-management/deactivation/
=> [DOCU-1859] Deactivated orgs in Konnect

app/_assets/javascripts/app.js
Switch all navtabs when a tab is selected
Makes it easier for people to choose a configuration option and use it through an entire guide
Try out /hub/kong-inc/basic-auth/ on the review app
=> Toggle all nav tabs with the same title

broken-link-checker/pr.js
Skip the "Edit this page" links when checking PRs from forks
The build process does not have access to the upstream repo name, so we cannot dynamically generate the correct URL for PRs from forks. This leads to every fork PR failing the build.
This PR will exclude the edit link when a PR comes from a fork
I've tested on this PR
=> Don't check 'Edit this page' links on forks

app/gateway/2.6.x/install-and-run/docker.md, app/gateway/2.7.x/install-and-run/docker.md
Follow up on #3608 .
Didn't get the commit in before PR was merged.
Better linking.
TBA
=> Target deck tabs for db-less getting started guide links

app/_data/kong_versions.yml, app/gateway/changelog.md
Patch release changelog entry. No other doc impact.
Gateway patch release.
https://deploy-preview-3623--kongdocs.netlify.app/gateway/changelog/
=> Release: Gateway 2.7.1.1

app/gateway/2.7.x/developer-portal/administration/application-registration/azure-oidc-config.md
Update Dev Portal Azure requests to call Azure instead of Kong. 
Addresses [DOCU-2162](https://konghq.atlassian.net/browse/DOCU-2162)
https://deploy-preview-3650--kongdocs.netlify.app/gateway/2.7.x/developer-portal/administration/application-registration/azure-oidc-config/#test-client-credentials-flow
=> [DOCU-2162] Update Dev Portal Azure requests

app/gateway/2.7.x/developer-portal/configuration/authentication/oidc.md
Add to note about registration flow for Dev Portal using OIDC.
Addresses [DOCU-2174](https://konghq.atlassian.net/browse/DOCU-2174)
https://deploy-preview-3647--kongdocs.netlify.app/gateway/2.7.x/developer-portal/configuration/authentication/oidc/
=> [DOCU-2174] Add note about reg flow to OIDC for Dev Portal

app/gateway/2.7.x/reference/configuration.md
Add EE badge to `cluster_mtls` -> `pki_check_cn`
Verified with Gateway engineer. 
Addresses [DOCU-2186](https://konghq.atlassian.net/browse/DOCU-2186)
Link TBA.
=> [DOCU-2186] Add EE badge to cluster_mtls pki_check_cn

app/_assets/stylesheets/header.less, app/_includes/nav-v2.html, gulpfile.js
Disabling the blue top-of-page promo banner.
The webinar has concluded and the banner is no longer accurate.
https://deploy-preview-3665--kongdocs.netlify.app/
=> Chore: Disable promo banner

app/deck/1.11.x/guides/kong-enterprise.md
- clarify how to use decK `sync` with multiple workspaces
Current doc is a bit unclear on this matter, which led to users opening issues.
Testing and review have been done [here](https://github.com/Kong/deck/pull/576)
=> [DOCU-2179] Add note on how to deploy multiple workspaces

app/_data/extensions/kong-inc/prometheus/versions.yml, app/_hub/kong-inc/prometheus/1.4.x.md, app/_hub/kong-inc/prometheus/index.md
Added documentation for Prometheus plugin 1.5.0.
This is my first rodeo, so feel free to make any necessary changes (or just suggest them in your review) if something doesn't look right.
https://konghq.atlassian.net/browse/DOCU-2188
I don't have write access to this repo, so I'm not sure if a netflix test link will get generated or not. Maybe somebody can add perms for me?
=> [DOCU-2188] Add docs for Prometheus 1.5.0

app/mesh/1.6.x/features/rbac.md
That is for the next incoming release (1.6.x)
=> add zone token access to Kong Mesh RBAC

app/_data/docs_nav_mesh_1.6.x.yml, app/mesh/1.6.x/features/ubi-images.md
Docs about upcoming UBI images distributions. It will be released with the next release of Kong Mesh.
=> feat(kmesh): UBI images

app/_data/docs_nav_mesh_1.6.x.yml, app/mesh/1.6.x/plan-and-deploy/license.md
Add information about the Kong Mesh license. Edited by @subnetmarco 
I could use some help where to place it. It's not really a feature. Install section? New section?
There was no such information before
Waiting for netfliy preview...
=> Kong Mesh license

app/mesh/changelog.md
Add missing changelog for KM 1.6
=> add changelog for KongMesh 1.6

app/gateway/changelog.md
Remove Dependencies changes list item regarding a pgmoon version bump that did not make the release.
=> fix(changelog) - remove dependecies item about pgmoon version bump

app/deck/1.11.x/guides/defaults.md
Add a plugin example + output to the test section of the decK defaults guide.
Also fixed some indents to get rid of an extra space that was appearing in codeblocks that are nested in lists.
Need to make it clear that plugin defaults are supported. Users are most concerned with plugin defaults, as there are many different options.
Tested the example, everything works as documented.
https://deploy-preview-3742--kongdocs.netlify.app/deck/1.11.x/guides/defaults/
=> [DOCU-2209] Plugin example for decK defaults guide

app/_hub/kong-inc/ip-restriction/index.md
Add multiple callouts about naming changes, to: description, inside table, and in the plugin changelog. 
Addresses https://konghq.atlassian.net/browse/DOCU-416
https://deploy-preview-3753--kongdocs.netlify.app/hub/kong-inc/ip-restriction/
=> [DOCU-416] Add callouts about naming changes

app/mesh/1.6.x/installation/helm.md
=> Improve helm docs for mesh

app/gateway/2.8.x/get-started/comprehensive/prepare.md
Fixing a typo.
Issue  #3774.
N/A
=> Fix typo in getting started guide ( #3774)

app/mesh/1.3.x/features/kds-auth.md, app/mesh/1.4.x/features/kds-auth.md, app/mesh/1.5.x/features/kds-auth.md
Backport `remote` => `zone` changes from @svenwal in #3799
=> Backport #3779

app/konnect/org-management/okta-idp.md
Replaces usage of "Okta domain" with the full "Issuer URI".
Application functionality changed (KHCP-3219).
Create an Okta configuration in Konnect following the instructions on this page.
Note: You may receive an error on the "Test Configuration" button, but saving the config will work.
I have tested in production before raising this PR.
=> fix: update instructions for Konnect Okta config

app/_data/docs_nav_mesh_1.5.x.yml, app/_data/docs_nav_mesh_1.6.x.yml, app/konnect-platform/support-policy.md
Missing support policy for recent versions of KM
=> fix(kong-mesh): fix support policy

app/enterprise/2.4.x/admin-api/index.md, app/enterprise/2.5.x/admin-api/index.md, app/gateway-oss/1.1.x/db-less-admin-api.md, app/gateway-oss/1.2.x/db-less-admin-api.md, app/gateway-oss/1.3.x/db-less-admin-api.md, app/gateway-oss/1.4.x/db-less-admin-api.md, app/gateway-oss/1.5.x/db-less-admin-api.md, app/gateway-oss/2.0.x/db-less-admin-api.md, app/gateway-oss/2.1.x/db-less-admin-api.md, app/gateway-oss/2.2.x/db-less-admin-api.md, app/gateway-oss/2.3.x/db-less-admin-api.md, app/gateway-oss/2.4.x/admin-api.md, app/gateway-oss/2.5.x/admin-api.md, app/gateway/2.6.x/admin-api/index.md, app/gateway/2.7.x/admin-api/index.md, app/gateway/2.8.x/admin-api/index.md
Small formatting improvement of API endpoint responses
Because the new format is more consistent and easier to read 😬 
No functional changes were made.
=> Improve formatting of API endpoint responses

app/_data/extensions/kong-inc/openid-connect/versions.yml, app/_data/kong_versions.yml, app/_hub/kong-inc/openid-connect/2.2.x.md, app/gateway/changelog.md
Update the changelog for Kong Gateway 2.6.x, 2.7.x and 2.8.x releases
https://deploy-preview-3821--kongdocs.netlify.app/gateway/changelog/#2810
https://deploy-preview-3821--kongdocs.netlify.app/gateway/changelog/#2720
https://deploy-preview-3821--kongdocs.netlify.app/gateway/changelog/#2610
=> Gateway patch release april

app/mesh/1.7.x/plan-and-deploy/license.md
Clarify what happens when license expires. Make this section a subsection of the docs to make it easy to find
=> chore(mesh): clarify what happens when a license expires

app/mesh/changelog.md
Add changelog as needed.
Preparing for the release
=> chore(mesh): add changelog for 1.6.1 and 1.7.0

app/mesh/1.7.x/index.md
Replace Mesh graphic with features table
The existing graphic does not list all current capabilities
https://deploy-preview-3796--kongdocs.netlify.app/mesh/
=> Replace Mesh graphic with features table

app/gateway-oss/2.5.x/pdk/kong.client.md
=> chore(client): update example for kong.client.get_forwared_ip

app/mesh/1.5.x/installation/windows.md, app/mesh/1.6.x/installation/windows.md, app/mesh/1.7.x/installation/windows.md, app/mesh/installer.ps1
Fixes the Kong Mesh Windows installation.
Signed-off-by: John Harris <john@johnharris.io>
Fixes:
- DOCU-2268
- DOCU-2269.
cc/ @Troy-Starks
=> Fix windows mesh install instructions

.github/workflows/run-smoke-tests.yml, app/_plugins/blocks/plugin_version_block.rb, app/_plugins/generators/plugin_single_source_generator.rb
Fix issues raised by a PR not being up to date with `main` before merge
Automated tests should pass
=> Fix Smoke Tests + run on `main`

app/kubernetes-ingress-controller/2.3.x/deployment/k4k8s-enterprise.md
Fixes a small typo in the installation docs, missing `\` in the helm command
=> Correct typo in helm command

app/contributing/style-guide.md, app/contributing/word-choice.md
Update Style Guide
Adding `database` to the list of words that aren't capitalized.
```bash
make install
make run
```
=> Update Style Guide

app/gateway/2.6.x/plan-and-deploy/hybrid-mode/hybrid-mode-setup.md, app/gateway/2.7.x/plan-and-deploy/hybrid-mode/hybrid-mode-setup.md, app/gateway/2.8.x/plan-and-deploy/hybrid-mode/hybrid-mode-setup.md
Fix the TLS Web Client/Server messaging for hybrid mode
Fixing a misleading example
/gateway/2.8.x/plan-and-deploy/hybrid-mode/hybrid-mode-setup/#generate-a-certificatekey-pair
=> Certificate PKI Mode TLSv3 extension

app/gateway/2.8.x/configure/auth/kong-manager/sessions.md
Add missing commas to JSON admin_gui_session_conf configuration object and removal of unnecessary </strong> html tag
=> Kong Manager Session: Add missing commas to JSON configuration object

app/gateway/2.8.x/reference/external-plugins.md
Fixed broken link. 
I've created this [DOCU-2321](https://konghq.atlassian.net/browse/DOCU-2321) to address the content and structure of the original guide. 
[Jira Ticket](https://konghq.atlassian.net/browse/DOCU-2319)
=> [fix] Plugins in other languages doc - Broken link

README.md
=> Improve the overall readability by altering punctuations, articles and typos.

app/gateway/2.8.x/get-started/quickstart/configuring-a-service.md
Improves the Configuring a Service Quickstart page
- Adds links to key terms on introduction
- Clarifies the behavior of the Route
- Tidies some areas (subjectively)
During my onboarding I felt some friction with this page, so this PR is an incremental improvement on some of the content to help future readers.
- Tested by building the site locally and previewing the content changes
review:general
=> Improves the Configuring a Service Quickstart page

app/_hub/kong-inc/kafka-log/_index.md, app/_hub/kong-inc/kafka-upstream/_index.md
Document new SASL authentication mechanism support.
https://konghq.atlassian.net/browse/DOCU-2354
https://github.com/Kong/kong-ee/pull/3201
https://deploy-preview-3973--kongdocs.netlify.app/hub/kong-inc/kafka-upstream/
https://deploy-preview-3973--kongdocs.netlify.app/hub/kong-inc/kafka-log/
=> [DOCU-2354] Kafka scram-sha-512 support

src/gateway/install-and-run/amazon-linux.md
Docs portion of the following changes:
- https://github.com/Kong/kong-distributions/pull/787
- https://github.com/Kong/kong-ee/pull/3247
- https://github.com/Kong/kong/pull/8846
https://konghq.atlassian.net/browse/ENGEN-453
=> [ENGEN-453] chore(amzn) add amazon linux 1 deprecate notice

app/gateway/changelog.md
There's a typo in the changelog that went out today.
=> Fix changelog typo

app/_data/docs_nav_gateway_3.0.x.yml, src/gateway/configure/dynamic-plugin-ordering.md, src/gateway/configure/dynamic-plugin-ordering/get-started.md, src/gateway/configure/dynamic-plugin-ordering/index.md, src/gateway/plugin-development/custom-logic.md
Releated PR: https://github.com/Kong/kong-ee/pull/3164
Internal: https://konghq.atlassian.net/browse/FT-2387
You should be able to test this feature by following the docs. If not, the docs are crap.
https://deploy-preview-3905--kongdocs.netlify.app/
=> docs(gateway): dynamic plugin ordering

app/_hub/kong-inc/jwt/0.1-x.md, app/_hub/kong-inc/jwt/2.1-x.md, app/_hub/kong-inc/jwt/_index.md
* Fix applicable algorithms on secret parameter of jwt plugin
* Update available algorithms for jwt plugin 
* Fix response code when JWT has invalid signature 
Make doc up-to-date.
Relevant commits in kong are included in commit message for reference
=> Fix jwt plugin doc

.github/styles/kong/dictionary.txt, app/_hub/moesif/kong-plugin-moesif/_index.md
Summary
Updates to Kong Moesif plugin docs
Add: Compatible versions
Update: How to install steps
Add: Missing Config options
Reason
Was out of date
Testing
Markdown tested
review:copyedit
References: https://github.com/Kong/docs.konghq.com/pull/4004
=> Update: Kong Moesif Plugin versions 

app/_data/kong_versions.yml, app/mesh/changelog.md, app/mesh/installer.sh
Prepare `release/mesh-1.8` branch for the real release with changelog updated etc.
n/a
n/a
=> chore: release kong mesh 1.8.0 and 1.7.1

app/mesh/changelog.md
Add release dates, one upgrade instruction and one additional feature for kong mesh 1.8.0
n/a
n/a
=> chore: add release dates + one feature and upgrade

app/_includes/docs-sidebar.html, app/_includes/nav-v2.html
Currently running the docs site locally and clicking Gateway, Deck, Mesh, or KIC, results in a 404. This PR addresses that. 
Click the links from the navigation bar. 
https://deploy-preview-4027--kongdocs.netlify.app/
=> Update sidebar and nav

docs/platform-install.md
Question for reviewers: should I also break the commands into separate steps so people don't run them all in one go (like I did...)? 
Added prereq section, added note about adding Homebrew to your PATH, and changed repo to HTTPS URL instead of SSH.
Made these changes based on issues I experience when configuring the docs to run locally. 
Not sure if this can be tested unless you uninstall homebrew.
=> Update docs platform install instructions

app/konnect/dev-portal/customization/index.md, app/konnect/dev-portal/dev-reg.md
Adding content for SSO/IdP Configuration. Targeted for Helium.
TDX-2081
Definitely want layout / readability opinions on [Customization Page](https://deploy-preview-3994--kongdocs.netlify.app/konnect/dev-portal/customization/#single-sign-on) and [Developer Registration](https://deploy-preview-3994--kongdocs.netlify.app/konnect/dev-portal/dev-reg/#sso)
=> [TDX-2081]: update developer registration and SSO docs 

app/_hub/kong-inc/statsd-advanced/2.2.x.md, app/_hub/kong-inc/statsd-advanced/_index.md, app/_hub/kong-inc/statsd-advanced/versions.yml
Support identifier default for consumer_identifier, service_identifier and workspace_identifier
https://konghq.atlassian.net/browse/FTI-4086
I've already run this project and confirmed my change works.
=> feat(plugin) add consumer_identifier_default, service_identifier_default and workspace_identifier_default

app/_hub/kong-inc/openid-connect/_index.md
Update description of plugin configuration parameter. 
[DOCU-2233](https://konghq.atlassian.net/browse/DOCU-2233)
[OIDC plugin doc
](https://deploy-preview-4075--kongdocs.netlify.app/hub/kong-inc/openid-connect/#parameters)
=> [DOCU-2233] config.token_post_args_client description

app/konnect-platform/support-policy.md
Updates the Kong Mesh support policy and dates.
PTAL @lahabana
=> docs(mesh) update Kong Mesh support policy dates

.github/styles/kong/Terms.yml, .github/styles/kong/dictionary.txt, app/konnect/dev-portal/Troubleshooting/index.md, app/konnect/dev-portal/access-and-approval/auto-approve-devs-apps.md, app/konnect/dev-portal/access-and-approval/manage-app-connections.md, app/konnect/dev-portal/access-and-approval/manage-app-reg-requests.md, app/konnect/dev-portal/access-and-approval/manage-devs.md, app/konnect/dev-portal/access.md, app/konnect/dev-portal/applications/application-overview.md, app/konnect/dev-portal/applications/dev-apps.md, app/konnect/dev-portal/applications/dev-gen-creds.md, app/konnect/dev-portal/applications/dev-reg-app-service.md, app/konnect/dev-portal/applications/enable-app-reg.md, app/konnect/dev-portal/customization/index.md, app/konnect/dev-portal/dev-reg.md, app/konnect/dev-portal/index.md, app/konnect/legacy/dev-portal/applications/enable-app-reg.md
Enforces new style guidelines on Konnect section.
[docu-2315](https://konghq.atlassian.net/browse/DOCU-2315)
Soon
=> [DOCU-2315] Dev Portal section copy edits

app/konnect/dev-portal/customization/index.md
Remove the Allowed TLDs section due to a change in Konnect logic. Improve the Custom URLs section by adding troubleshooting details, restricted domains list, and more useful information for Konnect users.
TDX-1947
https://deploy-preview-4088--kongdocs.netlify.app/konnect/dev-portal/customization
=> feat(portal): Improve Dev Portal Customization page and remove Allowed TLDs section

app/_data/docs_nav_konnect.yml, app/konnect/account-management/billing.md, app/konnect/account-management/change-plan.md, app/konnect/account-management/index.md, app/konnect/org-management/okta-idp.md, app/konnect/org-management/teams-and-roles/index.md, app/konnect/org-management/teams-and-roles/manage.md, app/konnect/org-management/teams-and-roles/roles-reference.md, app/konnect/org-management/teams-and-roles/teams-reference.md, app/konnect/org-management/users.md
* Style clean-up
* Adjust nav to follow nesting style (no links for top-level accordion items)
* Adjust instructions for new nav and UI updates
* Split up user list items into basic tasks
https://konghq.atlassian.net/browse/DOCU-2317
netlify TBA
=> [DOCU-2317] Konnect administer section clean-up and validation

.github/ISSUE_TEMPLATE/improve-existing-docs.yaml
Fixes grammar issue possibly in improve-existing-docs.yaml
Changes wording as per what I think should be right
review:copyedit is needed
=> chore(Issue Templates) Fix improve-existing-docs.yaml grammar issues

app/_includes/footer.html
Update links in footer to new product pages to avoid redirects.
https://konghq.atlassian.net/browse/DOCU-2385
Test the footer on any page in the preview.
=> [DOCU-2385] Product links in footer

app/konnect/getting-started/import.md, src/deck/guides/konnect.md
Clarify app registration plugins with decK.
Added an entry into troubleshooting, because people have run into this multiple times already. 
Also added a step to the import/migration guide to remove unsupported config. Also something that people have run into trouble with.
https://konghq.atlassian.net/browse/DOCU-2157 
https://deploy-preview-4120--kongdocs.netlify.app/deck/latest/guides/konnect/
https://deploy-preview-4120--kongdocs.netlify.app/konnect/getting-started/import/
=> [DOCU-2157] Konnect with decK: app registration and migration

app/konnect-platform/support-policy.md
Adding KIC to the support policy page.
KIC was missing prior from the support policy page.
View changes
=> Update support policy to include KIC

.github/styles/kong/Terms.yml, .github/styles/kong/dictionary.txt, app/_data/kong_versions.yml, app/mesh/changelog.md
Releasing 2 new patch versions
=> chore: release KongMesh 1.8.1 and 1.7.2

src/gateway/reference/configuration.md
Gateway 3.0 version of this [PR](https://github.com/Kong/kong-ee/pull/3464)
=> [chore] Update 3.0 Config.md file

src/mesh/index.md
=> Fix typo in Mesh comparison table

app/gateway/2.8.x/plan-and-deploy/security/secrets-management/backends/gcp-sm.md
fixing typos and fixing httpie command for `config`
=> fix(vaults/gcp) fixing typos and fixing httpie command for `config`

app/konnect/org-management/okta-idp.md
This section is no longer required. 
https://kongstrong.slack.com/archives/CQK8J4VN3/p1658878194544959?thread_ts=1658726590.046879&cid=CQK8J4VN3
=> [fix]remove login_email from okta idp custom claims

.github/styles/kong/dictionary.txt, app/_hub/kong-inc/serverless-functions/_index.md
[FTI-4214](https://konghq.atlassian.net/browse/FTI-4214)
This PR update pre/post-function plugin be applied scopes.
=> Update plugin serverless-functions docs.

app/_hub/kong-inc/aws-lambda/_index.md
=> [chore] Gateway 2.8.1.3 support for Lambda plugin

src/mesh/features/rbac.md
Resolves #4176
Adds consistency with all other mesh features
[/mesh/latest/features/rbac/](https://deploy-preview-4192--kongdocs.netlify.app/mesh/latest/features/rbac/)
=> Show k8s examples before Universal on Mesh RBAC

.github/styles/kong/dictionary.txt, app/_hub/kong-inc/serverless-functions/_index.md
Ports this to 3.0 
https://github.com/Kong/docs.konghq.com/pull/4182
=> [fix] Port changes to serverless functions doc to Gateway 3.0 

app/gateway/2.8.x/admin-api/admins/reference.md, src/gateway/admin-api/admins/reference.md
Ports https://github.com/Kong/docs.konghq.com/pull/4194 into gateway 3.0 branch
=> 3.0 Add status enum docs to Admin endpoint 

src/gateway/reference/nginx-directives.md
[docu-2446](https://konghq.atlassian.net/browse/DOCU-2446)
=> [Docu-2446] Nginx directives reference

app/_data/kong_versions.yml, app/mesh/changelog.md
Release patch version of Kong Mesh. It is still based on Kuma 1.7.1.
=> release Kong Mesh 1.8.2

src/gateway/understanding-kong/key-concepts/services.md
New documentation: Provides an overview of what a service is and how they work in Gateway
[DOCU-2408](https://konghq.atlassian.net/browse/DOCU-2408)
Questions for reviewers:
- Do the sections work or is there anything I can change/add?
=> [DOCU-2408] Understanding Kong: Services

src/gateway/reference/performance-testing-framework.md, src/gateway/understanding-kong/kong-performance-testing.md
- New How-to Doc: Contains the following sections from this [doc](https://docs.konghq.com/gateway/latest/plan-and-deploy/performance-testing-framework/): Installation Drivers Workflow Sample Output section
- Contains the reference portions of this [doc](https://docs.konghq.com/gateway/latest/plan-and-deploy/performance-testing-framework/)
https://konghq.atlassian.net/browse/DOCU-2413
https://konghq.atlassian.net/browse/DOCU-2447
=> [DOCU-2413] and [DOCU-2447] Performance Testing Framework IA rework

app/gateway/changelog.md
This pull request adds a missing bug fix for 2.8.1.3 to the changelog.
=> fix(changelog) add a missing bug fix for 2.8.1.3

src/gateway/kong-production/canary.md, src/gateway/understanding-kong/loadbalancing.md
New tutorial: Uses examples to demonstrate how to set up ring balancers for canary releases. Derived from this [doc](https://docs.konghq.com/gateway/latest/reference/loadbalancing/#canary-releases)
[DOCU-2425] (https://konghq.atlassian.net/browse/DOCU-2425)
[DOCU-2425]: https://konghq.atlassian.net/browse/DOCU-2425?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DOCU-2425] Kong in Production: Canary Deployments

app/gateway/changelog.md
This pull request adds a missing entry for a bug fix in the 2.8.1.1 and 2.8.1.2 releases.
=> fix(changelog) add a missing bug fix to 2.8.1.1/2 changelog

app/gateway/2.8.x/plan-and-deploy/security/secrets-management/getting-started.md, app/gateway/2.8.x/plan-and-deploy/security/secrets-management/index.md
* Removed a note for `vaults=bundled`
* Added a short explanation of why this might not work for someone that isn't on the latest patch
* Minor phrasing and grammar cleanup
Extension of changes made in https://github.com/Kong/docs.konghq.com/pull/4222.
Netlify
=> Vaults GA changes

app/_includes/md/enterprise/event-hooks-intro.md
=> Correct typo

app/_data/docs_nav_gateway_3.0.x.yml, src/gateway/kong-production/monitoring/datadog.md
Created a doc that explains how to collect metrics from Prometheus with Datadog. Turns out the OpenTelemetry plugin doesn't solve this problem right now, so this doc is needed. 
[MA-365](https://konghq.atlassian.net/browse/MA-365)
=> [MA-365] Collect Prometheus metrics with Datadog

src/gateway/get-started/configure-services-and-routes.md
A new tutorial doc that covers services and routes. 
[2415](https://konghq.atlassian.net/browse/DOCU-2415)
coming soon
=> [DOCU-2415] Configure Routes and Services

app/_data/docs_nav_deck_1.13.x.yml, app/_data/kong_versions.yml
Updates the decK docs from 1.12.x -> 1.13.x
=> [update] Update decK version

.github/styles/kong/Repetition.yml, src/kubernetes-ingress-controller/concepts/ingress-versions.md, src/kubernetes-ingress-controller/guides/configuring-https-redirect.md, src/kubernetes-ingress-controller/guides/prometheus-grafana.md, src/kubernetes-ingress-controller/guides/using-gateway-api.md
Add Vale repetition rule. Triggered by #4243 
It will run in CI
=> Add Vale repetition rule

app/_hub/kong-inc/rate-limiting-advanced/_index.md
Opened this PR so I could make Vale updates to [this PR](https://github.com/Kong/docs.konghq.com/pull/4237) created from a forked branch. 
https://github.com/Kong/docs.konghq.com/pull/4237
=> Add Redis disconnect behavior to Rate Limiting Advanced plugin

app/_data/docs_nav_gateway_3.0.x.yml, src/gateway/understanding-kong/how-to/aws-secrets-manager.md
DEVREL-372: Adds a how-to guide for PG Secrets via AWS Secrets Manager
DEVREL-372
Built docs locally, will repair any vale or build errors forward
https://deploy-preview-4233--kongdocs.netlify.app/gateway/latest/understanding-kong/how-to/aws-secrets-manager/
=> DEVREL-372: Adds a how-to guide for PG Secrets via AWS Secrets Manager

gulpfile.js
Fix the need to rerun `make dev` manually when editing `src` files
Test locally
=> Automatic Jekyll rebuild when changing src

src/gateway/understanding-kong/key-concepts/routes.md
New doc: Provides an overview of what a route is and how they work in Gateway
[DOCU-2409](https://konghq.atlassian.net/browse/DOCU-2409)
=> [DOCU-2409] Understanding Kong: Routes

src/gateway/understanding-kong/key-concepts/upstreams.md
New Doc: Provides an overview of what an upstream is and how they work in Gateway
[DOCU-2410](https://konghq.atlassian.net/browse/DOCU-2410)
Is the upstream example accurate? Or is there anything else I can add?
=> [DOCU-2410] Understanding Kong: Upstreams

app/_hub/kong-inc/statsd-advanced/_index.md, app/_hub/kong-inc/statsd/_index.md
1. Update StatsD document based on the latest code
2. Add a message about removing StatsD Advanced plugin
=> feat(statsd) update StatsD document

app/_hub/kong-inc/forward-proxy/_index.md
fix the http_proxy_host example value
=> fix the http_proxy_host example value

.github/workflows/build-docs-pdf.yml, pdf-generation/build-urls.js, pdf-generation/package-lock.json, pdf-generation/package.json, pdf-generation/run.js
Fix PDF generation for nav items that depend on redirects
Can't currently build Mesh PDFs
Successful run at https://github.com/Kong/docs.konghq.com/actions/runs/2903035543
=> Use netlify dev for PDF generation

src/gateway/kong-production/monitoring/prometheus.md
Adds a how-to guide for monitoring with Prometheus 
Built docs locally
https://konghq.atlassian.net/browse/DOCU-2422
=> DOCU-2422: Adds How to monitor with Prometheus

src/mesh/features/vault.md
Document CommonName replace functionality. 
We implemented this in upcoming KM 1.9
Waiting for preview...
=> mesh: replace characters in common name

app/enterprise/2.1.x/kong-manager/administration/workspaces/workspaces.md, app/enterprise/2.2.x/kong-manager/administration/workspaces/workspaces.md, app/enterprise/2.3.x/kong-manager/administration/workspaces/workspaces.md, app/enterprise/2.4.x/kong-manager/administration/workspaces/workspaces.md, app/enterprise/2.5.x/kong-manager/administration/workspaces/workspaces.md, app/gateway/2.6.x/configure/auth/kong-manager/workspaces.md, app/gateway/2.7.x/configure/auth/kong-manager/workspaces.md, app/gateway/2.8.x/configure/auth/kong-manager/workspaces.md
2.x version of https://github.com/Kong/docs.konghq.com/pull/4299.
Workspace name is not editable once you've created the workspace.
https://konghq.atlassian.net/browse/DOCU-2387
Netlify
=> [DOCU-2387] Workspace name is not editable (main branch)

app/gateway/changelog.md
=> [changelog] version update

app/mesh/changelog.md
Signed-off-by: slonka <slonka@users.noreply.github.com>
Update changelog.md before release
Release
Not needed
=> docs: update changelog

app/konnect-platform/support-policy.md
Add the new mesh version to the support policy
=> Add Mesh 1.9.0 to support policy

app/_data/docs_nav_mesh_1.9.x.yml, app/_data/kong_versions.yml, app/konnect-platform/support-policy.md, app/mesh/changelog.md, src/mesh/features/vault.md
Release Mesh 1.9
Preview coming soon
=> [Release] mesh 1.9

Gemfile, Gemfile.lock, app/_includes/breadcrumbs.html, app/_plugins/filters/titleize_filter.rb
Title Case breadcrumbs rather than Sentence case
/gateway/latest/kong-production/install-options/helm/
=> Titleize breadcrumbs

src/gateway/kong-production/install-options/docker/build-custom-images.md
Address feedback from eng-enablement channel + Saju
=> Docker custom build feedback

app/_data/docs_nav_gateway_3.0.x.yml, app/_data/tables/features/gateway.yml, app/_data/tables/install_options.yml, app/_includes/feature-table.html, src/gateway/kong-production/install-options/index.md
Add install options index page
[/gateway/3.0.x/kong-production/install-options/](https://deploy-preview-4343--kongdocs.netlify.app/gateway/latest/kong-production/install-options/)
=> Docu 2484 install index page

app/_data/tables/install_options.yml, src/gateway/install/index.md
Update /install/ index page with accurate support column
=> Update /install/ index page

app/_plugins/generators/plugin_single_source_generator.rb
Canonical URLs for plugins.
Fixing smoke tests once more.
Smoke tests should pass.
=> Add / to plugin canonical URLs

src/gateway/get-started/rate-limiting.md
Fixes the getting started section around advanced rate limiting
Built docs locally
=> Get Started: Updates rate limiting advanced plugin discussion

app/_hub/signal_sciences/signal-sciences/_index.md
Fix a typo in the plugin reference
Typo, intal -> install
N/A
review:copyedit
=> Fix typo in plugin reference documentation

app/_data/docs_nav_gateway_3.0.x.yml, src/gateway/kong-enterprise/fips-support.md, src/gateway/kong-enterprise/index.md
Docs for Kong Gateway FIPS mode.
https://konghq.atlassian.net/browse/DOCU-2063
FT-1806.
https://deploy-preview-4306--kongdocs.netlify.app/gateway/latest/kong-enterprise/fips-support/
https://deploy-preview-4306--kongdocs.netlify.app/gateway/latest/kong-enterprise/#fips-support
=> docs(*) fips

app/_hub/kong-inc/request-transformer-advanced/_index.md, app/_hub/kong-inc/request-transformer/_index.md, app/_hub/kong-inc/request-validator/_index.md
Update some overlooked paths in plugins for new router.
Need for a doc update called out in https://docs.google.com/spreadsheets/d/1FYbaNny9Z58WYYyjCNcKc4GB8VUfdq8utzBODvmPmjo/edit.
Not really sure the syntax is right. Needs a tech review.
=> Add `~` to paths attribute in plugins

tools/moved-urls-checker/README.md, tools/moved-urls-checker/package-lock.json, tools/moved-urls-checker/package.json, tools/moved-urls-checker/run.js
Add a tool that outputs pages that are missing a `moved_urls.yml` entry
Some old pages are linking to themselves as the latest URL for a piece of content as there's a missing `moved_urls.yml` entry
I tested with the following:
```bash
node run.js --nav gateway_2.8.x
```
And got the following output:
```
-----------------------------------------------------------------
Pages that link to themselves (no moved_urls.yml entry set):
-----------------------------------------------------------------
http://localhost:8888/gateway/2.8.x/availability-stages/
http://localhost:8888/gateway/2.8.x/install-and-run/centos/
http://localhost:8888/gateway/2.8.x/get-started/quickstart/configuring-a-service/
http://localhost:8888/gateway/2.8.x/get-started/quickstart/configuring-a-grpc-service/ …
```
=> Add moved_urls.yml detection tool

app/_hub/kong-inc/rate-limiting-advanced/_index.md, app/_hub/kong-inc/rate-limiting/_index.md, app/_hub/kong-inc/response-ratelimiting/_index.md, app/gateway/changelog.md, src/gateway/get-started/ratelimiting.md, src/gateway/kong-enterprise/consumer-groups/index.md
=> Update default policy/strategy for rate limiting plugins

app/contributing/style-guide.md, app/contributing/word-choice.md
Expand capitalization guidelines and clean up some terminology.
The plugin question came up in Slack, and has come up before.
Netlify
=> Style guide: capitalization

app/gateway/changelog.md
This pull request adds missing entries for bug fixes in Gateway 2.8.x.x series.
=> fix(changelog): add missing entries for GW 2.8.x.x

app/_data/kong_versions.yml, app/_hub/kong-inc/ldap-auth-advanced/_index.md
Add a couple of missing pieces of docs for 3.0.
=> docs(gateway) add 3.0 dependencies versions

.github/styles/kong/Terms.yml, .github/styles/kong/dictionary.txt, app/gateway/2.8.x/reference/db-less-and-declarative-config.md, src/deck/faqs.md
Validate dbless configuration with Visual Studio Code and SchemaStore.
Include schema validation in schemastore and use that with redhat extension in Visual Studio Code. 
The steps for test on doc changes
=> Include sample: how can configure dbless with Visual Studio Code.

app/gateway/changelog.md, src/gateway/upgrade.md
1. OSS also supports bg migration for hybrid mode;
2. Instruction and explanation of the migrations process
=> Correct statements of blue-green deploys

.github/workflows/run-smoke-tests.yml, Makefile, README.md, package-lock.json, package.json, tests/__utils__/customMatchers.js, tests/__utils__/fetchPage.js, tests/breadcrumbs.test.js, tests/edit_link.test.js, tests/home.test.js, tests/install.test.js, tests/plugin.test.js, tests/seo.test.js, tests/sidebar.test.js, tests/titles.test.js
Decrease smoke test time by not spinning up a browser for every test
Saving the environment, one PR at a time. (The tests run in ~5 seconds rather than 2 minutes)
Check GitHub Actions on this PR, or run `make smoke` locally
=> Replace Playwright with fetch+cheerio

app/gateway/changelog.md
☝️ 
Switching to slim images should be a bigger change for consumers, but we should still mention this.
=> We switched our convenience tags from Alpine base to Debian base

src/gateway/index.md
Fix duplicated breadcrumb on Gateway index page
=> Fix Kong Gateway overview breadcrumb

app/_data/landing_page.yml
=> Fix homepage links

app/gateway/changelog.md
=> Add broken Alpine image to 3.0 Known Issues

app/_data/tables/features/gateway.yml, src/gateway/install/index.md
Clean up feature comparison table and make the install options easier to understand.
[/gateway/latest/](https://deploy-preview-4446--kongdocs.netlify.app/gateway/latest/#features)
[/gateway/latest/install/](https://deploy-preview-4446--kongdocs.netlify.app/gateway/latest/install/)
=> Feature table alignment

app/konnect/architecture.md, app/konnect/getting-started/access-account.md, app/konnect/index.md, app/konnect/updates.md
Any suggestions for another place to add the quick start link? 
[docu-2480](https://konghq.atlassian.net/browse/DOCU-2480)
=> [DOCU-2480] CTA in Konnect

app/konnect/architecture.md, app/konnect/getting-started/access-account.md, app/konnect/index.md, app/konnect/updates.md
=> [Cherry Pick] CTA in Konnect (#4445)

.github/styles/kong/dictionary.txt, app/konnect/org-management/teams-and-roles/teams-reference.md
These changes to predefined teams have been made in production:
- Remove Portal Viewer
- Remove Service Maintainer
- Add Organization Admin (Read Only)
Announcement https://kongstrong.slack.com/archives/C01888Q7PJ7/p1662683646165059
The removed teams were meaningless carryover from Cloud01 or not being used.
The new team was a feature request.
No testing required.
=> Update Predefined Teams

app/_data/tables/features/gateway.yml
=> Fixing a FIPS typo

app/_hub/kong-inc/openid-connect/_index.md
EE plugin `openid-connect` now supports both anonymous username and UUID.
Refer to FTI-3340.
Docs misleads customers.
=> feat(openid-connect) support both anonymous username and UUID

app/konnect/dev-portal/customization/index.md
Changes have been made already, so we can update the docs now to include the list of restrictions.
=> chore: uncomment domain name restrictions (TDX-2341)

app/_includes/md/personal-access-token.md, app/konnect/getting-started/import.md, app/konnect/runtime-manager/runtime-groups/declarative-config.md, src/deck/guides/konnect.md
Made the generating a PAT doc an include file so we can include it in Konnect and decK docs. The plan is to create a standalone "API Auth" page in the Konnect docs once the API is public and add this to that.
https://kongstrong.slack.com/archives/CDSTDSG9J/p1663748332710429
Netlify
=> PAT docs for Konnect

app/gateway/changelog.md
=> [fix] Broken link in changelog

src/gateway/kong-manager/auth/reset-password.md
This PR removes the third reset token step.
[FTI-4356](https://konghq.atlassian.net/browse/FTI-4356) Can not type a new token in Kong Manager
=> fix(auth): update reset token steps.

src/gateway/reference/configuration.md
Adding missing property.
Property is missing from doc.
Netlify
=> Add missing router_flavor property to conf ref

app/_hub/kong-inc/jwt/_index.md
Signed-off-by: afzal442 <afzal442@gmail.com>
This PR simply updates the `jwt` response for consumer id
fixes: [#8286](https://github.com/Kong/kong/issues/8286)
review:copyedit: Request for writer review
=> fix: Updated the `jwt` response for consumer id

.github/styles/kongplugins/plugin-ignore.txt, app/_hub/kong-inc/jwt/_index.md
- changes urls to `localhost`
- Updates the response examples. 
https://github.com/Kong/kong/issues/8286
Make sure everything is rendering correctly.
=> [update] Update responses examples in JWT plugin docs

.github/styles/kongplugins/plugin-ignore.txt
Missed this one, as I didn't ask the contributor to rebase https://github.com/Kong/docs.konghq.com/pull/4527.
Fix breaking check.
=> Add grant_type to plugin ignore list

src/gateway/kong-manager/auth/oidc/configure.md
adds the admin mapping claim
Slack report in #docs
https://docs.konghq.com/hub/kong-inc/openid-connect
=> [fix] Add admin claim

src/kubernetes-ingress-controller/deployment/k4k8s.md
Signed-off-by: afzal442 <afzal442@gmail.com>
Adds correct link to kustomize install and modifies helm install to add missing namespace
Adds a note to support hostname.
Fixes: #4159
=> fix: Added correct link to `kustomize` install and modifies `helm` install and note to show an option 

app/mesh/1.1.x/install.md, app/mesh/1.2.x/install.md, app/mesh/1.3.x/install.md, app/mesh/1.4.x/install.md, app/mesh/1.5.x/install.md, app/mesh/1.6.x/install.md, src/mesh/install.md
Fixed the path to the icons on the mesh install docs
=> [fix] mesh install icons

docs/platform-install.md
Signed-off-by: afzal442 <afzal442@gmail.com>
Fixes #4235 
This PR adds missing instruction to platform-install on how to install all deps
review:tech: Request for technical review from an SME.
=> chore: Adds instruction to platform-install to install all deps

app/konnect/network.md
Added the hostnames that were missing for the geo regions to the Network page. I also reformatted the hostnames into two different tables, let me know if that doesn't work as well as a list.
https://github.com/Kong/docs.konghq.com/pull/4147#issuecomment-1268934047
/konnect/network
=> Multi-geo API updates

app/konnect/updates.md
Added update regarding Quick start release notes.
=> Updated for quick start release notes

app/konnect/updates.md
Konnect Platform September release notes.
Konnect Platform September release notes.
None Required.
=> Add Org Admin (Read Only) Predefined Team

app/konnect/dev-portal/index.md, app/konnect/servicehub/service-versions.md
Signed-off-by: Tomasz Wylężek <tomwylezek@gmail.com>
Adjust content related to service version lifecycle.
For now the work is behind FF and when the feature is GA then we will merge that docs adjustment
TDX-2281
Definitely want layout / readability / if proper place opinions about what I wrote.
https://deploy-preview-4334--kongdocs.netlify.app/konnect/servicehub/service-versions/
=> feat(service-version): adjust docs [tdx-2281]

Makefile
This PR adds a ruby version check as per the version defined in the `.ruby-version` file.
```
make ruby-version-check
```
=> chore(build): add specific ruby requirement check in Makefile

app/konnect/updates.md
=> add the dev portal september release notes

app/gateway/changelog.md
Forgot to update the release date for Gateway 2.8.2.0.
=> Update release date for 2.8.2

src/gateway/admin-api/index.md
Remove the invalid field from this API endpoint docs.
=> fix(admin-api): removed consumers type field

app/gateway/changelog.md
Signed-off-by: Andrew Kew <andrew@quadcorps.co.uk>
Adding changelog for FTI-2744 missed from new release 2.8.2.0
Missing from changelog
=> Added changelog for FTI-2744 for 2.8.2.0

app/_hub/kong-inc/mocking/_index.md
Mocking plugin enhancements
[FTI-4188]
[FTI-4188]: https://konghq.atlassian.net/browse/FTI-4188?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(mocking): Mocking functionality enhancements

app/konnect/updates.md
Adding links to the relevant docs for Sept Konnect release notes
=> Update Sept Konnect release notes w/ doc links

app/konnect/updates.md
* Fixing release note entry formatting
* Quick copyedit of all September release notes
* Add beta badge to dynamic client registration, which is in beta according to release note
Ran into broken formatting in Konnect release notes:
Netlify
=> Konnect release note fixes

app/_data/tables/compat.json, app/gateway/2.6.x/compatibility.md, app/gateway/2.7.x/compatibility.md, app/gateway/2.8.x/compatibility.md
Adjust the docs to reflect updates from product.
cc @anandraiin3 
From FTI-4303, DOCU-2489
=> doc: remove RHEL 7 and mention minor version support policy

app/gateway/changelog.md
https://konghq.atlassian.net/browse/DOCU-2468
=> [fix] 2.7 changelog known issue 

.github/styles/kongplugins/auto-ignore.txt, .github/styles/kongplugins/dictionary.txt, app/_hub/kong-inc/basic-auth/_index.md, app/_hub/kong-inc/hmac-auth/_index.md, app/_hub/kong-inc/jwt/_index.md, app/_hub/kong-inc/key-auth-enc/_index.md, app/_hub/kong-inc/key-auth/_index.md, app/_hub/kong-inc/ldap-auth-advanced/_index.md, app/_hub/kong-inc/ldap-auth/_index.md, app/_hub/kong-inc/mtls-auth/_index.md, app/_hub/kong-inc/oauth2-introspection/_index.md, app/_hub/kong-inc/oauth2/_index.md, app/_hub/kong-inc/openid-connect/_index.md, app/_hub/kong-inc/vault-auth/_index.md
Allow anonymous to be configured as the username of the consumer.
I've never tested yet
FTI-3109
https://github.com/Kong/kong/pull/9371
=> Allow anonymous to be configured as the username of consumer

app/_hub/index.html
Add Kong Gateway to Plugin Hub title
Aghi request
/hub/
=> Add Kong Gateway to Plugin Hub title

src/kubernetes-ingress-controller/deployment/k4k8s.md
fix helm install command to install Kong in the following pages:
- https://docs.konghq.com/kubernetes-ingress-controller/latest/deployment/k4k8s/
fix the invalid helm command in deployment/k4k8s page. 
https://deploy-preview-4642--kongdocs.netlify.app/kubernetes-ingress-controller/latest/deployment/k4k8s/
=> fix helm install command

app/_data/docs_nav_konnect.yml, app/_data/tables/install_options_konnect.yml, app/_includes/feature-table.html, app/_includes/md/konnect/runtime-certs.md, app/konnect/index.md, app/konnect/runtime-manager/index.md, app/konnect/runtime-manager/runtime-instances/gateway-runtime-conf.md, app/konnect/runtime-manager/runtime-instances/gateway-runtime-docker.md, app/konnect/runtime-manager/runtime-instances/gateway-runtime-kubernetes.md, app/konnect/runtime-manager/runtime-instances/index.md, app/konnect/runtime-manager/runtime-instances/renew-certificates.md, app/konnect/runtime-manager/runtime-instances/runtime-parameter-reference.md, src/gateway/install/index.md
* Intro page for runtime instance installation options
* Update runtime instance instructions to match UI
* Update code samples & reference with `konnect_mode` and `vitals`, two new params that are now recommended/needed in Konnect.
DOCU-2495
This can be merged at any time after review, as the UI changes are already live.
Netlify
=> [DOCU-2495] Runtime instances updates for October

.github/styles/kong/dictionary.txt, app/_data/docs_nav_konnect.yml, app/api/identity.yaml, app/konnect/api/filtering.md, app/konnect/api/identity-management/identity-integration.md, app/konnect/api/index.md, app/konnect/identity-management-api.md, app/konnect/updates.md
Cherry-pick from Konnect branch
https://konghq.atlassian.net/browse/DOCU-2552
=> Add API documentation to Konnect (#4633)

src/gateway/production/deployment-topologies/hybrid-mode/index.md
=> Remove stray todo

app/konnect/dev-portal/applications/dynamic-client-registration/okta.md, app/konnect/updates.md
Adding the beta banner to doc, release note, and minor edits.
DCR is in public beta but there's nothing in the docs to note that.
Netlify
=> Add beta banner to DCR doc

src/gateway/kong-enterprise/fips-support.md
Updates fips
https://github.com/Kong/docs.konghq.com/pull/4686
=> [update] fips

.github/styles/kongplugins/auto-ignore.txt, app/_hub/kong-inc/acme/_index.md
Add support for Redis SSL
Internal ticket FTI-4432
=> feat(acme): add support for Redis SSL

app/_data/docs_nav_gateway_3.0.x.yml, app/gateway/2.8.x/plan-and-deploy/security/secrets-management/advanced-usage.md, src/gateway/kong-enterprise/secrets-management/advanced-usage.md
[INTF-2957](https://konghq.atlassian.net/browse/INTF-2957) Need to update docs vaults link `vaults-object` instead of `vaults-entity`
=> Change docs vaults link `vaults-entity` to `vaults-object`

app/api/identity.yaml
Update identity.yaml with latest OAS updates.
- Spelling/Formatting
- Filtering attribute name -> role
- 200 -> 201 upon create
=> Update identity.yaml with latest specs

src/mesh/gettingstarted.md
Updated the "Getting Started" page because it was still directing users to the Kuma docs. 
Kuma docs are now shared with Mesh, so linking users to the Kuma docs isn't necessary.
/mesh/latest/gettingstarted/
=> Update Getting Started to remove references to Kuma docs

src/mesh/index.md
Adds link to https://kuma.io/docs/1.8.x/contribute/introduction/#community
=> Add Kuma contribution link to Mesh intro. 

app/_data/docs_nav_mesh_2.0.x.yml, app/_redirects
Fixed the following:
- https://deploy-preview-4710--kongdocs.netlify.app/mesh/latest/documentation/configuration/: broken link on Overview text (/mesh/2.0.x/documentation/introduction), but I think that’s linking to the wrong spot in Kuma and should be changed to a different link. I added a redirect to a page that I thought would work rather than fix the link in Kuma right now because they froze docs. 
- Changed nav name to "Kong Mesh data collection" to match Kuma.
- Added this missing page: https://deploy-preview-4710--kongdocs.netlify.app/mesh/2.0.x/generated/cmd/kumactl/kumactl_get_zone
I also found a few issues that were both in Kuma and Kong Mesh (formatting issues, won't impact user's workflows I don't think), that I think could be fixed post 2.0 since Kuma docs are frozen right …
=> Fix QA issues in Networking, Monitor & Manage, Resource Docs

app/_data/docs_nav_mesh_2.0.x.yml, src/mesh/features/access-audit.md, src/mesh/features/rbac.md
Access audit functionality in Kong Mesh 2.0
=> mesh: access audit

app/_hub/kong-inc/response-ratelimiting/_index.md
Add corresponding docs for the PR https://github.com/Kong/kong/pull/8595
=> feat(response-ratelimiting): add support for Redis SSL

src/mesh/installation/ecs.md
See https://github.com/Kong/docs.konghq.com/pull/4717#discussion_r1014190064
=> chore: replace Kong Mesh with product in ECS docs

app/gateway/changelog.md
=> Add missing global plugins scope fix

app/_hub/kong-inc/request-transformer/_index.md
Kept the one with the most info (value_in_examples)
=> feat: remove duplicate replace.body

app/konnect/dev-portal/applications/dynamic-client-registration/okta.md
Fixing a broken step.
Broken step:
https://deploy-preview-4746--kongdocs.netlify.app/konnect/dev-portal/applications/dynamic-client-registration/okta/
=> Konnect DCR: Fix broken step

app/_hub/kong-inc/application-registration/_index.md
=> Dead link #4736

app/_assets/javascripts/app.js, src/gateway/index.md
Testing the form handler in netlify preview
=> DOCU-2494 - CTA for onboarding nurture campaign

app/konnect/dev-portal/customization/index.md
Removing section of supported TLDs, as we now support generic TLDs (except the ones listed under the restrictions section).
TDX-2586
=> chore(konnect-portal): remove section regarding supported TLDs (TDX-2586)

app/_includes/header.html
The new Konnect platform is at https://cloud.konghq.com.
=> fix(plugins): update konnect cloud link in konnect-compatible plugin badge

app/_hub/kong-inc/response-ratelimiting/_index.md
=> fix(response-rl): explanation of month and year

.github/styles/kong/dictionary.txt, .github/styles/kongplugins/dictionary.txt, .github/styles/kongplugins/plugin-ignore.txt, app/_hub/kong-inc/forward-proxy/_index.md
update for https://github.com/Kong/kong-ee/pull/3582
=> update for forward proxy: x_headers

app/konnect/dev-portal/applications/dynamic-client-registration/okta.md, app/konnect/dev-portal/applications/enable-app-reg.md, app/konnect/runtime-manager/runtime-groups/index.md, app/konnect/updates.md
*docs from TDX-2587 TDX 2195 
* Changelog entry
https://konghq.atlassian.net/browse/DOCU-2517
=> [DOCU-2517] App Reg Multiple RGs and DCR - GA release

app/konnect/analytics/index.md, app/konnect/org-management/teams-and-roles/teams-reference.md, app/konnect/updates.md
Contains a cherry pick of the new analytics teams docs from `konnect` to `main`. 
#4732
TBA, this PR was already approved by PM and a writer, so it just needs a quick review
=> New Analytics roles cherry pick (#4732)

tests/seo.test.js
=> Fix flaky spec

src/kubernetes-ingress-controller/guides/prometheus-grafana.md
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX19Gzhxlxn0g0BkvRQXrRWlx9prZbuGahM%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=Glp2wfW)
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX18WxqUMzOqy3Oh2wdcwc1z0JO20nZb6DI%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=gylaTq7)
Command for installing the billing, invoice, and comments services while following the Prometheus-Grafana guide for Kong does not work. Link to the docs - https://docs.konghq.com/kubernetes-ingress-controller/2.7.x/guides/prometheus-grafana/#install-services. The …
=> fix link for installing services in promstack guide

app/konnect/dev-portal/applications/enable-app-reg.md, src/kubernetes-ingress-controller/guides/prometheus-grafana.md
Adding a note that some plugins are not compatible if they are not in the default runtime group.
=> chore(portal): add note for multi rg regarding plugins (TDX-2637)

app/konnect/updates.md
=> DOCU-2803 - AppReg for multi RGs GA

docs/templates/explanation-template.md, docs/templates/how-to-template.md, docs/templates/reference-template.md, docs/templates/tutorial-template.md
Reusable content type templates that we can use when creating a new page.
For reviewers:
- Feel free to make any suggestions on the templates, I just used info from Divio, my experience with our docs, and I based it off of [GitHub's templates](https://github.com/github/docs/blob/main/contributing/content-templates.md#conceptual). Admittedly, I still get some of the content types confused. 
- The eventual vision is that I also add a page to our contributing guide (external, I think) that explains each topic type in more detail, similar to what [GitHub has here](https://github.com/github/docs/blob/main/contributing/content-model.md#content-types). So it would contain info about how to title the topic/sections, how to write the info in the topic, and example docs. I'd then add links to that …
=> Content type templates

app/konnect/compatibility.md, app/konnect/updates.md
This is a cherry-pick of the konnect 3.1 release notes.
=> [docu-2777] Konnect release notes for GW 3.1 (#4842)

app/_data/docs_nav_gateway_3.1.x.yml, src/gateway/kong-enterprise/consumer-groups/index.md, src/gateway/kong-manager/consumer-groups.md
Documenting how to create consumer groups in KM by using a tutorial. 
DOCU-2782
- I didn't have a dev KM instance, so I'm not sure if everything works as intended. It would be great if someone could test the steps out to verify everything is correct.
- I chose not to add the KM instructions to the [Enterprise consumer groups doc](https://docs.konghq.com/gateway/latest/kong-enterprise/consumer-groups/) for several reasons. I tried to, and it was kind of a formatting nightmare that would take a lot more time to work out. And, they provide instructions for deleting the consumer group, which we wouldn't want to document for KM because that would just be generic UI instructions vs. tutorial steps. Let me know if you think was this the wrong approach.
- The [Enterprise …
=> [DOCU-2782] KM Consumer Groups

app/_includes/md/support-policy.md
New  table entry for 3.1 support.
Chore PR for 3.1
Netlify
=> Update support policy for 3.1

app/_data/tables/os_support.yml, app/gateway/changelog.md
Added Ubuntu 22.04 support to the 3.1 changelog and OS support table.
DOCU-2824
- View the changelog (is that a good spot for OS support?)
- View /gateway/latest/os-support/ to see if Ubuntu 22.04 is listed there
=> [DOCU-2824] 3.1 fast-follow: Ubuntu 22.04 support

src/gateway/how-kong-works/routing-traffic.md
=> Remove duplicate text in routing-traffic.md

src/kubernetes-ingress-controller/concepts/design.md
=> Minor grammar fix

app/_includes/md/support-policy.md
Change 3.1 date from 12/01 to 12/06 in support policy table
=> Update support policy w/ new 3.1 date

app/gateway/changelog.md
Change release date from 12/01 to 12/06 in changelog
=> Update changelog w/ new 3.1 date

app/_data/docs_nav_gateway_3.1.x.yml, app/_redirects, src/gateway/migrate-ce-to-ke.md, src/gateway/upgrade-31x.md
Created a new upgrade doc for 3.1.x that contains the incremental upgrade scenarios for 3.1.x.
DOCU-2823
- /gateway/latest/upgrade-31x (is the file name okay for this one?)
- Check the redirect that I added. Is it correct and does it work?
=> [DOCU-2823] New 3.1.x Upgrade doc

app/konnect/api/index.md
=> [fix] Change API url

app/_data/kong_versions.yml, app/gateway/changelog.md
=> Bump version

app/gateway/changelog.md
Adding link for Dynamic Log Levels to changelog.
=> docs link in gateway changelog

app/mesh/changelog.md, src/mesh/support-policy.md
=> add changelog for 2.0.1 and fix support-policy with 2.0.x

app/_data/docs_nav_contributing.yml, app/contributing/contribution-templates.md
=> Content Templates added to contribution guide

.github/styles/kong/dictionary.txt, app/_data/docs_nav_konnect.yml, app/konnect/dev-portal/applications/dynamic-client-registration/curity.md
Konnect Portal support for DCR with Curity as the IDP is currently being validated behind a feature flag. This PR is anticipation if it being made GA soon.
=> feat(portal-dcr): how-to configure Curity DCR for konnect portal [TDX-2644]

app/_data/kong_versions.yml
Update CE and EE versions for Kong Gateway
We missed this step with the latest release
N/A
=> Fix Gateway EE versions

app/konnect/api/index.md
=> Attempted fix to 404 on runtime groups config

app/_hub/kong-inc/key-auth/_index.md
1. `ttl` is incompatible with DB-less or Hybrid mode.
2. Add `tags` doc entry.
Misleading customers.
=> fix(key-auth): add missing docs

app/_data/docs_nav_konnect.yml, app/konnect/api/portal-auth/portal-rbac-guide.md
Adds Portal RBAC Setup Guide
TDX-2666
=> feat(konnect-portal): adds guide for setting up rbac via API endpoints

app/_assets/javascripts/ab-test.js
A/B test concluded with no significant result
=> Force top CTA to always go to Sales demo

app/_data/docs_nav_konnect.yml, app/konnect/dev-portal/applications/dynamic-client-registration/auth0.md, app/konnect/dev-portal/applications/dynamic-client-registration/curity.md
Konnect Portal support for DCR with Auth0 as the IDP is currently being validated behind a feature flag. This PR is anticipation if it being made GA soon.
=> feat(konnect-portal): how-to configure Auth0 DCR [TDX-2715]

.github/styles/kong/dictionary.txt, app/_data/docs_nav_konnect.yml, app/konnect/dev-portal/applications/dynamic-client-registration/curity.md
…-2644] (#4893)
* feat(portal-dcr): add how-to for configuring Curity DCR for konnect portal
* refactor(dcr): update curity intro
* feat(dcr): add curity DCR to the konnect nav
* Apply suggestions from code review
* Fix Vale error
Co-authored-by: Diana <75819066+cloudjumpercat@users.noreply.github.com>
cherry pick for Curity DCR GA
DOCU-2832
=> Cherry-pick - Curity DCR 

app/konnect/updates.md
=> Add Curity DCR changelog

app/_src/gateway/admin-api/admin-api-3.0.x.md, app/_src/gateway/admin-api/index.md, app/gateway/2.7.x/admin-api/index.md, app/gateway/2.8.x/admin-api/index.md, app/konnect/api/runtime-groups-config/index.md
Removes duplicate text: 
```
Default: `true`.
```
=> fix(admin-api): remove duplicate text

app/_src/gateway/admin-api/consumer-groups/reference.md
support is available as of decK 17.0.0.
=> Remove note about decK + consumer groups

app/konnect/api/runtime-groups-config/index.md
Addressed extra http in API call
=> Fixed extra http in API call

app/_hub/kong-inc/rate-limiting-advanced/_index.md
reflect the change of https://github.com/Kong/kong-ee/pull/3926
=> plugin(RLA): custom response

app/_hub/kong-inc/key-auth-enc/_index.md
Support tags of a key (FTI-4084)
FTI-4084 requests to add `tags` to a key.
Feat #_[FTI-4084]_
[FTI-4084]: https://konghq.atlassian.net/browse/FTI-4084?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(key-auth-enc): support tags of a key (FTI-4084)

app/mesh/changelog.md
Add changelog for version 1.9.2
New release
=> docs(mesh): add changelog for 1.9.2

app/_hub/kong-inc/vault-auth/_index.md
Fix broken link in vault-auth doc.
=> [fix] broken link in vault-auth plugin doc.

app/_data/docs_nav_konnect.yml, app/konnect/upgrade-faq.md
https://konghq.atlassian.net/browse/DOCU-2892
This adds an FAQ page that contains information about CP upgrades. 
https://deploy-preview-4986--kongdocs.netlify.app/konnect/upgrade-faq/
[DOCU-2892]: https://konghq.atlassian.net/browse/DOCU-2892?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [docu-2892] Konnect CP Upgrade faq

app/_src/gateway/get-started/services-and-routes.md, app/_src/gateway/how-kong-works/routing-traffic.md, app/_src/gateway/key-concepts/routes/index.md
Describe the basic routing strategy of Kong Gateway
Some users don't understand how Kong Gateway routes requests and make incorrect assumptions.
https://github.com/Kong/kong/issues/9914#issuecomment-1349975871
https://github.com/Kong/kong/issues/9589
KAG-247
=> Add description of basic routing logic of Kong Gateway

app/_hub/kong-inc/key-auth-enc/_index.md
https://konghq.atlassian.net/jira/software/c/projects/DOCU/boards/58?modal=detail&selectedIssue=DOCU-2373
Does this parameter need to be added to the top config parameter section?
=> [DOCU-2373] Key auth encrypted plugin: Re-add ttl when parameter is available

app/_hub/kong-inc/opentelemetry/_index.md
=> typo in otelcollector command

app/konnect/dev-portal/applications/dynamic-client-registration/curity.md
Removed the beta flag for the DCR Curity doc.
DCR Curity is going GA.
Verify beta flag is removed at /konnect/dev-portal/applications/dynamic-client-registration/curity/
=> DCR Curity [GA]

app/mesh/changelog.md
Add changelog for version 1.6.3, 1.7.5, 1.8.4
Released a few weeks ago
=> docs(mesh): add changelog for 1.6.3, 1.7.5, 1.8.4

.github/PULL_REQUEST_TEMPLATE.md
Tested PR template and found some errors. This fixes them.
Netlify link: n/a
=> PR template fixes

app/mesh/changelog.md
Add a changelog for versions that are going to be released
We are working on the patch release but it isn't ready yet. Prepared PR with changes to merge them after releasing of helm chart.
Do not merge yet
=> docs(mesh): add new release changelog and fix old one

app/_data/docs_nav_konnect.yml, app/konnect/dev-portal/applications/dynamic-client-registration/auth0.md, app/konnect/dev-portal/applications/dynamic-client-registration/curity.md
This cherry picks #4952  from `konnect` to `main` to prepare it for GA. 
* feat(portal-dcr): add how-to guide for Auth0 DCR in konnect portal
* fix(konnect-portal): adjust steps in Curity guide to match the correct field names
* fix(typo): initial
* Update auth0.md
Updating instances of Konnect to use variable
Co-authored-by: Amy Goldsmith <59702069+acgoldsmith@users.noreply.github.com>
=> [cherry-pick] how-to configure Auth0 DCR [TDX-2715] (#4952)

app/contributing/style-guide.md
Added a few do/do not entries to our style guide. I've been running into these a bunch during reviews.
Netlify link: https://deploy-preview-5056--kongdocs.netlify.app/contributing/style-guide/
=> Add some common issues to style guide

app/_hub/kong-inc/jwt-signer/_index.md
small corrections to jwt-signer config docs.
~- [ ] PR pointed to correct branch (`main` for immediate publishing, or a release branch: e.g. `release/gateway-3.2`, `release/deck-1.17`)~
https://konghq.atlassian.net/browse/KAG-316
=> docs(jwt-signer): improve config description

app/_hub/kong-inc/rate-limiting-advanced/_index.md
Add details to various parameters' descriptions in order to make the documentation more clear and user friendly.
This is part of the ongoing effort of improving plugins docs
[KAG-156]
[KAG-156]: https://konghq.atlassian.net/browse/KAG-156?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs(rate-limiting-advanced): revise parameters descriptions

app/_hub/kong-inc/opa/_index.md
Support custom message from OPA server (FTI-4574). Related code PR is <https://github.com/Kong/kong-ee/pull/4362>.
=> feat(opa): support custom message from OPA server (FTI-4574)

app/konnect/api/portal-auth/portal-rbac-guide.md
https://kongstrong.slack.com/archives/CDSTDSG9J/p1674505360158049
=> [fix] Mention where to find the Dev Portal Portal ID

app/_data/kong_versions.yml, app/gateway/changelog.md
Changelog for Gateway 3.1.1.2.
https://konghq.atlassian.net/browse/DOCU-2891
After merging this PR, also merge:
- https://github.com/Kong/docs.konghq.com/pull/5038
- https://github.com/Kong/docs.konghq.com/pull/5032
Netlify link: https://deploy-preview-5048--kongdocs.netlify.app/gateway/changelog/
=> Release: Gateway 3.1.1.2 (changelog)

app/konnect/org-management/teams-and-roles/roles-reference.md
Added new roles to the reference based on what's currently available in product.
Netlify link:
=> Adding additional roles to the reference table

app/konnect/dev-portal/applications/enable-app-reg.md
Removing a sentence fragment left over from a previous update that went unnoticed.
Netlify link:
=> Remove stray line in app reg doc

app/konnect/api/runtime-groups-config/index.md
Fixing broken link in Konnect docs.
Netlify link:
=> Fix Konnect api link

app/_hub/kong-inc/openid-connect/_index.md
Improved readibility, clarified a few details in the plugin's description and configuration fields.
Fixed a broken link.
[KAG-402]
[KAG-402]: https://konghq.atlassian.net/browse/KAG-402?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs(openid-connect): docs improvements

app/_data/kong_versions.yml, app/gateway/changelog.md
Changelog entry for emergency fix, and document known issue for 3.1.1.2.
Netlify link:
=> Release/Gateway 3.1.1.3: Changelog and version bump

app/mesh/changelog.md
Signed-off-by: Marcin Skalski <marcin.skalski@konghq.com>
- Added changelog for Kong Mesh 2.1.0 version
Netlify link:
=> chore(docs) add Kong Mesh 2.1.0 changelog

app/_includes/md/plugins-hub/json-object-log.md, app/_includes/md/plugins-hub/log-format.md
* Order example log entry for increased readability
* Align explanation paragraph with this order
* Fix and improve description of log fields
* Added missing fields
KAG-157, KAG-158
=> docs(log): improve docs on log serialization format

app/konnect/runtime-manager/runtime-groups/index.md
Update the Gateway Object list to keep consistent with Konnect UI
Confirmed with Rick on what should be listed in the list https://kongstrong.slack.com/archives/CDSTDSG9J/p1675479606728739
Netlify link:
=> Keep consistent with current UI

app/_src/gateway/key-concepts/services.md
Removed the 3rd paragraph under "Services," because it is just a rewording of the 1st paragraph, unnecessary.
Netlify link: 
https://docs.konghq.com/gateway/latest/key-concepts/services/
=> Remove redundant Services paragraph

app/_src/gateway/kong-enterprise/dev-portal/working-with-templates.md, app/gateway/2.6.x/developer-portal/working-with-templates.md, app/gateway/2.7.x/developer-portal/working-with-templates.md, app/gateway/2.8.x/developer-portal/working-with-templates.md
Fixing a typo.
Fixes https://github.com/Kong/docs.konghq.com/issues/5132.
Netlify link:
=> Fix typo in dev portal doc

app/_src/gateway/plugin-development/custom-logic.md
Corrected hyperlink and added proxy-cache plugin in the list
=> Corrected hyperlink and added proxy-cache plugin

.github/styles/kongplugins/plugin-ignore.txt, app/_hub/kong-inc/openid-connect/_index.md
Documentation for https://github.com/Kong/kong-ee/pull/4395 / [KAG-234](https://konghq.atlassian.net/browse/KAG-234)
[KAG-234]: https://konghq.atlassian.net/browse/KAG-234?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs(openid-connect): session library v4.0.0

.github/styles/kongplugins/plugin-ignore.txt, app/_hub/kong-inc/session/_index.md, app/_src/gateway/kong-enterprise/dev-portal/authentication/sessions.md, app/_src/gateway/kong-manager/auth/sessions.md
Documentation for https://github.com/Kong/kong/pull/10199 / [KAG-549](https://konghq.atlassian.net/browse/KAG-549)
[KAG-549]: https://konghq.atlassian.net/browse/KAG-549?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs(session-plugin): docs for session library v4

app/_hub/kong-inc/session/_index.md
The current link of multiple authentication redirect to a not found page, so this change updates the link to point always to the correct page.
Netlify link:
=> Fix multiple authentication broken link

.github/styles/kongplugins/plugin-ignore.txt, app/_hub/kong-inc/key-auth/_index.md
requesting copy-edit for
* logical circuits
* anonymous consumer
* decision table for common scenarios
https://konghq.atlassian.net/browse/KAG-397
https://deploy-preview-5140--kongdocs.netlify.app/
=> plugins(key-auth): various improvements

.github/workflows/ci-autofix.yml, .prettierignore
Cherry pick [this commit](https://github.com/Kong/docs.konghq.com/pull/5098/commits/7b1aa7f3deba2d2010268ffbc4fce9010426f2a0) to make prettier happy.
Netlify link:
=> Cherry-pick: Fix prettier error

app/_src/gateway/production/deployment-topologies/db-less-and-declarative-config.md, app/_src/gateway/production/deployment-topologies/hybrid-mode/index.md, app/_src/gateway/production/deployment-topologies/index.md
=> quick fixes

app/_data/docs_nav_gateway_3.2.x.yml, app/_src/gateway/admin-api/index.md, app/konnect/api/runtime-groups-config/index.md
* Updates autodocs for admin API and Konnect core entities 
https://konghq.atlassian.net/browse/DOCU-2961
=> [docu-2961] Update autodocs 

.github/styles/kongplugins/plugin-ignore.txt, app/_hub/kong-inc/session/_index.md, app/gateway/changelog.md
Adding missing entries reported in https://kongstrong.slack.com/archives/CDSTDSG9J/p1676420018990379.
Other edits (supposed to go into the main changelog PR, but I forgot to push my commits before it got merged):
* Fixing indent in Session plugin changelog, currently it breaks formatting completely
* Removing mention of plugin support in FIPS builds from 3.1 changelog
* Links to plugin changelogs for specific param changes. The lists are massive and don't really belong in a central changelog.
Netlify link: 
https://deploy-preview-5167--kongdocs.netlify.app/gateway/changelog/
https://deploy-preview-5167--kongdocs.netlify.app/hub/kong-inc/session/#changelog
=> 3.2 changelog edits + missing entries

app/_src/gateway/install/helm-quickstart.md, app/_src/gateway/install/kubernetes/helm-quickstart.md, app/_src/gateway/install/kubernetes/helm.md, app/_src/gateway/install/kubernetes/openshift.md, app/_src/gateway/kong-enterprise/dev-portal/authentication/basic-auth.md, app/_src/gateway/kong-enterprise/dev-portal/authentication/sessions.md, app/_src/gateway/kong-manager/auth/basic.md, app/_src/gateway/kong-manager/auth/index.md, app/_src/gateway/kong-manager/auth/ldap/configure.md, app/_src/gateway/kong-manager/auth/ldap/service-directory-mapping.md, app/_src/gateway/kong-manager/auth/oidc/configure.md, app/_src/gateway/kong-manager/auth/sessions.md, app/_src/gateway/production/access-control/start-securely.md, app/_src/gateway/production/networking/dns-considerations.md, app/_src/gateway/upgrade-31x.md
Upgrade guide:
* Added all the breaking changes from the changelog
* Tables and upgrade guidance for the sessions library upgrade
* The upgrade table sort of combined 3.1 and 3.2 paths, so I split those out into their own tables
* Used variables for versions whenever possible
Other topics:
* Searched through all of our docs for any mention of the deprecated parameters and updated them to the new ones
https://konghq.atlassian.net/browse/DOCU-2989
Main changes: https://deploy-preview-5181--kongdocs.netlify.app/gateway/latest/upgrade/
Some of the updated topics with new params:
https://deploy-preview-5181--kongdocs.netlify.app/gateway/latest/install/kubernetes/helm-quickstart/
https://deploy-preview-5181--kongdocs.netlify.app/gateway/latest/install/kubernetes/openshift/ …
=> [DOCU-2989] Upgrade guidance + sessions parameter cleanup

app/_src/gateway/install/helm-quickstart.md, app/_src/gateway/install/kubernetes/helm-quickstart.md, app/_src/gateway/install/kubernetes/helm.md, app/_src/gateway/install/kubernetes/openshift.md, app/_src/gateway/kong-enterprise/dev-portal/authentication/basic-auth.md, app/_src/gateway/kong-enterprise/dev-portal/authentication/sessions.md, app/_src/gateway/kong-manager/auth/basic.md, app/_src/gateway/kong-manager/auth/index.md, app/_src/gateway/kong-manager/auth/ldap/configure.md, app/_src/gateway/kong-manager/auth/ldap/service-directory-mapping.md, app/_src/gateway/kong-manager/auth/oidc/configure.md, app/_src/gateway/kong-manager/auth/sessions.md, app/_src/gateway/production/access-control/start-securely.md, app/_src/gateway/production/networking/dns-considerations.md, app/_src/gateway/upgrade-31x.md
Reverts Kong/docs.konghq.com#5181
Wasn't ready to be merged.
=> Revert "[DOCU-2989] Upgrade guidance + sessions parameter cleanup"

.github/styles/kong/dictionary.txt, app/mesh/changelog.md
Changelog for new patch versions of Kong Mesh
Netlify link:
=> changelog for new mesh versions

app/gateway/changelog.md
Adding notice of 3.2 rollback to changelog
=> 3.2 rollback notice to changelog

app/_data/docs_nav_gateway_3.2.x.yml, app/_redirects, app/moved_urls.yml
Support policy page was renamed from `support-policy.md` to `support/index.md`, which changed the URL to `/support/`. Using the new page as the source, but making it so that we still keep the old `/support-policy/` URL and don't break links.
As part of the support policy rework, two other URLs were removed: OS support and install support. Added them to moved URLs; not sure if they'll work how I want them to, so will need to test in preview.
Netlify link:
=> Support policy URL

app/_data/tables/plugin_index.yml, app/_data/tables/version_errors_konnect.yml, app/konnect/compatibility.md
* Adds 3.2 to supported versions
* Updates compatibility table
* Fixes an existing malformed url
Checked for: 
* Trailing ticks/commas
* Missing ticks around field/entity/resource names
* Broken links
* Casing and spacing in url tags
* Max length for description and resolution at 80 chars (does not include indents)
Netlify link: https://deploy-preview-5163--kongdocs.netlify.app/konnect/runtime-manager/troubleshoot/
=> add 3.2 version, compatibility table updates

app/konnect/runtime-manager/runtime-instances/index.md
- Added information to the page about using CP/DP with a forward-proxy that is non-transparent.
DOCU-2967
Netlify link:
=> [DOCU-2967] Share CP/DP proxy 3.1 content into Konnect

app/_includes/md/plugins-hub/json-object-log.md
Make the descriptions of latencies in file-log/http-log/tcp-log/udp-log plugins more clear
FTI-4835
=> modify the description of latencies for logging plugins

app/konnect/org-management/audit-logging/webhook.md
Based on feedback from early adopter who misconfigured their authorization header, include the authentication type in the sample request.
Netlify link:
=> docs(audit-logs): update example for webhook config

app/_data/docs_nav_konnect.yml, app/konnect/org-management/auth.md, app/konnect/org-management/sessions-reference.md
Added login session duration info to Konnect auth overview page. _Should this be in a reference topic instead?_
https://konghq.atlassian.net/browse/DOCU-2518
Netlify link:
=> [DOCU-2518] Konnect login session duration

app/_includes/md/personal-access-token.md, app/_src/deck/guides/konnect.md
Document system account tokens in decK guides.
Had to split out the include, since we can't use version conditionals in the Konnect docs, but they're needed for decK docs.
Ticket: https://konghq.atlassian.net/browse/DOCU-2838; expanding on info in https://github.com/Kong/docs.konghq.com/pull/4999.  
❗ Merge only when https://github.com/Kong/docs.konghq.com/pull/4999 is merged.
Netlify link:
=> Using system account PATs with decK

app/_data/kong_versions.yml, app/gateway/changelog.md, app/konnect/compatibility.md
Bumping version to 3.2.1.
Opening so that anyone can add changelog entries as needed.
* changelog: https://deploy-preview-5204--kongdocs.netlify.app/gateway/changelog/
* check that docs are using correct version in variables: https://deploy-preview-5204--kongdocs.netlify.app/gateway/latest/install/docker/
* konnect compat: https://deploy-preview-5204--kongdocs.netlify.app/konnect/compatibility/
=> 3.2 changelog + metadata

app/_hub/kong-inc/opentelemetry/_index.md, app/_includes/hub-examples.html
Fix opentelemetry plugin doc example for "headers" parameter with declarative file.
https://github.com/Kong/kong/issues/10357
Netlify link:
=> Fix opentelemetry plugin configuration example

app/konnect/updates.md
Created the changelog for Konnect Feb 2023.
n/a
Netlify link:
=> Konnect Feb 2023 Changelog

app/_assets/javascripts/app.js, app/_includes/hub_cards.html, app/hub/index.html
[Jira ticket](https://konghq.atlassian.net/browse/DOCU-3001)
Filter plugins based on the anchor and update the filters accordingly.
[All plugins](https://deploy-preview-5206--kongdocs.netlify.app/hub/)
[Konnect plugins](https://deploy-preview-5206--kongdocs.netlify.app/hub/#konnect)
[Third party](https://deploy-preview-5206--kongdocs.netlify.app/hub/#pub-not-konghq)
=> Update url when filtering plugins

app/_includes/md/kic/deploy-kic.md, app/_includes/md/kic/kong-enterprise-license-secret.md, app/_src/kubernetes-ingress-controller/deployment/aks.md, app/_src/kubernetes-ingress-controller/deployment/eks.md, app/_src/kubernetes-ingress-controller/deployment/gke.md, app/_src/kubernetes-ingress-controller/deployment/k4k8s-enterprise.md, app/_src/kubernetes-ingress-controller/deployment/kong-enterprise.md, app/_src/kubernetes-ingress-controller/deployment/minikube.md, app/_src/kubernetes-ingress-controller/guides/cert-manager.md, app/_src/kubernetes-ingress-controller/guides/using-gateway-discovery.md
Extract some bits of KIC related docs to includes and fix some minor issue for 2.9 release.
Netlify link:
=> chore(kic): extract common docs to includes

app/konnect/getting-started/configure-runtime.md
Updated Docker install steps to resolve #4452 .
https://konghq.atlassian.net/browse/DOCU-2526
Netlify link:
=> [DOCU-2526] Removed outdated steps from Konnect Docker install

app/_hub/kong-inc/mocking/_index.md
=> chore(mocking): clarify support for Swagger 2.0 and OpenAPI 3.0

app/_data/docs_nav_mesh_2.1.x.yml
Update Kuma submodule to latest master
Netlify link:
=> Update Kuma submodule

app/_src/gateway/admin-api/index.md
Updated the upstreams health api schema api example. As described in https://github.com/Kong/kong/issues/6662, the provided examples were out of date. 
Netlify link:
=> fix(upstreams): health api schema

app/_hub/kong-inc/jwt/_index.md
=> fix routes endpoint in jwt plugin

app/gateway/changelog.md
https://konghq.atlassian.net/browse/DOCU-3047
Netlify link:
=> 3.2.2.0 Changelog

app/konnect/org-management/system-accounts.md
Update the system accounts documentation to mention the UI.
Navigate to https://cloud.konghq.com/global/organization/system-accounts in Konnect to create and manage system account entities.
Netlify link:
=> Add system accounts UI description.

app/_src/kubernetes-ingress-controller/troubleshooting.md, app/kubernetes-ingress-controller/1.0.x/troubleshooting.md, app/kubernetes-ingress-controller/1.1.x/troubleshooting.md, app/kubernetes-ingress-controller/1.2.x/troubleshooting.md, app/kubernetes-ingress-controller/1.3.x/troubleshooting.md, app/kubernetes-ingress-controller/2.0.x/troubleshooting.md, app/kubernetes-ingress-controller/2.1.x/troubleshooting.md, app/kubernetes-ingress-controller/2.2.x/troubleshooting.md
This PR aims to fix KIC's dead links which came up in https://github.com/Kong/docs.konghq.com/pull/5241
Netlify link:
=> chore(kic): fix dead links

app/_assets/stylesheets/base.less, app/_assets/stylesheets/header-v2.less, app/_includes/nav-v2.html
Issue: Search bar shrinks too much on smaller screens so you can't see that you're typing. This happens on a fairly standard resolution, so it happens to a large subset of users.
Fixing:
* Better spacing in navbar
* Match demo/free trial button styles to konghq.com
* Min width on search bar so it never gets too small
Before:
After:
Test on any page except the docs site landing page, eg https://deploy-preview-5297--kongdocs.netlify.app/gateway/latest/.
If you have a large monitor/high resolution, resize the page to see the limit of the search bar size.
=> Fix navbar spacing issues

app/_data/kong_versions.yml, app/_src/deck/reference/deck_dump.md, app/_src/deck/reference/deck_reset.md, app/_src/deck/reference/deck_sync.md
* Bumped decK version
* entries for `--skip-consumers` now mention that it also skips consumer groups.
Netlify link:
=> Release: decK 1.19.1

app/_includes/md/plugins-hub/json-object-log.md, app/_includes/md/plugins-hub/log-format.md
This PR adds workspace name in the logging payload.
(https://konghq.atlassian.net/browse/FTI-4728)
Netlify link:
=> feat(logging): add workspace name in the logging payload

app/_data/docs_nav_mesh_2.2.x.yml
Kuma community section to mesh 2.2
=> [Mesh] add community section to 2.2.x

app/gateway/changelog.md
Changelog for Gateway 3.2.2.0, re-releasing.
https://konghq.atlassian.net/browse/DOCU-3047
❗ @acgoldsmith  to merge.
Netlify link:
=> [DOCU-3047] Release: Gateway 3.2.2.0

app/_data/docs_nav_mesh_2.1.x.yml, app/_data/docs_nav_mesh_2.2.x.yml
This PR merges into release/mesh-2.2
=> Mesh update intro 

app/_data/docs_nav_konnect.yml, app/konnect/org-management/audit-logging/reference.md
* Consolidate common fields.
* Add section about access logs.
* Add section about log format.
=> feat(kaudit): Add info about log messages

app/_src/deck/reference/deck.md
=> fix deck > konnect link

app/_hub/imperva/imp-appsec-connector/_index.md
Imperva plugin name, because it was unclear.
Netlify link: 
@lena-larionova
=> Fix Imperva plug-in name to be more clear.

app/konnect/api/portal-auth/portal-rbac-guide.md
Based on feedback from our field team (Kong private slack: https://kongstrong.slack.com/archives/C04RXLGNB6K/p1680288258157369), there were opportunities to improve our Portal RBAC documentation. 
Netlify link:
=> Make improvements to Portal RBAC docs
