app/_data/kong_versions.yml
@reviewer
Updating latest real version of Kong Gateway (Enterprise) 2.3.
This version is used for installation docs.
Check that installation docs are using the new version, eg: https://deploy-preview-2765--kongdocs.netlify.app/enterprise/2.3.x/deployment/installation/ubuntu/
=> Update EE metadata to latest patch version

app/_hub/optum/kong-response-size-limiting/index.md
response size limiting remove unsupported versions. supported versions are very out of date. need to review with PM and partners.
=> Optum 3rd party plugin

app/_hub/optum/kong-splunk-log/index.md
remove incompatible versions. This list if accurate would get very long.
=> Splunk 3rd party plugin

app/_hub/okta/okta/index.md
Remove cluttering incompatible versions. The versions listed for EE are no longer supported. Need to review and discuss with @eskibars what Enterprise versions are currently supported.
=> Okta integration remove incompatible versions

Dockerfile, Makefile
Simplifying the Dockerfile and Makefile.
Doc site build process is long. This removes some extra steps and should hopefully make it a bit more efficient.
Thanks @gszr for contributing this change!
Watch the checks, make sure they work, and hope that they're shorter.
=> (no ticket, fix) Simplify Dockerfile and Makefile

Dockerfile, app/_data/kong_versions.yml
Updating decK version in doc metadata.
New version of decK released yesterday: https://github.com/kong/deck/releases
TBA
=> Update decK version to 1.6.0 and adjust dockerfile with build fix

app/gateway-oss/2.4.x/hybrid-mode.md
Add some ops-related info to Hybrid Mode docs:
- DP startup and where does it look for configuration
- Disconnected mode (the DP while CP is down) and how to provision/reconfig without CP
=> docs(hybrid)  DP config startup and disconnected mode

app/enterprise/2.3.x/property-reference.md
Docs team - added some definitions for the different tracing types. I only added this one section to doc as some of the other updates to this file will be for the 2.4 release. This update is just to make the content better.
Added some definitions to the different tracing types included when using granular tracing, an enterprise feature.
[DOCU-1083](https://konghq.atlassian.net/browse/DOCU-1083)
[Granular tracing - tracing_types](https://deploy-preview-2771--kongdocs.netlify.app/enterprise/2.3.x/property-reference/#tracing_types)
=> [DOCU-1083] updated property reference with granular tracing trace types definitions

app/_hub/kong-inc/ldap-auth-advanced/index.md
The LDAP Advanced plugin does not support the ability to authorize based on groups, instead the plugin gives the ability to obtain LDAP groups and set them in a header to the request before proxying to the upstream which is useful for the Kong Manager role mapping, for example.
=> docs(ldap-auth-advanced) fix EE-only feature (groups) description

app/gateway-oss/2.4.x/proxy.md
behavior. add description of URI normalization methods used by the router.
=> docs(gateway/proxy) add more detailed description of the regex matching

app/_hub/kong-inc/ldap-auth-advanced/index.md
Referrals are not supported in the plugin. One way to work around this is
to hit the LDAP Global Catalog instead, which is usually listenning on a
different port than the default `389`. This way, referrals don't get sent
back to the plugin.
The plugin doesn’t authenticate users (allow/deny requests) based on group
membership. For example:
- if the user is member of an LDAP group, the request will be allowed -> 200 OK
- if the user is _not_ member of a group, the request will still be allowed -> 200 OK
@reviewer
=> docs(ldap-auth-advanced) add more notes

app/getting-started-guide/2.4.x/dev-portal.md
@reviewer
Updating a link.
Link got missed in 2.4.x version of the getting started guide, as it was on a different branch when the links were updated as a whole.
=> Fixing missed dev portal link

app/_data/docs_nav_gsg_2.4.x.yml
@reviewer
Adding missing nav file for the 2.4.x version of the getting started guide.
Nav is missing.
https://deploy-preview-2789--kongdocs.netlify.app/getting-started-guide/2.4.x/overview/
=> Add missing nav file

app/enterprise/changelog.md
Combined both [CE 2.4.0.0 changelog](https://github.com/Kong/kong/blob/2.4.0-rc.1/CHANGELOG.md#240-rc1) and [EE - changelog](https://konghq.atlassian.net/wiki/spaces/FTT/pages/8356124/Kong+Enterprise+-+Changelog+Features+Release+Schedule#KongEnterprise-Changelog%2CFeatures%26ReleaseSchedule-KongEnterprise2.4.0.0Beta) for the 2.4.0 beta release.
[Google doc with original CE 2.4 beta changelog questions](https://docs.google.com/document/d/1wH08qMpYgzUWGyfn1Fyk1s9m_53sB423D1o79WqAQ0Q/edit)
[DOCU-1401](https://konghq.atlassian.net/browse/DOCU-1401)
Because we are releasing a 2.4.0.0 beta and want to inform users of the updates.
[2.4.0.0-beta changelog](https://deploy-preview-2786--kongdocs.netlify.app/enterprise/changelog/#2400-beta)
=> [DOCU-1401] Adds 2.4.0.0 beta change log entry

app/_includes/md/mesh/install-universal-run.md, app/mesh/1.0.x/installation/amazonlinux.md, app/mesh/1.0.x/installation/centos.md, app/mesh/1.0.x/installation/debian.md, app/mesh/1.0.x/installation/kubernetes.md, app/mesh/1.0.x/installation/macos.md, app/mesh/1.0.x/installation/openshift.md, app/mesh/1.0.x/installation/redhat.md, app/mesh/1.0.x/installation/ubuntu.md
@reviewer
Call Mesh version consistently in Mesh install docs
Stray odd call to version variable was creating inconsistent version numbers in Mesh install docs, leading to user confusion
will post Netlify preview when it's ready
=> fix version variable for mesh

app/enterprise/2.3.x/property-reference.md
Added doc for the new header option added to the 2.3.3.1 patch.
Now users can add a custom header and footer to Kong Manager that will persist past the login screen.
[DOCU-1141](https://konghq.atlassian.net/browse/DOCU-1141)
[FTI-1585](https://konghq.atlassian.net/browse/FTI-1585)
Will add sample site link when available.
=> [DOCU-1141]Docs/autodoc conf ee 2.3.x

app/_data/kong_versions.yml, app/mesh/changelog.md
@reviewer
Mesh release 1.2.3 (all new features are in Kuma)
Release
https://6079ce9e640812000773fab4--kongdocs.netlify.app/mesh/changelog/
https://6079ce9e640812000773fab4--kongdocs.netlify.app/mesh/1.2.x/installation/openshift/ (check version number in commands for any arbitrary install platform)
=> mesh 1.2.3 release

app/_data/extensions/kong-inc/request-transformer/versions.yml, app/_hub/kong-inc/request-transformer/0.1-x.md, app/_hub/kong-inc/request-transformer/1.2.x.md, app/_hub/kong-inc/request-transformer/index.md
https://konghq.atlassian.net/browse/DOCU-681 add datatypes
https://konghq.atlassian.net/browse/DOCU-158 remove vestige from when there was differentiation between the open source and enterprise plugins. It's confusing and doesn't add value. The EE Request Transformer Advanced plugin is slated for  future deprecation per @eskibars since its functionality was ported to this OSS CE plugin and there is no longer a discernible difference.
Schema:
https://github.com/Kong/kong-plugin-request-transformer/blob/master/kong/plugins/request-transformer/schema.lua
https://deploy-preview-2766--kongdocs.netlify.app/hub/kong-inc/request-transformer/
=> [DOCU-681][DOCU-158] Request Transformer plugin datatypes, formatting, editing, versioning

app/konnect/runtime-manager/gateway-runtime-kubernetes.md
Change variable to hardcoded version, as the latest version doesn't work with Konnect.
There's a breaking change with the OIDC plugin that breaks compatibility with 2.3.3.x
https://deploy-preview-2797--kongdocs.netlify.app/konnect/runtime-manager/gateway-runtime-kubernetes/#write-and-apply-configuration - see codeblock
=> (no ticket) Change gateway version in konnect helm config

app/_data/kong_versions.yml, app/mesh/changelog.md
@reviewer
Update version number, add changelog entry for Mesh 1.2.4
New release
https://deploy-preview-2800--kongdocs.netlify.app/mesh/changelog/
https://deploy-preview-2800--kongdocs.netlify.app/mesh/1.2.x/installation/kubernetes/ or any install page (check for correct version number, 1.2.4)
=> release Mesh version 1.2.4

app/gateway-oss/2.4.x/index.md
See slack convos https://kongstrong.slack.com/archives/G012HLJ4GJJ/p1618919908088100
https://kongstrong.slack.com/archives/CDSTDSG9J/p1618913942118000
https://deploy-preview-2802--kongdocs.netlify.app/gateway-oss/
Tested all links on this landing page and they now work, no more 404.
=> fix old links

app/enterprise/2.3.x/deployment/installation/amazon-linux-2.md, app/enterprise/2.3.x/deployment/installation/amazon-linux.md, app/enterprise/2.3.x/deployment/installation/centos.md, app/enterprise/2.3.x/deployment/installation/docker.md, app/enterprise/2.3.x/deployment/installation/kong-for-kubernetes.md, app/enterprise/2.3.x/deployment/installation/kong-on-kubernetes.md, app/enterprise/2.3.x/deployment/installation/rhel.md, app/enterprise/2.3.x/deployment/installation/ubuntu.md
Update software license agreement links on Kong Gateway Enterprise installation pages for version 2.3.x.
@eskibars 
@HCloward 
Update links to the Kong Software License Agreement on all of the enterprise install instructions for 2.3.x. 
Request by Shane Connelly and Tom/Legal as software license was updated in 2.3, and update needed for bintray migration. 
Check new software license link on individual installation pages. 
Netlify links to:
- Ubuntu: https://deploy-preview-2804--kongdocs.netlify.app/enterprise/2.3.x/deployment/installation/ubuntu/
- CentOS: https://deploy-preview-2804--kongdocs.netlify.app/enterprise/2.3.x/deployment/installation/centos/
- Amazon-Linux: https://deploy-preview-2804--kongdocs.netlify.app/enterprise/2.3.x/deployment/installation/amazon-linux/
- …
=> [DOCU-1415] Update SW license link on EE install pages

app/enterprise/2.3.x/deployment/installation/docker.md
https://konghq.atlassian.net/browse/DOCU-1425 This fix is for 2.3.x. Will do another PR for 2.4.x on private repo where that upcoming version currently resides. 2.2.x does not have this issue. https://github.com/Kong/docs.konghq.com-private/blob/release/ee-2.4/app/enterprise/2.4.x/deployment/installation/docker.md
Checked all other applicable install topics and only Docker was off. https://docs.konghq.com/enterprise/2.3.x/deployment/installation/docker/#step-7-optional-enable-the-dev-portal
https://deploy-preview-2811--kongdocs.netlify.app/enterprise/2.3.x/deployment/installation/docker/
Thanks again @HCloward for your keen eye!
=> [DOCU-1545] Enable Dev Portal fix install instructions

app/_data/kong_versions.yml, app/enterprise/1.5.x/deployment/installation/docker.md, app/enterprise/2.1.x/deployment/installation/docker.md, app/enterprise/2.2.x/deployment/installation/docker.md, app/enterprise/2.3.x/deployment/installation/docker.md
@reviewer
Updating `docker pull` commands to point to new location. Updating 2.3.x, 2.2.x, 2.1.x, and 1.5.x, as these are the available images on Docker Hub (https://hub.docker.com/r/kong/kong-gateway).
Companion PR to https://github.com/Kong/docs.konghq.com/pull/2814.
What this PR is not updating:
- Prerequisites. These are being updated in https://github.com/Kong/docs.konghq.com/pull/2814.
- Immunity images.
- Kubernetes instructions. 
Migration from Bintray to https://hub.docker.com/r/kong/kong-gateway
Docker pull commands tested, all worked for me. 
Previews:
[2.3.x](https://deploy-preview-2815--kongdocs.netlify.app/enterprise/2.3.x/deployment/installation/docker/)
[2.2.x](https://deploy-preview-2815--kongdocs.netlify.app/enterprise/2.2.x/deployment/installation/docker/) …
=> Bintray migration: Docker updates

app/_includes/hub-examples.html
Fix syntax. 
Line breaks weren't showing up for some plugins.
Before:
(https://docs.konghq.com/hub/kong-inc/response-transformer/, declarative (YAML) tab)
Check the declarative YAML tab in plugin docs, eg: https://deploy-preview-2818--kongdocs.netlify.app/hub/kong-inc/response-transformer/
=> [DOCU-1434] Fix declarative config example syntax

app/_includes/footer.html
Interim fix for link. Will be a bigger site-wide change in the future.
Had to remove tracking query portion of URL, as it doesn't seem to work with anchors (`#`).
Currently, the OSS doc is going to Konnect demo, which isn't a great user experience.
TBA
=> [DOCU-1429] Fix footer link to oss gateway

app/_data/kong_versions.yml, app/mesh/changelog.md
@subnetmarco 
Update changelog and version number for Mesh (built on Kuma 1.1.5, also just released)
Support release
https://deploy-preview-2829--kongdocs.netlify.app/mesh/1.2.x/install/
https://deploy-preview-2829--kongdocs.netlify.app/mesh/changelog/
=> mesh release 1.2.5 (kuma 1.1.5)

app/gateway-oss/2.4.x/plugin-development/custom-logic.md
This part of the guide was out of date (BasePlugin has been deprecated for several versions of Kong now).
=> docs(2.4) remove deprecated BasePlugin from Plugin Development guide

app/konnect/updates.md
Pointing out one more known issue with generated kubernetes yaml in the Konnect SaaS GUI.
No ticket, issue pointed out on slack.
https://deploy-preview-2836--kongdocs.netlify.app/konnect/updates/#20210507
=> Konnect: known issue for k8s tab in runtime manager

app/_hub/kong-inc/http-log/index.md
https://konghq.atlassian.net/browse/DOCU-1476 correction as noted by Fel and others in slack
https://deploy-preview-2839--kongdocs.netlify.app/hub/kong-inc/http-log/#custom-headers
Reviewers: also not sure why there are double angle brackets around the token placeholder? removed a set.
=> [DOCU-1476] HTTP log plugin custom header code block 

app/_data/kong_versions.yml, app/mesh/1.2.x/features/vault.md, app/mesh/changelog.md
@subnetmarco @lena-larionova 
Add Mesh 1.2.6 release version, changelog. Include hopefully fixes to markdown for intermediate CA with Vault docs.
Release day!
https://deploy-preview-2845--kongdocs.netlify.app/mesh/1.2.x/features/vault/ and any mesh install page (for version number checking), e.g. https://deploy-preview-2845--kongdocs.netlify.app/mesh/1.2.x/installation/kubernetes/
=> update docs for release, include new docs for intermediate CA with Vault

app/konnect/runtime-manager/gateway-runtime-conf.md
Fixing a small typo that points to the wrong file. Other runtime setup topics refer to the correct files.
Broken setup.
=> Konnect linux runtime setup typo

app/_hub/kong-inc/kafka-log/index.md
https://konghq.atlassian.net/browse/DOCU-912 Remove unnecessary install section (already removed from Kafka Upstream plugin). Also removed dupe global topic.
The more I look at this doc, the more room for improvements I see. Will log follow-up ticket. https://konghq.atlassian.net/browse/DOCU-1483
https://deploy-preview-2848--kongdocs.netlify.app/hub/kong-inc/kafka-log/
=> [DOCU-912] Kafka Log plugin remove install section

app/_hub/kong-inc/kafka-log/index.md
https://konghq.atlassian.net/browse/DOCU-1483
Instead of odd UPPERCASE placeholders, replaced with default values in examples.
Before:
After:
=> [DOCU-1483] kakfa log plugin cleanup cont

app/_hub/kong-inc/request-transformer-advanced/index.md
https://konghq.atlassian.net/browse/DOCU-677 Add datatypes. Copied over from open source plugin, which is virtually identical save for one field (allow.body). This plugin will not be deprecated in the near future, but perhaps when the JQ plugin is released. See Shane's comments in the ticket.
Schema link:
https://github.com/Kong/kong-plugin-enterprise-request-transformer/blob/master/kong/plugins/request-transformer-advanced/schema.lua
https://deploy-preview-2852--kongdocs.netlify.app/hub/kong-inc/request-transformer-advanced/
=> [DOCU-677] Request Transformer Advanced plugin port datatypes /examples from corresponding OSS plugin

app/gateway-oss/2.4.x/plugin-development/custom-logic.md
Per @bungle with PR [#6873](https://github.com/Kong/kong/pull/6873) the `ssl_certificate` phase on plugins has been added to the Stream module - therefore it should be added to the table in this doc.
Will open a separate PR to add this update to the Enterprise docs.
[Plugin development guide > Implementing custom logic > Available contexts > Stream module](https://deploy-preview-2856--kongdocs.netlify.app/gateway-oss/2.4.x/plugin-development/custom-logic/#available-contexts)
=> Adds the certificate function to the stream module table

app/_hub/kong-inc/opa/index.md
https://konghq.atlassian.net/browse/DOCU-1407
The compatible with version in the sidebar does not display the version until release time. That note and beta tag removed for GA.
Direct review link: 
https://deploy-preview-2823--kongdocs.netlify.app/hub/kong-inc/opa/
=> [DOC-1407] OPA plugin remove beta tag, version note for GA (merge for 2.4 EE GA)

app/_hub/kong-inc/aws-lambda/index.md
https://konghq.atlassian.net/browse/DOCU-671 part of epic https://konghq.atlassian.net/browse/DOCU-301
Schema link:
https://github.com/Kong/kong-plugin-aws-lambda/blob/master/kong/plugins/aws-lambda/schema.lua
https://deploy-preview-2869--kongdocs.netlify.app/hub/kong-inc/aws-lambda/
This PR also adds a new config recently whose doc was missed in release 2.2.0 per changlog https://github.com/Kong/kong/blob/master/CHANGELOG.md#220:
Not bumping version since it's still 3.5.4 per the handler
=> [DOCU-671] AWS Lambda plugin datatypes

app/_hub/index.html, app/_hub/kong-inc/request-transformer-advanced/index.md, app/_hub/kong-inc/request-transformer/index.md, app/_hub/kong-inc/response-transformer-advanced/index.md
* Removing response transformer advanced, request transformer, and request transformer advanced from Konnect Plus filter.
* Slight edit to filter text, as it was reported that users are assuming "Plus (SaaS only)" means that the plugins are available in SaaS only, not the other way around.
* Had to remove OSS filter as it was confusing people - had multiple people reach out to ask why we had both Free and OSS categories if they're the same.
Plugins didn't make it into Konnect Plus.
Check that response transformer advanced, request transformer, and request transformer advanced are greyed out when you click the "Plus" filter: https://deploy-preview-2855--kongdocs.netlify.app/hub
=> [DOCU-1491] Remove unsupported plugins from Plus filter

app/konnect/getting-started/configure-runtime.md, app/konnect/runtime-manager/gateway-runtime-conf.md, app/konnect/runtime-manager/gateway-runtime-docker.md, app/konnect/runtime-manager/gateway-runtime-kubernetes.md
@mikefero 
* Add PowerShell option for Docker install
* Update and fix up runtime prerequisites
* Point to advanced setup for windows users from quickstart guide, since the script won't work for them
Reviewers: I don't love having to point the users from the docker setup instructions to one of the other UI tabs, but there's no good way to grab the info they need otherwise.
https://konghq.atlassian.net/browse/DOCU-1477
Customer ran into issues with trying to run the Docker script on Windows, and there were no advanced instructions to back them up when it failed.
Mainly here: https://deploy-preview-2854--kongdocs.netlify.app/konnect/runtime-manager/gateway-runtime-docker/
Minor changes made to:
https://deploy-preview-2854--kongdocs.netlify.app/konnect/runtime-manager/gateway-runtime-kubernet …
=> [DOCU-1477] Runtime manager: Windows instructions for Docker

app/_includes/md/enterprise/download/centos.md, app/enterprise/2.4.x/deployment/installation/centos.md
@eskibars discovered that the centos 6 OS was not available for download even though the docs say it is so it should be removed from docs as an option.
* [Install Kong Gateway on Centos OS - 2.4.x](https://deploy-preview-2878--kongdocs.netlify.app/enterprise/2.4.x/deployment/installation/centos/)
* [Install Kong Gateway on Centos OS - 2.3.x](https://deploy-preview-2878--kongdocs.netlify.app/enterprise/2.3.x/deployment/installation/centos/)
* [Install Kong Gateway on Centos OS - 2.2.x](https://deploy-preview-2878--kongdocs.netlify.app/enterprise/2.2.x/deployment/installation/centos/)
* [Install Kong Gateway on Centos OS - 2.1.x](https://deploy-preview-2878--kongdocs.netlify.app/enterprise/2.1.x/deployment/installation/centos/)
* [Install Kong Gateway on Centos OS - …
=> [DOCU-1504]Removes centos 6 from available download options

app/enterprise/changelog.md
After we released 2.4.1.0, it was determined that the mtls-auth plugin is incompatible. Since this is a known issue, we should include it in the changelog to inform users.
[DOCU-1511](https://konghq.atlassian.net/browse/DOCU-1511)
[FTI-2551](https://konghq.atlassian.net/browse/FTI-2551)
[2.4.1.0 changelog](https://deploy-preview-2877--kongdocs.netlify.app/enterprise/changelog/#known-issues)
=> [DOCU-1511]Updates 2.4.1.0 Enterprise changelog with mtls-auth plugin issue

app/_layouts/extension.html
@tlblessing 
Enabling the image modal feature for the plugin docs.
Request from @tlblessing. Need to be able to see detail in screenshots.
Tested locally with Mocking plugin.
Netlify TBA
=> Add image modal to plugins

app/enterprise/1.3-x/kong-for-kubernetes/install.md, app/enterprise/1.5.x/introduction.md, app/enterprise/2.1.x/introduction.md, app/enterprise/2.2.x/introduction/index.md, app/enterprise/2.3.x/index.md, app/enterprise/2.4.x/index.md
* Fixing broken external links to kubernetes labs
* Adding links to Konnect registration
* Adding links to download Kong Gateway for free - only to 2.3.x and 2.4.x, since the feature was only introduced recently.
Broken link reported by Aghi, and I noticed that we don't link to Konnect Plus as well. 
https://deploy-preview-2888--kongdocs.netlify.app/enterprise/#try-kong-gateway-enterprise - 2.4 and 2.3 are the same
https://deploy-preview-2888--kongdocs.netlify.app/enterprise/2.2.x/introduction/#try-kong-gateway-enterprise - 2.2.x and earlier don't mention free mode, but still link to Konnect
=> Fix "Try Kong Gateway" section in docs intro

app/robots.txt
This fix removes old versions of Kong documentation from search
results.
Follows Google Robot Spec https://developers.google.com/search/docs/advanced/robots/robots_txt
Issue 2890
https://support.google.com/webmasters/answer/6062598?hl=en
=> fix/(robots.txt) Add Disallow statements

app/enterprise/changelog.md
@mikefero Please take a look for accuracy - thanks!
The 2.4.1.0 release had some issues with the mTLS plugin and Konnect. The 2.4.1.1 patch release fixes those issues.
EE changelog needs entry for 2.4.1.1 patch release.
Will add sample build link when available.
=> [DOCU-1512]Adds 2.4.1.1 release notes to the ee changelog

app/robots.txt
Adding KIC 1.2 doc to robots.txt to stop it from being indexed by search engines.
KIC 1.3 was released, and we want to drive search traffic there.
N/A
=> Add old version of KIC to robots.txt

app/kubernetes-ingress-controller/1.0.x/concepts/custom-resources.md, app/kubernetes-ingress-controller/1.0.x/references/custom-resources.md, app/kubernetes-ingress-controller/1.1.x/concepts/custom-resources.md, app/kubernetes-ingress-controller/1.1.x/references/custom-resources.md, app/kubernetes-ingress-controller/1.2.x/concepts/custom-resources.md, app/kubernetes-ingress-controller/1.2.x/references/custom-resources.md, app/kubernetes-ingress-controller/1.3.x/concepts/custom-resources.md, app/kubernetes-ingress-controller/1.3.x/concepts/design.md, app/kubernetes-ingress-controller/1.3.x/concepts/ingress-classes.md, app/kubernetes-ingress-controller/1.3.x/concepts/ingress-versions.md, app/kubernetes-ingress-controller/1.3.x/guides/configuring-health-checks.md, app/kubernetes-ingress-controller/1.3.x/guides/preserve-client-ip.md, app/kubernetes-ingress-controller/1.3.x/references/annotations.md, app/kubernetes-ingress-controller/1.3.x/references/custom-resources.md, app/kubernetes-ingress-controller/1.3.x/references/plugin-compatibility.md
Fixing links in KIC docs.
KIC 1.3 didn't pick up changes made in 1.2, and I missed that while reviewing. Fixing links that were previously fixed in 1.2, plus a few more to avoid unnecessary redirects.
Caught by weekly GH action: https://github.com/Kong/docs.konghq.com/runs/2706638290?check_suite_focus=true
Tested by running the link checker locally, no broken links.
=> Fix links in KIC docs

app/_hub/kong-inc/vault-auth/index.md
https://konghq.atlassian.net/browse/DOCU-1538 This PR turns off the autogenerated GUI examples in the plugin hub doc for Vault.
I'm not sure that we should add a note about why this plugin does not appear in any GUI. This is a current limitation in the code as noted in the slack convo pasted into the ticket. It requires some hardcoding on the part of eng. @eskibars what do you think?
https://deploy-preview-2898--kongdocs.netlify.app/hub/kong-inc/vault-auth/
The GUI tabs should no longer be present in the autogen examples.
=> [DOCU-1538] Vault plugin is not available in GUIs due to custom DAO

app/_hub/kong-inc/key-auth/index.md
this says the parameter is an array of strings, but the default value is a string (not an array with a string)
@reviewer
=> updates docs typo

app/_hub/kong-inc/request-validator/index.md
@reviewer
https://docs.konghq.com/hub/kong-inc/request-validator/
The docs for the request validator plugin shows `allowed_content_types` to be a string, but it's actually an array of strings.
here's the source code https://github.com/Kong/kong-plugin-enterprise-request-validator/blob/master/kong/plugins/request-validator/schema.lua#L97-L103
=> request-validator.config.allowed_content_types is an array

app/_includes/head.html
@reviewer
Fixing page title to ignore pages marked "no_version".
Currently, for pages with no version, the markdown file name gets filled in instead. You can see this issue with unversioned docs in any place that stores page metadata.
Browser tab label:
Google search results:
Open any unversioned doc and mouse over the browser tab. Check that the title in the tab label doesn't contain the markdown filename. For example:
https://deploy-preview-2916--kongdocs.netlify.app/konnect/
=> Fix version display in page title metadata

app/_redirects
Adding a 2.4 redirect.
There are still many links that lead to the old gateway OSS doc location. Cleaning them all up, especially with other gateway docs changes coming in the future, isn't feasible, so we handle them with redirects for now.
https://konghq.atlassian.net/browse/DOCU-1543
Test the redirect by going to a 2.4 page and make sure it redirects to gateway-oss/2.4: 
https://deploy-preview-2920--kongdocs.netlify.app/2.4.x/proxy/
=> [DOCU-1543] Add redirect for gateway 2.4

app/_data/docs_nav_ee_2.2.x.yml, app/_data/docs_nav_ee_2.3.x.yml, app/_data/docs_nav_ee_2.4.x.yml, app/enterprise/2.2.x/deployment/installation/overview.md, app/enterprise/2.3.x/deployment/installation/overview.md, app/enterprise/2.4.x/deployment/installation/overview.md
@reviewer
The links currently being used are pointing to a removed marketplace entry.
The current links are broken.
Validate that the links work and point to active marketplace entry.
=> Update AWS AMI links in installation docs

app/_assets/stylesheets/page.less, app/_assets/stylesheets/pages/docs.less
Adjusting site widths so that the page ToC collapses earlier and makes more room for the content. 
Setting an absolute width for the main container so that percentage widths have something to relate to and stop awkward jumpy transitions.
Lots of issues with jumpy site window resizing, and awkward section widths at smaller sizes. 
Bad:
Old/bad behavior: open [any docs page](https://docs.konghq.com/enterprise/) in full screen, then slowly resize the width of the window. Notice the sudden jump from whitespace on either side to no whitespace. Also notice how awkwardly narrow the middle column becomes before the page ToC collapses.
New/better behavior: test the same page in the netlify preview: https://deploy-preview-2921--kongdocs.netlify.app/enterprise/
=> Site width and responsiveness

app/_includes/head.html
Removing clearbit.
Doing this through Google Tag Manager instead.
=> Removing clearbit from docs

app/_hub/kong-inc/route-transformer-advanced/index.md
@HCloward 
Route Transfer Advanced plugin configurations `path`, `host`, and `port` are "semi-optional" parameters (one of them must be specified during the configuration).
https://konghq.atlassian.net/browse/DOCU-1550
=> [DOCU-1550] fix(plugin) indicate semi-optional params for EE route transformer

app/kubernetes-ingress-controller/1.3.x/guides/getting-started-istio.md
@reviewer
This PR is to update the documentation for the Getting Started using Istio guide to ensure that it functions correctly.
The following detailed changes were made:
- Updated to show second command for applying the Kubernetes manifest for `Deploy bookinfo in an Istio-enabled namespace` 
- Updated `productpage` ingress so that it would work correctly by adding:
-  `kubernetes.io/ingress.class: kong` so that kong detects service and routing works correctly
-  `EOF` at end of manifest
Documentation under [Getting Started using Istio](https://docs.konghq.com/kubernetes-ingress-controller/1.3.x/guides/getting-started-istio/) was incorrect around sample commands to be used
Run through guide and test steps as required
https://deploy-preview-2936--kongdocs.netlify.app
=> Updated getting-started-istio documentation

app/_hub/kong-inc/graphql-rate-limiting-advanced/index.md, app/_hub/kong-inc/rate-limiting-advanced/index.md, app/_hub/kong-inc/rate-limiting/index.md, app/_hub/kong-inc/response-ratelimiting/index.md, app/konnect/updates.md
@skibum 
Release notes for Konnect Cloud deploy on 06/15/21. 
* Resolving some confusion around rate limiting plugins by removing a setting that doesn't work in Konnect Cloud
* Adjusting property descriptions in plugin docs to explain what each strategy/policy is.
* "strategy" and "policy" are two different config setting names for the same thing. Two plugins use the parameter "policy", and two use "strategy", but both settings accomplish the same goal.
* These descriptions were already known, just not used in every plugin. Used part of the description from the Rate Limiting plugin and from the plugin compatibility table. 
* Set the value in examples to `local`, as that's the only setting that can work in all modes without extra configuration.
Deploy went out today. …
=> [DOCU-1556][DOCU-1558] Konnect Cloud updates for deploy on June 15

app/_data/docs_nav_kic_1.2.x.yml, app/_data/docs_nav_kic_1.3.x.yml
Fixing table of contents.
Old ToC got pulled in when the KIC docs were versioned for 1.3.
Currently, that means the ToC is all one level and not expanded: https://docs.konghq.com/kubernetes-ingress-controller/
Check that the nav for https://deploy-preview-2944--kongdocs.netlify.app/kubernetes-ingress-controller/ matches version 1.2.x.
=> Fix table of contents for kic 1.3

app/kubernetes-ingress-controller/1.3.x/guides/using-oidc-plugin.md
updated a copy-paste(?) error to show the right name of the plugin
@reviewer
fixed a copy-paste error. The output of kubectl apply was showing the wrong plugin name
=> fix typo in the OIDC setup section

README.md
Add full URL to Kong docs contributing guide. 
The current link points to a GitHub 404 page.
=> Update Contributing Guide link in README.md

app/_includes/md/enterprise/download/immunity.md
Check to be sure Immunity install docs for EE v2.1+ include a note that states v2.4.x is not compatible with Immunity.
Immunity is incompatible with EE v2.4.1.0 and v2.4.1.1 - the install docs need to indicate that it will not work with those versions until the fix is released with v2.4.1.2.
[DOCU-1553](https://konghq.atlassian.net/browse/DOCU-1553)
=> [DOCU-1553]Adds note about Immunity being incompatible with Kong Enterprise v2.4.x

app/enterprise/2.4.x/property-reference.md, autodoc-conf-ee/data.lua
I think this is the best way to update this file - not entirely sure . .. 
Li Yang noticed that the file linked to in the prop ref is only useful for OSS gateway users. After talking with Mike Fero, the ee version of the file can be found with a specific command that I included.
To make it easier for Gateway Enterprise users to find the nginx custom template.
=> [DOCU-1551]Updates autodoc for EE Prop reference with where to find the ee nginx custom template

algolia/config-full-docs.json, app/_redirects, app/robots.txt
* Redirecting unversioned decK links to /latest/
* Setting algolia config to only index the latest deck version
* Stopping pre-1.7 decK docs from being indexed by search engines
Links were all updated in the docs but unversioned links exist out in the world. Issue was reported on Slack: https://kongstrong.slack.com/archives/CDSTDSG9J/p1623879076092400
Test any of the redirects in the file to make sure they work. For example: https://deploy-preview-2945--kongdocs.netlify.app/deck/installation/
=> Fixing issues with decK links and versions

app/contributing/index.md
Fixing a link
Link wasn't displaying because of an extra newline.
reviewers: I skipped the Netlify preview initially because I was thinking I updated the README itself, but that's not at all true. You can still test the link directly on the branch though: https://github.com/Kong/docs.konghq.com/blob/docs/readme-link/app/contributing/index.md
=> Fix link to Kong/kong README [skip ci]

app/_hub/kong-inc/grpc-gateway/index.md, app/_hub/kong-inc/grpc-web/index.md
Update gRPC-gateway and gRPC-Web plug-in page URLs to include `/latest/` instead of hard-coded version. 
Hard-coded versions require manual updating. 
Local testing to ensure links go to latest docs.
=> update urls on grpc plugins

app/_assets/css/hub.css, app/_assets/stylesheets/page.less, app/_assets/stylesheets/pages/landing-page.less
Removing underlines from link hover states for accuracy.
Fixing font size in plugin search bar
Modernizing and making the styles consistent.
For plugins, there was an unnecessary global font size set on the page that was shrinking it:
Test search bar at the top of https://deploy-preview-2964--kongdocs.netlify.app/hub/, font size should be normal
Spot-check that any links you see have no underlines, for example:
https://deploy-preview-2964--kongdocs.netlify.app/hub/kong-inc/application-registration/
https://deploy-preview-2964--kongdocs.netlify.app/enterprise/changelog/
=> Design: fix plugin search bar and remove underlines

app/_assets/stylesheets/cookie-policy.less, app/_assets/stylesheets/navtabs.less
Adjusting tab display on mobile.
Tabs extend plugin pages on mobile.
https://deploy-preview-2970--kongdocs.netlify.app/getting-started-guide/2.4.x/improve-performance/ - resize the width of the page until it's below 575px to test the tabs.
=> Responsive tabs

README.md
* Add MIT and contributor badges
* Improve introduction text by adding listed key info
* Clean up run instructions for Docker, gulp, and npm
* Add section for plug-in contributors to grab a badge
* Add note that "Generate the PDK, Admin API, CLI, and Configuration documentation" section is for source code maintainers
* Help get new contributors up-and-running faster
* Reward plug-in contributors with a copy-and-paste-able badge
* Clarify any confusion about intended audience for each section
Addresses: Issues [#809](https://github.com/Kong/docs.konghq.com/issues/908) and [#1030](https://github.com/Kong/docs.konghq.com/issues/1030)
Tested locally via Atom Markdown previewer.
=> [DOCU-1570] Improve README

app/_assets/javascripts/app.js, app/_assets/stylesheets/base.less, app/_assets/stylesheets/page.less, app/_includes/md/2.4.x/docker-install-steps.md, app/enterprise/2.4.x/deployment/installation/docker.md, jekyll-dev.yml, jekyll.yml
@HCloward @falondarville 
* Adding support for editable placeholders in the documentation, inspired by [Google's implementation](https://developers.google.com/style/placeholders?hl=en).
* Removing line numbers from codeblocks: we've tested them out and found they weren't adding much value and were instead making codeblocks look busy.
* Enabling language guessing for syntax highlighting: instead of leaving codeblocks unformatted, if there is a codeblock without a language explicitly set on it, the syntax highlighter will attempt to guess the language. If it can't figure it out, it defaults to plaintext. 
Since you can't insert HTML into fenced codeblocks, you must set `pre` and `code` tags instead. To include a placeholder, use a `<div contenteditable="true">` tag. For example:
``` …
```
=> [DOCU-1544] Doc feature: Editable placeholders

app/enterprise/2.1.x/deployment/upgrades/migrations.md, app/enterprise/2.2.x/deployment/upgrades/migrations.md, app/enterprise/2.3.x/deployment/upgrades/migrations.md, app/enterprise/2.4.x/deployment/upgrades/migrations.md, app/gateway-oss/1.1.x/upgrading.md, app/gateway-oss/1.2.x/upgrading.md, app/gateway-oss/1.3.x/upgrading.md, app/gateway-oss/1.4.x/upgrading.md, app/gateway-oss/1.5.x/upgrading.md, app/gateway-oss/2.0.x/upgrading.md, app/gateway-oss/2.1.x/upgrading.md, app/gateway-oss/2.2.x/upgrading.md, app/gateway-oss/2.3.x/upgrading.md, app/gateway-oss/2.4.x/upgrading.md
Check that Patch releases section has been removed from upgrade guide for EE versions 2.1.x and higher and Migrating Databases for a Major or Minor Version Release header has been updated to Migrating Databases for Upgrades.
Yi Lang noticed some discrepancies in our migration doc that I confirmed with the Fast Track Team.
Fast Track Team say there is no reason for the Patch releases section to exist as it is inaccurate and to update the header suggesting steps are diff depending on type of update. 
[Slack Convo](https://kongstrong.slack.com/archives/CDSTDSG9J/p1623295650075700)
[DOCU-1552](https://konghq.atlassian.net/browse/DOCU-1552)
- [Migrating Kong Gateway from 2.3.x to 2.4.x](https://deploy-preview-2935--kongdocs.netlify.app/enterprise/2.4.x/deployment/upgrades/migrations/)
- …
=> [DOCU-1552]Updates migrations doc by removing patch releases section

app/contributing/markdown-rules.md, app/contributing/style-guide.md
Made some edits to the style guide per our doc team discussions. Also, added the new badge to the markdown rules doc and updated the examples with a dot before the class.
The style guide needed update as part of our continuous improvement efforts and after creating the db-less compatible badge, I realized the dot was missing from the examples and needed to be added.
[Badges update](https://deploy-preview-2961--kongdocs.netlify.app/contributing/markdown-rules/#badges)
[Style guide update](https://deploy-preview-2961--kongdocs.netlify.app/contributing/style-guide/)
=> Makes updates discussed in style guide team meeting

app/_redirects
Adding a redirect for logical top-level Getting Started guide page (docs.konghq.com/getting-started-guide). 
Currently it leads to a 404.
Test that https://deploy-preview-2981--kongdocs.netlify.app/getting-started-guide redirects to the getting started guide overview.
=> Add getting started guide redirect

app/getting-started-guide/2.4.x/overview.md
Setting the Getting Started Guide to use the regular layout and not hide the right-hand page nav.
Missing page nav for no good reason.
https://deploy-preview-2983--kongdocs.netlify.app/getting-started-guide/2.4.x/overview/ - the right-hand page nav should be visible.
=> Remove is_homepage from getting started guide metadata

pdf-generation/create-pdf.js
Removing references to classes that no longer exist.
Line numbers, and therefore all the extra rouge classes that went with them, were removed in https://github.com/Kong/docs.konghq.com/pull/2968.
N/A
=> Remove references to rouge css classes [skip ci]

app/_hub/kong-inc/mocking/index.md, app/_hub/kong-inc/opa/index.md
Plugins are missing their labels.
These two plugins are available in Konnect Plus, not just Enterprise.
https://deploy-preview-2991--kongdocs.netlify.app/hub/ - make sure that OPA and Mocking both have the PLUS badge
=> Label OPA and Mocking plugins as Plus tier

app/gateway-oss/2.5.x/external-plugins.md
The default PATH is too limited.  most users will have to add `/usr/local/bin.  Mention in the parameter definition and include in all the examples .
Fixes: Kong/kong#7481
=> external-plugins: recommend full executable paths

app/_assets/stylesheets/base.less, app/contributing/markdown-rules.md, app/contributing/style-guide.md
Adding guidelines for using editable placeholders to contributing guide and removing info about line numbers.
Also adjusting padding and margins for placeholders because it became clear, while writing up guidelines, that they were way too big.
https://konghq.atlassian.net/browse/DOCU-1592
https://deploy-preview-2995--kongdocs.netlify.app/contributing/markdown-rules/#placeholders
=> [DOCU-1592] Instructions for using editable placeholders

app/_plugins/alias_generator.rb
This reverts commit 79554c95e2ed66a23177af20b652f1143349184d.
/latest/ URLs are broken in the output.
=> Revert "remove extra index path to prevent duplicate URLs"

app/_plugins/alias_generator.rb
We only want to generate each alias once
This code snippet works by generating a redirect for every segment of a URL
e.g. enterprise/2.4.x/developer-portal/using-the-editor/ will generate:
* enterprise/latest => enterprise/2.4.x
* enterprise/latest/developer-portal => enterprise/2.4.x/developer-portal
* enterprise/latest/developer-portal/using-the-editor => enterprise/2.4.x/developer-portal/using-the-editor
This works until you have two pages with a common base URL such as:
* enterprise/2.4.x/developer-portal/working-with-templates/index.html
* enterprise/2.4.x/developer-portal/using-the-editor/
In this instance, enterprise/2.4.x/developer-portal will be generated twice
and jekyll will complain with the following error:
> Conflict: The following destination is shared by …
=> Fix duplicate alias generation

app/sitemap.txt
We are using sitemap.txt and sitemap.xml.
* Sitemap.xml gets submitted to search providers and is the current sitemap logged in Google Search Console. It’s also specified in our robots.txt. 
* Sitemap.txt hasn't been touched in six years and isn't actually in use.
Sitemap.txt doesn’t appear to have a use, and is listing all outdated version pages. It adds a not-insignificant amount of time to our build.
N/A
=> Delete duplicate sitemap file

app/konnect/dev-portal/administrators/app-registration/disable-app-reg.md, app/konnect/dev-portal/administrators/app-registration/enable-app-reg.md, app/konnect/dev-portal/administrators/app-registration/manage-app-connections.md, app/konnect/dev-portal/administrators/app-registration/manage-app-reg-requests.md, app/konnect/dev-portal/administrators/auto-approve-devs-apps.md, app/konnect/dev-portal/administrators/customization/themes.md, app/konnect/dev-portal/administrators/manage-devs.md, app/konnect/dev-portal/administrators/public-portal.md, app/konnect/dev-portal/developers/dev-apps.md, app/konnect/dev-portal/developers/dev-gen-creds.md, app/konnect/dev-portal/developers/dev-reg-app-service.md, app/konnect/dev-portal/developers/dev-reg.md, app/konnect/getting-started/declarative-config.md, app/konnect/manage-plugins/index.md, app/konnect/manage-plugins/shared-config.md, app/konnect/shared-config/index.md, app/konnect/updates.md
Cleaning up references to the Shared Config page. Should always say "Shared Config page", as shared config is not a real concept and only exists as a bucket for misc configurations.
Also cleaning up all the unnecessary "this item displays" text, and shortening prereqs for permissions to just list the permission. 
Terminology and UI woes and a small step towards simplifying GUI documentation.
https://deploy-preview-3008--kongdocs.netlify.app/konnect/shared-config/
Most topics under app reg and dev portal, eg: 
https://deploy-preview-3008--kongdocs.netlify.app/konnect/dev-portal/administrators/app-registration/enable-app-reg/
Shortening the following topics:
https://deploy-preview-3008--kongdocs.netlify.app/konnect/dev-portal/administrators/auto-approve-devs-apps/ …
=> Konnect docs: shared config and app reg cleanup

Makefile
Adding `rm -rf app/.jekyll-cache` to `clean`. 
Also adding comments to explain what each command does so that anyone can understand what's going on, and which one they might want to run.
Jekyll-cache should be cleaned out so that tests are more accurate, and will help with troubleshooting.
For the comments, taking a cue from Michael's [recent PR](https://github.com/Kong/docs.konghq.com/pull/3002). We should try to add code comments as much as possible, so that anyone on the team can understand what's going on.
To test, pull down the branch and run `make clean && make install`. It should remove dist and jekyll-cache, which will get recreated next time you `make run`.
=> Add jekyll-cache to makefile clean

app/_includes/hub_cards.html, app/deck/1.7.x/index.md, app/kubernetes-ingress-controller/1.3.x/index.md
/hub:
* add `title` attributes to links with `extn.name` and `extn.desc`
/deck:
* change clickable video stills to easy-to-read links
* update links to be more readable and descriptive
/kubernetes-ingress-controller:
* update links to be more readable and descriptive
Accessibility efforts. 
Note that for /decK, clickable images appear misleading (as hosted or imbedded media) for users not using a screen reader. For screen-reader users, there was no description of the image. I opted to add descriptive links instead. 
Tested locally. 
https://deploy-preview-3017--kongdocs.netlify.app/hub/ 
https://deploy-preview-3017--kongdocs.netlify.app/deck/
https://deploy-preview-3017--kongdocs.netlify.app/kubernetes-ingress-controller/
I recommend creating an accessible links section …
=> [DOCU-1603] Add title attrs and more desc link titles

app/kubernetes-ingress-controller/1.3.x/troubleshooting.md
@Bradamant3 
Turning code phrases into code blocks and some minor teeny edits.
Long code phrases were breaking mobile site.
I wonder if we should add some guidelines around when to use a code phrase vs when to use a code block @HCloward @Bradamant3 
https://deploy-preview-3015--kongdocs.netlify.app/kubernetes-ingress-controller/1.3.x/troubleshooting/
=> KIC troubleshooting: Turn code phrases into codeblocks

app/enterprise/1.3-x/developer-portal/working-with-templates.md, app/enterprise/1.5.x/developer-portal/working-with-templates.md, app/enterprise/2.1.x/developer-portal/working-with-templates.md, app/enterprise/2.2.x/developer-portal/working-with-templates.md
I was trying to change route for rendered spec file using `x-headmatter` and stumbled upon collections having issues.
I've fixed only the obvious mistakes.
I don't know if it a required attribute or if other (route, output) attributes are correct.
=> fix docs for developer-portal collections

app/contributing/markdown-rules.md
Adding caution against using editable placeholders for private or sensitive information. 
Ran into this issue and realized we need guidelines around it.
TBA
=> Contributing: Add caution about using editable placeholders

app/_hub/kong-inc/key-auth-enc/index.md, app/_hub/kong-inc/key-auth/index.md
Document `ttl` parameter when creating a key with the key-auth plugin.
This feature is not documented
=> Document key-auth TTL parameter

app/gateway-oss/2.5.x/hybrid-mode.md
Note that the cluster certificate (from either `cluster_cert` or `cluster_ca_cert`, depending on the mtls mode) is added to the content (if any) of `lua_ssl_trusted_certificate`.
=> DP cluster.crt is added to lua_ssl_trusted_certificate.

app/gateway-oss/2.5.x/db-less-and-declarative-config.md
@jackkav please take a look and tell me if I added this new ability correctly. I am not sure if this can be done after a Kong instance has already started or if it is only something users can do upon starting a Kong instance. Also, I am not sure what the `-v $HOME/git/kong/kong/db/declarative/init.lua:/usr/local/share/lua/5.1/kong/db/declarative/init.lua` line is for. 
Kong 2.5 update - [PR 7379](https://github.com/kong/kong/pull/7379)
There was a feature request to be able to start Kong in dbless without having to create a declarative configuration file - to be able to simply start Kong with the declarative configuration as part of an environment variable in a string.
Kong issue - [#7344](https://github.com/Kong/kong/discussions/7344)
=> Adds new ability to add declarative config with a string feature

app/_assets/javascripts/app.js, app/_layouts/default.html
After merging the build improvement PR @falondarville noticed that the blue bar wasn't showing on the homepage. This is due to the sidebar not existing and has been fixed in this PR.
Additionally, the page title generation was being cached and the Algolia search was missing code on the landing page. Both of these are resolved in this PR.
Fixes for production and PR #3003 
* Blue bar should show up on the landing page
* Page titles should be correct
=> Include cache fixes

app/_layouts/extension.html
All plugins are showing `google-auth` as the name due to the recent update to use `include_cached`. This PR passes in the parameters directly to fix this issue
Visit `/hub/kong-inc/basic-auth/` - you should see 
```
curl -X POST http://{HOST}:8001/services/{SERVICE}/plugins \
--data "name=basic-auth"  \
```
rather than
```
curl -X POST http://{HOST}:8001/plugins/ \
--data "name=google-logging" 
```
=> Fix include_cache issue on plugin pages

gulpfile.js
@lena-larionova @falondarville 
Refactor the `gulpfile` to reduce duplication and provide predictable builds
Whilst running `make run` without any arguments I noticed that the first time the build ran `jekyll_dev`, but when I changed a file it ran `jekyll` without the dev profile. This is due to `watch_files` being hardcoded to run `jekyll`.
I started to add a `watch_files_dev` method but noticed a lot of duplication within the methods and decided to take another route and dynamically decide what to run based on the value of the `dev` variable that is used elsewhere.
Whilst refactoring I noticed that other methods were almost exact copies (e.g. `js` and `js_min`, `images` and `images_min`). By using the `dev` variable I could combine these methods and only run the minification tasks when …
=> Refactor gulp

app/enterprise/changelog.md
v2.5.0.0 beta release changelog updates
[2.5.0.0 beta changelog entry](https://deploy-preview-3033--kongdocs.netlify.app/enterprise/changelog/#2500-beta)
=> Adds the v2.5 EE beta release notes to the changelog

app/konnect/shared-config/index.md
Fixing a link that the link checker flagged as broken.
Broken link.
https://deploy-preview-3046--kongdocs.netlify.app/konnect/shared-config/
=> Fix broken link in Shared Config doc

app/_assets/stylesheets/pages/landing-page.less, app/_layouts/landing-page.html
Removing subtitle text that was on the landing page initially for old users of the old doc site, which changed in Feb 2021.
Also removing related CSS class.
https://konghq.atlassian.net/browse/DOCU-1624
TBA
=> [DOCU-1624] Remove search bar subtitle and increase margin

app/enterprise/changelog.md
@HCloward 
Fixed links and the proxy_stream_error_log property name.
Links were broken.
Couldn't find a property named `proxy_stream_error`, realized that was a typo also - check against the eng PR: https://github.com/kong/kong/pull/7046
TBA
=> Fix links and property name in changelog

app/_assets/stylesheets/accordion.less, app/_assets/stylesheets/base.less, app/_assets/stylesheets/navtabs.less, app/_assets/stylesheets/page.less, app/_assets/stylesheets/pages/docs.less, app/_assets/stylesheets/pages/extension.less, app/_assets/stylesheets/syntax.less, app/_assets/stylesheets/variables.less
* Add underlines to links (ADA guidelines) in body text. This does not include the navigation.
* Consistent link colors - matching the landing page
* Syntax highlighting uses purple instead of red
* Add even/odd rules to tables to separate rows more clearly
* Change scrollbar color for consistency - was a light blue tone that doesn't go with anything else
* Slightly raise contrast on font color
Various tickets and accessibility guidelines.
https://konghq.atlassian.net/browse/DOCU-204
Tested with ADA contrast checker and with chrome dev tools.
Lots of tables: https://deploy-preview-3049--kongdocs.netlify.app/konnect-platform/compatibility/plugins/
* Resize the screen to mobile size to see how the tables react - previously, they were fully white and nearly unreadable on …
=> Styling changes to links, tables, and code syntax

app/enterprise/2.4.x/vitals/vitals-reports.md
The time limit for Vitals Reports was up to 12 hours but has been updated to up to 3 years.
@rezaloo75 requested update in [Slack](https://kongstrong.slack.com/archives/C029PLEEKTK/p1627400698004100)
Will include Netlify preview build when available.
=> Update vitals reports time limit

app/_assets/css/hub.css, app/_assets/stylesheets/header-v2.less, app/_assets/stylesheets/page.less, app/_assets/stylesheets/pages/docs.less, app/_assets/stylesheets/pages/landing-page.less, app/_hub/index.html, app/_includes/header.html, app/_includes/nav-v2.html, app/_layouts/docs-v2.html, app/_layouts/landing-page.html, app/_layouts/page.html, gulpfile.js
Add "skip to content" feature. 
@adamjkuhn I am working on site accessibility, and my current feature is a "skip to content" button (reached through tabbing) that skips tabbing through the menu and goes to the first element on that page (header). I'm having issues with the anchor linking from the "skip to content" to the #main ids. They are going too far down the page. 
To replicate: 
* pull down my work locally and navigate to the docs homepage
* tab to see "skip to content"
* use Enter
* you will see that the anchor goes to below the header
It's working on main product pages correctly, for example, /konnect/ (styling at docs.less). But it's not working on the homepage, the hub page, and the hub detail pages. 
Note that base.less (lines 221-230) could be interfering with …
=> [DOCU-1628] add skip to content

app/_assets/stylesheets/base.less, app/_assets/stylesheets/footer.less, app/_assets/stylesheets/header-v2.less
* when fixing underline on hover for the submenu non-clickable headers, the styling stripped from the remaining nav items. I added underlining to non-Docs items
* added underline on hover to footer items
* remove bold when active for Docs menu item
Increase accessibility by adding more visible indicator that user is hovering on a link. 
Hover over main nav and footer link items.
=> add underline on hover to main nav and footer

app/_assets/stylesheets/pages/landing-page.less, app/_layouts/landing-page.html
Previously, the "Key features" and "Ecosystem integrations" cards on the landing pages (on mobile) can only be accessed if the user scrolls right. This makes it difficult for users to understand how to use the page to see the content "hidden". 
The "Key features" and "Ecosystem integrations" cards now stack on smaller screen so that you don't have to scroll right. 
* users can see all content without having to guess how to use the scrolling feature
* provides more accessible elements
* makes more sense visually
Check out the landing page "Key features" and "Ecosystem integrations" cards on smaller screens and mobile. They will stack now.
=> [DOCU-1635] make features cards stack on mobile

app/enterprise/2.4.x/deployment/hybrid-mode-setup.md, app/enterprise/2.4.x/deployment/hybrid-mode.md, app/gateway-oss/2.4.x/hybrid-mode.md, app/gateway-oss/2.5.x/hybrid-mode.md
@HCloward 
* Adding missing sections from OSS gateway docs to enterprise gateway docs:
* Fault tolerance and disconnected mode added to hybrid mode info page
* Revocation checks added to hybrid mode setup page
* Fixing typo in "DP node stat sequence" (should be "start sequence") and adding this missing section to enterprise gateway docs
* Reformatted the start sequence table into a list, as it is a list of steps that the DP node takes, in order, and cleaned up the text of that section.
Issue noted on Slack.
https://konghq.atlassian.net/browse/DOCU-1622
https://deploy-preview-3064--kongdocs.netlify.app/enterprise/2.4.x/deployment/hybrid-mode/#fault-tolerance
https://deploy-preview-3064--kongdocs.netlify.app/enterprise/2.4.x/deployment/hybrid-mode-setup/ - see sections on DP node start …
=> [DOCU-1622][DOCU-1397] Add missing hybrid mode sections to enterprise doc

app/_includes/md/enterprise/deploy-license.md, app/enterprise/2.4.x/deployment/licenses/deploy-license.md
Add back in deleted content that is still valid and pertinent. 
https://github.com/Kong/docs.konghq.com/issues/3069
Check /enterprise/2.4.x/deployment/licenses/deploy-license/ for "Environmental variable" tab.
=> Re-add deployment content (issue 3069)

app/_data/docs_nav_ee_1.3-x.yml, app/_data/docs_nav_ee_1.5.x.yml, app/_data/docs_nav_ee_2.1.x.yml, app/_data/docs_nav_ee_2.2.x.yml, app/_data/docs_nav_ee_2.3.x.yml, app/_data/docs_nav_ee_2.4.x.yml, app/enterprise/1.3-x/developer-portal/configuration/authentication/sessions.md, app/enterprise/1.3-x/developer-portal/networking.md, app/enterprise/1.3-x/developer-portal/overview.md, app/enterprise/1.5.x/developer-portal/configuration/authentication/sessions.md, app/enterprise/1.5.x/developer-portal/networking.md, app/enterprise/2.1.x/developer-portal/configuration/authentication/sessions.md, app/enterprise/2.1.x/developer-portal/networking.md, app/enterprise/2.2.x/developer-portal/configuration/authentication/sessions.md, app/enterprise/2.2.x/developer-portal/networking.md, app/enterprise/2.3.x/developer-portal/configuration/authentication/sessions.md, app/enterprise/2.3.x/developer-portal/networking.md, app/enterprise/2.4.x/developer-portal/configuration/authentication/sessions.md
* Update URLs to networking content for versions 1.3.x +. 
* Delete `networking.md` for versions 1.3.x +.
Link currently goes to older documentation. Addresses https://github.com/Kong/docs.konghq.com/issues/3068
Local testing. Go through EE docs versions 1.3.x + and click on "Networking" to ensure that it is linking to "Property Reference" section.
=> Update networking urls (issue 3068)

app/_hub/kong-inc/route-transformer-advanced/index.md
Remove link to changelog on route transformer advanced plugin docs. 
We don't actively maintain this changelog. 
=> [DOCU-1644] rm changelog link for route transformer advanced plugin

app/_hub/kong-inc/graphql-rate-limiting-advanced/index.md, app/_hub/kong-inc/rate-limiting-advanced/index.md
@murillopaula , @HCloward 
Removing the option to select `local` as a rate limiting strategy for the Rate Limiting Advanced and GraphQL Rate Limiting Advanced plugins. Instead, documenting the workaround defined here: https://konghq.atlassian.net/browse/DOCU-1636
A direct `local` strategy does not exist, but you can rate limit locally using `sync_rate`.
See https://konghq.atlassian.net/browse/DOCU-1636 for more detail.
https://deploy-preview-3071--kongdocs.netlify.app/hub/kong-inc/graphql-rate-limiting-advanced/
https://deploy-preview-3071--kongdocs.netlify.app/hub/kong-inc/rate-limiting-advanced/
=> [DOCU-1636] Rate limiting advanced plugin: local strategy workaround

package-lock.json, package.json
Removing echint.
Echint is deprecated and not maintained: https://www.npmjs.com/package/echint
This code linter flags very odd warnings as errors (mostly about having an extra newline at the end of a file, or an indent in the wrong place) and causes builds to fail.
Run the build locally and make sure it doesn't break.
Wait for checks to pass on this PR.
=> [DOCU-1630] Remove echint

app/_data/extensions/kong-inc/jwt/versions.yml, app/_hub/kong-inc/jwt/2.1-x.md
Removing version 1.0-x from the JWT version dropdown.
This version doc doesn't exist: https://github.com/Kong/docs.konghq.com/tree/main/app/_hub/kong-inc/jwt
The dropdown entry causes a 404.
Check by testing the version dropdown and making sure all versions work: https://deploy-preview-3076--kongdocs.netlify.app/hub/kong-inc/jwt/
=> [DOCU-1641] Remove non-existent JWT version

app/_hub/cleafy/cleafy/index.md
Removing legacy value `kong_legacy_api`. It's not used anywhere in our templates.
https://github.com/Kong/docs.konghq.com-private/issues/87
Just check that the page didn't break: https://deploy-preview-3079--kongdocs.netlify.app/hub/cleafy/cleafy/
=> Cleafy plugin doc: remove legacy metadata

app/_layouts/docs-v2.html
Desired behavior (was previously working): when you're on a doc page (eg https://docs.konghq.com/enterprise/2.1.x/deployment/installation/docker/) and switch to another version of this page using the dropdown in the top left, the same page should load up but with the new URL ( eg https://docs.konghq.com/enterprise/2.4.x/deployment/installation/docker/). Caching breaks this.
Caching is also breaking the link to latest documentation from older versions. Again, see https://docs.konghq.com/enterprise/2.1.x/deployment/installation/docker/ - the note at the top of the page should link to the latest version of this Docker installation, but instead it simply goes to https://docs.konghq.com/enterprise/
DOCU-1633
Switch versions on the left hand side switcher and it should take you …
=> Version switcher cache

app/enterprise/changelog.md
@HCloward 
https://github.com/Kong/kong-ee/pull/2431 was planned to go into the
2.5.0.0 release but did not make it in time. Engineering had added the
changelog entry because it was planned to go in, but I missed that this
did not actually make it into the release.
=> fix(changelog) Remove line that did not make it into the 2.5.0.0 release

.github/workflows/run-smoke-tests.yml, .rspec, Gemfile, Gemfile.lock, Makefile, README.md, netlify.toml, spec/breadcrumbs_spec.rb, spec/home_spec.rb, spec/plugin_spec.rb, spec/sidebar_spec.rb, spec/spec_helper.rb
Add an automated test framework to ensure that we're not breaking any key functionality whilst refactoring.
I broke the site multiple times whilst adding the `include_cached` gem.
* During the initial PR (#3003)
* Sidebar was cached unintentionally
* Breadcrumbs were cached unintentionally
* The plugin hub CSS file wasn't loaded due to `head.html` being cached
* Active state was being cached (this was solved with Javascript)
* Promo banner wasn't showing on the homepage (#3027)
* Plugin configuration instructions were all showing the same plugin instructions (#3030)
Tests have been added to cover all of these cases
Run the tests locally. See the `Testing` section in the README.
The tests are automatically run on GitHub Actions too
=> Add testing framework

app/_hub/kong-inc/datadog/index.md
@svenwal - I removed the original string and replaced it with 
This is to remove the current default value for config.metrics as it is wrong. 
[DOCU-1655](https://konghq.atlassian.net/browse/DOCU-1655)
[Datadog plugin](https://deploy-preview-3084--kongdocs.netlify.app/hub/kong-inc/datadog/)
=> [DOCU-1655]Updates datadog plugin doc with correct default value

app/enterprise/2.5.x/support-policy.md
As far as I understand the support policy, the only thing that needs updating on this table is adding the new release number.
[DOCU-1661](https://konghq.atlassian.net/browse/DOCU-1661)
[Version Support for Kong Gateway (Enterprise)](https://deploy-preview-3094--kongdocs.netlify.app/enterprise/2.5.x/support-policy/#version-support-for-kong-gateway-enterprise)
=> [DOCU-1661]Updates support policy table by adding the 2.5.x.x release

app/_includes/head.html, jekyll-dev.yml, jekyll.yml
@falondarville and also @Kong/team-docs 
This change will give us better link previews and a more up-to-date website summary for search engines.
**Reviewers:** I did some research on the difference between site name and site title, and came up blank. Site name isn't even a default jekyll variable, it's a custom one that someone added. I'm still not sure why we had a different site name vs site title, so I made them the same and removed the redundancy in link titles. However, if someone knows more about this and could answer _why_ we might have this and whether we might need to come up with a unique site name, I'd be glad to hear about it.
Site metadata was very out of date, and our link previews would only ever generate a site description as the link title. 
TBA
=> [DOCU-1692] Update site title, name, and description

app/_data/extensions/kong-inc/basic-auth/versions.yml
Removing nav entry for a plugin version that doesn't have docs.
Broken link in the [basic auth dropdown to 1.0-x,](https://docs.konghq.com/hub/kong-inc/basic-auth/) and the version doesn't exist: https://github.com/Kong/docs.konghq.com/tree/main/app/_hub/kong-inc/basic-auth
Check nav on basic auth: https://deploy-preview-3113--kongdocs.netlify.app/hub/kong-inc/basic-auth/
=> Basic auth plugin: remove non-existent version

app/enterprise/2.5.x/plugin-development/custom-logic.md
I checked the order by the below commands:
```
cd /usr/local/share/lua/5.1/kong/plugins/
find . | xargs grep  \.PRIORITY |  sort -k 3 -t " " -n -r | grep ip-
```
Then you can find below:
`./ip-restriction/handler.lua:  PRIORITY = 990,`
=> Deleted the duplicated order for ip-restriction

app/kubernetes-ingress-controller/2.0.x/concepts/ingress-classes.md, app/kubernetes-ingress-controller/2.0.x/guides/cert-manager.md, app/kubernetes-ingress-controller/2.0.x/guides/configure-acl-plugin.md, app/kubernetes-ingress-controller/2.0.x/guides/configuring-fallback-service.md, app/kubernetes-ingress-controller/2.0.x/guides/configuring-health-checks.md, app/kubernetes-ingress-controller/2.0.x/guides/configuring-https-redirect.md, app/kubernetes-ingress-controller/2.0.x/guides/getting-started-istio.md, app/kubernetes-ingress-controller/2.0.x/guides/getting-started.md, app/kubernetes-ingress-controller/2.0.x/guides/prometheus-grafana.md, app/kubernetes-ingress-controller/2.0.x/guides/redis-rate-limiting.md, app/kubernetes-ingress-controller/2.0.x/guides/using-consumer-credential-resource.md, app/kubernetes-ingress-controller/2.0.x/guides/using-external-service.md, app/kubernetes-ingress-controller/2.0.x/guides/using-kongclusterplugin-resource.md, app/kubernetes-ingress-controller/2.0.x/guides/using-kongingress-resource.md, app/kubernetes-ingress-controller/2.0.x/guides/using-kongplugin-resource.md, app/kubernetes-ingress-controller/2.0.x/guides/using-mtls-auth-plugin.md, app/kubernetes-ingress-controller/2.0.x/guides/using-oidc-plugin.md, app/kubernetes-ingress-controller/2.0.x/guides/using-rewrites.md, app/kubernetes-ingress-controller/2.0.x/references/annotations.md, app/kubernetes-ingress-controller/2.0.x/references/custom-resources.md
Update Ingress examples in documentation to use resources compatible
with Kubernetes 1.22, which removes support for Ingress versions other
than networking.k8s.io/v1:
https://kubernetes.io/blog/2021/07/14/upcoming-changes-in-kubernetes-1-22/#api-changes
Replace ingress.class annotations on Ingress objects with
ingressClassName fields. Although still supported, the ingress.class
annotaion is deprecated. Note that KIC still lacks proper support for
the associated IngressClass resource and treats ingressClassName
effectively the same as the ingress.class annotation.
Remove documentation for classless resources. These are no longer
supported in KIC 2.x.
Changes in Kubernetes and our controller mandate this change.
Waiting for Netlify. The annotations page contains new raw HTML, need to check …
=> doc(kic) update Ingress documentation for 1.22

app/konnect/dev-portal/administrators/public-portal.md, app/konnect/dev-portal/developers/dev-reg.md, app/konnect/dev-portal/index.md
* rm screenshot and info about where to find Portal URL (this appears in Developer Registration - may move later, this is iterative)
* clean up product description
* add "see also" to give users a place to go next (will add to this as we continue to iterate)
Current overview contains extraneous information.
https://deploy-preview-3117--kongdocs.netlify.app/konnect/dev-portal/
=> [DOCU-1164] clean up Dev Portal Overview

app/enterprise/2.3.x/deployment/hybrid-mode.md, app/enterprise/2.4.x/deployment/hybrid-mode.md, app/enterprise/changelog.md
The Enterprise Gateway is releasing 5 minor releases with a handful of bug fixes and the changelog needs to be updated with these new versions and what updates are included in them.
Internal changelog:
- [2.1.4.7](https://konghq.atlassian.net/wiki/spaces/FTT/pages/2594734310/Kong+Enterprise+2.1.4.7)
- [2.2.1.4](https://konghq.atlassian.net/wiki/spaces/FTT/pages/2594865355/Kong+Enterprise+2.2.1.4)
- [2.3.3.3](https://konghq.atlassian.net/wiki/spaces/FTT/pages/2590736896/Kong+Enterprise+2.3.3.3)
- [2.4.1.2](https://konghq.atlassian.net/wiki/spaces/FTT/pages/2594734458/Kong+Enterprise+2.4.1.2)
- [2.5.0.1](https://konghq.atlassian.net/wiki/spaces/FTT/pages/2596307228/Kong+Enterprise+2.5.0.1)
[DOCU-1705](https://konghq.atlassian.net/browse/DOCU-1705)
- …
=> [DOCU-1705] Updates ee changelog with 5 new minor releases

app/_hub/kong-inc/basic-auth/0.1-x.md, app/_hub/kong-inc/basic-auth/2.1-x.md, app/_hub/kong-inc/basic-auth/index.md
Basic auth plugin:
* Removing "optional" label from the password property in the consumer credential.
* In latest version of the doc, minor cleanup (phrasing, grammar, format); turned request/response codeblocks into two tabs for easier copying; placeholder formatting.
Bug reported on Slack. Ticket: https://konghq.atlassian.net/browse/DOCU-1716
https://deploy-preview-3119--kongdocs.netlify.app/hub/kong-inc/basic-auth/
=> [DOCU-1716] Basic auth plugin: Remove optional label from password

app/kubernetes-ingress-controller/2.0.x/guides/using-udpingress.md
This is another iteration on the KIC 2.x docs which are in flight and adds a `UDPIngress` guide page.
Resolves https://github.com/Kong/docs.konghq.com/issues/2903
I tested the guide manually running through each step to ensure that everything up to and including the verification step worked.
Everything worked minus a bug a found in the chart which is now reported as:
- https://github.com/Kong/charts/issues/445
And will be fixed before 2.0.0 GA.
=> docs: udp guide for kic v2

app/_data/docs_nav_contributing.yml, app/contributing/community-expectations.md, app/contributing/community.md, app/contributing/hackathons.md
In order to prep for our upcoming hackathon, we needed some resources:
* Community: provides contributors with information on our docs-as-code process
* Community Expectations: provides contributors with information on our inclusive language and accessibility efforts. Note that I plan on adding more content to the inclusive language section later on but this is a good starting place. 
* Hackathons: provides contributors with general information about effective hackathon participation
In addition to adding three pages, I hid "Terms" and "Plugin docs" from our sidebar nav as they were incomplete and can be confusing to contributors. 
We didn't have in-depth information for contributors to be able to join our community. 
Community: …
=> [DOCU-1719] Add Community Tab to Contributing

app/_layouts/docs-v2.html
Setting KIC beta notification banner to not appear on 2.0.x.
Since the beta KIC doc is based on main, it's pulling in the beta notification banner into all pages. Because of that, the beta docs end up with two banners on every page: https://kic-v2-beta--kongdocs.netlify.app/kubernetes-ingress-controller/
N/A, but tested locally. Will need to merge into beta branch.
=> Stop wrong banner from appearing in KIC beta version

app/_data/docs_nav_kic_2.0.x.yml, app/kubernetes-ingress-controller/2.0.x/guides/using-udpingress.md
@Bradamant3 
This is another iteration on the KIC 2.x docs which are in flight and adds a `UDPIngress` guide page.
Resolves https://github.com/Kong/docs.konghq.com/issues/2903
I tested the guide manually running through each step to ensure that everything up to and including the verification step worked.
Everything worked minus a bug a found in the chart which is now reported as:
- https://github.com/Kong/charts/issues/445
And will be fixed before 2.0.0 GA.
=> docs: add a UDPIngress guide

app/konnect/runtime-manager/gateway-runtime-kubernetes.md
Replaced `config,yaml` with `values.yaml` in document.
=> Invalid reference to config,yaml in the documentation

app/_includes/hub-examples.html
The URL https://github.com/Kong/kubernetes-ingress-controller/blob/main/docs/references/custom-resources.md#kongplugin is an old URL which is written as a 301 since December 2020, and now includes a link to https://docs.konghq.com/kubernetes-ingress-controller/latest/references/custom-resources/ instead. Updating accordingly for improved CX, including anchor to KongPlugin section in Custom Resources doc page.
Updated the URL to avoid the 301 redirect from GitHub (which is not a real automatic 301, thus why this change is needed).
The old URL was modified to display a 301 Permanent Redirect and included a link to the new destination. Saving this step for improved customer experience.
Just click the new URL and it should direct to the latest version automatically for the …
=> Updated old URL for KongPlugin to new URL

app/kubernetes-ingress-controller/2.0.x/references/custom-resources.md
This patch adds UDPIngress to the TOC in the CRD reference.
Resolves https://github.com/Kong/kubernetes-ingress-controller/issues/1348
=> docs: add udpingress to crd toc

app/_data/docs_nav_kic_2.0.x.yml
Adds prometheus to the references TOC.
The entry in the TOC is currently missing.
Resolves https://github.com/Kong/kubernetes-ingress-controller/issues/1803
=> docs: add prom metrics to kic 2.x toc

algolia/config-full-docs.json
Updating latest Kong Gateway, Mesh, and Getting started guide versions.
Search results are pulling up the previous version.
N/A
=> Update search to index latest versions [skip ci]

app/enterprise/2.5.x/developer-portal/administration/application-registration/3rd-party-oauth.md, app/enterprise/2.5.x/developer-portal/administration/application-registration/auth-provider-strategy.md, app/enterprise/2.5.x/developer-portal/administration/application-registration/azure-oidc-config.md, app/enterprise/2.5.x/developer-portal/administration/application-registration/enable-application-registration.md, app/enterprise/2.5.x/developer-portal/administration/application-registration/managing-applications.md, app/enterprise/2.5.x/developer-portal/administration/application-registration/okta-config.md, app/enterprise/2.5.x/developer-portal/administration/developer-permissions.md, app/enterprise/2.5.x/developer-portal/configuration/authentication/basic-auth.md, app/enterprise/2.5.x/developer-portal/configuration/authentication/key-auth.md, app/enterprise/2.5.x/developer-portal/configuration/authentication/oidc.md, app/enterprise/2.5.x/developer-portal/configuration/smtp.md
In Gateway Enterprise, I changed instances of "Developer Portal" to "Dev Portal". 
Note: We are not currently updating the folder name (and hence, URL) as we will defer this for our single-sourcing efforts. 
Growth team initiated a name change. 
Local
=> [DOCU-1801] Developer Portal to Dev Portal

app/_assets/javascripts/app.js, app/_includes/accordion-item.html, app/_includes/hub_cards.html, app/_includes/image-modal.html, app/_layouts/landing-page.html
* Removing alt text from left nav, landing page, and plugin hub icons. 
* Also removing alt text from decorative images on the landing page (arrows, background banners)
* Adjusting image modals to pull alt text from the images that they're expanding, instead of affixing a useless "image" label.
https://konghq.atlassian.net/browse/DOCU-1708
Currently, we have alt text on decorative icons throughout the site. If the icons are decorative, they should have empty alt text. See: homepage, product pages left-side menu, and hub
Reference: https://www.w3.org/WAI/tutorials/images/decorative/
https://deploy-preview-3178--kongdocs.netlify.app/ - text with Chrome WAVE extension
=> [DOCU-1708] Accessibility: Icon and image modal alt text

app/enterprise/changelog.md
Main update is to inform users about the Dev Portal template issue being fixed by the hot fixes - [FTI-2828](https://konghq.atlassian.net/browse/FTI-2828), and for 2.5.0.2 a fix for the Mocking plugin was also included - [FTI-2582](https://konghq.atlassian.net/browse/FTI-2582)
[DOCU-1798](https://konghq.atlassian.net/browse/DOCU-1798)
2.2.1.5
2.3.3.4
2.4.1.2
2.5.0.2
=> [DOCU-1798]Adds changelog entries for the 2.2.1.5, 2.3.3.4, 2.4.1.3, and 2.5.0.2 hot fix releases

app/kubernetes-ingress-controller/2.0.x/concepts/ingress-classes.md, app/kubernetes-ingress-controller/2.0.x/guides/cert-manager.md, app/kubernetes-ingress-controller/2.0.x/guides/configure-acl-plugin.md, app/kubernetes-ingress-controller/2.0.x/guides/configuring-fallback-service.md, app/kubernetes-ingress-controller/2.0.x/guides/configuring-health-checks.md, app/kubernetes-ingress-controller/2.0.x/guides/configuring-https-redirect.md, app/kubernetes-ingress-controller/2.0.x/guides/getting-started-istio.md, app/kubernetes-ingress-controller/2.0.x/guides/getting-started.md, app/kubernetes-ingress-controller/2.0.x/guides/prometheus-grafana.md, app/kubernetes-ingress-controller/2.0.x/guides/redis-rate-limiting.md, app/kubernetes-ingress-controller/2.0.x/guides/using-consumer-credential-resource.md, app/kubernetes-ingress-controller/2.0.x/guides/using-external-service.md, app/kubernetes-ingress-controller/2.0.x/guides/using-kongclusterplugin-resource.md, app/kubernetes-ingress-controller/2.0.x/guides/using-kongingress-resource.md, app/kubernetes-ingress-controller/2.0.x/guides/using-kongplugin-resource.md, app/kubernetes-ingress-controller/2.0.x/guides/using-mtls-auth-plugin.md, app/kubernetes-ingress-controller/2.0.x/guides/using-oidc-plugin.md, app/kubernetes-ingress-controller/2.0.x/guides/using-rewrites.md, app/kubernetes-ingress-controller/2.0.x/references/custom-resources.md
@mflendrich 
My initial attempt in https://github.com/Kong/docs.konghq.com/pull/3118 was incomplete because I didn't update the backends and didn't include pathTypes.
The v1 Ingresses are invalid otherwise. Using `implementationSpecific` as the default for everything since that was the de facto behavior in v1beta1.
Spot check against your own K8S 1.22 instances. I did:
```
16:47:33-0700 yagody $ echo "    
apiVersion: networking.k8s.io/v1
kind: Ingress                   
metadata:    
name: demo-example-com
spec:                   
ingressClassName: kong
rules:                
- host: demo.example.com
http:                 
paths:
- path: /
pathType: ImplementationSpecific
backend:                        
service:
name: echo …
```
=> doc(kic) fix v1 Ingress specs

app/kubernetes-ingress-controller/2.0.x/references/prometheus.md
n/a
Fixes the link to the controller-runtime metrics definition
A link to the wrong place has been there
n/a
=> KIC 2.0: fix an incorrect external link

app/deck/1.7.x/installation.md
@liyangau noted in docs channel on Slack that this download code sample was pointing to the prior version and not the latest version, 1.7. I have updated the variable to point to the 1 index instead of 0.
Want to be sure users are being directed to download the version that matches the version of the doc they are reading.
[DOCU-1808](https://konghq.atlassian.net/browse/DOCU-1808)
Will include Netlify link when available.
=> [DOCU-1808]Updates kong version in download code sample

README.md
Remove Docker instructions from README. And minor typo fixes. 
Docker does not currently work for docs site local development. 
N/A
=> [DOCU-1811] rm Docker instructions from README

app/_includes/head.html
@falondarville
Currently the landing page preview is `Kong Docs |`, including that extra `|` character.
Adjusting page title to display in a more useful and cleaner way. 
Accidentally used `page.title` instead of `page_title` originally.
TBA
When netlify preview is ready, right click on a page in the preview and click "Inspect". Look through the `<head>` tag to find the title metadata.
=> Adjust the metadata for page titles

app/enterprise/changelog.md
UpdateS changelog with EE Kong Gateway v2.5.1.0 patch release
[DOCU-1812](https://konghq.atlassian.net/browse/DOCU-1812)
=> [DOCU-1812]Adds changelog for 2.5.1.0 EE kong gateway release

app/gateway-oss/2.4.x/upgrading.md, app/gateway-oss/2.5.x/upgrading.md
The 2.5.x upgrading guide for Gateway OSS was not updated the last release. Also some sections which were determined to be inaccurate were not removed. This PR fixes those two things and some minor editing as well.
[DOCU-1806](https://konghq.atlassian.net/browse/DOCU-1806)
[Upgrade guide](https://deploy-preview-3183--kongdocs.netlify.app/gateway-oss/2.5.x/upgrading/)
=> [DOCU-1806]Updates gateway-oss upgrading guide with 2.5.x version

app/gateway-oss/2.6.x/upgrading.md
The 2.6.x upgrading guide for Gateway OSS was not updated the last release. Also some sections which were determined to be inaccurate were not removed. This PR fixes those two things and some minor editing as well.
[DOCU-1806](https://konghq.atlassian.net/browse/DOCU-1806)
[Upgrade guide](https://deploy-preview-3184--kongdocs.netlify.app/gateway-oss/2.6.x/upgrading/)
=> [DOCU-1806]Updates 2.6.x upgrading guide with new version

app/_assets/stylesheets/header-v2.less
* Adjust media queries to shrink search and nav earlier
* Hide the logo divider when search is opened on smaller screens
* Remove an unused media query
Navbar issues.
Test any page below the landing page, eg https://deploy-preview-3195--kongdocs.netlify.app/konnect/
* Test top navbar resize; make sure the caret (down arrow) is not visible when the navbar is expanded horizontally
* Click on the search icon when on a smaller screen and check that the logo divider is not visible.
=> [DOCU-1717] Fix top nav issues

gulpfile.js, package-lock.json, package.json
Removing and uninstalling the gulp-imagemin package.
* Image compression runs from scratch on every single build, therefore recompressing images every time
* This package is currently adding 5 minutes to build times
As a replacement for this package, here is the proposed plan:
1. Disable gulp-imagemin.
2. For any new image: as part of the image upload process, require that images are compressed locally by each author.
3. Periodically (e.g. once every couple of months) compress all images to account for anything that was missed.
Netlify log: https://app.netlify.com/sites/kongdocs/deploys/613a514a38c40400075c71f0
Performance comparison: build completed in 10 minutes and 4 seconds; previous builds (see list [here](https://app.netlify.com/sites/kongdocs/deploys)) normally …
=> [DOCU-1815] Remove gulp-imagemin and uninstall the package

app/konnect/deployment/index.md, app/konnect/runtime-manager/gateway-runtime-conf.md, app/konnect/runtime-manager/gateway-runtime-docker.md, app/konnect/runtime-manager/gateway-runtime-kubernetes.md, app/konnect/runtime-manager/runtime-parameter-reference.md, app/konnect/updates.md
* Entry in changelog to introduce support for 2.5
* Update version in sample codeblocks for runtime setup
* Remove `lua_ssl_trusted_certificate` from the doc due to changes made in https://github.com/kong/kong/pull/7044.
Konnect CP has been updated to run on Gateway 2.5.0.1.
https://konghq.atlassian.net/browse/DOCU-1650
https://konghq.atlassian.net/browse/DOCU-1653
Changelog entry: 
https://deploy-preview-3163--kongdocs.netlify.app/konnect/updates
Versions and `lua_ssl_trusted_certificate` updated in:
https://deploy-preview-3163--kongdocs.netlify.app/konnect/runtime-manager/gateway-runtime-docker/
https://deploy-preview-3163--kongdocs.netlify.app/konnect/runtime-manager/gateway-runtime-conf/
https://deploy-preview-3163--kongdocs.netlify.app/konnect/runtime-manager/gateway-runtime-kubernete …
=> [DOCU-1650][DOCU-1653] Konnect deploy Aug31

app/_includes/nav-v2.html
Kong Academy now supplants both Kong U and the old workshops/labs environment.
The Kong U and old Portal links are now outdated and should no longer be publicized.
=> Update navigation to include Kong Academy link, remove outdated links

app/gateway-oss/2.5.x/proxy.md
I only added the `http` tag for syntax highlighting.
=> docs: added syntax highlighting

app/konnect-platform/compatibility/index.md
@PaulFischer-Kong 
Adding help text to send users to appropriate channels based on product. 
https://konghq.atlassian.net/browse/DOCU-1775
https://deploy-preview-3171--kongdocs.netlify.app/konnect-platform/compatibility/
Test by selecting different products from the product dropdown.
Note that the redirect is temporarily commented out for the preview. Will re-add it before merging.
=> [DOCU-1775] Compat guide: Add help text based on selected product

app/_assets/stylesheets/page.less, app/_hub/kong-inc/ldap-auth-advanced/index.md, app/_hub/kong-inc/ldap-auth/index.md, app/_hub/kong-inc/mocking/index.md, app/_hub/kong-inc/statsd-advanced/index.md, app/_hub/kong-inc/statsd/index.md, app/contributing/markdown-rules.md
* Add a `no-icon` option for admonitions
* Removing the `tip` class, as we decided sometime back, as a team, to narrow down the options to only three
* Cleaning up any use of the `tip` style (there weren't many)
* Adding usage info to contributing guide
Need an iconless option for some situations. For example, when labelling a product "beta" or "tech preview", we don't want the X icon around as it looks like the feature is broken (this just came up for Okta IdP docs). 
https://deploy-preview-3216--kongdocs.netlify.app/contributing/markdown-rules/#admonitions
=> Introduce a "no-icon" option for admonitions and remove "tip"

app/_data/docs_nav_deck_1.8.x.yml, app/deck/1.7.x/reference/deck.md, app/deck/1.7.x/reference/deck_convert.md, app/deck/1.7.x/reference/deck_diff.md, app/deck/1.7.x/reference/deck_dump.md, app/deck/1.7.x/reference/deck_konnect.md, app/deck/1.7.x/reference/deck_konnect_diff.md, app/deck/1.7.x/reference/deck_konnect_dump.md, app/deck/1.7.x/reference/deck_konnect_ping.md, app/deck/1.7.x/reference/deck_konnect_sync.md, app/deck/1.7.x/reference/deck_ping.md, app/deck/1.7.x/reference/deck_reset.md, app/deck/1.7.x/reference/deck_sync.md, app/deck/1.7.x/reference/deck_validate.md, app/deck/1.7.x/reference/deck_version.md, app/deck/1.8.x/reference/deck.md, app/deck/1.8.x/reference/deck_completion.md, app/deck/1.8.x/reference/deck_diff.md, app/deck/1.8.x/reference/deck_dump.md, app/deck/1.8.x/reference/deck_konnect.md, app/deck/1.8.x/reference/deck_konnect_diff.md, app/deck/1.8.x/reference/deck_konnect_dump.md, app/deck/1.8.x/reference/deck_konnect_ping.md, app/deck/1.8.x/reference/deck_konnect_sync.md, app/deck/1.8.x/reference/deck_ping.md, app/deck/1.8.x/reference/deck_reset.md, app/deck/1.8.x/reference/deck_sync.md, app/deck/1.8.x/reference/deck_validate.md, app/deck/1.8.x/reference/deck_version.md
@hbagdi , @Kong/team-docs 
* Generate new CLI doc for deck 1.8
* Set up formatting for `deck completion`; did not do anything with grammar, as we will need to clean up the text on the deck repo side to generate cleaner instructions
* Remove `--timeout` and `--silence-event` flags from 1.7. Since the doc was generated halfway between releases, it accidentally picked up flags that are not available in 1.7.
deck 1.8 release.
Flag removal from 1.7 is based on changelog entry: https://github.com/Kong/deck/blob/main/CHANGELOG.md#v180---20210913
https://deploy-preview-3218--kongdocs.netlify.app/deck/
https://deploy-preview-3218--kongdocs.netlify.app/deck/1.8.x/reference/deck_completion/
=> [DOCU-1665][DOCU-1842] deck CLI updates for 1.8

app/_data/kong_versions.yml, app/mesh/changelog.md
Patch release for Mesh only to fix goroutine leak (see changelog item)
Release
Will post Netlify link. See also version number change in `kong_versions.yml`
=> Minor Mesh release (without Kuma)

.github/PULL_REQUEST_TEMPLATE.md
Removing "Review" section from the github template.
The reviewer section is redundant with the "Reviewers" section of the PR.
N/A
=> GH template: Remove redundant reviewer section [skip ci]

app/konnect/dev-portal/developers/dev-gen-creds.md
1. The proxy is either available at a URL [Linux](https://docs.konghq.com/konnect/runtime-manager/gateway-runtime-conf/) or an IP address [Kubernetes](https://docs.konghq.com/konnect/runtime-manager/gateway-runtime-kubernetes/)
2. The next segment of the URL must be the route and not the name of the service
=> Fixed the URL

app/_data/docs_nav_kic_2.0.x.yml, app/kubernetes-ingress-controller/2.0.x/guides/using-consumer-credential-resource.md, app/kubernetes-ingress-controller/2.0.x/guides/using-external-service.md, app/kubernetes-ingress-controller/2.0.x/guides/using-ingress-with-grpc.md, app/kubernetes-ingress-controller/2.0.x/guides/using-kong-with-knative.md, app/kubernetes-ingress-controller/2.0.x/guides/using-kongclusterplugin-resource.md, app/kubernetes-ingress-controller/2.0.x/guides/using-kongingress-resource.md, app/kubernetes-ingress-controller/2.0.x/guides/using-kongplugin-resource.md, app/kubernetes-ingress-controller/2.0.x/guides/using-mtls-auth-plugin.md, app/kubernetes-ingress-controller/2.0.x/guides/using-oidc-plugin.md, app/kubernetes-ingress-controller/2.0.x/guides/using-rewrites.md, app/kubernetes-ingress-controller/2.0.x/guides/using-tcpingress.md
Some minor cleanup of our CRD related guides.
Resolves https://github.com/Kong/kubernetes-ingress-controller/issues/1792
I created a cluster and walked through all the example code, which was functional except for one YAML configuration which I fixed as a part of this PR.
=>  docs: cleaning up KIC 2.0 docs "CRD" guides

app/kubernetes-ingress-controller/2.0.x/guides/prometheus-grafana.md
@Bradamant3
* Fixing link
* Changing note to full Markdown formatting
* Rephrasing intro for clarity and removing repetition
Someone pointed out the broken link on Slack. See https://konghq.atlassian.net/browse/DOCU-1814.
https://deploy-preview-3197--kongdocs.netlify.app/kubernetes-ingress-controller/2.0.x/guides/prometheus-grafana/
=> [DOCU-1814] Fix link and other issues in KIC 2.0 prometheus guide

app/_includes/head.html, app/_layouts/default.html
Adjusting the way a plugin page title displays in link previews, browser tab titles, and anywhere else that uses the metadata.
No ticket; this is a fix for an issue accidentally introduced in https://github.com/Kong/docs.konghq.com/pull/3210.
Currently, plugin pages all display "Index" as the page title; for example, see https://docs.konghq.com/hub/kong-inc/basic-auth/ (look at the browser tab label).
Compare browser tab label on https://deploy-preview-3234--kongdocs.netlify.app/hub/kong-inc/basic-auth/ with  https://docs.konghq.com/hub/kong-inc/basic-auth/. The Netlify preview version should have the plugin name. 
=> Plugin page title adjustment

app/kubernetes-ingress-controller/2.0.x/guides/getting-started-istio.md
This PR updates the Istio guide for the Kong Kubernetes Ingress controller to a modern Istio version and fixes problems with the documentation.
This patch also expands beyond the original guide in the following ways:
- extended explanations about components designed to help improve understanding
- significantly more links, allowing readers to explore further outside of the guide's boundaries afterwards
- more concise command and output examples
Resolves https://github.com/Kong/kubernetes-ingress-controller/issues/1791
I've tested these examples successfully against a `v1.19` Kubernetes cluster on GKE.
=> docs: major updates of istio guide

app/_data/docs_nav_deck_1.8.x.yml, app/deck/1.8.x/guides/defaults.md
Documenting the decK defaults feature introduced in 1.8 (https://github.com/Kong/deck/pull/419). 
Going by Harry's responses on https://konghq.atlassian.net/browse/FTI-2356 and looking through the implementation PR in the decK repo, I documented only the core entities. However, based on Fel's last comment on the FTI ticket, it looks like it might be possible to set plugin defaults as well, as long as you know what the default values are? Not sure about this.
https://konghq.atlassian.net/browse/DOCU-1843
https://deploy-preview-3229--kongdocs.netlify.app/deck/1.8.x/guides/defaults/
=> [DOCU-1843] Guide for using defaults with decK

app/_hub/kong-inc/oauth2/0.1.x.md, app/_hub/kong-inc/oauth2/1.0.x.md, app/_hub/kong-inc/oauth2/index.md
Fixes heading levels for the OAuth2 Authentication section in https://docs.konghq.com/hub/kong-inc/oauth2/#oauth-20-flows
Fix to the issue: https://github.com/Kong/docs.konghq.com/issues/3214
Locally ran an instance of the docs platform and confirmed the heading levels are updated correctly
=> Fixes header levels in OAuth2 doc

app/_hub/kong-inc/session/index.md
This PR refactors the existing Sessions plugin documentation, fixes grammatical errors, and reduces sentence complexities.
The present tense has been enforced.
Word `Kong` has been removed to avoid repetitive usage and `**Plugin**` has been set with small `p` and bold style is removed on all of its occurrences.
To resolve the issue - https://github.com/Kong/docs.konghq.com/issues/3239
The page preview looks good.
https://deploy-preview-3249--kongdocs.netlify.app/hub/kong-inc/session/#usage
(Scroll a bit up as the permalink doesn't always land up at the correct place `USAGE` section)
=> Copyedit Sessions plugin documentation #3239

app/getting-started-guide/2.5.x/expose-services.md
When using DB-less mode, the admin API (and I'm assuming Kong Manager, but I don't know that to be true) doesn't support creating services to avoid config drift. This should clarify that for other folks going through the guide.
=> decK for DB-less mode in the getting-started-guide

app/404.html, app/_assets/stylesheets/pages/404.less
* Using `default` layout to prevent sidebar and extra content from showing up
* Adjusting the CSS to fit default layout (mainly margins) and bring in some branding colours
Expanding on the work done in https://github.com/Kong/docs.konghq.com/pull/3248. 
https://deploy-preview-3260--kongdocs.netlify.app/404
=> 404 page layout adjustments

app/gateway-oss/2.0.x/configuration.md, app/gateway-oss/2.1.x/configuration.md, app/gateway-oss/2.2.x/configuration.md, app/gateway-oss/2.3.x/configuration.md, app/gateway-oss/2.4.x/configuration.md, app/gateway-oss/2.5.x/configuration.md, app/gateway-oss/2.6.x/configuration.md
Mention Lua functions available in templating. 
https://github.com/Kong/kong/pull/6872
`os.getenv` is added in 2.6, also adding the description for other existing functions user can use in templating.
The feature is originally from a community issue https://github.com/Kong/kong/issues/6546.
=> docs(configuration) mention Lua functions available in templating

app/gateway-oss/2.5.x/getting-started/adding-consumers.md, app/gateway-oss/2.5.x/getting-started/configuring-a-grpc-service.md, app/gateway-oss/2.5.x/getting-started/configuring-a-service.md, app/gateway-oss/2.5.x/getting-started/enabling-plugins.md, app/gateway-oss/2.5.x/getting-started/quickstart.md
This PR tries to incline the Kong Gateway QuickStart guide as per the latest Kong Style document.
To resolve the issue - https://github.com/Kong/docs.konghq.com/issues/3205
The page previews look good
https://deploy-preview-3270--kongdocs.netlify.app/gateway-oss/2.5.x/getting-started/quickstart/
https://deploy-preview-3270--kongdocs.netlify.app/gateway-oss/2.5.x/getting-started/configuring-a-service/
https://deploy-preview-3270--kongdocs.netlify.app/gateway-oss/2.5.x/getting-started/configuring-a-grpc-service/
https://deploy-preview-3270--kongdocs.netlify.app/gateway-oss/2.5.x/getting-started/enabling-plugins/
https://deploy-preview-3270--kongdocs.netlify.app/gateway-oss/2.5.x/getting-started/adding-consumers/
=> Issue 3205 : Test and edit Kong Gateway (OSS) Quickstart guide

app/contributing/community.md
Given discussion with the Insomnia team regarding their Issue process, it would be in our (and the community's) best interest to stop assigning Issues to individual contributors (outside of the Kong org). 
* It puts pressure on a single individual to commit to that Issue even if they find it too complex after they start working on it
* It creates potential conflict between contributors vying to work on the same task
* It increases overhead for repo maintainers, who have to keep an eye on whether or not a PR is raised by a specific contributor for that specific Issue originally assigned to them
* Individuals outside of the Kong org also do not have the ability to assign Issues to themselves, so it puts onus on us to go through each Issue and assign it as comments appear
=> Cont Guidelines - Hackathon: rm Issue assignment

app/_data/kong_versions.yml
Updating decK version.
Merge when https://github.com/Kong/deck/pull/496 is merged.
https://deploy-preview-3262--kongdocs.netlify.app/deck/1.8.x/installation/ - version used in installation codeblock
=> chore: deck 1.8.2 release

app/_assets/stylesheets/page.less, app/_data/docs_nav_ce_2.6.x.yml, app/gateway-oss/2.6.x/admin-api.md
This is related to:
https://github.com/Kong/kong/pull/7895
This PR adds latest auto-generated docs including the change PR above made proposes. It also updates `page.less` to include `HTTP OPTIONS` and `HTTP HEAD` methods, and adds styles for them.
=> chore(*) styles and auto generated for 2.6

app/_hub/kong-inc/datadog/3.0.x.md, app/_hub/kong-inc/datadog/index.md
New environemnt variables for the datadog plugin. Also, plugin version was bumped.
The new datadog plugin version is being release alongside Kong 2.6.0.
I didn't test, just documented a community contribution (https://github.com/Kong/kong/pull/7463)
=> docs(datadog) env vars docs, version bump

app/kubernetes-ingress-controller/2.0.x/guides/getting-started-istio.md
@shaneutt if you want to make sure I didn't break anything.
@lena-larionova I think you're probably the best person on the docs team to discuss formatting changes with.
Followup on initial hasty review of guide
Complete writer review for a guide that's getting a lot of attention lately. Biggest overall changes:
- removed command/response tabs. In most cases, removed responses to install commands because they're often not included and are reasonably intuitive. In the case of `kubectl apply` tended to leave responses bc they show what's going on at what level in the cluster, but happy to discuss that choice.
- added ordered lists for instructions. Tends to leave a lot of whitespace after end of list, but makes instructions clearer. Moved explanations around to support this approach; did not …
=> [DOCU-1857] KIC beta: provide more thorough copyedit of Istio guide

app/_assets/stylesheets/page.less, app/_assets/stylesheets/pages/docs.less
* Nested ordered lists no longer get smaller and smaller
* Adjusted margins on list items and shrunk the massive margins at the ends of lists
Really awkward list styling, for example:
Compare the [old nested list styling](https://docs.konghq.com/konnect/org-management/okta-idp/) with [adjusted styling](https://deploy-preview-3280--kongdocs.netlify.app/konnect/org-management/okta-idp/).
=> [DOCU-1699] List styling improvements

app/contributing/style-guide.md
Add a line in our Best Practices table to use US English. 
* We have had contributions that don't use US English. 
* Consistency.
=> Cont Guidelines: add best practice to use US English

app/kubernetes-ingress-controller/2.0.x/guides/getting-started-istio.md, app/kubernetes-ingress-controller/2.0.x/references/version-compatibility.md
This adds a version compatibility reference which is relevant to our existing Istio guide and shows which versions of the KIC have been tested with Istio in order to use Kong as an Ingress Gateway into applications in the mesh network.
Resolves https://github.com/Kong/kubernetes-ingress-controller/issues/1859
The [KIC](https://github.com/kong/kubernetes-ingress-controller) now includes testing facilities to automatically test this:
=> docs: add istio version compat table

app/_hub/kong-inc/mtls-auth/index.md
Correcting "ssl_certifica_by_lua" to "ssl_certificate_by_lua" to correctly name the phase used in the Client Certificate request.
Typo of "ssl_certifica_by_lua" needed to be corrected to "ssl_certificate_by_lua".
There was a typo that needed correcting.
Nothing to test.
=> Minor correction to name of Lua phase

README.md, app/_data/docs_nav_contributing.yml, app/_includes/md/README.md, app/contributing/includes.md
Adding guidelines for using includes to the contributing guide, and adding links to the new instructions from both the site and include directory READMEs.
Why the contributing guide and not something internal? Because there's no reason to hide these instructions, and if anyone runs into issues, we can send them a link to the guide.
https://deploy-preview-3285--kongdocs.netlify.app/contributing/includes/
=> [DOCU-1714] Guidelines for using includes

app/_data/docs_nav_konnect.yml, app/konnect/dev-portal/customization/customization-overview.md, app/konnect/dev-portal/index.md
Move customization content from entry file to Customization Overview. 
Part of the Konnect Dev Portal (cloud) docs reorg to increase usability. 
https://deploy-preview-3289--kongdocs.netlify.app/konnect/dev-portal/customization/customization-overview/
=> [DOCU-1877] Konnect Dev Portal: add Customization Overview

app/_assets/stylesheets/header.less, app/_includes/nav-v2.html, gulpfile.js, spec/home_spec.rb
Commenting out promo banner components to remove the Hackathon banner from the doc site.
Also removing the cookie policy margin section of `header.less`; the section has been commented out for the past two years and the navbar has long since been redesigned to account for the cookie policy.
To do: add info on how to edit the promo banner to our team Confluence.
Hackthon is over, we don't currently need any banner.
Make sure to test a variety of pages in the preview: plugin hub, landing page, content pages; also test scrolling down the page and resizing down to mobile.
https://deploy-preview-3290--kongdocs.netlify.app/
https://deploy-preview-3290--kongdocs.netlify.app/hub
=> Remove hackathon banner

app/deck/1.8.x/guides/getting-started.md
* Improving grammar, phrasing, clarity of information, and formatting in decK getting started guide
* Split codeblocks that were just lists of commands into steps that explain what you're doing and why
* Added a couple of commands for better understanding of the process (`deck ping` to check connection, sample curl request to check your config was pushed)
Usability. The decK docs have been neglected for a long time, and we have a lot of people using decK.
TBA
=> [DOCU-1885] Clean up decK getting started guide

app/enterprise/changelog.md
v2.6.0.0 beta changelog - includes [OSS v2.6.0 changelog](https://github.com/Kong/kong/blob/master/CHANGELOG.md#260) as well as Enterprise additions included on the [Internal changelong on Confluence](https://konghq.atlassian.net/wiki/spaces/FTT/pages/2587787325/Kong+Enterprise+2.6.0.0).
v2.6.0.0 Beta is scheduled for release Tuesday, 9/28/
=> [DOCU-1731]Docs/2.6 beta changelog ee

app/_data/docs_nav_konnect.yml, app/konnect/migrate.md
Guide for migrating from a self-hosted Kong Gateway setup to Konnect Cloud. 
* Convert object configurations with decK
* Add dev portal documents with decK
* Decide what to do with your data planes, then power down old ones + their datastores, if those exist
* Do all the other things manually using a bunch of other guides
Used decK to test as much as possible; the rest is manual and hard to write concrete steps for. The whole process is mostly "use deck to convert your configuration, then add everything else manually, therefore follow these other guides".
Guide based on personal testing, demos, and Michael Heap's blog: https://konghq.com/blog/migrating-kong-gateway-konnect/. 
Need a migration guide between self-hosted and cloud deployments. …
=> [DOCU-1122][DOCU-1094] Migration guide from gateway to Konnect

app/_assets/stylesheets/badges.less, app/_includes/header.html, app/_layouts/docs-v2.html, app/_layouts/extension.html, app/getting-started-guide/2.6.x/dev-portal.md, app/getting-started-guide/2.6.x/manage-teams.md, app/getting-started-guide/2.6.x/overview.md, app/getting-started-guide/2.6.x/protect-services.md
* Adding links to badges that appear in page titles, linking off to pricing page
* Adding `aria-label` for links, following WGAC guidelines: https://www.w3.org/WAI/WCAG21/Techniques/aria/ARIA8.html
* I considered adding tooltips but that's more of a nice-to-have and doesn't add much for accessibility
* Removing Konnect Enterprise subscription banner in favor of badges in plugins
* Replacing banners in Getting Started Guide with either badges, explanations, or simplified them so that badges aren't needed
* Labelling getting started guide dev portal and RBAC pages as enterprise
Badges are not accessible. If someone is visually impaired or uses a screenreader, the badge gets passed over completely and they have no way of knowing it exists.
For plugins: request from Gayle for jq plugin, as we …
=> [DOCU-1856][DOCU-1893] Accessible badges

app/_hub/kong-inc/route-by-header/index.md
Added 2.5.x compatibility in list.
This plugin works correctly on 2.5.0 but is missing from the documentations as a supported version. I believe this is due to confusion earlier on deprecation of this plugin which was a decision that was later reversed as I understand it. Ref: https://konghq.atlassian.net/browse/FT-1695
=> Added 2.5.x compatibility

app/kubernetes-ingress-controller/2.0.x/guides/using-udpingress.md
Somehow the port flag on `dig` didn't make it into the examples, this fixes that.
=> fix: port missing in dig example

app/enterprise/2.6.x/deployment/installation/amazon-linux-2.md, app/enterprise/2.6.x/deployment/installation/amazon-linux.md, app/enterprise/2.6.x/deployment/installation/centos.md, app/enterprise/2.6.x/deployment/installation/docker.md, app/enterprise/2.6.x/deployment/installation/rhel.md, app/enterprise/2.6.x/deployment/installation/ubuntu.md
Adding link classes to installation banners.
Easier tracking for link clicks.
Example link: https://deploy-preview-3334--kongdocs.netlify.app/enterprise/2.6.x/deployment/installation/ubuntu/
=> [DOCU-1938] Add link classes

app/gateway-oss/2.7.x/plugin-development/custom-entities.md
The guide used a syntax that we consider deprecated in 2.7.0
The hash-like syntax was deprecated in https://github.com/Kong/kong/pull/7942
=> docs(plugin-development guide) use array-like DAOs

app/_assets/stylesheets/page.less, app/_assets/stylesheets/pages/docs.less
Fixing blockquote styling so that unstyled `>` content is simpler. 
(Also got rid of .reading-time element, we removed read time from pages a long time ago).
Too many elements were picking up the note styling, so we had pages full of blue blocks: https://docs.konghq.com/kubernetes-ingress-controller/2.0.x/references/annotations/
https://docs.konghq.com/enterprise/2.6.x/support-policy/
https://deploy-preview-3344--kongdocs.netlify.app/enterprise/2.6.x/support-policy/
https://deploy-preview-3344--kongdocs.netlify.app/kubernetes-ingress-controller/2.0.x/references/annotations/
=> Fix blockquote styling

app/contributing/community.md
Update Community instructions to include information about forking (rather than branching straight from our repo). 
Kong GitHub permissions have changed. 
@lena-larionova please ensure I have the right/common/preferred forking workflow down. 
https://deploy-preview-3354--kongdocs.netlify.app/contributing/community/
=> [DOCU-1965] Community: update instructions for forking

app/mesh/1.2.x/features/fips-support.md, app/mesh/1.2.x/installation/macos.md, app/mesh/1.3.x/features/fips-support.md, app/mesh/1.3.x/installation/macos.md, app/mesh/1.4.x/features/fips-support.md, app/mesh/1.4.x/installation/macos.md
Note that FIPS compliance is not supported on macOS (nor on Windows, but we're not shipping Windows yet ...)
https://konghq.atlassian.net/browse/DOCU-1934 and see more detailed rationale in linked Trello code task
Tested locally for versions 1.2.x, 1.3.x, 1.4.x (FIPS feature and macOS install pages). FIPS compliance shipped with version 1.2.0.
See:
https://deploy-preview-3357--kongdocs.netlify.app/mesh/1.4.x/installation/macos/
https://deploy-preview-3357--kongdocs.netlify.app/mesh/1.4.x/features/fips-support/
and corresponding pages for versions 1.3.x and 1.2.x
=> [DOCU-1934] note that FIPS compliance is not supported on macOS

app/_hub/kong-inc/kafka-log/index.md, app/_hub/kong-inc/kafka-upstream/index.md
* Add note about Kafka Zookeeper to Kafka Log and Kafka Upstream plugin documentation. 
Kafka is no longer requiring or removing ZooKeeper. 
https://konghq.atlassian.net/browse/DOCU-916
=> [DOCU-916] Add note about Kafka ZooKeeper

app/enterprise/0.36-x/oasconfig.md
Gateway v. 0.36 endpoint `/oas-config` is deprecated and no longer maintained. Added a warning and directed users over to Insomnia and Inso CLI. 
Screenshot says `aos` not `oas`, I've fixed this. 
https://deploy-preview-3363--kongdocs.netlify.app/enterprise/0.36-x/oasconfig/
=> [DOCU-811] Gateway: Add deprecated endpoint note

.gitignore, app/_includes/md/admin-listen.md, app/enterprise/2.6.x/deployment/installation/amazon-linux-2.md, app/enterprise/2.6.x/deployment/installation/amazon-linux.md, app/enterprise/2.6.x/deployment/installation/centos.md, app/enterprise/2.6.x/deployment/installation/docker.md, app/enterprise/2.6.x/deployment/installation/rhel.md, app/enterprise/2.6.x/deployment/installation/ubuntu.md, app/enterprise/2.6.x/kong-manager/networking/configuration.md, app/enterprise/2.6.x/network.md, app/enterprise/2.6.x/plugins/oidc-cognito.md, app/enterprise/2.6.x/proxy.md, app/enterprise/2.6.x/start-kong-securely.md, app/enterprise/2.6.x/vitals/vitals-influx-strategy.md, app/gateway-oss/2.6.x/network.md, app/gateway-oss/2.6.x/proxy.md, app/install/docker.md
Expanding on https://github.com/Kong/docs.konghq.com-private/pull/689.
* Creating a reusable `include` file with the `admin_listen` warning with a long and short version. Long version is for examples that set `admin_listen`, short is for mentions of `admin_listen` without a full example.
* Ran a search and added the warning to 2.6.x versions of content in `/gateway-oss`, `/install`, and `/enterprise` docs.
* Fixing the gitignore file, it was catching the `/install/` directory as well as the root install file. Needed to fix to get the Docker topic updated.
From Rob Serafini on original PR:
> The admin_listen in the example code in our docs (all over the place) causes kong to listen for admin api requests from any IP address. This example is useful for developers trying Kong out, but should …
=> [DOCU-1982] admin_listen port warning

app/_hub/kong-inc/prometheus/index.md
* Add `per_consumer` to Prometheus plugin docs
* Update Prometheus plugin docs example with new options and remove legacy ones
* `per_consumer` exists in Kong code since https://github.com/Kong/kong/commit/7e205b0fb3c1536526943e856e38943dfc8b9a10
* updated example contains outdated informations
Changes have been locally tested using `make run` and new doc preview in browser.
=> docs: add prom `per_consumer` option and update example

app/mesh/1.4.x/features/opa.md
OPA policy requires an explicit http protocol tag/annotation for the mesh config. This PR adds relevant content. DO NOT MERGE/APPROVE, WAITING ON TECH REVIEW TO ADD TO OTHER VERSIONS.
PTAL @parkanzky @jpeach @scottslowe (tagging y'all bc timezones, otherwise can tag team-octo)
n.b. This content is mostly a dupe of the linked content in the Kuma docs, with the exception that the tag/annotation is explicitly _required_. (Probably should clean up Kuma docs here too but OPA policy is the only thing that seems to break without it.)
https://konghq.atlassian.net/browse/DOCU-1712
Tested content locally on site.
https://deploy-preview-3361--kongdocs.netlify.app/mesh/1.4.x/features/opa/#usage
=> [DOCU-1712] add required http protocol to opa doc for mesh

app/_includes/docs-sidebar.html, app/_includes/nav-v2.html, app/contributing/terms.md, archive/studio/old/1.0.x/debugging-with-insomnia.md
Update Insomnia docs links
Docs for Insomnia live at new URL: https://docs.insomnia.rest/
=> [DOCU-1998] update Insomnia docs links

app/contributing/style-guide.md
Add a note to differentiate "gateway" from "Gateway"
Consistency and clarification of how we use this term in different contexts.
Link TBA.
=> [DOCU-1995] Style Guide: note about gateway capitalization

app/_hub/kong-inc/jq/index.md, app/konnect/deployment/index.md, app/konnect/dev-portal/applications/application-overview.md, app/konnect/dev-portal/applications/disable-app-reg.md, app/konnect/dev-portal/applications/enable-app-reg.md, app/konnect/runtime-manager/gateway-runtime-docker.md, app/konnect/runtime-manager/gateway-runtime-kubernetes.md, app/konnect/updates.md
Konnect deploy (DOCU-1974):
* Adding changelog entry with app reg tagging and 2.6.x support info
* Updating version numbers in Runtime Manager setup topics
* Adding note to jq plugin (we have similar notes for OPA and mocking plugins from the last release)
Tags for application registration plugins (DOCU-1976):
* Added info about the new tags to the app reg overview
* linking off to said info from enable and disable app reg topics
* minor language cleanup to simplify app reg docs; got rid of a bunch of extra screenshots
Konnect deploy Nov 10th. Missed the notification as it got buried in all the other SMT tickets in the production channel.
Support for 2.6.0.0 was added earlier but was not reflected in the UI until last week, so rolling it into this update.
(Accidentally pushed both tickets …
=> [DOCU-1974][DOCU-1976] Konnect: Support for Gateway 2.6 and app reg tagging

app/_assets/stylesheets/pages/landing-page.less, app/_data/landing_page.yml, app/_includes/md/gateway-ports.md, app/_layouts/landing-page.html, app/contributing/variables.md, app/konnect-platform/guides.md, app/konnect-platform/index.md, app/konnect/index.md, app/konnect/key-concepts-and-terms.md, app/konnect/migrate.md
* Changing instances of "self-hosted" to "self-managed"
* Removing some "self-hosted" labels from the landing page altogether, as they are adding unnecessary complexity
"Self-hosted" is not the correct term, it should be "self-managed". This has been set for a while, but we've never gone through to docs to fix this.
Main changes are on the landing page: https://deploy-preview-3380--kongdocs.netlify.app/
=> Fix "self-hosted" terminology

app/kubernetes-ingress-controller/2.0.x/guides/configuring-https-redirect.md
Suggestion to change the http response code cited in the documentation for setting up https redirects on kong gateway routes. This may be applicable to other areas of the documentation outside of the kubernetes ingress controller, if that's the case I'm happy to add those to this PR if someone can point them out.
Per the Mozilla Developer Web Docs on http 308 
> A browser redirects to this page and search engines update their links to the resource ... The request method and the 
> body will not be altered, whereas 301 may incorrectly sometimes be changed to a GET method.
curl and other utilities that rely on it (including Postman) exhibit this behavior when they receive http 301 in response to a POST request. I suggest changing this documentation to use code 308 so that clients are still …
=> use code 308 instead of 301 for https redirects

app/mesh/1.5.x/features/rbac.md
Otherwise the example doesn't show what it's supposed to and the final request won't be denied.
=> docs(mesh/rbac) add note about LOCALHOST_IS_ADMIN for example

app/gateway/2.6.x/install-and-run/macos.md
Fixing broken link.
Broken link.
Looked for the same error throughout the docs, this is the only place place it exists. Other installation topics also have correct links.
https://deploy-preview-3389--kongdocs.netlify.app/gateway/2.6.x/install-and-run/macos/
=> [DOCU-2040] Fix link to getting started guide

app/gateway/2.6.x/plugin-development/custom-logic.md
* Add tabs to plugin dev guide, custom logic page, to separate lists of Enterprise and OSS plugins
* Add Enterprise plugin table - missed in the doc merge
* Add missing plugins: jq, mocking, opa, grpc-gateway, and grpc-web
* Note for correlation ID plugin and labels for Free vs OSS
To find all of this info, I used my install of Kong Gateway 2.6 and ran 
`find . | xargs grep  \.PRIORITY`
Missing Enterprise plugins from plugin execution order table.
Preview: https://deploy-preview-3393--kongdocs.netlify.app/gateway/2.6.x/plugin-development/custom-logic/#plugins-execution-order
=> [DOCU-2041] Add enterprise plugin execution order and missing plugins

app/gateway/2.6.x/plugin-development/custom-logic.md
Removing one extra line from the plugin priority table.
The OSS/Free mode table should have two entries for correlation ID, but the Enterprise table should only have one. Accidentally added two entries to both.
TBA
=> Remove extra correlation-id entry

app/gateway/2.6.x/plan-and-deploy/hybrid-mode/hybrid-mode-setup.md
Add a warning to the TLS mode section instructing users to use PKI mode if they place an intermediate TLS-aware proxy between CP and DP nodes.
Hybrid shared mTLS forcibly sets SNI to `kong_clustering`. Intermediate TLS proxies that use SNI to route upstream will almost certainly not recognize this and will misroute traffic or present the wrong certificate. PKI mode allows explicitly setting SNI to the CP hostname, which should be recognized if the intermediate is properly configured.
We do not currently set SNI by default in PKI mode (we probably should), so this instructs users to set that config value also.
Await Netlify to see if I broke the warning box.
=> doc(hybrid) add warning for intermediate proxy

app/gateway/2.6.x/developer-portal/working-with-templates.md
This change applies to self-managed Dev Portal. In "Working with Templates", I added a note that you can add the property `showExtensions` and set it to `true` to show custom properties. 
Closes [TDX-1631](https://konghq.atlassian.net/browse/TDX-1631) (not part of 2.7)
https://deploy-preview-3401--kongdocs.netlify.app/gateway/2.6.x/developer-portal/working-with-templates/#show-custom-properties
=> [TDX-1631] Dev Portal: Add showExtensions option

app/_data/kong_versions.yml
Updating metadata for latest patch versions.
Patch releases went out last week, see changelog: https://docs.konghq.com/gateway/changelog/
See versions in https://deploy-preview-3403--kongdocs.netlify.app/gateway/2.6.x/install-and-run/docker/ and  https://deploy-preview-3403--kongdocs.netlify.app/enterprise/2.5.x/deployment/installation/docker/
=> Update Gateway patch versions

app/mesh/1.5.x/features/rbac.md
Incorrect YAML indentation in example
Should be the following
```
$ CSR=$(cat backend-owner.csr | base64 | tr -d "\n") && echo "apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
name: backend-owner
spec:
request: $CSR
signerName: kubernetes.io/kube-apiserver-client
usages:
- client auth" | kubectl apply -f -
```
=> Incorrect YAML indentation

app/_layouts/extension.html
Add list of `site.data.kong_versions_gateway` versions to the plugin doc. Currently, the doc isn't picking up 2.6.x because it's only generating from the old split CE/EE lists.
Currently, the doc isn't picking up 2.6.x because it's only generating from the old split CE/EE lists. 
For example, this plugin is compatible with 2.6.x but the live doc has no versions in the compatibility list (bottom of right sidebar): https://docs.konghq.com/hub/kong-inc/jq/, even though the [source file](https://github.com/Kong/docs.konghq.com/blame/main/app/_hub/kong-inc/jq/index.md#L37) includes the version.
All Kong plugins should now have 2.6.x in the sidebar. For example, see https://deploy-preview-3416--kongdocs.netlify.app/hub/kong-inc/jq/, or …
=> Generate combined gateway versions

app/gateway/2.6.x/install-and-run/amazon-linux.md, app/gateway/2.6.x/install-and-run/debian.md
Amazon Linux 2 was released in 2017 and Amazon Linux 1 EOL including an extention was December 30, 2020
Debian Stretch was released in 2017 and Jessie was EOL was June 30, 2020 (ELTS is 2022).
This doesn't change that we release packages for these releases and folks will be able to interprit where to locate them
based on the installation instructions it simply doesn't actively document how to download / install them.
Arguably we should stop doing new releases to EOL releases and only to patch / security but that's a product question I won't explore right now
=> docs(installation): nuke amazonlinux 1 and jessie install links

app/gateway/2.6.x/install-and-run/amazon-linux.md, app/gateway/2.6.x/install-and-run/centos.md, app/gateway/2.6.x/install-and-run/debian.md, app/gateway/2.6.x/install-and-run/rhel.md, app/gateway/2.6.x/install-and-run/ubuntu.md
Install an explicit version when installing from our yum and apt repository for verbosity and anti-failure
More verbose is better. Folks that are fluent in yum / apt will know the package version isn't explicitely required but having it by default is better than not.
Ensures that the customer knows exactly what package is being installed
=> chore(installation): pin the apt and yum repository version explicitely

app/_data/docs_nav_gateway_2.6.x.yml
Add version support policy to Gateway nav.
Request from CRE. We used to have a link to this policy in the EE nav and now it's hard to find.
See entry under introduction: https://deploy-preview-3422--kongdocs.netlify.app/gateway/
=> Add support policy to nav

app/mesh/1.5.x/features/rbac.md
Fix error in RBAC example for Kubernetes
=> docs(mesh/rbac) fix YAML example indentation

app/gateway/2.6.x/reference/external-plugins.md
Add a space before `[go-pdk]()`.
Documentation format.
None
=> docs: update external-plugins to have a space

app/_data/tables/plugin_index.yml
Adding jq plugin to plugin compatibility table.
Plugin was missing.
https://deploy-preview-3434--kongdocs.netlify.app/konnect-platform/compatibility/plugins/
=> [DOCU-2026] Add jq plugin to compatibility index

app/_assets/stylesheets/hub-landing-page.less, app/_hub/index.html, app/gateway/2.6.x/plugin-development/access-the-datastore.md, app/gateway/2.6.x/plugin-development/admin-api.md, app/gateway/2.6.x/plugin-development/custom-entities.md, app/gateway/2.6.x/plugin-development/custom-logic.md, app/gateway/2.6.x/plugin-development/distribution.md, app/gateway/2.6.x/plugin-development/entities-cache.md, app/gateway/2.6.x/plugin-development/file-structure.md, app/gateway/2.6.x/plugin-development/index.md, app/gateway/2.6.x/plugin-development/plugin-configuration.md, app/gateway/2.6.x/plugin-development/tests.md
Main change in this PR: adding the plugin development guides to the Plugin Hub navigation, and fixing the navigation so that it doesn't cut off the bottom.
Other changes: light copyedit of the Plugin Development Guide, mostly removing redundant headers, updating note styling, and fixing minor phrasing/grammar issues. Slightly heavier copyedit on `distribution.md`, as it was really hard to read in its current state.
Was asked to add the plugin dev content to the plugin hub nav, as they're hard to find. 
Beyond that, the plugin dev guide hasn't been edited in years and really needs help.
Menu additions: https://deploy-preview-3435--kongdocs.netlify.app/hub/
Plugin dev guide: https://deploy-preview-3435--kongdocs.netlify.app/gateway/2.6.x/plugin-development/
=> [DOCU-2042] Add plugin dev guides to plugin hub; copyedit

app/gateway/2.7.x/admin-api/index.md, app/gateway/2.7.x/reference/proxy.md
Add doc for TLS passthrough routing, a new feature being added to 2.7.
The original PR is at https://github.com/Kong/kong/pull/6757.
=> doc(router) add docs for TLS passthrough

app/robots.txt, netlify.toml
Some deploy previews are being indexed by Google. This PR will adds a `disallow` rule to `robots.txt` to stop all search engines indexing the content unless `JEKYLL_ENV` is set to `production` (done via `netlify.toml`)
Deploy previews are being indexed, we'd like them not to be:
https://master--kongdocs.netlify.app/enterprise/1.3-x/kong-for-kubernetes/install/
https://marcoam-patch-3--kongdocs.netlify.app/enterprise/2.1.x/kong-for-kubernetes/install-on-kubernetes/
Visit `/robots.txt` in a deploy preview and it should contain the following:
```
User-agent: *
Disallow: /
```
Visit it in production and it should contain:
```
User-agent: *
Disallow: /enterprise/*
Disallow: /mesh/1.0*
Disallow: /mesh/1.1*
Disallow: /mesh/1.2*
Disallow: /gateway-oss/*
Disallow: …
```
=> Disable robots.txt on non-main deploys

app/deck/1.8.x/faqs.md
Fixing error that's breaking the page and leading to a 404.
Copy-paste error, broken page: https://docs.konghq.com/deck/1.8.x/faqs/
TBA
=> Fix copy-paste error in decK doc

app/konnect/runtime-manager/gateway-runtime-conf.md, app/konnect/runtime-manager/gateway-runtime-docker.md, app/konnect/runtime-manager/gateway-runtime-kubernetes.md, app/konnect/runtime-manager/runtime-parameter-reference.md
Removing `anonymous_reports=off` setting from Konnect Cloud docs.
For a gateway data plane, the `anonymous_reports` setting defaults to `on`. In the doc and the Konnect UI, the setting was being explicitly overwritten and users were told to set it to `off`. This is no longer happening in the UI, so the doc is following suit (see https://konghq.atlassian.net/browse/KHCP-1509).
https://deploy-preview-3439--kongdocs.netlify.app/konnect/runtime-manager/gateway-runtime-docker/
https://deploy-preview-3439--kongdocs.netlify.app/konnect/runtime-manager/gateway-runtime-conf/
https://deploy-preview-3439--kongdocs.netlify.app/konnect/runtime-manager/gateway-runtime-kubernetes/
https://deploy-preview-3439--kongdocs.netlify.app/konnect/runtime-manager/runtime-parameter-reference/
=> [DOCU-1535] Remove anonymous_reports default override from Konnect Cloud

app/_hub/inspur/apig-response-transform/index.md, app/_hub/kong-inc/forward-proxy/index.md, app/_hub/kong-inc/grpc-gateway/0.1.x.md, app/_hub/kong-inc/grpc-gateway/index.md, app/_hub/kong-inc/grpc-web/0.1.x.md, app/_hub/kong-inc/grpc-web/0.2.x.md, app/_hub/kong-inc/grpc-web/index.md, app/_hub/kong-inc/opa/index.md, app/_hub/kong-inc/openwhisk/index.md, app/_hub/kong-inc/response-transformer-advanced/index.md, app/_hub/yesinteractive/kong-jwt2header/index.md, app/_layouts/extension.html
Fixing plugin template to parse the `dbless_compatible` field correctly, and update some formatting and values in plugin docs for consistency & accuracy.
Issue reported on Slack. Plugins were showing two different values for db-less compatibility.
Spot check some Kong plugins: if the plugin mentions db-less support, the main body text and the sidebar entry should say the same thing.
https://deploy-preview-3444--kongdocs.netlify.app/hub/
[Correlation ID plugin](https://deploy-preview-3444--kongdocs.netlify.app/hub/kong-inc/correlation-id/) (issue was reported here)
=> [DOCU-2067][DOCU-2069] Fix parsing of dbless_compatible field in plugins

app/_assets/stylesheets/pages/extension.less, app/_includes/header.html, app/_layouts/extension.html
Add a banner to older plugin versions. 
Removing non-existent `header_caption` field, it hasn't (ever?) been in use.
Note: The yellow is a bit different form our normal yellow banner tone. It's the new Kongponents yellow; I'll be updating all docs to use the new tones in a future PR.
See ticket; we have no visual distinction for older plugin docs, so it's easy to accidentally end up on an old page.
Open any kong-inc plugin doc and check latest version vs older version, for example:
* Latest: https://deploy-preview-3446--kongdocs.netlify.app/hub/kong-inc/application-registration/
* Older (see banner, check link): https://deploy-preview-3446--kongdocs.netlify.app/hub/kong-inc/application-registration/1.0.x.html
=> [DOCU-2045] Banner for older versions of plugins

app/_data/docs_nav_ce_2.4.x.yml, app/_data/docs_nav_ce_2.5.x.yml, app/_data/docs_nav_ee_2.3.x.yml, app/_data/docs_nav_ee_2.4.x.yml, app/_data/docs_nav_ee_2.5.x.yml, pdf-generation/list-versions.js
* Adding `gateway` to list of mapped paths
* Setting versioned URLs for old `/enterprise/` and `/gateway-oss/` landing pages
This should fix PDF generation.
Fixes two different errors:
* https://github.com/Kong/docs.konghq.com/runs/4257695434?check_suite_focus=true#step:10:18
Didn't add `gateway` to list of versions, so it didn't recognize the value
* https://github.com/Kong/docs.konghq.com/runs/4257745507?check_suite_focus=true#step:10:17
The `/enterprise/` and `/gateway-oss/` aliases no longer exist without versions, because the latest version is `/gateway/`. On a live doc, this would be a redirect; on a local build (or a PDF build), it reads as a broken link, so the page can't be found.
N/A, have to merge and then test.
=> [DOCU-2046] Fix PDF gen (post single-sourcing)

app/_data/docs_nav_gateway_2.6.x.yml, jekyll-dev.yml, jekyll.yml
* Updating page scope so that it picks up the correct version for install topics.
* Setting absolute version URL for 2.6 so that it doesn't link to 2.7.
2.7 release task.
* Correct version appears in install topics, eg https://deploy-preview-3454--kongdocs.netlify.app/gateway/2.7.x/install-and-run/docker/
* The gateway 2.6.x introduction nav entry links to https://deploy-preview-3454--kongdocs.netlify.app/gateway/2.6.x/
=> chore/ Update 2.7 scope

app/_data/docs_nav_ce_2.0.x.yml, app/_data/docs_nav_ce_2.1.x.yml, app/_data/docs_nav_ce_2.2.x.yml, app/_data/docs_nav_ce_2.3.x.yml, app/_data/docs_nav_ce_2.4.x.yml, app/_data/docs_nav_ce_2.5.x.yml, app/_data/docs_nav_ee_1.5.x.yml, app/_data/docs_nav_ee_2.1.x.yml, app/_data/docs_nav_ee_2.2.x.yml, app/_data/docs_nav_ee_2.3.x.yml, app/_data/docs_nav_ee_2.4.x.yml, app/_data/docs_nav_ee_2.5.x.yml
Set getting started guide links in old split doc navs to go to their respective versions.
Issue https://github.com/Kong/docs.konghq.com/issues/3450.
Check nav entries for the "Getting Started Guide"  in `/enterprise/` and `/gateway-oss/` docs, they should go to their respective guide versions.
For example, check:
https://deploy-preview-3453--kongdocs.netlify.app/enterprise/2.5.x/
https://deploy-preview-3453--kongdocs.netlify.app/gateway-oss/2.3.x/
=> Versioned getting started guide URLs

app/gateway/2.6.x/plugin-development/custom-logic.md
Add route by header plugin based on its priority: https://github.com/Kong/kong-ee/blob/d1161cc2172159e98f7385b864894294092e9daf/plugins-ee/route-by-header/kong/plugins/route-by-header/handler.lua#L17
Plugin is missing from the list.
TBA
=> [DOCU-2075] Add route-by-header plugin to plugin priority list

app/_data/kong_versions.yml, app/_hub/kong-inc/openid-connect/index.md, app/gateway/changelog.md
Changelog for the Enterprise Gateway 2.6.0.2 patch release and doc update for OIDC param `session_redis_cluster_nodes`.
Patch release.
[Changelog](https://deploy-preview-3456--kongdocs.netlify.app/gateway/changelog/)
=> Release: Kong Gateway 2.6.0.2

app/_hub/kong-inc/mtls-auth/index.md
Edit plugin description to mention support for server-supplied certs.
Plugin supports both upstream and downstream mTLS; issue reported on Slack.
Preview: https://deploy-preview-3457--kongdocs.netlify.app/hub/kong-inc/mtls-auth/
=> Update mTLS plugin description

app/_data/extensions/kong-inc/forward-proxy/versions.yml, app/_hub/kong-inc/forward-proxy/1.0.5.md
Adds two auth parameters,`auth_username` and `auth_password`. 
https://github.com/Kong/kong-ee/pull/2611
Preview: https://deploy-preview-3458--kongdocs.netlify.app/hub/kong-inc/forward-proxy/
**Reviewers**: please ignore the file `app/_hub/kong-inc/forward-proxy/1.0.5.md`, it's the previous version.
=> [DOCU-2073] Forward proxy auth parameters

app/gateway/2.6.x/configure/auth/kong-manager/oidc.md
Fixing a typo.
Typo fix. 'Requires' was spelled incorrectly. This PR fixes that.
=> Fixing typo of 'requires'.

app/enterprise/1.3-x/db-encryption.md, app/enterprise/1.5.x/db-encryption.md, app/enterprise/2.1.x/db-encryption.md, app/enterprise/2.2.x/db-encryption.md, app/enterprise/2.3.x/db-encryption.md, app/enterprise/2.4.x/db-encryption.md, app/enterprise/2.5.x/db-encryption.md, app/gateway/2.6.x/plan-and-deploy/security/db-encryption.md
Mention keyring_blob_path in db-encryption document. The filed exists at
https://github.com/Kong/kong-ee/blob/master/kong.conf.default#L2473
=> Add `keyring_blob_path` to db-encryption guide

app/_hub/kong-inc/datadog/index.md, app/_hub/kong-inc/http-log/index.md, app/_hub/kong-inc/loggly/index.md, app/_hub/kong-inc/statsd/index.md, app/_hub/kong-inc/syslog/index.md, app/_hub/kong-inc/tcp-log/index.md, app/_hub/kong-inc/udp-log/index.md
Updating plugin protocol lists. 
Companion PR to https://github.com/Kong/docs.konghq.com/pull/3373.
To do: update Enterprise plugins once kong-ee has a 2.7 branch.
Support for TLS passthrough.
> If a plugin declares it supports all protocols like file-log:
https://github.com/Kong/kong/blob/master/kong/plugins/file-log/schema.lua#L7, we should add the
`tls_passthrough` to its list.
Preview link TBA
=> [DOCU-2061] Add tls_passthrough to supported plugins

app/gateway/2.6.x/vitals/vitals-prometheus-strategy.md
Added a warning to the page to make it clearer to users that they need to use the Kong statsd exporter forked image and not the public project which will not work with the supplied statsd mapping config
I didnt think it was very clear on this page that the statsd exporter was a private forked image from Kong, and that the mappings supplied would not work with the prometheus community image.
Deployed it to my cluster and my Grafana dashboards now work
=> Added warning around statsd exporter image

app/_data/extensions/kong-inc/zipkin/versions.yml, app/_hub/kong-inc/zipkin/1.3.x.md, app/_hub/kong-inc/zipkin/1.4.x.md
* Adding entry for `local_service_name` parameter. 
* Adding `ignore` option for `header_type` parameter
* Minor organizational cleanup to make param entries more readable
For reviewers: please review updates made in `app/_hub/kong-inc/zipkin/index.md`
https://github.com/Kong/kong-plugin-zipkin/pull/123
https://github.com/Kong/kong-plugin-zipkin/pull/99
https://deploy-preview-3476--kongdocs.netlify.app/hub/kong-inc/zipkin/
=> [DOCU-2092] Zipkin: Add local_service_name param and header_type: ignore

app/enterprise/2.1.x/admin-api/index.md, app/enterprise/2.2.x/admin-api/index.md, app/enterprise/2.3.x/admin-api/index.md, app/enterprise/2.4.x/admin-api/index.md, app/enterprise/2.5.x/admin-api/index.md
Adding `tls_verify`,`tls_verify_depth`, `ca_certificates`, and `url` parameters to the Gateway service object configuration in older Enterprise docs.
The feature was introduced in 2.1 but not added until we single-sourced the Gateway docs. 2.6.x versions onwards are up to date.
Changelog entry from 2.1: https://github.com/Kong/kong/blob/master/CHANGELOG.md#210
https://deploy-preview-3471--kongdocs.netlify.app/enterprise/2.5.x/admin-api/#service-object
=> [DOCU-2087] Add missing TLS parameters to enterprise docs

app/gateway/2.7.x/install-and-run/debian.md
Adding download and install instructions to the Debian doc for the `kong-enterprise-edition` package.
Support for Debian in 2.7.
Preview: https://deploy-preview-3472--kongdocs.netlify.app/gateway/2.7.x/install-and-run/debian/
=> [DOCU-2082] Enterprise install & download instructions for Debian

app/_data/extensions/kong-inc/rate-limiting/versions.yml, app/_hub/kong-inc/rate-limiting/2.2.x.md, app/_hub/kong-inc/rate-limiting/index.md
Bumping Rate Limiting plugin version.
Adding commit (https://github.com/Kong/docs.konghq.com/commit/d4781029a86d0062797c7648cfac806db5bfe06d) from closed PR #3339.
Had to split the content from https://github.com/Kong/docs.konghq.com/pull/3426 as `redis_username` is not making it into the 2.7 release, but the options in this PR are.
https://deploy-preview-3478--kongdocs.netlify.app/hub/kong-inc/rate-limiting/
=> Plugin: Rate limiting redis SSL properties

app/gateway/2.6.x/install-and-run/docker.md
Add missing copy code button to Docker install guide. 
Closes [DOCU-2098](https://konghq.atlassian.net/browse/DOCU-2098)
Reported missing copy code button.
=> [DOCU-2098] Add missing copy code to Docker install

app/gateway/2.6.x/install-and-run/docker.md
the PG hostname should point to the PG_Host_Name as it is confusing to say "DATABASE_NAME"
while running the Kong Gateway it is supposed to read the correct hostname been configured at the previous steps and not the DB name
=> Update docker.md to start a container with Kong Gateway

app/mesh/1.5.x/features/rbac.md
RBAC on Zone CP will be restricted by default in the next minor version of Kong Mesh
=> Kong Mesh: restricted RBAC on zone CP

app/_data/docs_nav_gateway_2.7.x.yml, app/_hub/kong-inc/rate-limiting-advanced/1.5.x.md, app/_hub/kong-inc/rate-limiting-advanced/index.md, app/gateway/2.7.x/admin-api/consumer-groups/examples.md, app/gateway/2.7.x/admin-api/consumer-groups/reference.md
Consumer groups doc.
* Admin API reference for consumer groups
* Admin API examples for consumer groups: cURL and HTTPie examples
* RLA plugin ref: added two new properties
**For reviewers:** ignore the file `app/_hub/kong-inc/rate-limiting-advanced/1.5.x.md` - this is a new file but with no new content, as a side-effect of the plugin doc versioning. Please review `app/_hub/kong-inc/rate-limiting-advanced/index.md` instead.
Consumer groups feature.
Tested all examples locally with a 2.7 preview build.
[API Reference](https://deploy-preview-3443--kongdocs.netlify.app/gateway/2.7.x/admin-api/consumer-groups/reference/)
[Examples](https://deploy-preview-3443--kongdocs.netlify.app/gateway/2.7.x/admin-api/consumer-groups/examples/)
[RLA plugin param …
=> [DOCU-2047] Consumer groups

app/_redirects, app/gateway/2.6.x/get-started/comprehensive/dev-portal.md
Closes [3487](https://github.com/Kong/docs.konghq.com/issues/3487)
Add two redirects for links that go to 404 from this page: https://docs.konghq.com/gateway/2.6.x/get-started/comprehensive/dev-portal/
Note that Administration and Configuration are menu items that are clicked to open sub-menus and not pages themselves. So I linked instead to a page within those sections.
=> [DOCU-2101] Add Dev Portal redirects

app/gateway/2.7.x/get-started/comprehensive/dev-portal.md, app/gateway/2.7.x/get-started/comprehensive/manage-teams.md, app/gateway/2.7.x/install-and-run/docker.md, app/gateway/2.7.x/vitals/vitals-prometheus-strategy.md
Copying over changes made in 2.6.x since the 2.7.x directory was created.
Based on the following merge: 4b676d1
No automatic change syncing between directories. Have to make these changes manually.
https://deploy-preview-3499--kongdocs.netlify.app/gateway/2.7.x/vitals/vitals-prometheus-strategy/#download-and-configure-statsd-exporter - added warning block
https://deploy-preview-3499--kongdocs.netlify.app/gateway/2.7.x/install-and-run/docker/ - editable fields in Docker install
=> chore/Sync 2.6.x and 2.7.x directories

app/_assets/stylesheets/pages/docs.less
Fixing nav overflow issue.
Nav gets cut off if the text is too long and has no whitespace breaks:
Check that nav entries wrap instead of cutting off: https://deploy-preview-3498--kongdocs.netlify.app/gateway/2.6.x/pdk/kong.service.response/
=> [bug fix] Let right ToC wrap instead of cutting off

app/gateway/2.7.x/configure/auth/kong-manager/oidc-mapping.md, app/gateway/2.7.x/install-and-run/upgrade-enterprise.md
Explain breaking change in OIDC for KM in v2.7.x and clarify value required for parameter.
CX request, testing new feature
Tested locally, Netlify pages:
- https://deploy-preview-3506--kongdocs.netlify.app/gateway/2.7.x/configure/auth/kong-manager/oidc-mapping/
- https://deploy-preview-3506--kongdocs.netlify.app/gateway/2.7.x/install-and-run/upgrade-enterprise/#kong-manager-upgrade-to-27x
=> clarify information about new oidc mapping for manager

app/enterprise/2.1.x/plugin-development/custom-entities.md, app/enterprise/2.2.x/plugin-development/custom-entities.md, app/enterprise/2.3.x/plugin-development/custom-entities.md, app/enterprise/2.4.x/plugin-development/custom-entities.md, app/enterprise/2.5.x/plugin-development/custom-entities.md, app/gateway-oss/2.0.x/plugin-development/custom-entities.md, app/gateway-oss/2.1.x/plugin-development/custom-entities.md, app/gateway-oss/2.2.x/plugin-development/custom-entities.md, app/gateway-oss/2.3.x/plugin-development/custom-entities.md, app/gateway-oss/2.4.x/plugin-development/custom-entities.md, app/gateway-oss/2.5.x/plugin-development/custom-entities.md, app/gateway/2.6.x/plugin-development/custom-entities.md, app/gateway/2.7.x/plugin-development/custom-entities.md, archive/enterprise/2.6.x/plugin-development/custom-entities.md, archive/gateway-oss/2.6.x/plugin-development/custom-entities.md
The update/upsert instructions in the plugin development guide had two extra brackets. This PR removes them from all 2.x versions of enterprise and OSS gateway.
Reported by a community user in https://github.com/Kong/kong/discussions/7616.
=> docs(gateway) fix plugin development guide about update/upsert

app/kubernetes-ingress-controller/1.0.x/guides/cert-manager.md, app/kubernetes-ingress-controller/1.1.x/guides/cert-manager.md, app/kubernetes-ingress-controller/1.2.x/guides/cert-manager.md, app/kubernetes-ingress-controller/1.3.x/guides/cert-manager.md, app/kubernetes-ingress-controller/2.0.x/guides/cert-manager.md
Update the link to install cert-manager as the [current link](https://docs.cert-manager.io/en/latest/getting-started/install/kubernetes.html) leads to 404
[Current link](https://docs.cert-manager.io/en/latest/getting-started/install/kubernetes.html) to cert-manager docs leads to 404
Check the new link (https://cert-manager.io/docs/installation/)
=> Update cert-manager docs link

app/_assets/javascripts/app.js, app/_plugins/navtabs.rb
Adding the ability to tab through navtab elements. 
Making docs accessible.
Tab through some tabs. Sample pages:
https://deploy-preview-3502--kongdocs.netlify.app/hub/kong-inc/basic-auth/
https://deploy-preview-3502--kongdocs.netlify.app/gateway/2.7.x/get-started/comprehensive/protect-services/
Use `tab` to move forward and `shift+tab` to move backward, and press the `Enter` key to switch to a tab.
=> [DOCU-1953] Make navtabs accessible

app/_data/extensions/kong-inc/rate-limiting-advanced/versions.yml
Adding 1.6.x to the Rate Limiting Advanced plugin's list of versions.
Plugin version was bumped, but I missed updating this metadata file.
https://deploy-preview-3505--kongdocs.netlify.app/hub/kong-inc/rate-limiting-advanced/ - check that versions 1.6.x, 1.5.x, and 1.4.x exist in the dropdown.
=> [bugfix] RLA plugin: add 1.6.x version

app/gateway/2.7.x/get-started/comprehensive/prepare.md
Adding a link to hybrid mode doc from the gateway getting started guide.
Resolves https://github.com/Kong/docs.konghq.com/issues/3484.
Check link in https://deploy-preview-3515--kongdocs.netlify.app/gateway/2.7.x/get-started/comprehensive/prepare/#optional-verify-control-plane-and-data-plane-connection.
=> Link to hybrid mode doc

app/_includes/head.html
Disabling cookie policy in local (`development`) and `preview` environments. 
OneTrust only applies to the `konghq.com` domain, so it doesn't register in dev and preview environments, and the policy banner loads every time you load a page. This is unnecessary and also very annoying when testing.
No cookie policy banner in the preview: https://deploy-preview-3503--kongdocs.netlify.app/
If we ever need to test something with the cookie policy banner in the future, will need to comment out `{% if jekyll.environment == "production" %}` and `{% endif %}` tags in the `head.html` include.
=> fix: Load cookie policy only on prod

app/_hub/kong-inc/mtls-auth/index.md
Update to resolve issue #3451
Adding in Konnect specific instructions to add certificates to a Kong instance for mtls.
#3451 
Used the instructions for a customer. Would recommend testing by using these instructions to add certificates
https://deploy-preview-3495--kongdocs.netlify.app/
=> Konnect instructions for Adding Certificate Authorities

app/mesh/1.5.x/features/kds-auth.md
Fixing link to point to latest version of Kuma docs, not a versioned page. 
Resolves https://github.com/Kong/docs.konghq.com/issues/3477.
Check link in https://deploy-preview-3516--kongdocs.netlify.app/mesh/1.5.x/features/kds-auth/#additional-security.
=> Fix link in mesh doc

app/gateway/2.7.x/install-and-run/index.md
Removing "OSS-only" badge from Debian install tile.
As of Gateway 2.7, support for Enterprise installations now exists and is documented.
See Debian tile: https://deploy-preview-3520--kongdocs.netlify.app/gateway/2.7.x/install-and-run/
=> Remove OSS-only label from Debian tile

app/enterprise/1.3-x/admin-api/db-encryption.md, app/enterprise/1.5.x/admin-api/db-encryption.md, app/enterprise/2.1.x/admin-api/db-encryption.md, app/enterprise/2.2.x/admin-api/db-encryption.md, app/enterprise/2.3.x/admin-api/db-encryption.md, app/enterprise/2.4.x/admin-api/db-encryption.md, app/enterprise/2.5.x/admin-api/db-encryption.md, app/gateway/2.6.x/admin-api/db-encryption.md, app/gateway/2.7.x/admin-api/db-encryption.md
* Fixing wrong attribute value for `/keyring/remove` from `id` to `key`.
* Fixing broken formatting
Broken formatting and wrong attribute name.
https://deploy-preview-3521--kongdocs.netlify.app/gateway/2.7.x/admin-api/db-encryption/
=> [DOCU-1973] Fix attribute and broken formatting in db keyring encryption

app/_hub/kong-inc/openid-connect/2.0.x.md, app/_hub/kong-inc/openid-connect/2.1.x.md, app/_hub/kong-inc/openid-connect/index.md
Fixing typo.
Typo, should be `config.scopes_required` instead of `scores`. Reported on Slack.
=> OIDC plugin: Fix typo in param name

app/_plugins/alias_generator.rb, app/_plugins/versions.rb, jekyll-dev.yml, jekyll.yml
This PR updates our alias generator to add an entry to the Netlify _redirects file instead of writing out a file with Javascript to redirect
Broken link checking can't follow JavaScript redirects, so we need to switch to HTTP redirects
Try out a page that gets redirected by an alias. Here's a list from production:
```
/kubernetes-ingress-controller/latest/deployment/admission-webhook	/kubernetes-ingress-controller/2.1.x/deployment/admission-webhook
/kubernetes-ingress-controller/latest/deployment/aks	/kubernetes-ingress-controller/2.1.x/deployment/aks
/kubernetes-ingress-controller/latest/references/annotations	/kubernetes-ingress-controller/2.1.x/references/annotations
/kubernetes-ingress-controller/latest/guides/cert-manager	/kubernetes-ingress-controller/2.1.x/guides/cert-manager …
```
=> Use Netlify _redirects for aliases

app/_assets/javascripts/app.js, app/_assets/stylesheets/badges.less, app/_assets/stylesheets/page.less
Adding tooltips to `FREE`, `ENTERPRISE`, `PLUS`, `OSS ONLY`, and `DB-LESS COMPATIBLE` badges. 
Didn't add a tooltip for the `BETA` badge, as I couldn't figure out what to say that wasn't obvious from the badge label.
Lots of confusion around the meaning of the badge labels, particularly the FREE and PLUS badges. 
Test in various scenarios:
* In-text labels, for example (need to adjust top margin): [Gateway intro](https://deploy-preview-3523--kongdocs.netlify.app/gateway/)
* H1 headers (page titles): [plugin page](https://deploy-preview-3523--kongdocs.netlify.app/hub/kong-inc/application-registration/) and [main doc page](https://deploy-preview-3523--kongdocs.netlify.app/gateway/2.7.x/vitals/vitals-reports/)
* Tables in main content body, for example in the [contributing …
=> [DOCU-2035] Badge tooltips

app/_hub/kong-inc/rate-limiting-advanced/index.md, app/gateway/2.7.x/admin-api/consumer-groups/examples.md, app/gateway/2.7.x/admin-api/consumer-groups/reference.md, app/gateway/changelog.md
Add notice about no declarative config support to 2.7 changelog, rate limiting advanced doc, and consumer groups docs.
Feature is not supported in decK.
https://deploy-preview-3539--kongdocs.netlify.app/gateway/2.7.x/admin-api/consumer-groups/examples/
https://deploy-preview-3539--kongdocs.netlify.app/gateway/changelog/#enterprise
=> [DOCU-2117] Consumer groups not supported with deck

app/mesh/1.5.x/features/vault.md
Add some missing comments for config fields. @jakubdyszkiewicz 
Purpose of some fields was unclear
https://deploy-preview-3541--kongdocs.netlify.app/mesh/1.5.x/features/vault/#navtab-id-1
=> docs(mesh): add comments to example Vault mTLS config

app/_assets/javascripts/app.js
Automatically close the module/version dropdown when the other is clicked
The version dropdown can currently overlap the module dropdown unexpectedly.
Open the version dropdown, then click on the module dropdown. The version dropdown should automatically be closed
=> Fix overlapping module/version selector dropdowns

app/gateway/2.6.x/admin-api/index.md, app/gateway/2.7.x/admin-api/index.md
The DB-less and Declarative config section was moved to _reference_ and the link on the admin API was not updated
Broken link
Search for "declarative config" on /gateway/2.7.x/admin-api/ and make sure it goes to the correct page
=> Fix broken links to DB-less and Declarative config on Admin API

app/_layouts/docs-v2.html, app/_layouts/extension.html, app/_plugins/environment_variables.rb
Update the "Edit this page" link on branches to point to the correct branch on GitHub
Builds are failing when new files are added on a branch as the "Edit this page" link points to a file that doesn't exist on `main` on GitHub
Check the "Edit this page" link on Netlify. It should point you to the `fix-edit-page-link` branch on GitHub
=> Fix Edit This Page link on branches

app/_data/docs_nav_konnect.yml, app/konnect/dev-portal/customization/custom-domain.md
* Add custom domain page to Cloud Dev Portal documentation
* Move "Customization Overview" to Customization toggle menu
Users need further information about the custom domain option for Cloud Dev Portal.
All content changes.
https://deploy-preview-3551--kongdocs.netlify.app/konnect/dev-portal/customization/custom-domain/
=> [DOCU-2123] Cloud Dev Portal: Add custom domain page

app/_assets/javascripts/copy-code-snippet-support.js
The existing replacement regex didn't support multiple line replacement as
it was missing the `m` modifier.
Multi-line replacement is required when there are multiple commands in a single code block
Fix copy to clipboard on pages such as https://docs.konghq.com/gateway/2.7.x/reference/clustering/ (search for `node A`)
Try copying the `node A` code block to your clipboard. There will be no `$` present in the review app, but the second command will be prefixed with a `$` on production
=> [DOCU-2138] Fix multi-line copy to clipboard

app/kubernetes-ingress-controller/1.0.x/guides/cert-manager.md, app/kubernetes-ingress-controller/1.1.x/guides/cert-manager.md, app/kubernetes-ingress-controller/1.2.x/guides/cert-manager.md, app/kubernetes-ingress-controller/1.3.x/guides/cert-manager.md, app/kubernetes-ingress-controller/2.0.x/guides/cert-manager.md, app/kubernetes-ingress-controller/2.1.x/guides/cert-manager.md
Update the apiVersion for ClusterIssuer from `cert-manager.io/v1alpha2` to `cert-manager.io/v1` as per https://cert-manager.io/docs/configuration/acme/dns01/route53/#creating-an-issuer-or-clusterissuer
The apiVersion `cert-manager.io/v1alpha2` was not recognized when the _ClusterIssuer_ object is created.
Follow the steps in https://docs.konghq.com/kubernetes-ingress-controller/1.3.x/guides/cert-manager/ except use `cert-manager.io/v1` as the apiVersion
=> Update apiVersion for ClusterIssuer to cert-manager.io/v1

app/_hub/kong-inc/exit-transformer/1.3-x.md, app/_hub/kong-inc/exit-transformer/index.md, app/_hub/kong-inc/jq/index.md, app/_hub/kong-inc/oauth2/0.1.x.md, app/_hub/kong-inc/oauth2/1.0.x.md, app/_hub/kong-inc/oauth2/index.md
Remove `k8s_examples: false` from all Kong, Inc. plugin metadata.
It's not clear why these were omitted in the first place--I'm guessing that they were removed because these plugins don't support DB-less mode (it's the common thread between them), but you can use KIC YAML configuration to configure these plugins for a DB-backed KIC+Kong instance.
We should provide KIC config for them as such. They're marked DB-less incompatible separately.
Optional review request to the rest of the team if someone else recalls some other reason we disabled these.
Awaiting Netlify to confirm examples appear.
=> fix(kic) restore K8S examples to Kong plugins

app/_data/docs_nav_mesh_1.1.x.yml, app/_data/docs_nav_mesh_1.2.x.yml, app/_data/docs_nav_mesh_1.3.x.yml, app/_data/docs_nav_mesh_1.4.x.yml, app/_data/docs_nav_mesh_1.5.x.yml, app/mesh/1.1.x/install.md, app/mesh/1.2.x/install.md, app/mesh/1.3.x/install.md, app/mesh/1.4.x/install.md, app/mesh/1.5.x/install.md
Removing marketplaces tab and nav link.
This link and marketplace posting is not maintained (it's still on Mesh 1.1). The alliances team is handling it separately instead, and all marketplaces/alliances links will live on the marketing site.
This content has already been removed for Gateway. See the DOCU ticket (DOCU-866) for more information.
https://deploy-preview-3568--kongdocs.netlify.app/mesh/1.5.x/install/ - no tab for "marketplaces", and no nav entry for it either.
=> [DOCU-866] Remove marketplaces install tab from mesh docs

app/_includes/docs-sidebar.html
Removing duplicate entry for Insomnia and updating the sidebar menu to match the one in the top nav of the site.
Inconsistent menus and an old duplicate link to Insomnia.
Check that the left sidebar dropdown on any doc page (eg https://deploy-preview-3566--kongdocs.netlify.app/gateway/) matches the Docs dropdown in the top navigation of the site. 
Insomnia link should go to docs.insomnia.rest, not support.insomnia.rest.
=> Make sidebar consistent with site top nav

app/enterprise/2.1.x/vitals/vitals-influx-strategy.md, app/enterprise/2.2.x/vitals/vitals-influx-strategy.md, app/enterprise/2.3.x/vitals/vitals-influx-strategy.md, app/enterprise/2.4.x/vitals/vitals-influx-strategy.md, app/enterprise/2.5.x/vitals/vitals-influx-strategy.md, app/gateway/2.6.x/vitals/vitals-influx-strategy.md, app/gateway/2.7.x/vitals/vitals-influx-strategy.md
Removing a sentence that mentions a 25-hour data retention limit for Vitals with InfluxDB. 
Cleared it from all 2.x docs to reduce confusion.
The 25-hour data retention limitation is only applicable when using Postgres or Cassandra as a backing DB. 
It is not true with InfluxDB, and in fact, the mention of a strictretention policy is directly contradicting a sentence earlier in the paragraph, which states:
> Vitals InfluxDB data points are not downsampled or managed by a retention policy through Kong.
Sample topics:
https://deploy-preview-3569--kongdocs.netlify.app/gateway/2.7.x/vitals/vitals-influx-strategy/#managing-the-retention-policy-of-the-kong-database 
https://deploy-preview-3569--kongdocs.netlify.app/enterprise/2.5.x/vitals/vitals-influx-strategy/#managing-the-retention-policy-of- …
=> [DOCU-2112][DOCU-2113] Remove 25-hour limit for Vitals with InfluxDB

app/gateway-oss/2.4.x/upgrading.md, app/gateway-oss/2.5.x/upgrading.md, app/gateway/2.6.x/install-and-run/upgrade-enterprise.md, app/gateway/2.6.x/install-and-run/upgrade-oss.md, app/gateway/2.7.x/install-and-run/migrate-ce-to-ke.md, app/gateway/2.7.x/install-and-run/upgrade-enterprise.md, app/gateway/2.7.x/install-and-run/upgrade-oss.md
* Fixing wrong versions in OSS doc from 2.4.x to 2.7.x
* Updating all versions in EE upgrade doc for 2.7.x
* Removing incremental upgrade requirement, as this isn't actually necessary at all.
* Attempt to clarify/simplify the path - if minor upgrade, move on. If major upgrade, look over the changelogs for breaking changes first, then otherwise move on.
* Make it clearer that you have three main path options:
* Upgrade your Postgres DB directly with `migrations up`/`migrations finish`
* Upgrade your Cassandra DB with the same method as PG, or do a database dump first to reduce downtime
* Install on a fresh datastore, only migrating the `kong.conf` file.
Many confused users, internally and externally. A few issues called out on Slack and in calls. 
Doc preview: …
=> Improve Gateway EE upgrade guide and fix wrong versions

app/gateway/2.7.x/install-and-run/debian.md
Fixing Debian install links.
Broken links.
Link checker should pass successfully.
See https://deploy-preview-3570--kongdocs.netlify.app/gateway/2.7.x/install-and-run/debian/
=> Fix Debian install and download links

.github/workflows/require-review-label.yml, README.md
Fail the build if there is not a `review:*` label applied to the PR
When raising a pull request, it's useful to indicate what type of review you're looking for from the team. To help with this, we've added three labels that can be applied:
- `review:copyedit`: Request for writer review.
- `review:general`: Review for general accuracy and presentation. Does the doc work? Does it output correctly?
- `review:tech`: Request for technical review from an SME.
At least one of these labels must be applied to a PR or the build will fail
This PR will fail the build until the `review:tech` label is applied
=> Ensure there's a review:* label on all PRs

app/_hub/wallarm/wallarm/index.md
Fixing link to Terms of Service.
Broken link. Reported through feedback tool.
https://deploy-preview-3559--kongdocs.netlify.app/hub/wallarm/wallarm/
=> Fix link in Wallarm plugin doc

app/kubernetes-ingress-controller/2.1.x/references/custom-resources.md
Fixing links.
Links are incorrectly formatted.
Check https://deploy-preview-3558--kongdocs.netlify.app/kubernetes-ingress-controller/2.1.x/references/custom-resources/#kongingress
=> Fix link formatting in k8s custom resource ref

.github/renovate.json
Automatically apply the `review:tech` labels to Renovate PRs
The build will fail without it, and it helps us triage PRs more easily
We'll have to wait for Renovate to raise a PR. It's been implemented using the details on the [Renovate docs](https://docs.renovatebot.com/configuration-options/)
=> Automatically apply review:tech to Renovate PRs

.github/workflows/check-links.yml, README.md
Manually mark PR link checks as successful by applying the `ci:manual-approve:link-validation` label
Link checking fails in some cases with a HTTP 400 from Netlify. Whilst we reproduce the issue, we want a way to make the build pass. Whilst we _can_ merge with a failing workflow, it leaves a red cross in the PR list which isn't ideal
Add the `ci:manual-approve:link-validation` label to this PR and watch as the `build` job in the `check-links` workflow is skipped
=> Add ability to mark link checker as manually reviewed

app/_layouts/extension.html
Fix typo on closing table cell tag (`</td>`). 
Closing tag is in the wrong place, so the `Type: string` line ends up outside the table:
TBA
Check any plugin
=> Fix positioning of `name` datatype for plugins

app/kubernetes-ingress-controller/2.0.x/references/version-compatibility.md, app/kubernetes-ingress-controller/2.1.x/references/version-compatibility.md
Updates KIC version compatibility tables for Kong 2.7 and Kubernetes 1.23
We've run the versions we expect to work on 1.23 on 1.23, and they did:
https://github.com/Kong/kubernetes-ingress-controller/actions/runs/1747707378
https://github.com/Kong/kubernetes-ingress-controller/actions/runs/1747833961
TestDeployAllInOneDBLESSNoLoadBalancer and TestDeployAllInOnePostgresWithMultipleReplicas, which are expected to fail on 2.0.x (their fixes are only in 2.1.x--I need to update the workflow a bit to let you choose the E2E test version, since it's currently locked to the tests in main)
We know of no breaking changes in Kong 2.7 that would break compatibility with versions that are supported with 2.6
Check netlify to confirm tables not busted.
=> doc(kic) update version compatibility tables

app/_assets/stylesheets/page.less
Removing height limit from codeblocks to avoid vertical scrollbars.
Not doing: removing the horizontal scroll. That can cause confusion due to awkward line breaks, so leaving it as is for now.  We can decide if letting lines wrap is fine in the future.
Originally, max height was added to codeblocks to stop pages from getting really stretched out. However, this has proven to be a poor solution, and has created some awkward UX 
- occasionally, code blocks add a scrollbar for one or two lines
- other times, there are both horizontal and vertical scrollbars, and navigating the codeblocks gets difficult
- if someone wants to highlight the codeblock to copy the text, scrolling is awkward. yes, we provide a copy-code button, but not everyone uses it
Awkward codeblock examples: …
=> Remove max height from codeblocks

.github/PULL_REQUEST_TEMPLATE.md
Add a reminder to use a label when submitting a PR to the PR template
I keep forgetting to add a label
N/A
=> Add labels reminder to PULL_REQUEST_TEMPLATE

app/gateway/2.6.x/reference/configuration.md, app/gateway/2.7.x/reference/configuration.md, app/gateway/changelog.md
* Changelog entries for 2.7.1.0 and 2.6.0.3.
* Adding a config reference doc entry for the new parameter `cluster_max_payload`.
* Note to reviewers: the text for this entry is unedited and getting added as-is from the `kong.conf.default` file. Not changing it to avoid conflicts with autodoc generation; will need to be edited in the source file.
Also note that the wiki lists this change for 2.6.0.3:
> Fix The garbage can icon overlaps the View link which causes users to click Delete instead of View
However, this change already went in with 2.6.0.1 (https://docs.konghq.com/gateway/changelog/#2601) - was there a regression, did it not actually go into 2.6.0.1, or is it just mislabelled?
Patch releases.
https://deploy-preview-3592--kongdocs.netlify.app/gateway/changelog/
=> Release: Gateway patches 2.7.1.0 and 2.6.0.3

app/_includes/nav-v2.html, spec/sidebar_spec.rb
Followup on #3566 
Now that the sidebar / top nav are consistent, let's add a test to make sure it never gets out of sync again.
I also added a missing `s` from the top navigation that the test highlighted.
One less thing for people to have to remember. The build will fail if we forget to change one of the two sections
The tests will pass
=> Ensure sidebar + top nav module list is consistent

app/_includes/hub-examples.html, app/gateway/2.6.x/get-started/comprehensive/expose-services.md, app/gateway/2.7.x/get-started/comprehensive/expose-services.md
* Making sure that the tab titles for the Kong Manager tabs on plugin hub examples are consistent.
* Fixing inconsistent tab order in a getting started guide topic (single-sourced versions)
Issue came up in https://github.com/Kong/docs.konghq.com/pull/3587. If the title is inconsistent, then the matching tabs on the same page won't open.
We also have a bug ticket for a similar issue (consistent tab order), DOCU-1942. To avoid confusion, when a matching tab opens, it should be in the same order in all tab blocks on the page.
https://deploy-preview-3593--kongdocs.netlify.app/hub/kong-inc/basic-auth/ - tabs are titled "Kong Manager", not "Manager"
https://deploy-preview-3593--kongdocs.netlify.app/gateway/2.7.x/get-started/comprehensive/expose-services/ - titles for tab groups are in …
=> [DOCU-1942] Consistent tab titles

app/mesh/1.2.x/features/opa.md, app/mesh/1.3.x/features/opa.md, app/mesh/1.4.x/features/opa.md, app/mesh/1.5.x/features/opa.md
Replace OPA JWT example with long-lived token to fix #3579
#3579
Complete the full Example in this docs page
=> Replace OPA JWT example with long-lived token to fix #3579

app/_includes/breadcrumbs.html, app/_includes/docs-sidebar-item.html, app/_includes/docs-sidebar.html, app/_includes/head.html, app/_includes/md/deb.md, app/_includes/md/installation.md, app/_includes/md/rpm.md
Reduce duplication during sidebar navigation item rendering.
The `include-check.sh` script previously added was used to make sure we don't depend on any `page.*` level variables in includes. Passing them in to the `include_cached` function breaks the cache for each permutation of `page.*` input
Save some build minutes on Netlify, make life better for people running the docs locally
Original build time:
After switching to `include_cached` for the sidebar:
This needs extensive testing. Check the sidebar on different products _and_ different versions.
I'm 95% confident with this change thanks to the `include-check.sh` work
=> Sidebar rendering speed improvements

app/mesh/1.4.x/features/vault.md, app/mesh/1.5.x/features/vault.md
Moved comments out of a codeblock into a note.
Fixes https://github.com/Kong/docs.konghq.com/issues/3525. Because of the comments, if you copy this text and then paste it into a terminal, it will generate an error. 
https://deploy-preview-3597--kongdocs.netlify.app/mesh/1.5.x/features/vault/#step-2-create-a-role-for-generating-data-plane-proxy-certificates
=> Fix codeblock in Mesh Vault doc

app/_includes/breadcrumbs.html, app/_layouts/docs-v2.html
Remove restrictions so that sidebar toggle always appears on mobile. There is no reason for it to be hidden.
Fixes https://github.com/Kong/docs.konghq.com/issues/3153.
Mobile issue: On unversioned docs, and occasionally on doc landing pages, the icon to open the left sidebar does not appear, so there is no way to access the table of contents. 
Normal doc (versioned, icon works):
Unversioned doc, icon missing:
Tested on chrome and firefox on my phone, and with chrome on desktop.
https://deploy-preview-3599--kongdocs.netlify.app/konnect/
https://deploy-preview-3599--kongdocs.netlify.app/konnect-platform/
Open the links on mobile, or resize your browser to 800px width or less, and make sure that the icon to open the left sidebar is always there and is useable.
=> Fix sidebar toggle visibility on mobile

app/_assets/stylesheets/page.less
Hiding the scroll-to-top button on mobile, as it shouldn't be used there. 
Scrolling to the top on a phone or tablet is built into the device and we're unnecessarily crowding the screen with this button.
https://deploy-preview-3598--kongdocs.netlify.app/gateway/ (or any page): open the link on mobile, or resize your browser to 800px width or less, and make sure the scroll-to-top button doesn't appear.
=> Remove scroll-to-top button from mobile

app/_hub/kong-inc/oauth2/index.md
Remove the nonexistent persistent_refresh_token field
From https://github.com/Kong/kong/issues/8348
Orignal PR https://github.com/Kong/kong/pull/5264, `persistent_refresh_token` was mentioned in the PR as first iterration but only `reuse_refresh_token` is merged.
The extra field was added in https://github.com/Kong/docs.konghq.com/commit/6b970cb77e73098802034a55e272e87c58c1a5d1
=> docs(oauth2) remove the nonexistent persistent_refresh_token field

app/_data/kong_versions.yml
Bumping Gateway versions to latest available (double-checked against downloads.konghq.com and our Docker Hub listings).
Companion update to https://github.com/Kong/docs.konghq.com/pull/3592. Forgot to bump the versions.
TBA
=> Update gateway versions based on 2.7 and 2.6 patch releases

app/gateway/2.6.x/get-started/comprehensive/load-balancing.md, app/gateway/2.7.x/get-started/comprehensive/load-balancing.md, app/getting-started-guide/2.1.x/load-balancing.md, app/getting-started-guide/2.2.x/load-balancing.md, app/getting-started-guide/2.3.x/load-balancing.md, app/getting-started-guide/2.4.x/load-balancing.md, app/getting-started-guide/2.5.x/load-balancing.md, app/getting-started-guide/CE-2.0.x_KE-1.5.x/load-balancing.md
Renaming the upstream in the getting started guide from `upstream` to `example_upstream` to avoid using reserved entity names and causing issues.
Fixes #3601 (submitter closed issue before I pushed a fix, but it's still an issue.)
Did this in all versions because it has the potential to break the guide's flow entirely.
https://deploy-preview-3603--kongdocs.netlify.app/gateway/2.7.x/get-started/comprehensive/load-balancing/
=> Change upstream name in getting started guide

app/_assets/stylesheets/base.less, app/_assets/stylesheets/hub-landing-page.less, app/_assets/stylesheets/page.less, app/_assets/stylesheets/pages/docs.less, app/_assets/stylesheets/pages/extension.less, app/_assets/stylesheets/pages/landing-page.less, app/gateway/2.7.x/install-and-run/index.md
* Consolidate base header settings in `base.less` and remove duplicate header styling from `page.less`, `docs.less`, and `extension.less`. The basic header styling should be (and is, mostly) consistent across our docs; changing header styling for specific purposes (eg page titles in specific contexts) should be done through classes whenever possible. This way, styling doesn't overlap and makes it easier for maintainers to find the source of any particular style.
* Increasing font weights for better visual contrast, and adjusting margins for clearer relationships between headers and preceding/following text. Compare:
Old: 
New:
It needs to be more obvious where the docs are sectioned. Current header style blends into the text.
Need to look through a variety of content to make sure this …
=> Improve header contrast

app/deck/1.10.x/installation.md, app/deck/1.9.x/installation.md
Fix the `kong_versions` entry for `decK` 1.9 and 1.10
Existing installation instructions are inaccurate
Check the following URLs:
* https://deploy-preview-3606--kongdocs.netlify.app//deck/1.9.x/installation/
* https://deploy-preview-3606--kongdocs.netlify.app//deck/1.10.x/installation/
=> [DOCU-2166] Fix decK 1.9 and 1.10 installation instructions

app/gateway/2.7.x/reference/external-plugins.md
This adds quotes to the Golang struct tags.
The current Golang config struct has a minor error in that the struct tags are missing. This would cause an issue when encoding/decoding the json configs. Example: https://go.dev/play/p/2hCSyXzXWgR
[Here is an example of it in action](https://go.dev/play/p/2hCSyXzXWgR)
=> Use quoted struct tags for golang configuration

app/gateway/changelog.md
Adjusting phrasing for the changelog entry for Dev Portal auth with OIDC in 2.7.
Issue reported in Slack. Changelog entry was misleading.
https://kongstrong.slack.com/archives/CDSTDSG9J/p1643636506353189
Explanation from Nate Bailey: 
> The flow for developer portal registration changed for OIDC. The user now authenticates with the IDP first and the email from the claims is used to pre populate the registration form to prevent a mismatch. This is different from the autogeneration of accounts that was added to the Manager. The Portal cannot support this because there are dynamic custom fields required for developers that we cannot get from the claims.
https://deploy-preview-3611--kongdocs.netlify.app/gateway/changelog/#dev-portal
=> Adjust phrasing for Dev Portal OIDC changelog entry

app/api/developer-portal.json
Adding a disclaimer to the intro page of the dev portal API doc to say that yes, we know it's incomplete, please file issues or PRs letting us know exactly what errors you ran into.
Doc has been our for two days and this has come up a couple of times already. There is no "edit in github" or "report and issue" link on the side like there is in our other content, so I'm adding these links on the landing page for now.
https://deploy-preview-3618--kongdocs.netlify.app/gateway/2.7.x/developer-portal/portal-api/#/
=> Dev Portal API doc disclaimer

app/_assets/stylesheets/pages/docs.less, app/_includes/head.html
* Adding external link icons. 
* Went with the pure CSS route; can also do this with JS, if reviewers think that would be better.
* Updating font-awesome using their latest docs; the version we were using didn't have a lot of the newer icons, including an external link icon. Nowadays, they provide a script to add to your site instead of referencing a versioned stylesheet. This way, it should stay up-to-date.
**Exceptions:** No link icons on buttons, on badges, or in the footer. For buttons and badges, this is a stylistic choice; for the footer, it's for consistency with the konghq.com site. 
**@ Reviewers:** Should these icons also be left out of the navbar, for consistency with our other sites? Additionally, there's some jumpiness because of the way the page loads, with text loading …
=> [DOCU-1698] External link icons + update font awesome

app/gateway/2.6.x/install-and-run/docker.md, app/gateway/2.7.x/install-and-run/docker.md
Based on the confusion caused by editable placeholders and a few other changes, fixing the Docker install instructions for Gateway:
- Removing editable placeholders and replacing with hardcoded values. If a user needs to change any values, they can change them.
- Adding descriptions for parameters, so that if they want to customize the install, they know what each param does
- Cleaning up order of instructions and chunking up the DB-less mode section
- Cleaning up DB-less mode text
- FIxing `migrations` command
- Removing step to tag docker image:
- We were tagging the OSS `kong` image  as `kong`, which is redundant
- We shouldn't use `kong-ee` anymore. The Enterprise image name is `kong/kong-gateway`, which is fairly clear as it is and is different from the OSS image.
**Explanations for …
=> [DOCU-2114] Fix Docker install instructions

app/_hub/kong-inc/prometheus/index.md
- Remove the older unsupported Gateway versions (checked the difference between 1.3.x and 1.4.x versions of this plugin)
- Move the "new in 1.4.x" section into a changelog at the end of the page, to match the approach we use in other plugins
- Fix header levels
Was in a team analytics call and we were looking at the doc for this plugin, noticed some wonky formatting.
https://deploy-preview-3609--kongdocs.netlify.app/hub/kong-inc/prometheus/
=> Prometheus plugin minor fixes

app/_includes/nav-v2.html, app/contributing/variables.md, app/enterprise/1.3-x/kong-for-kubernetes/install.md, app/enterprise/2.2.x/introduction/index.md, app/enterprise/2.3.x/index.md, app/enterprise/2.4.x/index.md, app/enterprise/2.5.x/index.md, app/gateway/2.6.x/index.md, app/gateway/2.7.x/index.md, jekyll-dev.yml, jekyll.yml
konglabs.io doesn't exist anymore and has been replaced with education.konghq.com. 
- In the interest of maintainability, I've defined a variable for a `learn` link pointing to Kong Academy and replaced all the old links with the variable. This way, if the link changes again in the future, we can just update the variable definition.
- Added a table for link variables to our contributing guide, and cleaned up the variables topic a bit. 
- Removed the codeblock with variables, it was redundant with the table.
- Commented out the broken version variable section.
https://deploy-preview-3617--kongdocs.netlify.app/gateway/#try-in-konnect
https://deploy-preview-3617--kongdocs.netlify.app/contributing/variables
=> Update konglabs links and variables

gulpfile.js
1. Speed up the build by removing the implicit call to `clean`.
2. Delete the HTML size report that we don't use
3. Remove remaining references to GH Pages
This is best explained with a 70 second video
https://user-images.githubusercontent.com/59130/151998634-aded07c0-6de8-41b9-b8b8-bb3929f7f77d.mp4
Run `gulp` locally
=> Gulpfile updates

app/kubernetes-ingress-controller/2.0.x/guides/prometheus-grafana.md, app/kubernetes-ingress-controller/2.1.x/guides/prometheus-grafana.md
Add the KIC dashboard to the Prometheus/Grafana guide
https://grafana.com/grafana/dashboards/15662 is now available.
```
helm install trp prometheus-community/kube-prometheus-stack -f /tmp/values.yaml
```
with [values.yaml.txt](https://github.com/Kong/docs.konghq.com/files/7982635/values.yaml.txt), confirming that the dashboards appear.
=> doc(kic) add KIC Grafana dashboard

app/_assets/stylesheets/badges.less, app/_layouts/docs-v2.html, app/_layouts/extension.html, app/contributing/markdown-rules.md
* Add conditional alpha and beta banners to main docs layout
* Update alpha and beta banners on plugins layout
* Create a badge for alpha/tech preview 
* Went with the name "tech preview" as that's what Konnect is using instead of alpha, but added (alpha quality) in brackets because our open-source projects are more used to this terminology. "Alpha" is also used in decK flags.
We're missing `alpha` and `beta` tag handling logic from the `docs-v2.html` layout, although it does exist in the `extension.html` layout. Noted in https://github.com/Kong/docs.konghq.com/pull/3621#issuecomment-1029444084.
Tested by applying `alpha: true` and `beta: true` to a few random pages.
=> Re-add missing alpha and beta banners

app/_data/kong_versions.yml
Update version metadata.
2.7.1 Docker image was published today: https://hub.docker.com/_/kong?tab=tags
Check any installation page, Kong Gateway (OSS) tab:
https://deploy-preview-3626--kongdocs.netlify.app/gateway/2.7.x/install-and-run/centos/?tab=kong-gateway-oss
=> Update OSS gateway version to 2.7.1

app/enterprise/2.3.x/deployment/kong-user.md, app/enterprise/2.4.x/deployment/kong-user.md, app/enterprise/2.5.x/deployment/kong-user.md, app/gateway-oss/2.3.x/kong-user.md, app/gateway-oss/2.4.x/kong-user.md, app/gateway-oss/2.5.x/kong-user.md, app/gateway/2.6.x/plan-and-deploy/kong-user.md, app/gateway/2.7.x/plan-and-deploy/kong-user.md
* Add missing custom non-root user instructions to Gateway (OSS and EE) 2.3-2.5 docs
* Slight adjustment to 2.6 and 2.7 for language that was missing from it, plus updating variables
* Minor cleanup to alert syntax
The topic accidentally diverged in 2.3.x. Changes were made in 2.2.x but not picked up by the next version.
The topic was mostly fixed in the single-sourcing audit and is therefore mostly accurate in 2.6.x and 2.7.x.
Current Gateway: https://deploy-preview-3629--kongdocs.netlify.app/gateway/2.7.x/plan-and-deploy/kong-user/
Old Enterprise: https://deploy-preview-3629--kongdocs.netlify.app/enterprise/2.5.x/deployment/kong-user/
Old Gateway OSS: https://deploy-preview-3629--kongdocs.netlify.app/gateway-oss/2.5.x/kong-user/
=> [DOCU-449] Add missing kong user info

app/_assets/javascripts/app.js, app/_assets/stylesheets/header.less, app/_assets/stylesheets/page.less, app/_assets/stylesheets/pages/docs.less, app/_includes/toc.html, app/_layouts/docs-v2.html, app/_layouts/extension.html, app/contributing/markdown-rules.md, app/deck/1.10.x/compatibility-promise.md, app/deck/1.10.x/guides/backup-restore.md, app/deck/1.10.x/guides/best-practices.md, app/deck/1.10.x/guides/ci-driven-configuration.md, app/deck/1.10.x/guides/deduplicate-plugin-configuration.md, app/deck/1.10.x/guides/environment-variables.md, app/deck/1.10.x/guides/multi-file-state.md, app/konnect-platform/compatibility/index.md, app/konnect-platform/guides.md, app/konnect/deployment/license-management.md, app/konnect/dev-portal/index.md, app/konnect/shared-config/index.md, app/mesh/1.5.x/features/fips-support.md
Improvements to the right-side "On this page" navigation:
* If sidebar is open, toggle is always visible. This fixes the issue of having a hidden sidebar creating space on pages where it shouldn't. 
* For example: https://docs.konghq.com/gateway/2.7.x/admin-api/ - with the sidebar and toggle completely hidden, there is no way to close the sidebar, and therefore no way to make the text expand to fill the page. You have to switch to some other page, toggle the sidebar, and then return here for it to work. This change fixes that.
* Github links are now always visible, even if the page has no headers.
* Hide 'on this page' if there are no headers
* Current behavior: even if there are no h2 or h3 elements on the page, an "On this page" link appears (for example: …
=> Improve "on this page" & github links sidebar

app/_hub/kong-inc/canary/0.3.x.md, app/_hub/kong-inc/canary/0.4.x.md, app/_hub/kong-inc/canary/index.md
Update Upstream Healthchecks general links to section-specific links. 
Changed on all version containing these links.
Addresses [DOCU-1643](https://konghq.atlassian.net/browse/DOCU-1643).
https://deploy-preview-3640--kongdocs.netlify.app/hub/kong-inc/canary/#upstream-healthchecks
=> [DOCU-1643] Update links in Canary Release plugin

app/gateway/2.7.x/reference/configuration.md
Remove db version content from Property Reference datastore section in 2.7.x. 
Addresses [DOCU-1612](https://konghq.atlassian.net/browse/DOCU-1612).
Link TBA.
=> [DOCU-1612] Remove db version content from Property Reference datastore section

app/konnect/deployment/index.md, app/konnect/runtime-manager/gateway-runtime-docker.md, app/konnect/runtime-manager/gateway-runtime-kubernetes.md, app/konnect/updates.md
* Update changelog.
* Update runtime setup docs with 2.7 versions
* Update deployment table with 2.7
* Use tagged image for Docker container
2.7 support went out in December and we missed it. Found out by testing, tracked down date in production channel.
https://deploy-preview-3631--kongdocs.netlify.app/konnect/updates/
Check that the version is 2.7 and not 2.6:
https://deploy-preview-3631--kongdocs.netlify.app/konnect/runtime-manager/gateway-runtime-docker/
https://deploy-preview-3631--kongdocs.netlify.app/konnect/runtime-manager/gateway-runtime-kubernetes/
=> Update Konnect docs with 2.7 gateway support

app/enterprise/2.1.x/deployment/hybrid-mode-setup.md, app/enterprise/2.2.x/deployment/hybrid-mode-setup.md, app/enterprise/2.3.x/deployment/hybrid-mode-setup.md, app/enterprise/2.4.x/deployment/hybrid-mode-setup.md, app/enterprise/2.5.x/deployment/hybrid-mode-setup.md, app/gateway/2.6.x/plan-and-deploy/hybrid-mode/hybrid-mode-setup.md, app/gateway/2.7.x/plan-and-deploy/hybrid-mode/hybrid-mode-setup.md
* Enterprise Gateway 2.1-2.5: Fixed the image name to point to the tag that they set in the Docker install instructions
* Gateway 2.6-2.7: Updated hybrid mode docker instructions to use EE/OSS tabs and variables for image name to match the 2.6 and 2.7 docker installation instructions
Image names are wrong, and hybrid mode instructions in 2.6 and 2.7 no longer work as-is with the CP Docker installation instructions.
New doc: https://deploy-preview-3630--kongdocs.netlify.app/gateway/2.7.x/plan-and-deploy/hybrid-mode/hybrid-mode-setup/
Old Enterprise doc: https://deploy-preview-3630--kongdocs.netlify.app/enterprise/2.5.x/deployment/hybrid-mode-setup/
=> [DOCU-1651] Fix hybrid mode docker instructions

app/gateway/2.6.x/reference/cli.md, app/gateway/2.7.x/reference/cli.md
Adding notes to Gateway 2.6 and 2.7 docs that db_export is only supported in OSS.
Doc ticket asks to remove notes from old content that `db_export` is not supported, but after testing and research, it turns out it's the other way around. 
`db_export` does not work with Kong Enterprise, and wasn’t supposed to. In the changelog for 1.5, there is a fix listed that says it was accidentally available in 1.3: [Kong Gateway Changelog](https://docs.konghq.com/gateway/changelog/#fixes-55) 
Manually tested with 2.7 and 2.6, `db_export` does not work. In 2.6 it simply does nothing; in 2.7 it throws plugin errors.
https://deploy-preview-3633--kongdocs.netlify.app/gateway/2.7.x/reference/cli/#kong-config
https://deploy-preview-3633--kongdocs.netlify.app/gateway/2.6.x/reference/cli/#kong-config
=> [DOCU-360] Note for db_export support

app/enterprise/0.35-x/proxy.md, app/enterprise/0.36-x/proxy.md, app/gateway-oss/1.2.x/proxy.md, app/gateway-oss/1.3.x/proxy.md, app/gateway-oss/1.4.x/proxy.md, app/gateway-oss/1.5.x/proxy.md, app/gateway-oss/2.0.x/proxy.md, app/gateway-oss/2.1.x/proxy.md, app/gateway-oss/2.2.x/proxy.md, app/gateway-oss/2.3.x/proxy.md, app/gateway-oss/2.4.x/proxy.md, app/gateway-oss/2.5.x/proxy.md
Scrub `X-Kong-Debug` and replace with `Kong-Debug`.
Header name is wrong.
=> [DOCU-1472] Fix Kong-Debug header name

app/_hub/kong-inc/openid-connect/index.md
https://openid.net/specs/openid-connect-core-1_0.html#DistributedExample
Distributed/Aggregated Claims are defined in the openid-connect spec.
Internal: FTI-2978
Testing is included in the respective plugin/lib implementations.
dependent on:
* https://github.com/Kong/kong-ee/pull/2856
* Kong/kong-openid-connect#38
=> docs(oidc): add docs for 'resolve_distributed_claims'

app/gateway/2.7.x/developer-portal/administration/application-registration/auth-provider-strategy.md, app/gateway/2.7.x/developer-portal/administration/application-registration/enable-application-registration.md, app/gateway/2.7.x/developer-portal/administration/application-registration/enable-key-auth-plugin.md, app/gateway/2.7.x/developer-portal/configuration/smtp.md, app/gateway/2.7.x/developer-portal/theme-customization/adding-javascript-assets.md, app/gateway/2.7.x/developer-portal/theme-customization/easy-theme-editing.md, app/gateway/2.7.x/developer-portal/theme-customization/emails.md, app/gateway/2.7.x/developer-portal/theme-customization/markdown-extended.md, app/gateway/2.7.x/developer-portal/theme-customization/single-page-app.md, app/gateway/2.7.x/developer-portal/using-the-editor.md
Remove version-specific text from on-prem Dev Portal docs.
Addresses [DOCU-2128](https://konghq.atlassian.net/browse/DOCU-2128).
Click through on-prem Dev Portal documentation prerequisites: https://deploy-preview-3643--kongdocs.netlify.app/gateway/2.7.x/developer-portal/
=> [DOCU-2128] remove version-specific text from on-prem Dev Portal docs

app/_hub/kong-inc/mocking/0.1.x.md, app/_hub/kong-inc/mocking/index.md
Document supported response codes for the Mocking plugin. 
The mocking plugin only supports `200`, `201`, and `204` responses.
See https://github.com/Kong/kong-plugin-mocking/blob/master/kong/plugins/mocking/handler.lua#L202.
https://deploy-preview-3646--kongdocs.netlify.app/hub/kong-inc/mocking/
=> [DOCU-1929] Supported response codes for Mocking plugin

app/gateway/changelog.md
Adding an alert banner for the Kong Manager changelog entry in 2.7.0.0 to say that it was a breaking change and what exactly changed. 
We introduced a breaking change for Kong Manager in 2.7.0.0 but it wasn't labelled as a breaking change, and users have already run into problems with it.
https://deploy-preview-3654--kongdocs.netlify.app/gateway/changelog/#kong-manager
=> Breaking change note for Kong Manager changelog entry in 2.7.0.0

app/_includes/md/mesh/install-universal-run.md
In includes file for Kong Mesh, swap `KUMA_LICENSE_PATH` for `KMESH_LICENSE_PATH`.
Addresses [DOCU-1583](https://konghq.atlassian.net/browse/DOCU-1583)
Check the includes file in file changes. The change applies on multiple pages, including the following:
https://deploy-preview-3652--kongdocs.netlify.app/mesh/1.5.x/installation/amazonlinux/#2-run-kong-mesh
=> [DOCU-1583] Fix Mesh license variable

app/kubernetes-ingress-controller/1.0.x/deployment/aks.md, app/kubernetes-ingress-controller/1.1.x/deployment/aks.md, app/kubernetes-ingress-controller/1.2.x/deployment/aks.md, app/kubernetes-ingress-controller/1.3.x/deployment/aks.md, app/kubernetes-ingress-controller/2.0.x/deployment/aks.md, app/kubernetes-ingress-controller/2.1.x/deployment/aks.md
Fix typos and styling issues in Azure Kubernetes Ingress Control for all versions of documentation.
Addresses [DOCU-486](https://konghq.atlassian.net/browse/DOCU-486)
https://deploy-preview-3651--kongdocs.netlify.app/kubernetes-ingress-controller/2.1.x/deployment/aks/
https://deploy-preview-3651--kongdocs.netlify.app/kubernetes-ingress-controller/2.0.x/deployment/aks/
https://deploy-preview-3651--kongdocs.netlify.app/kubernetes-ingress-controller/1.3.x/deployment/aks/
https://deploy-preview-3651--kongdocs.netlify.app/kubernetes-ingress-controller/1.2.x/deployment/aks/
https://deploy-preview-3651--kongdocs.netlify.app/kubernetes-ingress-controller/1.1.x/deployment/aks/
https://deploy-preview-3651--kongdocs.netlify.app/kubernetes-ingress-controller/1.0.x/deployment/aks/
=> [DOCU-486] Fix typos and styling issues

app/deck/1.11.x/guides/defaults.md
* Adding sample of plugin default config; removing notes about plugin defaults not being available.
* Examples are no longer treated as reference; they are only examples, as values change and docs won't be able to maintain. Instead, they're replaced with examples/instructions for finding the schema for each object and adding them to the declarative config file.
Plugin defaults will be supported in decK 1.11.
Engineering plugins [PR](https://github.com/Kong/deck/pull/562)
Other core entities [PR](https://github.com/Kong/deck/pull/573)
Haven't tested the feature (need to figure out how to do that with an unreleased version of decK), will need eng review and verification. 
Doc preview: https://deploy-preview-3636--kongdocs.netlify.app/deck/1.11.x/guides/defaults/
=> [DOCU-2177] Deck support for plugin defaults

app/gateway-oss/2.4.x/admin-api.md, app/gateway-oss/2.5.x/admin-api.md, app/gateway/2.6.x/admin-api/index.md, app/gateway/2.7.x/admin-api/index.md
In the Admin API documentation, change `Not available in DB-less mode.` to `This API is not available in DB-less mode.`
Addresses [DOCU-2185](https://konghq.atlassian.net/browse/DOCU-2185)
One example: https://deploy-preview-3653--kongdocs.netlify.app/gateway/2.7.x/admin-api/#add-service
=> [DOCU-2185] Update Admin API note

app/_data/kong_versions.yml, app/gateway/changelog.md
Changelog for gateway patch release and a version bump.
Same change is going into 2.7.1.2. It's in a separate PR (https://github.com/Kong/docs.konghq.com/pull/3645) in case the releases don't go out at the same time.
Patch release.
https://deploy-preview-3644--kongdocs.netlify.app/gateway/changelog/#2604
=> Release: Gateway 2.6.0.4

app/gateway/2.7.x/admin-api/index.md
Remove wording in Admin API docs Target Object that says targets cannot be modified or deleted.
Addresses [DOCU-2140](https://konghq.atlassian.net/browse/DOCU-2140)
https://deploy-preview-3663--kongdocs.netlify.app/gateway/2.7.x/admin-api/#target-object
=> [DOCU-2140] Admin API: Remove wording about cannot delete/modify

app/_includes/md/2.1.x/migrations/migrate-dev-portal.md
Update Dev Portal templates file URLs on last instance of migrations doc (2.1.x). 
Addresses [DOCU-1813](https://konghq.atlassian.net/browse/DOCU-1813)
https://deploy-preview-3662--kongdocs.netlify.app/enterprise/2.1.x/developer-portal/latest-migrations/#create-files
=> [DOCU-1813] 2.1.x migrate Dev Portal URL updates

app/enterprise/2.1.x/deployment/hybrid-mode-setup.md, app/enterprise/2.2.x/deployment/hybrid-mode-setup.md, app/enterprise/2.3.x/deployment/hybrid-mode-setup.md, app/enterprise/2.4.x/deployment/hybrid-mode-setup.md, app/enterprise/2.5.x/deployment/hybrid-mode-setup.md, app/gateway/2.6.x/plan-and-deploy/hybrid-mode/hybrid-mode-setup.md, app/gateway/2.7.x/plan-and-deploy/hybrid-mode/hybrid-mode-setup.md
On Hybrid Mode Setup pages for Gateway 2.1.x and newer, change `Vitals telemetry` to `telemetry`.  
Addresses [DOCU-1068](https://konghq.atlassian.net/browse/DOCU-1068)
Newest version: https://deploy-preview-3667--kongdocs.netlify.app/gateway/2.7.x/plan-and-deploy/hybrid-mode/hybrid-mode-setup/
=> [DOCU-1068] Hybrid Mode: rm Vitals from telemetry mentions

app/deck/1.11.x/reference/deck.md, app/deck/1.11.x/reference/deck_completion.md, app/deck/1.11.x/reference/deck_convert.md, app/deck/1.11.x/reference/deck_diff.md, app/deck/1.11.x/reference/deck_dump.md, app/deck/1.11.x/reference/deck_konnect.md, app/deck/1.11.x/reference/deck_konnect_diff.md, app/deck/1.11.x/reference/deck_konnect_dump.md, app/deck/1.11.x/reference/deck_konnect_ping.md, app/deck/1.11.x/reference/deck_konnect_sync.md, app/deck/1.11.x/reference/deck_ping.md, app/deck/1.11.x/reference/deck_reset.md, app/deck/1.11.x/reference/deck_sync.md, app/deck/1.11.x/reference/deck_validate.md, app/deck/1.11.x/reference/deck_version.md
- Reduce whitespace at the start of codeblocks
- Remove duplicate section in `deck sync`
- Typo fix
Found some errors when prepping release branch.
https://deploy-preview-3670--kongdocs.netlify.app/deck/1.11.x/reference/deck/ - able to see more of the codeblock without scrolling. Still not pretty, but this helps for now, until we reformat this content.
https://deploy-preview-3670--kongdocs.netlify.app/deck/1.11.x/reference/deck_sync/ - no more extra section
=> decK CLI ref cleanup for 1.11

app/mesh/1.5.x/features/vault.md
This PR updates the Vault documentation.
Fixes #3545
This PR adds some documentation to the Vault section. Specifically, it calls out the need to use mesh-scoped secrets and highlights a potential problem when using `jq` to filter the output of the command to create the Vault token.
The current documentation is unclear about the need to use a mesh-scoped secret. The current documentation also does not call out that the use of `jq` _may_ mask errors encountered in the process of creating the necessary Vault token.
These changes arose out of my attempt to use the Vault documentation. The confirmation regarding the need to use a mesh-scoped secret came from Engineering; I haven't personally tested/verified. As for the invalid token situation, it can be replicated:
1. Intentionally introduce …
=> Update Vault documentation

app/_hub/kong-inc/correlation-id/index.md
Add info about how to edit an Nginx param in Correlation ID plugin docs.
Addresses [DOCU-876](https://konghq.atlassian.net/browse/DOCU-876).
@lena-larionova for the technical review, do you know someone we can ping? The original task creator is not at Kong. 
https://deploy-preview-3656--kongdocs.netlify.app/hub/kong-inc/correlation-id/#can-i-see-my-correlation-ids-in-my-kong-logs
=> [DOCU-876] Correlation ID Plugin: edit Nginx param

app/_data/extensions/kong-inc/canary/versions.yml, app/_hub/kong-inc/canary/0.5.x.md, app/_hub/kong-inc/canary/index.md
Add documentation for new config.canary_by_header_name for canary plugin
Addresses DOCU-2187
=> [DOCU-2187] Add config.canary_by_header_name to canary plugin

app/_hub/kong-inc/response-transformer-advanced/index.md
Add missing parameters to Response Transformed Advanced plugin.
Addresses [DOCU-493](https://konghq.atlassian.net/browse/DOCU-493)
Requires an engineer to ensure the definition for `config.rename.if_status` is accurate. **EDIT**: Shane provided a correction and I've incorporated it. I've also removed `tags`.
https://deploy-preview-3682--kongdocs.netlify.app/hub/kong-inc/response-transformer-advanced/#parameters
=> [DOCU-493] response trans adv plugin: missing params

app/enterprise/1.5.x/property-reference.md, app/enterprise/2.1.x/property-reference.md
Add missing `status_listen` to 1.5.x and 2.1.x. Checked elsewhere. 
Addresses [DOCU-885](https://konghq.atlassian.net/browse/DOCU-885)
** Note that I matched that page's styling, so these two records look different.
https://deploy-preview-3677--kongdocs.netlify.app/enterprise/1.5.x/property-reference/#status_listen
https://deploy-preview-3677--kongdocs.netlify.app/enterprise/2.1.x/property-reference/#status_listen
=> [DOCU-885] Add missing status_listen

app/enterprise/2.2.x/admin-api/index.md, app/enterprise/2.3.x/admin-api/index.md, app/enterprise/2.4.x/admin-api/index.md, app/enterprise/2.5.x/admin-api/index.md, app/gateway-oss/2.2.x/admin-api.md, app/gateway-oss/2.3.x/admin-api.md, app/gateway-oss/2.4.x/admin-api.md, app/gateway-oss/2.5.x/admin-api.md, app/gateway/2.6.x/admin-api/index.md
Removes cannot delete or modify wording for older docs versions on combined, Enterprise, and OSS. 
Applied to 2.2.x and newer.
See related https://github.com/Kong/docs.konghq.com/pull/3663
Example on 2.2.x: https://deploy-preview-3681--kongdocs.netlify.app/enterprise/2.2.x/admin-api/#target-object
=> Related to DOCU-2140 Admin API rm cannot del/mod

app/_hub/kong-inc/serverless-functions/index.md
Add description of `pre-` and `post-` plugins for Serverless Functions plugins. 
Rm auto-generated examples
Addresses [DOCU-1647](https://konghq.atlassian.net/browse/DOCU-1647)
https://deploy-preview-3674--kongdocs.netlify.app/hub/kong-inc/serverless-functions/
=> [DOCU-1647] Add desc to Serverless Functions plugin

app/gateway/2.7.x/developer-portal/theme-customization/easy-theme-editing.md
Add a note that on-prem Dev Portal doesn't carry over between default Dev Portal and other Workspaces.
Addresses [DOCU-385](https://konghq.atlassian.net/browse/DOCU-385)
https://deploy-preview-3675--kongdocs.netlify.app/gateway/2.7.x/developer-portal/theme-customization/easy-theme-editing/#the-appearance-tab
=> [DOCU-385] Dev Portal styling doesn't carry over

app/enterprise/2.1.x/kong-manager/administration/workspaces/add-workspace.md, app/enterprise/2.2.x/kong-manager/administration/workspaces/add-workspace.md, app/enterprise/2.3.x/kong-manager/administration/workspaces/add-workspace.md, app/enterprise/2.4.x/kong-manager/administration/workspaces/add-workspace.md, app/enterprise/2.5.x/kong-manager/administration/workspaces/add-workspace.md, app/gateway/2.6.x/configure/auth/kong-manager/workspaces.md, app/gateway/2.7.x/configure/auth/kong-manager/workspaces.md
Replace wording about Workspace naming in Kong Manager doc
Addresses [DOCU-1848](https://konghq.atlassian.net/browse/DOCU-1848)
On 2.7.x: https://deploy-preview-3676--kongdocs.netlify.app/gateway/2.7.x/configure/auth/kong-manager/workspaces/#creating-new-workspaces
=> [DOCU-1848] Clarify wording in Kong Manager

app/gateway/2.6.x/get-started/comprehensive/secure-services.md, app/gateway/2.7.x/get-started/comprehensive/secure-services.md
The `/` before `?apikey ` is not needed, so remove it.
http://<admin-hostname>:8000/mock/?apikey=apikey
The URL in the doc has a no required `/`. 
User may hit a 404 error if using the URL on the website. 
Can't verify the auth with the provided URL
Using the Browser directly.
=> remove unnecessary / in the URL

app/mesh/1.5.x/installation/windows.md, app/mesh/1.6.x/installation/windows.md
Change `Kuma` to `Kong Mesh` as well as the name of env var
from `KUMA_LICENSE_PATH` to `KMESH_LICENSE_PATH`
Found out that the docs are wrong
It's small PR so looking at other parts of the installation where we are using proper env var should be enough, but if not, we can always test the instructions on windows machine
=> docs(mesh): fix windows installation docs

app/_data/extensions/kong-inc/graphql-rate-limiting-advanced/versions.yml, app/_data/extensions/kong-inc/proxy-cache-advanced/versions.yml, app/_data/extensions/kong-inc/response-ratelimiting/versions.yml, app/_hub/kong-inc/graphql-rate-limiting-advanced/0.1.x.md, app/_hub/kong-inc/graphql-rate-limiting-advanced/index.md, app/_hub/kong-inc/openid-connect/index.md, app/_hub/kong-inc/proxy-cache-advanced/0.4.x.md, app/_hub/kong-inc/proxy-cache-advanced/index.md, app/_hub/kong-inc/rate-limiting-advanced/index.md, app/_hub/kong-inc/rate-limiting/index.md, app/_hub/kong-inc/response-ratelimiting/1.0.x.md, app/_hub/kong-inc/response-ratelimiting/index.md
* Create changelog entries for plugins edited in https://github.com/Kong/docs.konghq.com/pull/3540 and https://github.com/Kong/docs.konghq.com/pull/3553.
* Out of the plugins I added changelogs to, also fixed versions for `proxy-cache-advanced`, `graphql-rate-limiting-advanced`, and `response-ratelimiting` plugins. These versions were not following the actual plugin versions, and they weren't following Kong Gateway versions either, so the versions were basically made up. If I left them as-is, the changelog entries would've only made things more confusing.
* Added changelog entries to call out the doc changes as well, in case a user notices the version changes.
Missing plugin changelog entries.
To find the correct plugin versions to set, I went digging in the old plugin repositories and …
=> Changelogs and version fixes for 2.8 plugins

app/_data/extensions/kong-inc/forward-proxy/versions.yml, app/_hub/kong-inc/forward-proxy/1.1.x.md
* Added `http_proxy_host`, `http_proxy_port`, `https_proxy_host`, and
`https_proxy_port` configuration parameters for mTLS support. 
* Labelling `proxy_host` and `proxy_port` as deprecated.
* Fixed previous plugin version, it was labelled incorrectly. See https://github.com/Kong/kong-ee/blob/master/plugins-ee/forward-proxy/CHANGELOG.md. 
This doc likely needs more detail. What else needs to be configured for an mTLS connection? 
Gateway 2.8 includes changes to the forward proxy plugin.
Eng PR: https://github.com/Kong/kong-ee/pull/2950
Doc preview: https://deploy-preview-3691--kongdocs.netlify.app/hub/kong-inc/forward-proxy/
=> [DOCU-2192] Forward proxy mTLS support

app/enterprise/2.4.x/external-plugins.md, app/enterprise/2.5.x/external-plugins.md, app/gateway-oss/2.4.x/external-plugins.md, app/gateway-oss/2.5.x/external-plugins.md, app/gateway/2.6.x/reference/external-plugins.md, app/gateway/2.7.x/reference/external-plugins.md
Use pip3 (Python 3.x) in instruction and reference to the API reference link.
=> doc(external-plugins) use pip3 and mention API reference

app/gateway/2.8.x/reference/external-plugins.md
This PR mentions the deprecation of the go-pluginserver -- aka "Legacy
Style". The External Plugins guide is updated so that it consistently advises
uses to use the embedded pluginserver option for Go.
The external go-pluginserver is deprecated and scheduled to be removed in 2.8. As such, docs need to advise users to use the new embedded pluginserver option for Go plugins.
=> Update Go pdk docs

app/_data/docs_nav_kic_2.2.x.yml, app/kubernetes-ingress-controller/2.2.x/guides/using-gateway-api.md
Adds a new Gateway API guide for KIC.
New 2.2 alpha feature.
Tested code by running it.
This is a follow-up to https://github.com/Kong/docs.konghq.com/pull/3621 and should not be merged until after it, and should be rebased to main to drop the first commit after.
Per https://github.com/Kong/docs.konghq.com/pull/3621#issuecomment-1029444084 we need to mark this alpha, but it appears that the front matter isn't working as expected.
=> Add KIC Gateway API Guide

app/gateway/2.8.x/configure/auth/index.md, app/gateway/2.8.x/configure/auth/kong-manager/workspaces.md, app/gateway/2.8.x/developer-portal/administration/application-registration/auth-provider-strategy.md, app/gateway/2.8.x/developer-portal/administration/application-registration/azure-oidc-config.md, app/gateway/2.8.x/developer-portal/administration/application-registration/enable-application-registration.md, app/gateway/2.8.x/developer-portal/administration/application-registration/enable-key-auth-plugin.md, app/gateway/2.8.x/developer-portal/administration/application-registration/okta-config.md, app/gateway/2.8.x/developer-portal/configuration/authentication/oidc.md, app/gateway/2.8.x/developer-portal/configuration/smtp.md, app/gateway/2.8.x/developer-portal/index.md, app/gateway/2.8.x/developer-portal/theme-customization/adding-javascript-assets.md, app/gateway/2.8.x/developer-portal/theme-customization/easy-theme-editing.md, app/gateway/2.8.x/developer-portal/theme-customization/emails.md, app/gateway/2.8.x/developer-portal/theme-customization/markdown-extended.md, app/gateway/2.8.x/developer-portal/theme-customization/single-page-app.md, app/gateway/2.8.x/developer-portal/using-the-editor.md, app/gateway/2.8.x/get-started/comprehensive/secure-services.md, app/gateway/2.8.x/plan-and-deploy/hybrid-mode/hybrid-mode-setup.md, app/gateway/2.8.x/reference/configuration.md, app/gateway/2.8.x/reference/external-plugins.md
Copying changes made since previous merge from Gateway 2.7.x docs to Gateway 2.8.x docs.
See merge commit for reference: https://github.com/Kong/docs.konghq.com/commit/45a647d61aca27fa82a3f481313e46dc36058849
Chore PR. Have to manually copy content as we don't have automation for this.
Scroll through changes and check that nothing looks out of place.
=> (chore) Copy changes from 2.7.x to 2.8.x

app/_data/kong_versions.yml
Check Gateway dependencies against wiki & changelogs and update accordingly.
In general, I don't actually know if we use these dependencies for anything on the docs site. I'm updating it because it's there, but it might be worth taking a second look at post-2.8. One for the retro.
N/A
=> (chore) Update dependencies for 2.8

app/_hub/kong-inc/prometheus/index.md
It adds one extra field to the plugin.
The pull request which introduced the change is https://github.com/Kong/kong/pull/8387
Internal Tracking in FT-2426
=> document new version of the Prometheus plugin in 2.8

app/_data/extensions/kong-inc/prometheus/versions.yml
Prometheus plugin version skips 1.5 and goes directly to 1.6.
Plugin was changed to 1.6 but the nav label wasn't. See https://github.com/Kong/docs.konghq.com/pull/3712#issuecomment-1054142647.
Check that the dropdown contains 1.6.x and 1.4.x, but not 1.5.x: https://deploy-preview-3721--kongdocs.netlify.app/hub/kong-inc/prometheus/
=> Bump prometheus plugin nav version

.github/workflows/require-review-label.yml
Fix label name.
The labeler GH action looks for `review:autogen`, but the label placed on autogenerated docs is `review:autodoc`. See https://github.com/Kong/docs.konghq.com/pull/3725
N/A
=> Fix autodoc label name

app/_hub/kong-inc/aws-lambda/index.md
* Deprecate `proxy_scheme` parameter
* Improve description for `proxy_url` parameter: added a bit of info on using `http` and explained that it's still secure (which is definitely something users would ask about)
Eng PR: https://github.com/Kong/kong/pull/8406 
https://deploy-preview-3726--kongdocs.netlify.app/hub/kong-inc/aws-lambda/
=> [DOCU-2214] AWS lambda plugin: deprecate proxy_scheme

app/gateway/2.8.x/configure/auth/kong-manager/oidc-mapping.md
Add `admin_auto_create_rbac_token_disabled` to the Kong Manager OIDC configuration topic.
https://github.com/Kong/kong-ee/pull/2988
Originally added to https://github.com/Kong/docs.konghq.com/pull/3717, which wasn't the right place for this information.
https://deploy-preview-3727--kongdocs.netlify.app/gateway/2.8.x/configure/auth/kong-manager/oidc-mapping/
=> Document admin_auto_create_rbac_token_disabled

app/_assets/javascripts/promo-banner.js, app/_assets/stylesheets/header.less, app/_includes/nav-v2.html, gulpfile.js
Enabling the promo banner and prepping link to 2.8 release blog.
https://deploy-preview-3728--kongdocs.netlify.app/
Check the promo banner at the top of any docs page.
Note to reviewers: the link will be broken for now, as the blog isn't live yet.
=> [DOCU-2211] Promo banner for gateway 2.8

app/deck/1.11.x/guides/multi-file-state.md
Recently a [GH issue](https://github.com/Kong/deck/issues/574) was opened for `deck`  in regards to some confusing behaviour when using multiple state files along with the `--select-tag`.
Here we are adding some clarification on how these two features should be used together.
https://github.com/Kong/deck/issues/574
Steps included in the ticket and in the docs itself.
=> Clarify how to use deck with tags and multiple files

app/_assets/stylesheets/footer.less, app/_includes/footer.html
Fixing the docs site footer.
**SEO work:**
- Updating URLs from `http` to `https`
- Removing tracking queries from URLs
**Accessibility:**
- Switching the h5 category headers to a named div
Reference: https://w3.org/WAI/tutorials/page-structure/headings/
**Consistency with marketing site:**
- Added missing links to Kong Gateway and Kong Mesh
- Updated the "Get Started" URL to go to the correct place instead of a redirect
- Updated the solution guide URLs to go to the correct pages instead of redirects
Partially fixes DOCU-2204 (mixed content links) and DOCU-2205 (tracking parameters).
Fixes recommended based on SEO audit results, accessibility guidelines (header levels), and consistency with the konghq.com marketing site. 
See the footer: https://deploy-preview-3693--kongdocs.netlify.app/
=> Update & fix docs site footer

app/gateway/2.8.x/install-and-run/migrate-ce-to-ke.md, app/gateway/2.8.x/install-and-run/upgrade-enterprise.md, app/gateway/2.8.x/install-and-run/upgrade-oss.md
Bump versions from 2.6.x/2.7.x to 2.7.x/2.8.x.
OSS:
* Added section on deprecations: `go-pluginserver` and CentOS support.
Enterprise: 
* There are no breaking changes or particular upgrade considerations for this release.
Gateway 2.8 release.
https://deploy-preview-3730--kongdocs.netlify.app/gateway/2.8.x/install-and-run/migrate-ce-to-ke/
https://deploy-preview-3730--kongdocs.netlify.app/gateway/2.8.x/install-and-run/upgrade-enterprise/
https://deploy-preview-3730--kongdocs.netlify.app/gateway/2.8.x/install-and-run/upgrade-oss/
Verified with eng.
=> [DOCU-2195] Upgrade guide updates for 2.8

app/enterprise/1.5.x/introduction/index.md, app/enterprise/1.5.x/release-notes.md, app/enterprise/2.1.x/introduction/index.md
Searched for `itm` and `utm` params used in URLs leading to *.konghq.com, and removed them.
Companion PR to https://github.com/Kong/docs.konghq.com/pull/3693.
We have other means of tracking traffic to konqhq.com, so including these params creates skewed/inaccurate data and reflects poorly on our SEO.
N/A
=> [DOCU-2205] Remove tracking params from URLs to konghq.com

app/gateway/2.8.x/install-and-run/centos.md
Adding a deprecation notice for the CentOS installation doc and removing OSS install instructions.
CentOS has reached EOL and Kong is no longer building OSS CentOS images.
https://deploy-preview-3729--kongdocs.netlify.app/gateway/2.8.x/install-and-run/centos/
=> [DOCU-2215] Deprecation notice for gateway OSS on centos

app/gateway/2.8.x/reference/configuration.md
Generate configuration reference for Gateway 2.8 from `kong.conf.default`.
Manually document `admin_auto_create_rbac_token_disabled`, as it is missing from the source file in the kong-ee repo. This one will need tech review.
Chore PR.
https://deploy-preview-3717--kongdocs.netlify.app/gateway/2.8.x/reference/configuration/
=> (chore) Generate config reference for 2.8

.github/workflows/algolia.yml
Add `workflow_dispatch` to algolia GH action so that any docs team member can manually kick off the Algolia indexer for search.
Need this option for release days. Currently, I run the indexer manually from my local env on a release day.
N/A, need to merge first.
=> Add workflow_dispatch option for algolia indexer

.github/workflows/add-plugin-version.yml
Apply a `review:autodoc` label.
Every PR needs a label. Eg https://github.com/Kong/docs.konghq.com/pull/3733. 
Won't be able to test until we run it in a future release.
=> Review label for plugin version GH action

app/_includes/footer.html
Fixing a broken link to konghq.com/gateway/. This used to be a redirect but no longer works.
Every link check will fail until this is fixed because the footer is on every page.
Link check passed.
=> Fix broken link in footer

app/kubernetes-ingress-controller/2.1.x/guides/cert-manager.md
added additional `podAnnotations` for `cert-manager` ingress. In situations when https ingress deployed in kuma managed namespace, we don't want to inject sidecar for `cert-manager` solver ingress.
added `podTemplate` yaml snipped with anotations. Ref: https://github.com/cert-manager/cert-manager/pull/1749
Users may deploy Kong ingress in the same namespace with kuma.
This snippet prevents injecting sidecar in cert-manager` solver ingress. 
run through this instruction in GKE cluster with cert-manager installed.
=> [cert-manager.md] Improve `ClusterIssuer` snippet 

app/enterprise/2.1.x/vitals/vitals-influx-strategy.md, app/enterprise/2.1.x/vitals/vitals-prometheus-strategy.md, app/enterprise/2.2.x/vitals/vitals-influx-strategy.md, app/enterprise/2.2.x/vitals/vitals-prometheus-strategy.md, app/enterprise/2.3.x/vitals/vitals-influx-strategy.md, app/enterprise/2.3.x/vitals/vitals-prometheus-strategy.md, app/enterprise/2.4.x/vitals/vitals-influx-strategy.md, app/enterprise/2.4.x/vitals/vitals-prometheus-strategy.md, app/enterprise/2.5.x/vitals/vitals-influx-strategy.md, app/enterprise/2.5.x/vitals/vitals-prometheus-strategy.md, app/gateway/2.6.x/vitals/vitals-influx-strategy.md, app/gateway/2.6.x/vitals/vitals-prometheus-strategy.md, app/gateway/2.7.x/vitals/vitals-influx-strategy.md, app/gateway/2.7.x/vitals/vitals-prometheus-strategy.md, app/gateway/2.8.x/vitals/vitals-influx-strategy.md, app/gateway/2.8.x/vitals/vitals-prometheus-strategy.md
Add note on InfluxDB and Prometheus that on Hybrid Mode, you need to configure `vitals_strategy` and `vitals_tsdb_address` on both the Control Plane and all Data Planes. Added to 2.6.x and 2.7.x
Addresses [DOCU-978](https://konghq.atlassian.net/browse/DOCU-978)
https://deploy-preview-3671--kongdocs.netlify.app/gateway/2.7.x/vitals/vitals-prometheus-strategy/#enable-vitals-with-prometheus-strategy-in-kong
https://deploy-preview-3671--kongdocs.netlify.app//gateway/2.7.x/vitals/vitals-influx-strategy/#configure-kong-gateway
=> [DOCU-978] Add Hybrid Mode note for Vitals

app/enterprise/1.3-x/admin-api/index.md, app/enterprise/1.5.x/admin-api/index.md, app/enterprise/2.1.x/admin-api/index.md, app/enterprise/2.2.x/admin-api/index.md, app/enterprise/2.3.x/admin-api/index.md, app/enterprise/2.4.x/admin-api/index.md, app/enterprise/2.5.x/admin-api/index.md, app/gateway-oss/1.3.x/admin-api.md, app/gateway-oss/1.4.x/admin-api.md, app/gateway-oss/1.5.x/admin-api.md, app/gateway-oss/2.0.x/admin-api.md, app/gateway-oss/2.1.x/admin-api.md, app/gateway-oss/2.2.x/admin-api.md, app/gateway-oss/2.3.x/admin-api.md, app/gateway-oss/2.4.x/admin-api.md, app/gateway-oss/2.5.x/admin-api.md, app/gateway/2.6.x/admin-api/index.md, app/gateway/2.7.x/admin-api/index.md, app/gateway/2.8.x/admin-api/index.md
Remove Admin API **Delete Service Associated to a Specific Route** endpoint from versions 1.3.x onward.
Addresses [DOCU-348](https://konghq.atlassian.net/browse/DOCU-348)
Latest:
https://deploy-preview-3740--kongdocs.netlify.app/gateway/2.8.x/admin-api/#delete-service
=> [DOCU-348] Admin API: rm del service for route

app/_includes/md/gateway/setup.md, app/gateway/2.8.x/install-and-run/docker.md
* Add license env variable to docker installation instructions.
*  If the user wants to, they can simply exclude the variable. If they have no license and leave the setting in, the container still starts with no issues, just without a license.
* Added links to license docs for other license application options
* Improve license step for distros + a bit of cleanup 
* Instead of linking to the "Deploy license" topic, included the instructions on the page, so that users have a clear choice depending on their environment.
* Removed editable placeholders; a few had editable password fields, which isn't secure, and otherwise, we're avoiding using editable placeholders until we overhaul them.
* Short descriptions for Manager and Dev Portal sections to call out the need for a database.
There's …
=> [DOCU-2217] Better license info in installation guides

app/enterprise/2.1.x/admin-api/index.md, app/enterprise/2.2.x/admin-api/index.md, app/enterprise/2.3.x/admin-api/index.md, app/enterprise/2.4.x/admin-api/index.md, app/enterprise/2.5.x/admin-api/index.md, app/gateway-oss/2.1.x/admin-api.md, app/gateway-oss/2.2.x/admin-api.md, app/gateway-oss/2.3.x/admin-api.md, app/gateway-oss/2.4.x/admin-api.md, app/gateway-oss/2.5.x/admin-api.md, app/gateway/2.6.x/admin-api/index.md, app/gateway/2.7.x/admin-api/index.md, app/gateway/2.8.x/admin-api/index.md
All the following from EE, CE, and Gateway (single sourced) 2.1.x and newer.
1. Remove endpoints that meet the following form:
```
/targets
/targets/{targets}
/targets/{targets}/upstream
```
2. Remove `run_on`
3. For list targets and add targets, remove `host:port`
Addresses [DOCU-1618](https://konghq.atlassian.net/browse/DOCU-1618)
Applied to 2.1.x and newer. Here's the latest from our single sourced Gateway docs:
**Note that the indenting was there to begin with - I didn't modify the styling. 
https://deploy-preview-3684--kongdocs.netlify.app/gateway/2.7.x/admin-api/
https://deploy-preview-3684--kongdocs.netlify.app/gateway/2.6.x/admin-api/
=> [DOCU-1618] RM deprecated Target endpoints

app/_hub/kong-inc/response-transformer-advanced/index.md, app/_hub/kong-inc/response-transformer/index.md
Add more content to differentiate Response Transformer and Response Transformer Advanced. 
Moved over the Advanced differentiator description from Advanced, and add a list of configs that Advanced only has.
Addresses [DOCU-510](https://konghq.atlassian.net/browse/DOCU-510)
https://deploy-preview-3750--kongdocs.netlify.app/hub/kong-inc/response-transformer-advanced/
https://deploy-preview-3750--kongdocs.netlify.app/hub/kong-inc/response-transformer/
=> [DOCU-510] Add diff: Response Transformer Advanced

app/gateway/2.6.x/plan-and-deploy/kubernetes-deployment-options.md, app/gateway/2.7.x/plan-and-deploy/kubernetes-deployment-options.md, app/gateway/2.8.x/plan-and-deploy/kubernetes-deployment-options.md
“[Database-backed installation with or without the Kong Ingress Controller](https://docs.konghq.com/gateway/2.7.x/install-and-run/kubernetes)" currently goes to [Install on Kubernetes - v2.7.x | Kong Docs](https://docs.konghq.com/gateway/2.7.x/install-and-run/kubernetes/). Updated to go to [Install on Kubernetes with Helm - v2.7.x | Kong Docs](https://docs.konghq.com/gateway/2.7.x/install-and-run/helm).
Addresses docs domain piece of https://konghq.atlassian.net/browse/DOCU-2196
Updated on 2.6.x and newer. Investigating whether or not we should make this change to older versions. 
@lena-larionova on older versions, I looked at the [Installing Kong for Kubernetes Enterprise](https://deploy-preview-3749--kongdocs.netlify.app/enterprise/2.5.x/deployment/installation/kong-for-kubernetes/) and …
=> [DOCU-2196] Update k8 install link

app/konnect/deployment/index.md, app/konnect/runtime-manager/gateway-runtime-docker.md, app/konnect/runtime-manager/gateway-runtime-kubernetes.md, app/konnect/updates.md
* Adding a release note for Kong Gateway 2.8 support
* Updating versions to 2.8
* In Docker runtime topic, removing section to pull and tag the Docker image. This section is redundant and not actually used, as we explicitly call out the version tag in the "Start Kong Gateway" section.
Gateway 2.8 support for Konnect Cloud was introduced yesterday.
Tested by setting up a 2.8.0.0 Docker runtime through Konnect Runtime Manager.
Release note: https://deploy-preview-3752--kongdocs.netlify.app/konnect/updates/
Docker: https://deploy-preview-3752--kongdocs.netlify.app/konnect/runtime-manager/gateway-runtime-docker/
=> Konnect: Gateway 2.8 support

app/_hub/kong-inc/graphql-rate-limiting-advanced/index.md, app/_hub/kong-inc/proxy-cache-advanced/index.md, app/_hub/kong-inc/rate-limiting-advanced/index.md, app/gateway/changelog.md
Add missing redis params: `keepalive_pool`, `keepalive_pool_size`, and `keepalive_backlog` to GraphQL Rate Limiting Advanced, Proxy Cache Advanced, and Rate Limiting Advanced plugins.
Add `keepalive_pool_size` to changelog entry.
Addresses [DOCU-1968](https://konghq.atlassian.net/browse/DOCU-1968).
GraphQL Rate Limiting Advanced: https://deploy-preview-3754--kongdocs.netlify.app/hub/kong-inc/graphql-rate-limiting-advanced/#parameters
Rate Limiting Advanced: https://deploy-preview-3754--kongdocs.netlify.app/hub/kong-inc/rate-limiting-advanced/#parameters
Proxy Cache Advanced: https://deploy-preview-3754--kongdocs.netlify.app/hub/kong-inc/proxy-cache-advanced/#parameters
Changelog entry: https://deploy-preview-3754--kongdocs.netlify.app/gateway/changelog/#plugins-15 (added …
=> [DOCU-1968] Add missing redis params to plugins

app/konnect-platform/support-policy.md
Updating table of supported versions to include gateway 2.8. 
Missed this update for the 2.8 release. Adding to release checklist going forward, and need to find out when the version support policy ownership is transferring to the CX team.
Netlify preview TBA
=> Add gateway 2.8 to version support policy

app/_includes/md/enterprise/turn-on-rbac.md
In the Get Started Comprehensive guide, we have a broken `echo` command. I removed the `\` characters, which were breaking the command. 
Addresses [DOCU-2093](https://konghq.atlassian.net/browse/DOCU-2093)
The change is made in an includes file, meaning that I only had to do it in one place. 
https://deploy-preview-3755--kongdocs.netlify.app/gateway/2.8.x/get-started/comprehensive/manage-teams/#turn-on-rbac
=> [DOCU-2093] Remove breaking \ from get started

app/contributing/markdown-rules.md, app/gateway/2.6.x/configure/auth/kong-manager/networking.md, app/gateway/2.6.x/developer-portal/working-with-templates.md, app/gateway/2.6.x/install-and-run/upgrade-oss.md, app/gateway/2.6.x/plan-and-deploy/systemd.md, app/gateway/2.7.x/configure/auth/kong-manager/networking.md, app/gateway/2.7.x/developer-portal/working-with-templates.md, app/gateway/2.7.x/install-and-run/upgrade-oss.md, app/gateway/2.7.x/plan-and-deploy/systemd.md, app/gateway/2.7.x/plugin-development/custom-logic.md, app/gateway/2.8.x/configure/auth/kong-manager/networking.md, app/gateway/2.8.x/developer-portal/working-with-templates.md, app/gateway/2.8.x/install-and-run/upgrade-oss.md, app/gateway/2.8.x/plan-and-deploy/systemd.md, app/gateway/2.8.x/plugin-development/custom-logic.md
* Add instructions to Markdown guide to end usage of code in headers
* Remove code in headers from (inclusive) 2.6.x - 2.8.x
Addresses [DOCU-1996](https://konghq.atlassian.net/browse/DOCU-1996)
Note that some of the changes I made will also be made over on the Kong/kong repo, as some of the content was auto-generated.
@lena-larionova is Working with Templates auto-generated? And if so, from where?
Contributing guide: https://deploy-preview-3756--kongdocs.netlify.app/contributing/markdown-rules/#headers
Kong Manager networking: https://deploy-preview-3756--kongdocs.netlify.app/gateway/2.8.x/configure/auth/kong-manager/networking/#using-httpslocalhost
Dev Portal Working with Templates: https://deploy-preview-3756--kongdocs.netlify.app/gateway/2.8.x/developer-portal/working-with-templates/ …
=> [DOCU-1996] Remove code in headers

app/gateway/2.8.x/configure/auth/allowing-multiple-authentication-methods.md
I believe that there is a typo in the docs, the following sentence
> Next, we add both Key Auth and Basic Auth plugins to our consumer, and set the anonymous fallback to the consumer we created earlier.
Should be changed for
> Next, we add both Key Auth and Basic Auth plugins to our service, and set the anonymous fallback to the consumer we created earlier.
The documentation is saying that we are adding the plugins to the consumer, but the plugins are being added to the service.
No need, it's just a documentation typo fix.
=> Fix typo in allowing-multiple-authentication-methods.md

app/kubernetes-ingress-controller/2.2.x/guides/cert-manager.md
Copy of changes made in https://github.com/Kong/docs.konghq.com/pull/3707.
Changes were not pulled into latest version.
https://deploy-preview-3763--kongdocs.netlify.app/kubernetes-ingress-controller/2.2.x/guides/cert-manager/#request-tls-certificate-from-lets-encrypt
=> Additional podAnnotations for cert-manager

app/_layouts/default.html
Setting `nofollow noreferrer` to `http` instead of  both `http` and `https`.
We are currently setting `nofollow noreferrer` on all absolute URLs. This means we're blocking tracking and indexing for every single absolute link, including any links to konghq.com sites. Taking SEO team's recommendation to only set it for unsecured absolute URLs.
TBA
=> Set nofollow rule for unsecured URLs only

app/_assets/stylesheets/badges.less
Adjusting badge and tooltip positioning to make it consistent. 
Having `inline-flex` set on the base `badge` element is causing issues with badges in headers. Ran into this issue while working on Konnect docs and trying to apply badges to sections in the docs.
Before:
After:
Sample pages with badges; hover over a badge to see a tooltip:
https://deploy-preview-3769--kongdocs.netlify.app/gateway/
https://deploy-preview-3769--kongdocs.netlify.app/gateway/2.8.x/reference/configuration/#default-developer-portal-authentication-section
https://deploy-preview-3769--kongdocs.netlify.app/gateway/2.8.x/install-and-run/macos/
https://deploy-preview-3769--kongdocs.netlify.app/hub/kong-inc/application-registration/
=> Adjust positioning of badges and tooltips in headers

app/enterprise/2.1.x/health-checks-circuit-breakers.md, app/enterprise/2.2.x/health-checks-circuit-breakers.md, app/enterprise/2.3.x/health-checks-circuit-breakers.md, app/enterprise/2.4.x/health-checks-circuit-breakers.md, app/enterprise/2.5.x/health-checks-circuit-breakers.md, app/gateway-oss/2.0.x/health-checks-circuit-breakers.md, app/gateway-oss/2.1.x/health-checks-circuit-breakers.md, app/gateway-oss/2.2.x/health-checks-circuit-breakers.md, app/gateway-oss/2.3.x/health-checks-circuit-breakers.md, app/gateway-oss/2.4.x/health-checks-circuit-breakers.md, app/gateway-oss/2.5.x/health-checks-circuit-breakers.md, app/gateway/2.6.x/reference/health-checks-circuit-breakers.md, app/gateway/2.8.x/reference/health-checks-circuit-breakers.md
Back-port changes from #3777 to 2.0.x upwards
See review app
=> Backport #3777 to old versions

show-version-diff/README.md, show-version-diff/package-lock.json, show-version-diff/package.json, show-version-diff/run.js
Show the changes between all versions of a single file using `diff`.
The following command shows all changes to `deck.md`, ignoring the `pre-1.7` folder.
```bash
node run.js --source ../app/deck/1.11.x/reference/deck.md --ignore "pre-1.7"
```
https://user-images.githubusercontent.com/59130/159183785-6262dad2-3470-4c98-9267-5bf65b20fb70.mp4
To make it easier to see differences between versions whilst combining files. Useful once #3765 is merged
Clone the branch, run the command above and take a look at the output
=> Add show-version-diff utility

app/konnect-platform/support-policy.md
Update Gateway 2.8 release dates to be 12 months later
2.8 is the last minor version before the major 3.0 release, so we're adding an additional support period
Waiting for review app
=> Update Gateway 2.8.x support dates

app/mesh/1.6.x/features/kds-auth.md
This document has been very outdated referencing the word "remote" when we have renamed this to "zone" a while back. This includes a long list of variable names which made all copy&paste examples fail
=> Fixing all traces of old "remote" against "zone"

app/gateway/2.8.x/install-and-run/ubuntu.md
Please see https://kongstrong.slack.com/archives/C0DSXDXV1/p1648243358762779 for more information.
The Enterprise tab was pointing to the OSS version of the file, and had the wrong naming convention as well. These are corrected now with this PR.
The URLs were incorrect earlier, pointing to a 404 Not Found file instead as the URL wasn't accurate.
Can follow the fully formed URLs to test. Was a little difficult for me to see in Preview mode as it didn't contain the full URL, but I believe the changes I made are all that's needed (1: pointing to kong-enterprise-edition in the directory structure, and 2: replacing _amd64 with _all).
=> Corrected the install URL for EE on Ubuntu

app/_data/docs_nav_gateway_2.8.x.yml, app/gateway/2.8.x/admin-api/developers/reference.md
First pass at documenting the Kong admin API `/developers` endpoints, including a new `/developers/export` endpoint being introduced in Gateway 2.8. This doc will eventually be turned into a spec and generated that way, but for now it is written manually to match the rest of our Kong Admin API docs.
Everything based on https://github.com/Kong/kong-ee/blob/master/kong/api/routes/developers.lua.
Original endpoint list from https://konghq.atlassian.net/browse/FTI-2907, verified against the code.
Note: The `/developers/{developer}/consumer` endpoint is in the ticket but not in the `developers.lua` file. What is the purpose of that endpoint? Should it be in the doc?
~To do:~
~* Get some outstanding questions answered~
~* Write an intro~
~* Write descriptions for each section~
All done.
This …
=> [DOCU-280] Document the kong admin API /developers endpoint

app/gateway/changelog.md
Added a note about a feature being PostgreSQL only (i.e. does not apply to Cassandra users).
Seems this feature is applicable to PostgreSQL only, based on comments in https://github.com/Kong/kong-ee/pull/2839.
=> Added note about a feature being PostreSQL-applicable only

app/gateway/2.7.x/install-and-run/debian.md, app/gateway/2.8.x/install-and-run/debian.md
Fixing gateway enterprise install URL.
Companion PR to #3787 . Same error on Debian doc.
The files are here, note the `kong-enterprise-edition` in the URL:
https://download.konghq.com/gateway-2.x-debian-jessie/pool/all/k/kong-enterprise-edition/
The previous URL pointed to OSS install files: 
https://download.konghq.com/gateway-2.x-debian-jessie/pool/all/k/kong/
=> Fix install URLs for Debian

app/gateway/2.7.x/developer-portal/theme-customization/alternate-openapi-renderer.md, app/gateway/2.8.x/developer-portal/theme-customization/alternate-openapi-renderer.md
The docs currently show `spec_renderer_type` when it should be `spec_render_type`
Customer reported issue
Validated in the spec-renderer file:
https://github.com/Kong/docs.konghq.com/blob/main/app/code-snippets/spec-renderer.html#L16
Check the review app at /gateway/2.8.x/developer-portal/theme-customization/alternate-openapi-renderer/
=> Fix spec_render_type typo in Portal docs

app/enterprise/0.31-x/plugins/rbac-api.md, app/enterprise/0.32-x/plugins/rbac-api.md, app/enterprise/0.33-x/rbac/admin-api.md, app/enterprise/0.34-x/rbac/admin-api.md, app/enterprise/0.35-x/admin-api/rbac/reference.md, app/enterprise/0.36-x/admin-api/rbac/reference.md, app/enterprise/1.3-x/admin-api/rbac/reference.md, app/enterprise/1.5.x/admin-api/rbac/reference.md, app/enterprise/2.1.x/admin-api/rbac/reference.md, app/enterprise/2.2.x/admin-api/rbac/reference.md, app/enterprise/2.3.x/admin-api/rbac/reference.md, app/enterprise/2.4.x/admin-api/rbac/reference.md, app/enterprise/2.5.x/admin-api/rbac/reference.md, app/gateway/2.6.x/admin-api/rbac/reference.md, app/gateway/2.7.x/admin-api/rbac/reference.md, app/gateway/2.8.x/admin-api/rbac/reference.md
Typo in `DELETE` roles request examples in RBAC admin API docs.
https://konghq.atlassian.net/browse/FT-2498
No doc ticket; this is a quick fix for an FT ticket that's been hanging around for a few weeks, and it has no reason to.
Checked the API definition, it's definitely `roles`: https://github.com/Kong/kong-ee/blob/master/kong/api/routes/rbac.lua#L436-L443
=> Fix RBAC typo

app/gateway/2.6.x/get-started/comprehensive/load-balancing.md, app/gateway/2.7.x/get-started/comprehensive/load-balancing.md, app/gateway/2.8.x/get-started/comprehensive/load-balancing.md, app/getting-started-guide/2.3.x/load-balancing.md, app/getting-started-guide/2.4.x/load-balancing.md, app/getting-started-guide/2.5.x/load-balancing.md
Fixing the upstream hostname. We changed the name to `example_upstream` some time back to avoid running into reserved entity issues, but missed a couple of instances of the old name.
Ran a search through all the getting started guides for `upstream` and replaced it with the correct name.
Customer-reported issue: https://github.com/Kong/docs.konghq.com/issues/3795
Resolves #3795
Netlify preview.
=> Fix upstream name

app/_plugins/konnect_icon_tag.rb
Adds a new helper to show inline Konnect icons
Usage: `{% konnect_icon runtimes %}`
Output:
```
```
Add a single point of configuration for how inline icons look in the Konnect docs
Add `{% konnect_icon runtimes %}` to a page and inspect the HTML. You'll see the `alt` text if the icon doesn't exist
=> Add konnect_icon helper

app/gateway/2.8.x/developer-portal/helpers/cli.md
Made a very minor typo fix where the documentation stated "Enable" but it should be "Disable"
=> Fixing a typo

app/kubernetes-ingress-controller/2.2.x/troubleshooting.md
Adds instructions for accessing the ingress controller's profiler.
It's something we ask users to do but didn't really document.
None.
=> doc(kic) add profiling instructions

app/_hub/kong-inc/key-auth-enc/index.md
There was a small issue with our docs where we were still referencing the non-encrypted plugin
=> Fixing small references to non-encrypted plugin

app/_hub/kong-inc/request-transformer-advanced/index.md
Fix the typo "for pefixing" in request-transformer-advanced plugin
=> Fix a typo in request-transformer-advanced plugin

app/_data/docs_nav_mesh_1.7.x.yml, app/mesh/1.7.x/features/acmpca.md, app/mesh/1.7.x/features/vault.md, app/mesh/1.7.x/gettingstarted.md
Add documentation for Mesh support of AWS ACM Private CA
New feature
Generate the page and read.
=> docs(kuma-cp): Add documentation for ACM Private CA

app/_data/docs_nav_mesh_1.7.x.yml, app/_data/kong_versions.yml, app/_redirects, app/mesh/1.7.x/features/windows.md, app/mesh/1.7.x/installation/docker.md, app/mesh/1.7.x/installation/kubernetes.md
Make windows and ubi docs more prominent
Windows was not listed in the list of enterprise features and UBI images were not referenced in the different install docs.
=> chore(mesh): make windows and ubi docs more prominent

app/konnect/configure/runtime-manager/runtime-groups/declarative-config.md, app/konnect/configure/runtime-manager/runtime-groups/manage.md, app/konnect/deployment/import.md
Replace the `--konnect-runtime-group` flag with `--konnect-runtime-group-name`
Flag has changed recently
=> fix: use correct deck flag for RGs

app/_includes/md/konnect/dev-portal-access.md, app/konnect/dev-portal/access-and-approval/auto-approve-devs-apps.md, app/konnect/dev-portal/customization/custom-domain.md, app/konnect/dev-portal/customization/public-portal.md
Updating any instructions for accessing dev portal settings in Konnect to use new location.
Also adding role prereqs needed to be able to access the menu item.
The settings page for the dev portal moved from `Settings` -> `Portal` to `Dev Portal` -> `Settings`. 
The `Portal URL` setting moved under that option as well.
Ran a search for any mention of settings or of Dev Portal customization. Checked the cloud-02 site to verify.
=> [DOCU-2265] Dev portal settings page relocation

app/mesh/1.6.x/installation/helm.md, app/mesh/1.7.x/installation/helm.md
Unless I have a very funky local setup, the command `helm chart values x/x` does not work. Using `helm show values x/x` does work though.
```
$ helm version
version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.17.2"}
$ helm chart values kong-mesh/kong-mesh
Error: unknown command "chart" for "helm"
Run 'helm --help' for usage.
```
I was unable to add the label, but it would be `review:copyedit` 😄
=> Update helm install commands

app/gateway/2.7.x/admin-api/consumer-groups/reference.md, app/gateway/2.8.x/admin-api/consumer-groups/reference.md
Fixes consumers groups rate limiting overrides body attributes.
https://docs.konghq.com/gateway/2.7.x/admin-api/consumer-groups/reference/#configure-rate-limiting-for-a-consumer-group
They do not mention the keys being nested in a config dict.
incorrect body payload:
```json
{
"window_size": [60],
"limit": [200]
}
```
correct body payload:
```json
{
"config": {
"window_size": [60],
"limit": [200]
}
}
```
verify by sending a PUT to the admin endpoint with both payloads mentioned above
=> Fix consumers groups rate limiting overrides attributes

Makefile, README.md, docs/platform-install.md, package.json
Clean up the `Makefile` and add detailed platform installation instructions for MacOS under the `docs` folder.
To make it easier for people to run the docs site locally and contribute.
I've tested these instructions in a fresh MacOS virtual machine and could build the site as expected
=> Platform setup

app/gateway/2.8.x/developer-portal/administration/application-registration/enable-application-registration.md
Re-adding "enable application registration" doc content to fix copy-paste error from 2.8.
Issue filed here: https://github.com/Kong/docs.konghq.com/issues/3847
Issue caused by human error (accidentally overwrote the file when copying changes from 2.7 to 2.8); this will be avoidable in the future as we switch to single-sourced docs.
Check that 2.8.x now has the same content as 2.7.x.
https://deploy-preview-3854--kongdocs.netlify.app/gateway/2.8.x/developer-portal/administration/application-registration/enable-application-registration/
https://deploy-preview-3854--kongdocs.netlify.app/gateway/2.7.x/developer-portal/administration/application-registration/enable-application-registration/
=> Re-add 'enable app reg' doc

app/enterprise/0.35-x/pdk/kong.client.md, app/enterprise/0.36-x/pdk/kong.client.md, app/enterprise/1.3-x/pdk/kong.client.md, app/enterprise/1.5.x/pdk/kong.client.md, app/enterprise/2.1.x/pdk/kong.client.md, app/enterprise/2.2.x/pdk/kong.client.md, app/enterprise/2.3.x/pdk/kong.client.md, app/enterprise/2.4.x/pdk/kong.client.md, app/enterprise/2.5.x/pdk/kong.client.md, app/gateway-oss/0.14.x/pdk/kong.client.md, app/gateway-oss/1.0.x/pdk/kong.client.md, app/gateway-oss/1.1.x/pdk/kong.client.md, app/gateway-oss/1.2.x/pdk/kong.client.md, app/gateway-oss/1.3.x/pdk/kong.client.md, app/gateway-oss/1.4.x/pdk/kong.client.md, app/gateway-oss/1.5.x/pdk/kong.client.md, app/gateway-oss/2.0.x/pdk/kong.client.md, app/gateway-oss/2.1.x/pdk/kong.client.md, app/gateway-oss/2.2.x/pdk/kong.client.md, app/gateway-oss/2.3.x/pdk/kong.client.md, app/gateway-oss/2.4.x/pdk/kong.client.md, app/gateway/2.6.x/pdk/kong.client.md
Replace `kong.request.get_forwarded_ip()` with `kong.client.get_forwarded_ip()`. 
Continuation of https://github.com/Kong/docs.konghq.com/pull/3829. Separate PR to avoid weird fork editing issues.
This was fixed in the docs in 2.7.x but never backported, and someone recently filed a PR to fix an older version. 
Netlify preview (sample pages):
https://deploy-preview-3846--kongdocs.netlify.app/gateway/2.6.x/pdk/kong.client/#kongclientget_forwarded_ip
https://deploy-preview-3846--kongdocs.netlify.app/enterprise/2.5.x/pdk/kong.client/#kongclientget_forwarded_ip
https://deploy-preview-3846--kongdocs.netlify.app/gateway-oss/2.5.x/pdk/kong.client/#kongclientget_forwarded_ip
=> PDK fix: kong.client typo

app/_plugins/generators/single_source_generator.rb, docs/single-sourced-versions.md
Make `page.version` and `page.release` available in single sourced content
We need the concrete version number (e.g. `1.2.0`) rather than the release (`1.2.x`) in some places. This PR makes it available
I've tested on #3845 and it worked as expected
=> Add `version` to single sourcing

app/_redirects
Add missing Mesh redirect after SEO changes were merged
Fix a broken link
Review App
=> Fix broken Mesh Windows link

app/_redirects
Adding a redirect for a broken link. The source of the broken link is in the Kong Manager code.
Issue called out on Slack: https://kongstrong.slack.com/archives/CH14Q7DEH/p1650403771168029
Broken link in Kong Manager UI.
https://deploy-preview-3863--kongdocs.netlify.app/gateway/latest/admin-api/vitals - this URL should redirect to https://deploy-preview-3863--kongdocs.netlify.app/gateway/latest/vitals
=> Redirect for broken link to vitals

src/deck/reference/deck.md, src/deck/reference/deck_completion.md, src/deck/reference/deck_convert.md, src/deck/reference/deck_diff.md, src/deck/reference/deck_dump.md, src/deck/reference/deck_konnect.md, src/deck/reference/deck_konnect_diff.md, src/deck/reference/deck_konnect_dump.md, src/deck/reference/deck_konnect_ping.md, src/deck/reference/deck_konnect_sync.md, src/deck/reference/deck_ping.md, src/deck/reference/deck_reset.md, src/deck/reference/deck_sync.md, src/deck/reference/deck_validate.md, src/deck/reference/deck_version.md
* Generate decK docs using updated CLI generation script.
* Add deprecation notice to all `deck konnect` commands. 
Upcoming v1.12 release.
**For reviewers:** These files have been generated via script from [kong/deck](https://github.com/Kong/deck). The docs generation script was recently updated (see https://github.com/Kong/deck/pull/642) and reviewed on the code side. I'm aware that the content needs some work, but the main purpose of this change is to create more user-friendly formatting.
The deprecation notice comes from https://github.com/Kong/deck-private/commit/f687fd66fbc7d2d526360c519c5df93e73bf9698, slightly adjusted for format.
When reviewing this PR, please click through the deck > CLI Reference navigation, make sure they're all using the new formatting, and that every `deck …
=> decK v1.12: Generate cli docs

app/_layouts/extension.html
Setting link to go to _index.html instead of index.html.
Getting broken links on plugin landing pages. Issue called out on Slack: https://kongstrong.slack.com/archives/CDSTDSG9J/p1650478018021109
TBA, check preview.
=> Fix github edit link for plugins

app/_plugins/generators/latest_version_generator.rb, tests/install.test.js
Fix missing `version-index` so that the version shows correctly on the install pages
Current prod:
With fix:
https://deploy-preview-3869--kongdocs.netlify.app/gateway/latest/install-and-run/rhel/
=> Fix missing version-index on /latest/ pages

app/enterprise/2.1.x/deployment/licenses/report.md, app/enterprise/2.2.x/deployment/licenses/report.md, app/enterprise/2.3.x/admin-api/licenses/reference.md, app/enterprise/2.3.x/deployment/licenses/report.md, app/enterprise/2.4.x/admin-api/licenses/reference.md, app/enterprise/2.4.x/deployment/licenses/report.md, app/enterprise/2.5.x/admin-api/licenses/reference.md, app/enterprise/2.5.x/deployment/licenses/report.md, app/gateway/2.6.x/admin-api/licenses/reference.md, app/gateway/2.6.x/plan-and-deploy/licenses/report.md
Backporting improvements to the license docs and adding `/license/reports` to the Gateway admin API reference in v2.1-2.6.
Backporting through 2.1.x only, as we are going to be archiving all versions before that.
In 2.7, we updated the Kong Gateway license doc to make it easier to follow and added the missing endpoint to 2.7 and onwards. Customers ran into this doc and tried to use it in 2.6, got a slightly different result, but had nothing to compare to and assumed the current doc was wrong. This happened because 2.6 didn't document the license info in the same way.
This came up in https://github.com/Kong/docs.konghq.com/pull/3745; see comments in the closed PR for background on how we discovered what was actually going on.
To test, check the preview to make sure all the content appears …
=> Backport license doc improvements

app/_assets/stylesheets/pages/docs.less
Adjusting external link icon so that it doesn't appear below the "Run in Insomnia" button:
This button shows up here: https://docs.konghq.com/konnect/reference/konnect-api/
@Guaris pinging you since you've likely already noticed this issue, since you're working on this topic.
https://deploy-preview-3875--kongdocs.netlify.app/konnect/reference/konnect-api/
=> Remove external link icon from insomnia run button

app/konnect/configure/runtime-manager/runtime-groups/manage.md
Uncommenting the runtime group deletion instructions, since it is now possible to delete one.
You can now delete a runtime group in cloud.konghq.com.
https://deploy-preview-3872--kongdocs.netlify.app/konnect/configure/runtime-manager/runtime-groups/manage/#delete-a-runtime-group.
I've tested backing up and deleting a runtime group locally.
=> Konnect: Deleting a runtime group

app/_hub/kong-inc/oauth2/_index.md
The original docs confuses customers. Upstream header
"X-Credential-Identifier" actually evaluates to `client_id`.
Customer reporting issue at FTI-3320.
=> docs(oauth2) give more details to header X-Credential-Identifier

app/_assets/javascripts/app.js
Update the address bar + add a history entry when using in-page navigation
Fix the “click anchor link, highlight address bar, copy URL from there” muscle memory
Try using any sidebar navigation in the review app
=> Update URL when using in-page navigation

check-generated-content/run.js
We were trying to check deleted files for autogenerated content, which failed when we couldn't read the file's frontmatter (as it was deleted)
Fix the build!
I've tested locally against #3890 and it's working as expected
=> Don't check removed files for autogenerated content

app/_hub/kong-inc/prometheus/_index.md
Update docs to highlight latency unit
When working with the metrics there is no way to find out the latency unit.
No testing is needed, please confirm the Latency shows up in milliseconds. 
Seems like Kong is using ngx variables to work with the latency.
```
latency = ctx.KONG_BALANCER_ENDED_AT - ngx.req.start_time() * 1000
function Kong.preread()
local ctx = ngx.ctx
if not ctx.KONG_PROCESSING_START then
ctx.KONG_PROCESSING_START = start_time() * 1000
end
```
Nginx resources for start_time 
- https://www.nginx.com/resources/wiki/modules/lua/#ngx-req-start-time
- https://github.com/openresty/lua-nginx-module#ngxreqstart_time  
- http://nginx.org/en/docs/http/ngx_http_log_module.html # search for $request_time
```
$request_time
request processing time in seconds with a milliseconds …
```
=> Update docs for latency to specify the unit

app/_hub/kong-inc/graphql-proxy-cache-advanced/_index.md, app/_hub/kong-inc/proxy-cache-advanced/0.4.x.md, app/_hub/kong-inc/proxy-cache-advanced/_index.md, app/_hub/kong-inc/proxy-cache/0.31-x.md, app/_hub/kong-inc/proxy-cache/0.32-x.md, app/_hub/kong-inc/proxy-cache/0.33-x.md, app/_hub/kong-inc/proxy-cache/0.34-x.md, app/_hub/kong-inc/proxy-cache/_index.md
Both proxy-caching and proxy-caching-adv plugin say the default value of config.memory.dictionary_name is kong_cache. But it is not correct, please replace it with kong_db_cache in below URL
DOCU-2286
Review app
=> Fix proxy-cache config.memory.dictionary_name default value

src/gateway/plugin-development/custom-logic.md, src/gateway/plugin-development/entities-cache.md, src/gateway/plugin-development/plugin-configuration.md
Based on the migration instructions in the custom logic topic, cleaned out the BasePlugin module from examples and removed deprecated methods.
Also moved the "migrating from BasePlugin" section a bit further down; the old location made it look like the rest of the text below it was part of the migration, but it is not (see https://github.com/Kong/docs.konghq.com/pull/3400/files for reference). 
BasePlugin is deprecated and slated to be removed in 3.0.
https://deploy-preview-3903--kongdocs.netlify.app/gateway/latest/plugin-development/custom-logic/#migrating-from-baseplugin-module
https://deploy-preview-3903--kongdocs.netlify.app/gateway/latest/plugin-development/entities-cache/
https://deploy-preview-3903--kongdocs.netlify.app/gateway/latest/plugin-development/plugin-configuration/
=> [DOCU-2302] Clean out mentions of old BasePlugin module

app/gateway/2.8.x/index.md
This bulleted list explains modes and subscriptions. Since the badges for these get introduced here, it might look cleaner to put them at the beginning of the list items rather than weaving them into the sentence structure.
Just exploring your docs and GitHub workflow.
=> Move mode badges to the beginning of list items

README.md
Fix the netlify status badge.
We switched sites and there's a new link the badge now. Also, I broke it with an accidental previous commit.
Check the file in the branch: https://github.com/Kong/docs.konghq.com/blob/netlify-badge/README.md
=> Fix badge for new site

app/kubernetes-ingress-controller/2.2.x/guides/upgrade.md, app/kubernetes-ingress-controller/2.3.x/guides/upgrade.md
Update the KIC 2.x upgrade instructions for versions past 2.1 to note
that the steps apply generally to 2.x versions past 2.0.
Internal report that the current steps were unclear.
None.
=> Update KIC upgrade instructions for 2.x

app/gateway/2.6.x/plugin-development/custom-logic.md, app/gateway/2.7.x/plugin-development/custom-logic.md, app/gateway/2.8.x/plugin-development/custom-logic.md
Wrong variable is being used in the custom plugin development guides, so anywhere it refers to Kong Gateway is actually says "Kong Gateway (OSS)". Switching to the correct variable.
I also ran a search for `{{site.ce_product_name}}` throughout the 2.6.x-2.8.x versions of the gateway doc and didn't find it anywhere it shouldn't be. It's only being used in installation and update topics, and in the guide for using systemd, where the instructions vary depending on your Gateway package.
Didn't apply to versions before 2.6.x as the OSS and Enterprise gateway docs were still split then.
https://konghq.atlassian.net/browse/DOCU-2323
Check that variables resolve to "Kong Gateway" instead of "Kong Gateway (OSS)", eg in this topic:
https://deploy-preview-3933--kongdocs.netlify.app/gateway/latest/plu …
=> Fix variables in plugin development guides

app/_assets/javascripts/app.js, app/_assets/stylesheets/badges.less, app/_assets/stylesheets/page.less, app/_hub/index.html, app/_includes/header.html, app/_includes/hub_cards.html, app/_layouts/docs-v2.html, app/_layouts/extension.html
Further improvements to plugin hub badges.
* "Konnect compatible" badge to make the info more prominent
* Filter for Konnect on the plugin hub landing page
* Fix a bunch of alignment issues for badges that were making pages jumpy on load
* Fixed badge tab-ability, you can use your keyboard to move through them now
In the previous round of reviews, Hayden asked for the Konnect compatibility information to be easily visible when you first load a page, as it's currently hard to see. As well, we were asked for a Konnect filter on the Plugin Hub landing page.
Check the "Konnect" filter on the Hub landing page: https://deploy-preview-3934--kongdocs.netlify.app/hub/
Check badges on a few plugins:
* [All three badges](https://deploy-preview-3934--kongdocs.netlify.app/hub/kong-inc/opa/)
* [Only …
=> Konnect compatibility badges and filter

app/_assets/javascripts/app.js
Adds a "Contact Sales" link to the Enterprise tooltip
Old:
New:
Aghi requested 
Hover over any enterprise badge on the site
=> Add Contact Sales to Enterprise tooltip

app/_data/docs_nav_konnect.yml, app/konnect/configure/runtime-manager/runtime-instances/troubleshoot.md, app/konnect/deployment/license-management.md
* New topic for troubleshooting runtime instances in Konnect
* Some minor phrasing updates for the license topic
Info for out-of-sync runtime instances gathered from engineering; info for version compat gathered from personal testing.
Note: The process for finding a currently compatible gateway is janky and unreliable, so I've raised that issue with Ross and Hayden. Nothing else to do for this doc with that, but they're going to brainstorm a way to expose the information in the UI.
https://konghq.atlassian.net/browse/DOCU-2273
https://deploy-preview-3914--kongdocs.netlify.app/konnect/configure/runtime-manager/runtime-instances/troubleshoot/
=> [DOCU-2273] Troubleshoot runtime instances

.github/workflows/check-links.yml, app/_includes/md/deb.md, src/gateway/install-and-run/debian.md
This is the docs analogue to https://github.com/Kong/kong/pull/8807
Changes to the platforms being tagetted by our build/test/release infrastructure are considered a breaking change, so deprecating Debian 8 "Jessie" has been slated for Kong Gateway 3.0-- *thus this PR targets the `release/gateway-3.0` branch*.
See also:
- https://konghq.atlassian.net/browse/ENGEN-450
- https://github.com/Kong/kong/pull/8807
- https://github.com/Kong/kong-distributions/pull/766
- https://github.com/Kong/kong-build-tools/pull/448
> July 9th, 2020
> The Debian Long Term Support (LTS) Team hereby announces that Debian 8 jessie support has reached its end-of-life on June 30, 2020, five years after its initial release on April 26, 2015.
~https://www.debian.org/News/2020/20200709
=> [ENGEN-450] Chore(debian 8): add deprecations of Debian 8 "Jessie"

app/_data/kong_versions.yml
Update the version that appears in install docs.
https://github.com/Kong/deck/releases/tag/v1.12.1
Check version in installation doc: https://deploy-preview-3936--kongdocs.netlify.app/deck/latest/installation/
=> Update decK version to 1.12.1

app/_assets/javascripts/app.js, app/_assets/stylesheets/badges.less, app/_assets/stylesheets/base.less, app/_includes/header.html, app/_layouts/docs-v2.html, app/contributing/markdown-rules.md
* Setting `target=_blank` on badges to open links in a new page.
* Fixing header margin issue
* Adding badge to style guide
* Minor consistency edit for keeping style definitions in our `.less` files and not in having it directly in an HTML tag
* Badge link targeting issue was reported by Rick.
* Have been running into a weird margin issue on headers, turned out it was due to a hacky workaround to have clickable anchor links. The workaround is no longer necessary, since the issue has long been fixed, and all we had left was this weird margin.
https://deploy-preview-3949--kongdocs.netlify.app/hub/kong-inc/mocking/ - click on badges, links should open in new tab/window.
https://deploy-preview-3949--kongdocs.netlify.app/contributing/markdown-rules/#badges style guide entry
=> Open badge links in new tab/page

app/gateway/2.8.x/get-started/comprehensive/expose-services.md, app/gateway/2.8.x/get-started/quickstart/configuring-a-service.md
Improves the getting started comprehensive guide, expose services page
- Fixes some of the URLs, in particular the httpie ones were not consistent with curl
- Added a blurb about Data Plane
- Removed the `:` character from the port number reference
Change based on my review during onboarding of this page. The Admin API reference at the end of the page was inaccurate. 
Built the site locally and reviewed the content
=> Improves the getting started comprehensive guide, expose services page

app/_assets/stylesheets/header.less
Fixing margins on plugin docs.
When promo banner is active, the margins on the plugin docs are huge and they shrink when the promo banner is closed (blue banner at top of page).
They shrink back down to normal size when banner is closed:
Check the plugin docs, then close the promo banner and check that the margins remain the same size.
=> Fix margins when promo banner is active

app/_data/docs_nav_konnect.yml, app/konnect/account-management/billing.md, app/konnect/account-management/change-plan.md, app/konnect/account-management/index.md, app/konnect/configure/runtime-manager/runtime-groups/declarative-config.md, app/konnect/configure/runtime-manager/runtime-groups/manage.md, app/konnect/configure/runtime-manager/runtime-instances/gateway-runtime-conf.md, app/konnect/configure/runtime-manager/runtime-instances/gateway-runtime-docker.md, app/konnect/configure/runtime-manager/runtime-instances/gateway-runtime-kubernetes.md, app/konnect/configure/servicehub/manage-services.md, app/konnect/deployment/import.md, app/konnect/dev-portal/access-and-approval/auto-approve-devs-apps.md, app/konnect/dev-portal/applications/enable-app-reg.md, app/konnect/dev-portal/customization/index.md, app/konnect/org-management/auth.md, app/konnect/org-management/okta-idp.md, app/konnect/org-management/teams-and-roles.md, app/konnect/org-management/teams-and-roles/index.md, app/konnect/org-management/teams-and-roles/manage.md, app/konnect/org-management/teams-and-roles/roles-reference.md, app/konnect/org-management/teams-and-roles/teams-reference.md, app/konnect/org-management/users.md, app/konnect/vitals/analyze.md, app/konnect/vitals/generate-reports.md
* Remove prereqs with "required role" that we had in most tasks. 
* Split multi-purpose teams and roles doc into how-to and explanation
* Add `content_type` tag to edited topics (and a few in the roles/access section)
To do: comment out sharing feature temporarily, as it's not available yet.
Follow up task (not for this PR): create a troubleshooting entry that talks about access/roles.
Roles and permissions within Konnect and Kong Gateway: We are not going to prescribe a specific role and permission because there are multitudes of different roles that could work for any given task. At the moment, we were nearly always saying that "You must have organization admin permissions", which helps no one.
TBA
=> [DOCU-2225] Teams and roles cleanup

.gitignore
Set github to ignore the `.netlify` directory, which gets generated when you run smoke tests locally. 
Was running smoke tests locally and noticed that github was seeing this dir. Don't want someone to accidentally commit it at some point.
Pull down the branch locally, break something (eg, delete a top level nav section from Gateway) and run `make smoke`. This will generate a local `.netlify` directory.
Use `git status` to check that the directory isn't seen by github.
=> Ignore netlify test directory

app/_layouts/docs-v2.html
Fixing the "edit this page" link to github from "latest" pages.
"Latest" is an alias, so there is no "latest" directory in the source. The gh page edit links were trying to go to latest.
Eg, click "edit this page" here and notice that it take you to "latest": https://docs.konghq.com/gateway/latest/install-and-run/
Check the "edit this page" link in the top right corner for any /latest/ URL. It should take you to the correct version. Eg:
https://deploy-preview-3956--kongdocs.netlify.app/gateway/latest/install-and-run/
https://deploy-preview-3956--kongdocs.netlify.app/mesh/latest/gettingstarted/
=> Fix "edit this page" links

app/enterprise/2.1.x/admin-api/index.md, app/enterprise/2.2.x/admin-api/index.md, app/enterprise/2.3.x/admin-api/index.md, app/enterprise/2.4.x/admin-api/index.md, app/enterprise/2.5.x/admin-api/index.md
Backport the description for the `service` parameter of the route object.
https://konghq.atlassian.net/browse/DOCU-846
The request was originally made to update 1.4.x; since then, all gateway-oss and gateway pages have been updated. The old enterprise docs, however, did not pick up the change.
Not updating 1.4.x as we're deprecating any doc before 2.0 soon.
https://deploy-preview-3959--kongdocs.netlify.app/enterprise/2.5.x/admin-api/#request-body-3
=> [DOCU-846] Add service name as an option to route config.service description

app/gateway/2.8.x/reference/configuration.md
Generated update for the configuration reference to add Dev Portal property descriptions.
For reviewers: please just check that it displays in the preview. Don't make text edits here, as the source of this content is in the kong/kong-ee repo.
Follow-up PR to: https://github.com/Kong/docs.konghq.com/pull/3751
https://deploy-preview-3951--kongdocs.netlify.app/gateway/latest/reference/configuration/
=> Generate 2.8.x conf for dev portal updates

app/_hub/kong-inc/forward-proxy/_index.md
Expand descriptions for the the forward proxy plugin to include fallback behavior info.
https://konghq.atlassian.net/browse/DOCU-2352
https://github.com/Kong/kong-ee/pull/3211/  
https://deploy-preview-3971--kongdocs.netlify.app/hub/kong-inc/forward-proxy/
=> [DOCU-2352] Document forward proxy fallback behavior

app/_hub/kong-inc/mtls-auth/_index.md
Document new proxy parameters for the mTLS auth plugin. 
https://github.com/Kong/kong-ee/pull/3078
https://konghq.atlassian.net/browse/DOCU-2353
https://deploy-preview-3972--kongdocs.netlify.app/hub/kong-inc/mtls-auth/
Reviewers: I drafted this doc but don't really understand how CRLs or OCSP servers work, so please validate my phrasing.
=> [DOCU-2353] mTLS auth plugin: proxy host and port parameters

app/_data/docs_nav_gateway_2.8.x.yml, tests/sidebar.test.js
* Moving the Dev Portal section to the top level of the Kong Gateway navigation so that it's easier to find.
* Ensuring that the top level of each section is consistent - each one is a "drawer" only, and not a clickable link.
Had many reports of users struggling to find this section. The location of it is admittedly confusing.
Reviewers: I'm not 100% set on the title "Overview of Kong Gateway", but I didn't want it to be called just "Overview" in the section "Introduction". Any other ideas are welcome.
https://deploy-preview-3955--kongdocs.netlify.app/gateway/
=> Gateway nav improvements

app/_includes/md/deb.md, src/gateway/install-and-run/ubuntu.md
Companion PR to:
- https://github.com/Kong/kong-build-tools-base-images/pull/40
- https://github.com/Kong/kong-build-tools/pull/476
- https://github.com/Kong/kong-build-tools-base-images/pull/40
Ubuntu 16.04 aka "Xenial Xerus" reached "End of Standard Support" in April of 2021.
=> [ENGEN-451] chore(xenial) 👋

pdf-generation/create-pdf.js, pdf-generation/list-plugins.js
PDF generation is broken in two ways:
1. The switch from `index` to `_index` for plugins prevented PDF generation for the default version of plugins
2. The addition of the OpenAPI renderer prevented that page from being printed to PDF
Some `prettier` printing also made it in to the PR, but I don't think it's a bad thing
Fixing the existing tooling
Run this locally:
```
cd pdf-generation
npm ci
KONG_PLUGIN_NAME=basic-auth node run.js
KONG_DOC_VERSIONS=gateway_2.8.x node run.js
```
=> Fix PDF Generation for plugins + docs

app/_plugins/generators/latest_version_generator.rb, app/_plugins/generators/single_source_generator.rb, app/_plugins/generators/versions.rb
Mark files as generated in the conflicted files output when using single sourcing generation
It was hard to work out why duplicates were happening previously
Create a file in `app/demo/one`, then create an entry in a nav file with the `url: /demo/one` and look at the error message
=> Add generated path to conflict warning for single sourced documents

app/_hub/kong-inc/key-auth/_index.md
Add more explanation for the valid value range of key's `ttl` in the key-auth plugin. According to the [dao layer check function](https://github.com/Kong/kong/blob/9dfffb5d8316c5277afeb81cd46b42d47a6ac705/kong/db/dao/init.lua#L193-L199), the `ttl` type option should be within the range between 0 and 100000000.
And as for the key-auth plugin, `ttl` set to zero has the same effect as `ttl` is missing
Related bugfix: https://github.com/Kong/kong/pull/8831
=> [FTI-4021]add explanation for valid value range of key's ttl in key-auth plugin

algolia/config-full-docs.json
Set algolia config to index `/latest/` instead of incrementing versions with every release
We now have evergreen URLs at `latest` for any versioned doc. Setting the index to pull from `latest` creates a more consistent experience and leaves us one less task to do at release time. 
Tested by running the index locally. It completed successfully.
=> Update algolia config

app/gateway/2.8.x/reference/configuration.md, autodoc-conf-ee/data.lua
Fixes an issue with links in `reference/configuration` rendering like this. 
[netlify](https://deploy-preview-3982--kongdocs.netlify.app/gateway/latest/reference/configuration/#injecting-individual-nginx-directives)
check links, read copy.
=> [Fix] data.lua link syntax

app/gateway/2.8.x/reference/clustering.md
Mentioning AWS Aurora by name implied official support. Instead, we want to highlight that read-replicas are useful for scaling Kong.
Raised by CRE
Check `/gateway/2.8.x/reference/clustering/#use-read-only-replicas-when-deploying-kong-clusters-with-postgres` in the review app
=> Remove mention of AWS Aurora

app/_assets/stylesheets/navtabs.less, app/_assets/stylesheets/variables.less, app/_includes/hub-examples.html, app/_layouts/extension.html
An attempt at combining the plugin config examples into something that's hopefully easier to navigate/understand.
You can set the `parent` class on a group of `navtabs` to surround it with a border. This makes it clearer that the tabs contain tabs.
Previously:
Reworked:
https://user-images.githubusercontent.com/54370747/171506991-09cd8f27-2fcb-4394-80a8-0038d7b2cd1a.mov
Most recently, the issue was raised by Rick. However, this issue has been called out many times in the past: we have too many similar examples and they cover a huge portion of the plugin page while being mostly the same. 
Feedback from Rick: to a new user, it looks like each section has to be done in order (enable on a service, then on a route, etc). It's not immediately clear that a) these instructions are independent …
=> Combine plugin examples into tabs for better UX

app/_data/kong_versions.yml
Bumping the decK patch version.
https://github.com/Kong/deck/releases/tag/v1.12.2
Check the decK install guide.
=> (chore) Bump decK version

.gitignore, docs/development/ruby-debug.md
Add instructions how to start a debug session for Jekyll with vscode
It took a little while to work out, and we'll need it on multiple machines
Follow the instructions locally
=> Add Ruby Debug instructions

app/gateway/2.8.x/reference/configuration.md, app/gateway/changelog.md
Documenting parameters for dev portal application emails. From here: https://github.com/Kong/kong-ee/blob/2.8.1.1/kong.conf.default#L2203-L2254
Feature went into 2.8.1.1 but wasn't documented then.
https://konghq.atlassian.net/browse/DOCU-2360
https://deploy-preview-3995--kongdocs.netlify.app/gateway/changelog
https://deploy-preview-3995--kongdocs.netlify.app/gateway/latest/reference/configuration/#portal_application_status_email
=> [DOCU-2360] Portal application/service emails

app/gateway/2.8.x/developer-portal/theme-customization/emails.md, app/gateway/2.8.x/reference/configuration.md, app/gateway/changelog.md
Following up on https://github.com/Kong/docs.konghq.com/pull/3995 with a couple more additions that we snuck into 2.8.1.1.
https://konghq.atlassian.net/browse/DOCU-2360
https://deploy-preview-3999--kongdocs.netlify.app/gateway/changelog
https://deploy-preview-3999--kongdocs.netlify.app/gateway/latest/reference/configuration/#portal_smtp_admin_emails
https://deploy-preview-3999--kongdocs.netlify.app/gateway/latest/developer-portal/theme-customization/emails/
=> [DOCU-2360] Portal email recipients and developer metadata

app/_hub/kong-inc/key-auth-enc/_index.md
The endpoint to retrieve `key-auth-enc` plugin credentials is not right.
Change `key-auth-enc` to `key-auths-enc`.
Mislead end users.
=> fix(docs) update key-auths-enc endpoint

app/_hub/kong-inc/request-transformer-advanced/_index.md, app/_hub/kong-inc/request-transformer/_index.md
The previous examples for the request transformer plugins were:
* syntactically invalid
* confusing in that they guided the user to setup a regex capture but then it was not used later
The previous code was inaccurate and confusing for the user
Tested the changed code against Kong GW 2.8.1
=> Fixes examples on request transformer plugins

app/_hub/moesif/kong-plugin-moesif/_index.md
Update to include required changes needing to be made to kong.conf prior to enabling the plugin.
Plugin will fail to enable if changes are not made to kong.conf prior to issuing curl command.
When attempting to enable the plugin without first editing the kong.conf file with the necessary changes, the following error will arise: 
```json
{"name":"schema violation","message":"schema violation (name: plugin 'moesif' not enabled; add it to the 'plugins' configuration property)","fields":{"name":"plugin 'moesif' not enabled; add it to the 'plugins' configuration property"},"code":2
}
```
=> Update _index.md to include kong.conf changes to enable Moesif plugin

app/konnect/vitals/generate-reports.md
With https://konghq.atlassian.net/browse/MA-565, we made the time preview more human readable.
=> Updated time preview

app/_plugins/generators/latest_version_generator.rb
The edit link was broken on `/latest/` pages. Resolves #4009
The edit link on /kubernetes-ingress-controller/latest/references/custom-resources/ is broken in prod, but works on the preview
=> Fix edit link on /latest/ pages

app/konnect/vitals/generate-reports.md
Since we now need to consider entities for Runtime Manager (e.g. Gateway Services or Consumer) and Service Hub/Developer Portal (e.g. Services and Applications), it is important to let the reader know what entities/data we include into the generated report based on the chosen report type.
- Services only includes Service packages that are catalogued/registered inside Service Hub. It does not include Gateway Services.
- Routes include anything across Runtime Manager and Service Hub but of course, it does only unique entities (e.g. same route can exist in Runtime Manager and attached to a Service Version in Service Hub.
- Applications only includes applications created in the Konnect Dev Portal, not the Consumer manually created inside Runtime Manager.
Mainly because we have similar …
=> Clarify what each report type entitles

.github/styles/kong/Terms.yml, .github/styles/kong/dictionary.txt, app/_data/docs_nav_mesh_1.6.x.yml, app/_data/docs_nav_mesh_1.8.x.yml, src/mesh/features/acmpca.md, src/mesh/features/cert-manager.md, src/mesh/features/vault.md, src/mesh/gettingstarted.md, src/mesh/index.md, vale.ini
Signed-off-by: Paul Parkanzky <paul.parkanzky@konghq.com>
Add documentation for cert-manager in Kong Mesh.
cert-manager added to 1.8 mesh release.
Netlify preview
=> docs(kong-mesh) add cert-manager documentation

app/_hub/kong-inc/degraphql/_index.md, app/_hub/kong-inc/degraphql/versions.yml
* Add new `graphql_server_path` parameter
* Set up version file so that we can single-source this plugin going forward
* Some grammar, formatting, and style cleanup
https://konghq.atlassian.net/browse/DOCU-2349
https://deploy-preview-3960--kongdocs.netlify.app/hub/kong-inc/degraphql/
=> [DOCU-2349] GraphQL server path

app/_includes/breadcrumbs.html, tests/breadcrumbs.test.js
Replace 'kong konnect platform' and 'open source' in breadcrumbs with 'home'.
I also did some exploration to get each breadcrumb linking to the parent page, and I ran into an issue: not every directory item has a page associated with it. For example, you might have the following path:
https://docs.konghq.com/kubernetes-ingress-controller/latest/concepts/design/
The breadcrumbs would be:
Home > Kubernetes Ingress Controller > Concepts
* The final page doesn't appear in the breadcrumbs because you're already on it - this is expected.
* The "concepts" breadcrumb is the problem here: this page doesn't exist. So instead of trying to determine whether a page exists and have random unlinked pages, for now I chose to link only the first two breadcrumbs: "Home" and product name. 
* This is a …
=> Remove old titles from breadcrumbs

app/gateway/2.8.x/index.md
Add a note for the Kong Manager perf issue in traditional mode.
We are telling the clients that using Kong Manager in traditional mode may have an impact on the overall performance of the Kong.
INTF-2900
=> docs(km) note Kong Manager perf issue in traditional mode

app/_data/docs_nav_gateway_3.0.x.yml, app/_data/tables/os_support.yml, app/_redirects, app/gateway/changelog.md, src/gateway/install-and-run/amazon-linux.md, src/gateway/install-and-run/centos.md, src/gateway/install-and-run/debian.md, src/gateway/install-and-run/docker.md, src/gateway/install-and-run/index.md, src/gateway/install-and-run/macos.md, src/gateway/install-and-run/os-support.md, src/gateway/install-and-run/rhel.md, src/gateway/install-and-run/ubuntu.md, src/gateway/plan-and-deploy/kong-user.md, tests/sidebar.test.js
Creating a central location to track supported OSes and deprecations. We’re getting more and more of them over time, and we need a way to keep track of when to remove, deprecate, and have an easily reusable templated blurb. 
Removed the warnings from installation pages. It overwhelms the installation pages in a bad way, making the whole page look deprecated. From looking around at other places, docs don't usually mention a supported OS version right on an installation page, so they also don't have to add these notices there.
Breakdown:
* One central doc with tables of supported and deprecated OSes, along with the versions they were introduced or were deprecated in, and links to EoL statements.
* I went with a markdown file with table + separate data file, with the idea that the data file …
=> [DOCU-2329] Linux OS support and deprecation

src/kubernetes-ingress-controller/guides/using-gateway-api.md, src/kubernetes-ingress-controller/references/cli-arguments.md, src/kubernetes-ingress-controller/references/version-compatibility.md
Adds section for KIC 2.4 and updates shared metadata.
https://github.com/Kong/kubernetes-ingress-controller/releases/tag/v2.4.0
Omits most Gateway updates for now. Added https://github.com/Kong/docs.konghq.com/issues/4026 for a Kubernetes Team member to add more detail separately from the initial update.
I have left the compatibility table in its existing format after adding 2.4, with the single source version only including a subset of versions. The listed versions now extend through 2.0, and as only 2.3+ use the single source page, this should be fine until it can converted into a format that works better with single source. I've requested this from the Docs team in https://github.com/Kong/docs.konghq.com/issues/4028
Reviewed:
https://deploy-preview-4029--kongdocs.netlify.app/kubernetes- …
=> Add 2.4 release changes.

app/_hub/tomkerkhove/microsoft_azure_container_instances/_index.md
Fix the forward slashes to backward slashes for Linux commands
The command has forward slashes, which fails while running in Linux and needs to be backward slashes for new lines.
N/A
=> Fix slashes in deploying to Azure command

app/_hub/kong-inc/oauth2/_index.md
The documentation for the [Kong OAuth2 plugin](https://github.com/Kong/kong/tree/master/kong/plugins/oauth2) states that a refresh token will be generated automatically when manually creating (aka migrating) token. This is incorrect; the [DAO attribute](https://github.com/Kong/kong/blob/a02542d6dfb96073c4ef6ab5f86b350b756ae2fa/kong/plugins/oauth2/daos.lua#L103) does not define ` auto = true` and so a refresh token will not be generated automatically.
Existing documentation is currently incorrect/out-of-sync from reality.
Attempt to creating a OAuth2 token by following the existing documentation but excluding the `refresh_token` parameter. E.g.:
```
$ curl -X POST http://localhost:8001/oauth2_tokens --data 'credential.id=962db0d1-f06e-4085-8dee-5538f213ca69' --data "token_type=bearer" …
```
=> fix: description of generation of refresh token in OAuth2 plugin documentation

.github/styles/kong/dictionary.txt, app/gateway/2.6.x/reference/configuration.md, app/gateway/2.7.x/reference/configuration.md, app/gateway/2.8.x/reference/configuration.md, autodoc-conf-ee/data.lua
Adding content that was overwritten in autogenerating the 2.6.x configuration reference doc.
Updating the source file so that this won't come up again.
Issue reported on Slack; bringing in content from https://github.com/Kong/docs.konghq.com/pull/3265. 
TBA
=> Add missing info for nginx templates

app/_hub/kong-inc/oauth2-introspection/_index.md
Improving the description for `introspection_url`. Based on dev's suggestion in the linked ticket and verified against FTI ticket. 
Also doing some minor grammar and formatting cleanup while I'm in here.
https://konghq.atlassian.net/browse/DOCU-2172
https://deploy-preview-4040--kongdocs.netlify.app/hub/kong-inc/oauth2-introspection/
=> [DOCU-2172] Clarify https URL requirement for Oauth2 Introspection plugin

app/_includes/md/gateway-ports.md, app/konnect/network.md
* Updating the list of Konnect hostnames a user might need to add to their firewall's allowlist. 
* Renamed the section from "Hostnames to add to allow lists" to simply "Hostnames" to parallel the rest of the page. The whole point of this entire doc is to provide lists of ports and hosts to add to allowlists, it's not specific to this section.
* Simplified the Kong Gateway ports table to just the proxy ports. Unless I'm missing something, none of the other ports are actually in use in Konnect or on data planes - they're all self-hosted control plane ports.
https://konghq.atlassian.net/browse/DOCU-2371
https://deploy-preview-4039--kongdocs.netlify.app/konnect/network/
=> [DOCU-2371] Konnect hostnames and ports

app/_data/docs_nav_konnect.yml, app/konnect/org-management/okta-idp.md, app/konnect/org-management/troubleshoot.md
* Clarify exactly which issuer URL to use for Okta SSO configuration. 
* Create a troubleshooting topic for account/org issues - we have two pieces of Okta config advice that are buried in the config topic itself. Pulling them into a troubleshooting topic for _hopefully_ easier findability.
https://konghq.atlassian.net/browse/DOCU-2341
https://deploy-preview-4023--kongdocs.netlify.app/konnect/org-management/okta-idp/#set-up-konnect
https://deploy-preview-4023--kongdocs.netlify.app/konnect/org-management/troubleshoot/
=> [DOCU-2341] Improve Okta issuer URL instructions

app/konnect/runtime-manager/runtime-groups/index.md
Enterprise customers will have 10 runtime groups by default (they can purchase more if they want).
Updating per latest pricing and packaging decisions
=> Update Enterprise RG count to 10 total by default

app/_hub/kong-inc/key-auth-enc/_index.md
Removing a setting that isn't available in the plugin.
Parameter doesn't exist.
Reported on Slack, see: https://kongstrong.slack.com/archives/C0DSXDXV1/p1655994419162749
https://docs.konghq.com/hub/kong-inc/key-auth-enc/
=> key-auth-enc plugin: Remove non-existent ttl parameter

app/_assets/javascripts/promo-banner.js, app/_includes/nav-v2.html
Updating to Kong Summit 2022 to mimic the banner on the konghq.com site. 
Gateway 2.8 has been in the banner for a while, and Summit is coming up.
Check that the banner appears for you in the preview: https://deploy-preview-4052--kongdocs.netlify.app/
Check that the link works, and that when you close the banner, the `closebanner-summit-2022` cookie is set and the banner stops appearing sitewide. You can check with Chrome DevTools:
=> Update promo banner for Kong Summit 2022

app/_data/docs_nav_deck_1.12.x.yml, src/deck/faqs.md, src/deck/guides/konnect.md
Adding a guide for using decK with Konnect with examples into the decK docs.
The only thing I couldn't figure out was the purpose of the `--konnect-addr` flag in the current environment. Users only have one API they can target, right? Or can they somehow target `konnect.konghq.com` still? I couldn't get it to do anything different - @GGabriele, is there something I'm missing, or is this flag not helpful to customers at the moment (only useful internally)?
Note that this is going into live docs, not into the `konnect` branch, because this version of decK is already out - even though Konnect is in beta.
https://konghq.atlassian.net/browse/DOCU-2308
Tested all the things with decK 1.12 and cloud.konghq.com; that's also how I figured out precedence for auth methods. If that's not the desired …
=> [DOCU-2308] DecK Konnect guide

src/gateway/developer-portal/working-with-templates.md
Changed `layout` type from boolean to string.
Changed `layout` type from boolean to string. Decided to only change the 3.0.x version.
[DOCU-1428](https://konghq.atlassian.net/browse/DOCU-1428)
=> Fix `layout` type in Working with Templates

src/gateway/admin-api/db-encryption.md, src/gateway/plan-and-deploy/security/db-encryption.md
Add recovery key API for Gateway EE 3.0.
FT-3020
=> docs(keyring) add recovery key for 3.0

.github/styles/kong/Terms.yml, vale.ini
Adding rules to ignore all content in curly brackets:
Previous rules weren't ignoring the following:
* `{:.class-name}`
* `{#header-short-name}`
Check locally.
=> Vale: Adjust rules for curly brackets

app/gateway/2.6.x/reference/cli.md, app/gateway/2.7.x/reference/cli.md, app/gateway/2.8.x/reference/cli.md
Updated `reset` command
Updated migrations `reset` command in auto docs that were already generated. The Gateway CLI work was completed in https://github.com/Kong/kong/pull/9010. 
This change was requested in [DOCU-1474](https://konghq.atlassian.net/browse/DOCU-1474) because it was unclear to customers that the reset command would erase data instead of reset the migration steps.
In the Netlify preview Kong Gateway docs, go to **Reference > CLI Reference > kong migrations** to make sure the `reset` command description is updated in versions 2.6.x-2.8.x.
=> Updated migrations `reset` command in auto docs

.github/styles/kong/dictionary.txt, app/_hub/kong-inc/acme/0.2.11.md, app/_hub/kong-inc/acme/0.2.13.md, app/_hub/kong-inc/acme/0.2.14.md, app/_hub/kong-inc/acme/0.3.x.md, app/_hub/kong-inc/acme/_index.md
Add missing Admin API section and explain `domains` behaviour
We use autodoc to generate core admin endpoints, but seems not for endpoints exposed from plugins (?)
Please let me know if it's favored, or should i move them to autodoc instead.
=> doc(acme) add missing Admin API section and explain `domains` behaviour

.github/styles/kong/dictionary.txt, app/gateway/2.8.x/install-and-run/kubernetes.md
Moves the NOTE warning up to the proper section related to the instruction
Adds code formatting to guidance as well
When following this guide the first time, I got tripped up by what the "NOTE" in this
docs page is telling me. But I didn't notice it because it was located at the bottom of the
doc and not in proximity to the instruction I was runnig.
Built docs locally and verified local version of the page
=> Tweaks KIC install

app/gateway/2.8.x/index.md, src/kubernetes-ingress-controller/guides/using-kongplugin-resource.md
Removes command output from the example commands. 
This also relates to DOCU-2369 which requests the removal of shell prompt characters
from example commands.
If the command output and shell prompt are in the example commands, the user cannot copy and paste the command to a shell and immediately execute. This add some burden to the reader.
Built docs locally and evaluated the page manually
=> DOCU-2377: Cleanup KIC using kongplugin resource guide

app/_includes/md/rpm.md
As part of the work to add ubi-minimal/slim images, I changed this: https://github.com/Kong/docker-kong/blob/8a361ad78d4f84b67e893588fd3a6108bea67fe7/rhel/Dockerfile#L43-L45
So here are the adjoining docs.
Sibling PR to: https://github.com/Kong/docker-kong/pull/576
=> [FT-2378] [ENGEN-452] Add notes for ubi-minimal usage

app/_data/docs_nav_konnect.yml, app/konnect/vitals/analyze.md, app/konnect/vitals/index.md
Changes the upper bound to 30 days, and adds the time interval chart. 
https://konghq.atlassian.net/browse/DOCU-2227
[link](https://deploy-preview-4018--kongdocs.netlify.app/konnect/vitals/)
=> [DOCU-2227]Vitals page Updates

src/kubernetes-ingress-controller/guides/getting-started.md
Additionally:
* attempts to standardize some of the layout of command -> expected results to
match what was started in https://github.com/Kong/docs.konghq.com/pull/4064
* Adds a CTA at the bottom of the guide
* updates command expected output to more modern responses
Removes the command prompts from the instruction commands, allows a user to more easily copy and paste the instructions
Locally built and viewed the changed page
=> DOCU-2369: Removes prompts from instruction commands

app/mesh/1.6.x/features/rbac.md, src/mesh/features/rbac.md
Fix RBAC example, it should contain `system:serviceaccounts:kube-system` described also in this page in `Defaults`.
=> fix(mesh): add missing group in rbac example

src/mesh/features/cert-manager.md
Fix broken link in https://docs.konghq.com/mesh/latest/features/cert-manager/
The redirection is not working properly
Signed-off-by: Matthieu MOREL <mmorel-35@users.noreply.github.com>
=> Fix broken link in https://docs.konghq.com/mesh/latest/features/cert-manager/

app/_data/kong_versions.yml
Bump decK version for latest release: https://github.com/Kong/deck/releases/tag/v1.12.3
https://github.com/Kong/deck/releases/tag/v1.12.3 is out.
https://deploy-preview-4092--kongdocs.netlify.app/deck/latest/installation/
=> chore: Bump decK version to 1.12.3

app/konnect/runtime-manager/runtime-groups/index.md
Once again, changing the number of available runtime groups in an Enterprise subscription. This time, we're removing any concrete numbers and instead directing anyone that's interested to the pricing page so they can contact sales, if interested.
The limit is going to depend on the customer and whatever plan they negotiate with sales.
https://deploy-preview-4090--kongdocs.netlify.app/konnect/runtime-manager/runtime-groups/
=> Konnect: Remove language on the number of runtime groups

app/_hub/kong-inc/acl/_index.md
The Admin API call to associate a customer with the ACL plugin is incorrect. Misleading users.
Wrong Admin API usage.
=> docs(acl) fix an Admin API usage error

app/_hub/kong-inc/forward-proxy/_index.md
Add a description about usage of the forward-proxy
The forward-proxy can not be used with upstream, refer to https://konghq.atlassian.net/browse/FTI-4122
=> FTI-4122 note forward-proxy with upstream

app/_includes/md/rpm.md, app/gateway/2.8.x/install-and-run/rhel.md
Original PR added changes to a doc that's not in use anymore: https://github.com/Kong/docs.konghq.com/pull/4024
Moving it into the latest documentation.
@curiositycasualty I had to split the commands out and add some placeholder values that'll pick up the correct latest version of the gateway. Let me know if it looks right.
Also - are there UBI-minimal packages for `kong-enterprise-edition`? I'm working off of the assumption that there are, but I'm not entirely sure if that's correct.
Doc is in the wrong place.
Tested locally. Netlify preview: https://deploy-preview-4081--kongdocs.netlify.app/gateway/latest/install-and-run/rhel/
Will need some help checking accuracy. In the preview, you can switch to the open-source version by clicking the toggle in the top right:
Output looks like this:
=> Add UBI install instructions to the correct doc

src/gateway/admin-api/db-encryption.md, src/gateway/plan-and-deploy/security/db-encryption.md
Reorder the structure to make it more readable. Disaster recovery are moved a seperate section and unnessary detail on that is removed in first section.
Also mention the new options user can look for Hybrid data plane.
Might need some hyperlinks to link `declarative_config_encryption_mode` and secrets management.
=> doc(keyring) reorder the structure, mention new options for Data Plane

.github/styles/kong/dictionary.txt, app/_hub/kong-inc/request-validator/_index.md
New version has Draft 4 compatible values in both parameters and adds sending the body value
The example at the bottom contained a Draft 4 example for the parameter validation. The also included (but not used) body validator was in Kong schema format and had no effect at all (Kong accepts it, but it has consequences at all).
Customer trying body validation to work by copy&pasting previous example failed
Follow the instructions :)
=> Fixed mixture of Kong schema and Draft 4

app/_assets/stylesheets/badges.less, app/_layouts/docs-v2.html
Remove badges from beta/alpha banners and setting badge link opacity to 1. With anything under 1, the tooltip becomes hard to read when there's a link involved and it overlaps with text.
Ran into badge opacity issues in some Konnect docs. When a badge from a header overlaps with a banner, it doesn't go well. Was going to figure out a way to fix it, but it's honestly easier to read the banners when they don't have those badges.
If anything, we can adjust the banners for better beta/alpha design in the future.
Beta banner: https://deploy-preview-4108--kongdocs.netlify.app/gateway/latest/plan-and-deploy/security/secrets-management/ 
Alpha/tech preview banner: https://deploy-preview-4108--kongdocs.netlify.app/kubernetes-ingress-controller/latest/guides/using-gateway-api/ 
Badge opacity, hover …
=> Badge adjustments

app/_hub/tomkerkhove/microsoft_azure_container_instances/_index.md
Add Kong PG SSL for Azure postgres database
Mention port for Kong URL and Admin URL
Azure Postgres databases [enforces SSL connection by default](https://docs.microsoft.com/en-us/azure/postgresql/single-server/concepts-ssl-connection-security) and hence it is necessary to add SSL connection for Kong's postgres database.
Also, mentioned the ports for the Kong Gateway and the URL for the Admin API since it is necessary to be clear and Azure Container Instances does not support different port mapping yet i.e., mapping 8080 to 80. The Gateway would run in `<dns-label>.westeurope.azurecontainer.io:8000` and not `<dns-label>.westeurope.azurecontainer.io`
N/A
=> Add Kong PG SSL for Azure postgres database

app/_includes/md/gateway/setup.md, app/gateway/2.6.x/plan-and-deploy/security/start-kong-securely.md, app/gateway/2.7.x/plan-and-deploy/security/start-kong-securely.md, app/gateway/2.8.x/plan-and-deploy/security/start-kong-securely.md
Updated files with instructions for making the `KONG_PASSWORD`. I'm pretty sure "start-kong-securely.md" isn't single sourced, so I updated all the supported files. 
[DOCU-268](https://konghq.atlassian.net/browse/DOCU-268)
Verify that the new "Important" note displays on affected pages (CentOS, Debian, RHEL, Ubuntu, Docker, Amazon Linux) for versions 2.6.x-2.8.x. I had issues with caching that prevented them from displaying on all pages originally, so I wanted to confirm that that won't always be the case.
=> [DOCU-268] Note about setting the KONG_PASSWORD

app/_plugins/generators/canonical_url_generator.rb, app/moved_urls.yml, docs/seo.md, tests/seo.test.js
Add the ability to track canonical URLs when the URL of a page changes
When we update the IA for 3.0 URLs will change. We don't want duplicate content penalties
Visit /gateway-oss/2.5.x/configuration/ and view source
The canonical tag should point to `/gateway/latest/reference/configuration/` which is the new URL for that page
=> Add support for moving URLs and setting canonical URL correctly

app/konnect/servicehub/index.md
fixes an instance of a word that appears twice, and a missing period.
=> [fix] Small copy edits

app/_plugins/generators/single_source_generator.rb, docs/single-sourced-versions.md
Add support for unlisted single-sourced docs
We need it for some of the how-to guides until we decide how to expose them publicly.
Tested locally with the following config:
```diff
--- a/app/_data/docs_nav_gateway_3.0.x.yml
+++ b/app/_data/docs_nav_gateway_3.0.x.yml
@@ -505,3 +505,5 @@ items:
- text: Plugins in Other Languages
url: /reference/external-plugins
+unlisted:
+  - url: /how-to/example
```
And `example.md`:
```markdown
---
title: Example
---
This is a test
```
=> Add support for unlisted single-sourced docs

app/konnect/dev-portal/customization/index.md
Due to current limitations, we need to re-add the list of supported TLDs to the Customize Dev Portal page. I'm commenting out the `Domain name restrictions` section instead of removing it - we hope to extend the support to all (allowed) TLDs soon.
TDX-2218
https://deploy-preview-4119--kongdocs.netlify.app/
=> feat(portal): update list of supported TLDs for Dev Portal Custom URLs [TDX-2218]

app/gateway/2.8.x/get-started/quickstart/index.md
Changes the Kong quickstart guide to use the `PG_HOST` value to configure the database connection instead of the deprecated C* value.
C* is deprecated, PG values should be used
Tested the code in a local docker environment
=> Kong GW quickstart remove C* config and use PG_HOST

app/_data/kong_versions.yml, app/gateway/changelog.md
Changelog and version bump for Gateway 2.8.1.2.
I combined Dev Portal and Kong Manager into one section since there were a couple of fixes that covered Kong Manager issues but for Dev Portal pages.
Patch release.
Based on https://konghq.atlassian.net/wiki/spaces/FTT/pages/2825289743/Kong+Enterprise+2.8.1.2. 
https://deploy-preview-4070--kongdocs.netlify.app/gateway/changelog/
Check version number in install topics, eg https://deploy-preview-4070--kongdocs.netlify.app/gateway/latest/install-and-run/debian/
=> Release: Gateway 2.8.1.2

app/_data/landing_page.yml, app/_hub/kong-inc/application-registration/_index.md, app/_includes/breadcrumbs.html, app/_includes/hub-examples.html, app/_layouts/landing-page.html, app/contributing/word-choice.md, app/konnect/servicehub/service-implementations.md
* Cleaning up instances of ServiceHub
* Adjusting landing page to get rid of "Konnect Platform" terminology and inaccurate links
* Updating descriptions from marketing materials
* Updating Konnect UI instructions for plugin examples
Consistent branding with Helium and accurate examples.
TBA
=> Clean up branding and descriptions for Konnect

app/_data/docs_nav_kic_2.2.x.yml, app/_data/docs_nav_kic_2.3.x.yml, app/_data/docs_nav_kic_2.4.x.yml, src/kubernetes-ingress-controller/guides/using-kong-with-knative.md
Guide `ingress-class` instead of `ingress.class` for Knative Ingress.
https://github.com/Kong/kubernetes-ingress-controller/issues/2344 introduced to use `ingress-class` instead of `ingress.class` for Knative Ingress, however Kong document hasn't been changed.
I tested it on K8s v1.24 + Knative v1.5.0 with Kong v2.8 + Ingress Controller v2.5 .
If we use `ingress.class` in above versions, it does not work (endpoint address is not assigned to K8s service for ksvc.)
=> Guide `ingress-class` instead of `ingress.class` for Knative

src/kubernetes-ingress-controller/guides/cert-manager.md
1. `ClusterIssuer`'s are not namespaced
2. Removing an unnecessary cert-manager annotation
3. Denoting that the `email` setting in a `ClusterIssuer` is an optional key
Noticed some minor issues when deploying and reading the cert-manager API docs
1. Deploy cert-manager via helm
2. Deploy the ClusterIssuer config in the guide
3. Follow remainder of guide
=> cert-manager kic guide fixes/enhancements

.github/styles/kong/dictionary.txt, app/gateway/2.8.x/plugin-development/custom-entities.md
In the example of migration file, it used `postgresql` key while it should be `postgres` instead.
=> Fix migration code example

app/_includes/hub-examples.html, app/_layouts/extension.html
* Remove default values from generated examples
* Add name option to service, route, and consumer parameters and explain when these options are to be used. For reference, see https://docs.konghq.com/gateway/latest/admin-api/#add-plugin.
* Set `enabled` to not required because the default is true, and you really don't need to set it.
* Applied consistent styling 
* Fixed Kong Manager examples and added a condition to the note for enterprise and plus plugins.
Default values shouldn't be pulled into examples. Since they're defaults, they're already there, so telling people to configure them is confusing and adds unnecessary complexity.
Came from https://github.com/Kong/docs.konghq.com/pull/3708, where the plugin author simply disabled the examples to make up for the unnecessary values in the …
=> Plugin Hub examples and common parameters

.github/styles/kong/dictionary.txt, app/_data/docs_nav_gateway_3.0.x.yml, src/gateway/get-started/comprehensive/dev-portal.md, src/gateway/get-started/comprehensive/expose-services.md, src/gateway/get-started/comprehensive/improve-performance.md, src/gateway/get-started/comprehensive/load-balancing.md, src/gateway/get-started/comprehensive/manage-teams.md, src/gateway/get-started/comprehensive/prepare.md, src/gateway/get-started/comprehensive/protect-services.md, src/gateway/get-started/comprehensive/secure-services.md
remove KM, Deck, and HTTPIE instructions from comprehensive docs. 
This also includes renaming according to the IA sheet. 
This PR does not contain new KM docs or new decK docs. Those will be added in a later PR. 
This PR does not contain major updates to these docs. That will be added in a later PR. 
[[DOCU-2402]](https://konghq.atlassian.net/browse/DOCU-2402)
soon
[DOCU-2402]: https://konghq.atlassian.net/browse/DOCU-2402?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DOCU-2402] Remove KM and decK, and HTTPie instructions from comprehensive docs.

app/_hub/_init/my-extension/_index.md, app/_plugins/generators/plugin_single_source_generator.rb
Adding full steps for creating a new plugin doc (icon, versions.yml) to the template.
The info is hard to track down and scattered (it exists in some internal docs that aren't kept up-to-date). It's simpler to add this info to the template instead, which is what new plugin authors are already looking at. Often, we will have new plugin submissions where the person fully followed the template instructions and didn't bother looking anywhere else, so the icon and versions file are missing.
Need this for doc team as well.
On branch, shouldn't be published to live site.
@mheap I ran into an issue with this template, caused by single-sourcing. The plugin doc generator actually creates a published/live doc for the template as well, under …
=> Further improve the plugin template

app/gateway/2.6.x/reference/configuration.md, app/gateway/2.7.x/reference/configuration.md, app/gateway/2.8.x/reference/configuration.md
Add cluster_telemetry_server_name into 2.6-2.8 docs
This issue was discovered as a result of https://github.com/Kong/docs.konghq.com/pull/4089. I made changes to the kong/kong-ee repo in https://github.com/Kong/kong-ee/pull/3464. 
Is this technically accurate? (is it enterprise and has no defaults?)
=> [DOCU-2401] Add cluster_telemetry_server_name into 2.6-2.8 docs

.github/styles/kong/dictionary.txt, app/_hub/kong-inc/request-transformer-advanced/_index.md, app/_hub/kong-inc/request-transformer/_index.md
This PR fixes a typo in the `request-transformer` documentation page.
- https://docs.konghq.com/hub/kong-inc/request-transformer/
=> Fix response typo in request-transformer page

.github/styles/kong/dictionary.txt, app/gateway/2.8.x/plugin-development/entities-cache.md
Adding explicit definition of `...` parameter in of the `kong.cache` function.
Reading at the `kong` code i was a bit confused on the use of `kong.cache`. I'd have prefer to have to kind of precision to help me developing my own plugin.
=> kong.cache function parameters precision

app/enterprise/2.1.x/property-reference.md, app/enterprise/2.2.x/property-reference.md, app/enterprise/2.3.x/property-reference.md, app/enterprise/2.4.x/property-reference.md, app/enterprise/2.5.x/property-reference.md, app/gateway/2.6.x/reference/configuration.md, app/gateway/2.7.x/reference/configuration.md, app/gateway/2.8.x/reference/configuration.md
Removes examples of adding a path when configuring `portal_gui_host`
Adding a path to `portal_gui_host` is not supported
=> fix(portal) remove examples of portal_gui_host with a path

app/_data/docs_nav_gateway_3.0.x.yml, src/gateway/kong-production/environment-variables.md, src/gateway/kong-production/kong-conf.md
This PR adds two docs: 
A how-to for `kong.conf` and a small how-to on setting environment variables. The info for these docs was pulled out of existing documentation. 
I'm sort of stuck on the title of the kong.conf file. Any thoughts? 
[2418](https://konghq.atlassian.net/browse/DOCU-2418)
soon
=> [DOCU-2418] Kong.conf config 

src/gateway/kong-production/kong-openresty.md, src/gateway/reference/configuration.md
This PR pulls the Open Resty section out of the reference configuration file and into its own file. 
[DOCU-2419](https://konghq.atlassian.net/browse/DOCU-2419)
=> [DOCU-2419] Open Resty 

.github/styles/kong/dictionary.txt, app/_data/docs_nav_gateway_2.8.x.yml, app/_hub/kong-inc/vault-auth/0.4.0.md, app/_hub/kong-inc/vault-auth/_index.md, app/_hub/kong-inc/vault-auth/versions.yml, app/gateway/2.8.x/plan-and-deploy/security/secrets-management/advanced-usage.md, app/gateway/2.8.x/plan-and-deploy/security/secrets-management/backends/aws-sm.md, app/gateway/2.8.x/plan-and-deploy/security/secrets-management/backends/env.md, app/gateway/2.8.x/plan-and-deploy/security/secrets-management/backends/gcp-sm.md, app/gateway/2.8.x/plan-and-deploy/security/secrets-management/backends/hashicorp-vault.md, app/gateway/2.8.x/plan-and-deploy/security/secrets-management/backends/index.md, app/gateway/2.8.x/plan-and-deploy/security/secrets-management/getting-started.md, app/gateway/2.8.x/plan-and-deploy/security/secrets-management/index.md, app/gateway/2.8.x/plan-and-deploy/security/secrets-management/reference-format.md
Added documentation for GCP Vault to Secret Management section in Kong Gateway 
[FTI-4100](https://konghq.atlassian.net/browse/FTI-4100). In discussion with the product engineering team to ship this feature as part of gateway release v2.8.1.3. 
Slack discussion: https://kongstrong.slack.com/archives/C0223LNEQCB/p1658393569090289?thread_ts=1658213496.854579&cid=C0223LNEQCB
Minor document update.
=> Add GCP vault in 2.8.1.3

.github/styles/kong/dictionary.txt, app/_data/docs_nav_gateway_2.8.x.yml, app/_data/kong_versions.yml, app/_hub/kong-inc/acme/_index.md, app/_hub/kong-inc/aws-lambda/_index.md, app/_hub/kong-inc/vault-auth/0.4.0.md, app/_hub/kong-inc/vault-auth/versions.yml, app/gateway/2.8.x/plan-and-deploy/security/secrets-management/advanced-usage.md, app/gateway/2.8.x/plan-and-deploy/security/secrets-management/backends/aws-sm.md, app/gateway/2.8.x/plan-and-deploy/security/secrets-management/backends/env.md, app/gateway/2.8.x/plan-and-deploy/security/secrets-management/backends/gcp-sm.md, app/gateway/2.8.x/plan-and-deploy/security/secrets-management/backends/hashicorp-vault.md, app/gateway/2.8.x/plan-and-deploy/security/secrets-management/backends/index.md, app/gateway/2.8.x/plan-and-deploy/security/secrets-management/getting-started.md, app/gateway/2.8.x/plan-and-deploy/security/secrets-management/index.md, app/gateway/2.8.x/plan-and-deploy/security/secrets-management/reference-format.md, app/gateway/changelog.md
Changelog and any doc updates for the Gateway 2.8.1.3 patch release.
⚠ **Important:** ⚠  We have two potential issues here, both listed under "Features" in the changelog:
Dev checklist for remaining work (mostly docs): https://github.com/Kong/kong-ee/pull/3554
Upcoming patch release. 
https://konghq.atlassian.net/browse/DOCU-2400
https://deploy-preview-4142--kongdocs.netlify.app/gateway/changelog/
I set a release date, but need to verify that this is actually when the release comes out.
=> [DOCU-2400] Release: Gateway 2.8.1.3

app/_layouts/extension.html
Resolves #4161
Resolves #4094
Plugin hub was reporting that a plugin is db-less incompatible in the body, but that it's compatible in the sidebar.
The word `yes` is a boolean true in YAML, and the plugin specified `yes` rather than `"yes"` in the frontmatter. This PR adds a check for `dbless_compatible == true` in addition to the existing `dbless_compatible == "yes"`
[/hub/smartparkingtechnology/google-logging/](https://deploy-preview-4190--kongdocs.netlify.app/hub/smartparkingtechnology/google-logging/)
Old:
New:
=> Fix db-less rendering in plugin hub

src/mesh/installation/macos.md
Resolves #4057
We provide Mesh as an arm64 binary but did not link to it
[/mesh/1.8.x/installation/macos/](https://deploy-preview-4191--kongdocs.netlify.app/mesh/1.8.x/installation/macos/)
=> Add link to arm Mesh downloads

app/gateway/2.8.x/admin-api/admins/reference.md
Resolves #3862
This will likely need porting in to 3.0 too
Help users understand the available statuses in the admin list endpoint. Values taken from https://github.com/Kong/kong-ee/blob/master/kong/enterprise_edition/dao/enums.lua#L12-L19
[/gateway/2.8.x/admin-api/admins/reference/#list-admins](https://deploy-preview-4194--kongdocs.netlify.app/gateway/2.8.x/admin-api/admins/reference/#list-admins)
=> Add status enum docs to Admin endpoint

.github/styles/kong/dictionary.txt, app/_hub/kong-inc/mocking/0.1.x.md, app/_hub/kong-inc/mocking/_index.md
The mocking plugin does not support grpc endpoints
Resolves #4048
[/hub/kong-inc/mocking/](https://deploy-preview-4196--kongdocs.netlify.app/hub/kong-inc/mocking/)
=> Remove grpc from mocking plugin protocols

app/_hub/kong-inc/application-registration/_index.md, app/_includes/hub-examples.html, app/_layouts/extension.html
Adds a new `params.global` entry to plugin configuration that can be set to `false` if a plugin is not available globally (e.g. application registration).
I chose to keep the `Enable globally` tab and show a warning in there to make it obvious that the plugin is not available globally. This is unusual for plugins, and I think the explicit warning is more helpful than a missing tab.
Resolves #3867
[/hub/kong-inc/application-registration/](https://deploy-preview-4195--kongdocs.netlify.app/hub/kong-inc/application-registration/)
=> Add params.global entry to plugins

app/_hub/kong-inc/file-log/_index.md
Resolves #3182
Adding the minimum version required to the parameter description. Once this plugin is single sourced + delegated to gateway releases, we could use `minimum_version` to conditionally render this field. Until then, we need to use the description
[/hub/kong-inc/file-log/](https://deploy-preview-4193--kongdocs.netlify.app/hub/kong-inc/file-log/)
=> Add minimum version for custom_fields_by_lua

.github/styles/kong/dictionary.txt, src/gateway/kong-production/environment-variables.md, src/gateway/kong-production/kong-conf.md, src/gateway/kong-production/kong-openresty.md, src/gateway/kong-production/website-api-serving.md
Infrastructure architecture PR. Take a section from the configuration reference doc and pulls it into its own doc. 
[[2420]](https://konghq.atlassian.net/browse/DOCU-2420)
=> [docu-2420] Website and API in the same Kong Gateway instance

.github/styles/kong/dictionary.txt, app/_data/docs_nav_gateway_3.0.x.yml, src/gateway/plugin-development/other/go.md, src/gateway/plugin-development/other/javascript.md, src/gateway/plugin-development/other/plugins-kubernetes.md, src/gateway/plugin-development/other/python.md
Three new docs that cover writing plugins in Python, Go, and JavaScript. One doc that covers mounting plugins using a Dockerfile. 
[DOCU-2441](https://konghq.atlassian.net/browse/DOCU-2441)
[DOCU-2442](https://konghq.atlassian.net/browse/DOCU-2442)
[DOCU-2443](https://konghq.atlassian.net/browse/DOCU-2443)
Coming soon
=> [docu-2441-2443] Write plugins in other languages

app/_hub/kong-inc/opa/_index.md
- Fix the example rego file in the OPA plugin documentation. Currently, the `allowBoolean` document does not have a default value, which means that if not evaluated the returned value will be undefined and the OPA decision response will be a `{}`, which will eventually cause a 500 error on Kong side. Can be reproduced by following the current version of document, https://docs.konghq.com/hub/kong-inc/opa/#usage. When [trying request on the first time](https://docs.konghq.com/hub/kong-inc/opa/#make-a-request), the 500 error will occur.
- Add two missing config params, `include_body_in_opa_input` and `include_parsed_json_body_in_opa_input`
Fix https://konghq.atlassian.net/browse/FT-2788
=> [FT-2788]fix opa documents undefined return

app/_hub/kong-inc/opa/_index.md
Mirrors https://github.com/Kong/docs.konghq.com/pull/4211 on 3.0
The fix in that doc also affects the 3.0 release.
=> [chore] OPA documents undefined return 3.0

app/moved_urls.yml, tests/install.test.js, tests/seo.test.js, tests/sidebar.test.js
Fixing some smoke tests.
Will do the full list of moved URLs in separate PR.
Broken tests.
Tests should pass.
=> Update smoke tests for new IA

app/gateway/2.8.x/reference/configuration.md
Quick fix set vaults from `off` to `bundled` until we run the autodocs.
=> [fix] Vaults bundled

src/gateway/kong-production/monitoring/datadog.md
Add a brief tidbit doc for explaining and showing an example configuration for connecting Datadog to Kong prometheus
=> fix(add-datadog-prometheus): docs

app/gateway/2.8.x/plan-and-deploy/security/secrets-management/getting-started.md, app/gateway/2.8.x/plan-and-deploy/security/secrets-management/index.md, src/gateway/kong-enterprise/secrets-management/getting-started.md, src/gateway/kong-enterprise/secrets-management/index.md
Copy changes made in https://github.com/Kong/docs.konghq.com/pull/4226 into 3.0.
Slight adjustment to the content, as the main reason for the notes in 2.8 was because the feature changed in a patch version. In 3.0, we don't have that issue anymore.
Netlify
=> Port vaults doc updates into 3.0

.github/styles/kong/dictionary.txt, app/gateway/2.8.x/reference/loadbalancing.md
Add missing commas to JSON configuration object
Fix reference to Service host field in the upstream entity (loadbalancing)
=> Fix lb upstream and JSON objects

src/gateway/kong-enterprise/plugin-ordering/get-started.md
rate-limiting's `limit_by` defaults to `consumer`. In this case we do not have a consumer configured as this is not a supported case with plugin-ordering.
=> docs: fix issues with plugin-ordering examples

app/_data/docs_nav_gateway_3.0.x.yml, src/gateway/get-started/configure-services-and-routes.md, src/gateway/reference/router-operators.md, src/gateway/understanding-kong/how-to/router-atc.md
Two new docs: 
Reference for operators and fields.
Quick how-to create routes with the new router. 
Added a set of  if version tags for the comprehensive guide for 3.1 
[docu-2457](https://konghq.atlassian.net/browse/DOCU-2457)
[docu-2458](https://konghq.atlassian.net/browse/DOCU-2458)
[docu-2388](https://konghq.atlassian.net/browse/DOCU-2388)
=> [docu-2457] Router Reference, Router Route creation

app/_data/docs_nav_kic_2.4.x.yml, app/_data/docs_nav_kic_2.5.x.yml, src/kubernetes-ingress-controller/guides/using-gateway-api.md, src/kubernetes-ingress-controller/references/gateway-api-support.md
Add introduction of gateway API features of KIC for version 2.4 and later.
fixes #4026.
=> doc: add gateway API features in KIC 2.4

app/_data/docs_nav_gateway_3.0.x.yml, src/gateway/kong-enterprise/secrets-management/advanced-usage.md, src/gateway/kong-enterprise/secrets-management/backends/aws-sm.md, src/gateway/kong-enterprise/secrets-management/backends/env.md, src/gateway/kong-enterprise/secrets-management/backends/gcp-sm.md, src/gateway/kong-enterprise/secrets-management/backends/google-sm.md, src/gateway/kong-enterprise/secrets-management/backends/hashicorp-vault.md, src/gateway/kong-enterprise/secrets-management/backends/index.md, src/gateway/kong-enterprise/secrets-management/getting-started.md, src/gateway/kong-enterprise/secrets-management/index.md, src/gateway/kong-enterprise/secrets-management/reference-format.md
Secrets management went into a soft GA in a 2.8 patch version, copying those edits into 3.0. I'm not writing anything new here.
* Updating links for new nav structure
* Updating nav
* Some cleanup of beta and 2.8 mentions. 
Parity with changes made in 2.8.
https://konghq.atlassian.net/browse/DOCU-2291
Netlify preview
=> [DOCU-2291] Copy vaults GA edits to 3.0

app/_data/docs_nav_kic_2.6.x.yml, app/_data/kong_versions.yml, src/kubernetes-ingress-controller/guides/using-gateway-api.md
Update the Gateway API guide for `v0.5.0` in KIC `v2.6.0` to use beta resources and indicate that the the integration is now considered beta.
Resolves https://github.com/Kong/docs.konghq.com/issues/4123
Manually tested the documentation to verify the correct result.
=> docs: handle beta GW apis for 2.6.x KIC

app/_assets/images/icons/documentation/icn-flag.svg, app/_assets/images/icons/documentation/icn-learning.svg, app/_data/docs_nav_gateway_3.0.x.yml
Updating the icons in the new nav to be unique for each section.
* I used the icon we used to use for Dev Portal for the "Develop Custom Plugins" section. It's not an official dev portal icon, it just signifies development - so I think that should be alright.
* Used icons that we already have for most things, had to adjust the learning icon to work for the nav (it's not in use anywhere else). 
* The previous icon used for getting started was a timer, which is supposed to denote getting started quickly. I'm not sure that it really applies (or ever did). The alternative is the learning icon. What do we think?
* Fixed flag icon so it doesn't get blurry (img width is set to 20px, but icon width was 19px, so it was getting a tiny bit stretched).
https://konghq.atlassian.net/browse/DOCU-2459 …
=> [DOCU-2459] Gateway icons

app/_data/docs_nav_kic_2.3.x.yml, app/_data/docs_nav_kic_2.4.x.yml, app/_data/docs_nav_kic_2.5.x.yml
Mark duplicated KIC navigation entries as `generate: false` to remove duplicate generation warning
Run locally, watch as these errors no longer show up:
=> Fix duplicate page generation in KIC

.github/styles/kong/dictionary.txt, src/gateway/understanding-kong/how-to/router-atc.md
This PR contains a fix for `acl` route creation command by adding a single quote at the end of the curl command
I have noticed that the current example is not working with a missing single quote.
With the fix in this PR, the curl works as expected and I am able to create the route.
=> add missing single quote

pdf-generation/build-urls.js
PDF generation is broken for single sourced content
To be able to build Mesh PDFs
```
cd pdf-generation
npm ci
KONG_DOC_VERSIONS=mesh_1.8.x node run.js
```
=> Fix PDF generation for single sourced content

app/gateway/2.8.x/reference/configuration.md
Updated vaults description based on the following feedback:
> In 2.8.1.3 vault bundles are turned on by default and the out of the box memory consumption increase is immediately visible. I think we should update our docs to point this out and show how to turn off vault bundles if customer is not using secrets-mgmt.
I also updated the kong.conf file in kong/kong-ee: https://github.com/Kong/kong-ee/pull/3635 
I didn't think we'd also need to update [this page](https://docs.konghq.com/gateway/latest/plan-and-deploy/security/secrets-management/#beta-and-general-availability-phases), but let me know if you think we should.
=> Fix vault bundles description

app/_includes/breadcrumbs.html, app/_layouts/docs-v2.html
Link all segments in the breadcrumbs to the overview page for that section. The segment is only linked in the URL exists, and is presented without a link if it would lead to a 404.
The breadcrumbs expect the overview page to be named `index.md` within a folder (e.g. /gateway/3.0.x/kong-enterprise/). It does NOT work if the file is named `overview.md` (e.g. /gateway/3.0.x/kong-production/deployment-topologies/overview/). We should standardise on our overview URLs, and I'd vote for not having `/overview/` explicitly in the URL
The new IA work has created nested subdirectories. This highlights that breadcrumb links are working incorrectly:
Try any nested URLs in the review app
=> Fix breadcrumb links

.github/styles/kong/dictionary.txt, app/enterprise/1.3-x/plugins/graphql-quickstart.md, app/enterprise/1.5.x/plugins/graphql-quickstart.md, app/enterprise/2.1.x/plugins/graphql-quickstart.md, app/enterprise/2.2.x/plugins/graphql-quickstart.md, app/enterprise/2.3.x/plugins/graphql-quickstart.md, app/enterprise/2.4.x/plugins/graphql-quickstart.md, app/enterprise/2.5.x/plugins/graphql-quickstart.md, app/gateway/2.6.x/configure/graphql-quickstart.md, app/gateway/2.7.x/configure/graphql-quickstart.md, app/gateway/2.8.x/configure/graphql-quickstart.md
The service name was first defined as `graphql-service` but then referred to as `example-service` in the rest of the guide.
=> fix the service name in graphql quickstart

.github/styles/kong/dictionary.txt, src/gateway/kong-production/monitoring/statsd.md
Adds StatsD monitoring page under Kong in Production
Helps the user with a how-to guide to quickly run Kong GW, StatsD, and StatsD plugin
https://konghq.atlassian.net/browse/DOCU-2423
built and viewed docs locally
=> DOCU-2423: Adds StatsD monitoring page under Kong in Production

app/_data/docs_nav_kic_2.5.x.yml, src/kubernetes-ingress-controller/concepts/gateway-api.md, src/kubernetes-ingress-controller/guides/using-gateway-api.md
Adds a new Gateway API page under the KIC Concepts section. This covers two alpha limitations where Kong's implementation differs from a hypothetical standard Gateway API implementation:
- Gateways are not provisioned automatically and require configuring Kong to match their listeners.
- A Kong instance can only support a single GatewayClass with a single Gateway.
Update the Gateway API guide with links to the new concepts page.
Update the Gateway API guide to include an example of a user-provided certificate.
Fix #4054
Fix #4229
Awaiting preview.
=> doc(kic) add Gateway API concepts

app/konnect/runtime-manager/index.md
Fix broken image for Docker logo
/konnect/runtime-manager/
=> Fix Docker logo on Runtime Manager overview

app/_data/docs_nav_gateway_3.0.x.yml, src/gateway/reference/faq.md
Add instructions on how to recover from a corrupted LMDB cache in a new FAQ section
/gateway/latest/reference/faq/
=> Add LMDB corruption FAQ

src/gateway/reference/configuration.md
Remove mentions of `config.cache.tar.gz`
The config cache has been replaced with LMDB in 3.0
```bash
fgrep -r "config.cache" src
```
=> Remove config.cache in favour of LMDB

app/gateway/2.8.x/plan-and-deploy/security/secrets-management/backends/aws-sm.md, src/gateway/kong-enterprise/secrets-management/backends/aws-sm.md
Switch from `httpie` to `curl` for AWS SM examples
Add consistency to the docs
Try out the curl requests
=> Switch AWS Secrets Manager examples to use curl

src/gateway/kong-production/deployment-topologies/hybrid-mode/hybrid-mode-setup.md
Removes a mention of config cache
=> [fix]Remove config cache

app/_data/kong_versions.yml, app/gateway/changelog.md
Changelog based on https://konghq.atlassian.net/wiki/spaces/FTT/pages/2870542409/Kong+Enterprise+2.8.1.4.
Upcoming patch release for 2.8.1.4.
Ran Vale locally on new chunk of content.
https://deploy-preview-4274--kongdocs.netlify.app/gateway/changelog/
=> Changelog and version bump for 2.8.1.4

app/_data/docs_nav_gateway_3.0.x.yml, autodoc-conf-ee/data.lua, autodoc-conf-ee/run.lua, src/gateway/reference/configuration.md
* Manually diffed the version of the file on the branch with the generated doc from https://github.com/Kong/kong-ee/blob/master/kong.conf.default  and cleaned up the changes.
* Added a two-sentence description for what this reference is for and linked to kong.conf guide
* Script updates:
* Adjusted header levels for the new format
* Moved the horizontal lines (`---`) from around params to around sections. Previous formatting was confusing, made it look like a section only had one parameter in it.
* new path - this might change in the future. I considered building autodocs newly for each version and sourcing that file (eg build to `configuration_3.0.x.md`), but I'm not sure if that's the best approach. Will address when we fix autodocs post-3.0. 
* Adjustments for enterprise badges on …
=> Config reference for 3.0

app/gateway/changelog.md
The AWS & GCP references were mixed up in 2.8.1.4, correcting them in this PR.
They were incorrectly stated, needed to be swapped.
=> Correcting AWS & GCP references in 2.8.1.4

.github/styles/kong/dictionary.txt, app/_assets/javascripts/app.js, app/_assets/stylesheets/navtabs.less, app/gateway/2.8.x/install-and-run/debian.md, app/gateway/2.8.x/install-and-run/ubuntu.md, src/gateway/kong-production/install-options/linux/debian.md, src/gateway/kong-production/install-options/linux/ubuntu.md
Add `apt-mark hold` instructions to prevent accidental Gateway upgrades
cc @hutchic 
Customers accidentally upgrade to newer versions when running `apt upgrade`. This note will help them avoid doing so
=> Add apt-mark hold instructions to Ubuntu/Debian

app/_hub/kong-inc/openid-connect/_index.md
doc(openid-connet) session_compressor default to 'none'.
Misleading customers.
=> doc(openid-connet) session_compressor default to 'none'

tests/breadcrumbs.test.js
Adding autolinked breadcrumbs changed the format of the text to add whitespace (non-visible), which made the smoke test fail. This updates the tests to be more flexible
Failing build
Smoke tests should pass
=> Fix smoke tests for newly linked breadcrumbs

.github/styles/kong/dictionary.txt, src/gateway/admin-api/index.md
From Kong 3.0, path handling v1 will be deprecated and when `router_flavor` == `expressions`, the field will be unconfigurable.
=> docs on path handling algorithm in Kong 3.0

app/_data/docs_nav_gateway_3.0.x.yml, src/gateway/kong-production/deployment-topologies/traditional.md, src/gateway/kong-production/deployment-topologies/traditional/index.md
Move old Clustering Reference to Topologies -> Traditional
The doc already talks about a traditional topology. This makes it more discoverable
/gateway/latest/kong-production/deployment-topologies/traditional/
=> Traditional / Clustering Topology

app/gateway/2.6.x/configure/auth/rbac/index.md, app/gateway/2.7.x/configure/auth/rbac/index.md, app/gateway/2.8.x/configure/auth/rbac/index.md
Removes a broken image from the RBAC guide. 
Reported in Slack
/gateway/latest/configure/auth/rbac/
=> [Fix] Remove broken image from Rbac guide 

app/_data/docs_nav_gateway_2.8.x.yml
Add missing `2.8.x` to URL
2.8 overview link was pointing to 3.0 docs
Test in review app
=> Fix Gateway 2.8.x Overview nav link

app/_headers
Adds the Access-Control-Allow-Method and Access-Control-Allow-Headers headers to the `latest_version` endpoint so that GET requests using a `Content-Type` header work in CORS scenarios.
Signed-off-by: Philipp Rudloff <philipp.rudloff@konghq.com>
Some requests to the `/mesh/latest_version` endpoint are made using a `Content-Type` header. These are rejected by the browser because the CORS preflight request doesn’t include this header.
Using the Netlify deployment preview and the following test call:
```sh
curl -i -X OPTIONS https://docs.konghq.com/mesh/latest_version/ | grep 'access-control-allow-'
curl -i -X OPTIONS https://deploy-preview-4333--kongdocs.netlify.app/mesh/latest_version/ | grep 'access-control-allow-'
```
=> fix: sets access-control-allow-* headers

app/_data/docs_nav_gateway_3.0.x.yml, src/gateway/get-started/proxy-caching.md
Updates the proxy-caching get started guide to match the other work done in related PRs
To improve the getting started experience for readers
Built docs locally
=> DOCU-2471: Updates proxy-caching get-started guide for 3.0 release

app/_plugins/generators/alias_generator.rb
Add redirects for any entries in `moved_urls.yml`
Any moved URLs need an entry in `moved_urls.yml` so that canonical URLs and the "latest version" links work. We can reuse that data to redirect any `/latest/` URLs.
Visit `/gateway/latest/install-and-run/rhel/` and it should redirect
Resolves DOCU-2483
=> Moved urls redirects

src/gateway/reference/configuration.md
Adding `ipv6only`, `so_keepalive`, and lower bounds for nginx worker params. 
Came across a few missing updates in the configuration reference while working on the changelog.
Please don't copyedit. This is coming directly from https://github.com/Kong/kong/blob/master/kong.conf.default and will have to be fixed up there first.
Netlify preview
=> Add missing config options

src/gateway/get-started/proxy-caching.md, src/gateway/get-started/rate-limiting.md, src/gateway/get-started/services-and-routes.md
Makes the example route name match the example service name. Fixes up referring sections of the guide as well
The guides were not accurate with the route name, this fixes that and makes the name consistent with the example service name
built locally
=> Get started fix route name

src/gateway/plugin-development/access-the-datastore.md, src/gateway/plugin-development/admin-api.md, src/gateway/plugin-development/configuration.md, src/gateway/plugin-development/custom-entities.md, src/gateway/plugin-development/custom-logic.md, src/gateway/plugin-development/distribution.md, src/gateway/plugin-development/entities-cache.md, src/gateway/plugin-development/file-structure.md, src/gateway/plugin-development/index.md, src/gateway/plugin-development/tests.md
The `Plugin Development` prefix was repeated on every page. This PR removes them
=> Plugin Development title cleanup

src/gateway/get-started/load-balancing.md
Updates the load balancing getting started guide
To bring this guide up to date with the other get-started work being done in companion PRs
built docs locally
=> DOCU-2473: Load Balancing get-started guide update

src/gateway/plugin-development/custom-logic.md
Updating priority tables:
* Adding new plugins: opentelemetry, tls plugins, and websocket plugins
* Fixing typos for previously updated plugin priorities
* Updated `pre-function` plugin based on changelog entry
* Added missing ACME plugin to OSS table
Priorities pulled from plugin handler files in source code. ([enterprise](https://github.com/Kong/kong-ee/tree/master/plugins-ee) and [oss](https://github.com/Kong/kong/tree/master/kong/plugins))
Plugin priority doc had some oversights.
Netlify
=> Update plugin priorities

src/gateway/reference/cli.md
Update CLI doc for any changes in 3.0.
Normally an autogenerated doc. Resolving manually as the action is currently not working.
Netlify
Please do not copyedit. This text is coming from the CLI help.
=> Update CLI doc for 3.0

src/gateway/support-policy.md
Added an entry for 3.0 in the support policy table.
Followed the 24 month period for support, then another 12 months for end of sunset support, based on the standard set with 2.1.x.
Needs updating with release.
Netlify
=> Update support policy table for 3.0.x.x
