Kong/docs.konghq.com

- src/gateway/get-started/load-balancing.md
Adds a CTA to the final page of the get started workflow
Provide awareness to GW enterprise features.
built docs locally and tested links
> Get Started: Adds cta to load balancing outro

- src/gateway/production/monitoring/index.md
Adds monitoring overview page
built locally and ran vale on file
> DOCU-2421: Adds monitoring overview page

- src/gateway/kong-enterprise/secrets-management/reference-format.md
- src/gateway/production/kong-openresty.md
Remove titles when they duplicate the page title
/gateway/latest/kong-enterprise/secrets-management/reference-format
/gateway/latest/production/kong-openresty/
> Remove duplicate page titles

- app/_data/docs_nav_gateway_3.0.x.yml
Adding missing nav entry for `kong.tracing` pdk.
It's missing.
Netlify
> Add tracing pdk to nav

- app/_data/tables/plugin_index.yml
Add new plugins to compatibility table: opentelemetry, websocket size limit, and websocket validator.
TLS plugins are already present in the table.
New plugins.
Netlify
> Update plugin compatibility table

- app/_layouts/default.html
- app/_layouts/docs-v2.html
- app/_layouts/extension.html
Add `target="_blank"` to external links to open them in a new tab.
We have an external link icon to warn people, but the links don't open in a new tab, as would be expected.
Netlify. Check some external links.
> Open external links in new tab

- src/gateway/install/kubernetes/helm-quickstart.md
https://deploy-preview-4388--kongdocs.netlify.app/gateway/latest/install/kubernetes/helm-quickstart/
Remediate use-ability bugs and oversights in new helm quickstart page.
Additional feedback collected revealing platform specific incompatibility of sed command and lack of hyperlinks to explain terms and dependencies used.
Tested by manually performing instructions in the guide.
> Apply Helm chart feedback + fix sed inconsistenies

- src/gateway/install/index.md
Switch from "Local only" to "Runs, but no official support available"
We have customers running production workloads on some "unsupported" deployments. This PR makes it clearer that they are valid deployment targets, but support is not available
/gateway/latest/install/
> Clarify "unsupported" in installation table

- app/gateway/changelog.md
This includes some nuanced updates to the changelog re: WebSockets.
WebSocket services and routes are stable/GA, as are any of the WebSocket plugins that ship with Kong. What _should_ have a beta/unstable label is the lua-level API (PDK, plugin interface, etc).
The intended message to get across is:
1. The new WebSocket services and routes are ready to use, including our bundled WebSocket plugins.
2. There's also a new WebSocket PDK. It is not stable (yet), so be prepared to roll with any breaking changes if you write your own WebSocket plugin today.
Following these changes, I reordered the list items to emphasize the non-beta features and group the beta ones under a single element.
> update beta status for websockets

- app/gateway/changelog.md
- jekyll-dev.yml
- jekyll.yml
- src/gateway/upgrade.md
- tests/breadcrumbs.test.js
* Adjust info about blue-green deployments and what versions+Gateway packages they're available for
* removed attribution to community contributor. The change they made + asked for isn't directly related, though it affects blue-green.
* Add missing entry for ldap auth advanced plugin
* Updating our product name variables, which are out of date
A couple of conversations in Slack:
https://kongstrong.slack.com/archives/CDSTDSG9J/p1662459895450809
https://kongstrong.slack.com/archives/C02GZ0CGJNT/p1662489559237329
Netlify
> Changelog: Blue-green deployment fixes + missing info

- src/gateway/index.md
Adds a "Quick Links" launchpad on the Gateway index page
To help people find what they need faster
[/gateway/latest/](https://deploy-preview-4396--kongdocs.netlify.app/gateway/latest/)
> Add Gateway quick links section

- README.md
- broken-link-checker/excluded.json
- broken-link-checker/package-lock.json
- broken-link-checker/package.json
- broken-link-checker/product.js
Add new per-product broken link checker
Helps track down broken links in a smaller section of the site to make fixing them accessible
```bash
node product.js --nav gateway_2.8.x --perPage 1 --page 177
node product.js --nav gateway_2.8.x --perPage 1 --page 177 --ignore olivine
```
> Add new per-product broken link checker

- app/_hub/kong-inc/acme/_index.md
- app/_hub/kong-inc/grpc-gateway/_index.md
- app/_hub/kong-inc/grpc-web/_index.md
- app/_hub/kong-inc/openid-connect/1.5.x.md
- src/deck/guides/defaults-v2.md
- src/deck/guides/defaults.md
- src/deck/guides/environment-variables.md
- src/deck/guides/getting-started.md
- src/deck/guides/kong-enterprise.md
- src/deck/guides/konnect.md
- src/deck/guides/multi-file-state.md
- src/gateway/install/docker/index.md
- src/gateway/kong-enterprise/plugin-ordering/get-started.md
- src/gateway/production/deployment-topologies/db-less-and-declarative-config.md
- src/gateway/production/running-kong/secure-admin-api.md
Bumping `_format_version` in declarative config examples to 3.0.
Didn't bump the version in `/konnect/` topics yet. Leaving that for the Konnect 3.0 support update, will be in a separate PR.
decK `_format_version` was bumped to 3.0 for the route path changes. 
See [changelog entry](https://release-gateway-3-0--kongdocs.netlify.app/gateway/changelog/#:~:text=Bumped%20the%20version%20number%20(_format_version)%20of%20declarative%20configuration%20to%203.0%20for%20changes%20on%20route.path.%20Declarative%20configurations%20with%20older%20versions%20are%20upgraded%20to%203.0%20automatically).
Netlify
> Bump deck format version to 3.0

- src/kubernetes-ingress-controller/deployment/k4k8s-enterprise.md
- src/kubernetes-ingress-controller/deployment/k4k8s.md
Kustomize manifests have been moved from `deploy/manifests/base` to `config/base` in KIC repository and the kustomize command was no longer valid. 
Proof for the changed manifests location: https://github.com/Kong/kubernetes-ingress-controller/tree/main/config/base
I have discovered the issue while trying to deploy KIC using the documentation. 
I have verified that the updated command works.
> Fix KIC's kustomize manifests path

- app/gateway/changelog.md
This adds a line item to the Known Limitations section about `nginx-opentracing` as well as a deprecation notice.
https://konghq.atlassian.net/browse/FT-3356
---
Ready for review, but please do not merge without a final :+1: from @tyler-ball or a core gateway manager.
> Add OpenTracing item to Known Limitations

- app/gateway/changelog.md
> We accidently removed RFC3987 validation from route paths

- app/gateway/changelog.md
- src/gateway/upgrade.md
* Rephrase the decK changelog and upgrade guide entries and add a callout to be careful with `deck sync`ing old files.
* Add general callout to the changelog to look at breaking changes and limitations.
* Update release date
Trying to avoid breaking people's environments.
Netlify
> Changelog & upgrade: clarify declarative config + update release date

- app/gateway/2.8.x/developer-portal/helpers/cli.md
In testing, there does not appear to be a verbose option, and in the Portal CLI GitHub there is no reference to verbose either.
Reference: https://github.com/Kong/kong-portal-cli
Because the docs included mention of verbose mode which doesn't seem to exist in Portal CLI.
> Removing reference to Verbose in the CLI

- app/_data/docs_nav_gateway_2.8.x.yml
Fixing nav to match live site.
When doing a very final check of the release branch, noticed that 2.8.x links to latest, therefore going to 3.0.x - then found the missed changes as well.
Check the gateway 2.8.x nav in netlify.
> Fix 2.8.x nav

- src/gateway/plugin-development/custom-entities.md
- src/gateway/upgrade.md
Point Gateway OSS at release branch and not the tag until the release is officially out
> Use OSS release branch in URLs

- src/gateway/install/linux/amazon-linux.md
Fix Amazon Linux 2 install instructions as the package name changed
Tested locally + in docker
> Fix AmazonLinux2 install instructions

- src/gateway/key-concepts/routes/expressions.md
Rename `atc` to `expression` in routing docs
> Rename atc to expression

- app/_data/docs_nav_gateway_3.0.x.yml
- src/gateway/install/kubernetes/kubectl.md
Add `navtabs` to the k8s manifest install
The page felt messy whilst I was working through the manifest instructions to ensure that they work with 3.0
/install/kubernetes/kubectl
> Clean up k8s install (Gateway)

- app/konnect/getting-started/import.md
- app/konnect/runtime-manager/runtime-groups/declarative-config.md
- src/deck/guides/konnect.md
Docs for the new personal access tokens feature. 
[DOCU-2353](https://konghq.atlassian.net/browse/DOCU-2453)
* /deck/latest/guides/konnect/#authenticate-using-a-personal-access-token : This is the only section that explains how to obtain a PAT. Is this sufficient or should we create a separate page in the Konnect guide about this as well? My thinking was that this is related to decK/Konnect API auth workflows, so the content should exist alongside those workflows instead of a separate page, but I'd like to know what you think.
> [DOCU-2453] Documentation for Konnect Personal Access Tokens

- .github/workflows/require-review-label.yml
Adding the new `review:sme` label to label-checking workflow.
Added a new label to split the job of `review:tech` into two. `review:tech` now means internal docs platform changes, whereas `review:sme` is asking for external review (engineering, PM).
Putting the label on this PR to test. If it passes, then it worked.
Edit: yep, it worked.
> Add review label to workflow

- app/_data/tables/version_errors_konnect.yml
- app/konnect/compatibility.md
- app/konnect/index.md
- app/konnect/runtime-manager/gateway-config.md
- app/konnect/runtime-manager/index.md
- app/konnect/runtime-manager/runtime-instances/gateway-runtime-docker.md
- app/konnect/runtime-manager/runtime-instances/gateway-runtime-kubernetes.md
- app/konnect/runtime-manager/runtime-instances/upgrade.md
- app/konnect/runtime-manager/troubleshoot.md
- app/konnect/servicehub/index.md
- app/konnect/servicehub/service-implementations.md
- app/konnect/updates.md
Update the Konnect docs with Gateway 3.0 info and support.
* Bump version for docker images to 3.0.0.0
* Still using `alpine` since that's what the UI uses; PM made this decision because these sample scripts are meant to target the net new user, ie the tester.
* Table for error messages based on eng-provided content. Turned the provided data into yaml and added links to relevant plugin docs.
* Mentions of the version compatibility issues in various places
* release note
* adding a quick links section to match Gateway 3.0
I couldn't find anything that made sense to add to the decK docs; those docs are already up to date for all the things decK supports (plugin ordering, PATs, etc).
https://konghq.atlassian.net/browse/DOCU-2478
Broken links are to be expected right now. This depends on some …
> [DOCU-2478] Konnect 3.0 support

- app/_data/docs_nav_kic_2.5.x.yml
Guide is missing from 2.5.x nav in KIC docs. Seems like the previous fix to add it to the nav wasn't picked up by 2.5.x as it had already branched from `main` and wasn't rebased.
Broken link + missing guide. Reported here: https://github.com/Kong/docs.konghq.com/issues/2939#issuecomment-1216912331
Netlify.
> Add missing knative guide to nav

- src/gateway/get-started/rate-limiting.md
Fixes a command in the getting started guide that doesn't work on bash (worked on zsh).
bash compatibility is important for the guide
Tested the command in bash as well as zsh
> Fix for get-started rate limiting test command

- app/_hub/kong-inc/file-log/_index.md
Add missing key to File Log plugin doc. 
Without the key, plugin doc generates without a configuration section.
Netlify
Check that the plugin has a configuration reference section
> File log plugin: missing `params` key

- src/gateway/get-started/proxy-caching.md
Add missing `port number` to a code snippet in `/gateway/get-started/proxy-caching.md`
The current snippet was broken.
Go to [Manage cached entities](https://deploy-preview-4455--kongdocs.netlify.app/gateway/3.0.x/get-started/proxy-caching/#manage-cached-entities) and run the last code snippet.
> Add missing port to get-started/proxy-caching code snippet

- app/_hub/kong-inc/acme/_index.md
- app/_hub/kong-inc/aws-lambda/_index.md
- app/_hub/kong-inc/azure-functions/_index.md
- app/_hub/kong-inc/forward-proxy/_index.md
- app/_hub/kong-inc/graphql-rate-limiting-advanced/_index.md
- app/_hub/kong-inc/kafka-log/_index.md
- app/_hub/kong-inc/kafka-upstream/_index.md
- app/_hub/kong-inc/ldap-auth-advanced/_index.md
- app/_hub/kong-inc/loggly/_index.md
- app/_hub/kong-inc/openid-connect/_2.2.x.md
- app/_hub/kong-inc/openid-connect/_index.md
- app/_hub/kong-inc/proxy-cache-advanced/_index.md
- app/_hub/kong-inc/rate-limiting-advanced/_index.md
- app/_hub/kong-inc/rate-limiting/_index.md
- app/_hub/kong-inc/request-transformer-advanced/_index.md
- app/_hub/kong-inc/response-ratelimiting/_index.md
- app/_hub/kong-inc/session/_index.md
- app/_layouts/extension.html
Add a `referenceable` attribute to plugin parameters that will render the `referenceable` help text rather than manually adding it to the description
Fixes a broken link, and helps with maintenance
Check any referenceable fields in plugins
> Make 'referenceable' a parameter attribute in plugins

- src/kubernetes-ingress-controller/guides/using-gateway-api.md
- src/kubernetes-ingress-controller/references/gateway-api-support.md
update gateway apiVersion to `v1beta1` for resource `Gateway`, `GatewayClass`, `HTTPRoute`.
Gateway API has removed `v1alpha2` resources  `Gateway`, `GatewayClass`, `HTTPRoute`, and we decided to remove support for the resources above in `v1alpha2` version: https://github.com/Kong/kubernetes-ingress-controller/issues/2887. We need to update the docs for KIC 2.6 to update the references of these resources. 
Would fix #4407.
> update gatewayAPI to v1beta1 in KIC >= 2.6.x

- src/gateway/upgrade.md
Removing a phrase left over from old upgrade guide. The phrase is incorrect and misleading.
Someone ran into it on Slack: https://kongstrong.slack.com/archives/C03CTMSHP6C/p1663172321949689
Netlify
> Upgrade guide: remove old instructions

- src/gateway/get-started/rate-limiting.md
Step 1:
```
curl -X POST http://localhost:8001/consumers/ \
--data username=jsmith
```
Step 2:
```
curl -X POST http://localhost:8001/plugins \
--data "name=rate-limiting" \
--data "consumer.id=jsmith" \
--data "config.second=5" \
```
If you run the above, the 2nd curl returns
```"message":"schema violation (consumer.id: expected a valid UUID)"```
Should plugin be created with `--data "consumer.username=jsmith` instead.
Command does not work.
Follow the quick start guide and create a consumer and create the rate limiting plugin.
> Fix curl for consumer rate limiting plugin

- app/gateway/changelog.md
Fixed the link to secrets management in the release notes.
Link was a 404.
/gateway/changelog/
> Fix Secrets Management link in 3.0 release notes

- app/_data/docs_nav_kic_2.6.x.yml
- app/_data/kong_versions.yml
- src/kubernetes-ingress-controller/guides/upgrade-kong-3x.md
- src/kubernetes-ingress-controller/references/version-compatibility.md
Adds documentation for KIC 2.6. consisting of metadata updates, compat table updates, and a new article for Kong 3.x upgrades.
Part of https://github.com/Kong/kubernetes-ingress-controller/issues/2880
Normally I would submit docs after the KIC release is actually out, but in this case I'd like to link to the doc from the KIC changelog. I think we probably just allow the changelog link to be a dead link temporarily and merge this once the release is available, but wasn't sure we wanted to order it that way.
Awaiting preview.
Partial runthrough of the new guide commands. I tested the commands to create the IngressClassParameters resource and patch the IngressClass. The rest are copied from https://docs.konghq.com/kubernetes-ingress-controller/latest/guides/upgrade/ with minor adjustments …
> doc: add KIC 2.6 and Kong 3.x controller guide

- app/_data/docs_nav_gateway_3.0.x.yml
- app/_data/tables/features/gateway.yml
- app/gateway/changelog.md
- src/gateway/kong-enterprise/fips-support.md
- src/gateway/kong-enterprise/index.md
- src/gateway/reference/configuration.md
We had an issue with the FIPS packages so held off on releasing that with the rest of the 3.0.0.0 packages. We fixed the issue and preparing to release only the 3.0.0.0 FIPS packagges.
Reverts https://github.com/Kong/docs.konghq.com/pull/4416
Netlify
> Adding FIPS 3.0.0.0 release documentation

- app/gateway/changelog.md
Removing limitation. 
See slack convo: https://kongstrong.slack.com/archives/CDSTDSG9J/p1663272232698729
Netlify
> No more limitation for TLS connections in Alpine builds

- app/gateway/changelog.md
Add a note clarifying that `pg_ssl` in FIPS mode isn't supported in 3.0.
> docs(gateway) add note on pg_sql and fips

- src/kubernetes-ingress-controller/guides/using-gateway-api.md
- src/kubernetes-ingress-controller/references/cli-arguments.md
- src/kubernetes-ingress-controller/references/feature-gates.md
update KIC docs about gateway APIs for KIC 2.6 release. Includes:
- feature gate `Gateway` turned on by default, and added `GatewayAlpha`  feature gate.
- added `--gateway-api-controller-name` flag.
- conditions of reconciling `Gateway` changed. 
KIC 2.6 released and docs are added, but the docs about gateway APIs are not updated. fixes: #4480, also fixes #4479.
https://deploy-preview-4481--kongdocs.netlify.app/
> update gateway api related docs for KIC 2.6

- src/kubernetes-ingress-controller/guides/upgrade-kong-3x.md
Phrasing and formatting edits to clarify the purpose of the `enableLegacyRegexDetection`option + some minor cleanup edits.
Addressing an unresolved comment left on the KIC 2.6 release PR: https://github.com/Kong/docs.konghq.com/pull/4444#discussion_r969955115
Netlify
> KIC 2.6: Clarification for upgrading to Kong Gateway 3.x

- app/_plugins/generators/single_source_generator.rb
- docs/single-sourced-versions.md
- src/kubernetes-ingress-controller/guides/using-gateway-api.md
Allow setting frontmatter values for specific versions
Needed to mark some versions as `alpha` and later versions as non-alpha.
/kubernetes-ingress-controller/2.5.x/guides/using-gateway-api/
/kubernetes-ingress-controller/2.6.x/guides/using-gateway-api/
> Add support for frontmatter overrides

- .vale.ini
Vale is currently ignoring the ignore rules.
The `[ignores]` tag was added in https://github.com/Kong/docs.konghq.com/pull/4448, from what I can tell, accidentally. There were some changes tested out for ignoring blocks of text that were reverted, but this change stuck around.
Currently, it's breaking the check, as [Vale flags everything](https://github.com/Kong/docs.konghq.com/runs/8459427205) that we originally had an ignore rule for (eg navtabs or lte/gte tags). 
Run `vale` locally on this branch on some topic with navtabs or version labels, eg 
```
vale src/kubernetes-ingress-controller/guides/using-gateway-api.md
```
> Fix vale ignore rules

- src/gateway/get-started/index.md
- src/gateway/production/monitoring/prometheus.md
- src/gateway/production/monitoring/statsd.md
Kat Morgan and I discovered on Ubuntu that when piping the script to sh (which is dash on ubuntu) the shell does not respect the bash shebang and the script syntax is invalid. Modifying the instructions to pass the script to bash works on Ubuntu and MacOS.
The instructions do not work on Ubuntu
Tested code locally on Ubuntu and MacOS.  Did not test the docs build itself as the change is trivial
> Kong Quickstart: Pipes quickstart to script to bash instead of sh

- app/_data/docs_nav_gateway_3.0.x.yml
- app/gateway/changelog.md
- src/gateway/key-concepts/routes/expressions.md
- src/gateway/reference/router-expressions-language.md
- src/gateway/reference/router-operators.md
This PR adds more description of expressions matching priority. It also renames the "Router operators" reference page to a more meaningful name, that page is already much more than just about operators.
> Router docs improvement

- app/konnect/network-resiliency.md
- app/konnect/network.md
Clarifying info about DP access through firewalls. Previously, the doc was saying that the CP needs access, which is incorrect.
See https://kongstrong.slack.com/archives/CQK8J4VN3/p1663685608861879?thread_ts=1663682193.400399&cid=CQK8J4VN3.
Netlify.
> Change "control plane" to "data planes"

- app/_hub/kong-inc/exit-transformer/_index.md
- app/_includes/hub-examples.html
Add the ability to add k8s-specific examples in the plugin hub
Some values need specifying inline in the YAML. The existing examples assumed that `curl` was being used
See the Kubernetes tab in /hub/kong-inc/exit-transformer/#example-config
> Add ability to provide k8s-specific examples

- app/_data/docs_nav_deck_1.15.x.yml
- src/deck/guides/3.0-upgrade.md
- src/deck/reference/deck_convert.md
Upgrade/convert guide for declarative config in Gateway 3.0. 
Although db migrations cover config data already in the database, state files are not updated with migrations. These have to be converted in 3.0 format separately.
https://konghq.atlassian.net/browse/DOCU-2499
See netlify.
> [DOCU-2499] decK: 3.0 migration guide

- src/deck/guides/konnect.md
Add an environment precedence section to the decK Konnect reference. 
Also updating any place in the guide where it should mention PATs but only mentions passwords.
Precedence fix coming in decK 1.15. 
https://konghq.atlassian.net/browse/DOCU-2522
https://deploy-preview-4498--kongdocs.netlify.app/deck/latest/guides/konnect/
> [DOCU-2522] decK: order of precedence for Gateway vs Konnect modes

- src/gateway/admin-api/index.md
Fix the wrong API path of "Set Target Address As Unhealthy"
The correct API path of "Set Target Address As Unhealthy" is `/upstreams/{upstream name or id}/targets/{target or id}/{address}/unhealthy`
> fix(admin-api): fix wrong api path

- app/kubernetes-ingress-controller/2.1.x/concepts/custom-resources.md
Correcting the annotation for KongIngress which was raised as an issue in https://github.com/Kong/docs.konghq.com/issues/3699
Link to actual page -  https://docs.konghq.com/kubernetes-ingress-controller/2.1.x/concepts/custom-resources/#kongingress
Correction Reference -
https://docs.konghq.com/kubernetes-ingress-controller/latest/references/annotations/#konghqcomoverride
Correcting the annotation for KongIngress which was raised as an issue in https://github.com/Kong/docs.konghq.com/issues/3699
> Updated the annotation for KongIngress

- src/kubernetes-ingress-controller/deployment/admission-webhook.md
- src/kubernetes-ingress-controller/deployment/aks.md
- src/kubernetes-ingress-controller/deployment/eks.md
- src/kubernetes-ingress-controller/deployment/gke.md
- src/kubernetes-ingress-controller/deployment/k4k8s-enterprise.md
- src/kubernetes-ingress-controller/deployment/kong-enterprise.md
- src/kubernetes-ingress-controller/deployment/minikube.md
During releases, we publish KIC manifests with the updated version before that image becomes available. In the event that something goes wrong during the release, there may be an extended period where the manifests at the tip of master or main do not work.
To avoid documentation pointing to broken manifests, this change replaces short URLs with their full versions, and uses templates to inject the doc page's version into the URL. There may be a better way to get this version, but replacing bits of the `kong_version` value at least achieves the right end result. I furthermore want to avoid the bitly URLs in particular because we don't have a paid account and can't modify them. Until such time as we do, I don't want to use them.
This does have a side effect of always using the first release …
> Pin KIC install versions

- app/_data/docs_nav_kic_2.7.x.yml
- app/_data/kong_versions.yml
- src/kubernetes-ingress-controller/guides/upgrade-kong-3x.md
- src/kubernetes-ingress-controller/references/version-compatibility.md
Adds KIC 2.7 with a revised Kong 3.x upgrade guide.
Updates the 2.6 compatibility information based on what we've learned about older EOL Kubernetes versions.
This should not be merged automatically. We will merge it once the release is actually out.
2.7 is effectively 2.6.1, but our fix required a breaking change, so it's getting a minor version bump instead of a patch release. The upgrade guide refers to 2.7 as the first version that supports Kong 3.x now, which isn't technically true, but is close enough to true because of 2.6's incomplete support. We don't want to maintain separate versions of the guide for 2.6 and 2.7 because the recommended configuration for 2.6 isn't actually possible.
https://deploy-preview-4503--kongdocs.netlify.app/kubernetes-ingress-controller/latest/guides/upgr …
> doc(kic) add 2.7 docs

- src/gateway/admin-api/index.md
Adds links. 
[corresponding PR](https://github.com/Kong/kong-ee/pull/3829)
> [fix] Add links to router docs in router object api documentation

- app/konnect/getting-started/index.md
Updating "runtime connection" to "runtime instance".
"runtime connection" is old terminology left over from pre-Helium. It's not present anywhere else in the docs, UI, or any of our communications.
https://konghq.atlassian.net/browse/DOCU-2585
Netlify
> [DOCU-2585] Update runtime terminology

- src/kubernetes-ingress-controller/references/version-compatibility.md
Adds a compatibility matrix of supported KIC Gateway API features vs Kubernetes minor versions. 
My reasoning behind the support and why it's limited to fewer versions than what we've got for the general Kubernetes support: 
* [Gateway API declares to support the 5 recent versions of Kubernetes](https://gateway-api.sigs.k8s.io/concepts/versioning/#supported-versions),
* I inspected all KIC releases' go.mods to verify which Gateway API bundle versions were used for each of them.
* Based on the release dates, I verified which Kubernetes version was the latest at the time of the Gateway API bundle release for every KIC version.
* The supported Kubernetes versions are the 5 recent ones at the time of the bundle release + newer ones. 
Resolves …
> Add KIC Gateway API and Kubernetes support table

- app/_hub/kong-inc/oauth2/_index.md
Change is to mention various ways of how we can call OAuth2/token endpoint to retrieve access_token for client_credentials grant_type.
Where is the problem?
https://docs.konghq.com/hub/kong-inc/oauth2/
What happened?
I dont see documentation of various ways of calling "/oauth2/token" call for client_credentials flow.
What did you expect to happen?
In Client credentials flow, there is a provision to make "oauth2/token" call by passing the client ID, client secret and grant_type as query param or a JSON body or in a url-encoded form data.
I would like to see if this approved, can be submitted for Kong Hackathon 2022 under documentation category.
review:tech
> Updated index.md for OAuth2 Authentication

- .github/workflows/linting.yml
This adds `filter_mode: added` instead of using `__onlymodified`. 
testing:
This is now:
It creates an output of:
While only expressing the errors in the changed files:
> add filter mode to vale

- .github/workflows/linting.yml
Previously I enabled this on annotated lines. It should be on modified files. 
I'll make two more commits to this PR to test if the second commit flags the spelling mistake in the first commit. [2785e6f](https://github.com/Kong/docs.konghq.com/pull/4552/commits/2785e6f6dcb8fd251b98dd55fe08595163c84bcf) contains 4 mistakes, [36c0ef6](https://github.com/Kong/docs.konghq.com/pull/4552/commits/36c0ef600ec1feead545c0c2102769559014d43c) brings the total to 7. 
Here are the results:
forced push over those commits so this can be merged.
> [fix] Vale on modified files

- app/_hub/kong-inc/zipkin/_index.md
The documentation for the Zipkin plugin say to use commas to separate values passed in to the "Zipkin-Tags" header. The code says semicolons.
https://github.com/Kong/kong/blob/fab7b28cc1dddd1e2bd3ac28bf93316322186e48/kong/plugins/zipkin/request_tags.lua#L21
I haven't tested this yet. I just noticed while writing a test around a pre-function that leverages this functionality.
> Swap comma for semicolon in Zipkin plugin docs

- app/_hub/kong-inc/route-by-header/_index.md
Remove UI examples for `route-by-header`
The route-by-header plugin can't be configured using the UI
Also resolves DOCU-2592
TBC
> Remove konnect UI examples from route by header plugin

- src/gateway/install/docker/index.md
Removed operating system portion of the image tags used in the documentation for install commands. 
It seems we are moving away from Alpine image recommendations (for prod systems) in 3.0 to Debian or RHEL based images instead. As a result of that change in 3.0, our docs should reflect that better in the commands we provide for installing an instance of Kong in Docker, since we already called it out as not production-worthy in the main Install Kong page. 
Since this doc is generated based on the selected version of Kong, I felt it was perhaps best to remove all references to alpine in the tags and stick to just the version itself. Reason behind that was that Alpine is the default image in 2.x when using just the version tag, and Debian is the default image for 3.x when using just the …
> Removing OS part of image tag names

- app/_includes/nav-v2.html
Make Kong Incubator the main CTA in the top nav
We need the Incubator projects to be adopted to inform our strategic roadmap
Try the link at the top of the screen
> Add Incubator to top nav

- app/_hub/kong-inc/key-auth-enc/_index.md
Make some examples for the Key Auth Advanced plugin clearer, clean up a bunch of formatting, and use formatting consistent with style guide.
https://konghq.atlassian.net/browse/DOCU-2259
Technically, the example did work as documented before, but it wasn't very clear, and the request format looked like an error. Provided two options - with key and and without - to make it more obvious that not providing a key in the request is intentional.
Netlify
> [DOCU-2259] Key auth encrypted plugin example fix

- .github/styles/kongplugins/plugin-ignore.txt
- app/_hub/kong-inc/prometheus/_index.md
Fixing a typo in config parameter.
https://github.com/Kong/docs.konghq.com/issues/4569
Netlify. Check against the plugin schema: https://github.com/Kong/kong/blob/master/kong/plugins/prometheus/schema.lua
> Prometheus: fix latency typo

- src/gateway/kong-enterprise/dev-portal/cli.md
Tiny update to correctly display the <workspace> code tag
Came across the page & noticed the tag is invisible, making the sentence awkward to read.
N/A
review:general
> Updated cli.md to show workspace tag

- .github/styles/kong/auto-ignore.txt
- src/kubernetes-ingress-controller/concepts/custom-resources.md
- src/kubernetes-ingress-controller/guides/using-kongingress-resource.md
- src/kubernetes-ingress-controller/references/custom-resources.md
Fix #4474
This makes several changes to KongIngress documentation:
- All KongIngress docs now recommend the use of annotations where possible and explain the precedence order when both are present. This has been our recommendation for some time but was never properly documented.
- The KongIngress guide has been largely rewritten to expand the existing load balancer configuration documentation for Services and cover header routing for Ingress (it's the only KongIngress-exclusive Ingress configuration).
- The KongIngress section of the custom resources concepts documentation has been updated to remove some outdated information, simplify language, and remove inline code formatting for resource names (for everything, not just KongIngress). The formatting change is based on the convention used …
> Rework KongIngress documentation.

- src/kubernetes-ingress-controller/guides/using-gateway-api.md
Update using-gateway-api.md to use correct gatewayClass annotation. The 2.6x KIC [release](https://github.com/Kong/kubernetes-ingress-controller/blob/main/CHANGELOG.md#260) mentions that the gatewayClass requires the annotation `konghq.com/gatewayclass-unmanaged`. This PR tries to correct the annotation used in the guide.
Just to make sure that those who are following the guide will use the correct gatewayClass annotation.
> Use correct gatewayClass annotation in the guide

- src/mesh/installation/amazonlinux.md
- src/mesh/installation/centos.md
- src/mesh/installation/debian.md
- src/mesh/installation/docker.md
- src/mesh/installation/ecs.md
- src/mesh/installation/helm.md
- src/mesh/installation/kubernetes.md
- src/mesh/installation/macos.md
- src/mesh/installation/openshift.md
- src/mesh/installation/redhat.md
- src/mesh/installation/ubuntu.md
- src/mesh/installation/windows.md
There were a few issues in the getting started docs that were mostly typos.
> fix: diverse typos in mesh getting started docs

- app/gateway/changelog.md
These are breaking changes so added to the appropriate section.
We simply missed this as part of the 3.0.0.0 release.
netlify
> We removed lookaround and backreferences, adding that to the release notes

- src/kubernetes-ingress-controller/concepts/gateway-api.md
- src/kubernetes-ingress-controller/guides/using-gateway-api.md
This PR removes the alpha banner for Gateway API support in KIC and tweaks the wording around the feature gate which default was changed in 2.6.
> kic: remove alpha for Gateway API

- src/kubernetes-ingress-controller/guides/using-gateway-api.md
- src/kubernetes-ingress-controller/references/gateway-api-support.md
This PR addresses a missing alpha banner for older KIC version (between 2.4 and 2.5 inclusive) that is missing after my last PR #4588
> kic: add alpha banner for Gateway API support in KIC in v2.4 and v2.5

- app/_data/kong_versions.yml
- app/gateway/changelog.md
Changelog for Gateway 2.8.2.0 patch.
Upcoming patch release.
Compiled from https://konghq.atlassian.net/wiki/spaces/FTT/pages/2884239361/Kong+Enterprise+2.8.2.0 and linked tickets.
https://konghq.atlassian.net/browse/DOCU-2498
Netlify
> Release: Gateway 2.8.2.0

- src/gateway/admin-api/index.md
After https://github.com/Kong/docs.konghq.com/pull/4573 , the invalid field `type` is still present in the code examples. This MR fixes this.
Related https://github.com/Kong/kong/issues/9501
:hammer_and_wrench: with :heart: by [Siemens](https://opensource.siemens.com/)
> fix(admin-api): remove consumers type field from examples

- src/kubernetes-ingress-controller/deployment/admission-webhook.md
Changing failurePolicy from Fail to Ignore to match 2.5.0 and newer KIC version defaults.
In KIC 2.5.0 and higher, we changed the Admission Controller to use a new default of Ignore instead of Fail, so just bringing the docs into alignment too. Ref: https://github.com/Kong/kubernetes-ingress-controller/issues/2501
> Change Fail to Ignore on failurePolicy for Admission Controller

- src/gateway/kong-enterprise/dev-portal/applications/auth-provider-strategy.md
Removes text that states that key-auth does not work with hybrid mode. Oauth 2.0 is the only plugin that is not fully compatible with hybrid mode. https://docs.konghq.com/hub/plugins/compatibility/
https://konghq.atlassian.net/browse/DOCU-2618
> [fix] Key-auth hybrid mode

- app/gateway/changelog.md
Minor edits to the 2.8.2.0 changelog + adding missing entry for AWS lambda fix.
Checked against eng changelog and dedicated tickets, the AWS lambda fix was the only thing missing at this point.
Changelog was released hastily following eng release and was missing some things.
Netlify
> 2.8.2 changelog fixes

- app/_hub/kong-inc/request-validator/_index.md
Support `config.allowed_content_types` to be configured with parameter
Currently, the config.allowed_content_types doesn't support being configured with a parameter(especially `charset`). 
Request with header "Content-type: application/json, charset=UTF-8" will always get 400 {"message":"request param doesn't conform to schema"}
Would like to release this to 3.1 and the next **feature** release of 2.8.x.x(after 2.8.2.0)
[FTI-2650]
[FTI-2650]: https://konghq.atlassian.net/browse/FTI-2650?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(request-validator): support config.allowed_content_types to be configured with parameter

- src/gateway/kong-enterprise/dev-portal/enable.md
- src/gateway/kong-manager/enable.md
Add links to kong.conf and clean up + validate Dev Portal set up instructions.
Dev Portal on-prem setup instructions were very outdated; this has been on my to-do list for a bit.
https://konghq.atlassian.net/browse/DOCU-275 (papercut ticket, needed something to do while waiting at airport)
Netlify
> [DOCU-275] Validate and improve the Dev Portal enablement doc

- app/_plugins/generators/single_source_generator.rb
- jekyll-dev.yml
- jekyll.yml
- src/gateway/install/docker/build-custom-images.md
- src/gateway/install/docker/index.md
- src/gateway/install/linux/amazon-linux.md
- src/gateway/install/linux/centos.md
- src/gateway/install/linux/debian.md
- src/gateway/install/linux/rhel.md
- src/gateway/install/linux/ubuntu.md
- src/gateway/kong-enterprise/analytics/influx-strategy.md
- src/gateway/production/deployment-topologies/hybrid-mode/setup.md
Remove `version-index` from single sourced content and replace it with `page.versions.ce` and `page.versions.ee`
We don't need it any more. It was error-prone and we forget to update it
Spot check changed pages
I grepped for any usage and they've all been removed:
```
$ fgrep -r "version-index" src
```
> Remove version-index from pages in `src`

- app/_assets/javascripts/app.js
- app/_assets/stylesheets/base.less
Fix scroll behaviour when clicking an anchor link by replacing JS implementation with CSS. It previously scrolled to the header, but the header was off-screen
Papercut fix - it was annoying
Try clicking an anchor link in the right hand sidebar. I've tested with the mobile and full screen layouts
https://deploy-preview-4612--kongdocs.netlify.app/gateway/changelog/#2814
> Fix anchor scroll behaviour

- app/_includes/md/gateway/root-user-note.md
Highlight the root-user-note section in "important"
https://konghq.atlassian.net/browse/FTI-4351
We have discovered potential users skip/ignore the section 
Highlighting this section might help with this issue
review the section and verify it's shown in "Important" instead of "Note"
> Make root-user-note.md shown in important section

- src/gateway/reference/configuration.md
Fixes #4559 
Removed tlsv1 from postgress settings docs
Tslv1 as of 3.0.0 this is not a supported value/option
View the docs
> Removed tlsv1 from postgress settings docs

- app/_includes/md/gateway/root-user-note.md
Followup to #4618 
cc @Guaris 
There was a missing class, which meant that the blockquote is not being styled correctly
> Add missing .important class in non-root user content

- package-lock.json
- package.json
Remove standard JS linter
We don't use it in any CI pipelines. It's an unused dependency
Can you test something that doesn't exist? 🤔
> Remove standard JS linter

- src/gateway/how-kong-works/routing-traffic.md
expresses that regex values need a ~ to be considered regex, and also that not including it means the route gets parsed as plain text. 
reported. 
I've also created [docu-2630] for updating this entire doc.
> [fix] regex description for routes

- .github/styles/kongplugins/auto-ignore.txt
- app/_hub/kong-inc/route-transformer-advanced/_index.md
Add a new option escape_path to the route-transformer-adv plugin.
The new option will enable the ability to escape the path transformed.
Realted PR: https://github.com/Kong/kong-ee/pull/3760
https://konghq.atlassian.net/browse/FTI-4272
> [FTI-4272] add escape_path to route-transformer-adv plugin

- app/_hub/kong-inc/rate-limiting/_index.md
The description for the rate-limiting plugin's `limit_by` parameter was incorrect.
Limiting by service does not use a (non-existent) config.service_id parameter, but instead uses the service.id the plugin is configured against.
https://github.com/Kong/docs.konghq.com/issues/4580
Tested behavior on local Kong 3.0 instance. The config.service_id parameter is invalid, and results in an error:
```json
{
"fields": {
"config": {
"service_id": "unknown field"
}
},
"name": "schema violation",
"code": 2,
"message": "schema violation (config.service_id: unknown field)"
}
```
Benjamin Bertow <benjamin.bertow@mercedes-benz.com>, Mercedes-Benz Tech Innovation GmbH
> Correct limit_by service for rate-limiting plugin

- src/kubernetes-ingress-controller/guides/getting-started.md
Add a link to guide of using gateway API in getting started page of KIC. To make the docs of gateway API more visible.
KIC has supported gateway API by default from 2.6.0. But we do not have a place on getting started page to guide users of KIC to use gateway API. So I added a link to the guide of gateway API at the bottom. fixes #4638.
https://deploy-preview-4639--kongdocs.netlify.app/kubernetes-ingress-controller/latest/guides/getting-started/
> add link to guides for using gateway api in gettingstarted page

- src/gateway/plugin-development/custom-logic.md
Fixing an ordering bug in the plugin table
the ordering is not correct for the graphql plugin 
verify that the plugin are ordered correctly
> fix priority order

- src/kubernetes-ingress-controller/concepts/design.md
- src/kubernetes-ingress-controller/concepts/gateway-api.md
- src/kubernetes-ingress-controller/guides/using-gateway-api.md
- src/kubernetes-ingress-controller/references/gateway-api-support.md
This PR adds Gateway API concepts to KIC's design/architecture overview.
It also does some minor tweaks to the docs, as well as changing the section title in "Using Gateway API" from `Alpha` to `Beta` for KIC versions 2.6 and above.
https://github.com/Kong/kubernetes-ingress-controller/issues/2968
> kic: add Gateway API mention in KIC's architecture design overview

- app/_data/tables/compat.json
- Adding back RHEL 7.9 support that was incorrectly dropped in https://github.com/Kong/docs.konghq.com/pull/4594
> doc(compat) add back RHEL 7.9

- src/gateway/production/deployment-topologies/db-less-and-declarative-config.md
Main changes are the "See also" section and the link to the schema on line 162.
Otherwise, some minor style/grammar cleanup while I'm in this topic.
It came up in a conversation internally that we only provide a minimal example in the docs: https://kongstrong.slack.com/archives/C02GZ0CGJNT/p1666886042487039 
https://deploy-preview-4655--kongdocs.netlify.app/gateway/latest/production/deployment-topologies/db-less-and-declarative-config/
> Link to declarative config schema

- app/_plugins/generators/kuma_to_kong_mesh.rb
Replace Kuma with Kong Mesh in titles
When using single sourced content, we can't use `{{ site.mesh_product_name }}` in titles. This blanket replaces Kuma with Kong Mesh in titles
/mesh/latest/features/policy-enforcement/choosing-policies/ in the review app
> Replace Kuma with Kong Mesh in titles

- app/_assets/kubernetes-ingress-controller/examples/echo-service.yaml
- app/_assets/kubernetes-ingress-controller/examples/echo-services.yaml
- src/kubernetes-ingress-controller/guides/using-gateway-api.md
This adds info about traffic splitting using Gateway API HTTPRoute.
This PR also makes the "Using Gateway API" page only visible in KIC versions >= 2.2.x since that's the version that initial implementation was released in: https://github.com/Kong/kubernetes-ingress-controller/blob/main/CHANGELOG.md#220
#4157
> kic: add Gateway API HTTPRoute traffic splitting

- src/deck/3.0-upgrade.md
Adjusting description for decK diff, sync, and validate command behavior in 3.0.
DOCU-2595
Previously the doc had two different descriptions for self-managed vs Konnect control planes for the sync, diff, and validate commands. The Konnect description was incomplete + misleading, so I fixed that, then tested all of the documented scenarios on Konnect and on a self-managed gateway instance and came to the conclusion that the control plane type (konnect vs self-managed) doesn't actually matter here. What makes the difference is the format version in the config file and the validity of the routes.
Netlify
> [DOCU-2595] decK upgrade guide: correct descriptions for sync, diff, validate

- src/gateway/kong-enterprise/plugin-ordering/get-started.md
- src/kubernetes-ingress-controller/references/custom-resources.md
Adds a reference and example for configuring plugin ordering using KIC.
#4654 
Waiting for Netlify to confirm formatting.
[test.txt](https://github.com/Kong/docs.konghq.com/files/9891024/test.txt) is a basic test to confirm that the example is accepted and results in a plugin with ordering configuration.
> doc(kic) add plugin ordering config

- app/_layouts/default.html
- gulpfile.js
- package-lock.json
- package.json
Make Segment events triggering more reliable
It previously used a 500ms sleep before triggering a page. We now loop every 30ms until analytics.js is loaded
Will only work in prod due to CORS rules. I've seen the request being attempted and failing in dev tools locally
> Make Segment events more reliable

- app/gateway/2.6.x/configure/auth/rbac/index.md
- app/gateway/2.7.x/configure/auth/rbac/index.md
- app/gateway/2.8.x/configure/auth/rbac/index.md
- src/gateway/kong-manager/auth/rbac/index.md
This pull request adds a _How RBAC rules work in Kong_ section for `2.6.x`, `2.7.x`, `2.8.x`, and `3.0.x`.
This clarifies how RBAC rules work in Kong and provides references for previously implicit concepts within the role-based access control.
[FTI-4295](https://konghq.atlassian.net/browse/FTI-4295) [FTI-2581](https://konghq.atlassian.net/browse/FTI-2581)
> fix(kong-manager): add how RBAC rules work in Kong section

- app/_data/kong_versions.yml
- app/gateway/changelog.md
Changelog for 3.0.1.0 and 3.0.1 based on committed eng ticket list.
Planned 3.0.1.0 patch release.
https://konghq.atlassian.net/browse/DOCU-2619
https://deploy-preview-4643--kongdocs.netlify.app/gateway/changelog/
> Release: Changelog for Gateway 3.0.1.0

- gulpfile.js
- jekyll-dev.yml
Set the `site.links.web` to the corresponding url when running it locally and in preview apps, i.e.:
* `http://localhost:3000` for localhost
* `process.env.DEPLOY_PRIME_URL` for preview apps 
Some [links](https://github.com/Kong/docs.konghq.com/search?q=site.links.web) use the `site.links.web` config, which was hardcoded to production's url making it impossible to test changes before releasing them.
Make contributors' life easier by allowing them to test changes locally and in review apps by setting the right url based on the `environment`. 
Visit https://deploy-preview-4701--kongdocs.netlify.app//kubernetes-ingress-controller/latest/guides/using-gateway-api/#traffic-splitting-with-httproute and verify that file in the code snippet can be downloaded.
> Set links web url accordingly

- .github/workflows/sync-submodules.yml
Adds a GitHub Action to update the Kuma submodule automatically
Makes updating the submodule as easy as clicking a button!
This needs to be on `main` to test. I've tested the action locally using these parameters and it worked as expected
> Add automatic submodule update workflow

- src/mesh/features/rbac.md
Signed-off-by: Marcin Skalski [marcin.skalski@konghq.com](mailto:marcin.skalski@konghq.com)
Summary
Extend Kong Mesh docs with RBAC to include usage of new policies introduces in 2.0 version
Reason
https://github.com/Kong/kong-mesh/issues/1874
> docs(mesh) Add docs for mesh RBAC for new policies

- app/_includes/md/mesh/install-universal-quickstart.md
- app/_includes/md/mesh/install-universal-run.md
- src/mesh/features/acmpca.md
- src/mesh/features/cert-manager.md
- src/mesh/features/kds-auth.md
- src/mesh/features/opa.md
- src/mesh/features/vault.md
- src/mesh/gettingstarted.md
- src/mesh/index.md
- src/mesh/installation/docker.md
- src/mesh/installation/ecs.md
- src/mesh/installation/helm.md
- src/mesh/installation/kubernetes.md
- src/mesh/installation/openshift.md
- src/mesh/installation/windows.md
Versioning links for single-sourced content.
We're getting broken links on versions pre-2.0.
Netlify - check the links on 2.0.x and an earlier version. 2.0.x should go to the page on docs.konghq.com, while 1.9.x and earlier will go to the Kuma site.
> Version links to Kuma

- app/_data/tables/os_support.yml
Specify the minor version of RHEL 7 we supporting. Associated PR [#4594](https://github.com/Kong/docs.konghq.com/pull/4594) and [#4649](https://github.com/Kong/docs.konghq.com/pull/4649)
[FTI-4457](https://konghq.atlassian.net/browse/FTI-4457) [DOCU-2489](https://konghq.atlassian.net/browse/DOCU-2489)
> docs(compat) specify the minor version of RHEL 7

- jekyll-dev.yml
- jekyll.yml
Made a variable for the the default namespace so that "kuma-system" is replaced with "kong-mesh-system".
https://github.com/kumahq/kuma-website/pull/1122
Locally, "kuma-system" wasn't being replaced with "kong-mesh-system". I'm hoping it displays correctly in the Netlify preview. Or it might be a submodule issue?
To test, look at /mesh/latest/deployments/multi-zone/ to see if "kuma-system" was replaced with "kong-mesh-system".
> Add default namespace variable

- app/_data/docs_nav_mesh_2.0.x.yml
- app/_includes/md/mesh/install-universal-run.md
- app/_redirects
- src/mesh/features/kds-auth.md
- src/mesh/features/rbac.md
- src/mesh/index.md
- src/mesh/installation/kubernetes.md
Removed two topics copied from Kuma:
*  `/.repos/kuma/app/docs/dev/introduction/what-is-kuma/`: This topic is an intro to Kuma specifically. Our intro to Kong Mesh already covers everything + more. The only thing I grabbed from this topic was the multizone example deployment diagram.
* `/.repos/kuma/app/docs/dev/introduction/enterprise/`: This is basically an advertisement for Kong Mesh from the Kuma perspective, and doesn't make sense to leave in the nav.
Other stuff:
* Fixed Red Hat link that was accidentally named Debian
* Fixed links
* Added some redirects (need to test with latest)
QA for Kong Mesh 2.0
Netlify
> Kong Mesh QA: Intro, getting started, and install

- src/gateway/reference/router-expressions-language.md
Add table headers in String Transformations section of router expression reference page
fixes #4695.
https://deploy-preview-4696--kongdocs.netlify.app/gateway/latest/reference/router-expressions-language/
> fix: add table headers in String Transformations section

- app/_data/docs_nav_mesh_2.0.x.yml
- app/_redirects
- OPA Policy support in sidebar needed a space between OPA and policy
- Found a few links to just "/policies", so I redirected them.
- /mesh/2.0.x/policies/protocol-support-in-kuma was a 404 on the new MeshTrace (beta) page and I don't know why it wasn't transformed to "kong-mesh". I just added a temp redirect.
- Found a 404 to a "Policy matching" page that was unlisted in Kuma, so I added it to the nav in Mesh. 
Result of QA 
- Test redirects
- From the MeshTrace (beta) page, test the link in "You must explicitly specify the protocol for each service and data plane proxy you want to enable tracing for." and "If you don’t understand this table you should read matching docs."
> QA for Policies in Mesh 2.0

- gulpfile.js
The previous code overrode the whole `links` config breaking the `download` links.
This replaces the link inline so everything else keeps working as expected. 
* [Download links](https://deploy-preview-4720--kongdocs.netlify.app/mesh/latest/installation/kubernetes/#1-download-kong-mesh) work 
* the url for the file in [this code snippet](https://deploy-preview-4720--kongdocs.netlify.app/kubernetes-ingress-controller/latest/guides/using-gateway-api/#traffic-splitting-with-httproute) work
> Replace web url inline instead of appending the config to the file

- app/_data/docs_nav_mesh_2.0.x.yml
Update the Kuma src file paths in the Mesh 2.0 nav to point at the 2.0.x folder.
We are currently pointing to the /dev folder in the nav and that folder will change into the /2.0.x folder when the release happens. 
**NOTE:** This won't work until after the Mesh team has turned the /dev folder into the /2.0.x folder.
> Update 2.0 Mesh nav to point to the correct folder

- .github/workflows/linting.yml
- src/gateway/kong-enterprise/index.md
Add OIDC to enterprise plugins section on overview page.
OIDC is our most popular/most used Enterprise plugin, so it should be mentioned in the Enterprise overview doc.
Netlify
> Add OIDC to list of sample enterprise plugins

- app/_includes/md/support-policy.md
- src/gateway/support-policy.md
There are 2 sections of Version support for Kong Gateway (Enterprise), one showing up to 2.8.x one up to 3.0.x
* Removed extra table
* Updated the table to include 3.0.x
> [fix] Support policy table issue

- app/_data/docs_nav_mesh_2.0.x.yml
Charly let me know that we were missing the following two docs in the Mesh nav that currently exist in the Kuma nav:
- https://kuma.io/docs/2.0.x/policies/meshaccesslog/
- https://kuma.io/docs/2.0.x/policies/meshtrafficpermission/
I added these docs back in and double checked that no other docs were missing from the nav.
Docs existed in Kuma nav but not Mesh nav.
Check that the following pages work in the Netlify preview:
- /policies/meshaccesslog/
- /policies/meshtrafficpermission/
> Add missing beta docs to Policies section

- .github/styles/kongplugins/plugin-ignore.txt
- app/_hub/kong-inc/vault-auth/_index.md
Update user facing documentation for the vault-auth plugin new functionality (support for kv engine v2), coming with Kong EE 3.1.0
https://konghq.atlassian.net/browse/FT-2904
[DOCU-2772]
[DOCU-2772]: https://konghq.atlassian.net/browse/DOCU-2772?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(vault-auth): secrets engine v2 compatibility

- app/konnect/dev-portal/applications/enable-app-reg.md
- app/konnect/runtime-manager/runtime-groups/index.md
This describes an update to dev portal's app registration. It was previously available only in the `default` runtime group. App registration is now available as a `Tech Preview` in all runtime groups. However, for compatibility with Kong Gateway's < 3.0, there are some differences with how it is applied, depending on the runtime group.
https://konghq.atlassian.net/browse/TDX-2195
Application registration is opening support for any runtime group. Only compatible with Kong Gateway versions >= 3.0
> [TDX-2195] Dev portal app reg with multi-runtime group support

- src/deck/reference/deck_diff.md
- src/deck/reference/deck_konnect_diff.md
- src/deck/reference/deck_konnect_sync.md
- src/deck/reference/deck_reset.md
- src/deck/reference/deck_sync.md
Add flag for masking DECK_ environment variable values at diff outputs.
https://github.com/Kong/deck/pull/463 is going into 1.16.
Netlify
This is a generated doc.
> decK: add env variable masking flag

- src/gateway/kong-enterprise/secrets-management/backends/aws-sm.md
- src/gateway/kong-enterprise/secrets-management/how-to/aws-secrets-manager.md
Adding `AWS_SESSION_TOKEN=<token>` to AWS vault backend config.
Missing token value noted in Slack: https://kongstrong.slack.com/archives/C037510LW2X/p1668013808779929?thread_ts=1667993877.584539&cid=C037510LW2X
Netlify
> Add missing config parameter for AWS secrets vault

- app/_data/kong_versions.yml
Prep branch for decK patch release.
Quick followup fix to 1.16 for an issue with `deck ping`: https://github.com/Kong/deck/commit/4ee5ad69335abe1c14a1a5fb4f3d72250ea519e1
Netlify; [installation doc](https://deploy-preview-4752--kongdocs.netlify.app/deck/latest/installation/) should say 1.16.1
> chore: bump decK patch version

- .github/styles/kongplugins/auto-ignore.txt
- app/_hub/kong-inc/rate-limiting-advanced/_index.md
Adds a new option `config.disable_penalty` to the rate-limiting-advaned plugin. 
If set to `true`, then won't count the denied requests (status = `429`).
Related PR [Kong/kong-ee#3762](https://github.com/Kong/kong-ee/pull/3762)
FTI-3281
> [FTI-3281] add an option `config.disable_penalty` to rate-limiting-advanced plugin

- .github/styles/kongplugins/auto-ignore.txt
- .github/styles/kongplugins/dictionary.txt
- app/_hub/kong-inc/mtls-auth/_index.md
Adds a new option `config.send_ca_dn` to the mtls-auth plugin. 
The new option will enable the ability to send ca dn in the TLS handshake message.
Related PR: [Kong/kong-ee#3890](https://github.com/Kong/kong-ee/pull/3890)
FTI-4430
> [FTI-4430] mtls-auth plugin supports sending ca dn in ssl handshake essage

- src/gateway/index.md
Changing CTA link to HTTPS, which Kaitlyn confirms is correct next step.
Field pointing to HTTP is flagged as insecure
Field pointing to HTTPS should not be flagged as insecure
> CTA to HTTPS

- app/_assets/javascripts/app.js
- app/_assets/stylesheets/cta-form.less
- app/_assets/stylesheets/index.less
- src/gateway/index.md
* Moving styling out of doc page and into stylesheet as a better practice
* Tweak styling for better UX (smaller screens + better contrast)
Before:
After:
Follow-up to https://github.com/Kong/docs.konghq.com/pull/4534 based on review.
Netlify
> Clean up CTA form styling and move to stylesheet

- app/gateway/2.6.x/reference/configuration.md
- app/gateway/2.7.x/reference/configuration.md
- app/gateway/2.8.x/reference/configuration.md
- src/gateway/reference/configuration.md
This updates the URL in the doc, the corresponding PR to update the config is here: 
https://github.com/Kong/kong-ee/pull/4003
This PR does not depend on that one to merge.
> [fix] remove empty achor link from URL

- src/gateway/kong-enterprise/plugin-ordering/index.md
This PR removes the `Kong Manager` section in plugin ordering docs.
Kong Manager 3.1 will support plugin ordering configuration, rendering the removed section obsolete.
Related links:
- https://konghq.atlassian.net/browse/INTF-2878
- https://github.com/Kong/kong-admin/pull/1955
Docs version 3.0 and prior should still keep this section.
> chore(kong-gateway): remove Kong Manager tip in plugin ordering

- app/_hub/kong-inc/basic-auth/_index.md
- app/_hub/kong-inc/file-log/_index.md
- app/_hub/kong-inc/hmac-auth/_index.md
- app/_hub/kong-inc/http-log/_index.md
- app/_hub/kong-inc/kafka-log/_index.md
- app/_hub/kong-inc/key-auth-enc/_index.md
- app/_hub/kong-inc/key-auth/_index.md
- app/_hub/kong-inc/ldap-auth-advanced/_index.md
- app/_hub/kong-inc/ldap-auth/_index.md
- app/_hub/kong-inc/loggly/_index.md
- app/_hub/kong-inc/oauth2/_index.md
- app/_hub/kong-inc/serverless-functions/_index.md
- app/_hub/kong-inc/syslog/_index.md
- app/_hub/kong-inc/tcp-log/_index.md
- app/_hub/kong-inc/udp-log/_index.md
This adds WebSocket protocols (`ws` and `wss`) to all the plugins that support them. All of the auth-related plugins have been supported since 3.0. The logging plugins are newly-supported in 3.1.
FT-3544
View the plugin pages and check the `Compatible protocols` section in the bottom right.
> docs(plugins): add WebSocket protocols to supported plugins

- app/_hub/kong-inc/request-transformer/_index.md
Fix the description of the config `config.add.querystring` in the [request-transformer](https://docs.konghq.com/hub/kong-inc/request-transformer/) docs page
None
None
> Fix typo in `config.add.querystring` description

- app/mesh/installer.sh
Changes the `REPO_PREFIX` argument to `REPO` following changes to the kuma.io/installer.sh changes made in https://github.com/kumahq/kuma-website/pull/1149.
Signed-off-by: Philipp Rudloff <philipp.rudloff@konghq.com>
Mirror changes introduced in https://github.com/kumahq/kuma-website/pull/1149.
Can be verified by running
```sh
curl https://deploy-preview-4770--kongdocs.netlify.app/mesh/installer.sh | sh -
```
> chore: uses REPO argument in installer.sh script

- tools/broken-link-checker/lib/src-to-urls.js
Fix broken link checker for items with a `src` entry
Builds are currently failing
N/A
> Fix broken link checker

- app/_hub/SmartParkingTechnology/google-logging/_index.md
- app/_hub/inspur/apig-request-transformer/_index.md
- app/_hub/inspur/apig-response-transform/_index.md
- app/_hub/kong-inc/basic-auth/_index.md
- app/_hub/kong-inc/file-log/_index.md
- app/_hub/kong-inc/hmac-auth/_index.md
- app/_hub/kong-inc/http-log/_index.md
- app/_hub/kong-inc/kafka-log/_index.md
- app/_hub/kong-inc/key-auth-enc/_index.md
- app/_hub/kong-inc/key-auth/_index.md
- app/_hub/kong-inc/ldap-auth-advanced/_index.md
- app/_hub/kong-inc/ldap-auth/_index.md
- app/_hub/kong-inc/loggly/_index.md
- app/_hub/kong-inc/oauth2/_index.md
- app/_hub/kong-inc/serverless-functions/_index.md
- app/_hub/kong-inc/syslog/_index.md
- app/_hub/kong-inc/tcp-log/_index.md
- app/_hub/kong-inc/udp-log/_index.md
- app/_hub/kong-inc/websocket-size-limit/_index.md
- app/_hub/kong-inc/websocket-validator/_index.md
- app/_hub/qnap/api-transformer/_index.md
- app/_hub/reedelk/reedelk-transformer/_index.md
- app/_hub/seifchen/kong-path-allow/_index.md
- app/_hub/yesinteractive/kong-jwt2header/_index.md
- app/_hub/yesinteractive/kong-log-google/_index.md
Updating missed plugins with the new protocols formatting and setting `minimum_version` for the `ws` and `wss` protocols.
3.1 release branch build is failing because of some plugin's formatting for the protocols values. Updating all plugins to use the new formatting to avoid further errors.
I'm fairly certain that the main culprit is the Kafka Log plugin, which previously didn't have a protocols key. Field got added in 3.1 with the old formatting.
By the time I'd figured that out, I'd already fixed it in a bunch of other places.
Build should succeed.
> Plugin protocols: fix errors, use new formatting, and set min versions

- README.md
jekyll expects files in src/.repos/kuma/* which are coming from a submodule.
> docs(readme): add submodule update instructions

- .github/styles/kong/auto-ignore.txt
- src/kubernetes-ingress-controller/references/prometheus.md
- src/kubernetes-ingress-controller/troubleshooting.md
It adds a section on troubleshooting translation failures in Kubernetes Ingress Controller. 
Part of [#3097](https://github.com/Kong/kubernetes-ingress-controller/issues/3097).
The added section won't be visible now as it's relevant only for KIC >= v2.8.0 which is to be released soon. I tested that by manually changing the conditional to v2.7.0. 
https://deploy-preview-4779--kongdocs.netlify.app/
> kic: add translation failures troubleshooting section

- src/gateway/install/linux/ubuntu.md
XR: https://github.com/Kong/docs.konghq.com/pull/4769
Added the uninstall instructions for OSS and EE. 
https://deploy-preview-4781--kongdocs.netlify.app/gateway/latest/install/linux/ubuntu/
> Add uninstall instructions to Ubuntu

- .github/styles/kongplugins/plugin-ignore.txt
- app/_hub/kong-inc/opa/_index.md
Add a new option `include_uri_captures_in_opa_input` to the OPA plugin.
The new option will enable the ability to make regex capture groups included as the input to OPA
Realted PR: https://github.com/Kong/kong-ee/pull/3270
https://github.com/Kong/kong-ee/pull/3953/files
https://konghq.atlassian.net/browse/FTI-3323
> [FTI-3323]add include_uri_captures_in_opa_input option to OPA plugin

- app/_hub/_init/my-extension/_index.md
- app/_hub/_init/my-extension/versions.yml
* Added list of possible protocols
* Removed "version" field from template
* Added sample version.yml file
Need to update for single-sourced plugins.
Draft for now, in case we resolve the `delegate_releases: false` release incrementation support.
Won't show up in netlify build, review file in PR only.
~Attempting to skip netlify build, will see if it works.~ Nope.
> Plugin template: Update and add sample versions file

- app/_assets/javascripts/ab-test.js
- app/_includes/nav-v2.html
- gulpfile.js
- package-lock.json
- package.json
Add support for A/B testing the top CTA
To understand what is resonating with visitors
Load the review app and you'll get either the incubator or sales demo CTA. This is randomly selected every 24h.
To see the other CTA, change the `top_cta` cookie to contain either `incubator` or `sales_demo` using developer tools
> Add a/b test support for the top CTA

- app/_hub/kong-inc/jq/versions.yml
- app/_hub/kong-inc/kong-terraform-aws/_index.md
- app/_hub/kong-inc/mocking/versions.yml
- app/_hub/kong-inc/opa/versions.yml
- app/_hub/kong-inc/opentelemetry/_index.md
- app/_hub/kong-inc/opentelemetry/versions.yml
- app/_hub/kong-inc/tls-handshake-modifier/_index.md
- app/_hub/kong-inc/tls-handshake-modifier/versions.yml
- app/_hub/kong-inc/tls-metadata-headers/_index.md
- app/_hub/kong-inc/tls-metadata-headers/versions.yml
- app/_hub/kong-inc/websocket-size-limit/_index.md
- app/_hub/kong-inc/websocket-size-limit/versions.yml
- app/_hub/kong-inc/websocket-validator/_index.md
- app/_hub/kong-inc/websocket-validator/versions.yml
Bumping plugin versions for any plugins not using `delegate_versions: true`.
3.1 release prep.
Netlify.
Check some of the bumped plugins:
https://deploy-preview-4786--kongdocs.netlify.app/hub/kong-inc/mocking/
https://deploy-preview-4786--kongdocs.netlify.app/hub/kong-inc/websocket-size-limit/
https://deploy-preview-4786--kongdocs.netlify.app/hub/kong-inc/tls-metadata-headers/
> chore: Bump plugin versions for 3.1

- src/gateway/admin-api/consumer-groups/reference.md
- src/gateway/kong-enterprise/consumer-groups/index.md
We'd like an API to support deleting the current consumer group configurations.
[] FT-3564(https://konghq.atlassian.net/browse/FT-3564)
Test by using curl -i -X DELETE http://{HOSTNAME}:8001/consumer_groups/JL/overrides/plugins/rate-limiting-advanced
> docs(consumer_group): add delete api for consumer group configuration

- app/_data/kong_versions.yml
- app/gateway/changelog.md
Changelog and version bump for gateway 2.8.2.1.
There are a few items that I had to move from the 2.8.2.0 changelog into 2.8.2.1. These items apparently never made it into the 2.8.2.0 release, but there was no communication about this. The tickets in question also currently have no information about how or why this happened - trying to figure it out in https://kongstrong.slack.com/archives/C02GZ0CGJNT/p1668641928341129. 
[DOCU-2633](https://konghq.atlassian.net/browse/DOCU-2633)
https://deploy-preview-4784--kongdocs.netlify.app/gateway/changelog/#2821
> [DOCU-2633] Release: Gateway 2.8.2.1

- app/konnect/network.md
Document Konnect's static IP list endpoint for different Konnect geos
adds https://ip-addresses.origin.konghq.com/ip-addresses.json for the list of IPs, and https://ip-addresses.origin.konghq.com/rss for the rss feed with updates.
> DOCU-2809 

- app/gateway/2.8.x/plan-and-deploy/security/secrets-management/backends/hashicorp-vault.md
- src/gateway/kong-enterprise/secrets-management/backends/hashicorp-vault.md
Fixing HCV Vault `mount` name in the Response object to be consistent with the name in the Request object
> Fix HCV mount name in Result object

- app/_plugins/generators/plugin_single_source/kong_versions.rb
- app/_plugins/generators/plugin_single_source/plugin/versioned.rb
- spec/app/_plugins/generators/plugin_single_source/kong_versions_spec.rb
Update KongVersions to fetch the file relative to the site's source
It was making the specs fail because it was using the file under app/_data instead of the fixtures.
Fixes https://github.com/Kong/docs.konghq.com/pull/4814
> Update KongVersions to fetch the file relative to the site's source

- app/_data/tables/plugin_index.yml
- app/_hub/kong-inc/app-dynamics/_index.md
- app/_hub/kong-inc/app-dynamics/versions.yml
- app/_hub/kong-inc/oas-validation/versions.yml
- app/_hub/kong-inc/saml/versions.yml
- app/_hub/kong-inc/xml-threat-protection/versions.yml
* Following the changes made in https://github.com/Kong/docs.konghq.com/pull/4810, setting the `minimum_version` for plugins introduced in 3.1.x
* Adding OAS validation and XML threat protection plugins to compatibility table
* Minor fixes to table: moving Mocking plugin up for alphabetical order, and moving AppDynamics from the Traffic category to the Analytics and Monitoring category
* Minor edits to AppDynamics plugin: 
* Variables can't be used in plugin doc front matter (yaml section)
* Duplicate note
* Removed some "please"s
See above.
Netlify.
> Update plugin versions and compatibility table

- app/_hub/_init/my-extension/versions.yml
Adding a comment to describe `minimum_version`.
To avoid confusion from plugin authors.
N/A; attempting to skip netlify.
> Clarify minimum_version in plugin template [skip ci]

- app/gateway/changelog.md
- src/gateway/kong-manager/enable.md
Edited the `admin_gui_url` examples with the new root path for Kong Manager. Also added an entry to the changelog.
DOCU-2779
Go to:
- /gateway/latest/kong-manager/enable
- The release notes
> [DOCU-2779] Allow root path to be specified for Kong Manager

- app/_data/tables/features/mesh.yml
Removes the 'operator' feature in the mesh overview
Bug / incorrect information
> (docs)mesh remove operator feature

- app/_data/docs_nav_gateway_3.1.x.yml
- app/_redirects
- src/gateway/reference/key-management.md
Add a new reference for `key-management` that describes how `keys` and `key-sets` are used alongside examples.
This is an OSS feature.
https://konghq.atlassian.net/browse/DOCU-2786
Things to do before merging:
> add docs for keys and key-sets entities

- app/_data/docs_nav_gateway_3.0.x.yml
- app/_data/docs_nav_gateway_3.1.x.yml
- app/_redirects
- src/gateway/production/logging.md
- src/gateway/production/logging/customize-gateway-logs.md
- src/gateway/production/logging/log-reference.md
- src/gateway/production/logging/update-log-level-dynamically.md
https://konghq.atlassian.net/browse/DOCU-2751
Documents new feature and covers the following cases:
- ~~The user should not leave any node with debug log level for too long otherwise it would be too verbose, could fill the disk quickly~~
- ~~Exercise the GET endpoint often to get current log level~~
- ~~The root (/) endpoint will show current, up-to-date information about the log level considering the ones changed by the API proposed in this document~~
- Traditional nodes and CP nodes
- ~~Change log level of individual traditional node~~
- ~~Broadcast log level change to all traditional nodes~~
- ~~The new APIs can be RBAC protected~~
- ~~Changes to the API can be reflected in the audit logs~~
-  ~~It’s currently not possible to change the log level of DP and DB-less nodes~~
- …
> [docu-2751] Dynamic log levels

- app/_hub/kong-inc/jwe-decrypt/_index.md
Fixed a broken link to the new Key management page that was on the JWE decrypt plugin doc.
The link had `{{page.kong_version}}` in it, but it looks like plugin docs only use `/latest` links?
Go to the JWE decrypt plugin page and test out the link to the Key Management page. The link should work, but I just wanted to verify that using `/latest` is correct.
> Fix link to key management page on JWE Decrypt plugin

- src/gateway/kong-enterprise/plugin-ordering/get-started.md
- src/gateway/kong-enterprise/plugin-ordering/index.md
Added instructions for how to configure plugin ordering with Kong Manager. This is for Gateway 3.1. 
DOCU-2783
Go to: KM tabs in `/gateway/latest/kong-enterprise/plugin-ordering/get-started/`
Questions for writer reviewers:
- I originally created a "Plugin Ordering" subsection in the Kong Manager section of the docs for this info, but I was mostly copying what was in the Kong Enterprise "Plugin Ordering" subsection, so I figured I'd just add it there. Does this work, or should this live in Kong Manager? I thought maybe at one point we ripped out KM instructions during 3.0 and moved them to the KM section.
- I know this is documenting the UI, but I think it's okay here because it's focused on teaching the user how plugin ordering works with an example vs. generic plugin ordering …
> [DOCU-2783] Plugin ordering in Kong Manager

- src/gateway/plugin-development/custom-logic.md
Adding new plugins to plugin priority table in custom plugin dev doc.
Also checked the priorities of all existing plugins; no changes have happened in 3.1.
Guide for checking plugin priority [here](https://konghq.atlassian.net/wiki/spaces/KD/pages/2673541151/Check+plugin+priority+list). Instead of running 3.1 though, I just pulled the repo and searched through the `plugins` and `plugins-ee` directories, then compared priorities with existing table.
New plugins.
Netlify. Note that these changes are in the Enterprise tab, not the OSS/Free tab.
https://deploy-preview-4833--kongdocs.netlify.app/gateway/latest/plugin-development/custom-logic/#kong-plugins
> chore: Plugin priority 3.1 updates

- src/deck/installation.md
Add Deck Windows installation instructions using CMD.
As of [Windows 10 Build 17063](https://learn.microsoft.com/en-us/virtualization/community/team-blog/2017/20171219-tar-and-curl-come-to-windows), tar and curl are now packaged by default in the OS.
Used PowerShell to add to environment path since SETX has a 1024 characters limit and could truncate the values.
Make Deck setup on Windows easier
```
curl -sL https://github.com/kong/deck/releases/download/v1.15.1/deck_1.15.1_windows_amd64.tar.gz -o deck.tar.gz
mkdir deck
tar -xvzf deck.tar.gz -C deck
```
The following command can be used to add the directory to the PATH. If this is not desired can be removed.
`powershell -command "[Environment]::SetEnvironmentVariable('Path', [Environment]::GetEnvironmentVariable('Path', 'User') + …
> Add Deck Windows installation instructions

- autodoc-conf-ee/data.lua
- src/gateway/reference/configuration.md
Generating the configuration reference doc and setting `{% if_version %}` tags for anything new.
Note that `cluster_telemetry_server_name` isn't new with this release, it was just missing from the doc previously, so it doesn't need the tags.
Chore PR for release.
Netlify
> chore: Config reference for 3.1

- app/konnect/compatibility.md
- app/konnect/updates.md
Konnect users can now use the Kong Gateway 3.1 with Konnect. 
https://konghq.atlassian.net/browse/DOCU-2777
This needs to be cherry-picked into release 3.1
> [docu-2777] Konnect release notes for GW 3.1

- app/gateway/changelog.md
update changelog to reflect the fix the timer error in Core was not part of 2.8.2.1 and instead is releasing as this patch. 
DOCU-2818
> DOCU-2818 changelog 2.8.2.2

- src/gateway/kong-enterprise/fips-support.md
Adding ubuntu 22.04 to list of supported packages for fips. 
The original PR aims to better structure the install docs to include FIPS packages as an option on the install pages. Not going with this approach as we need to keep FIPS separate for now for legal reasons. (fyi @gszr)
Based on https://github.com/Kong/docs.konghq.com/pull/4851/files, which was working with an older version of the doc.
Netlify
> FIPS support for ubuntu 22.04

- app/_data/docs_nav_gateway_3.1.x.yml
- src/gateway/production/networking/cp-dp-proxy.md
Doc for setting up a forward proxy connection between CP and DP.
I can't really test this, so I can't verify that this is correct. Need some SME help.
Outstanding questions @dndx:
* From design doc: "Customers need to ensure their proxy does not MITM or mutate the certificate used by Kong DP when connecting to CP" - How do you verify this? 
* What special info do we need for Konnect here?
* From design doc: "We should document roughly how many connections each Kong DP will open to the CP, so that user knows how much proxy servers are needed to support a given number of Kong deployments." - how would you estimate this number?
https://konghq.atlassian.net/browse/DOCU-2757
https://deploy-preview-4846--kongdocs.netlify.app/gateway/latest/production/networking/cp-dp-proxy/
> [DOCU-2757] CP/DP forward proxy config

- app/_data/kong_versions.yml
- app/gateway/changelog.md
* Bump release version
* Update release date
* expand description of timer issues based on ticket + PRs
Comment in https://github.com/Kong/docs.konghq.com/pull/4849#discussion_r1037458945.
Release date has changed and version needs bumping.
> Gateway 2.8.2.2: Expand the changelog entry for the timer fix and bump 2.8.x version

- .github/styles/kongplugins/plugin-ignore.txt
- app/_hub/kong-inc/aws-lambda/_index.md
- app/_hub/kong-inc/basic-auth/_index.md
- app/_hub/kong-inc/hmac-auth/_index.md
- app/_hub/kong-inc/jwt/_index.md
- app/_hub/kong-inc/key-auth-enc/_index.md
- app/_hub/kong-inc/key-auth/_index.md
- app/_hub/kong-inc/ldap-auth-advanced/_index.md
- app/_hub/kong-inc/ldap-auth/_index.md
- app/_hub/kong-inc/mtls-auth/_index.md
- app/_hub/kong-inc/oauth2-introspection/_index.md
- app/_hub/kong-inc/oauth2/_index.md
- app/_hub/kong-inc/openid-connect/_index.md
- app/_hub/kong-inc/opentelemetry/_index.md
- app/_hub/kong-inc/rate-limiting/_index.md
- app/_hub/kong-inc/route-transformer-advanced/_index.md
- app/_hub/kong-inc/session/_index.md
- app/_hub/kong-inc/vault-auth/_index.md
- app/_hub/kong-inc/zipkin/_index.md
- app/gateway/changelog.md
Documenting the following plugin updates from 3.1 changelog:
- Zipkin: Added response_header_for_traceid field in Zipkin plugin.
The plugin will set the corresponding header in the response
if the field is specified with a string value.
- Rate Limiting: The HTTP status code and response body for rate-limited
requests can now be customized. 
- AWS Lambda: Added requestContext field into awsgateway_compatible input data
- Authentication plugins: The anonymous field can now be configured as the username of the consumer.
This field allows you to configure a string to use as an “anonymous” consumer if authentication fails.
- _fixed the min and max versions to display the anonymous parameter correctly_
- Session: Added new config `cookie_persistent`, which allows the browser to persist
cookies …
> [DOCU-2815] 3.1 Plugin updates

- app/_data/docs_nav_kic_2.7.x.yml
- src/kubernetes-ingress-controller/references/supported-router-flavors.md
Add compatibility table to show which kong router flavors are supported in KIC.
fixes [kuberneres-ingress-controller#3187](https://github.com/Kong/kubernetes-ingress-controller/issues/3187)
https://deploy-preview-4834--kongdocs.netlify.app/kubernetes-ingress-controller/latest/references/supported-router-flavors/
Kong 3.0.x `traditional_compatible` router is not fully supported in KIC because `traditional_compatible` router does not support some routes supported in `traditional` router. How should we mark it in the compatibility table?
- use a :heavy_check_mark: and add annotations to tell the incompatibilities
- use a :negative_squared_cross_mark: and add annotations to tell that most cases are supported (now this is used)
- use a symbol other than these two, or tell by text such as `Not …
> docs(kic): add compatibilities of router flavors of Kong

- src/gateway/upgrade.md
Corrected references to "upcoming 2.8.2 release" to ensure it's clear that the 2.8.2 release is already out and is the minimum requirement for blue-green upgrade styles.
The original notes imply that 2.8.2 is still to be released which is no longer accurate. Correcting the verbiage to reflect that.
> Updated references to 2.8.2

- src/gateway/kong-enterprise/secrets-management/backends/hashicorp-vault.md
Added three missing config options to the Hashicorp vault doc.
DOCU-2825
- View /gateway/latest/kong-enterprise/secrets-management/backends/hashicorp-vault/#vault-configuration-options
I put it in the first table in that section, not sure if that's the right place for it or not.
> [DOCU-2825] 3.1 fast-follow: HashiCorp vault config parameters

- app/gateway/changelog.md
Removed the mention of the privileged worker from the 3.1 release notes. 
The changes for this were reverted due to performance issues, but will be included in a later release.
View the Gateway changelog.
> Remove privileged worker from 3.1

- app/_data/tables/os_support.yml
- app/gateway/changelog.md
Added Amazon Linux 2022 to the changelog and table of supported OS.
DOCU-2827
- View the changelog
- View /gateway/latest/os-support/ to see if Amazon Linux 2022 is listed there
> [DOCU-2827] 3.1 fast-follow: Amazon Linux 2022 support

- app/gateway/changelog.md
Adding known limitation to Dynamic Logs
DOCU-2830 
Added Known limitation section ahead of Fixes
> DOCU-2830 Dynamic Log known issue

- app/_data/docs_nav_gateway_3.1.x.yml
- app/_redirects
- app/gateway/changelog.md
- src/gateway/migrate-ce-to-ke.md
- src/gateway/upgrade-31x.md
Updated 3.1.x upgrade page. Added an upgrade path table per feedback. 
Upgrade instructions for 3.1.x are specific, so we needed a new page as well as a table that specifically calls out what the upgrade path is. 
- For the new upgrade page (/gateway/latest/upgrade), I added the upgrade path table and only left in 3.0.x to 3.1.x instructions. I figured it would be easier/simpler to link back to other versions for upgrading to 2.8.x or 3.0.x than to try to duplicate that content on this page. Does this work in your opinion?
- Is the upgrade path table I added accurate?
> DOCU-2823 3.1.x Upgrade doc

- src/kubernetes-ingress-controller/references/gateway-api-support.md
change docs for support of gateway API in KIC into changedog format to provide a clearer view of "what version of KIC supports what features in gateway API". 
fixes https://github.com/Kong/kubernetes-ingress-controller/issues/3215
possibly another way to fix https://github.com/Kong/kubernetes-ingress-controller/issues/3173
https://deploy-preview-4869--kongdocs.netlify.app/kubernetes-ingress-controller/latest/references/gateway-api-support/
> doc(kic) change support of GWAPI into changelog format

- README.md
- app/contributing/index.md
- app/contributing/style-guide.md
Added links to the new content templates in various contributing guides for docs.
Added links so that it's easier to locate our templates for contributors.
TBD
> Add links to content templates

- Makefile
- app/_includes/hub_cards.html
- app/_layouts/extension.html
- app/_plugins/generators/plugin_single_source/single_source_page.rb
- spec/app/_plugins/generators/plugin_single_source/single_source_page_spec.rb
- spec/app/_plugins/generators/plugin_single_source_generator_spec.rb
[Related Jira ticket](https://konghq.atlassian.net/browse/DOCU-2828)
Fixes plugin pages re-generation so that they are re-built whenever the corresponding source file changes or its layout/ includes does.
This also removes some conditionals and calculations done in the templates and does them in ruby.
Fixes `Edit this page` link on plugin pages that have a source file for specific versions, e.g. [this one](https://deploy-preview-4884--kongdocs.netlify.app//hub/kong-inc/jwt-signer/2.2.x.html)
Plugin pages were being re-generated on every file change, even if the change wasn't related.
* Modify one of the plugin source files and check that the corresponding page is re-built
* Modify the layout and check that all the plugin pages are re-built
* Modify any file that is not related and check …
> Fix plugins regeneration

- src/kubernetes-ingress-controller/guides/routing-by-header.md
- src/kubernetes-ingress-controller/guides/using-kongingress-resource.md
- src/kubernetes-ingress-controller/references/annotations.md
- src/kubernetes-ingress-controller/references/custom-resources.md
Add deprecation notices for KongIngress if the KIC version is 2.8 or higher.
Add a new guide for routing by header using annotations.
Add new 2.8 annotations to annotations reference.
Kind of in limbo before we have a 2.8 to add. The existing guides are fine to go in as-is, since the new content won't go live until there's a 2.8, but until then the header routing guide is an orphan--no nav content to add it to yet.
Related to https://github.com/Kong/kubernetes-ingress-controller/issues/3017 and https://github.com/Kong/kubernetes-ingress-controller/issues/3174
Waiting on Netlify for formatting validation.
Partial testing of the new header annotations guide against nightly.
> doc(kic) deprecate KongIngress for 2.8

- src/kubernetes-ingress-controller/references/gateway-api-support.md
Adds a note regarding GW API's UDPRoute not being fully supported in terms of port matching. 
Part of https://github.com/Kong/kubernetes-ingress-controller/issues/3019.
https://deploy-preview-4889--kongdocs.netlify.app/kubernetes-ingress-controller/latest/references/gateway-api-support/
> docs(kic): add port matching unsupported note for udp routes

- app/_hub/kong-inc/rate-limiting-advanced/_index.md
- app/_hub/kong-inc/rate-limiting/_index.md
`redis.username` cannot be *default*. The Doc may confuse customers.
Required by Redis 6+.
Fix _[FTI-4151]_
[FTI-4151]: https://konghq.atlassian.net/browse/FTI-4151?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs(redis) redis.username cannot be 'default'

- app/_data/docs_nav_gateway_3.0.x.yml
- app/_data/docs_nav_gateway_3.1.x.yml
- app/_redirects
- src/gateway/plugin-development/pluginserver/performance.md
Added "External plugin performance" back to the 3.0 and 3.1 nav. I just added this to the `release/gateway-3.1` branch because it would need to be added to the 3.1 nav anyways.
Looks like the page was unintentionally removed during our IA rework in 3.0. 
- View the page /plugin-development/pluginserver/performance
- See if the redirect works correctly
> Add "External plugin performance" back

- app/_hub/kong-inc/statsd/_index.md
Formerlly, this list was ordered, but it was not intended to be step by step instructions
It's a fix
Built docs locally and manually validated the new list
> StatsD Plugin: Converts ordered list to unordered list for non-instruction list

- jekyll.yml
When there is need to set some value which is kuma specific, it has to be prefixed with a `kuma.` prefix.
Bug found when testing (slack discussion).
Check if the ebpf installation instructions are correct at the bottom of `docs/2.0.x/networking/transparent-proxying/#transparent-proxy-with-ebpf-experimental`. The correct value should be:
```shell
kumactl install control-plane \
--set "kuma.experimental.ebpf.enabled=true" | kubectl apply -f-
```
> chore(mesh): add set_flag_values_prefix var

- app/_hub/kong-inc/aws-lambda/_index.md
This PR adds the documentation of the new `https` config field in the aws-lambda plugin, which supports scheme config on the lambda service API endpoint.
This will be a Kong Gateway 3.2 feature.
[FTI-4484](https://konghq.atlassian.net/browse/FTI-4484)
> docs(aws-lambda): add new `https` config field in aws-lambda plugin

- app/_hub/kong-inc/rate-limiting-advanced/_index.md
docs(rate-limiting-advanced): add suggestions on the namespace field in DB-less mode
This PR adds some suggestions to guide users manually setting `namespace` field in the rate-limiting-advanced plugin when using DB-less mode.
The `namespace` field is an auto field and will be generated every time when new plugins are created. In DB-less mode, when a new configuration is pushed to the gateway instance, new entities will be created, which will result in the change of `namespace` value, thus may cause precision loss on the rate-limit couting.
This fixes part of the problem in [FTI-4549](https://konghq.atlassian.net/browse/FTI-4549)
> docs(rate-limiting-advanced): add suggestions on namespace field in DB-less mode

- app/_src/kubernetes-ingress-controller/guides/cert-manager.md
- app/kubernetes-ingress-controller/2.1.x/guides/cert-manager.md
- app/kubernetes-ingress-controller/2.2.x/guides/cert-manager.md
Copy/paste didn't work as double quotes were used in the YAML manifest _and_ the `echo` command. Swap to single quotes in the manifest
Enable copy/paste for consumers
I deployed a `cert-manager` instance using the guide on a GKE cluster
> Fix quotes in cert-manager example for KIC

- .github/workflows/linting.yml
Related [Jira ticket](https://konghq.atlassian.net/browse/DOCU-2841)
Make `reviewdog` fail when an error was found.
Currently, `reviewdog` returns with an exit code of 0, even [if it finds errors.](https://github.com/reviewdog/reviewdog#exit-codes) This leads us to believe that the check passes, when in fact it does not. When we moved the docs from src/ to app/_src it [reported](https://github.com/Kong/docs.konghq.com/runs/10075252384) over 9k errors.
> Make `vale`, actually `reviewdog` fail on error

- app/_data/docs_nav_gateway_3.1.x.yml
This somehow got removed in 3.1 docs.
> fix(nav) add file access permissions link to nav

- app/_src/kubernetes-ingress-controller/references/version-compatibility.md
Adds missing compatibility matrix entries for KIC 2.8 and its supported Kubernetes and Istio versions.
Part of https://github.com/Kong/kubernetes-ingress-controller/issues/3199.
> kic: update compatibility matrix for release 2.8

- app/_src/kubernetes-ingress-controller/references/supported-router-flavors.md
update supported router flavors in KIC for KIC 2.8 and Kong 3.1.
fixes https://github.com/Kong/kubernetes-ingress-controller/issues/3290
https://deploy-preview-4949--kongdocs.netlify.app/kubernetes-ingress-controller/latest/references/supported-router-flavors/
> kic: update support of router flavors

- app/_src/kubernetes-ingress-controller/references/annotations.md
Add the introduction of missing annotation `ingress.kubernetes.io/force-ssl-redirect`.  
fixes https://github.com/Kong/kubernetes-ingress-controller/issues/3260.
https://deploy-preview-4943--kongdocs.netlify.app/kubernetes-ingress-controller/latest/references/annotations
> kic: add docs for annotation 

- app/_data/docs_nav_konnect.yml
There were too many changes to https://github.com/Kong/docs.konghq.com/pull/4898 which made 
https://github.com/Kong/docs.konghq.com/pull/4931 fall out of sync. This PR contains only the link the API spec since #4898 has been merged already this PR will be much easier to use. **This is still for Hayden to merge if he can finish the API spec**.
> Remake: Konnect externalized API Spec PR 

- app/_src/kubernetes-ingress-controller/concepts/deployment.md
"Following figure shows how this deployment looks like:" could be changed to either "...how this deployment looks:" or "...what this deployment looks like". I figured the latter fit better with the tone of the rest of the documentation, but either would be correct.
> Minor grammar update

- app/_data/docs_nav_deck_1.17.x.yml
- app/_data/kong_versions.yml
This PR bumps the decK version to from 1.16 to 1.17. 
Autodocs do not need to be run for decK 1.17
> [Release] decK version 1.17

- app/_data/docs_nav_gateway_3.1.x.yml
The debug routes don’t show up in the nav sidebar: https://docs.konghq.com/gateway/latest/admin-api/#debug-routes
Fix https://konghq.atlassian.net/browse/DOCU-2883
> fix(nav): add debug routes to nav sidebar

- app/konnect/runtime-manager/runtime-instances/gateway-runtime-docker.md
Use site.data.kong_latest_gateway.ee-version rather than a hardcoded version in Konnect docs
The docs will automatically update when new versions are released (this assumes compatibility on day zero, which should be a baseline)
/konnect/runtime-manager/runtime-instances/gateway-runtime-docker/
> Use site.data.kong_latest_gateway.ee-version in Konnect

- app/_redirects
Add a redirect for a guide that no longer exists. If the file exists on disk (e.g. pre-2.7) then the redirect does not take effect.
The Gateway API guide has been refactored in KIC 2.7 and 2.8.
/kubernetes-ingress-controller/2.6.x/guides/using-gateway-api/ does not redirect
/kubernetes-ingress-controller/2.7.x/guides/using-gateway-api/ redirects
> Redirect moved file for KIC Gateway API guide

- app/_src/gateway/kong-enterprise/dev-portal/cli.md
This clarifies how you can use variables for `kong_admin_url` and `kong_admin_token` when using the [kong-portal-cli](https://github.com/Kong/kong-portal-cli) to manage [kong-portal-templates](https://github.com/Kong/kong-portal-templates/).
This was brought up as unclear by a team member.
> refactor(portal-cli): clarify details about variables

- app/_src/gateway/kong-enterprise/secrets-management/backends/env.md
Adding a note to simplify the usage of env variable which are been appended inside env section of kong helm deployment
> Updating how to pass env variables

- app/konnect/getting-started/configure-runtime.md
- app/konnect/runtime-manager/runtime-groups/declarative-config.md
This PR contains very minor fixes to wording and output that differed from what I saw when following the onboarding guide for Konnect and using declarative config with Konnect.
Namely:
- there is no "Add runtime instance" button. It's "New Runtime Instance". I expect this was a change in Konnect at some point.
- The route is set up at `/mock` not `/mockpath` (this is correctly identified [later in the doc](https://github.com/Kong/docs.konghq.com/blob/634e153fa9111543a407f148ba74eb348ea6c46e/app/konnect/runtime-manager/runtime-groups/declarative-config.md?plain=1))
- deck makes 3 objects - the sample output is missing the keyauth plugin
It prevents confusion when the docs are consistent with the experience.
I was using decK v1.17.0.
> Minor fixes to konnect deck onboarding

- app/_src/gateway/plugin-development/pluginserver/python.md
Multiple improvements to the Python PDK server document.
- Trailing whitespace removed
- Add a note to reflect the necessity of positional argument in phase handler
- Add a warning and example code to show the correct way to call PDK function
- Verbose logging content
[FTI-4601](https://konghq.atlassian.net/browse/FTI-4601), try to clear up some misunderstanding in the usage of Python PDK
[FTI-4601]: https://konghq.atlassian.net/browse/FTI-4601?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FTI-4601]: https://konghq.atlassian.net/browse/FTI-4601?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> python pdk doc improvements

- app/_hub/kong-inc/route-by-header/_index.md
Fixes `doamin` -> `domain` spelling errors.
> [fix] Spelling in Route By Header plugin

- app/_src/gateway/admin-api/index.md
Kong accepts HTTPS requests when route.protocols is set to only ["http"].
[FTI-4566]
[FTI-4566]: https://konghq.atlassian.net/browse/FTI-4566?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(route): update route.protocols document

- app/_hub/kong-inc/datadog/_index.md
- app/_hub/kong-inc/statsd/_index.md
This PR adds missing documentation on the new config fields for datadog & statsd plugins.
Ref: https://github.com/Kong/kong/pull/9521
> add datadog & statsd plugin missing doc

- app/_src/gateway/reference/configuration.md
- bump default `pg_ssl_version` to `tlsv1_2`
TLS versions lower than `tlsv1_2` are already deprecated and considered insecure. And since PostgreSQL 12.x+ a default minimum ssl version is added `ssl_min_protocol_version = 'TLSv1.2'`.
- constrain the valid values of this config
Currently it accepts any strings. Constrain it to accept only `tlsv1_1`, `tlsv1_2`, `tlsv1_3` or `any`. When `any` is set, the client negotiates the highest version with the server which can't be lower than `tlsv1_1`. Note our pgmoon has removed tlsv1 support. https://github.com/Kong/pgmoon/commit/2f2b028b960f5a4a4052d3ec0d5ef12774a3d3da
https://github.com/Kong/kong-ee/pull/4151
FTI-2972
> [FTI-2972] bump the default `pg_ssl_version` to `tlsv1_2` and update the accepted values

- .github/styles/kongplugins/plugin-ignore.txt
- app/_hub/kong-inc/mtls-auth/_index.md
document the new `allow_partial_chain` parameter
The new `allow_partial_chain` parameter was missing from the documentation.
https://github.com/Kong/kong-ee/pull/3876
FTI-4187
[FTI-4187]: https://konghq.atlassian.net/browse/FTI-4187?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(mtls-auth): document the new allow_partial_chain parameter

- app/_src/gateway/plugin-development/file-structure.md
The table at the bottom of the page lists filenames the plugin developer should use And the descriptions below go into more detail on each file The table and the descriptions are inconsistent regarding the API interface filename
I looked at existing plugins, and there seems to be a standard to use api.lua and not admin-api.lua despite that being the name of the referenced autodoc file.
I suggest we make the filename in the description match the filename in the table so the developer knows what to name their file.
To make the PDK more consistent for the reader
Built the docs locally and viewed the result manually
> Makes the PDK file structure slightly more consistent

- app/_src/gateway/get-started/index.md
Minor note addition to the getting started instructions to help guide users to advanced usage of the quickstart script. 
This change was at the request of the field who have customers using the script for various cases including running in licensed mode.
Built docs locally and viewed
> Getting started mention advanced docs

- app/_data/kong_versions.yml
- app/gateway/2.8.x/reference/configuration.md
- app/gateway/changelog.md
* Changelog for 2.8.2.3 based on internal Enterprise changelog.
* Prometheus parameters added from https://github.com/Kong/kong-ee/pull/4220/files. 
* This is listed as part of the release but is not yet merged, and the release is going out tomorrow. May have to remove it.
* Will also need to merge (or not merge) https://github.com/Kong/docs.konghq.com/pull/4972 along with this update.
https://konghq.atlassian.net/browse/DOCU-2817
Netlify
(This is still using the old changelog format, as we haven't settled on everything for the split method yet.)
> Gateway 2.8.2.3: Changelog and parameters

- app/_hub/kong-inc/prometheus/_1.6.0.md
- app/_hub/kong-inc/prometheus/_index.md
Changelog entry of new `kong.conf` directives added for the Prometheus plugin.
New directives were added so users can enable or disable some metrics in the Prometheus plugin. You can read more about why this change is needed in FTI-4460. 
I added a non-standard version section for the new feature as it is being released only for a specific version of Kong EE. Please let me know if there is a correct/better way of documenting this.
More details in:
Kong/kong-ee#4222
Kong/kong-ee#4189
Kong/kong-ee#4220
FTI-4460
> New kong.conf directives for Prometheus plugin

- app/konnect/runtime-manager/runtime-instances/gateway-runtime-kubernetes.md
Follow up PR to https://github.com/Kong/docs.konghq.com/pull/4970. The kubernetes doc should have the same update.
Preview: https://deploy-preview-5000--kongdocs.netlify.app/konnect/runtime-manager/runtime-instances/gateway-runtime-kubernetes/
> Use variable for kong gateway version in Konnect K8s doc

- app/_hub/kong-inc/rate-limiting-advanced/_index.md
- app/_includes/hub-examples.html
Make GUI examples respect `if_plugin_version` - fixes Konnect and KM examples for Rate Limiting Advanced
DOCU-2879
/hub/kong-inc/rate-limiting-advanced/
You'll see `config.strategy` twice in production, and once on the review app
> Fix plugin GUI examples when using `if_plugin_version`

- app/_src/mesh/features/rbac.md
Adds information of extra `to` and `from` RBAC qualifiers in incoming Kong Mesh 2.1
We introduced new functionality
Checked with the preview
> mesh: new policy rbac qualifiers

- app/_src/kubernetes-ingress-controller/concepts/ingress-versions.md
The attributes defined for apiVersion: networking.k8s.io/v1 did not match the one defined for apiVersion: networking.k8s.io/v1beta1. I did my best as a kubernetes novice, but please have someone internal review my changes and make any others necessary.
We're updating from k8s 1.21 to 1.22 and need these instructions to know exactly what to do wrt kong
> Updated ingress declaration examples to match

- app/_src/gateway/kong-enterprise/consumer-groups/index.md
Follow up to https://github.com/Kong/docs.konghq.com/pull/4969. 
Removing the note about decK support for consumer groups in one other topic.
Preview: https://deploy-preview-5001--kongdocs.netlify.app/gateway/latest/kong-enterprise/consumer-groups/
> Remove note about decK support

- app/_includes/md/support-policy.md
- app/_src/gateway/support-policy.md
- app/_src/kubernetes-ingress-controller/support-policy.md
- app/_src/mesh/support-policy.md
- app/gateway/2.8.x/support-policy.md
The support matrix for all products was shown within each product. 
It doesn't make sense to show Mesh version support when looking at Gateway or KIC (and vice versa)
- /gateway/latest/support-policy/
- /mesh/latest/support-policy/
- /kubernetes-ingress-controller/latest/support-policy/
> Version support pages show a single product

- jekyll-dev.yml
- jekyll.yml
Add placeholders for `helm_repo` and `helm_install_name` that will be used in Mesh docs following [this PR](https://github.com/kumahq/kuma-website/pull/1185).
Once we merge this, I'll create a follow-up PR (or use the github action) that updates the git submodule, which will pick up this change.  
Related [Jira ticket](https://konghq.atlassian.net/browse/DOCU-2882) and [Github  Issue](https://github.com/Kong/docs.konghq.com/issues/4960)
HELM commands in [Mesh documentation](https://docs.konghq.com/mesh/latest/deployments/multi-zone/) were still referring to Kuma, e.g.
```
helm install kuma --create-namespace --namespace kong-mesh-system --set controlPlane.mode=global kuma/kuma
```
Nothing to test here given that it's not being used at the moment.
> Add placeholders for `kuma` and `kuma/kuma` used in Mesh docs

- .github/styles/kongplugins/plugin-ignore.txt
- app/_hub/kong-inc/key-auth-enc/_index.md
- app/_hub/kong-inc/key-auth/_index.md
Follow-up to https://github.com/Kong/docs.konghq.com/pull/4941. 
Adding `tags` attribute to the `key-auth-enc` plugin as well as `key-auth`. Note that key-auth-enc doesn't yet support `ttl`; see FTI-4066 for detail.
Also updating the config examples with `tags` and `key` values, and with `ttl` for the Key Auth plugin.
> Add tags to key-auth-enc plugin; update examples

- .github/styles/kong/dictionary.txt
- app/_src/gateway/production/deployment-topologies/db-less-and-declarative-config.md
We should include this section of our Helm Chart README in the official documentation. It includes steps to configure a Proxy in Kubernetes with a declarative config when not using a KIC
https://github.com/Kong/charts/tree/main/charts/kong#db-less-deployment
Including steps to use a declarative configuration on a Proxy in Kubernetes when the Kong Ingress controller is disabled
Steps to perform this are somewhat buried in our Helm Chart README file
> Helm Chart README moved to official documentation

- app/konnect/dev-portal/applications/dynamic-client-registration/auth0.md
Adds note for developers setting up DCR with Auth0.
If this configuration is missed, the auth flow will not work.
> docs(portal): add warning for auth0 configuration [TDX-2739]

- app/_hub/kong-inc/app-dynamics/_index.md
- app/_hub/kong-inc/degraphql/_index.md
- app/_hub/kong-inc/graphql-rate-limiting-advanced/_index.md
- app/_hub/kong-inc/tls-handshake-modifier/_index.md
- app/_hub/kong-inc/tls-metadata-headers/_index.md
Searched through the doc for plugins that have `cloud: false` but not `konnect_examples: false` and updated them. The plugins noted in the ticket were the only ones.
Also found that the TLS plugins were supposed to have been checked in Konnect in 3.0 and have the examples enabled if they exist. I checked that, they are there, so I enabled examples.
Some plugins had Konnect examples even though they're not available in Konnect.
Netlify. 
Konnect examples for the graphql plugins should be gone, and the TLS plugins should have Konnect examples.
> [DOCU-2880] Plugin konnect examples

- app/_hub/kong-inc/prometheus/_index.md
The grafana dashboard URL apparently changed.
https://konghq.atlassian.net/browse/KAG-213
> docs(prometheus): update dashboard url

- app/_src/gateway/admin-api/consumer-groups/reference.md
- app/_src/gateway/kong-enterprise/consumer-groups/index.md
Adding tags to consumer group examples and `tags` attribute entries for creating a consumer group.
3.1 fast-follow PR based on https://konghq.atlassian.net/browse/DOCU-2900. 
Netlify.
Tested the API, things work, tags appear. Also tested out filtering by tags but didn't want to add an example of that here, since we don't include tag filtering examples in other API docs, and there is a specific doc section for that instead.
> [DOCU-2900] Add tags to consumer groups examples and reference

- .github/styles/kongplugins/plugin-ignore.txt
- app/_hub/kong-inc/graphql-rate-limiting-advanced/_index.md
- app/_hub/kong-inc/rate-limiting-advanced/_index.md
Improve description to include DB-less and declarative config info. Also add the value to the autogenerated config examples, since we recommend setting it explicitly for a large portion of users.
[Issue raised on Slack](https://kongstrong.slack.com/archives/CDSTDSG9J/p1673022359955879).
Explanation of behavior from FTI ticket:
> As you can see from the discussion on this related PR, we are going to not fix this on purpose: this is currently failing because the namespace field is an auto field, meaning that if the user doesn't provide any input, Kong autogenerates it. Since deck is a tool for declarative configuration, we believe this is a good place for deck to fail since not having a namespace and autogenerate it here would mean that decK is not pushing configuration declaratively: a …
> Rate Limiting Advanced plugin: Improve config.namespace description

- app/_hub/kong-inc/serverless-functions/_index.md
Set datatypes for serverless functions plugin parameters. Verified via https://github.com/Kong/kong/blob/master/kong/plugins/pre-function/_schema.lua#L20-L27. 
https://konghq.atlassian.net/browse/DOCU-669
https://deploy-preview-5023--kongdocs.netlify.app/hub/kong-inc/serverless-functions/
> [DOCU-669] Datatypes for serverless functions plugin

- .github/styles/kongplugins/plugin-ignore.txt
- app/_hub/kong-inc/zipkin/_index.md
Adding the missing parameter `default_service_name`. 
This parameter was added in a pre-2.1 version, so we don't need to set any conditionals on it.
References: 
* [plugin schema](https://github.com/Kong/kong/blob/master/kong/plugins/zipkin/schema.lua#L55)
* [PR from archived plugin repo](https://github.com/Kong/kong-plugin-zipkin/pull/45)
https://konghq.atlassian.net/browse/DOCU-2212
Netlify
> [DOCU-2212] Zipkin: Document missing parameter default_service_name

- .github/styles/kongplugins/dictionary.txt
- app/_hub/kong-inc/app-dynamics/_index.md
Adding a prerequisites section to the AppDynamics plugin with the SDK install info + platform requirements.
https://konghq.atlassian.net/browse/DOCU-2840
https://deploy-preview-5022--kongdocs.netlify.app/hub/kong-inc/app-dynamics/
> [DOCU-2840] AppDynamics plugin: Prereqs section with platform info

- app/_src/gateway/upgrade-31x.md
Add an anchor to the migrate/upgrade section. There are links to that anchor, this fixes them.
The link works in previous versions. 
Fixes https://github.com/Kong/docs.konghq.com/issues/5019.
https://deploy-preview-5021--kongdocs.netlify.app/gateway/latest/upgrade/
Check the link to "database migration" in the sentence "In either case, you can review the upgrade considerations, then follow the database migration instructions."
> Add missing anchor link on upgrade page 

- app/_data/tables/plugin_index.yml
- app/_hub/kong-inc/oas-validation/_index.md
Remove konnect labels and examples from OAS validation plugin.
Currently, the OAS Validation plugin is not supported in Konnect. It will be added in an upcoming patch release instead.
See [this conversation](https://kongstrong.slack.com/archives/C01888Q7PJ7/p1673366690845499?thread_ts=1673342450.933209&cid=C01888Q7PJ7) for background.
https://deploy-preview-5020--kongdocs.netlify.app/hub/kong-inc/oas-validation/
> OAS Validation plugin: Not supported in Konnect

- app/_hub/kong-inc/graphql-rate-limiting-advanced/_index.md
- app/_hub/kong-inc/openid-connect/_index.md
- app/_hub/kong-inc/rate-limiting-advanced/_index.md
- app/_hub/kong-inc/rate-limiting/_index.md
- app/_hub/kong-inc/response-ratelimiting/_index.md
- app/_hub/kong-inc/saml/_index.md
Follow-up to https://github.com/Kong/docs.konghq.com/pull/4913. 
The PR only edited the rate limiting plugins, but according to the linked FTI, the username `default` is not supported in Redis 6.0.0+ in general - this is not specific to Kong, so it should apply anywhere that we allow `redis.username`.
@outsinre can you please verify that this change is correct for all of these plugins?
> Clarify redis.username on all plugins that support it

- app/_includes/md/gateway/setup.md
Added a quick note to encourage Enterprise users to skip to the Seeding Super-Admin password section instead of running the initial ```kong migrations``` command without it.
A customer highlighted the concern that if following the documentation in-order as currently defined then it's too late to set the Super-Admin password by the time that section is read. To help users avoid this trap, I felt it was best to highlight the area before a user runs the initial ```kong migrations``` command.
> Add note about seeding super-admin password

- .github/PULL_REQUEST_TEMPLATE.md
- .github/styles/kong/dictionary.txt
- .github/workflows/require-review-label.yml
Attempting to make the PR template clearer.
* Combined the summary and reason sections into one
* Added changelog prompt
* Added checklist - is this useful at all? If we want to use it, what else should be part of this checklist?
* Left the info about labels in. It's a big block block of text that I don't think anyone reads, but the info needs to be there to cover why the builds fail. 
* Or does it? Should it be a bot comment instead, if someone doesn't add a label?
All feedback and ideas welcome.
> Simplify PR template

- Makefile
Adding `git submodule init && git submodule update` to the `make install` command. People (myself included) keep running into issues where the local submodule ends up out of date and the build fails.
Test locally by running `make install`. 
You can temporarily delete the `_src/.repos/kuma` folder first before running it to make sure that the command does pull the submodule.
> Update kuma submodule with `make install`

- app/_src/gateway/kong-manager/auth/workspaces-and-teams.md
Including:
- updating the description of roles to match what is in kong manager
- attempts to simplify some directions and clarify steps
Minor copy edits based on personal use of the page while walking through the current state of the Kong Manager product.
Some of these changes are personal opinion minor edits and some of them are clarifications from the behavior of the product the page describes.
Built docs locally
> Tweak: Adds minor copy edits to the workspaces and teams page

- app/gateway/changelog.md
Clarifies an issue in the changelog with a dynamically linked library in kong release 2.8.2.3
> FTI-4690: Notes a limitation in Kong 2.8.2.3 in regard to dynamically linked PCRE library

- .github/workflows/auto-close-kong-issues.yml
Automatically close issues raised by Kong org members
We prefer to track employee requests in Jira
Tested on a separate repo (it worked!)
> Add auto-close Kong issues workflow

- app/gateway/changelog.md
Removing amazon linux segfaults fix that didn't make it into the 2.8.2.3 builds. It is being deferred to 2.8.2.4 or 2.8.3.0. 
Netlify
> Remove Amazon Linux segfaults fix from changelog

- app/_hub/kong-inc/request-transformer-advanced/_index.md
Fast-follow PR for 3.1.
Documenting the following parameters, all introduced in 3.1: `dots_in_keys`, `replace.json_types`, `add.json_types`, `append.json_types`. They are exact copies of the entries for the Response Transformer Advanced plugin.
This is already [mentioned in the Gateway changelog](https://docs.konghq.com/gateway/changelog/#:~:text=Added%20support%20for%20navigating%20nested%20JSON%20objects%20and%20arrays%20when%20transforming%20a%20JSON%20payload.), we just didn't have a doc update for it.
https://konghq.atlassian.net/browse/DOCU-2911
Netlify link:
> [DOCU-2911] Request transformer advanced plugin: JSON object and array parameters

- app/_data/kong_versions.yml
- app/gateway/changelog.md
Changelog and version bump for 2.8.2.4.
There is only one ticket in this patch version, as it's a high-priority fix.
https://konghq.atlassian.net/browse/DOCU-2915
Netlify link: https://deploy-preview-5057--kongdocs.netlify.app/gateway/changelog/#2824
> Release: Gateway 2.8.2.4

- app/_hub/kong-inc/response-transformer/_index.md
Fix Typo in the Page for Response Transformer plugin documentation.
Just open https://docs.konghq.com/hub/kong-inc/response-transformer/ and see if the changes reflected.
- [X ] Review label added 
- [X ] PR pointed to correct branch (`main` for immediate publishing, or a release branch: e.g. `release/gateway-3.2`, `release/deck-1.17`)
> Fix Typo in the additional abilities listing

- app/_src/gateway/kong-enterprise/analytics/index.md
- app/gateway/2.8.x/vitals/index.md
* Added Prometheus to the Vitals/analytics supported strategies list. 
* Rephrased the list to say strategies instead of databases for accuracy.
This has always been true, it was just missing, so I've also updated 2.8.x.
Issue reported on Slack: https://kongstrong.slack.com/archives/CDSTDSG9J/p1674117603455889
Netlify link:
> Add prometheus to supported strategies list

- app/konnect/updates.md
Fixing this issue:
Also removing the date, as we don't post specific dates anymore; looks like it was an accidental leftover.
Ran into this when looking through the release notes.
Netlify link: https://deploy-preview-5068--kongdocs.netlify.app/konnect/updates/#november-2022
> Fix indent in release notes

- app/_hub/kong-inc/openid-connect/_index.md
Added PKCE to list of supported credentials and grants for the OIDC plugin. We have supported it for a long time but have never mentioned in the docs.
I looked into expanding auth code flow examples and decided against it, so that we don't simply repeat the [Auth0 documentation](https://auth0.com/docs/get-started/authentication-and-authorization-flow/authorization-code-flow-with-proof-key-for-code-exchange-pkce). As far as I can tell, any other config that the customer has to do happens on their end, not in this plugin.
Issue reported on [Slack](https://kongstrong.slack.com/archives/CDSTDSG9J/p1674238775807409).
Netlify link:
> OIDC plugin: Add PKCE to list of supported credentials and grants

- app/_hub/kong-inc/oas-validation/_index.md
- app/_hub/kong-inc/oas-validation/versions.yml
OAS validation plugin is bundled with Kong starting in 3.1.1.2. 
* Removing `bundled: false` for this plugin and moving the instructions into a conditional section that will only be visible for 3.1.x
* Adding a banner mentioning the version. 
* I didn't want to put all of the info in the banner at the top of the page, as that would take over the intro section.
https://konghq.atlassian.net/browse/DOCU-2906
Merge this PR only when 3.1.1.2 goes out.
Netlify link: https://deploy-preview-5038--kongdocs.netlify.app/hub/kong-inc/oas-validation/
> [DOCU-2906] OAS validation plugin is bundled with Kong

- app/_data/kong_versions.yml
Bumped the version for decK. 
1.7.2 was released today: https://github.com/Kong/deck/releases/tag/v1.17.2
Did a quick review of the changelog (https://github.com/Kong/deck/blob/main/CHANGELOG.md#v1172), nothing in there needs doc updates.
Netlify link: https://deploy-preview-5069--kongdocs.netlify.app/deck/latest/installation/
> chore: Bump deck version to 1.17.2

- app/_src/gateway/admin-api/event-hooks/reference.md
I don't think that the "Important: Before you can use event hooks for the first time, Kong needs to be reloaded." message at the top of the https://docs.konghq.com/gateway/latest/admin-api/event-hooks/reference/ page is necessary.
Please remove it as per this PR or explain why it should remain. 
For reference, I see it being added in this commit https://github.com/Kong/docs.konghq.com-private/commit/e4a83dd35b0fae58c5eae1ff3a06a409af93dc0e#diff-573438562e7571186a5c5a030162746792c36f46275f591c5157fd55c4343631
> remove Important warning from the top of the Event Hooks reference page

- app/_includes/md/gateway/admin-api-workspaces.md
- app/_src/gateway/admin-api/admin-api-3.0.x.md
- app/_src/gateway/admin-api/developers/reference.md
- app/_src/gateway/admin-api/index.md
- app/_src/gateway/admin-api/workspaces/reference.md
- app/_src/gateway/kong-enterprise/workspaces/index.md
- app/gateway/2.8.x/admin-api/index.md
- app/gateway/2.8.x/admin-api/workspaces/examples.md
- app/gateway/2.8.x/admin-api/workspaces/reference.md
Adding doc on using the workspace name or ID prefix in requests to the Kong Admin API.
Previously, the info was buried on the Developer API reference page.
Minor clean up, removed HTTPie examples, and reused the info in the Admin API overview and the workspace examples pages. 
Tested all the things locally. Backported through 2.8.x.
Tickets:
https://konghq.atlassian.net/browse/DOCU-857
https://konghq.atlassian.net/browse/DOCU-2942
https://konghq.atlassian.net/browse/DOCU-2262
https://konghq.atlassian.net/browse/DOCU-2912
Netlify link:
> [DOCU-857] Using workspaces in an Admin API request

- app/_mesh_redirects
- app/_plugins/generators/alias_generator.rb
- spec/app/_plugins/generators/alias_generator_spec.rb
- spec/fixtures/app/_mesh_redirects
Add some of the redirects we have in Kuma to Kong-Mesh, the new release of Kuma's GUI points to the old urls that's why  we need them. Also, we should definitely automate the generation of this file so that we can update it every time we update kuma, this is a quick and dirty solution we can ship and test before the release.
cc @lahabana 
Netlify link:
> Add redirects for mesh

- app/_src/mesh/features/opa.md
- app/mesh/1.2.x/features/opa.md
- app/mesh/1.3.x/features/opa.md
- app/mesh/1.4.x/features/opa.md
- app/mesh/1.5.x/features/opa.md
- app/mesh/1.6.x/features/opa.md
Signed-off-by: slonka <slonka@users.noreply.github.com>
> What did you change and why?
We found a bug in OPA that only allows one policy to be defined, multiple policies never worked so we need to backport this.
> Include any supporting resources, e.g. link to a Jira ticket, GH issue, FTI, Slack, Aha, etc.
https://github.com/Kong/kong-mesh/pull/2516
Netlify link:
> docs(policies): add note about one policy for kong mesh opa

- app/_data/docs_nav_mesh_2.1.x.yml
- app/_src/mesh/features/meshopa.md
Signed-off-by: slonka <slonka@users.noreply.github.com>
Also how do I make sure it only appears in navbar since 2.1 KM release?
> What did you change and why?
I've added docs for new version of OPA policy.
> Include any supporting resources, e.g. link to a Jira ticket, GH issue, FTI, Slack, Aha, etc.
closes  https://github.com/Kong/kong-mesh/issues/2494
Netlify link:
> docs(kong-mesh): initial mesh opa docs

- app/_src/mesh/features/meshopa.md
Added missing container to curl command, and namespace
> docs(meshopa): fix missing container and namespace

- app/_src/mesh/features/meshopa.md
- changed k8s model to universal in universal example
- moved mesh to label
> docs(mesh): fixed model of MeshOPA and removed mesh name

- app/_hub/kong-inc/aws-lambda/_index.md
Reverts Kong/docs.konghq.com#4877
Hi team, can you help revert this change from the 3.2 changeset? We decide to postpone this change as it needs some more work to be done.
> Revert "docs(aws-lambda): add new `https` config field in aws-lambda plugin"

- app/_data/docs_nav_kic_2.8.x.yml
- app/_src/kubernetes-ingress-controller/deployment/admission-webhook.md
- app/_src/kubernetes-ingress-controller/deployment/overview.md
Call out the admission webhook more prominently in deploy documentation.
Use "admission webook" consistently. Previously documentation used "admission webhook" and "admission controller" interchangeably.
Add Helm chart instructions to the admission webhook documentation.
**Note:** this references a chart version that is not yet released.  It is ready for review but should not be merged until https://github.com/Kong/charts/pull/727 is merged.
None. No major changes to formatting, only some link updates that Vale should catch if I botched them
> doc(kic) update admission webhook documentation

- app/gateway/changelog.md
Changelog for 3.1.1.2 was missing all changes added to core/OSS gateway. 
There is a discrepancy between what the OSS engineering changelog shows, and what actually got pulled into the release on the Enterprise side.
https://konghq.atlassian.net/browse/DOCU-2957
PR can be merged at any time after review.
Netlify link:
> [DOCU-2957] Add missing 3.1.1.2 changelog entries

- app/enterprise/2.5.x/deployment/default-ports.md
Update default protocol for Hybrid CP Communications to **TCP instead of HTTP.** 
The feedback from the field was that at first sight they will provisioned Layer 7 LoadBalancer for Hybrid communication since its indicated as HTTP for port 8005 and 8006, which will not work as the config sync between CP and DP required a Layer 4 LoadBalancer passthrough
Include any supporting resources, e.g. link to a Jira ticket, GH issue, FTI, Slack, Aha, etc
https://kongstrong.slack.com/archives/CDSTDSG9J/p1675324064493179
Netlify link:
> PR - Update Hybrid communication protocol to TCP

- app/_src/gateway/install/docker/index.md
The version provided in the documentation does not seem to work as its outdated. Hence updated with the version which works currently on setting up the Kong using docker images.
What did you change and why? Updated the Postgres version from 9.6 to 12.2 which works
https://stackoverflow.com/questions/59142544/docker-kong-postgresql-error-failed-to-retrieve-postgresql-server-version-n
Netlify link: https://deploy-preview-5103--kongdocs.netlify.app/
Before Change : https://docs.konghq.com/gateway/latest/install/docker/#prepare-the-database
After Change: https://deploy-preview-5103--kongdocs.netlify.app/gateway/latest/install/docker/#prepare-the-database
> Postgres outdated version

- app/_src/kubernetes-ingress-controller/guides/preserve-client-ip.md
HI this PR address some outdated informations on the page `preserving client ip adress`. It adds informations on the AWS Load Balancer Controller instead of using the in-tree one.
The AWS Load Balancer Controller is a more complete approach on EKS to manage Load Balancers, network and application. 
The reason behind this PR is to update the page and remove the wrong information that proxy protocol can be enabled on a `in-tree` `nlb` load balancer.
To test the annotations/Load Balancers, you need an EKS cluster with the AWS Load Balancer Controller deployed.
To install the AWS Load Balancer Controller on an EKS cluster you can follow the official docs or use the kustomize package and terraform module included in this repository https://github.com/sighupio/fury-kubernetes-aws 
review:tech:
> Update NLB guide to preserve IP address on EKS using AWS Load Balancer Controller strategy

- app/gateway/changelog.md
Removed a line from a changelog entry that implied the user had to configure cache size for the RLA plugin. This is not the case - this is something the plugin does intenally. 
Reported on [Slack](https://kongstrong.slack.com/archives/CDSTDSG9J/p1675853248681819).
Netlify link:
> Changelog fix: Remove internal implementation info

- app/_src/gateway/production/networking/default-ports.md
Update default protocol for Hybrid CP Communications to TCP instead of HTTP.
The feedback from the field was that at first sight they will provisioned Layer 7 LoadBalancer for Hybrid communication since its indicated as HTTP for port 8005 and 8006, which will not work as the config sync between CP and DP required a Layer 4 LoadBalancer passthrough
This is a continuation from PR #5112 ,which only updated contents pre Kong Gateway 3.0. This PR will update latest Kong 3.x documentations.
Include any supporting resources, e.g. link to a Jira ticket, GH issue, FTI, Slack, Aha, etc
https://kongstrong.slack.com/archives/CDSTDSG9J/p1675324064493179
Netlify link:
> PR: Update default protocols for Hybrid communications in Kong 3.0 Production Page

- app/_data/kong_versions.yml
Bumping decK version. Patch release just went out: https://github.com/Kong/deck/blob/main/CHANGELOG.md#v1173
No other doc changes needed.
Netlify link:
> Chore: Bump deck version to 1.17.3

- app/_src/kubernetes-ingress-controller/references/feature-gates.md
KIC 2.8.x has enabled feature gate `CombinedRoutes` by default, so docs should be updated.
Netlify link: 
https://deploy-preview-5139--kongdocs.netlify.app/kubernetes-ingress-controller/2.8.x/references/feature-gates/
> fix: kic 2.8 enabled CombinedRoutes by default

- app/_src/gateway/how-kong-works/routing-traffic.md
- app/_src/gateway/kong-plugins/configuring-a-grpc-service.md
- app/_src/gateway/reference/configuration.md
- autodoc-conf-ee/run.lua
* Add new parameters to the Configuration Reference.
* Compared the Enterprise and OSS versions of kong.conf.default and labelled Enterprise features accordingly
* Had to make a copy of the Postgres table for 3.2.x, couldn't get version conditionals to work right without breaking the table - I think it's because I had to use both `lte` and `gte` one after the other.
* Searched for and updated any instances of the kong-debug header, adding a step to first enable sending debugging info.
* As part of this, cleaned up the very outdated gRPC service guide, which was mentioning Kong 1.3 everywhere.
Did not add a changelog/breaking change entry. This will be added in a separate changelog PR.
Ticket: https://konghq.atlassian.net/browse/DOCU-2928
Netlify link:
> [DOCU-2928] Kong-Debug header + configuration reference update

- app/_layouts/extension.html
- app/hub/plugins/compatibility.md
Added plugin `instance_name` to the plugin table. Every plugin has this field now.
Validated against a 3.2 KM instance, all plugins do indeed have this field.
Also fixed some format issues with the layout:
* Fixed plugin table spacing. We were using `br` tags instead of `p` tags for some reason.
* Added `optional` tags for optional parameters. These are already set for anything in `config.` but were missing from the `service_*`, `route_*`, `consumer_*`, and `enabled` parameters.
* Added a `false` option for global scope support. There is one plugin that doesn't support being applied globally, which I discovered when editing the layout.
https://konghq.atlassian.net/browse/DOCU-2983
Netlify links:
* Check any plugin for the `instance_name` param, for example: …
> [DOCU-2983] Plugin instance name + spacing fixes

- app/_hub/kong-inc/canary/_index.md
- app/_hub/kong-inc/opentelemetry/_index.md
- app/_src/gateway/how-kong-works/load-balancing.md
- app/gateway/changelog.md
Changelog for Gateway 3.2 release.
Compiled from OSS CHANGELOG.md, Enterprise CHANGELOG.md, and Enterprise changelog wiki page.
When going through changelog entries, found and added/fixed the following:
* New default value for Canary plugin's `start` parameter
* Consumer, route, and service scope support for OpenTelemetry plugin
* Missing `if_version` tags in load balancing doc for new `latency` algorithm.
We are also missing docs for two other things: `instance_name` in plugins and new audit log entries. 
Both of these items are logged in tickets and tagged as Gateway 3.2 fast-follow.
https://konghq.atlassian.net/browse/DOCU-2920
Netlify link: https://deploy-preview-5159--kongdocs.netlify.app/gateway/changelog/
❗Reviewers:
* Please make sure that any features you worked on are covered in …
> [DOCU-2920] Changelog for Gateway 3.2

- app/_src/gateway/admin-api/licenses/reference.md
- app/_src/gateway/get-started/index.md
- app/_src/gateway/licenses/examples.md
- app/_src/gateway/licenses/report.md
- app/_src/gateway/production/deployment-topologies/db-less-and-declarative-config.md
- app/_src/gateway/production/deployment-topologies/hybrid-mode/index.md
More QA edits, building on https://github.com/Kong/docs.konghq.com/pull/5166.
Using `{{page.version.ee}}` and `{{page.version.ce}}` instead to `{{page.kong_version}}` to use the real version name (eg 3.2.0.0) instead of the truncated one (eg 3.2.x).
Also finish the edit to the hybrid mode intro started in https://github.com/Kong/docs.konghq.com/pull/5166.
Netlify link:
> Gateway 3.2: QA edits

- app/_data/docs_nav_gateway_3.0.x.yml
- app/_data/docs_nav_gateway_3.1.x.yml
- app/_data/docs_nav_gateway_3.2.x.yml
- app/_src/gateway/admin-api/audit-logs.md
- app/_src/gateway/kong-enterprise/audit-log.md
Document new log entries and update audit logging doc. Tested everything in a local 3.2 Gateway instance.
* The new feature is documented in the "Kong Manager authentication" section in the "Audit Logging in Kong Gateway" doc. I also went through the code examples and added the new fields wherever relevant.
* ❗ Reviewers - you only need to look closely at this new "Kong Manager authentication" section. Nothing else is new.
* The rest of (and majority) of this PR is quality-of-life improvements to the doc: standardization, cleanup, split the admin API reference into the Admin API doc section (I had no idea we had an `/audit` endpoint until today!).
https://konghq.atlassian.net/browse/DOCU-2982
Netlify link:
> [DOCU-2982] Audit log updates for 3.2

- app/_assets/stylesheets/features-table.less
- app/_assets/stylesheets/page.less
- app/_assets/stylesheets/pages/docs.less
Fix table bordering styling issue introduced in a previous PR in this release.
Was causing borders to extend to the width of the content body instead of the table:
Netlify link: 
Check some narrow tables, eg Mesh support table.
> Fix table styling

- app/_hub/kong-inc/oauth2/_index.md
Added hybrid mode alongside DB-less where the OAuth 2.0 Authentication plugin isn't compatible
DB-less mode is the only one that was listed as being incompatible. Added hybrid mode as another deployment methodology where this plugin doesn't work.
Plugin compatibility [link](https://docs.konghq.com/hub/plugins/compatibility/) mentions both DB-less and hybrid under OAuth 2.0 Notes.
N/A
> oauth2_update

- app/_hub/kong-inc/datadog-tracing/_index.md
The datadog-tracing plugin was missing some attributes on the root span it generates. This documents those missing attributes.
> release 3.2/datadog services routes

- app/_data/tables/plugin_index.yml
- I added that Konnect was supported for the Datadog tracing plugin. 
DOCU-2945
Netlify link: 
❗ Reviewers: check that Datadog Tracing displays on the plugin compatibility page and that Konnect has a check for it.
> [DOCU-2945] Konnect + Gateway 3.2 - Datadog EE plugin

- app/_hub/kong-inc/rate-limiting/_index.md
Remove an information that, put that way, is redundant and confusing. The values `service.id` and `service.name` are not related with the configuration of the parameter `limit_by`, which can be set even when the plugin is configured globally.
> docs(rate-limiting): remove wrongly placed information

- app/_hub/kong-inc/openid-connect/_index.md
Clarified the session_cookie_renew property as it was pointed out by a customer that it wasn't clear this property was how many seconds prior to the lifetime expiration before being renewed.
> Explain the session_cookie_renew property in more detail

- app/gateway/changelog.md
Changes based on based on https://kongstrong.slack.com/archives/C02GZ0CGJNT/p1676483737035119
* Updated release date 
* Added entries for FTI-4818 and KAG-42.
* No entry needed for FTI-4819; this is an internal change only.
❗ Reviewers: please review, but **do not merge** yet, until we're 100% certain these issues are resolved and in the release.
Netlify link: https://deploy-preview-5173--kongdocs.netlify.app/gateway/changelog/
> [DOCU-2990] Changelog 3.2: late breaking changes

- app/konnect/org-management/teams-and-roles/index.md
- app/konnect/servicehub/manage-services.md
During the lead up to helium, we had originally planned on an entity sharing feature. This feature was documented and ready to go on most fronts, but was rolled back. It is now being completely removed from the roadmap and codebase.
Removing draft docs, which currently exist in commented-out form in a couple of konnect topics.
Netlify link:
> [DOCU-2270] Remove drafts for entity sharing

- app/_hub/kong-inc/jwt-signer/_2.2.x.md
- app/_hub/kong-inc/oauth2/_index.md
- app/_hub/kong-inc/statsd-advanced/_1.3-x.md
- app/_src/gateway/admin-api/workspaces/reference.md
- app/gateway/2.6.x/admin-api/workspaces/reference.md
- app/gateway/2.7.x/admin-api/workspaces/reference.md
- app/gateway/2.8.x/admin-api/workspaces/reference.md
Fixes issue https://github.com/Kong/docs.konghq.com/issues/5106.
Removing `/apis` endpoint, which was deprecated before 1.0.
Netlify:
> Remove last bits of old `/apis` endpoint

- app/_data/tables/plugin_index.yml
- app/_hub/kong-inc/oas-validation/_index.md
I enabled Konnect support in the OAS plugin docs, so it displays Konnect instructions as well as info that it is available in Konnect in the sidebar. 
DOCU-2947
Netlify link:
> Add Konnect support to the OAS plugin

- app/_src/gateway/upgrade-31x.md
-  After talking with Michael Martin, he confirmed that in 2.8.x, traditional and DB less can both go directly to 3.2.x. Hybrid still must do the indirect route however.
Netlify link: /gateway/latest/upgrade/
> Fix the upgrade path for 2.8.x traditional and DBless

- app/_src/kubernetes-ingress-controller/guides/setting-up-custom-plugins.md
Plugins MUST now have a valid PRIORITY (integer) and VERSION (“x.y.z” format) field in their handler.lua file, otherwise the plugin will fail to load. #8836
> add  VERSION  field

- app/_data/docs_nav_deck_1.18.x.yml
- app/_data/docs_nav_deck_1.19.x.yml
- app/_data/kong_versions.yml
- app/_src/deck/guides/defaults-v2.md
- app/_src/deck/guides/defaults.md
- app/_src/deck/guides/konnect.md
- app/konnect/getting-started/import.md
- app/konnect/runtime-manager/runtime-groups/declarative-config.md
Added decK 1.19.0, which we just released yesterday, and 1.18.1, which came out a couple of weeks ago. 
Both releases are very small and require little to no doc updates; see changelog: https://github.com/Kong/deck/blob/main/CHANGELOG.md#v1190
The plugin tab on the defaults guide page is not a new feature, it's just an addition of a missing tab.
Netlify link: https://deploy-preview-5197--kongdocs.netlify.app/deck/latest/
> Release/deck 1.18.1 and 1.19.0

- app/_data/docs_nav_konnect.yml
- app/konnect/reference/labels.md
- app/konnect/servicehub/manage-services.md
Adding a reference section in Konnect nav with a Labels reference topic.
I put it into a general reference section because labels are used in multiple places (runtime manager, service hub) and there's no central shared section that it fits into otherwise.
https://konghq.atlassian.net/browse/DOCU-2588
Will need to make a follow-up update in Flycode once this PR is merged to update the doc URL in the UI.
Netlify link: https://deploy-preview-5213--kongdocs.netlify.app/konnect/reference/labels/
> [DOCU-2588] Reference topic for labels in Konnect

- app/_src/gateway/licenses/index.md
Better license expiration description. Currently, the license expiration behavior is hard to understand.
Include the exact time at which the license expires.
https://konghq.atlassian.net/browse/DOCU-2820
https://konghq.atlassian.net/browse/DOCU-2753
Netlify link: https://deploy-preview-5212--kongdocs.netlify.app/gateway/latest/licenses/#license-expiration
> [DOCU-2820][DOCU-2753] Improve license expiration description

- app/_src/gateway/install/index.md
There's currently a bug on this page that expands the icons of each image whenever you click a link. Disabling that.
Netlify link:
> Fix: Disable icon expanding on install overview

- app/_src/kubernetes-ingress-controller/guides/using-ingress-with-grpc.md
- app/_src/kubernetes-ingress-controller/references/gateway-api-support.md
GRPCRoute support added for KIC 2.9
Netlify link:
> docs: GRPCRoute guide

- app/_data/docs_nav_konnect.yml
Header was changed to "Vaults Object", but the nav link wasn't. Fixing that.
Netlify link: 
https://deploy-preview-5224--kongdocs.netlify.app/konnect/api/runtime-groups-config/#vaults-object
> Fix Konnect nav link for vaults

- app/_hub/kong-inc/correlation-id/_index.md
the `sent_` prefixed headers are the headers returned by kong to the client. Without that prefix, it will refer to the header sent to the backend. Since the former ones are only available if the "echo to client" checkbox is ticked, this is the safer option for the example.
Netlify link:
> fix(correlation-id): example log correct header

- Makefile
Make ruby check fail instead of printing a warning when the ruby version doesn't match the required one
Netlify link:
> Make ruby check fail instead of printing a warning

- app/_hub/kong-inc/statsd/_index.md
The current metric section in StatsD plugin is broken, https://docs.konghq.com/hub/kong-inc/statsd/#metrics
See:
It should be a table like this:
Also, the CloudWatch link syntax is invalid. 
Netlify link:
> The metric's section in StatsD plugin doesn't render a table

- app/konnect/getting-started/app-registration.md
This information is stale, so I deleted the sentence. More detail is in https://docs.konghq.com/konnect/dev-portal/applications/enable-app-reg/#support-for-any-runtime-group, maybe a link should be added?
Netlify link:
> fix(getting-started) app reg is now on all runtimes

- app/_data/docs_nav_deck_1.10.x.yml
- app/_data/docs_nav_deck_1.11.x.yml
- app/_data/docs_nav_deck_1.12.x.yml
- app/_data/docs_nav_deck_1.13.x.yml
- app/_data/docs_nav_deck_1.14.x.yml
- app/_data/docs_nav_deck_1.15.x.yml
- app/_data/docs_nav_deck_1.16.x.yml
- app/_data/docs_nav_deck_1.7.x.yml
- app/_data/docs_nav_deck_1.8.x.yml
- app/_data/docs_nav_deck_1.9.x.yml
Adding 
```
- text: Entities Managed by decK
url: /reference/entities
```
To all single-sourced decK navs. The topic applies the whole way back.
This way, we avoid broken links in earlier versions (eg the broken link to "Entities Managed by decK" here: https://docs.konghq.com/deck/1.16.x/guides/backup-restore/). 
Netlify link:
> Backport deck entities topic to avoid broken links

- app/_src/deck/reference/entities.md
Added a note for `document_objects` as being the one sub-entity for services that isn't managed by decK.
**Note:** We also don't have the `document_objects` entity documented in our Admin API doc; in fact, it's purposely not generated, if you look at `admin_api.lua`: https://github.com/Kong/kong-ee/blame/master/autodoc/admin-api/data/admin-api.lua#L1177
It looks like there was a start to a project to add EE endpoints to the Admin API doc, and it stalled.
I think we should wait to revisit that until we have a spec.
https://konghq.atlassian.net/browse/DOCU-2985
Netlify link: https://deploy-preview-5209--kongdocs.netlify.app/deck/latest/reference/entities/
> [DOCU-2985] Mention document_objects as not managed by decK

- app/_hub/kong-inc/opentelemetry/_index.md
According to issue reporter, the span must be closed, otherwise you get a 400.
https://konghq.atlassian.net/browse/DOCU-2837
Netlify link: https://deploy-preview-5207--kongdocs.netlify.app/hub/kong-inc/opentelemetry/
> [DOCU-2837] Fix OpenTelemetry plugin example

- app/_hub/kong-inc/response-transformer/_index.md
> Ignored if the header is already set.
Use `v2` to highlight fact that `v2` is ignored because header already set
Docs
> fix: align examples to behaviour of add.headers

- app/_data/docs_nav_kic_2.9.x.yml
- app/_src/kubernetes-ingress-controller/guides/overview.md
nav updated for KIC 2.9 upcoming release. This update is needed to be coherent with the titles we already have for `TCPRoute` and `UDPRoute`.
Netlify link:
> docs(kic): update kic 2.9 nav

- app/_includes/nav-v2.html
Fix cta link, the url was being replaced in the [A/B test script](https://github.com/Kong/docs.konghq.com/commit/c567f615dbda1c88a4e6a0e1946f3d42e1928be6#diff-e6cf23c02e7353eb5dd94f2ccfd70a56df997e15454f12fbaf439e49bf7efcbf) 
Netlify link:
> Fix top-cta link

- app/_hub/kong-inc/datadog-tracing/_index.md
Adding missing Enterprise tag for Datadog Tracing plugin.
Issue reported in Slack: https://kongstrong.slack.com/archives/CDSTDSG9J/p1678200127324889
Netlify link:
> Datadog plugin fix: add enterprise tag

- app/_src/gateway/install/kubernetes/kubectl.md
fixed the kubectl apply URL with prefix v
What did you change and why? There is a typo in the URL which is navigating to page Not Found
https://discuss.konghq.com/t/incorrect-url-to-all-in-one-dbless-yaml-oss-version/11267
Netlify link: https://deploy-preview-5261--kongdocs.netlify.app/
> fixed the url for OSS

- app/_src/kubernetes-ingress-controller/references/supported-router-flavors.md
As per the [source code](https://github.com/Kong/kong-ee/blob/master/kong/conf_loader/init.lua#L507), the accepted values for `router_flavor` are `"traditional"`, `"traditional_compatible"` and `"expressions"`, not `"expression"`.
Netlify link:
> fix(kic): router_flavor mode

- app/_src/gateway/kong-enterprise/cp-outage-handling.md
Typo in Configure Data Plane Resilience
As we exporting into GCP bucket, the environment variable should be `EXPORT` instead of `IMPORT`. Other options of storage i.e AWS S3 uses `EXPORT` too.
Netlify link:
> Typo in Configure Data Plane Resilience

- tools/broken-link-checker/lib/src-to-urls.js
Any absolute URL would resolve to `/<product>/<release>` in the previous fix. This inverts the logic so that the URL is used rather than the prefix.
It previously worked as `url == prefix` for index pages (which is what I set out to fix)
N/A
> Fix absolute links in link checker

- app/konnect/runtime-manager/runtime-instances/install.md
- app/konnect/runtime-manager/runtime-instances/upgrade.md
- app/konnect/runtime-manager/troubleshoot.md
- app/konnect/runtime-manager/version-compatibility.md
Splitting the runtime manager troubleshooting topic into two: general troubleshooting and version compatibility, to make the version compatibility info more discoverable.
https://konghq.atlassian.net/browse/DOCU-3031
Netlify link:
> [DOCU-3031] Split RM troubleshooting topic

- app/_src/gateway/install/docker/index.md
Document how to start kong in Docker in `read-only` mode
Netlify link: 
[KAG-852]
[KAG-852]: https://konghq.atlassian.net/browse/KAG-852?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(*): docker read-only mode docs

- app/gateway-oss/2.1.x/kong-for-kubernetes/install.md
- app/gateway-oss/2.2.x/kong-for-kubernetes/install.md
- app/gateway-oss/2.3.x/kong-for-kubernetes/install.md
- app/gateway-oss/2.4.x/kong-for-kubernetes/install.md
- app/gateway-oss/2.5.x/kong-for-kubernetes/install.md
- app/gateway/2.6.x/install-and-run/kubernetes.md
- app/gateway/2.7.x/install-and-run/kubernetes.md
- app/gateway/2.8.x/install-and-run/kubernetes.md
- app/kubernetes-ingress-controller/1.0.x/deployment/kong-enterprise.md
- app/kubernetes-ingress-controller/1.1.x/deployment/kong-enterprise.md
- app/kubernetes-ingress-controller/1.2.x/deployment/kong-enterprise.md
- app/kubernetes-ingress-controller/1.3.x/deployment/kong-enterprise.md
- app/kubernetes-ingress-controller/2.0.x/deployment/kong-enterprise.md
- app/kubernetes-ingress-controller/2.1.x/deployment/kong-enterprise.md
- app/kubernetes-ingress-controller/2.2.x/deployment/kong-enterprise.md
- archive/gateway-oss/1.4.x/kong-for-kubernetes/install.md
- archive/gateway-oss/1.5.x/kong-for-kubernetes/install.md
- archive/gateway-oss/2.0.x/kong-for-kubernetes/install.md
Fixing links that were missing the `v` prefix for the KIC version. 
Contributor caught one of them here: https://github.com/Kong/docs.konghq.com/pull/5261
Expanding on the fix - didn't think to search the whole site in the original PR, but there are a lot more broken links than just that one.
@pmalek I'm throwing this one on `main`, you might want to update the 2.9 branch after this.
Netlify link:
> Fix KIC install links

- app/_src/mesh/features/ubi-images.md
- app/mesh/1.6.x/features/ubi-images.md
This is about KM and the values are for the KM chart, see the Helm install instructions otherwise (release is called `kong-mesh`, NS is `kong-mesh-system`, etc).
[Rendered](https://deploy-preview-5278--kongdocs.netlify.app/mesh/latest/features/ubi-images/#usage)
> docs(mesh): don't refer to Kuma in UBI instructions

- app/_src/gateway/kong-manager/auth/index.md
I added this note: 
"Kong Manager does not directly offer 2FA, MFA, OTP or captcha/Recaptcha. However, if you configured Kong manager to use OIDC auth https://docs.konghq.com/gateway/latest/kong-manager/auth/oidc/configure/ then you could provide MFA etc via the OIDC provider."
As per this KB article: https://support.konghq.com/support/s/article/How-can-I-integrate-2FA-MFA-OTP-or-captcha-recaptcha-with-Kong-Manager 
It's not an uncommon question from customers, hence we created the KB above. 
However, perhaps it's better suited as a note in the docs, hence this PR. 
Netlify link:
> Add a note about integrating Kong Manager with MFA

- app/_data/docs_nav_contributing.yml
- app/_hub/_init/my-extension/_index.md
- app/contributing/markdown-rules.md
- app/contributing/notices.md
- app/contributing/plugin-docs.md
- app/contributing/style-guide.md
- app/contributing/user-interfaces.md
* Topic for user interfaces (draft, will need more work after)
* Third-party plugins
* Split out "admonitions" and called them "notices" (instead; the content was split out and not discoverable before
* Various cleanup and replacements
https://konghq.atlassian.net/browse/DOCU-2506
Netlify link:
> [DOCU-2506] Style guide updates

- .github/styles/kongplugins/plugin-ignore.txt
- app/_hub/kong-inc/proxy-cache-advanced/_index.md
- app/_hub/kong-inc/proxy-cache/_index.md
This PR adds documentation of `ignore_uri_case` parameter in the cache-proxy plugin added with PR https://github.com/Kong/kong/pull/10453.
Netlify link: https://deploy-preview-5270--kongdocs.netlify.app
> feat(proxy-cache): add ignore_uri_case to configuring cache-key uri to be handled as lowercase

- app/_src/gateway/key-concepts/routes/expressions.md
See KAG-925 and issue https://github.com/Kong/kong/issues/10387.
Netlify link:
> docs(expressions): use `--form-string` for curl

- app/_src/deck/reference/entities.md
Marking consumer groups as supported in 1.17.x and later versions, based on https://github.com/Kong/deck/blob/main/CHANGELOG.md#v1170.
Issue reported on Slack: https://kongstrong.slack.com/archives/CDSTDSG9J/p1678976430380409
Netlify link: 
Check the output to make sure the table renders correctly in both 1.16.x and earlier, and 1.17.x and later.
> decK: consumer groups support

- app/_data/docs_nav_kic_2.4.x.yml
This PR fixes a missing nav section in 2.4 docs. This came up when changing files for 2.9 release: https://github.com/Kong/docs.konghq.com/actions/runs/4448486330/jobs/7811364792#step:5:168
Netlify link:
> chore(kic): add missing nav section for gateway API in 2.4

- app/_hub/kong-inc/graphql-rate-limiting-advanced/_index.md
- app/_hub/kong-inc/rate-limiting-advanced/_index.md
- app/_hub/kong-inc/rate-limiting-advanced/_v1.md
- app/_hub/kong-inc/rate-limiting/_index.md
- app/_hub/kong-inc/response-ratelimiting/_index.md
- app/_src/gateway/production/deployment-topologies/hybrid-mode/index.md
Default rate limiting strategy in Konnect is now `local`, the same as in all other places. It no longer needs a special callout.
Change happened in 3.0. This PR is a continuation of https://github.com/Kong/docs.konghq.com/pull/4378, these lines were missed.
Also removed any mention of Konnect from the GraphQL Rate Limiting advanced plugin, as this plugin is not supported in Konnect.
Issue called out in Slack: https://kongstrong.slack.com/archives/CDSTDSG9J/p1678997282969009 and https://kongstrong.slack.com/archives/CDSTDSG9J/p1678951045262189
Netlify link:
> Fix default rate limiting strategy in Konnect

- app/_src/gateway/upgrade.md
- app/gateway/changelog.md
Adding enterprise plugin priority changes to 3.0 changelog and 3.0 upgrade guide.
Original entry only listed the OSS plugin changes.
Issue reported on Slack: https://kongstrong.slack.com/archives/C01888Q7PJ7/p1679336589204529
Netlify link:
> Fix: Plugin priority changelog for 3.0

- app/_src/gateway/admin-api/admin-api-3.0.x.md
- app/_src/gateway/admin-api/index.md
- app/gateway/2.8.x/admin-api/index.md
This is still in EE.
https://github.com/Kong/kong-ee/blob/master/kong/api/routes/certificates.lua
> [Fix] Add passphrase param to certificates object

- app/_src/kubernetes-ingress-controller/guides/using-ingress-with-grpc.md
The `GRPCRoute` guide has been improved with a new section related to enabling the `GatewayAlpha` feature gate in KIC.
Netlify link:
> GatewayAlpha feature-gate added to grpc guide

- app/_data/konnect_errors.yml
- app/konnect/api/errors.md
Add a page documenting errors from the Konnect API.
This will be used with kongapi.info
kongapi.info/konnect/unauthenticated will be redirected to docs.konghq.com/konnect/api/errors#unauthenticated etc
The `konnect_errors` file will be maintained by Konnect engineering as new errors are added
Netlify link: https://deploy-preview-5329--kongdocs.netlify.app/konnect/api/errors/
> Add initial draft of Konnect API errors

- app/_hub/kong-inc/app-dynamics/_index.md
- app/_hub/kong-inc/app-dynamics/versions.yml
The AppDynamics plugin is not going to be bundled with Kong in the foreseeable future, and we shouldn't have to add a new entry for `bundled:false` with every release. Setting it directly in the plugin's front matter will apply it to all versions of the plugin.
Netlify link:
> AppDynamics: Set `bundled:false` to default for all versions

- app/_src/gateway/kong-manager/configuring-to-send-email.md
Made it a bit clearer that these properties are aimed to be deployed with the Control Plane configuration in case of Hybrid deployment. This came up as a question from a customer who wasn't sure where to place the configurations, whether it was on the CP or DP.
> Clarified where admin SMTP properties are set in Hybrid deployment

- app/_data/docs_nav_mesh_2.1.x.yml
- tests/edit_link.test.js
- Updated the 2.1 Mesh nav file to point to the files that were moved in the Kuma repo as part of the new Kuma in Production section (https://github.com/kumahq/kuma-website/pull/1245) 
- I'll make a separate PR to add the new Kuma in Production section to the 2.2 nav 
DOCU-2857
Netlify link: 
❗ To review:
- Go to the 2.1 nav and click on some of the pages that had their `src` updated, it should take you to the correct file.
> Update src files that are in the new Kuma in Production section

- app/_data/docs_nav_gateway_2.8.x.yml
- app/_data/docs_nav_gateway_3.0.x.yml
- app/_data/docs_nav_gateway_3.1.x.yml
- app/_src/gateway/support/index.md
- app/gateway/2.8.x/support-policy.md
Reported on [slack](https://kongstrong.slack.com/archives/CDSTDSG9J/p1678325245916159)
I changed the nav bars to pull from the same src file being used in 3.2 for 2.8, 3.0, and 3.1.
> [Fix] Update Support policy table

- app/_layouts/docs-v2.html
- app/_src/kubernetes-ingress-controller/guides/using-multiple-backends.md
Added the ability to add more information to the stability banner.
Netlify link: https://deploy-preview-5348--kongdocs.netlify.app/kubernetes-ingress-controller/latest/guides/using-multiple-backends/
> Add the ability to customise the stability banner

- app/_data/kong_versions.yml
Gateway 3.2.2 is out. The 3.2.1 release isn't available for Alpine
Netlify link:
> Update Kong Gateway patch version

- app/_hub/kong-inc/http-log/_index.md
Added config schema explanation, as per PR https://github.com/Kong/kong/pull/10533
The PR adds just one config option to the restricted list available for http-log's "content_type" schema entry.
Target is for it to end up at this page, upon the next Kong minor release: https://docs.konghq.com/hub/kong-inc/http-log/
Netlify link:
> docs(http-log): plugin schema update for 3.3

- app/_hub/imperva/imp-appsec-connector/_index.md
- app/_includes/header.html
- app/_includes/hub_cards.html
- app/_layouts/extension.html
* Enabled the compatible versions list for third party plugins
* Enabled enterprise badges for third-party plugins
* Changed 3rd party banner to read "Partner Plugin" instead of "Community Plugin", based on our new partner plugin program approach.
https://konghq.atlassian.net/browse/DOCU-3145
* Test on the Imperva plugin: 
* https://deploy-preview-5362--kongdocs.netlify.app/hub/ (look at the Imperva tile)
* https://deploy-preview-5362--kongdocs.netlify.app/hub/imperva/imp-appsec-connector/
* Check any other third-party plugins on the plugin hub to make sure that the version compatibility list appears in the side nav, eg: https://deploy-preview-5362--kongdocs.netlify.app/hub/wallarm/wallarm/ 
* And check that Kong plugins _don't_ have this list.
> [DOCU-3145] Third-party plugin layout adjustments

- app/_src/gateway/kong-enterprise/secrets-management/index.md
Added a table to the secrets documentation that lists all plugins with referenceable fields + the specific fields.
* Note: The vault auth plugin has a manually-added table row because the referenceable values for that plugin don't appear in the config table. This is because the config is nested, and our tables don't always list nested configs. This will be fixed once the plugin hub redesign stage 1 is complete, and we'll have to remove manually-added this table row then.
https://konghq.atlassian.net/browse/DOCU-3149
https://deploy-preview-5370--kongdocs.netlify.app/gateway/latest/kong-enterprise/secrets-management/#what-can-be-stored-as-a-secret
> [DOCU-3149] Referenceable plugin fields table

- app/contributing/markdown-rules.md
Follow-up to https://github.com/Kong/docs.konghq.com/pull/5348. 
Adding the new `stability_banner` option to our contributing docs.
Also adding the `badge` option, which was missing, and a link to more info about `content_type`. 
Netlify link: https://deploy-preview-5364--kongdocs.netlify.app/contributing/markdown-rules/
> Contributing guide: add missing front matter options

- app/_layouts/extension.html
Added a banner for any `plus` plugins to show that they're available free on Konnect during the trial period.
Applies to all `page.plus` plugins
Netlify link: https://deploy-preview-5386--kongdocs.netlify.app/hub/kong-inc/openid-connect/
> Add CTA for plus plugins to drive Konnect signups

- app/_src/gateway/production/logging/update-log-level-dynamically.md
Correct port number for dynamic log level changes update-log-level-dynamically.md. PUT requests listed port 59191; should be 8001;
Port number for 2 example Admin API requests was listed as 59191, but needed to be 8001 (default Admin API port)
Just try the suggested dynamic logging level changes with port 59191 and again with 8001 and you will see 8001 is correct.
> Correct update-log-level-dynamically.md

- app/_data/kong_versions.yml
- app/_data/tables/support/gateway/versions/32.yml
- app/gateway/changelog.md
Version bump and changelog for 3.2.2.1.
Alpine ARM package is available as of 3.2.2.1, so set it as compatible in the 3.2 table.
https://konghq.atlassian.net/browse/DOCU-3007
https://konghq.atlassian.net/browse/DOCU-3155
Netlify links:
https://deploy-preview-5393--kongdocs.netlify.app/gateway/latest/support-policy/
https://deploy-preview-5393--kongdocs.netlify.app/gateway/changelog/
> [DOCU-3155][DOCU-3007] Release: Gateway 3.2.2.1

- .github/workflows/sync-submodules.yml
The action is failing because github no longer sets all the permissions to `GITHUB_TOKEN`, just read access.
This adds write permissions to it.
Netlify link:
> Fix sync-submodules permissions

- app/_includes/nav-v2.html
- app/_layouts/extension.html
using a different utm campaign
Netlify link:
> updating utm campaign

- app/_assets/stylesheets/page.less
- app/_src/gateway/index.md
With the addition of the cloud quickstart the tiles got pushed to 2 lines on a 1080p screen. This change makes them uniformly distributed
Netlify link: /gateway/latest/
> Fix grid tiles on Gateway index page to be max 3 items wide

- app/_assets/stylesheets/page.less
- app/_data/docs_nav_konnect.yml
- app/konnect/runtime-manager/runtime-instances/index.md
* Removed hover & focus pseudoclasses from unlinked install grid tiles. The existence of a hover class was creating the illusion of clickable tiles, when the tiles are just visual. Hover classes are now applied only when there's a link on the tile.
* Added a short description of the runtime instance installation options and a line on how to get to them.
* Based on user testing (John and Amy), removing the "Installation Options" title from the page wasn't the right call, since it's not clear that installation options will appear on the overview. Reverted the title, but kept the URL the same.
Netlify link: https://deploy-preview-5400--kongdocs.netlify.app/konnect/runtime-manager/runtime-instances/
> Tile grid style fix + konnect runtime instances improvements

- .github/styles/kong/kongterms.yml
- app/_assets/javascripts/app.js
- app/_data/tables/plugin_index.yml
- app/_includes/hub-examples.html
- app/_layouts/extension.html
- app/_layouts/landing-page.html
There are a few places where the old "Konnect Cloud" name is still in use, so cleaning that out. 
Official, full product name is Kong Konnect: https://konghq.com/products/kong-konnect.
Netlify link:
> Clear out old Konnect Cloud product name

- app/konnect/reference/labels.md
Came up on Slack that we don't have filtering/search by labels yet. Removing the line from the docs.
https://kongstrong.slack.com/archives/C01888Q7PJ7/p1680615706054559
Netlify link: https://deploy-preview-5404--kongdocs.netlify.app/konnect/reference/labels/
> Konnect labels: remove info about filtering and search

- app/_assets/stylesheets/hub-landing-page.less
- app/_includes/hub_cards.html
- app/_layouts/extension.html
- app/hub/index.html
Various updates stemming from 3rd party plugin feedback.
* Adjusted banner to call out publisher name instead of just saying "a third-party contributor"
* Fix plugin hub title so that it appears as "Kong Plugin Hub" in google search, instead of just "Kong Hub"
* Filter adjustments:
* "Konnect" filter is now "Bundled with Konnect"
* Added a "Bundled with Gateway" filter
* "Subscription tiers" filter is now "Kong subscription tiers" to hopefully make it clearer that it only refers to Kong plugins
[Filters on Plugin Hub](https://deploy-preview-5401--kongdocs.netlify.app/hub/)
Banner on 3rd party plugin should contain publisher name, eg [Imperva](https://deploy-preview-5401--kongdocs.netlify.app/hub/imperva/imp-appsec-connector/)
> 3rd party plugins banner + plugin hub filters

- app/_data/docs_nav_mesh_2.2.x.yml
- Added the new Mesh in Production overview page to the 2.2 nav. This PR is the one that adds it on the Kuma side: https://github.com/kumahq/kuma-website/pull/1246 
DOCU-2858
Netlify link:
> [DOCU-2858] Add Mesh Overview topic to the 2.2 nav

- app/_data/docs_nav_mesh_2.0.x.yml
- app/_data/docs_nav_mesh_2.1.x.yml
-  I updated the 2.1 and 2.0 navs with the correct file path based on the files that I moved as a result of https://github.com/kumahq/kuma-website/pull/1266.
DOCU-2867
Netlify link:
> Add revised Reference section to the 2.1.x nav

- app/_data/docs_nav_mesh_2.0.x.yml
- app/_data/docs_nav_mesh_2.1.x.yml
- app/_data/docs_nav_mesh_2.2.x.yml
- I updated the Kuma Reference section here (https://github.com/kumahq/kuma-website/pull/1266) and moved a few files, so I also fixed the Mesh nav to match. I did this as part of the Kuma IA rework.
DOCU-2867
Netlify link:
> [DOCU-2867] Add the revised Mesh Reference section to the 2.2 nav

- app/konnect/runtime-manager/runtime-instances/index.md
- app/konnect/runtime-manager/troubleshoot.md
This PR adds the previously removed section back to the runtime IA installation options topic. It also adds it to the runtime instances troubleshooting topic.
> [Fix] Forward proxy CP info for Konnect

- app/_src/kubernetes-ingress-controller/references/feature-gates.md
This PR fixes the table of current feature gates and their defaults in KIC.
Netlify link:
> fix(kic): update KIC's feature gates

- app/_hub/kong-inc/route-transformer-advanced/_index.md
config.path is an string. Example value should also be an string, not an array.
current declarative example provides a   `(message: "schema violation (config.path: expected a string)")`  error while using deck
> fix route-transformer-advanced config.path example

- app/_src/gateway/key-concepts/routes/index.md
This PR updates the documentation to reflect the change in https://github.com/Kong/kong/pull/10615, which makes traditional_compat mode behave like the traditional router with respect to priorities of routes having multiple paths.
KAG-727
Netlify link:
> Fix description of routing priorities with multiple paths

- app/_src/kubernetes-ingress-controller/guides/using-gateway-discovery.md
We should recommend using client verification when GD deployment is used. Issue: https://github.com/Kong/kubernetes-ingress-controller/issues/3833
Netlify link: https://deploy-preview-5415--kongdocs.netlify.app/
> update Gateway Discovery tutorial with client verification

- app/konnect/analytics/index.md
- app/konnect/analytics/reference.md
- app/konnect/analytics/use-cases.md
Analytics capabilities are available for all tiers and are only restricted by retention today (like described in the overview page). Therefore, I removed all occurrences of the "PLUS" badge across the Analytics pages.
> removed plus badge from various analytics pages

- app/_hub/kong-inc/openid-connect/_index.md
There was no real information about PKCE requirements if it's needed to be used. Adding more details to show that ```code_challenge_methods_supported``` is a requirement in the IdP response if PKCE is needed to be used in Kong's OIDC plugin. This stems from a customer support case.
> Added note about PKCE usage with OIDC plugin

- app/_hub/kong-inc/oauth2/_index.md
Adds a warn section to Oauth2 Resource Owner Password Credentials Grant
section.
Related with https://github.com/Kong/kong/issues/1752 (that issue advocates for removing username and password, we added a warning for the whole section instead. The alternative would be removing that whole section entirely)
Netlify link:
> docs(oauth2): Warn about Resource Owner Password Credentials Grant

- app/_includes/head.html
- app/_layouts/default.html
- app/_src/gateway/index.md
- app/contributing/markdown-rules.md
- tests/descriptions.test.js
This allows us to customise the meta description for each page. It's marked as required in the style guide, but only for new pages going forwards. Existing pages will be updated on a best-effort basis
I've updated /gateway/latest/
Here's a local test I did on the Ubuntu install page too:
> Add support for `description` in frontmatter

- app/_src/gateway/reference/configuration.md
Added 'seconds' as the unit for worker_state_update_frequency. This was needed as a customer had asked questions about the unit/metric for this value and it was agreed that it was unclear from the documentation what the unit used is.
N/A
> Added 'seconds' as the unit for worker_state_update_frequency

- app/_assets/stylesheets/navtabs.less
- app/_src/gateway/install/linux/ubuntu.md
Initial attempt at a refactored Ubuntu install page.
The script has been tested on Ubuntu 22.04 and 20.04 (both LTS) on AWS, and on a local docker container.
I've intentionally removed the include as we have dedicated pages that I've linked to in next steps
Netlify link: https://deploy-preview-5389--kongdocs.netlify.app/gateway/3.2.x/install/linux/ubuntu/
> Update Ubuntu install instructions to use install script

- app/_includes/md/kic/http-test-routing-resource.md
- app/_includes/md/kic/http-test-routing.md
- app/_includes/md/kic/http-test-service.md
Switch kubectl apply -f https://bit.ly/echo-service for a Kong maintained `go-echo` service which has ARM (M1) support
Netlify link: /kubernetes-ingress-controller/2.9.x/guides/getting-started/
> Update KIC examples to use kong/go-echo for ARM support

- app/_hub/kong-inc/response-transformer-advanced/_index.md
- app/_hub/kong-inc/response-transformer/_index.md
Fixing broken HTML tags in response transformer plugin docs.
Issue reported on slack.
Netlify link: 
https://deploy-preview-5480--kongdocs.netlify.app/hub/kong-inc/response-transformer/
https://deploy-preview-5480--kongdocs.netlify.app/hub/kong-inc/response-transformer-advanced/
> Response transformer plugins: fix broken formatting

- app/mesh/installer.sh
Kuma's `installer.sh` can accept args, so should KM's
> feat(mesh/installer.sh): pass arguments to kuma installer.sh

- app/konnect/api/identity-management/identity-integration.md
- app/konnect/api/portal-auth/portal-rbac-guide.md
- app/konnect/api/runtime-groups-config/index.md
- app/konnect/network.md
Replacing region in Konnect API request examples to either a placeholder or `global`, as appropriate. When region is explicitly set to `us` in examples where other placeholders exist, the user gets confused and the requests are wrong for `eu` users.
https://konghq.atlassian.net/browse/DOCU-3192
Netlify link:
> [DOCU-3192] Use generic region in Konnect API examples

- app/_src/gateway/reference/router-expressions-language.md
> docs(router/expressions): fix the description of net.protocol

- app/_hub/kong-inc/aws-lambda/_index.md
This PR adds the docs of the new field of the aws-lambda plugin, `disable_https`.
Just FYI we used to have a PR in 3.2 but reverted before 3.2 release because this feature has been renamed: https://github.com/Kong/docs.konghq.com/pull/4877
Netlify link:
> docs(aws-lambda): add new disable_https field

- app/_hub/kong-inc/jwt/_index.md
- app/_hub/kong-inc/ldap-auth/_index.md
- app/_hub/kong-inc/oauth2/_index.md
- app/_hub/kong-inc/proxy-cache-advanced/_index.md
- app/_hub/kong-inc/proxy-cache/_index.md
- app/_hub/kong-inc/rate-limiting/_index.md
- app/_hub/kong-inc/request-size-limiting/_index.md
Follow-up to https://github.com/Kong/docs.konghq.com/pull/5480. Raw html was continuing to cause problems when used in front matter. Fixing that.
Got rid of two alert divs that refer to very, very old versions of Gateway.
Netlify links:
https://deploy-preview-5505--kongdocs.netlify.app/hub/kong-inc/oauth2/
https://deploy-preview-5505--kongdocs.netlify.app/hub/kong-inc/jwt/
https://deploy-preview-5505--kongdocs.netlify.app/hub/kong-inc/ldap-auth/
https://deploy-preview-5505--kongdocs.netlify.app/hub/kong-inc/proxy-cache/
https://deploy-preview-5505--kongdocs.netlify.app/hub/kong-inc/proxy-cache-advanced/
https://deploy-preview-5505--kongdocs.netlify.app/hub/kong-inc/rate-limiting/
https://deploy-preview-5505--kongdocs.netlify.app/hub/kong-inc/request-size-limiting/
> Clear out div tags from plugin front matter

- app/_src/gateway/production/deployment-topologies/index.md
Docs referred to hybrid mode (below) when in fact they were described (above), so I just edited that sentence in docs for deployment topologies.
Visit documentation page and verify it says "above" instead of "below" in deployment technologies page.
> Fixed reference to hybrid mode in docs

- app/_src/gateway/production/tracing/api.md
We changed the default value of tracing_sampling_rate in 3.3 (from 1 to 0.01). This doc still says that de default is 1. Instead of changing it to the new default, I removed all mentions to default from here.
Our auto-generated docs for the configuration change should pick up the new default value.
FTI-5032
--
Netlify link: 
[FTI-5032]: https://konghq.atlassian.net/browse/FTI-5032?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs(3.3) remove references to 'default tracing_sampling_rate'

- .github/styles/kongplugins/auto-ignore.txt
- app/_hub/kong-inc/acme/_index.md
correspond to [Kong/kong#10562](https://github.com/Kong/kong/pull/10562)
`namespace` will be treated as a prefix of key and is default to empty string `""` for backward compatibility. `namespace` must not be prefixed with any of the reserved words.
[KAG-615](https://konghq.atlassian.net/browse/KAG-615)
Netlify link: 
[KAG-615]: https://konghq.atlassian.net/browse/KAG-615?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs(acme): support redis namespace

- app/_redirects
- app/_src/gateway/install/linux/amazon-linux.md
- app/_src/gateway/install/linux/centos.md
- app/_src/gateway/install/linux/debian.md
- app/_src/gateway/install/linux/rhel.md
- app/_src/gateway/install/linux/ubuntu.md
- app/moved_urls.yml
https://kongstrong.slack.com/archives/CDSTDSG9J/p1683122758154309
- Added a link to https://docs.konghq.com/gateway/latest/support-policy/#supported-versions in all of the installation docs. Replacing the broken link where appropriate. 
- Rewrote redirects that pointed to the broken link. 
- Added redirect for the broken link to https://docs.konghq.com/gateway/latest/support-policy/#supported-versions
> [fix] Broken link in Linux installation docs

- app/_src/gateway/kong-plugins/graphql.md
The referenced GraphQL example is not supported or maintained by Kong.  In additton, "New upstream" was unclear to the reader
Netlify link:
> fix(graphql) Removes reference to an unsupported GraphQL Example

- app/konnect/runtime-manager/runtime-instances/renew-certificates.md
It's possible to renew DP certs with `openssl` but we didn't document the process publicly. 
Netlify link: https://deploy-preview-5518--kongdocs.netlify.app/konnect/runtime-manager/runtime-instances/renew-certificates/#:~:text=Alternatively%2C%20you%20can%20generate%20a%20certificate%20locally
> Add Konnect DP Certificate renewal with OpenSSL instructions

- app/_hub/kong-inc/proxy-cache-advanced/_index.md
- app/_hub/kong-inc/proxy-cache/_index.md
Netlify link: 
[FTI-1131]
[FTI-1131]: https://konghq.atlassian.net/browse/FTI-1131?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(proxy-cache): add wildcard and parameter match support for content_type

- app/_hub/kong-inc/rate-limiting-advanced/_index.md
Clarify how the `namespace` field works in RLA in response to feedback from @mrwanny 
Netlify link: https://deploy-preview-5526--kongdocs.netlify.app/hub/kong-inc/rate-limiting-advanced/#:~:text=0.02%20seconds%20(20ms).-,config.namespace
> Add shared rate limit example to Rate Limiting Advanced docs

- app/_hub/kong-inc/statsd/_index.md
* Adding info on where to find your lua_shared_dicts
* Changing the variable label in the syntax to `lua_shared_dict` so that the reader would know what to look for; shdict_name is a local variable only and doesn't help them find the right info
I found that you can figure out which shared dicts you have in your Kong env using the `/status` endpoint, so I ended up leaving out info on custom shared dicts. It doesn't seem relevant to talk about custom nginx templates in this context.
Issue reported on [Slack](https://kongstrong.slack.com/archives/CDSTDSG9J/p1682692187562059).
Netlify link: https://deploy-preview-5522--kongdocs.netlify.app/hub/kong-inc/statsd/#metrics
> StatsD plugin: Clarify shdict_name variable

- app/_src/kubernetes-ingress-controller/faq.md
- app/kubernetes-ingress-controller/1.0.x/faq.md
- app/kubernetes-ingress-controller/1.1.x/faq.md
- app/kubernetes-ingress-controller/1.2.x/faq.md
- app/kubernetes-ingress-controller/1.3.x/faq.md
- app/kubernetes-ingress-controller/2.0.x/faq.md
- app/kubernetes-ingress-controller/2.1.x/faq.md
- app/kubernetes-ingress-controller/2.2.x/faq.md
Currently links to K8s docs in that FAQ are broken, leads to `404` empty page
This PR fixes the above.
> fix(kic/faq): replace broken links for K8s docs

- app/_data/docs_nav_konnect.yml
The docs under the Administer nav section in Konnect have `org-management` as part of their URL, but there's no nav item for it. This can be confusing.
Issue reported in [Slack](https://kongstrong.slack.com/archives/CDSTDSG9J/p1683210668941149).
~Do not merge yet, Jackie is going to do a review of the content structure of this section.~ Ready to go.
Netlify link:
> Make Org Management a Konnect nav item

- app/_plugins/filters/indent_filter.rb
[Jira ticket](https://konghq.atlassian.net/browse/DOCU-3208)
It prepends 4 spaces to every line
It also fixes an edge case regarding code snippets being part of the content to be indented. Previously, it was adding an extra newline to the code snippet. This is the same fix we added to Kuma, see https://github.com/kumahq/kuma-website/pull/1117
[Netlify link](https://deploy-preview-5540--kongdocs.netlify.app/mesh/latest/production/secure-deployment/api-server-auth/#signing-key-rotation). Verify that the tabs under `Signing key rotation` section are rendered correctly.
> Fix indentation filter

- app/_data/docs_nav_gateway_3.3.x.yml
- app/_src/gateway/production/monitoring/health-check.md
- app/_src/gateway/production/monitoring/index.md
- app/_src/gateway/production/monitoring/readiness-check.md
New page + tutorial tempalte for KAG-76. Can decide if this is the right location when reviewing the draft content.
DOCU-2921
Netlify link: https://deploy-preview-5419--kongdocs.netlify.app/gateway/latest/production/monitoring/health-check/
> [DOCU-2921] Status endpoint + Kong health  check

- app/_src/gateway/production/logging/update-log-level-dynamically.md
Timeout support for dynamic log levels
KAG-5
DOCU-2903
Netlify link: https://deploy-preview-5550--kongdocs.netlify.app/gateway/latest/production/logging/update-log-level-dynamically/
> Timeout support for dynamic log levels

- app/_data/tables/support/gateway/packages.yml
- app/_data/tables/support/gateway/versions/33.yml
- app/_src/gateway/install/linux/amazon-linux.md
- app/_src/gateway/install/linux/rhel.md
- app/_src/gateway/install/linux/ubuntu.md
- app/_src/gateway/support/browser.md
- app/_src/gateway/support/index.md
- app/_src/gateway/support/third-party.md
- I added Amazon Linux 2023 to the 3.3 supported versions page
- I added the new Linux 2023 tab to the Amazon Linux install page
DOCU-3167
Netlify link: 
- https://deploy-preview-5536--kongdocs.netlify.app/gateway/latest/install/linux/amazon-linux/
- https://deploy-preview-5536--kongdocs.netlify.app/gateway/latest/support-policy/
> [DOCU-3167] Add Amazon Linux 2023 to support page

- app/_data/tables/support/gateway/versions/33.yml
- app/_src/gateway/support/browser.md
- app/_src/gateway/support/index.md
- app/_src/gateway/support/third-party.md
Adding 3.3 tabs for all of the support pages + Amazon RDS support.
Netlify link: https://deploy-preview-5569--kongdocs.netlify.app/gateway/latest/support/third-party/
https://deploy-preview-5569--kongdocs.netlify.app/gateway/latest/support/browser/
https://deploy-preview-5569--kongdocs.netlify.app/gateway/latest/support-policy/
Make sure all the support pages have 3.3 tabs and that Amazon RDS appears on the Postgres tile.
> Support page updates for 3.3

- app/_data/kong_versions.yml
- app/_src/gateway/kong-manager/auth/oidc/mapping.md
- app/gateway/changelog.md
Changelog and version bump for Gateway 3.1.1.4.
Also adding the new `admin_auto_create` parameter, which is introduced in this release. This isn't a breaking change, as the default behavior of the parameter matches the behavior that occurred before it became configurable.
https://konghq.atlassian.net/browse/DOCU-3179
Netlify link:
> Release: Gateway 3.1.1.4

- app/_hub/kong-inc/oas-validation/_metadata.yml
- app/_plugins/generators/plugin_single_source/pages/base.rb
- app/_plugins/generators/plugin_single_source/pages/overview.rb
Make the Plugin Hub category breadcrumbs use the nice title rather than `analytics-monitoring` etc
I couldn't see where to add tests - let me know where to add them. Feel free to refactor if there's a better way to achieve this too.
Netlify link: /hub/kong-inc/datadog/
> Hub breadcrumbs

- app/_assets/stylesheets/pages/extension.less
- app/_hub/kong-inc/serverless-functions/_changelog.md
- app/_hub/kong-inc/serverless-functions/_index.md
- app/_hub/kong-inc/serverless-functions/_metadata.yml
- app/_hub/kong-inc/serverless-functions/versions.yml
- app/_hub/salt/salt/_metadata.yml
- app/_includes/plugins/schema.html
- app/_includes/plugins/schemas/field.html
- app/_includes/plugins/sidebar.html
- app/_plugins/generators/plugin_single_source/plugin/examples/kong.rb
- app/_plugins/generators/plugin_single_source/plugin/schemas/kong.rb
- spec/app/_plugins/generators/plugin_single_source/plugin/examples/kong_spec.rb
- spec/app/_plugins/generators/plugin_single_source/plugin/schemas/kong_spec.rb
- spec/templates/plugins/configuration_spec.rb
* Add missing descriptions to schemas
* Bring back `serverless-functions` plugins
* Fix an issue that rendered empty default values for some fields
* Add a link to `/hub/` on mobile to the sidenav
Netlify link:
> Plugin Hub: post-release fixes

- app/_includes/plugins/hub-examples/consumer.html
- app/_includes/plugins/hub-examples/kubernetes.html
- app/_includes/plugins/hub-examples/route.html
- app/_includes/plugins/hub-examples/service.html
Fix plugin hub examples for k8s configuration
Netlify link: I tested key-auth for service/route and rate-limiting for consumer
> Plugin k8s examples

- app/_plugins/generators/kuma_to_kong_mesh.rb
- spec/app/_plugins/generators/kuma_to_kong_mesh_spec.rb
- spec/fixtures/app/kuma-to-kong-mesh.md
Prevent the generator to replace kuma with kong-mesh on links that start with `/assets/`.
Netlify link:
> Fix kong mesh images

- app/_src/kubernetes-ingress-controller/troubleshooting.md
I couldn't work out how to enable the debug endpoint with Helm
Netlify link: /kubernetes-ingress-controller/latest/troubleshooting/#dumping-generated-kong-configuration
> Add Helm instructions when enabling KIC debug endpoint

- app/_src/gateway/upgrade-v2.md
- I fixed the upgrades table so it applies to 3.3 and added 3.3 breaking changes (copy/pasted with a few small changes from the changelog)
DOCU-3215
**Note:** I recreated this PR from #5557 because that one had issues with a rebase and added a bunch of unnecessary commits. 
Netlify link:
> [DOCU-3215] 3.3 upgrade guide

- app/_hub/moesif/kong-plugin-moesif/schemas/_index.json
Some of our default values changed for our latest plugin config. I've adjusted those values in the docs now.
Netlify link:
> adjusted defaults based on latest values for plugin

- app/_src/gateway/production/deployment-topologies/hybrid-mode/index.md
This is a fix for issue #5145 where it was mentioned we wrote data plane when we meant control plane in the Fault Tolerance section.
N/A
> Typo. Fix for #5145.

- tests/seo.test.js
GH Actions runners are underpowered. Increase the test timeout time (like we did in #4801)
Netlify link: N/A
> Increase timeout for flaky test

- app/_plugins/drops/sidenav.rb
- spec/app/_plugins/drops/plugins/sidenav_menu_item_spec.rb
Fix sidebar URLs that contain a URL fragment
Netlify link: Check the admin API URLs
> Fix trailing / on URLs with fragments

- app/_assets/javascripts/app.js
- app/_assets/stylesheets/badges.less
- app/_hub/imperva/imp-appsec-connector/_metadata.yml
- app/_hub/moesif/kong-plugin-moesif/_metadata.yml
- app/_hub/okta/okta/_metadata.yml
- app/_hub/salt/salt/_metadata.yml
- app/_hub/wallarm/wallarm/_metadata.yml
- app/_includes/header.html
- app/_includes/hub_cards.html
- app/_includes/plugins/badges.html
- app/_layouts/plugins/show.html
- app/_plugins/drops/plugins/badges.rb
Added a tech partner badge to the following plugins:
- Moesif
- Wallarm
- Imperva
- Salt
- Okta
https://konghq.atlassian.net/browse/DOCU-3229
Netlify link: https://deploy-preview-5596--kongdocs.netlify.app/hub/?support=third-party
> [DOCU-3229] Tech partner badges for third-party plugins

- app/_src/kubernetes-ingress-controller/concepts/deployment.md
Closes: https://github.com/Kong/kubernetes-ingress-controller/issues/4001
> kic: Gateway Discovery only works with DB-less deployments of Kong

- app/hub/plugins/compatibility/index.md
- app/konnect/compatibility.md
Fixes https://github.com/Kong/docs.konghq.com/issues/5606.
Also removing the "Deployment" section/heading, as it no longer exists on the Plugin Hub.
Netlify link: https://deploy-preview-5607--kongdocs.netlify.app/konnect/compatibility/#plugin-compatibility
> Fix konnect compatibility table

- app/_data/tables/support/gateway/packages.yml
- app/_data/tables/support/gateway/versions/32.yml
- app/_data/tables/support/gateway/versions/33.yml
- app/_includes/gateway-support.html
- app/_src/gateway/install/linux/amazon-linux.md
- app/_src/gateway/install/linux/ubuntu.md
- I added notes about AWS Graviton support to the Ubuntu and Amazon Linux install pages
- I also added a new column to the support table that shows which OSes support AWS Graviton processors
DOCU-3225
Netlify link: 
- /gateway/latest/support-policy/#supported-versions
- /gateway/latest/install/linux/amazon-linux/
- /gateway/latest/install/linux/ubuntu/
> [DOCU-3225] Add AWS Graviton support to OS support table

- app/_src/gateway/admin-api/index.md
* Added insomnia buttons for both specs
* reworked announcement
* grouped info in a table
Accepting any and all suggestions for table and announcement copy. It feels too verbose but I couldn't think of a better way to keep the "beta" in there, and "enterprise" and "OSS" respectively.
> Add insomnia button for specs

- .github/workflows/build-docs-pdf.yml
The PDF generation workflow doesn't work due to submodules being added
Netlify link: N/A
> Fix PDF generation with submodules

- app/_includes/md/enterprise/cassandra-deprecation.md
- app/_src/deck/faqs.md
- app/gateway/2.7.x/install-and-run/upgrade-oss.md
- app/gateway/2.8.x/install-and-run/upgrade-oss.md
- app/gateway/changelog.md
Cassandra support will be removed in 3.4
Netlify link: https://deploy-preview-5630--kongdocs.netlify.app/
> Update deprecation notice for Cassandra

- app/gateway/changelog.md
Reminders were a bit buried in their own section. Pulling up in the changelog per request from Tom.
Netlify link:
> Bring removal & deprecation reminders to top of changelog

- app/_plugins/drops/plugins/schema.rb
- spec/app/_plugins/drops/plugins/schema_field_spec.rb
Looks like the way to specify whether a field is `referenceable` differs a bit.
We have fields that have the property `referenceable`, e.g. acme:
```
{
"token": {
"referenceable": true,
"type": "string"
}
},
```
See https://github.com/fabianrbz/kong-plugins-docs-toolkit/blob/main/schemas/acme/3.2.x.json#L269-L274
Other fields, mostly of type `array` mark their elements as referenceable, e.g. request-transformer-advanced:
```
{
"body": {
"default": [
],
"type": "array",
"elements": {
"type": "string",
"referenceable": true
},
"description": "List of parameter `name:value` pairs. Rename the parameter name if and only if content-type is\none of the following: [`application/json`, `multipart/form-data`, `application/x-www-form-urlencoded`]; and parameter is present."
}
},
```
See …
> Fix referenceable fields.

- app/_data/docs_nav_kic_2.10.x.yml
- app/_data/kong_versions.yml
- app/_src/kubernetes-ingress-controller/references/kubernetes-events.md
- app/_src/kubernetes-ingress-controller/troubleshooting.md
Adds a `Kubernetes Events` reference page describing the events emitted by Kong Ingress Controller. Also adds a 2.10.x navigation for KIC.
Closes https://github.com/Kong/kubernetes-ingress-controller/issues/4042.
https://deploy-preview-5644--kongdocs.netlify.app/kubernetes-ingress-controller/latest/references/kubernetes-events/
> kic: add k8s events reference

- app/_data/docs_nav_kic_2.9.x.yml
- app/_src/kubernetes-ingress-controller/deployment/kind.md
I added a section on installing `Kong for Kubernetes with Kong Enterprise` for KIC on `kind`. I feel we have make it easy for developers to deploy Kong enterprise and be able to play around so they can use and promote the platform internally.
Netlify link: /kubernetes-ingress-controller/latest/deployment/kind/
> adding kind install instructions for KIC

- app/_src/gateway/admin-api/index.md
remove the excess "#" in  admin-api 
Netlify link:
> docs:  remove the excess "#"

- app/_plugins/hooks/external_links.rb
The hook was skipping single source pages because of the `instance_of?` check.
`#instance_of?` returns true only if the object is an instance of the exact class.
`#is_a?` returns true only if the object is an instance of the class or one of its subclasses.
Production
After the Changes
Netlify link: https://deploy-preview-5646--kongdocs.netlify.app/gateway/latest/
> Fix external links hook.

- app/_assets/images/icons/documentation/hub/icn-breadcrumbs.svg
Changing the home icon in plugin hub breadcrumbs to something clearer, as we had multiple people be confused about the previous one.
https://konghq.atlassian.net/browse/DOCU-3232
Netlify link:
> [DOCU-3232] Plugin hub home icon

- app/_hub/kong-inc/datadog/_index.md
There was some invalid markdown from a merge conflict present on the file causing the page to render a weird-looking section.
Before:
After:
Netlify link: https://deploy-preview-5655--kongdocs.netlify.app/hub/kong-inc/datadog/
> Remove merge conflict from datadog plugin

- app/_src/gateway/get-started/proxy-caching.md
The `HIT` section in the proxy-cache doc was wrong and contained the same content as the `MISS` section. Fix the content  in the `HIT` section.
Netlify link:
> Doc: Fix HIT section in proxy-cache doc.

- app/_plugins/tags/referenceable_fields/table_tag.rb
- app/_plugins/tags/referenceable_fields/table_template.erb
- app/_src/gateway/kong-enterprise/secrets-management/index.md
- spec/app/_plugins/tags/referenceable_fields_spec/table_tag_spec.rb
Use the newly generated file containing all the plugins that have referenceable fields + the corresponding fields to render the `Referenceable fields` table. It was manually generated/maintained until now.
This will keep the table up to date with the schemas.
Netlify link:
> Fix referenceable fields table

- app/konnect/runtime-manager/configuration/index.md
This update adds new documentation around the limits for each resource within a runtime group. These limits are per runtime group and not global to the organization.
Jira: [KOKO-960](https://konghq.atlassian.net/browse/KOKO-960)
Netlify link: https://deploy-preview-5658--kongdocs.netlify.app/konnect/runtime-manager/configuration/#configuration-limits
[KOKO-960]: https://konghq.atlassian.net/browse/KOKO-960?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> doc: add documentation for limits on configuration resources

- app/_hub/kong-inc/exit-transformer/_index.md
- app/_hub/kong-inc/mocking/_index.md
- app/_src/deck/guides/defaults-v2.md
- app/_src/gateway/admin-api/developers/reference.md
- app/_src/gateway/install/helm-quickstart.md
- app/_src/gateway/install/kubernetes/helm-quickstart.md
- app/_src/gateway/kong-enterprise/audit-log.md
- app/_src/gateway/kong-enterprise/consumer-groups/index.md
- app/_src/gateway/kong-enterprise/dev-portal/applications/enable-key-auth-plugin.md
- app/_src/gateway/kong-enterprise/dev-portal/authentication/azure-oidc-config.md
- app/_src/gateway/kong-enterprise/event-hooks/index.md
- app/_src/gateway/kong-enterprise/plugin-ordering/get-started.md
- app/_src/gateway/kong-enterprise/secrets-management/advanced-usage.md
- app/_src/gateway/kong-enterprise/secrets-management/backends/aws-sm.md
- app/_src/gateway/kong-enterprise/secrets-management/backends/env.md
- app/_src/gateway/kong-enterprise/secrets-management/backends/gcp-sm.md
- app/_src/gateway/kong-enterprise/secrets-management/backends/hashicorp-vault.md
- app/_src/gateway/kong-enterprise/workspaces/index.md
- app/_src/gateway/licenses/examples.md
- app/_src/gateway/production/access-control/enable-rbac.md
- app/_src/gateway/production/access-control/register-admin-api.md
- app/_src/gateway/production/deployment-topologies/db-less-and-declarative-config.md
- app/_src/gateway/production/deployment-topologies/hybrid-mode/setup.md
- app/_src/gateway/reference/key-management.md
Cleaning out HTTPie from our docs, as its an extra tool that someone would need to install. This causes a problem for customers.
* Converting any httpie examples into curl
* For curl/httpie navtabs, removing the tabs and leaving curl only
* Cleaned up and tested the ["Enable RBAC"](https://docs.konghq.com/gateway/latest/production/access-control/enable-rbac/) doc. It became apparent that this needed doing as I couldn't just convert inaccurate commands from httpie to curl, I had to make sure they were real. This doc has also commonly been a source of bug reports in the past, and we've just never gotten to it.
Issue reported on Slack: https://kongstrong.slack.com/archives/CDSTDSG9J/p1685430807824339
https://konghq.atlassian.net/browse/DOCU-2925
https://konghq.atlassian.net/browse/DOCU-288 …
> [DOCU-2925] HTTPie cleanout

- app/_includes/plugins/header.html
- netlify.toml
Run lighthouse against each product landing page.
We can keep an eye on this and add thresholds to make the build fail if the changes made generate a bad score
Netlify link:
> Customize netlify's lighthouse plugin to run on specific pages

- app/_src/kubernetes-ingress-controller/faq.md
KIC 2.10 moves from using `Endpoint`s to `EndpointSlice`s.
This PR adds a FAQ section for that. Due to version dependent logic this can be merged to `main` before 2.10 is released.
Closes #5578
Netlify link:
> kic: add FAQ section for 2.10+ for EndpointSlices

- app/_hub/kong-inc/jwt/_index.md
Changed query string parameter as it was mentioned query string in metadata.yml and in this changed file 
Netlify link:
> Fixing the spelling mistake "query string" parameter

- app/_data/docs_nav_kic_2.10.x.yml
- app/_src/kubernetes-ingress-controller/concepts/expression-based-router.md
Add a guide page to introduce how to use expression based router in KIC. fixes https://github.com/Kong/kubernetes-ingress-controller/issues/4077.
Netlify link:
> add concept page for kic using expression router

- app/gateway/changelog.md
fix 3.2.2.3 release date
fixing the 3.2.2.3 release date that I missed on PR5673
Netlify link: (https://deploy-preview-5680--kongdocs.netlify.app/gateway/changelog/)
> Fix release date for 3.2.2.3

- app/_src/kubernetes-ingress-controller/references/supported-router-flavors.md
Update supported router flavors of KIC 2.10.x. fixes https://github.com/Kong/kubernetes-ingress-controller/issues/4086. 
Netlify link: 
https://deploy-preview-5678--kongdocs.netlify.app/kubernetes-ingress-controller/latest/references/supported-router-flavors/
> add support status of kong router flavors of kic 2.10

- .github/styles/kong/First-person.yml
- .github/styles/kong/Relativeurls.yml
- .github/styles/kong/We.yml
https://kongstrong.slack.com/archives/G012HLJ4GJJ/p1685972120560589
Based on a comment made in Slack this week. I added rules directly from [here](https://github.com/errata-ai/Google/tree/master/Google). 
We rule is set to warning, and the first person pronoun rule is set to error. In my opinion "I's" and "me's" should auto fail, the other rule can be used locally on a directory to remove We's and catch them in the moment. 
edit: 
Added rule to catch absolute URLs that should be relative
tested it on the following cases: 
```
[Kong Admin API Documentation](gateway/latest/admin-api/)
[Kong Admin API Documentation](https://docs.konghq.com/gateway/latest/admin-api/)
[Kong Admin API Documentation](https://google.com)
```
And: 
```
curl -L https://docs.konghq.com/mesh/installer.sh | …
```
> Chore: Add more style rules to Vale

- app/_src/gateway/reference/configuration.md
change from 1.0 to 0.01 according to https://github.com/Kong/kong/blob/release/3.3.x/kong.conf.default#L136
> fix default tracing_sampling_rate value

- app/konnect/api/runtime-groups-config/index.md
Fixes incorrect URL https://docs.konghq.com/konnect/api/runtime-groups-config/#retrieve-plugin-schema
https://kongstrong.slack.com/archives/C03NRECFJPM/p1686350903083519
> chore: Fix URL in plugin endpoint

- app/_data/docs_nav_kic_2.10.x.yml
- app/_data/docs_nav_kic_2.6.x.yml
- app/_data/docs_nav_kic_2.7.x.yml
- app/_data/docs_nav_kic_2.8.x.yml
- app/_data/docs_nav_kic_2.9.x.yml
- app/_src/kubernetes-ingress-controller/guides/choose-gateway-image.md
Adds instructions on how to use `kong/kong-gateway` with KIC
This can go in to `main` as it's not specifically tied to KIC/Konnect
Netlify link: [/kubernetes-ingress-controller/latest/guides/choose-gateway-image/](https://deploy-preview-5700--kongdocs.netlify.app//kubernetes-ingress-controller/latest/guides/choose-gateway-image/)
> Add docs on using Kong Enterprise with KIC

- app/_src/kubernetes-ingress-controller/concepts/deployment.md
[KIC from version 2.10.0](https://github.com/Kong/kubernetes-ingress-controller/blob/main/CHANGELOG.md#changed-1) no longer relies on `Endpoints` anywhere. RBAC permissions for them have been already removed in respective Helm Chart https://github.com/Kong/charts/pull/798
Netlify link: https://deploy-preview-5708--kongdocs.netlify.app
> fix(kic): rbac permission for Endpoints is redundant for KIC >=2.10

- app/_data/docs_nav_gateway_3.1.x.yml
- app/_src/gateway/admin-api/admin-api-3.1.x.md
fix issue with instance_name showing up in 3.1
This is fixed by adding a new API markdown file and referencing it from the 3.1 nav bar.
> chore: fix API parameter in wrong version

- app/gateway/changelog.md
Changelog entry for 3.2.2.3 was higher than 3.3.0.0, swapped these two so that 3.3.0.0 was above 3.2.2.3 to keep the versions ordered properly.
N/A
> Reordered 3.2.2.3 to be below 3.3.0.0 in the changelog

- app/_assets/javascripts/app.js
[Jira ticket](https://konghq.atlassian.net/browse/DOCU-3221)
Prevent badges' tooltips from being displayed in `/hub`. We already have the links' titles and the tooltips were overlapping them.
Before:
[Netlify link](https://deploy-preview-5716--kongdocs.netlify.app/hub/)
> Prevent badges' tooltips from being loaded in /hub

- app/_assets/stylesheets/pages/docs.less
- app/_assets/stylesheets/pages/extension.less
- app/_includes/plugins/right_nav.html
[Jira ticket](https://konghq.atlassian.net/browse/DOCU-3237)
Make the right nav collapsible.
Before:
After:
Netlify link:
> Make rightnav collpasible on plugin pages

- .gitmodules
- app/_includes/plugins/header.html
- app/_plugins/generators/plugin_single_source/pages/base.rb
- app/_plugins/generators/plugin_single_source/pages/configuration.rb
- app/_plugins/generators/plugin_single_source/pages/configuration_examples.rb
- app/_plugins/generators/plugin_single_source/plugin/release.rb
- spec/app/_plugins/generators/plugin_single_source/pages/configuration_examples_spec.rb
- spec/app/_plugins/generators/plugin_single_source/pages/configuration_spec.rb
- spec/app/_plugins/generators/plugin_single_source/plugin/release_spec.rb
- spec/fixtures/app/_hub/kong-inc/jq/_metadata.yml
- spec/support/shared_contexts/site.rb
[Jira ticket](https://konghq.atlassian.net/browse/DOCU-3280)
Add `edit this page` link to plugin configuration pages.
Netlify link:
> Plugin configuration edit links

- app/_src/gateway/install/kubernetes/helm.md
- app/_src/gateway/install/kubernetes/kubectl.md
- app/_src/gateway/install/kubernetes/openshift.md
- app/_src/kubernetes-ingress-controller/guides/getting-started-istio.md
- app/gateway/2.6.x/install-and-run/helm.md
- app/gateway/2.6.x/install-and-run/kubernetes.md
- app/gateway/2.6.x/install-and-run/openshift.md
- app/gateway/2.7.x/install-and-run/helm.md
- app/gateway/2.7.x/install-and-run/kubernetes.md
- app/gateway/2.7.x/install-and-run/openshift.md
- app/gateway/2.8.x/install-and-run/helm.md
- app/gateway/2.8.x/install-and-run/kubernetes.md
- app/gateway/2.8.x/install-and-run/openshift.md
- app/kubernetes-ingress-controller/2.0.x/guides/getting-started-istio.md
- app/kubernetes-ingress-controller/2.1.x/guides/getting-started-istio.md
- app/kubernetes-ingress-controller/2.2.x/guides/getting-started-istio.md
Redundant comma, others items don't have it before specifying version
Netlify link: https://deploy-preview-5743--kongdocs.netlify.app/
> fix(kic): remove redundant comma

- app/konnect/org-management/okta-idp.md
Clarified that the claim set up is optional as group claims are only needed if the admin intends to use Konnect team mapping functionality. It was marked optional in one sentence, but when looking at the later part it implied it's a requirement, so attempted to clarify this in the docs.
[Internal Slack thread](https://kongstrong.slack.com/archives/C0254TZHXHS/p1687378547342099?thread_ts=1687364981.012979&cid=C0254TZHXHS)
Netlify link: https://deploy-preview-5737--kongdocs.netlify.app/
> Clarify group claims / team mapping in Konnect Okta setup

- app/_hub/kong-inc/acl/_index.md
This simply updates a dead link on the [ACL plugin page](https://docs.konghq.com/hub/kong-inc/acl/). This appears to be an issue across all versions of page. As such, we may need to fix this across all release branches.
Netlify link: 
1. Open the ACL plugin page found [here](https://docs.konghq.com/hub/kong-inc/acl/).
2. Click on the "Basic configuration example" link, does it work?
> fix: correcting dead example link on ACL plugin page

- app/_src/gateway/kong-enterprise/cp-outage-handling.md
Add missing KONG_CLUSTER_FALLBACK_CONFIG_STORAGE param for S3 object storage.
Issue reported on Slack: https://kongstrong.slack.com/archives/CDSTDSG9J/p1688009597867569
Also disabled the "On this page" table of contents, as it doesn't work properly when headers are nested inside tabs.
Netlify link:
> Fix CP outage handling missing param

- app/_redirects
This is useful as doc links on MinK use konnect as a version which is always going to be the latest version
Fix #Kong/kong-mesh-gui#642
Netlify link:
> fix: redirect /mesh/konnect to /mesh/latest

- app/_plugins/generators/plugin_single_source/pages/base.rb
- app/_plugins/generators/plugin_single_source/pages/configuration_examples.rb
- app/_plugins/generators/plugin_single_source/pages/how_to.rb
- spec/app/_plugins/generators/plugin_single_source/pages/changelog_spec.rb
- spec/app/_plugins/generators/plugin_single_source/pages/configuration_examples_spec.rb
- spec/app/_plugins/generators/plugin_single_source/pages/configuration_spec.rb
- spec/app/_plugins/generators/plugin_single_source/pages/how_to_spec.rb
- spec/app/_plugins/generators/plugin_single_source/pages/overview_spec.rb
- spec/app/_plugins/generators/plugin_single_source/plugin/unversioned_spec.rb
- spec/app/_plugins/generators/plugin_single_source_generator_spec.rb
- spec/app/_plugins/generators/seo/index_spec.rb
- spec/app/_plugins/generators/seo/sitemap_spec.rb
- spec/fixtures/app/_hub/acme/kong-plugin/how-to/_local-testing.md
[Jira ticket](https://konghq.atlassian.net/browse/DOCU-3308)
Add an extra `How To` level for how-to pages.
If the file `how-to/_index.md` exists, this new level contains a link to it. Otherwise, this new level is just plain text.
Netlify link: 
* https://deploy-preview-5774--kongdocs.netlify.app/hub/kong-inc/acme/how-to/local-testing-development/
* https://deploy-preview-5774--kongdocs.netlify.app/hub/kong-inc/basic-auth/how-to/basic-example/
> Fix breadcrumbs for plugins how-to

- app/_src/kubernetes-ingress-controller/concepts/deployment.md
- app/konnect/network.md
- app/konnect/runtime-manager/kic.md
If our users have traffic restrictions of any kind for the outbound traffic, it's worth to mention what hosts they should have allow-listed for KIC+Konnect integration.
Closes https://github.com/Kong/kubernetes-ingress-controller/issues/4298.
https://deploy-preview-5781--kongdocs.netlify.app/kubernetes-ingress-controller/latest/concepts/deployment/
https://deploy-preview-5781--kongdocs.netlify.app/konnect/runtime-manager/kic/
> mention requirement for outbound traffic for kic+konnect

- app/gateway/changelog.md
Parameter is incorrectly named in our changelog, but correctly named in the OSS one: https://github.com/Kong/kong/blob/master/CHANGELOG.md#plugins-4
You can verify by looking at the linked eng PR.
Netlify link:
> Fix kong.tools.queue changelog entry

- app/konnect/org-management/teams-and-roles/roles-reference.md
- Fixed the title on Roles reference so "Services" is now "API products" (we forgot it during the API Products release)
https://kongstrong.slack.com/archives/CDSTDSG9J/p1689084720276279
Netlify link:
> Change Services title to API Products on Roles reference

- app/_plugins/generators/plugin_single_source/pages/configuration.rb
- app/_plugins/generators/plugin_single_source/pages/configuration_examples.rb
- app/_plugins/generators/plugin_single_source/plugin/release.rb
- app/_plugins/generators/plugin_single_source/plugin/schemas/base.rb
- spec/app/_plugins/generators/plugin_single_source/pages/configuration_examples_spec.rb
- spec/app/_plugins/generators/plugin_single_source/pages/configuration_spec.rb
- spec/app/_plugins/generators/plugin_single_source/plugin/release_spec.rb
We use the `source_file` as the page's `relative_path` which is used internally by Jekyll to konw which pages should be re-generated whenver a file changes.
Configuration and plugin hub example pages were setting it to `nil` causing all those pages to be re-generated whenever any file changed. This fixes the issue by setting the right `source_file` to those pages.
This only affects local build times.
Netlify link:
> Fix performance issue caused by plugin pages without `source_file`

- app/_src/gateway/kong-plugins/authentication/allowing-multiple-authentication-methods.md
Address issue https://github.com/Kong/docs.konghq.com/issues/5789 by replacing all random hostnames with `localhost`.
Also took the opportunity to clean this topic up:
* split codeblocks
* added steps and headings
Netlify link: https://deploy-preview-5795--kongdocs.netlify.app/gateway/latest/kong-plugins/authentication/allowing-multiple-authentication-methods/#validate-credentials
> Clean up multiple auth methods doc

- app/_hub/kong-inc/ip-restriction/_changelog.md
An upcoming change in Kong Gateway will add support for additional protocols in the ip-restriction plugin.  The plugin is slightly underdocumented, but the change is now mentioned in the changelog.
https://github.com/Kong/kong/pull/10245
Netlify link: 
KAG-722
> Add changelog entry for 3.4.x changes in the ip-restriction plugin

- app/_src/gateway/production/deployment-topologies/hybrid-mode/setup.md
Netlify link: https://deploy-preview-5807--kongdocs.netlify.app/gateway/latest/production/deployment-topologies/hybrid-mode/setup/
> Update the output of /clustering/data-planes, which is out-of-date.

- app/_plugins/hooks/total_pages.rb
Add a hook that outputs the number of generated pages after the site builds.
Makes it easy to keep track of how many pages are added by each PR.
Netlify link:
> Add hook that displays the total number of pages generated

- app/_src/kubernetes-ingress-controller/references/feature-gates.md
Add mention about KIC's `FillIDs` feature gate that's introduced in 2.10.
> kic: add mention about FillIDs feature gate

- app/_src/gateway/reference/configuration.md
- Someone in #docs reported that the description of ssl_ciphers was confusing if you were using DHE ciphers because you'd also have to use another parameter. This fixes the description.
- I'll also change this in Kong-ee, I just haven't made the PR yet.
https://kongstrong.slack.com/archives/CDSTDSG9J/p1688483985172189
Netlify link:
> Add sentence to ssl_cipher description

- app/_src/gateway/install/kubernetes/helm.md
- app/_src/gateway/install/kubernetes/openshift.md
- app/enterprise/2.1.x/deployment/installation/kong-on-kubernetes.md
- app/enterprise/2.2.x/deployment/installation/kong-on-kubernetes.md
- app/enterprise/2.3.x/deployment/installation/kong-on-kubernetes.md
- app/enterprise/2.4.x/deployment/installation/kong-on-kubernetes.md
- app/enterprise/2.5.x/deployment/installation/kong-on-kubernetes.md
- app/gateway/2.6.x/install-and-run/helm.md
- app/gateway/2.6.x/install-and-run/openshift.md
- app/gateway/2.7.x/install-and-run/helm.md
- app/gateway/2.7.x/install-and-run/openshift.md
- app/gateway/2.8.x/install-and-run/helm.md
- app/gateway/2.8.x/install-and-run/openshift.md
The cookie_domain example in the docs has a minor "typo". 
Netlify link: 
Please advise - which branch I should target - but as many versions are "affected" main seems the correct one?
> Fix cookie_domain example

- app/_src/gateway/licenses/report.md
Added an important note to clarify that the license report functionality cannot be run on DB-less deployments, it is only meant for database-backed deployments per [DOCU-1791](https://konghq.atlassian.net/browse/DOCU-1791).
Netlify link: 
- [y] Review label added 
- [y] PR pointed to correct branch
[DOCU-1791]: https://konghq.atlassian.net/browse/DOCU-1791?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Resolve DOCU-1791. Clarify db-backed instances only.

- app/_src/gateway/upgrade-v2.md
- We were asked to update Gateway 3.3 and later upgrade docs with a [note about PostgreSQL 15 changes](https://konghq.atlassian.net/browse/FTI-5149?focusedCommentId=105115), so I added that.
- I think opening this on the `main` branch is correct since this also impacts 3.3?
DOCU-3301
Netlify link:
> [DOCU-3301] Add PostgreSQL 15 note to upgrade doc

- .github/workflows/linting.yml
Pin vale version to 2.24 to fix terms.yml not reading the `custom` key.
> Pin vale version

- netlify.toml
Running the site locally (on `main`) was raising an error 
```
Liquid Exception: Vite Ruby can't find entrypoints/application.js in .jekyll-cache/vite/manifest.json
```
The problem was that `JEKYLL_ENV` was set to production for the [main branch](https://github.com/Kong/docs.konghq.com/blob/main/netlify.toml#L6)
According to netlify’s [docs](https://docs.netlify.com/configure-builds/file-based-configuration/#deploy-contexts), branch-specific contexts override everything else, so it was trying to run it in production mode.
Changing the config to use an environment-specific context instead of a branch-specific one fixes the issue.
Netlify link:
> Use environment instead of branch-specific context 

- app/konnect/compatibility.md
Removing note saying that only Kong Gateway is supported, since we now support Mesh (and KIC, though that's still gateway).
Is there a list of known supported Mesh versions in Konnect @cloudjumpercat ?
Netlify link:
> fix: Remove inaccurate note about runtime instances

- app/_assets/javascripts/app.js
- app/_assets/javascripts/navbar.js
- app/_includes/nav-v2.html
Fix a few issues on Mobile after the vite.js migration:
* top nav wasn't working
* clicking on the search icon wasn't focusing the input field - both modal and desktop
* missing variable declaration
Feature branch:
https://github.com/Kong/docs.konghq.com/assets/715229/65a04935-2622-4844-83f3-e767cc020598
Production:
https://github.com/Kong/docs.konghq.com/assets/715229/be426e15-e224-4fe4-9355-29070d2814a1
> Fix mobile experience

- app/_includes/anchor_links.html
Remove `Permalink` from anchor links' innerHTML.
It was making Google to index the links as `Permalink_<anchor>` and prepending `Permalink` to the text when copying the link.
Netlify link:
> Fix anchor links generation

- app/_src/gateway/kong-enterprise/aws-iam-auth-to-rds-database.md
This PR adds more explanation when user want to use the IAM Role defined by serviceaccount in an EKS environment to access RDS database. A request to the AWS STS service will happen inside this procedure so user have to make sure that they have no network restriction to the AWS STS service.
FTI-5211
Netlify link:
> chore(*): add more explanation when using EKS IRSA to access RDS database

- .vale.ini
- README.md
- app/_plugins/generators/plugin_single_source_generator.rb
- app/_plugins/hooks/products_renderer.rb
- spec/app/_plugins/generators/hooks/products_renderer_spec.rb
Render specific products based on the `KONG_PRODUCTS` env variable, which should be a  comma-separated list of the products to be rendered.
For example: 
```
KONG_PRODUCTS=gateway,kic,hub make run
```
generates the pages for:
* gateway
* kubernetes-ingress-controller
* plugin hub
It works by running two [hooks](https://jekyllrb.com/docs/plugins/hooks/#built-in-hook-owners-and-events) in different stages of the generation process:
* `:site, :post_read`: it skips pages that don't start with one of the specified product names - It always generates the home page. 
* `:site, :pre_render`: Mostly for single-sourced pages, it skips pages whose URLs don't start with one of the specified product names.
Netlify link:
> Add ability to render specific products and plugin hub

- Gemfile
- Gemfile.lock
- Makefile
Add foreman gem to Gemfile. 
It was added to `make install` but not to the Gemfile, so it was causing some [checks](https://github.com/Kong/docs.konghq.com/actions/runs/5703210629/job/15455607413) to fail.
Netlify link:
> Add foreman gem to Gemfile

- app/_plugins/blocks/inline_plugin_example/config.rb
- app/_plugins/generators/plugin_single_source/plugin/base.rb
- app/_plugins/generators/plugin_single_source/plugin/page_data.rb
- app/_plugins/generators/plugin_single_source/plugin/release.rb
- app/_plugins/generators/plugin_single_source/plugin/unversioned.rb
- spec/app/_plugins/blocks/inline_plugin_example/config_spec.rb
- spec/app/_plugins/generators/plugin_single_source/plugin/page_data_spec.rb
- spec/app/_plugins/generators/plugin_single_source/plugin/unversioned_spec.rb
- spec/app/_plugins/generators/plugin_single_source/plugin/versioned_spec.rb
- spec/app/_plugins/generators/versions_spec.rb
Inline plugin examples rely on pages having a `kong_version` set so that they can select the right version of the plugin's schema.
Netlify link:
> Set `kong_version` to hub pages.

- .github/workflows/scheduled-broken-link-checker.yml
The scheduled broken link checker requires `foreman` to be installed but we include it in the as a dev dependency.
Netlify link:
> Install foreman before running scheduled broken link checker

- app/_assets/stylesheets/pages/extension.less
Fixing the banner margin. If there's no header on the page, this happens:
Post-fix, we have this:
Look through old versions in any plugin doc.
> fix: Adjust the margin on the "old version" header in plugin docs

- app/_data/docs_nav_gateway_3.0.x.yml
- app/_data/docs_nav_gateway_3.1.x.yml
- app/_data/docs_nav_gateway_3.2.x.yml
- app/_data/docs_nav_gateway_3.3.x.yml
- app/_src/gateway/reference/configuration-3.0-3.3.md
- autodoc-conf-ee/run.lua
Generating the configuration reference for Gateway 3.4.
Content:
* Starting a new file here, as we are removing Cassandra entirely, and there have been many config changes in the last few releases. Since this is the planned LTS, I suspect we might need to edit this file in the future. This will make it easier.
Autogen script:
* Added all the exceptions for Kong Manager badges
* Verified which items actually should have badges, we had a few of them wrong (I think the features were added to OSS in a subsequent update, eg `lua_untrusted_sandbox_environment` and `node_id`).
* grouped the badges
https://konghq.atlassian.net/browse/DOCU-3377
Netlify link:  https://deploy-preview-5881--kongdocs.netlify.app/gateway/latest/reference/configuration/#admin_gui_listen
> chore: Update configuration reference for gateway 3.4

- app/_data/tables/install_options_34x.yml
- app/_src/gateway/install/docker/build-custom-images.md
- app/_src/gateway/install/index.md
- Since Alpine support is removed in 3.4, I made the Alpine instructions in the Docker install doc conditional
DOCU-2988
Netlify link: 
❗ For reviewers:
- The [tiles on the install overview page](https://docs.konghq.com/gateway/latest/install/), those will need to be updated, but I wasn't sure how to conditionally render those so they only show up for versions lte:3.3.x
> feat: Remove Alpine instructions from Docker install instructions for 3.4

- app/_src/gateway/reference/router-expressions-language.md
Kong gateway 3.4 added stream expression support and changed some behaviors,
We should update the reference doc for kong 3.4.
https://konghq.atlassian.net/browse/KAG-2149
https://github.com/Kong/kong/pull/11071
Netlify link:
> Update expression router documentation for kong 3.4

- api-specs/Gateway-EE/3.4/kong-ee-3.4.yaml
- app/_src/gateway/admin-api/index.md
- app/_src/gateway/admin-api/workspaces/reference.md
Added these two things to the markdown documentation.
> deprecated `overrides` endpoint note, cascade endpoint added to workspace delete.

- .github/styles/kong/Terms.yml
- .github/workflows/linting.yml
- .vale.ini
- app/_src/gateway/plugin-development/tests.md
Updated Github action to use Reviewdog
```
steps:
- uses: actions/checkout@v3
- uses: errata-ai/vale-action@reviewdog
```
Vale is failing, I suspect it has something to do with pinning the version, removing the parameter `-fail-on-error` makes this work while still preserving the error reporting ability: 
However, this makes the PR pass even with errors reported
> Chore: Fix vale, Update Github action

- app/_src/gateway/upgrade-v2.md
- Added a 3.4 version table to the Gateway upgrade doc 
Netlify link:
> chore: Add 3.4 version to Gateway upgrade doc

- app/_data/docs_nav_gateway_3.4.x.yml
- app/_src/gateway/breaking-changes/32x.md
- app/_src/gateway/breaking-changes/34x.md
- app/_src/gateway/migrate-cassandra-to-postgres.md
- app/gateway/changelog.md
Listing out the deprecations and breaking changes from 3.4. 
Based on changelog.
Removed the entry for `vitals` parameter from the changelog, as the change was reverted, so the default value hasn't changed after all.
Netlify link: https://deploy-preview-5914--kongdocs.netlify.app/gateway/latest/breaking-changes/
> chore: Breaking changes in Kong Gateway 3.4

- app/_data/installation/gateway.yml
Had to rotate the `gateway-34` repo gpg/rsa keys today and realized they would be good to add to the docs release.
Netlify link:
> chore: Add gpg/rsa gateway-34 repo keys

- app/_data/tables/version_errors_konnect.yml
JIRA: https://konghq.atlassian.net/browse/KOKO-1173
Adds version compatibility issues for gateway v3.4.
Removes `D155` due to a reversal of support for datadog-tracing between v3.2 and v3.2.2.
Adds a few other non v3.4 changeIDs.
Netlify link:
> chore: add compatibility issues for v3.4

- app/_src/gateway/install/docker/build-custom-images.md
- app/_src/gateway/install/linux/debian.md
- app/_src/gateway/install/linux/ubuntu.md
Ubuntu installation links should not be using `bionic`, as we are no longer building or supporting `bionic` packages. 
I didn't version-tag the release portion of the URL, since ubuntu jammy packages exist for all 3.x versions: https://cloudsmith.io/~kong/packages/?q=distribution%3Aubuntu+AND+distribution%3Ajammy
Netlify link:
> fix: Ubuntu installation links are using old release

- app/_src/gateway/install/linux/amazon-linux.md
Fixing broken links to AL2023 packages.
Struggling to figure out the right links for Amazon Linux 2 though.
Netlify link:
> fix: Amazon Linux 2023 installation links

- app/_src/gateway/support/index.md
LTS releases are supported for 3 years from release. Update Gateway 3.4 to August 2026
Netlify link: /gateway/latest/support-policy/
> Fix Gateway 3.4 LTS date

- .github/workflows/check-links.yml
Explicitly seeing the links that the link-checker tool is verifying can be a useful part of the review process. 
Netlify link:
> feat(gha): allow verbose link checking

- .github/styles/kongplugins/plugin-ignore.txt
- app/_hub/kong-inc/application-registration/_index.md
- app/_hub/kong-inc/application-registration/how-to/_index.md
Split app reg plugin doc into the "Using this plugin" section. 
Cross-linked a ton of content from the Gateway docs to hopefully make it easier to find app reg info. 
Was making this change as part of the OIDC plugin branch originally and it got too big (no surprise). 
[Overview](https://deploy-preview-5875--kongdocs.netlify.app/hub/kong-inc/application-registration/)
[Getting started](https://deploy-preview-5875--kongdocs.netlify.app/hub/kong-inc/application-registration/how-to/)
> chore: Split app reg plugin how-tos

- app/_hub/kong-inc/rate-limiting-advanced/_changelog.md
- app/_src/gateway/breaking-changes/34x.md
Updated the changelog to add information about the overrides endpoint deprecation and instructions on how to view the consumer groups API, and use the new guide that contains the new routes.
> Chore: Update changelog to add note about overrides endpoint deprecation. 

- app/_src/gateway/install/linux/amazon-linux.md
- app/_src/gateway/install/linux/ubuntu.md
- tools/install-tester/execute-in-docker.js
- tools/install-tester/index.js
The automated installation tests were failing for multiple reasons:
* The Amazon Linux page had been refactored to cover Amazon Linux 2 + Amazon Linux 2023. We use `%{amzn}` in the `rpm --eval` call so the same instructions work for both. The tabs for AL2/AL2023 have been merged
* We don't build Ubuntu `jammy` packages for 3.0. The installation instructions have been updated to use `bionic` for Kong Gateway 3.0
> Fix automated package installation tests

- app/konnect/updates.md
This PR skips changelog. 
Adds a changelog note that support for Konnect 3.4 and all compatible plugins is in. 
https://konghq.atlassian.net/browse/DOCU-3333
> Konnect support for Gateway 3.4

- app/_src/gateway/install/linux/ubuntu.md
We no longer build Ubuntu `bionic` packages for Kong Gateway 3.4+.
Update the conditional rendering to use Ubuntu `jammy` for all releases except 3.0, which provides a `bionic` package but no `jammy` package
> Fix Ubuntu 3.4 package install instructions

- app/_includes/md/enterprise/deploy-license.md
Fix the following broken link:
```json
{
"page": "http://localhost:8888/enterprise/2.5.x/deployment/licenses/deploy-license/",
"text": "Install Kong Gateway on Docker",
"target": "http://localhost:8888/gateway/2.5.x/install-and-run/docker",
"reason": "HTTP_404"
},
```
For old versions < 2.5.x the link was pointing to the wrong url.
https://deploy-preview-5950--kongdocs.netlify.app/enterprise/2.5.x/deployment/licenses/deploy-license/
> Fix link to docker installation

- app/_src/gateway/kong-enterprise/index.md
This PR skips changelog. 
Fixes the broken links by adding an `if_version` tag.
> Fix: Fix links to consumer groups API documentation

- app/_src/mesh/production/cp-deployment/license.md
Fixed step indentation in the Kong Mesh license doc.
Netlify link:
> fix: Broken step indents in Mesh license guide

- app/gateway/changelog.md
3.4 supports RHEL 9, but we were missing this entry from the changelog. 
This fix adds the missing entry and links to the available packages.
Netlify link:
> fix: Add changelog entry for RHEL 9 support

- app/_includes/md/kic/crd-ref/kong_consumer_group_description.md
Add missing `/` to kic link.
/kubernetes-ingress-controller/latest/references/custom-resources/
> Fix kic broken link

- .github/workflows/sync-kuma-submodule.yml
> fix(.github): use correct token in sync-kuma-submodule

- app/_data/tables/support/gateway/versions/34.yml
With addition of RHEL9 support, the docker image for RHEL8 is no longer available as of 3.4 
Netlify link:  https://deploy-preview-5965--kongdocs.netlify.app/gateway/latest/support-policy/
> (fix) Remove Docker from RHEL8 in 3.4 matrix

- app/konnect/runtime-manager/configuration/index.md
Configuration Limits table doesn't currently include Runtime Groups. Adding here is a short-term way to address better communication on limits in general. 
Netlify link:
> (fix) Add Runtime Groups limit

- app/_src/gateway/production/clustering.md
This is not on the changelog
User reported issues with the rendering in the `/gateway/3.0.x/production/clustering/` doc. The problem was that the headings used code tags and relative linking. Removed that in place of direct linking at the bottom of each section. Made a more info section at the bottom as well.
> Fix: Rendering issue on clusering reference page.

- app/gateway/changelog.md
Adding statement to deprecation section of changelog to make clear the Kong-provided Docker image in this release is RHEL9 not RHEL8. 
Netlify link: https://deploy-preview-5967--kongdocs.netlify.app/gateway/changelog/#breaking-changes-and-deprecations
> (Fix) RHEL8 Docker Image deprecation

- app/contributing/style-guide.md
From hackathon conversation. Path parameters are represented with curly braces, this is the standard when writing about API path parameters.
> Chore: Add path parameter style note to style guide

- app/_includes/plugins/schema.html
Add `consumer_group` section to plugin schemas.
Netlify link:
> Add `consumer_group` section to the plugin schemas

- app/konnect/getting-started/deploy-service.md
Fixing an indent that was causing the content of the step to break the formatting of the list.
Netlify link:
> fix: Indent in Konnect Getting Started Guide step

- app/_src/gateway/reference/router-expressions-language.md
Fix the mistake in #5889.
Netlify link:
> Fix fields name in router expression reference

- app/_hub/kong-inc/rate-limiting-advanced/_index.md
- app/_src/gateway/kong-enterprise/consumer-groups/index.md
* Updated the documentation to include a specific mention of no longer needing the `overrides` endpoint in the rate-limiting plugin doc. 
* Fixed a bullet that should have been written as gte 3.4.x but was written as lte 3.3.x
* Added an explanation of how the new consumer groups endpoint works.
> Update consumer groups documentation

- app/_src/gateway/upgrade-v2.md
Removed the contradictory line from the upgrade-v2.md file to make the upgrade table the "source of truth" and future doc updates easier to maintain for Kong Gateway version upgrade instructions.
Slack conversation: https://kongstrong.slack.com/archives/CDSTDSG9J/p1692729286950759
> Updated Kong Gateway upgrade guide to be the source of truth for future docs updates

- app/_hub/kong-inc/opentelemetry/_changelog.md
- app/_hub/kong-inc/opentelemetry/_index.md
Documentation updates for https://github.com/Kong/kong/pull/11254
Netlify link:
> feat(opentelemetry): propagate GCP trace header

- app/_assets/javascripts/navbar.js
Fixes submenus on enter.
When using the tabs + enter to open one of the menus in the topnav, hitting tab again would iterate over the menu items but hitting enter on one of them wasn't actually visiting the highlighted link, it was just closing the submenu.
This change fixes the issue, so that it actually visits the corresponding page.
Netlify link:
> Don't prevent default behaviour on enter

- app/_hub/kong-inc/app-dynamics/_metadata.yml
- app/_hub/kong-inc/serverless-functions/_metadata.yml
The AppDynamics and Serverless functions plugins were incorrectly listed as being incompatible with all Kong Gateway deployment modes: https://docs.konghq.com/hub/plugins/compatibility/#serverless
Fixing that by adding `network_config_opts` to the metadata files for both plugins. Both plugins can be run in DB-less, traditional, and hybrid modes.
Netlify link: https://deploy-preview-5999--kongdocs.netlify.app/hub/plugins/compatibility/#serverless
> fix: Add missing metadata to appdynamics and serverless functions plugins

- app/konnect/servicehub/index.md
There isn't a servicehub section anymore, this PR changes the two links in the new overview page.
> Konnect rename: Servicehub section

- app/konnect/analytics/index.md
- app/konnect/analytics/reference.md
- app/konnect/analytics/troubleshoot.md
- app/konnect/analytics/use-cases/latency.md
https://konghq.atlassian.net/browse/DOCU-3375
There is a link to the runtime manager section. I left that behind. I think when someone tackles the runtime manager section they should change the link based on what they rename those files to.
> Konnect rename: Renames the analytics section.

- app/konnect/network.md
You can now find cross-reference to the "Control Plane and Data Plane Communication through a Forward Proxy" page in the "Konnect Ports and Networking Requirements" page.
Updated based on Slack feedback [here](https://kongstrong.slack.com/archives/C02CWN8C7DK/p1693260752247129). 
Netlify link: https://deploy-preview-6028--kongdocs.netlify.app/konnect/network/
> (Fix) Cross-ref CP-DP communication through forward proxy in Konnect docs

- app/_data/landing_page.yml
- Since Konnect is renaming "runtimes", we needed to update the homepage to change "runtimes". 
- I know the homepage on `main` is now the refreshed one and this is the old one, but I wanted to make sure everything was updated. Was there anything I missed?
DOCU-3380
Netlify link:
> feat: Rename Konnect "runtimes" on the docs homepage

- app/_includes/md/gateway/setup.md
- app/_src/gateway/install/docker/index.md
- Our OSS install instructions (specifically Docker and I found some Linux ones as well) that still said that KM wasn't for OSS even though it is. I fixed those spots.
DOCU-3445
Netlify link:
> fix: Update OSS install instructions for Kong Manager

- app/_hub/kong-inc/ip-restriction/_index.md
Added a blurb about how the IP Address is determined when using the IP Restriction plugin, as this was confusing customers who were unaware of the appropriate settings that needed to be tweaked for their environment so the IP could be determined accurately.
> Add info about how IP address is determined for IP Restriction plugin

- app/_hub/kong-inc/rate-limiting-advanced/_index.md
There were some missing details from the RL (Rate Limiting) plugin which I pasted into the RLA (Rate Limiting Advanced) plugin index page, including extra details about the strategies that can be used and the use-cases for each.
Also added a section for how the IP address is determined as this was missing from the details and was not obvious to customers how this worked when limiting by IP address.
> Updated RLA index page to share some details from RL plugin

- app/_hub/kong-inc/rate-limiting/_index.md
We were missing details about how the IP address was determined when customers want to limit by IP address. Added these details to clarify how this works and linked to other sources for the appropriate properties that need to be set.
> Added info about limiting by IP address

- app/_src/kubernetes-ingress-controller/references/supported-router-flavors.md
This change fixes small typos in the documentation.
> Fix "supported-router-flavors" typos.

- api-specs/Gateway-OSS/3.4/kong-oss-3.4.yaml
- app/_data/docs_nav_gateway_3.4.x.yml
- app/_src/gateway/admin-api/admin-api-3.4.x.md
- app/_src/gateway/admin-api/index.md
- app/_src/gateway/reference/wasm.md
Adds documentation for the Filter Chain entity available in Kong Gateway 3.4 when WebAssembly support is enabled.
> Adds documentation for the Filter Chain entity available in Kong Gateway 3.4 

- app/_plugins/generators/plugin_single_source/plugin/schemas/base.rb
- app/hub/plugins/compatibility/index.md
The [scopes compatibility table](https://docs.konghq.com/hub/plugins/compatibility/#scopes) was missing a column for consumer groups. This PR enables generating the column and all entries from the plugins' schemas.
Additionally, the Application Registration plugin was listed as incompatible with all scopes, which is wrong - it's compatible with services only. Turns out we were selecting for the wrong key. Fixing this also fixes the display of the plugin's [config](https://docs.konghq.com/hub/kong-inc/application-registration/configuration/) and [basic examples](https://docs.konghq.com/hub/kong-inc/application-registration/how-to/basic-example/), which were both missing services.
Netlify link:
> Fix(plugin scopes): Consumer groups scope and application registration plugin

- app/_plugins/generators/plugin_single_source/plugin/schemas/base.rb
Partial revert of https://github.com/Kong/docs.konghq.com/pull/6059, undoing the app registration plugin part. That plugin is an exception and needs to be handled that way, and I can't figure out how to do it right. 
Reverting for now to prevent spec tests from failing in every PR. That just brings us back to the initial problem with the app reg plugin, which still needs fixing, but requires more Ruby knowledge than I have at the moment.
Netlify link:
> fix: Partial revert of plugin scopes changes

- app/_src/gateway/admin-api/index.md
- app/konnect/api/index.md
Update urls to latest for gateway apis
Remove mention of dev portal from API announcement banner.
> update urls to latest and remove mention of dev portal

- Makefile
Improve onboarding experience by using the example `.env` file by default. 
Run `make install` to copy the example to the correct location.
Netlify link: N/A
> Copy example .env when running make install

- app/_hub/kong-inc/grpc-web/how-to/_index.md
To enable grpc-web plugin via Admin API, the keyworkd `config` in curl data is missing.
> fix missing keyword config in curl data

- app/_hub/kong-inc/graphql-rate-limiting-advanced/overview/_index.md
GraphQL Introspection endpoint will only be read from the Kong service (`service = ngx.ctx.service`) instead of reading from a specific variable or ingress - local 
Documenting this behavior so consumers are aware of how to configure correctly and know about the limitation
Netlify link:
> Update _index.md - GraphQL Introspection endpoint related note.

- app/_includes/md/kic/http-test-routing-resource.md
- app/_src/kubernetes-ingress-controller/guides/using-external-service.md
Page on KIC exposing external service was having incorrect port number. 
https://docs.konghq.com/kubernetes-ingress-controller/latest/guides/using-external-service/
Port number was defaulting to 1027 which should be 80 in case of httpbin service
Preview link:
> changed the incorrect port number given in the docs for kic/using-external-service

- app/_data/docs_nav_konnect.yml
- app/_redirects
There was an  issue with the "Supported installation options" link opening two nav entries. If you clicked on one, two different entries would be highlighted as active.
Fixing it in the rename branch since that link has to change for rename also.
Preview link:
> Fix: Konnect nav duplicate entry

- app/_src/gateway/kong-enterprise/analytics/influx-strategy.md
Based on the code here https://github.com/Kong/kong-ee/blob/master/kong/vitals/influxdb/strategy.lua#L28 the Influxdb flush frequency is every 10 seconds instead of 5 seconds.
Preview link:
> fix(docs): Correct the influxdb flush frequency

- app/_src/gateway/kong-enterprise/cp-outage-handling.md
In troubleshooting a support case, we discovered that there was no mention of the `AWS_SESSION_TOKEN` variable which is needed in certain situations. Added a line in the Configuration section to clarify this for AWS S3.
Some customers were also confused thinking they needed to manually create the file structure including the config.json file in the bucket, so I added a line that confirmed this is created automatically and should not be created manually.
Also aligned some wording between AWS S3 and GCP bucket instructions, just minor tweaks to verbiage. Also modified "read/write" to "read & write" to remove any possible misunderstanding of the forward-slash being seen as an "or" when both are needed on the bucket.
Slack threads: https://kongstrong.slack.com/archives/C02DP1KL2DR/p16939313516 …
> Clarify and improve DP Resilience feature notes

- app/_src/gateway/kong-enterprise/analytics/influx-strategy.md
- Update the startup order and startup InfluxDB before starting up kong-gateway.
- From 3.4.0.0 Kong doesn't release the alpine docker image anymore thus correct the doc.
Preview link:
> fix(docs): correct the influxdb - gateway startup order

- app/_data/docs_nav_konnect.yml
Adds a deprecated subsection to the API section.
> Rename: deprecated API specs section

- .github/styles/kong/Terms.yml
- .github/styles/kong/dictionary.txt
- app/konnect/api/identity-management/identity-integration.md
Addressing vale comments from https://github.com/Kong/docs.konghq.com/pull/6121.
Removing the rule for "self-hosted -> self-managed" because we now have self-hosted Dev Portal.
`app/konnect/api/identity-management/identity-integration.md` gets a code block cleanup because the code block formatting was a) triggering vale, and b) super inconsistent across the page.
Preview link:
> chore: Vale cleanup for konnect rename branch

- app/_redirects
- app/_src/kubernetes-ingress-controller/guides/overview.md
- app/kubernetes-ingress-controller/1.0.x/guides/overview.md
- app/kubernetes-ingress-controller/1.1.x/guides/overview.md
- app/kubernetes-ingress-controller/1.2.x/guides/overview.md
- app/kubernetes-ingress-controller/1.3.x/guides/overview.md
- app/kubernetes-ingress-controller/2.0.x/guides/overview.md
- app/kubernetes-ingress-controller/2.1.x/guides/overview.md
- app/kubernetes-ingress-controller/2.2.x/guides/overview.md
Guide was removed in https://github.com/Kong/docs.konghq.com/pull/6068 but the link to it from the guides overview still remained.
Caught by the broken link checker: https://github.com/Kong/docs.konghq.com/actions/runs/6251198466/job/16971798110#step:12:399
Preview link:
> chore: Remove link to KIC guide that doesn't exist

- app/konnect/mesh-manager/service-mesh.md
- app/konnect/org-management/system-accounts.md
MinK auto creates a system account for zones. This shows up in the UI but is read only, so we needed to add a note about it so customers know what it does and why it's there. 
DOCU-3467
Preview link:
> feat: Add note about MinK system accounts

- app/_assets/javascripts/views/SpecView.vue
- app/_assets/stylesheets/header-v2.less
- app/_assets/stylesheets/page.less
- app/_includes/nav-v2.html
Fixing some issues with navbar formatting:
* On smaller screens, the top nav is misaligned and the buttons on the far right get cut off
old:
new:
* The margins of the top nav menu items overlap with some clickable areas of the docs, making them unusable
* In the API docs, the left nav scrolls together with the content body, making it difficult to use the left menu when scrolled down too far.
* Scroll was already set to `sticky` but with no `top` setting, there was nothing for it to stick to.
Issues 2 and 3 reported on slack.
You can test the menu resizing, but the other two fixes can't be tested via netlify preview since they're fixes to the API docs.
I tested them via dev tools in chrome, they _should_ work.
> fix: Layout issues with menus

- app/_hub/kong-inc/jq/overview/_index.md
- app/_plugins/drops/plugins/examples/curl.rb
- app/_plugins/drops/plugins/examples/konnect.rb
- spec/app/_plugins/drops/plugins/examples/curl_spec.rb
Missed renaming group ID in Konnect API examples in plugins, eg: https://docs.konghq.com/hub/kong-inc/basic-auth/how-to/basic-example/ (switch to konnect api tab).
Preview link:
> fix: Rename runtime group id to control plane id

- app/_assets/stylesheets/header-v2.less
Unsetting max navbar menu height on mobile. Accidentally broke it when setting a max height for the nav to deal with overlap, didn't account for the menu transformation on mobile.
Broken:
Resize any page down to mobile size: https://deploy-preview-6158--kongdocs.netlify.app/
> Fix: Mobile top nav

- api-specs/Gateway-EE/3.4/kong-ee-3.4.yaml
- api-specs/Gateway-OSS/3.4/kong-oss-3.4.yaml
Replacing some characters, as they're throwing errors when the specs are uploaded to Dev Portal.
Preview link: Changed already live, this is just syncing the source files:
https://docs.konghq.com/gateway/api/admin-ee/latest/
https://docs.konghq.com/gateway/api/admin-oss/latest/
> fix: Replace Gateway API spec characters causing errors

- app/konnect/getting-started/configure-mesh.md
- app/konnect/mesh-manager/service-mesh.md
MinK zones will be billed based on consumption. We need to call this out in docs so that customers know when they will be billed for something and how much it will be.
DOCU-3418
Relates to https://github.com/Kong/docs.konghq.com/pull/6099. I chose to branch these changes off of the `mink-beta` branch since the changes needed to happen on the MinK docs. Let me know if you think I missed anything by doing this or if I should branch differently. I figured this is also okay since MinK billing will release at the same as MinK.
Preview link:
> feat: MinK zone consumption billing notes

- app/_includes/md/availability-stages.md
- app/_layouts/docs-v2.html
The phrasing previously stated "should not be deployed in production" which isn't accurate in a SaaS world. The new phrasing says "should not be depended upon in production"
Preview link:
> Update tech preview/beta terminology to be Konnect friendly

- app/_data/kong_versions.yml
Bumping CE version to 2.8.4, DOCU-3482/KAG-2394
Preview link:
> chore: CE patch version 2.8.4 bump

- Makefile
Add a `make kill-ports` command to clear things that are listening on port 4000 (Jekyll) and port 3036 (Vite).
This is useful when you change branch without stopping the server first and the port continues to be used by a zombie process.
> Add 'make kill-ports' command

- app/_src/gateway/reference/configuration.md
- autodoc-conf-ee/run.lua
Moved the DP Resilience feature (Cluster Fallback) properties to their own section for better organization and linking. Loosely related to https://github.com/Kong/docs.konghq.com/pull/6064.
Also noticed our Wasm section had no reference to the text 'WebAssembly' which resulted in it not being found easily. Added that to the title of that section to allow for better searchability.
> Sectioned cluster_fallback configs + added WebAssembly text to Wasm section

- .github/renovate.json
Combine all non-major renovate updates into a single PR
> Group renovate updates in to a single PR

- app/_src/kubernetes-ingress-controller/support-policy.md
KIC EOL dates were incorrect. Updated to match 2.11 EOL
Preview link: [/kubernetes-ingress-controller/latest/support-policy/](https://deploy-preview-6117--kongdocs.netlify.app//kubernetes-ingress-controller/latest/support-policy/)
> Update KIC EOL dates

- app/_data/docs_nav_konnect.yml
Moving out the "Org Management" section up one level. The content under it is very buried and we don't need to have that anymore, with Plans and Billing not being its own special section.
Preview link:
> chore: Rearrange org management section in Konnect nav

- app/_hub/kong-inc/exit-transformer/overview/_index.md
The Exit Transformer plugin allows you to execute Lua functions. There is a setting in kong.conf that controls any plugins or other functionality that can do that. There was nothing in the plugin's doc about the setting, so I added that in.
https://konghq.atlassian.net/browse/DOCU-1046
Preview link: https://deploy-preview-6199--kongdocs.netlify.app/hub/kong-inc/exit-transformer/
> Update: Add info about untrusted_lua param to exit transformer plugin

- app/konnect/org-management/org-switcher.md
To navigate back to the org switcher from Konnect. The button now says "View Organizations" rather than "Back to org switcher".
Preview link:
> fix: View Organizations

- app/_hub/kong-inc/request-transformer-advanced/how-to/_templates.md
From ticket:
> The documentation would be more helpful if there was a link back to the using-regexes-in-paths to capture uri from the request transform doc to show how this is actually done. 
> This would provide the additional context of how to initially implement this functionality.
Adding the requested link + minor formatting edits to arrange the steps into an ordered list.
https://konghq.atlassian.net/browse/DOCU-156
Preview link: https://deploy-preview-6198--kongdocs.netlify.app/hub/kong-inc/request-transformer-advanced/how-to/templates/
> Update: Add link to routing reference from Request Transformer Advanced

- app/_src/gateway/reference/router-expressions-language.md
See: https://github.com/Kong/kong/pull/11348
Preview link: https://deploy-preview-6201--kongdocs.netlify.app/gateway/latest/reference/router-expressions-language/
> feat: support HTTP query parameters in expression routes.

- app/_includes/md/plugins-hub/json-object-log.md
There are no units specified for the `kong` latency value so this leads to confusion.
Found the units here: https://github.com/Kong/kong-ee/blob/master/kong/analytics/init.lua#L279-L282
https://konghq.atlassian.net/browse/DOCU-1614
Preview link:
> Update: Add latency units to JSON log format reference for logging plugins

- app/_hub/kong-inc/canary/_metadata.yml
- app/_hub/kong-inc/canary/overview/_index.md
Marking the Canary plugin as not supported for use with KIC.
From ticket:
> It looks like the way the Canary plugin works is not really designed to align with a Kubernetes-native philosophy and it doesn't really make sense to use with KIC.
We now have the Gateway API to cover for this functionality, so linking over to that instead.
https://konghq.atlassian.net/browse/DOCU-869
Preview link: 
https://deploy-preview-6221--kongdocs.netlify.app/hub/kong-inc/canary/
https://deploy-preview-6221--kongdocs.netlify.app/hub/kong-inc/canary/how-to/basic-example/
https://deploy-preview-6221--kongdocs.netlify.app/hub/plugins/compatibility/
> Update: Mark the canary plugin as not recommended for use with KIC

- app/_src/gateway/index.md
Variable was broken and not rendering properly, fixed it.
> Fix broken variable in Gateway overview doc

- app/_src/gateway/reference/configuration.md
- app/gateway/2.8.x/reference/configuration.md
The mem_cache_size parameter in kong.conf mentions that it controls the size of two caches, but doesn't say what the names of the caches are.
According to our [changelog](https://github.com/Kong/kong/blob/master/CHANGELOG-OLD.md#core-32), these two in-memory caches are kong_core_cache and kong_cache.
Resolves doc ticket https://konghq.atlassian.net/browse/DOCU-1878.
Parallel PR to https://github.com/Kong/kong/pull/11680.
Preview link:
> Update: Add cache names to mem_cache_size

- .github/workflows/generate-changelog.yml
- tools/changelog-generator/changelog.js
Two minor changes:
- Let the title of the generated PR include `[skip ci]` so that Netlify doesn't build any previews, since the changelog is not published on the docs site
- Set `vale off` so that vale doesn't run every time the action triggers, since the changelog is not generally spellchecked or heavily formatted.
Preview link:
> chore: Minor adjustments to changelog generator [skip ci]

- app/_src/mesh/features/acmpca.md
- app/_src/mesh/features/cert-manager.md
- app/_src/mesh/features/vault.md
The docs wrong since 2.4.0 - we changed the implementation.
Preview link:
> docs(mesh): adjust external ca verification docs since 2.4.0

- app/_assets/stylesheets/page.less
- app/_hub/kong-inc/jwt-signer/_metadata.yml
- app/_hub/kong-inc/key-auth-enc/_metadata.yml
- app/_hub/kong-inc/openwhisk/_metadata.yml
- app/_hub/kong-inc/vault-auth/_0.3.0/_metadata.yml
- app/_hub/kong-inc/vault-auth/_metadata.yml
- app/_layouts/extension.html
Some konnect-incompatible plugins were displaying Konnect Paid or Konnect Premium badges. This was happening because the metadata was incorrectly set to include either `paid: true` or `premium: true` for these plugins.
Fixing that, and adding a banner to konnect-incompatible plugin landing pages to call that out.
Preview link:
> fix: Plugin tiers for konnect-incompatible plugins

- .github/workflows/linting.yml
Update Vale Github Action so that it only runs against added/copied/modified files.
This also prevents Vale from running on `2.6.x` and `2.7.x` Gateway file changes.
Because of an [API limitation](https://github.com/reviewdog/reviewdog#filter-mode-support-table) two types of `comments` might appear as a result of the check. Excerpt from the docs:
> Note that not all reporters provide full support of filter mode due to API limitation. e.g. github-pr-review reporter uses [GitHub Review API](https://docs.github.com/en/rest/pulls/reviews) and [GitHub Review Comment API](https://docs.github.com/en/rest/pulls/comments) but these APIs don't support posting comment outside diff file, so reviewdog will use [Check annotation](https://docs.github.com/en/rest/checks/runs) as fallback to post those …
> Fix issue with Vale reporting incorrect things as broken

- .github/workflows/check-links.yml
- .github/workflows/generate-changelog.yml
- .github/workflows/linting.yml
- .github/workflows/run-tests.yml
- .github/workflows/scheduled-broken-link-checker.yml
We're spending a lot of (free, but still) build minutes testing commits that are out of date. This PR cancels old builds when new commits are pushed
> Set concurrency.cancel-in-progress for PRs

- app/_src/kubernetes-ingress-controller/deployment/k4k8s.md
Tested and validated [Kong for Kubernetes](http://localhost:8888/kubernetes-ingress-controller/2.12.x/deployment/k4k8s/) guide.
Not sure if the title should be Kong Ingress Controller for Kubernetes.
Preview link:
> fix: Kong for Kubernetes

- app/_plugins/hooks/url_conflicts.rb
Based on a Slack conversation.
By default, Jekyll logs a warning whenever two or more pages have the same output path which has caused us problems in the past because we noticed the issue after releasing the changes.
This change introduces a hook that raises whenever a conflict exists.
Preview link:
> Raise an exception when two or more pages have the same output path

- app/konnect/gateway-manager/plugins/add-custom-plugin.md
- app/konnect/gateway-manager/plugins/update-custom-plugin.md
Turns out that you can't pass a file directly via cURL to our Konnect CP configuration API. The contents of the file don't get escaped correctly. When testing this out originally, I used a mix of cURL and HTTPie, and HTTPie had no issues - but our default cURL instructions have problems here.
Issue was reported on [Slack](https://kongstrong.slack.com/archives/C03NRECFJPM/p1696622470557839).
Updating the doc with Fero's help, tested it all with curl this time around.
The jq instructions are in a "tip", since we can't tell them to use jq if they don't want to or don't have it.
Preview link:
> Fix: curl examples for custom plugins schemas in Konnect

- app/_layouts/docs-v2.html
- app/_src/gateway/kong-manager-oss/index.md
Add Github star button with count next to the page title.
[Preview link](https://deploy-preview-6267--kongdocs.netlify.app/gateway/latest/kong-manager-oss/)
> Add github star button to Kong manager oss page

- .github/workflows/check-links.yml
The broken link checker depends on the netfliy build and adding `[skip ci]` to a PR's title skips netlify from building the preview-app causing the link checker to fail.
Now we also prevent the link-checker from running if `[skip ci]` is present in the PR's title.
Preview link:
> Prevent link checker from running if `[skip ci]` is present in the PR's title

- .github/workflows/sync-submodules.yml
Add Github Action that syncs the `kong-plugins` submodule.
Preview link:
> Add Github Action that syncs kong-plugins submodule

- netlify.toml
Prevent lighthouse from running on `dev`, it was causing issues locally because the plugin requires an older node version
Preview link:
> Don't run lighthouse on `dev`

- .github/workflows/linting.yml
We keep getting a ton of Vale errors whenever the generated Mesh changelog is updated. All our other changelogs have vale off, but this one doesn't because it's autogenerated and that would wipe it out, so I had to add it to our linting file to ignore.
Preview link:
> update: Add generated mesh changelog to vale ignore list

- app/_hub/salt/salt/_metadata.yml
In Kong 3.3, the queue logic was updated, forcing a change to the plugin logic. This is that update.
background: https://konghq.com/blog/product-releases/reworked-plugin-queues-in-kong-gateway-3-3
Preview link:
> Update: Salt plugin now supports new queue in 3.3+

- app/_data/docs_nav_mesh_dev.yml
- app/_plugins/generators/seo/index_entry_builder.rb
- app/_plugins/generators/utils/version.rb
- app/_plugins/generators/versions.rb
- jekyll-dev.yml
- jekyll.yml
- spec/app/_plugins/generators/seo/index_entry/versioned_page_spec.rb
- spec/fixtures/app/_data/docs_nav_mesh_dev.yml
- spec/fixtures/app/_data/kong_versions.yml
Add a `dev` release for Kong Mesh.
This works as it does in Kuma so the mesh team can start using it for the next release.
Preview link:
> DOCU-3320: Add support for Mesh's `dev` release

- .github/workflows/check-links.yml
It raises the following error:
```
The workflow is not valid. .github/workflows/check-links.yml (Line: 26, Col: 9): Unexpected symbol: '"'. Located at position 85 within expression: needs.check.outputs.result == 'false' && !contains(github.event.pull_request.title, "[skip ci]")
```
Preview link:
> Fix broken-link checker

- app/_assets/stylesheets/badges.less
The `enterprise` badge is used in a couple of places that aren't gateway related, mainly Mesh. Renaming it back to just "Enterprise" instead of "Gateway Enterprise" for versatility.
Preview link:
> Chore: Rename badge back to ENTERPRISE

- .github/workflows/generate-changelog.yml
- tools/changelog-generator/changelog.js
Updates the changelog generator after seeing that it was no longer recognizing the skip-changelog tag. I also updated the github action to sync with main before creating a new branch, I suspect that that's why it sometimes overwrites the changelog.
> Update changelog generator [skip-ci]

- app/_src/gateway/kong-manager/auth/ldap/configure.md
Added `ldaps` to the `admin_gui_auth_conf` setting and added to the attribute table. Resolves DOCU-2529.
N/A
> Fix: Missing `ldaps` option in Kong Manager LDAP setup. Resolves DOCU-2529.

- app/konnect/org-management/oidc-idp.md
Fixes the reported issue in Jira [DOCU-3311](https://konghq.atlassian.net/browse/DOCU-3311) which was causing confusion with the `examplepath` name in the testing section of the login URL.
N/A
[DOCU-3311]: https://konghq.atlassian.net/browse/DOCU-3311?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix: Konnect OIDC sign-in & sign-out redirect URIs

- app/_src/gateway/support/browser.md
- app/_src/gateway/support/index.md
- app/_src/gateway/support/third-party.md
Support for Gateway 3.0 was removed in September, so we needed to update our support version docs to reflect that.
DOCU-3519
Preview link:
> update: Remove Gateway 3.0 from supported versions and move to older versions table

- .github/workflows/ci-autofix.yml
Fixes Vale for forks
See https://github.com/Kong/docs.konghq.com/actions/runs/6493878637/job/17635740287
From the logs:
```
Warning: Unable to find merge base between X and Y
Warning: Error checking commit history
Warning: If this pull request is from a forked repository, please set the checkout action `repository` input to the same repository as the pull request.
Warning: This can be done by setting actions/checkout `repository` to ${{ github.event.pull_request.head.repo.full_name }}
```
Preview link:
> Set repository to ${{ github.event.pull_request.head.repo.full_name }}

- app/_src/gateway-operator/get-started/kic/create-gateway.md
- app/gateway-operator/changelog.md
Update docs with 1.0.1 release https://github.com/Kong/gateway-operator/releases/tag/v1.0.1
Preview link:
> kgo: update docs with 1.0.1

- tools/broken-link-checker/full.js
It started to fail after we introduced `app/_data/docs_nav_mesh_dev.yml` because it tried to parse `dev` as a valid version.
Preview link:
> Fix full broken link checker.

- app/_includes/md/kic/prerequisites.md
- app/_src/kubernetes-ingress-controller/guides/services/tcp.md
- port the TCP guide to 3.0
- tested and validated for ingress
- installed Gateway API and tested however, there is an error that reads: "Error from server (NotFound): gateways.gateway.networking.k8s.io "kong" not found"  step3 of **Expose additional ports** section
steps to reproduce: start the cluster, install the CRD "kubectl apply -f https://github.com/kubernetes-sigs/gateway-api/releases/download/v0.8.1/experimental-install.yaml", then enable the feature " kubectl set env -n kong deployment/ingress-kong CONTROLLER_FEATURE_GATES="GatewayAlpha=true" -c ingress-controller" only change the <deployment > is 'kong-controller'
- set $HOST as a variable in the prerequisite because the steps use Host and not  PROXY_IP
- made GatewayAPI the default tab in the steps. …
> fix: Proxy TCP request

- app/_src/kubernetes-ingress-controller/guides/services/udp.md
- Tested and validated the guide.
- The only sections that does not work is "Update the Gateway"
installed Gateway API and tested however, there is an error that reads: "Error from server (NotFound): 
gateways.gateway.networking.k8s.io "kong" not found" step3 of Expose additional ports section
- steps to reproduce: start the cluster, install the CRD "kubectl apply -f https://github.com/kubernetes-sigs/gateway-api/releases/download/v0.8.1/experimental-install.yaml", then enable the feature " kubectl set env -n kong deployment/ingress-kong CONTROLLER_FEATURE_GATES="GatewayAlpha=true" -c ingress-controller" only change the is the name of the deployment 'kong-controller'
Preview link:
> fix: Proxy UDP requests

- app/_includes/md/kic/http-test-routing-resource.md
- app/_src/kubernetes-ingress-controller/guides/services/external.md
tested and validates the guide however, even after installing the CRDs and the Gateway APIs, the [test service](http://localhost:8888/kubernetes-ingress-controller/latest/guides/services/external/#test-the-service) gives 
```
HTTP/1.1 404 Not Found
Date: Thu, 12 Oct 2023 11:23:43 GMT
Content-Type: application/json; charset=utf-8
Connection: keep-alive
Content-Length: 52
X-Kong-Response-Latency: 0
Server: kong/3.4.0
{
"message":"no Route matched with those values"
}%
```
Preview link:
> fix: External Service

- app/_data/tables/support/gateway/packages.yml
- app/_data/tables/support/gateway/third-party.yml
- app/_data/tables/support/gateway/versions/28.yml
- app/_data/tables/support/gateway/versions/31.yml
- app/_data/tables/support/gateway/versions/33.yml
- app/_data/tables/support/gateway/versions/34.yml
- app/gateway/changelog.md
Fixing the following issues with the [Kong Gateway support matrix](https://docs.konghq.com/gateway/latest/support-policy/):
* PostgreSQL 9 and 10 are no longer supported by upstream but our docs claim to support them. Also, PostgreSQL 11 is also going out of support in 3 weeks
* Our support policy doc incorrectly stated the EOLs of many OSes. We have this statement (adjusted for dates/versions) at the top of every version's support table:
" Kong Gateway 2.8 LTS supports the following deployment targets until March 2025, unless otherwise noted by an earlier OS vendor end of life (EOL) date." 
However, our support tables aren't listing the accurate "earlier OS vendor end of life (EOL) dates".
* The support table inaccurately lists available Docker images. We have many new Docker images …
> Fix: Kong Gateway support matrix

- app/_assets/stylesheets/accordion.less
This was caused due to the way the sidebar items (accordion items) expanded and collapsed.
When an accordion item was "collapsed", its:
* max-height was set to 0
* opacity was set to 1 so technically even though they were "hidden" to the naked eye, they were still "visible".
This caused Chrome's and Firefox's `find in page` to count the supposedly "hidden" occurrences of the searched text as part of the results.
Setting the visibility to `hidden` when the item is collapsed, and to `visible` when it is expanded fixed the issue.
Prod:
Preview app:
[Preview link](https://deploy-preview-6325--kongdocs.netlify.app/mesh/latest/introduction/about-service-meshes/)
> DOCU-3435: Find in page counts hidden elements in the result

- app/_src/gateway/kong-enterprise/fips-support/index.md
Add a not to FIPS index page indicating that `FIPS is not supported when running kong gateway enterprise in free mode`.
KAG-2803
> add a note to FIPS index page

- app/konnect/gateway-manager/data-plane-nodes/index.md
Add a note about SSH access to Konnect data plane nodes when using the AWS, Azure, or GCP deployment styles and how it's not allowed directly but need to use the cloud provider tools.
Raised in Slack: https://kongstrong.slack.com/archives/C03NRECFJPM/p1691689181346589
N/A
> Update: SSH access note for instances deployed using Konnect Tech Preview install platforms

- app/_hub/kong-inc/jwt/overview/_index.md
A user asked to clarify the docs in scenario when multiple JWTs tokens are provided: https://github.com/Kong/kong/issues/11796. With the change from some time ago: https://github.com/Kong/kong/pull/9946 - kong rejects request when multiple JWTs were provided that differ from each other. 
This PR explicitly states that the request will be rejected.
Preview link: https://deploy-preview-6353--kongdocs.netlify.app/
A shortcut to the change: https://deploy-preview-6353--kongdocs.netlify.app/hub/kong-inc/jwt/
> fix(jwt): state what happens when multiple JWTs are provided

- app/_src/gateway/kong-enterprise/fips-support.md
- app/_src/gateway/kong-enterprise/fips-support/index.md
- app/_src/gateway/kong-enterprise/fips-support/plugins.md
From https://docs.google.com/document/d/1PJCcO_5DSTbv_08XxDlaS2Cx2-YeYfAencrFhS190AA/edit
and https://github.com/Kong/kong/pull/11725
Preview link:
> Update: reflect latest FIPS support status

- .github/workflows/linting.yml
- app/konnect/gateway-manager/plugins/add-custom-plugin.md
Fix the API URL for uploading custom plugin schemas
Preview link: /konnect/gateway-manager/plugins/add-custom-plugin/
> Fix API URL in Konnect Custom Plugin docs

- app/_src/gateway/reference/configuration-3.0-3.3.md
- app/_src/gateway/reference/configuration.md
Removes examples of adding a path when configuring `portal_gui_host`
Related: https://github.com/Kong/docs.konghq.com/pull/4179
Adding a path to `portal_gui_host` is not supported
> fix(portal) remove examples with path in portal gui host

- app/_data/docs_nav_kic_3.0.x.yml
- app/_src/kubernetes-ingress-controller/guides/services/http.md
We have guides for TCP, UDP and GRPC routing. We were missing a HTTP routing guide
Preview link:
> Add HTTP routing guide

- app/_src/kic-v2/guides/cert-manager.md
Kuma uses labels now instead of annotations.
Preview link:
> Update cert-manager guide to use Kuma labels

- app/_hub/kong-inc/openid-connect/overview/_index.md
When I merged the certificate-bound access token PR(#6284 ), I forgot to add conditional rendering. This fixes that.
Preview link:
> fix: cert bound access token conditional rendering

- app/_src/gateway/production/access-control/enable-rbac.md
As per case: 00038584 the changed examples try to use the token value returned in Step 3 here: https://docs.konghq.com/gateway/latest/production/access-control/enable-rbac/#super-admin-creates-one-admin-for-each-team However this is a hashed value: https://docs.konghq.com/gateway/latest/admin-api/rbac/reference/ and not the actual user token which was set for adminA in Step 1 here: https://docs.konghq.com/gateway/latest/production/access-control/enable-rbac/#super-admin-creates-one-admin-for-each-team
Preview link:
> Fix: Use placeholder token in TBAC examples instead of hashed value

- app/_plugins/generators/seo/index_entry_builder.rb
The sitemap included both `latest` and `1.0.x` URLs.
Fixes the issue by just including `latest`
Preview link:
> [Sitemap] Only include `latest` version for gateway-operator

- app/_src/gateway/kong-manager/workspaces.md
- app/gateway/changelog.md
In 3.5, users can now force delete a workspace. Since this allows them to automatically delete entities associated with the workspace instead of doing it manually, our instructions needed to be updated.
DOCU-3408
Preview link:
> feat: Kong Manager forced workspace deletion

- app/_includes/md/kic/add-tls-conf.md
- app/_src/kubernetes-ingress-controller/guides/services/https-redirect.md
Port content to 3.0
GatewayAPI first tab and Ingress as second tab
Preview link:
> fix: HTTPS redirects

- app/_includes/md/kic/prerequisites.md
KIC prereqs showed the Gateway API results even if Gateway API isn't enabled
Preview link: /kubernetes-ingress-controller/latest/guides/configuring-fallback-service/
> Fix KIC prerequisites
