Kong/docs.konghq.com

app/_src/mesh/plan-and-deploy/license.md
Closes https://github.com/Kong/docs.konghq.com/issues/5303
We are missing description how to update a license.
Netlify link:
=> docs(mesh): add instruction how to update a license

app/_src/mesh/features/kds-auth.md
add missing port in KDS auth example
Netlify link:
=> add missing port in KDS auth example

app/konnect/api/index.md
Updating the PAT page URL to match with what we have in production so that it doesn't lead to 404
Netlify link:
=> Update PAT page url

app/gateway/changelog.md
Corrected the release date of 3.2.1.0 as 30th Feb is an invalid date.
Netlify link:
=> Corrected the release date of 3.2.1.0

app/_src/gateway/key-concepts/routes/index.md
This reverts commit 7149a59e1b6cd9704426972e1dea726ee83c9560.
This documentation update will have to wait until
https://github.com/Kong/kong/pull/10615 is merged.
=> Revert "Fix description of routing priorities with multiple paths (#5402)"

app/_src/gateway/kong-enterprise/secrets-management/backends/aws-sm.md
=> [fix] Invalid json 

app/_includes/md/personal-access-token.md, app/_src/deck/guides/konnect.md, app/konnect/org-management/deactivation.md, app/konnect/updates.md
Reverts Kong/docs.konghq.com#5444
Will merge again at GA
=> Revert "[DOCU-3022][DOCU-3023] Right To Be Forgotten (RTBF) in Konnect & My Account + Navigation updates"

app/konnect/servicehub/index.md
subtitle: Track every service accross your architecture -> subtitle: Track every service across your architecture
Simple typo - accross to across
review:copyedit: Request for writer review.
=> Typo in index.md

app/_src/gateway/admin-api/index.md
=> [fix] Add latency algorithm to upstream object def

app/_hub/kong-inc/proxy-cache-advanced/_index.md
Add `ignore_uri_case` configuration parameter to `proxy-cache-advanced`, similar to https://github.com/Kong/docs.konghq.com/pull/5270/files (for proxy-cache).
Netlify link:
=> docs(proxy-cache-advanced): add ignore_uri_case

app/_data/docs_nav_mesh_2.2.x.yml, app/_plugins/generators/versions.rb, app/_redirects, app/_src/mesh/features/windows.md, app/_src/mesh/index.md, app/mesh/installer_old.ps1
The install page was using older architecture which is not the case anymore according to the IA change.
Netlify link:
=> mesh: update sidebar to follow IA work for install

app/_hub/kong-inc/request-transformer-advanced/_index.md, app/_hub/kong-inc/request-transformer/_index.md
add changelog for untrusted lua to request transformer and request transformer advanced plugins
related:
https://github.com/Kong/kong/pull/10327
https://github.com/Kong/kong-ee/pull/4618
Netlify link:
=> docs(request-transformer): untrusted_lua

app/konnect/compatibility.md, app/konnect/reference/labels.md
- Added a compatibility table to the Compatibility topic in Konnect with info about which Mesh version supports MinK
- Added a section and a link to the Kubernetes labels Mesh topic in the Labels reference page
DOCU-3181
Netlify link:
=> [DOCU-3181] (MinK) Updating existing Konnect topics: Labels and Compatibility tables

app/konnect/runtime-manager/runtime-instances/index.md, app/konnect/updates.md
Adding Version picker in Runtime Manager Quickstart
adding new note under Runtime installation options
Netlify link: https://deploy-preview-5508--kongdocs.netlify.app/konnect/runtime-manager/runtime-instances/
=> [DOCU-3190] Version picker in Runtime Manager Quickstart

app/_src/gateway/admin-api/rbac/reference.md
Fix https://github.com/Kong/docs.konghq.com/issues/5039
=> docs(rbac): fix rbac user-role reference

app/konnect/org-management/teams-and-roles/teams-reference.md
Portal Admin must also have access to Services to manage app reg requests. We are adding an alert banner in Organization in UI. So we are surfacing this info in doc as well
Netlify link:
=> Adding additional info for Portal Admin

app/konnect/getting-started/access-account.md
Matching the password criteria in doc with what we display in product
Netlify link:
=> Update Password Criteria

app/_hub/kong-inc/request-validator/_index.md
=> fix(request-validator): fix content-type breaking change

app/_data/docs_nav_gateway_3.3.x.yml
https://konghq.atlassian.net/browse/DOCU-3216
Adds a link to the nav bar.
=> [DOCU-3216] Status Endpoint link

app/_hub/kong-inc/oauth2/_index.md
Adding a changelog entry here for PR: https://github.com/Kong/kong/pull/10011
[FTI-3983](https://konghq.atlassian.net/browse/FTI-3983?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ)
Netlify link: 
[FTI-3983]: https://konghq.atlassian.net/browse/FTI-3983?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(oauth2): add a changelog entry

app/_src/gateway/reference/key-management.md
Fix typo that caused a variable to appear in plaintext.
Netlify link:
=> Typo in Keys reference doc

app/_src/gateway/admin-api/index.md, app/_src/gateway/plugin-development/pdk/kong.request.md, app/_src/gateway/plugin-development/pdk/kong.response.md, app/_src/gateway/plugin-development/pdk/kong.service.md, app/_src/gateway/plugin-development/pdk/kong.tracing.md, app/_src/gateway/plugin-development/pdk/kong.vault.md, app/_src/gateway/reference/configuration.md, app/konnect/api/runtime-groups-config/index.md
https://konghq.atlassian.net/browse/DOCU-3051
Auto docs for EE and OSS.
=> [DOCU-3051] Auto docs 3.3

app/_src/gateway/admin-api/index.md
=> Spec links

app/_data/docs_nav_konnect.yml, app/konnect/reference/labels.md, app/konnect/runtime-manager/runtime-instances/custom-dp-labels.md
How-to guide for setting up and checking data plane labels in Konnect.
https://konghq.atlassian.net/browse/DOCU-3065
Netlify link: https://deploy-preview-5554--kongdocs.netlify.app/konnect/runtime-manager/runtime-instances/custom-dp-labels/
=> [DOCU-3065] Data plane labels in konnect

app/_src/gateway/production/logging/update-log-level-dynamically.md
=> Fixes to log level doc

app/_hub/kong-inc/request-termination/_index.md
=> [plugin hub] fix rebase error in request termination

app/_src/mesh/features/meshglobalratelimit.md
- updated the instances of `rate limit-service` with `kong-mesh-ratelimit-service`.
- Fixes https://github.com/Kong/docs.konghq.com/issues/5481
Netlify link:
=> [Update] MeshGlobalRateLimit Policy

app/_src/kubernetes-ingress-controller/references/feature-gates.md
Add instructions on how to enable feature gates with KIC
Netlify link:
=> Add KIC FeatureGate with Helm instructions

app/_assets/stylesheets/badges.less
Fix bages for non-plugin docs
Netlify link:
=> Fix badges styles

app/_src/kubernetes-ingress-controller/references/feature-gates.md
Adds KIC 2.10 feature gates.
Part of https://github.com/Kong/kubernetes-ingress-controller/issues/3777.
Netlify link:
=> kic: update feature gates table

app/_src/gateway/support/third-party.md
Make Kong's support stance clearer for third party dependencies.
Netlify link: /gateway/latest/support/third-party/
=> Clarify Third Party support text

app/gateway/changelog.md
Changelog based on [CHANGELOG.md](https://github.com/Kong/kong/blob/master/CHANGELOG.md) and [CHANGELOG-EE.md](https://github.com/Kong/kong-ee/blob/master/CHANGELOG-EE.md) for 3.3.0 and 3.3.0.0.
https://konghq.atlassian.net/browse/DOCU-3169
TO DO:
* ~More links to docs~
* ~Finish checking what the changes actually are (mainly on the EE side)~
* ~Add deprecation & removal reminders from previous releases: cassandra, alpine~
Netlify link: https://deploy-preview-5562--kongdocs.netlify.app/gateway/changelog/
=> [DOCU-3169] Changelog for gateway 3.3.0.0

app/_data/kong_versions.yml, app/gateway/changelog.md
Changelog and version bump for Kong Gateway 3.2.2.2.
https://konghq.atlassian.net/browse/DOCU-3200
Netlify link:
=> Release: Gateway 3.2.2.2

app/_src/gateway/key-concepts/routes/expressions.md
Fixing my silly typo mistakes :(
=> docs(expressions): fix typo

app/gateway/changelog.md
The version in the 3.3. pr was different
=> [fix] 3.2.2 changelog

app/_hub/kong-inc/jwt/_index.md
Reuse the secret/key from the `Create a JWT credential` step
=> Align all samples

app/_hub/moesif/kong-plugin-moesif/_metadata.yml, app/_hub/moesif/kong-plugin-moesif/schemas/_index.json
=> Moesif updates

app/konnect/org-management/oidc-idp.md, app/konnect/org-management/okta-idp.md
Updating the path to access Auth Settings
Eng work tracked in - https://konghq.atlassian.net/browse/KHCP-7417
Aha - https://konghq.aha.io/features/KP-294
Netlify link: https://deploy-preview-5642--kongdocs.netlify.app/konnect/org-management/oidc-idp/
https://deploy-preview-5642--kongdocs.netlify.app/konnect/org-management/okta-idp/
=> Update Organization Path

app/_assets/javascripts/navbar.js, app/_includes/nav-v2.html, app/_layouts/landing-page.html
Remove the search bar from the legacy site.
Algolia search results only serve the latest docs which aren't relevant to the legacy site and were causing confusion.
Netlify link:
=> Legacy Site: Remove search

.github/workflows/scheduled-broken-link-checker.yml, tools/broken-link-checker/excluded.json
Runs a full broken link scan every Sunday.
Once we merge this, we can [subscribe](https://github.com/integrations/slack/blob/main/README.md#actions-workflow-notifications) on slack and receive notifications 
Netlify link:
=> Run a full broken links scan every sunday

app/gateway/changelog.md
[DOCU-3246](https://konghq.atlassian.net/browse/DOCU-3246)
Netlify link: https://deploy-preview-5673--kongdocs.netlify.app/gateway/changelog/
[DOCU-3246]: https://konghq.atlassian.net/browse/DOCU-3246?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DOCU-3246] 3.2.2.3 changelog

api-specs/Konnect/json/konnect.json, api-specs/Konnect/yaml/konnect.yaml
Adds konnect specs for the purpose of creating an insomnia button.
=> chore: Insomnia button creation add specs

app/konnect/api/index.md, app/konnect/api/runtime-groups-config/index.md
This PR adds a link to the beta API spec and a link to the insomnia button.
=> Chore: Konnect API add links + button

app/_src/gateway/get-started/key-authentication.md
Fixed a grammatical error in one of the doc pages
=> Fix grammar error in key-authentication.md

app/_includes/md/plugins-hub/json-object-log.md, app/_includes/md/plugins-hub/log-format.md
This PR adds a workspace name in the logging payload.
(https://konghq.atlassian.net/browse/FTI-4728)
The Kong-ee's PR is merged. https://github.com/Kong/kong-ee/pull/5339
Netlify link:
=> feat(logging): add workspace name in the logging payload (#5251)

docs/templates/kong-plugin-template/_metadata.yml, docs/templates/partner-plugin-template/_metadata.yml
Some more adjustments for the plugin templates to make it clear what you're being asked to do.
Main fix is the description for `support_url`. Was asked to make it clear that this is where people can file tickets/reports.
Netlify link:
=> Plugin templates: adjustments for clarity

app/_hub/kong-inc/rate-limiting-advanced/_metadata.yml
updating based on feedback from Saju.
RLA description was causing some confusion for prospect so removing content that makes it seem like the RLA was just re-engineered version of RL. 
Netlify link:
=> Updating the description for RLA

app/konnect/analytics/reference.md
Jira: https://konghq.atlassian.net/browse/DOCU-3158
Updated "Reports reference" section using "API product" and "API product version" instead of "Service" and "Service version". Dimensions still use camel case.
PR points to the `feat/api-products` branch where @cloudjumpercat and I collaborate on.
Netlify link:
=> feat(api-products): updated analytics reports reference page

app/konnect/org-management/teams-and-roles/manage.md, app/konnect/org-management/teams-and-roles/roles-reference.md
- Updated the Manage Teams doc because they added a new tab for Mesh Control Plane.
- Added a new table to Roles Reference for the Mesh control plane roles
DOCU-3217
Netlify link:
=> [DOCU-2966] Add MinK permissions

app/_hub/kong-inc/opentelemetry/_changelog.md, app/_hub/kong-inc/opentelemetry/_index.md
https://github.com/Kong/kong/pull/11075
Netlify link:
=> feat(opentelemetry): add AWS header propagation

app/konnect/org-management/audit-logging/reference.md
Uncommenting a line about access logs, this was missed in the release.
Netlify link:
=> Audit logs: Uncomment access logs list item

app/_data/docs_nav_mesh_2.3.x.yml, app/_data/kong_versions.yml
=> Bump mesh version

.github/workflows/linting.yml, Gemfile, Gemfile.lock, app/_data/docs_nav_mesh_2.3.x.yml, app/_data/kong_versions.yml, jekyll-dev.yml, jekyll.yml
=> Release Mesh version 2.3

app/_hub/kong-inc/jwt/_index.md
replace  VARIABLE  with  `{variable}`
Netlify link:
=> Update jwt _index.md

app/konnect/org-management/oidc-idp.md
Added docs for advanced OIDC configuration settings. 
https://konghq.aha.io/epics/KP-E-313
Advanced settings are visible here: https://cloud.konghq.com/global/organization/idp-settings#authentication-scheme
Netlify link:
=> Add advanced settings instructions

app/konnect/runtime-manager/kic.md
=> Removing note that KIC in Konnect is only for Enterprise tier today

app/_data/kong_versions.yml
Changelogs were updated, but not the release versions, so the install docs still list old versions (eg [Docker](https://docs.konghq.com/gateway/latest/install/docker/)).
Netlify link: https://deploy-preview-5791--kongdocs.netlify.app/gateway/latest/install/docker/
=> Update release versions for 2.8.4.2 & 3.3.1.0

app/enterprise/2.1.x/deployment/installation/overview.md, app/enterprise/2.2.x/deployment/installation/overview.md, app/enterprise/2.3.x/deployment/installation/overview.md, app/enterprise/2.4.x/deployment/installation/overview.md, app/enterprise/2.5.x/deployment/installation/overview.md, app/konnect/runtime-manager/index.md, app/mesh/1.2.x/install.md, app/mesh/1.3.x/install.md, app/mesh/1.4.x/install.md, app/mesh/1.5.x/install.md, app/mesh/1.6.x/install.md, archive/enterprise/1.3-x/deployment/installation/overview.md, archive/enterprise/1.5.x/deployment/installation/overview.md
Fixing the non-Mesh broken links from https://github.com/Kong/docs.konghq.com/actions/runs/5497092610/jobs/10017523676. 
Netlify link:
=> chore: Fix broken links

app/_layouts/default.html
Remove Twitter and facebook SDKs. We no longer support `share on X` so it's safe to remove it for everyone.
Let's see how this affects the load times and then we can proceed to prevent some scripts from loading in China. 
Netlify link:
=> Remove twitter and facebook sdks.

app/_hub/kong-inc/request-transformer/_index.md
Fix some examples to avoid confusion
N/A
- [] Review label added
=> fix(request-transformer): header examples

netlify.toml
Update lighthouse config, it now runs against the preview app by default.
Netlify link:
=> Change lighthouse config 

app/_hub/kong-inc/opentelemetry/_changelog.md
https://github.com/Kong/kong/pull/11220
Netlify link:
=> feat(opentelemetry): support the  parameter as referenceable

app/_data/docs_nav_deck_1.24.x.yml, app/_src/deck/reference/deck_file.md, app/_src/deck/reference/deck_file_add-plugins.md, app/_src/deck/reference/deck_file_add-tags.md, app/_src/deck/reference/deck_file_convert.md, app/_src/deck/reference/deck_file_list-tags.md, app/_src/deck/reference/deck_file_merge.md, app/_src/deck/reference/deck_file_openapi2kong.md, app/_src/deck/reference/deck_file_patch.md, app/_src/deck/reference/deck_file_remove-tags.md, app/_src/deck/reference/deck_file_validate.md
CLI references for new `deck file` commands.
In progress: cleaning them up, and will make a corresponding PR in decK repo so we don't have to make the changes each time we generate docs.
Netlify link:
=> decK file commands

app/_data/tables/support/gateway/versions/34.yml, app/_includes/md/gateway/setup.md, app/_includes/md/installation.md, app/_src/deck/faqs.md, app/_src/gateway/install/docker/index.md, app/_src/gateway/kong-enterprise/analytics/index.md, app/_src/gateway/kong-enterprise/analytics/reports.md, app/_src/gateway/kong-enterprise/audit-log.md, app/_src/gateway/kong-enterprise/fips-support/index.md, app/_src/gateway/kong-plugins/authentication/oidc/cognito.md, app/_src/gateway/kong-plugins/rate-limiting/algorithms/rate-limiting.md, app/_src/gateway/plugin-development/access-the-datastore.md, app/_src/gateway/plugin-development/custom-entities.md, app/_src/gateway/production/clustering.md, app/_src/gateway/production/deployment-topologies/index.md, app/_src/gateway/production/deployment-topologies/traditional/index.md, app/_src/gateway/production/tracing/index.md, app/_src/gateway/reference/cli.md, app/_src/gateway/reference/configuration.md, app/_src/gateway/upgrade-v2.md, app/konnect/getting-started/import.md, autodoc-conf-ee/run.lua
Cassandra has been removed from Kong Gateway for 3.4, so the docs are doing the same.
Took the following approach, depending on the type of content:
* Removed Cassandra from supported third-party apps list for 3.4
* For most content, I either wrapped the Cassandra info in `if_version` tags and left 3.4 without Cassandra, or rephrased and split into two if_version blocks, `lte` and `gte`.
* For content that didn't need to mention Cassandra - such as places where Postgres and Cassandra were listed in brackets as extra info, I removed it entirely. 
* Removed or version tagged CLI and config ref docs. When we generate them, we won't need to make changes to the params Cassandra touched.
* Removed Cassandra from conf-ee generation script.
https://konghq.atlassian.net/browse/DOCU-3224
No …
=> [DOCU-3224] Remove cassandra from 3.4

app/_plugins/blocks/navtabs.rb
Adding a selector to navtabs to help when scraping install instructions
Netlify link: N/A
=> Add data-panel attribute to navtabs

app/konnect/api/identity-management/identity-integration.md
Resolves DOCU-2969, updating the parameter names in one of the request calls.
Jira: [DOCU-2969](https://konghq.atlassian.net/browse/DOCU-2969)
Netlify link:
- [y] Review label added
- [y] PR pointed to correct branch
[DOCU-2969]: https://konghq.atlassian.net/browse/DOCU-2969?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Resolve DOCU-2969, update request parameters

.github/workflows/sync-kuma-submodule.yml
=> fix(.github): add missing group to sync-kuma-submodule

app/gateway/2.8.x/get-started/comprehensive/expose-services.md
Removing Admin API call for verification of a Service, Route, or Plugin.
Jira: [DOCU-2334](https://konghq.atlassian.net/browse/DOCU-2334)
Netlify link: 
- [y] Review label added 
- [y] PR pointed to correct branch (`main` for immediate publishing, or a release branch: e.g. `release/gateway-3.2`, `release/deck-1.17`)
[DOCU-2334]: https://konghq.atlassian.net/browse/DOCU-2334?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update for v2.8, resolve DOCU-2334.

app/_src/gateway/admin-api/admins/reference.md, app/enterprise/2.1.x/admin-api/admins/reference.md, app/enterprise/2.2.x/admin-api/admins/reference.md, app/enterprise/2.3.x/admin-api/admins/reference.md, app/enterprise/2.4.x/admin-api/admins/reference.md, app/enterprise/2.5.x/admin-api/admins/reference.md, app/gateway/2.6.x/admin-api/admins/reference.md, app/gateway/2.7.x/admin-api/admins/reference.md, app/gateway/2.8.x/admin-api/admins/reference.md, archive/enterprise/0.35-x/admin-api/admins/reference.md, archive/enterprise/0.36-x/admin-api/admins/reference.md, archive/enterprise/1.3-x/admin-api/admins/reference.md, archive/enterprise/1.5.x/admin-api/admins/reference.md
Fixes some typos found in the _Admin Reference_ in Admin API docs.
preåvious → previous
Netlify link:
=> fix(admin-api): typos in admins reference

app/_data/docs_nav_gateway_3.4.x.yml
Updating 3.4 to pull in changes made in 3.3 on `main` since the branches split.
Should fix the broken build on 3.4 branch.
=> chore: 3.3 > 3.4 nav changes

app/konnect/dev-portal/customization/index.md
Adds some more clarity on what the user needs to set in the developer portal settings in order to use the OSS portal.
Netlify link: https://deploy-preview-5888--kongdocs.netlify.app/konnect/dev-portal/customization/#complete-customization-using-the-open-source-dev-portal
=> chore: update docs for more clarity around oss portal

app/_hub/moesif/kong-plugin-moesif/_index.md, app/_hub/moesif/kong-plugin-moesif/_metadata.yml
Add: badges for Konnect/Free
Fix: Landing pages for Kong specific
Netlify link:
=> Add: badges for Konnect/free support, fix landing pages

api-specs/Gateway-EE/3.4/kong-ee-3.4.yaml, api-specs/Gateway-OSS/3.4/kong-oss-3.4.yaml
Last few things caught in the changelog that weren't generated by the admin api spec generator.
=> AdminAPI - Add cascade query param to workspace endpoints, fix issue with validate plugin endpoint.

app/_data/docs_nav_gateway_3.4.x.yml
Chore PR to update 3.4 nav.
Netlify link https://deploy-preview-5908--kongdocs.netlify.app/gateway/latest/
=> chore: Copy over nav changes from 3.3 to 3.4

app/gateway/2.8.x/support-policy.md
Follow on to https://github.com/Kong/docs.konghq.com/pull/5902 for 2.8 content
What did you change and why? DOCU-3358
Netlify link:
=> fix: modify language around patches

app/konnect/analytics/index.md, app/konnect/updates.md
Added release notes and a single section to highlight the new display limit on reports as well as any contextual chart.
Aha: https://konghq.aha.io/features/KP-312
Netlify link:
=> increased display limit improvement [KP-312]

api-specs/Gateway-EE/3.4/kong-ee-3.4.json, api-specs/Gateway-OSS/3.4/kong-oss-3.4.json, app/_src/gateway/admin-api/index.md
Updates the Insomnia buttons in the admin API spec and adds JSON versions of the admin API.
=> Update Insomnia buttons in Admin API spec

api-specs/Gateway-EE/3.4/kong-ee-3.4.json, api-specs/Gateway-EE/3.4/kong-ee-3.4.yaml
override message in the summary field not description.
=> Fix: Issue with override message in the wrong field

app/_data/tables/version_errors_konnect.yml
Fixes malformed yaml introduced in https://github.com/Kong/docs.konghq.com/pull/5918.
This causes the change metadata table to appear empty.
Netlify link:
=> fix: malformed yml

app/gateway/changelog.md
Changelog date was listed as TBA, changed to 08/09/23
=> Fix: Add date to gateway changelog

app/konnect/runtime-manager/configuration/vaults/how-to.md, app/konnect/runtime-manager/configuration/vaults/index.md, app/konnect/updates.md
- Added release note that explains the new feature
- Modified the Secrets/Vault overview bullet a little
- Added a new step to the vault config instructions as well as links to Gateway vault config docs
DOCU-3351
Netlify link:
=> feat: Update docs for Konnect support of vault secret TTL rotation

app/_assets/stylesheets/header-v2.less, app/_includes/nav-v2.html, app/_layouts/landing-page.html
[Jira ticket](https://konghq.atlassian.net/browse/DOCU-3348)
Move search to topnav in landing page
Netlify link:
=> DOCU-3348: Move search bar to topnav in home

app/_src/deck/reference/deck_file_add-plugins.md
Noticed an issue with the example provided in the docs, so created this PR to fix it.
Netlify link:
=> Updated deck file add-plugins reference

app/_data/docs_nav_konnect.yml, app/_redirects, app/konnect/updates.md
Consumer groups have been added to Konnect following the Gateway 3.4 release. 
https://konghq.atlassian.net/browse/DOCU-3398
=> Consumer groups scoping support for Konnect

app/konnect/runtime-manager/runtime-instances/index.md
Updated Install Options image to latest version, as well as listed out the different installation options for accessibility.
Slack thread: https://kongstrong.slack.com/archives/C059HUS5ALE/p1691688847299799
- [y] Review label added 
- [y] PR pointed to correct branch (`main` for immediate publishing, or a release branch: e.g. `release/gateway-3.2`, `release/deck-1.17`)
=> Update Konnect Runtime Install Options image

app/_redirects
=> fix(_redirects): add missing mesh opa redirect

README.md
Fixes the status badge that is broken
=> Fix: Status badge on README

app/_hub/kong-inc/response-transformer/_index.md
=> fix example

app/konnect/reference/labels.md, app/konnect/reference/plugins.md
Not a lot of changes here. 
https://konghq.atlassian.net/browse/DOCU-3379
=> Konnect rename: references

app/konnect/api/identity-management/identity-integration.md, app/konnect/api/index.md, app/konnect/api/portal-auth/portal-rbac-guide.md, app/konnect/org-management/audit-logging/reference.md, app/konnect/org-management/deactivation.md
I will submit a different PR for spec changes. 
https://konghq.atlassian.net/browse/DOCU-3378
=> Konnect Rename: API section

app/konnect/dev-portal/access-and-approval/azure.md, app/konnect/dev-portal/access-and-approval/manage-app-connections.md, app/konnect/dev-portal/applications/application-overview.md, app/konnect/dev-portal/applications/dev-reg-app-service.md, app/konnect/dev-portal/applications/dynamic-client-registration/auth0.md, app/konnect/dev-portal/applications/dynamic-client-registration/azure.md, app/konnect/dev-portal/applications/dynamic-client-registration/curity.md, app/konnect/dev-portal/applications/dynamic-client-registration/index.md, app/konnect/dev-portal/applications/dynamic-client-registration/okta.md, app/konnect/dev-portal/applications/enable-app-reg.md, app/konnect/dev-portal/customization/index.md, app/konnect/dev-portal/customization/self-hosted-portal.md, app/konnect/dev-portal/index.md, app/konnect/dev-portal/troubleshoot/index.md
This PR renames: 
```
Runtime Manager to Gateway Manager
Runtime Groups to Control Plane
Composite Runtime Groups to Control Plane Group
Runtime Instances to Gateway Instances
```
Also did some copy edits and minor restructuring. 
https://konghq.atlassian.net/browse/DOCU-3374
=> Konnect Rename: Dev Portal section

app/konnect/index.md, app/konnect/updates.md
Added a changelog item to release our pre-built reports feature ([Aha ticket](https://konghq.aha.io/features/KP-204)) and an intro sentence into the Analytics section inside the Konnect intro chapter. This feature is rather small and is only for new organization. Therefore, I think we don't need a lot of docs changes.
[Here](https://docs.google.com/spreadsheets/d/1QnwrHOjR-K-H5w9FQAWltNvq_H0OF8vv-y19o-5CtD0/edit#gid=0) is a list of the pre-built reports we deploy for all new organizations.
Netlify link:
=> feat(pre-built-reports): added changelog entry and an intro sentence

app/_assets/entrypoints/application.js, app/_assets/javascripts/promo-banner.js, app/_assets/stylesheets/header.less, app/_includes/nav-v2.html
Related [Jira ticket](https://konghq.atlassian.net/browse/DOCU-3429)
Add summit hackathon banner to the site
Netlify link:
=> Add summit hackaton banner

app/_data/tables/features/mesh.yml, app/_src/mesh/features/index.md, app/_src/mesh/features/windows.md, app/_src/mesh/gettingstarted.md, app/_src/mesh/install.md, app/_src/mesh/installation/windows.md
Remove Windows support from KM 2.4 onwards
Netlify link:
=> Add if_versions tags so windows support does not show up in KM v2.4

app/_assets/stylesheets/header.less
=> Fix banner styles

app/konnect/account-management/index.md, app/konnect/org-management/system-accounts.md, app/konnect/org-management/teams-and-roles/index.md, app/konnect/org-management/teams-and-roles/manage.md, app/konnect/org-management/teams-and-roles/roles-reference.md, app/konnect/org-management/teams-and-roles/teams-reference.md, app/konnect/org-management/users.md
https://konghq.atlassian.net/browse/DOCU-3376
Renames docs in the administer section.
=> Konnect rename: Administer section

app/_assets/javascripts/modal.js, app/_assets/javascripts/navbar.js
Fix menus on mobile, they weren't opening.
Desktop using the mouse
Desktop using the keyboard
Mobile
Unrelated: Fixed a js error with the modal.
Netlify link:
=> Fix menus on mobile

jekyll-dev.yml, jekyll.yml
YAML assets are being rendered in the default template in prod. This PR explicitly sets no layout to fix the issue
Netlify link: 
/assets/kubernetes-ingress-controller/examples/tcp-echo-service.yaml
=> Fix YAML assets

app/_hub/kong-inc/rate-limiting/_index.md, app/_hub/salt/salt/_metadata.yml
Updating for Konnect compatibility & Kong version support
taking colleagues work and putting into PR on main for Kong's docs repo
Netlify link:
=> add konnect and update version compatibility

app/_data/docs_nav_konnect.yml, app/konnect/api/index.md
update links to api specs in overview page to reference evergreen links, repeat spec description from devportal description field, update nav links to consistently refer to API spec and use evergreen links. 
Netlify link: https://deploy-preview-6067--kongdocs.netlify.app/konnect/api/
=> Post-launch tidy of Konnect API overview page + nav

app/_assets/javascripts/modal.js, app/_assets/stylesheets/modal.less, app/_layouts/docs-v2.html
* Remove grey background from the modal
* Make the modal show on all docs pages
* Update text to match the CTA in Kong Manager
Netlify link: /gateway/latest/
=> Update Konnect modal

app/konnect/org-management/audit-logging/reference.md
The audit log message content has been renamed.
https://konghq.atlassian.net/browse/TPS-1644
N/A
Preview link:
=> Add change notice

app/_src/gateway/breaking-changes/32x.md, app/gateway/changelog.md
- I added the 3.2.2.4 changelog because that version will be released soon.
DOCU-3366
Netlify link: https://deploy-preview-5947--kongdocs.netlify.app/gateway/changelog/#3224
=> chore: Add 3.2.2.4 changelog

app/_src/gateway/admin-api/admin-api-3.1.x.md, app/_src/gateway/admin-api/index.md, app/konnect/api/identity-management/identity-integration.md, app/konnect/api/runtime-groups-config/index.md, app/konnect/dev-portal/access-and-approval/manage-teams.md, app/konnect/gateway-manager/control-plane-groups/how-to.md, app/konnect/gateway-manager/control-plane-groups/migrate.md, app/konnect/gateway-manager/data-plane-nodes/custom-dp-labels.md, app/konnect/gateway-manager/data-plane-nodes/renew-certificates.md, app/konnect/org-management/system-accounts.md
List of all changes in the doc linked on the ticket
https://konghq.atlassian.net/jira/software/c/projects/DOCU/boards/58?modal=detail&selectedIssue=DOCU-3457
=> Update API urls to match rename changes

app/_data/docs_nav_konnect.yml
https://konghq.atlassian.net/browse/DOCU-3462
Not in this PR: 
- Add an insomnia button to the spec 
This has to be addressed in the spec itself and will be addressed once we merge everything to main. 
It will look like this:
=> Retire handwritten control plane config API docs

app/_src/kubernetes-ingress-controller/guides/using-tcpingress.md, app/_src/kubernetes-ingress-controller/guides/using-udpingress.md, app/assets/kubernetes-ingress-controller/examples/echo-service.yaml
Tested, validated, and formatted.
Preview link:
=> [fix] Exposing a TCP Service

app/konnect/updates.md
=> Rename: changelog

app/_data/konnect_oas_data.json
This PR updates the identity API from v2 to v3.
=> Identity API v2 -> v3 changes

app/_api/konnect/control-planes/_index.md, app/_data/docs_nav_konnect.yml, app/_data/konnect_oas_data.json
Adds the control plane v2 api to the branch. Deprecates runtime groups API.
=> add control planes v2 api to Konnect Great rename branch

app/konnect/updates.md
The Aha changelog was very outdated and written for an internal audience (it mentioned Mesh Manager). It was also missing the list of necessary changes that users will need to know to update their APIs and decK files. it also needed some minor formatting, which is never part of the Aha entry - our docs are formatted differently from Aha.
@acgoldsmith I know you want us to be able to use release notes as-is from Aha, but this one is especially egregious - listing an unreleased feature, missing actual necessary information.
Preview link: https://deploy-preview-6139--kongdocs.netlify.app/konnect/updates/
=> Chore: Changelog fix

app/_data/konnect_oas_data.json
=> chore: Sync Konnect OAS Data

app/_data/konnect_oas_data.json
=> Add deprecated to Runtime groups API

app/konnect/api/index.md
Update Insomnia link on API index site.
=> update insomnia link

app/_data/docs_nav_konnect.yml
alphabetize the API specs in the nav
Preview link:
=> Fix: alphabetize the specs in the nav

app/_src/kubernetes-ingress-controller/guides/using-tcpingress.md, app/_src/kubernetes-ingress-controller/guides/using-udpingress.md, app/assets/kubernetes-ingress-controller/examples/echo-service.yaml
Tested, Validated, and Formatted the UDP service guide
Preview link:
=> fix: Exposing UDP service

app/_includes/md/kic/http-test-routing.md, app/_includes/md/kic/prerequisites.md, app/_src/kubernetes-ingress-controller/guides/redis-rate-limiting.md
Formatting changes and curl option changes.
Used placeholders because the command varies based on the install method
Preview link:
=> fix: Using Redis for rate limiting

changelog.md
This is a scheduled pull request to update the changelog.
=> Automated Changelog update

app/_api/konnect/mesh-manager/_index.md, app/_data/docs_nav_konnect.yml, app/_data/konnect_oas_data.json
Currently (for beta), we just had a link to beta specs. I needed to add a new API spec in the new format for Mesh Manager. 
DOCU-3481
Preview link:
=> feat: Mesh Manager API specs

app/_data/konnect_oas_data.json
=> Change control plane spec v1 -> v2 [skip-ci]

app/_src/kubernetes-ingress-controller/references/annotations.md
Add a `konghq.com/rewrite` annotation to the KIC annotation reference.
Netlify link: https://deploy-preview-6086--kongdocs.netlify.app/kubernetes-ingress-controller/latest/references/annotations/
This section is not currently visible due to the version gate.
=> doc(kic) add rewrite annotation

app/_src/kubernetes-ingress-controller/guides/configuring-https-redirect.md
Tested, validated, and rewrote the guide.
Preview link:
=> fix: Configuring https redirect

app/_data/kong_versions.yml
bump deck to 1.27.1
Preview link:
=> chore: Update kong_versions.yml

api-specs/Gateway-EE/3.4/kong-ee-3.4.yaml, api-specs/Gateway-OSS/3.4/kong-oss-3.4.yaml
Updating service description to be more accurate per request from eng.
Will need to update on Dev Portal after.
https://konghq.atlassian.net/browse/DOCU-1086
Preview N/A
=> Update: Service description in API specs [skip ci]

app/_hub/kong-inc/aws-lambda/overview/_index.md
Previous line wasn't clear and readers were confused. The suggested text makes it clearer what the "additional headers" are.
https://konghq.atlassian.net/browse/DOCU-1554
Preview link:
=> fix: AWS Lambda plugin headers line

app/_assets/entrypoints/application.js, app/_assets/stylesheets/header.less, app/_includes/nav-v2.html
Removing banner advertising summit hackathon, as it is now over.
Preview link:
=> chore: Remove summit hackathon banner

app/404.html, app/_assets/stylesheets/pages/404.less
Docs 404 page had bad alignment and outdated links. Making some adjustments to the layout and using better element hierarchy. 
Preview link: https://deploy-preview-6210--kongdocs.netlify.app/404
=> Update: Docs 404 page

app/_hub/kong-inc/canary/_metadata.yml, app/_hub/kong-inc/canary/overview/_index.md
Change term used to describe Canary plugin to something clearer.
Preview link:
=> fix: Use framework instead of philosophy [skip ci]

app/_data/docs_nav_kic_2.11.x.yml, app/_data/docs_nav_kic_2.12.x.yml
removed the duplicate URLs in the nav files
Preview link:
=> fix: Fix the URLs

app/konnect/updates.md
link to docs for custom plugins
Preview link:
=> chore: update changelog

.github/workflows/auto-close-kong-issues.yml
Update the Github Action to use a token with the right permissions generated by  a github app
Preview link:
=> Fix Auto Close Kong Issues GH action

jekyll-dev.yml, jekyll.yml
We're adding these to kuma-website so adding it them here already so the auto update works fine
Preview link:
=> feat(mesh): proactively add new variable used in kuma-website

Makefile
It runs Jekyll in verbose mode making it easier to debug stuff locally.
Preview link:
=> DOCU-2842: Add `run-debug` command to Makefile

.github/workflows/sync-submodules.yml
It has the necessary permissions
Preview link:
=> Use `secrets.PAT` as token for submodule sync action

app/_data/kong_versions.yml, app/gateway/changelog.md
Changelog for Gateway EE 3.4.1.1 and OSS 3.4.2 releases.
Do not merge, need a link to blog.
Preview link:
=> Release: Changelog and version bump for Gateway 3.4.1.1 and 3.4.2

app/_data/kong_versions.yml, app/gateway/changelog.md
Changelog for Gateway EE 3.3.1.1 patch version.
Preview link:
=> Release: Changelog and version bump for Gateway 3.3.1.1

app/_data/kong_versions.yml, app/gateway/changelog.md
Changelog for Gateway EE 3.2.2.5 patch version.
Preview link:
=> Release: Changelog and version bump for Gateway 3.2.2.5

app/_data/kong_versions.yml, app/gateway/changelog.md
Changelog for Gateway EE 3.1.1.6 patch version.
Preview link:
=> Release: Changelog and version bump for Gateway 3.1.1.6

app/_data/kong_versions.yml, app/gateway/changelog.md
Changelog for Gateway EE 2.8.4.4 patch version.
Preview link:
=> Release: Changelog and version bump for Gateway 2.8.4.4

app/_src/gateway/production/deployment-topologies/hybrid-mode/setup.md
Docs for https://github.com/Kong/kong/pull/11625 which adds dp metadata (labels) for on-premise hybrid mode.
Preview link:
=> feat(labels): add on premise dp labels

tools/changelog-generator/changelog.js
The path to the file was wrong, it was trying to read it from the tool's folder instead of the repo's root.
This caused the action to override the existing file instead of appending the changes to it
Preview link:
=> Fix changelog-generator

app/konnect/dev-portal/access-and-approval/add-teams.md
When this was first published, we weren't able to get SME confirmation on the correct steps for setting up the IdP configuration. Users still needed this information, as well as information about configuring groups claims, so I added those in.
DOCU-3498
Preview link:
=> update: Portal OIDC teams mapping post-GA improvements for IdP config instructions

app/_includes/md/kic/prerequisites.md
Added the Gateway API install steps
Preview link:
=> fix: Prerequisites

app/_includes/md/kic/http-test-routing-resource.md, app/_includes/md/kic/http-test-routing.md, app/_includes/md/kic/http-test-service.md, app/_src/kubernetes-ingress-controller/plugins/acl.md
tested and validated teh guide to port to 3.0
Preview link:
=> fix: Access Control List plugin

app/_includes/md/kic/class.md, app/_includes/md/kic/prerequisites.md, app/_src/kubernetes-ingress-controller/plugins/rate-limiting.md
Ported the rate limiting plugin content to 3.0 folder
Preview link:
=> fix: Rate limiting plugin

api-specs/overlays/docs/docs.md, api-specs/overlays/ee/api-description.yaml, api-specs/overlays/ee/tag-descriptions.yaml, api-specs/overlays/oss/api-description.yaml, api-specs/overlays/oss/tag-descriptions.yaml
I added support for overlays for the tag descriptions since those will not be generated through any form of automation. 
https://konghq.atlassian.net/jira/software/c/projects/DOCU/boards/58?selectedIssue=DOCU-3499
=> Add Overlays for tag description [skip-ci]

app/gateway-operator/changelog.md
Update docs with gateway-operator 1.0.2
=> kgo: update docs with 1.0.2

app/_src/kubernetes-ingress-controller/guides/services/multiple-backends.md
tested, validated, and ported the contents to 3.0
Preview link:
=> fix: Multiple Backends

app/_src/kubernetes-ingress-controller/plugins/custom.md
tested validated and ported the content to 3,0
Preview link:
=> fix: Custom plugin

app/_includes/md/kic/deploy-kic-v3.md, app/_src/kubernetes-ingress-controller/install/cloud/eks.md
rewrite of the Amazon EKS install guide.
Preview link:
=> fix: Amazon EKS

changelog.md
This is a scheduled pull request to update the changelog.
=> Automated Changelog update [skip ci]

app/_src/kubernetes-ingress-controller/concepts/custom-resources.md
port contnent to 3.0
Preview link:
=> fix: Custom Resources 

app/_src/kubernetes-ingress-controller/concepts/ingress.md
port the content to 3.0
Preview link:
=> fix: Ingress

app/_src/kubernetes-ingress-controller/concepts/gateway-api.md
Port content to 3.0
Preview link:
=> fix: Gateway API

app/_src/kubernetes-ingress-controller/install/cloud/aks.md
format and rewrite of the Azure guide
Preview link:
=> fix: Azure guide

app/_src/kubernetes-ingress-controller/concepts/architecture.md
Port the content to 3.0
Preview link:
=> fix: Architecture

app/_src/gateway/licenses/index.md
Update Kong 3.5 docs as it was updated in: https://github.com/Kong/kong-ee/pull/6362
DOCU-3449
Preview link:
=> feat(licensing): update description of behavior after license expiration

app/_hub/nonamesecurity/nonamesecurity-kongprevention/overview/_index.md
Minor update to Noname plugin description.
Preview link:
=> noname description update

api-specs/Gateway-EE/portal-api.yaml, api-specs/Gateway-OSS/gateway-status.yaml, api-specs/Konnect/v2/yaml/portal-api.yaml, api-specs/Konnect/v2/yaml/portal-rbac.yaml, app/_api/dev-portal/_index.md, app/_api/gateway/admin-ee/_index.md, app/_api/gateway/admin-oss/_index.md, app/_api/gateway/status/_index.md, app/_api/konnect/api-products/_index.md, app/_api/konnect/api-requests/_index.md, app/_api/konnect/audit-logs/_index.md, app/_api/konnect/control-plane-configuration/_index.md, app/_api/konnect/control-planes/_index.md, app/_api/konnect/identity-management/_index.md, app/_api/konnect/mesh-manager/_index.md, app/_api/konnect/portal-rbac/_index.md, app/_api/konnect/portal/_index.md, app/_assets/stylesheets/pages/docs.less, app/_assets/stylesheets/pages/landing-oas.less, app/_layouts/oas/index.html
Adding Run in Insomnia buttons to API catalog in the docs.
Preview link: https://deploy-preview-6329--kongdocs.netlify.app/api/
Button alignment feels like the least bad one of the ones I've tried.
=> Feat: Insomnia buttons for API catalog landing page

app/_src/kubernetes-ingress-controller/guides/security/client-ip.md
Porting content to 3.0 
Preview link:
=> fix: Preserving Client IP Address

app/_src/kubernetes-ingress-controller/reference/annotations.md
Port content to 3.0
Preview link:
=> fix: KIC Annotations

app/_src/gateway/kong-manager/auth/oidc/configure.md
Waiting for this PR merged.
https://github.com/Kong/kong-ee/pull/6848
Preview link:
=> update the admin_gui_auth_conf of the OIDC

app/_data/docs_nav_kic_3.0.x.yml, app/_src/kubernetes-ingress-controller/guides/services/fallback.md
tested, and validated the guide end to end works as expected.
Preview link:
=> fix: Fallback Service for requests

app/_assets/javascripts/copy-code-snippet-support.js, app/_includes/md/kic/prerequisites.md, app/_src/kubernetes-ingress-controller/get-started/index.md, app/_src/kubernetes-ingress-controller/get-started/key-authentication.md, app/_src/kubernetes-ingress-controller/get-started/proxy-caching.md, app/_src/kubernetes-ingress-controller/get-started/rate-limiting.md, app/_src/kubernetes-ingress-controller/get-started/services-and-routes.md
Write KIC Getting Started guide. The structure mirrors the Gateway guide.
Preview link: ...
=> KIC 3.0: Getting Started guides

app/_includes/md/kic/annotate-plugin.md, app/_includes/md/kic/prerequisites.md, app/_src/kubernetes-ingress-controller/plugins/mtls.md
port content to 3.0
Preview link:
=> fix: mTLS Plugin

app/_includes/md/kic/http-service-httpbin.md, app/_includes/md/kic/prerequisites.md, app/_src/kubernetes-ingress-controller/guides/high-availability/health-checks.md, app/assets/kubernetes-ingress-controller/examples/httpbin-service.yaml, app/assets/kubernetes-ingress-controller/examples/tcp-echo-service.yaml
tested and validated the guides for configuring passive and active health checks.
Preview link:
=> fix: Health checks

app/_data/docs_nav_kic_3.0.x.yml, app/_src/kic-v2/deployment/admission-webhook.md, app/_src/kubernetes-ingress-controller/concepts/admission-controller.md, app/_src/kubernetes-ingress-controller/concepts/admission-webhook.md, app/_src/kubernetes-ingress-controller/concepts/annotations.md
Add remaining "How KIC works" docs:
* Annotations
* Admission Webhook
Preview link:
=> KIC 3.0: Annotations + Admission Webhook

app/_src/kic-v2/faq.md
Reverts Kong/docs.konghq.com#6401 - merged by mistake (to develop branch) without a review so let's revert it.
=> Revert "Document in FAQ running KIC as DaemonSet"

app/_src/kic-v2/guides/using-rewrites.md, app/_src/kic-v2/references/annotations.md, app/_src/kic-v2/references/feature-gates.md
tested and validated the guide.
Preview link: 
[rewritehostpathworks.txt](https://github.com/Kong/docs.konghq.com/files/13207384/rewritehostpathworks.txt)
=> fix: Rewriting hosts and paths

app/_assets/stylesheets/pages/docs.less, app/_includes/plugins/schema.html, app/_plugins/drops/plugins/schema.rb, spec/app/_plugins/drops/plugins/schema_field_spec.rb, spec/app/_plugins/drops/plugins/schema_spec.rb
List the `shorthand_fields` in a new section below the schema
Preview link:
=> [Plugin Hub] Deprecated fields

app/_assets/javascripts/copy-code-snippet-support.js, app/_src/kic-v2/guides/prometheus-grafana.md, app/assets/kubernetes-ingress-controller/examples/multiple-services.yaml
format, test and validate
Preview link:
=> fix: Integrate the Kong Ingress Controller with Prometheus/Grafana

app/_includes/md/mesh/install-universal-run.md
=> Fix install link

app/_data/docs_nav_kic_3.0.x.yml, app/_src/kubernetes-ingress-controller/production/observability/prometheus-grafana.md, app/_src/kubernetes-ingress-controller/production/observability/prometheus.md
Ported content to 3.0
Preview link: https://deploy-preview-6396--kongdocs.netlify.app/kubernetes-ingress-controller/latest/production/observability/prometheus/
=> fix: Prometheus

api-specs/Konnect/v2/yaml/api-products.yaml, api-specs/Konnect/v2/yaml/portal-management.yaml
Generated OAS files from platform-api
=> Automated OAS Update

app/_src/kubernetes-ingress-controller/install/cloud/gke.md
Add GKE guide for KIC 3.0
Preview link:
=> KIC 3.0: Install on GKE

app/_includes/md/kic/http-test-routing-resource.md, app/_includes/md/kic/http-test-routing.md, app/_src/kubernetes-ingress-controller/guides/requests/rewrite-annotation.md, app/_src/kubernetes-ingress-controller/guides/services/http.md
Add documentation about the `konghq.com/rewrite` annotation
Preview link: https://deploy-preview-6422--kongdocs.netlify.app/kubernetes-ingress-controller/latest/guides/requests/rewrite-annotation/
=> KIC 3.0: Rewrite annotation

app/_src/kubernetes-ingress-controller/reference/faq/router.md
Add FAQ page about router default changes
Preview link: https://deploy-preview-6423--kongdocs.netlify.app/kubernetes-ingress-controller/latest/reference/faq/router/
=> KIC 3.0: Router FAQ

app/_data/docs_nav_kic_3.0.x.yml, app/_src/kubernetes-ingress-controller/guides/security/kong-vault.md, app/_src/kubernetes-ingress-controller/guides/security/workspaces.md
Add Kong Vaults page. Remove CertManager + CP/DP mTLS pages until we have more content
Preview link:
=> KIC 3.0: Security

app/konnect/mesh-manager/migrate-zone.md
In the recently introduced [guide](https://github.com/Kong/docs.konghq.com/pull/6320), I forgot to include Kong Mesh specific policies in the script.
Preview link:
=> Add Kong Mesh specific policies to the migration script

app/konnect/gateway-manager/configuration/index.md
Update resource limit language from entity resource limit to Default entity resource limit.
=> Update resource limit language

app/_hub/kong-inc/application-registration/how-to/_index.md, app/_hub/kong-inc/application-registration/overview/_index.md, app/_src/gateway/kong-enterprise/dev-portal/applications/auth-provider-strategy.md, app/_src/gateway/kong-enterprise/dev-portal/applications/enable-application-registration.md, app/gateway/2.6.x/developer-portal/administration/application-registration/auth-provider-strategy.md, app/gateway/2.6.x/developer-portal/administration/application-registration/enable-application-registration.md, app/gateway/2.7.x/developer-portal/administration/application-registration/auth-provider-strategy.md, app/gateway/2.7.x/developer-portal/administration/application-registration/enable-application-registration.md, app/gateway/2.8.x/developer-portal/administration/application-registration/auth-provider-strategy.md, app/gateway/2.8.x/developer-portal/administration/application-registration/enable-application-registration.md
We've had the same wrong info in the app registration docs since 2.1.x: that when using Kong Gateway as the system of record, app reg can't be used in hybrid mode. This issue recently resurfaced as a customer ran into it. 
Changes made:
* Removing the inaccurate info and making it clear that the limitation is for the OAuth2 plugin only. 
* Added a column to the table in the App Reg plugin overview with info about supported topologies, to make it very clear up front.
* Cleaning up the app reg auth provider strategy docs to remove all the duplicate info and cut the content down to what the user needs to know. We have the same info repeated three times in one topic, making it very difficult to actually follow along with any instructions. 
* Removed outdated images from the edited topics. …
=> Fix: App registration doc lists hybrid mode as not supported

app/_data/docs_nav_gateway_3.4.x.yml, app/_data/docs_nav_gateway_3.5.x.yml, app/_src/gateway/licenses/report-v2.md, app/_src/gateway/licenses/report.md
Update Kong 3.5 docs as it was updated in: https://github.com/Kong/kong-ee/pull/6753
Preview link:
=> feat(license_report): update description of licensing report

app/_api/konnect/portal-management/_index.md, app/_data/docs_nav_konnect.yml, app/_data/konnect_oas_data.json, app/konnect/updates.md
Customers are able to integrate portal management operations with their automation systems (such as CI/CD pipelines) by utilizing a refactored and newly-published AIP-compliant Portal Management API.
Preview link: 
*  new spec URL /api/portal-managment/latest
* https://deploy-preview-6388--kongdocs.netlify.app/konnect/api/portal-management/latest/ (NB: spec will not render but demonstrates new URL)
* https://deploy-preview-6388--kongdocs.netlify.app/api/ > new card for spec available + Insomnia button 
* https://deploy-preview-6388--kongdocs.netlify.app/konnect/api/ > new Portal Management API in nav w/ link to spec
=> Feat: Portal Management API

app/_src/gateway/reference/configuration.md
Generate and version tag the Gateway config reference for 3.5.
Preview link: https://deploy-preview-6445--kongdocs.netlify.app/gateway/latest/reference/configuration/
=> chore: Update Gateway config reference for 3.5

app/_src/kubernetes-ingress-controller/reference/faq/nginx.conf.md
Ported the content to 3.0 based on the discussion in [slack](https://kongstrong.slack.com/archives/CA42V003B/p1682529527790259).
Fixes: https://github.com/Kong/kubernetes-ingress-controller/issues/4950
Preview link:
=> fix: FAQ nginx conf

app/_src/kubernetes-ingress-controller/upgrade/gateway.md
Port the content from the response in https://github.com/Kong/kubernetes-ingress-controller/issues/5026 to the 3.0
Preview link:
=> Upgrade KIC Gateway

app/_data/docs_nav_gateway_3.5.x.yml
Copying over any changes that have happened to the 3.4 nav on `main` since the 3.5 branch & nav file were created.
Preview link:
=> chore: Copy over nav changes from 3.4 to 3.5

api-specs/Gateway-EE/3.5/kong-ee-3.5.yaml, api-specs/Gateway-OSS/3.5/kong-oss-3.5.yaml, app/_src/gateway/plugin-development/pdk/kong.client.md, app/_src/gateway/plugin-development/pdk/kong.log.md, app/_src/gateway/plugin-development/pdk/kong.request.md, app/_src/gateway/reference/cli.md
Contains CLI, PDK, and OSS+EE API spec changes.
=> Gateway 3.5 Autodocs

app/_hub/kong-inc/rate-limiting-advanced/overview/_index.md, app/_hub/kong-inc/rate-limiting/overview/_index.md
RateLimit header fields for HTTP -> https://datatracker.ietf.org/doc/draft-ietf-httpapi-ratelimit-headers/
Preview link:
=> Updating link to IETF Draft

app/_src/gateway/kong-enterprise/index.md
notice while building out synonym list that these are only instance of expanded product terms for AWS and GCP that don't also include acronym, so adding. 
Preview link:
=> fix: add acronyms

package-lock.json, package.json
Bump spec-renderer to v0.12.2, it resolves a text formatting issue with code blocks in the Authorization modal
Preview link: `/konnect/api/api-products/latest/`
=> Bump spec-renderer

app/_data/tables/version_errors_konnect.yml
JIRA: https://konghq.atlassian.net/browse/KOKO-1305
* Adds version compatibility issues for gateway v3.5.
* Rewords "data plane" -> "data plane node".
* Corrects instances of `>` being interpreted as block quote.
Preview link:
=> chore: add compatibility updates for Gateway 3.5 release

app/_data/docs_nav_gateway_3.5.x.yml, app/_includes/md/gateway/setup.md, app/_redirects, app/_src/gateway/install/linux/ubuntu.md, app/_src/gateway/kong-plugins/authentication/oidc/azure-ad.md, app/_src/gateway/kong-plugins/authentication/oidc/curity.md, app/_src/gateway/kong-plugins/authentication/oidc/okta.md
Fixes broken links reported in this list by adding conditional rendering and redirects as a failsafe. 
```
[
{
"page": "http://localhost:8888/gateway/latest/install/linux/ubuntu/",
"text": "Enable Dev Portal",
"target": "http://localhost:8888/gateway/3.5.x/kong-enterprise/dev-portal/enable/",
"reason": "HTTP_404"
},
{
"page": "http://localhost:8888/gateway/latest/install/linux/debian/",
"text": "Dev Portal",
"target": "http://localhost:8888/gateway/3.5.x/kong-enterprise/dev-portal/",
"reason": "HTTP_404"
},
{
"page": "http://localhost:8888/gateway/latest/install/linux/amazon-linux/",
"text": "Dev Portal",
"target": "http://localhost:8888/gateway/3.5.x/kong-enterprise/dev-portal/",
"reason": "HTTP_404"
},
{
"page": "http://localhost:8888/gateway/latest/install/linux/rhel/",
"text": "Dev …
```
=> chore: Dev Portal broken links

app/_hub/kong-inc/acme/_changelog.md, app/_hub/kong-inc/aws-lambda/_changelog.md, app/_hub/kong-inc/canary/_changelog.md, app/_hub/kong-inc/cors/_changelog.md, app/_hub/kong-inc/grpc-gateway/_changelog.md, app/_hub/kong-inc/kafka-log/_changelog.md, app/_hub/kong-inc/mocking/_changelog.md, app/_hub/kong-inc/mtls-auth/_changelog.md, app/_hub/kong-inc/oas-validation/_changelog.md, app/_hub/kong-inc/oauth2-introspection/_changelog.md, app/_hub/kong-inc/openid-connect/_changelog.md, app/_hub/kong-inc/opentelemetry/_changelog.md, app/_hub/kong-inc/prometheus/_changelog.md, app/_hub/kong-inc/rate-limiting-advanced/_changelog.md, app/_hub/kong-inc/request-validator/_changelog.md, app/_hub/kong-inc/response-ratelimiting/_changelog.md, app/_hub/kong-inc/response-transformer/_changelog.md, app/_hub/kong-inc/saml/_changelog.md, app/_hub/kong-inc/session/_changelog.md, app/_hub/kong-inc/tcp-log/_changelog.md, app/_hub/kong-inc/zipkin/_changelog.md, app/_src/gateway/breaking-changes/35x.md, app/gateway/changelog.md
https://github.com/Kong/kong-ee/blob/next/3.5.x.x/changelog/3.5.0.0/3.5.0.0.md
https://github.com/Kong/kong-ee/blob/next/3.5.x.x/changelog/3.5.0/3.5.0.md
=> Release 3.5 Changelog

app/moved_urls.yml
Fixing broken links that are published in a blog post. I'll fix the remaining links in a followup PR
=> Fix broken links from Mattia's blog post

app/_src/gateway/production/access-control/register-admin-api.md, app/_src/gateway/production/access-control/start-securely.md
The official doc on the first super admin creation is misleading.
Preview link:
=> docs(rbac): update description on 1st super admin creation

app/_src/gateway/support/sbom.md
adding KB link to SBOM for 3.5
Preview link:
=> chore: Update sbom.md

app/_data/docs_nav_kic_3.0.x.yml, app/_src/kubernetes-ingress-controller/concepts/ingress.md, app/_src/kubernetes-ingress-controller/gateway-api.md, app/_src/kubernetes-ingress-controller/index.md, app/_src/kubernetes-ingress-controller/production/deployment-topologies/db-backed.md, app/_src/kubernetes-ingress-controller/production/deployment-topologies/index.md
Apply suggestions from Angle's review in https://github.com/Kong/docs.konghq.com/pull/6454
Preview link:
=> chore: Kic 3.0 nitpicks 

app/_data/docs_nav_gateway_3.4.x.yml, app/gateway/changelog.md
Update changelog for the Gateway 3.4.2.0 release
https://github.com/Kong/kong-ee/blob/next/3.4.x.x/changelog/3.4.2.0/3.4.2.0.md
https://konghq.atlassian.net/browse/DOCU-3563
=> Release Gateway 3.4.2.0

spec/templates/plugin_with_versions_spec.rb
Add spec for https://github.com/Kong/docs.konghq.com/pull/6506/files 
Preview link:
=> Add spec for 'Using plugins in Konnect' banner

app/_src/kubernetes-ingress-controller/guides/security/kong-vault.md
Fix code styling in KIC Vaults page
Preview link:
=> Fix Kong Vault in KIC styling

app/_data/kong_versions.yml, app/gateway/changelog.md
Build changelog for 3.5.0.1 based on source from https://github.com/Kong/kong-ee/blob/next/3.5.x.x/changelog/3.5.0.1/3.5.0.1.md
Preview link:
=> (chore) 3.5.0.1 changelog

app/konnect/gateway-manager/configuration/vaults/how-to.md, app/konnect/gateway-manager/configuration/vaults/index.md
Added Azure Key Vault as a supported secret manager for Konnect docs
https://konghq.aha.io/features/KP-391
This was hidden behind a feature flag from back in March. It is now ready to be turned on and released.
Preview link:
=> Azure Key Vault docs for Konnect

app/konnect/compatibility.md, app/konnect/updates.md
Adding statements of Konnect support for 3.5 to changelog + compatibility table, including Azure Key Vault support. 
Preview link:
=> (chore) Konnect + 3.5 support

app/_assets/stylesheets/footer.less, app/_includes/footer.html
Update the footer so that it matches the .com site
Preview link:
=> Update Footer to match .com site

app/_data/docs_nav_gateway_3.0.x.yml, app/_data/docs_nav_gateway_3.1.x.yml, app/_data/docs_nav_gateway_3.2.x.yml, app/_data/docs_nav_gateway_3.3.x.yml, app/_data/docs_nav_gateway_3.4.x.yml, app/_data/docs_nav_gateway_3.5.x.yml, app/_includes/md/gateway/install-linux-os.md, app/_includes/md/gateway/install-traditional-mode.md, app/_includes/md/gateway/root-user-note.md, app/_redirects, app/_src/gateway/install/linux/amazon-linux.md, app/_src/gateway/install/linux/debian.md, app/_src/gateway/install/linux/rhel.md, app/_src/gateway/install/linux/ubuntu.md, app/_src/gateway/install/post-install/set-up-data-store.md, app/_src/gateway/licenses/deploy.md
Split the DB install instructions from linux OS docs and add the info about config setup to all those pages.
This is a follow-up to work started by Michael Heap on the Ubuntu installation doc. This PR applies the same approach to the RHEL, Amazon Linux, and Debian install docs, and links off to the DB configuration as a post-installation task.
As part of this work, I took the old "post-installation" section from linux OS docs (eg https://docs.konghq.com/gateway/latest/install/linux/rhel/#set-up-configs) and split it up to only include relevant info + link to post-install info in other, already existing locations (eg enterprise license deployment and enabling Kong Manager).
The licensing troubleshooting section was also taken from the old setup include.
This PR also makes the pages …
=> Update: Linux installation pages cleanup & consistency

app/_src/gateway/reference/expressions-language/index.md, app/_src/gateway/reference/expressions-language/performance.md
=> style(expressions): fix typo in `performance.md`

package-lock.json, tools/konnect-oas-data-generator/package-lock.json
This reverts commit 6000d625fd73017bbd24afbd9389c8abacc05e7d.
This somehow introduced an error,  API specs don't render.
Preview link:
=> Revert "fix(deps): update non-major dependencies"

app/_src/gateway/install/kubernetes/openshift.md
https://github.com/Kong/docs.konghq.com/issues/5688
Preview link: 
`review:copyedit`
=> remove Kubernetes requirements and put the OpenShift requirements

app/konnect/gateway-manager/plugins/troubleshoot-custom-plugins.md
We accidentally added this blank page in https://github.com/Kong/docs.konghq.com/pull/6164
Preview link:
=> (chore) Delete blank custom plugins troubleshooting page

app/kong-kubernetes-changelog.md
We accidentally added this blank page on https://github.com/Kong/docs.konghq.com/pull/358
Preview link:
=> (chore) Delete app/kong-kubernetes-changelog.md

app/_src/gateway/kong-enterprise/index.md
Remove mention of vitals and dev portal from the intro paragraph of this doc.
=> Fix: Remove mention of vitals and dev portal from 3.5 intro paragraph

app/_hub/kong-inc/oauth2/overview/_index.md
Add a note about not recommended for Production environment.
Fixes: https://konghq.atlassian.net/browse/DOCU-2310
Preview link:
=> update: OAuth 2.0 Authentication

app/_plugins/blocks/mermaid.rb, app/_src/gateway/index.md
hopefully addressing the issue related to method length
=> fix: Mermaid rubocop fail 

app/_src/gateway/index.md
=> Remove stray diagram

app/_hub/kong-inc/tls-handshake-modifier/_metadata.yml
Reported by @hbagdi; this plugin is compatible with Konnect.
Preview link: /hub/kong-inc/tls-handshake-modifier/
=> tls-handshake-modifier is compatible with Konnect

app/konnect/api-products/service-documentation.md
https://github.com/Kong/docs.konghq.com/issues/6604
=> fix: Update title of add service documentation doc. 

app/_hub/kong-inc/jwt/overview/_index.md
Fixes: https://konghq.atlassian.net/browse/DOCU-2347
updated the incorrect examples section.
No validation done.
Preview link:
=> Update:JWT plugin overview section

app/konnect/compatibility.md
=> fix: Clear up confusion with plugin tiering

.github/workflows/sync-konnect-oas-data.yml
The action fails to create a PR because of missing permissions.
Add permissions to action and pass in the `PAT` token
Preview link:
=> Add permissions and token to sync-konnect-oas-data

app/_src/gateway/upgrade/backup-and-restore.md
Fix an error from https://github.com/Kong/docs.konghq.com/pull/6534.
Preview link:
=> docs(gateway-upgrade): fix an argument error

app/contributing/community-expectations.md
=> Update: Meta description for community-expectations.md

app/konnect/updates.md
Preview link: https://deploy-preview-6649--kongdocs.netlify.app/konnect/updates/
=> (fix) correct spacing on developer managed scopes changelog

app/_data/docs_nav_contributing.yml, app/contributing/diagrams.md
Instructions on using mermaid.js to make diagrams in the docs.
Preview link:
=> Feat: Add some basic docs for making diagrams with mermaid

.github/workflows/linting.yml
Update to use the `gh-pr-annotations` reporter from a custom build of `reviewdog`
=> Update reviewdog reporter

app/_api/gateway/admin-ee/_index.md, app/_api/gateway/admin-oss/_index.md
Update Insomnia buttons to point to v3.5.x (latest)
[Preview link](https://deploy-preview-6661--kongdocs.netlify.app/api/)
=> Update Insomnia buttons to point to v3.5.x

app/gateway/changelog.md
Changelog for CE/EE release of 3.4.3.1
Source file  https://github.com/Kong/kong-ee/pull/7567/files
Preview link: https://deploy-preview-6651--kongdocs.netlify.app/gateway/changelog/#3431
=> (feat) 3.4.3.1 changelog

.github/styles/kong/dictionary.txt, app/_data/docs_nav_mesh_2.5.x.yml, app/_data/docs_nav_mesh_dev.yml, app/_src/mesh/features/openshift-quickstart.md
Danny wrote up a great quickstart guide on GitHub about using OpenShift and Kong Mesh, so this PR converts it to docs.
DOCU-3309
Preview link:
=> feat: OpenShift Quickstart guide with Kong Mesh

app/_hub/kong-inc/app-dynamics/overview/_index.md
Refine the AppDynamics plugin documentation with updated installation instructions, distinguishing between recommended practices for Kong version 3.0.0.0 and later versus alternative approaches for older versions or unique environments.
[FTI-5652](https://konghq.atlassian.net/browse/FTI-5652)
Preview link: 
[FTI-5652]: https://konghq.atlassian.net/browse/FTI-5652?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: update AppDynamics installation guide

app/_data/kong_versions.yml, app/_src/gateway/breaking-changes/35x.md, app/_src/gateway/reference/configuration.md, app/gateway/changelog.md
source changelog: https://github.com/Kong/kong-ee/pull/7647/files
Preview link: 
https://deploy-preview-6684--kongdocs.netlify.app/gateway/changelog/#3502
https://deploy-preview-6684--kongdocs.netlify.app/gateway/latest/reference/configuration/#dns_no_sync
https://deploy-preview-6684--kongdocs.netlify.app/gateway/latest/breaking-changes/
=> (chore) 3.5.0.2 Changelog

app/_data/kong_versions.yml, app/gateway/changelog.md
Just starting the PR for now, will add source changelog when it's available.
Preview link: https://deploy-preview-6683--kongdocs.netlify.app/gateway/changelog/#3432
=> (chore) 3.4.3.2 Changelog

app/_src/kubernetes-ingress-controller/concepts/gateway-api.md
=> kic: gateway API concepts update

app/_plugins/generators/seo/index_entry_builder.rb, spec/app/_plugins/generators/seo/index_entry_builder_spec.rb
Remove assets from sitemap.
Preview link:
=> Remove assets from sitemap

app/_data/tables/support/gateway/packages.yml, app/_data/tables/support/gateway/versions/36.yml
Add support of Debian 12 for Kong Gateway 3.6.
KAG-3015
Related PRs:
Kong/kong#12218
Kong/kong-ee#7659
Note: 36.yml wasn't there so I copied 35.yml to 36.yml in a separate commit. If it's added by another PR I need to delete that commit and rebase from release/gateway-3.6 branch. Anyway, the essential change of this PR is:
```
diff --git a/app/_data/tables/support/gateway/packages.yml b/app/_data/tables/support/gateway/packages.yml
index 101089c58..a28d5b88a 100644
--- a/app/_data/tables/support/gateway/packages.yml
+++ b/app/_data/tables/support/gateway/packages.yml
@@ -72,6 +72,13 @@ _packages:
arm: false
fips: false
graviton: false
+  debian12: &debian12
+    os: Debian
+    version: 12
+    package: true
+    arm: false
+    fips: false
+    graviton: false
debian-stable: …
```
=> feat: Debian 12 support

app/_src/gateway/production/debug-request.md
Currently, the example output of request-debug in docs is too simple, so I replace it with a more better one.
Preview link: 
_[KAG-3434]_
[KAG-3434]: https://konghq.atlassian.net/browse/KAG-3434?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: use more informative example for request-debug docs

app/_src/kubernetes-ingress-controller/guides/services/https-redirect.md
=> fix: typo in ingress redirect docs

.github/styles/kong/dictionary.txt, app/_src/gateway/how-kong-works/load-balancing.md, app/_src/gateway/production/blue-green.md, app/_src/gateway/production/canary.md
Rewrite of the outdated page on loadbalancing
Preview link:
* https://deploy-preview-6689--kongdocs.netlify.app/gateway/latest/how-kong-works/load-balancing/#balancing-algorithms 
* https://deploy-preview-6689--kongdocs.netlify.app/gateway/latest/production/blue-green/
* https://deploy-preview-6689--kongdocs.netlify.app/gateway/latest/production/canary/
=> rewrite the loadbalancing document

app/_data/tables/support/gateway/packages.yml, app/_data/tables/support/gateway/versions/35.yml
Reverts Kong/docs.konghq.com#6587
=> Revert "(Feat) add support for Azure Linux to 3.5 matrix"

app/konnect/updates.md
Preview link: https://deploy-preview-6650--kongdocs.netlify.app/konnect/updates/
=> (feat) Konnect in GCP Changelog

app/contributing/style-guide.md
The Kong docs style guide was missing info on writing recommendations. I ran into some phrasing during a review and wanted to reference our guide, and realized that we never documented it (even though [we did discuss it and decided on a style](https://konghq.atlassian.net/wiki/spaces/KD/pages/2797568009/Standards+and+guidelines#:~:text=Standardize%20recommendations)).
Also took this opportunity to split up the "best practices" table into separate sections and add more info. 
* One of the main benefits of having a style guide is being able to link to specific guidelines, and that table made it difficult to do that + didn't have room to add more explanation. 
* As well, when you scrolled past a certain point, you couldn't tell which column was "Do" and which was "Do not" anymore.
* Removed …
=> Update: Rework style guide and add guidelines for writing recommendations

app/_src/gateway/upgrade/index.md, app/_src/gateway/upgrade/lts-upgrade.md
Customer noted that the instructions to review OS compatibility are buried too deeply within the upgrade guide, and they missed them on their first read through the guide.
Adding the links/instructions to review compatibility as the first step, as no upgrade can be performed if your system doesn't support it.
Preview link:
=> Update: Prerequisite to review version compatibility before Gateway upgrade

app/_src/gateway/kong-enterprise/index.md
Fix the broken link that came up in the last [scheduled broken link action](https://github.com/Kong/docs.konghq.com/actions/runs/7515703424/job/20459932899) run.
[Preview link](https://deploy-preview-6757--kongdocs.netlify.app/gateway/latest/kong-enterprise/)
=> Fix linked to `Verify signatures for Signed Images`

app/_data/kong_versions.yml, app/gateway/changelog.md
EE changelog here: https://github.com/Kong/kong-ee/pull/7816
=> Release: Gateway version 3.4.3.3

app/_data/kong_versions.yml, app/gateway/changelog.md
Changelog and version bump for upcoming 2.8.4.6 patch.
Preview link:
=> Release: Changelog and version bump for Gateway 2.8.4.6

app/_src/gateway/kong-enterprise/cp-outage-handling.md
https://github.com/Kong/kong-ee/pull/7627
KAG-2949
Preview link:
=> Update for DP resilience new changes

api-specs/Gateway-EE/3.5/kong-ee-3.5.yaml
Update Kong gateway EE spec to include endpoints that were present in the [markdown documentation](https://docs.konghq.com/gateway/latest/admin-api/)
=> Feat: Update Kong Gateway EE specs [skip ci]

netlify.toml
=> Add trailing slash to urls analyzed by lighthouse

app/_data/docs_nav_mesh_dev.yml
e2f955bb34bbb0ea6d34c798055fd240c06560bd fix(policies): update /policies page to /features (kumahq/kuma-website#1595)
df6130cd578a74487a7d5b15aab4d3c77d02d207 feat(dns): add instructions for customizing DNS configuration template (kumahq/kuma-website#1576)
42ee81041b9ef710d52400ba0f00ad40caeedd69 docs(policy): improve targetRef table (kumahq/kuma-website#1579)
e76bc74e24f3f3a7ce78fe18bcae8d062da553d1 chore(deps): update docs from repo source (kumahq/kuma-website#1586)
dc13a6856c94acf46d542f49b048ed15ef289422 docs(website): change button order (kumahq/kuma-website#1596)
37c87e64c8731cd3130e850bb016df2435ff5747 chore(policies): move all non targetRef policies in a subsection (kumahq/kuma-website#1592)
Triggered by …
=> chore(deps): bump kumahq/kuma-website from 79481f3c to e2f955bb

app/_src/gateway/get-started/index.md, app/_src/gateway/production/monitoring/prometheus.md, app/_src/gateway/production/monitoring/statsd.md
Where the quickstart is used, the output changed slightly to indicate the gateway was ready.
Minor copy update
=> Chore: fixes for a minor change in the Quickstart script output

app/konnect/updates.md
Changelogs for December and January GW Manager updates
Preview link:
=> feat: update Konnect changelog for Gateway manager updates

app/_hub/kong-inc/openid-connect/overview/_index.md
Fixed the broken link for the refresh grant type, previously pointing at
/hub/kong-inc/openid-connect/how-to/authentication/refresh-token-grant 
but should be
/hub/kong-inc/openid-connect/how-to/authentication/refresh-token/
Preview link:
=> Update: Fix broken link

app/_src/gateway/kong-enterprise/secrets-management/backends/azure-key-vaults.md
Updating the Azure Vault variable names as with the existing naming the Vault configuration doesn't work.
=> Fix: update azure vault variable names

app/_data/kong_versions.yml, app/gateway/changelog.md
Changelog and version bump for Gateway 3.5.0.3.
https://konghq.atlassian.net/browse/DOCU-3654
Preview link:
=> Release: Gateway 3.5.0.3

app/_data/docs_nav_mesh_2.6.x.yml
e3c0564ebafd72db2579eaf54558d31b675ead22 docs(policies): added references for target ref policies (kumahq/kuma-website#1608)
1e1e2446df1c612c505499ea117fd7f245b0f584 fix(demo): changed name of the policy (kumahq/kuma-website#1610)
ce6d3d51ba7de9292295c558f27614f01dea5a57 docs(meshtrafficpermission): added information about mesh traffic per… (kumahq/kuma-website#1607)
a5ed7c9621bf7aed33b07115b0e4a8da5862ee17 docs(targetRef): added information about proxyTypes (kumahq/kuma-website#1605)
d54bb7ac261c7398282bd5689ca942dfea66edcb docs(guides) federation (kumahq/kuma-website#1604)
f9f0c3d72d20226325fced6d6dc247086c3a3622 feat(policy): add docs for open telemetry in meshmetric policy (kumahq/kuma-website#1603)
3bcd9250ac31b67804620860ddd3804e92f16d46 docs(policies): applying …
=> chore(deps): bump kumahq/kuma-website from 11f2e1c9 to e3c0564e

app/_data/docs_nav_mesh_2.6.x.yml
fe0bc027bdace8945156bdaceebc34622d1b170b chore(sidebar): reorganize everything under `use kuma` (kumahq/kuma-website#1616)
79c306e2129eb8380475549c580085f1770329dc Standalone to single zone (kumahq/kuma-website#1611)
e50c81116cfdfecb53993bdd3cf6c3dd59569e38 docs(MeshTimeout): small style fixes + render fix (kumahq/kuma-website#1612)
ca04a14bd9029dab1e0e634c2a6f5aa5f84b37f0 docs(inspect-api): update page to show new policies (kumahq/kuma-website#1614)
2a1118ce7d277c7a3a9264a43da59ef36be2b45f docs(dataplane-health): update with new policies (kumahq/kuma-website#1613)
ddc9ed84295ae57f6209b6ce2539144db0acf1ed docs(meshtimeout): added new configuration option, and proxyTypes example (kumahq/kuma-website#1606)
Triggered by …
=> chore(deps): bump kumahq/kuma-website from e3c0564e to fe0bc027

.github/styles/kong/dictionary.txt, app/_data/docs_nav_gateway_3.6.x.yml, app/_src/gateway/kong-manager/auth/ldap/service-directory-mapping.md, app/_src/gateway/kong-manager/auth/oidc/configure.md, app/_src/gateway/kong-manager/auth/oidc/mapping.md, app/_src/gateway/kong-manager/auth/oidc/migrate.md
This pull request adds some warnings, migration guides, and instructions as per updates on the OIDC & LDAP authentication feature in Kong Gateway 3.6.
Preview link: 
KAG-3159
=> docs(kong-manager): OIDC and LDAP updates

netlify.toml, package.json
Install `development` group when the `ENV` is `development`
https://github.com/Kong/docs.konghq.com/assets/715229/fa759a27-d749-4843-9cd4-21d21a0d3dbe
For example, if this change is for an upcoming 3.6 release, surround your change in `{% if_version gte:3.6.x %} <content> {% endif_version %}` tags (or `if_plugin_version` tags for plugins).
=> Bundle `development` group in development

app/_src/gateway/support/browser.md, app/_src/gateway/support/index.md, app/_src/gateway/support/third-party.md
I updated the version support policy, third-party dependencies page, and the browser support page with the 3.6 gateway version in preparation for the release. 
DOCU-3632
Preview link:
=> chore: 3.6: Support matrix updates

app/konnect/updates.md
https://konghq.atlassian.net/browse/DOCU-3643
=> Feat: Improved Proxy URL support in Konnect 

app/_src/gateway/index.md
"we recommends" to "we recommend" 
Preview link: 
=> Fix: grammatical error

app/_includes/md/kic/support.md
Update supported k8s versions for Kong
Preview link: 
- [/kubernetes-ingress-controller/latest/support-policy/](https://deploy-preview-6908--kongdocs.netlify.app/kubernetes-ingress-controller/latest/support-policy/)
- [/gateway/latest/install/kubernetes/](https://deploy-preview-6908--kongdocs.netlify.app/gateway/latest/install/kubernetes/)
=> Update Kong/k8s support matrix

app/_hub/appsentinels/appsentinels/overview/_index.md
Followup PR to https://github.com/Kong/docs.konghq.com/pull/6778. Was merged with some trivial errors, in the interest of timezone coordination.
Preview link: https://deploy-preview-6918--kongdocs.netlify.app/hub/appsentinels/appsentinels/
=> chore: Fix up Appsentinels formatting and phrasing

app/_data/docs_nav_kic_3.2.x.yml, app/_data/kong_versions.yml
=> Bootstrap KIC 3.2 docs

app/_src/gateway/plugin-development/pdk/kong.plugin.md, app/_src/gateway/plugin-development/pdk/kong.response.md, app/_src/gateway/plugin-development/pdk/kong.service.request.md, app/_src/gateway/plugin-development/pdk/kong.service.response.md, app/_src/gateway/plugin-development/pdk/kong.tracing.md
PDK doc changes for 3.6 
https://konghq.atlassian.net/browse/DOCU-3638
=> Chore: PDK docs

app/_data/kong_versions.yml, app/gateway/changelog.md
Version bump and changelog for Gateway 2.8.4.7.
Preview link: https://deploy-preview-6911--kongdocs.netlify.app/gateway/changelog/#2847
=> Release: Gateway 2.8.4.7

app/_hub/kong-inc/request-transformer-advanced/how-to/_templates.md, app/_hub/kong-inc/request-transformer/how-to/_templates.md
=> fix(rt-plugin): fix description of variables

app/_data/kong_versions.yml, app/gateway/changelog.md
Changelog and version bump for Gateway 3.4.3.4.
Preview link: 
=> Release: Gateway 3.4.3.4

app/konnect/dev-portal/applications/enable-app-reg.md
=> Update enable-app-reg.md for app reg v2 changes

app/contributing/partner-plugins.md
Updating partner plugins statement in the contributing guide.
Preview link: 
=> chore: Update partner plugins statement

app/_data/kong_versions.yml
Releasing the docs for for Gateway 3.6.
Will create an  "unreleased" 3.7 branch after this is merged, as we need to create placeholder plugin schemas for 3.7.
Preview link: 
* TBA
Code freeze on all doc updates that aren't for this release.
```
make clean && make build
netlify dev
cd tools
cd broken-link-checker
node full.js --host <http://localhost:8888>
```
=> Release: Gateway 3.6

.github/styles/kong/dictionary.txt, app/_data/docs_nav_gateway_3.6.x.yml, app/_hub/kong-inc/acl/_changelog.md, app/_hub/kong-inc/acme/_changelog.md, app/_hub/kong-inc/app-dynamics/changelog.md, app/_hub/kong-inc/azure-functions/_changelog.md, app/_hub/kong-inc/basic-auth/_changelog.md, app/_hub/kong-inc/datadog/_changelog.md, app/_hub/kong-inc/forward-proxy/_changelog.md, app/_hub/kong-inc/ip-restriction/_changelog.md, app/_hub/kong-inc/jwt-signer/_changelog.md, app/_hub/kong-inc/ldap-auth-advanced/_changelog.md, app/_hub/kong-inc/mocking/_changelog.md, app/_hub/kong-inc/oas-validation/_changelog.md, app/_hub/kong-inc/oauth2-introspection/_changelog.md, app/_hub/kong-inc/openid-connect/_changelog.md, app/_hub/kong-inc/opentelemetry/_changelog.md, app/_hub/kong-inc/prometheus/_changelog.md, app/_hub/kong-inc/proxy-cache-advanced/_changelog.md, app/_hub/kong-inc/proxy-cache/_changelog.md, app/_hub/kong-inc/rate-limiting-advanced/_changelog.md, app/_hub/kong-inc/rate-limiting/_changelog.md, app/_hub/kong-inc/request-termination/_changelog.md, app/_hub/kong-inc/request-validator/_changelog.md, app/_hub/kong-inc/response-ratelimiting/_changelog.md, app/_hub/kong-inc/route-transformer-advanced/changelog.md, app/_hub/kong-inc/saml/_changelog.md, app/_src/gateway/breaking-changes/36x.md, app/_src/gateway/reference/configuration.md, app/gateway/changelog.md
Changelogs for 3.6, both general and each plugin's changelog + breaking changes page.
Preview link: 
https://deploy-preview-6939--kongdocs.netlify.app/gateway/changelog/#3600
https://deploy-preview-6939--kongdocs.netlify.app/gateway/unreleased/breaking-changes/
=> chore: Changelogs and breaking changes for 3.6

app/_data/tables/version_errors_konnect.yml
JIRA: https://konghq.atlassian.net/browse/KOKO-1435
* Adds version compatibility issues for gateway v3.6.
* Updates name remapping format to use newlines.
* Removes malformed link for Konnect Application Auth.
* Fixes malformed link for node certificate renewal.
Preview link: 
=> chore: add compatibility updates for Gateway 3.6 release

app/_src/gateway/support/sbom.md
Add SBOM link for 3.6.
Preview link: https://deploy-preview-6940--kongdocs.netlify.app/gateway/latest/support/sbom/
=> chore: 3.6 sbom link

app/_api/gateway/admin-ee/_index.md, app/_api/gateway/admin-oss/_index.md
Chore PR to update specs.
Preview link: 
=> chore: Generate insomnia buttons for 3.6 [skip ci]

app/_src/gateway/production/performance/performance-testing.md
Benchmark repo is currently private, so commenting out the links and info about running your own benchmarks for now.
Should be public by tomorrow.
Preview link: https://deploy-preview-6957--kongdocs.netlify.app/gateway/latest/production/performance/performance-testing/
=> chore: Comment out links to private benchmark repo

app/_hub/kong-inc/ai-proxy/how-to/_mistral.md
=> fix(ai-proxy): missing provider for mistral.ai

app/_assets/stylesheets/collapsible-sections.less, app/_includes/md/kic/prerequisites.md
Adjusting collapsible sections styling further based on feedback.
Also enabling the ability to:
* use this styling across the site
* disable the styling if needed with a `custom` class (currently used by KIC, since there's a lot of nested headers in the collapsible sections that would require heavy rework)
Preview link: https://deploy-preview-6958--kongdocs.netlify.app/hub/kong-inc/openid-connect/how-to/authorization/claims/
* `eq:<version>` - …
=> chore: Adjust collapsible sections to apply everywhere

app/konnect/compatibility.md
See docs.konghq.com/konnect/compatibility/#plugin-compatibility.
Preview link: 
=> chore: Add gateway version to konnect compat list

app/_src/gateway/production/performance/performance-testing.md
The performance benchmark repo is now public:  https://github.com/Kong/kong-gateway-performance-benchmark
Preview link: 
=> chore: Uncomment links to benchmarking repo

app/konnect/gateway-manager/data-plane-nodes/index.md
https://docs.konghq.com/konnect/gateway-manager/data-plane-nodes/
=> Fix: Remove extra identical heading from konnect installation docs 

app/_data/kong_versions.yml, app/_src/gateway/breaking-changes/36x.md, app/gateway/changelog.md
Changelog and version bump for gateway 3.6.1.0
Preview link: https://deploy-preview-6994--kongdocs.netlify.app/gateway/changelog/
=> Release: Gateway 3.6.1.0

app/_hub/kong-inc/openid-connect/how-to/third-party/_auth0.md
Auth0 configurations example is misleading in docs, updated the doc to remove properties that are not needed and added the important property that is needed.
Auth0 configurations example is misleading in docs, updated the doc to remove unwanted properties and added the important property that is needed.
Preview link: 
=> Updated example of Auth0 configuration _auth0.md

app/_data/docs_nav_deck_1.30.x.yml, app/_data/docs_nav_deck_1.35.x.yml, app/_includes/md/deck-reference-links.md, app/_src/deck/index.md, app/_src/deck/reference/deck_file_kong2kic.md, app/_src/deck/use-case.md
I added the documentation for the upcoming deck file `kong2kic` subcommand. I updated as well the landing page for the `deck` command.
https://konghq.atlassian.net/browse/APIOPS-8
landing page: https://deploy-preview-6905--kongdocs.netlify.app/deck/unreleased/
kongair page: https://deploy-preview-6905--kongdocs.netlify.app/deck/unreleased/use-case/
kon2kic: https://deploy-preview-6905--kongdocs.netlify.app/deck/unreleased/reference/deck_file_kong2kic/
- [review:sme] Review label added 
* `lte:<version>` - …
=> deck file kong2kic docs

app/_includes/md/kic-crd-upgrades.md, app/_src/kubernetes-ingress-controller/support-policy.md, app/_src/kubernetes-ingress-controller/upgrade/kic.md
Add information about chart compatibility with other versions.
AFAIK we haven't really ever had any official chart compatibility policy with regards to other versions. The added content reflects my understanding of the de facto policy, which is that we usually can and will accommodate older versions even in recent chart releases, but can only determine how to handle it on a case-by-case basis. We can usually make newer chart releases compatible with LTS versions, but worst case may need to instead backport fixes to older chart releases.
Add CRD update information. Helm CRD management behaves differently from everything else Helm touches and is a notorious stumbling block for upgrades. I tried to make a blurb that's relevant for both the compatibility and upgrade docs, but it maybe doesn't …
=> chore: add chart version and CRD info

app/_data/docs_nav_deck_1.36.x.yml, app/_layouts/landing-page.html, tools/broken-link-checker/config/ignored_targets.json
Updated deck's nav file and fixed a link to KM's getting started - cc @lahabana is that the right link? the old one was removed as part of [this PR](https://github.com/Kong/docs.konghq.com/pull/6900).
Preview link: 
=> Fix broken links

app/_hub/TheLEGOGroup/aws-request-signing/_metadata/_index.yml, app/_hub/amberflo/kong-plugin-amberflo/_metadata/_index.yml, app/_hub/appsentinels/appsentinels/_metadata/_index.yml, app/_hub/datadome/kong-plugin-datadome/_metadata/_index.yml, app/_hub/imperva/imp-appsec-connector/_metadata/_index.yml, app/_hub/moesif/kong-plugin-moesif/_metadata/_index.yml, app/_hub/nonamesecurity/nonamesecurity-kongtrafficsource/_metadata/_index.yml, app/_hub/okta/okta/_metadata/_index.yml, app/_hub/optum/kong-response-size-limiting/_metadata/_index.yml, app/_hub/optum/kong-service-virtualization/_metadata/_index.yml, app/_hub/optum/kong-spec-expose/_metadata/_index.yml, app/_hub/optum/kong-splunk-log/_metadata/_index.yml, app/_hub/optum/kong-upstream-jwt/_metadata/_index.yml, app/_hub/salt/salt/_metadata/_index.yml, app/_hub/wallarm/wallarm/_metadata/_index.yml, app/_includes/md/about-plugins.md, app/_layouts/extension.html, app/hub/index.html, docs/templates/partner-plugin-template/_metadata.yml, jekyll-dev.yml, jekyll.yml
For more accuracy, we are updating the category "No support available". We've had a lot of feedback from plugin owners that this category is misleading, because support is available, it's just not done by Kong.
Summary of changes:
* Category name and banner text: "No support available" -> "Contact 3rd party for support"
* Category in filter: "No support available" -> "Support by 3rd party" ("Contact 3rd party for support" doesn't fit in the space)
* URL slugs: 
* "third-party" -> "third-party-partner" for tech partners - changed this for clarity
* "none" -> "community" for 3rd party plugins that aren't partners
* Updates plugin templates to reflect the changes
Preview link: 
For example, if this change is for an upcoming 3.6 release, enclose your content in `{% if_version gte:3.6.x %} …
=> Chore: Update the 'No support available' plugins category and language

app/konnect/getting-started/add-api.md, app/konnect/getting-started/import.md, app/konnect/getting-started/index.md, app/konnect/index.md
We got some feedback before we shipped the Konnect get started rework, so this PR implements that feedback. 
DOCU-3691
Preview link: 
=> fix: Konnect Get Started Guide fast follows

app/konnect/api-products/productize-service.md
Adds API instructions to the productize a service documentation
=> Chore: Productize a service API instructions

app/_data/docs_nav_kgo_1.2.x.yml, app/_src/gateway-operator/concepts/gateway-configuration.md, app/_src/gateway-operator/concepts/managed-gateways.md, app/_src/gateway-operator/customization/data-plane-image.md, app/_src/gateway-operator/get-started/kic/create-gateway.md, app/_src/gateway-operator/get-started/kic/create-route.md, app/_src/gateway-operator/get-started/kic/install.md, app/_src/gateway-operator/get-started/konnect/create-route.md, app/_src/gateway-operator/guides/upgrade/data-plane/rolling.md
=> KGO managed gateways

app/_data/docs_nav_kgo_1.2.x.yml, app/_includes/md/kgo/prerequisites-kic.md, app/_includes/snippets/gateway-operator/install_with_helm.md, app/_plugins/hooks/products_renderer.rb, app/_src/gateway-operator/guides/ai-gateway.md, app/assets/gateway-operator/ai-gateway-crd.yaml, spec/app/_plugins/generators/hooks/products_renderer_spec.rb
Add example usage for AIGateway
Preview link: [/gateway-operator/unreleased/guides/ai-gateway/](https://deploy-preview-7078--kongdocs.netlify.app/gateway-operator/unreleased/guides/ai-gateway/)
=> KGO: AIGateway docs

app/konnect/network-resiliency.md
Adds peering information to the [Network Resiliency FAQ](https://docs.konghq.com/konnect/network-resiliency/)
https://konghq.atlassian.net/browse/DOCU-3700
=> Feat: Cloud Gateways network and peering information

changelog.md
This is a scheduled pull request to update the changelog.
=> Automated Changelog update [skip-ci]

app/_data/docs_nav_kgo_1.3.x.yml, app/_data/kong_versions.yml, app/_includes/md/kgo/prerequisites-kic.md, app/_includes/snippets/gateway-operator/install_with_helm.md
Switch KGO docs to 1.2
Preview link: /gateway-operator/latest/
=> Release KGO 1.2

app/_includes/md/plugins-hub/json-object-log.md
Documentation PR for [this feature addition](https://github.com/Kong/kong/pull/12730). Please do not merge until the feature PR is merged.
Review `/hub/kong-inc/file-log/#json-object-considerations`
[KAG-3798](https://konghq.atlassian.net/browse/KAG-3798)
[KAG-3798]: https://konghq.atlassian.net/browse/KAG-3798?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update: add latencies.receive to file-log JSON property docs

app/_data/kong_versions.yml, app/gateway/2.8.x/reference/configuration.md, app/gateway/changelog.md
Changelog, version bump, and generating kong.conf reference.
https://konghq.atlassian.net/browse/DOCU-3738
Preview link: https://deploy-preview-7136--kongdocs.netlify.app/gateway/changelog/#2848
=> Release: Gateway 2.8.4.8

app/_src/gateway/reference/expressions-language/index.md
=> style(gateway/expressions-language): fix incorrect formatting

app/konnect/updates.md
change log for DOCU-3677
Feat: UX improvements to Control Plane Groups
Preview link: 
=> Feat: UX improvements to Control Plane Groups

app/_data/docs_nav_gateway_3.6.x.yml, app/_data/docs_nav_gateway_3.7.x.yml, app/_data/tables/features/gateway.yml, app/_src/gateway/kong-enterprise/index.md, app/_src/gateway/kong-enterprise/provenance-verification.md
These are the customer-facing docs needed to allow customers to take full advantage of the recent changes to the Kong Enterprise build that implement SLSA build provenance and verification for only container images
Confluence: [Solutions Document](https://konghq.atlassian.net/wiki/spaces/KS/pages/3309273092/Solution+-+Container+Provenance+-+SLSA+generator)
Jira: [SEC-973](https://konghq.atlassian.net/browse/SEC-1003)
https://github.com/Kong/kong-ee/pull/7179
Preview link: https://deploy-preview-7067--kongdocs.netlify.app/gateway/3.6.x/kong-enterprise/provenance-verification/
Use any of the following …
=> Add gateway image build provenance verification docs

app/_hub/kong-inc/openid-connect/how-to/authentication/_authorization-code-flow.md, app/_hub/kong-inc/openid-connect/how-to/authentication/_client-credentials.md, app/_hub/kong-inc/openid-connect/how-to/authentication/_introspection.md, app/_hub/kong-inc/openid-connect/how-to/authentication/_jwt-access-token.md, app/_hub/kong-inc/openid-connect/how-to/authentication/_kong-oauth-token.md, app/_hub/kong-inc/openid-connect/how-to/authentication/_password-grant.md, app/_hub/kong-inc/openid-connect/how-to/authentication/_refresh-token.md, app/_hub/kong-inc/openid-connect/how-to/authentication/_session.md, app/_hub/kong-inc/openid-connect/how-to/authentication/_user-info.md, app/_hub/kong-inc/openid-connect/how-to/authorization/_acl.md, app/_hub/kong-inc/openid-connect/how-to/authorization/_claims.md, app/_hub/kong-inc/openid-connect/how-to/authorization/_consumer.md, app/_hub/kong-inc/openid-connect/how-to/third-party/_cognito.md, app/_hub/kong-inc/openid-connect/how-to/third-party/_curity.md, app/_includes/md/plugins-hub/oidc-prereqs.md
Updating and cleaning up workflows for all of the OIDC plugin examples.
https://konghq.atlassian.net/browse/DOCU-3651
Previews:
[Auth code flow](https://deploy-preview-6788--kongdocs.netlify.app/hub/kong-inc/openid-connect/how-to/authentication/authorization-code-flow/)
[Client credentials grant](https://deploy-preview-6788--kongdocs.netlify.app/hub/kong-inc/openid-connect/how-to/authentication/client-credentials/)
[Introspection auth](https://deploy-preview-6788--kongdocs.netlify.app/hub/kong-inc/openid-connect/how-to/authentication/introspection/)
=> Feat: Update OIDC examples

app/_src/gateway/kong-enterprise/provenance-verification.md, app/_src/gateway/kong-enterprise/signed-images.md
Late breaking feedback from/for the recent provenance verification docs work.
Jira: https://github.com/Kong/docs.konghq.com/pull/7067
Original PR: https://konghq.atlassian.net/browse/SEC-1003
Tagged with "review-general" but this PR itself is basically an SME review of the previous PR so.. ¯\\_(ツ)_/¯ 
Preview link: 
- [na] [Conditional version tags](https://docs.konghq.com/contributing/conditional-rendering/#conditionally-render-content-by-version) added, if applicable.
=> Fix: Add to Image Provenance & Signing Documents

app/konnect/gateway-manager/control-plane-groups/index.md
Changing the Team Yellow references to Team Green to reflect the correct color in the diagram
Preview link:
=> Updated the references to Team Yellow to Team Green to reflect the colors in the diagram

app/_src/kubernetes-ingress-controller/concepts/gateway-api.md
=> Add tls.mode=Terminate to KIC Gateway API concept

app/_hub/kong-inc/request-transformer-advanced/how-to/_index.md
The append example was not really using the append config option
Preview link: 
=> Correct append config example

app/konnect/gateway-manager/data-plane-nodes/upgrade.md
https://konghq.atlassian.net/browse/DOCU-3740
Adds UI and API instructions for upgrading managed data plane nodes to the existing [data plane node upgrade doc](https://docs.konghq.com/konnect/gateway-manager/data-plane-nodes/upgrade/). 
Preview: https://deploy-preview-7155--kongdocs.netlify.app/konnect/gateway-manager/data-plane-nodes/upgrade/
=> Cloud gateways: How to upgrade data plane nodes

app/_src/mesh/features/rbac.md
There is multiple fixes and changes related to RBAC documentation. Some of them were related to just moving things around, so please do review on commit per commit bases.
xref. https://github.com/Kong/kong-mesh/issues/5496
Preview link: https://deploy-preview-7195--kongdocs.netlify.app/mesh/latest/features/rbac/
=> fix(mesh): fix mesh RBAC documentation

app/_src/kubernetes-ingress-controller/index.md
Minor update to grammar and punctuation.
N/A
Preview link: 
=> Fix: KIC overview grammar and punctuation

app/konnect/gateway-manager/troubleshoot.md
https://konghq.atlassian.net/browse/DOCU-3748
Updates troubleshooting section with information about upgrading, custom domains, and DNS capabilities.
=> Cloud Gateways: Update troubleshooting section

Makefile
**chore: set SHELL in Makefile**
Add the line `SHELL := /usr/bin/env bash` at the start of the Makefile to avoid the following error while running `make install`:
```
/bin/sh: 1: [[: not found
Makefile:8: *** ruby "3.3.0" is required. Found "ruby 3.3.0 (2023-12-25 revision 5124f9ac75) [x86_64-linux]". Run `rbenv install "3.3.0"`.  Stop.
```
(Note: this error happens on a system where `ruby -v` produces `ruby 3.3.0 (2023-12-25 revision 5124f9ac75) [x86_64-linux]`)
**chore: fix install command order**
Move `git submodule update --init` before `bundle install` to address `The path `/home/phil/kong/docs.konghq.com/app/_src/.repos/kuma/jekyll-kuma-plugins` does not exist.` during `make install` command.
**chore: install specific compatible netlify-cli version**
Install a specific netlify-cli …
=> chore: set shell in makefile

app/_src/gateway/install/index.md
=> Remove br from install page note

tools/broken-link-checker/config/ignored_targets.json
Fixes Schedule broken link checker
Preview link: 
=> Exclude moesif page from broken link checker

app/_assets/entrypoints/oas.less, app/_assets/entrypoints/search.js, app/_assets/javascripts/components/Sidebar.vue, app/_assets/javascripts/views/SearchApp/App.css, app/_assets/stylesheets/footer.less, app/_assets/stylesheets/header-v2.less, app/_assets/stylesheets/hub-landing-page.less, app/_assets/stylesheets/page-header.less, app/_assets/stylesheets/page.less, app/_assets/stylesheets/pages/extension.less, app/_assets/stylesheets/pages/landing-page.less, app/_assets/stylesheets/variables.less, app/_includes/nav-v2.html
Set max-width to 1280px to the topnav + content
Preview link: 
=> Set max-width to 1280px

api-specs/Konnect/v2/yaml/cloud-gateways.yaml, app/_data/docs_nav_konnect.yml, app/_data/konnect_oas_data.json, app/_includes/md/konnect/konnect-architecture.md, app/konnect/dedicated-cloud-gateways.md, app/konnect/gateway-manager/control-plane-groups/index.md, app/konnect/gateway-manager/data-plane-nodes/index.md, app/konnect/gateway-manager/data-plane-nodes/transit-gateways.md, app/konnect/gateway-manager/dedicated-cloud-gateways.md, app/konnect/gateway-manager/index.md, app/konnect/gateway-manager/provision-cloud-gateway.md, app/konnect/geo.md, app/konnect/getting-started/index.md, app/konnect/index.md, app/konnect/reference/custom-dns.md, app/konnect/updates.md
https://konghq.atlassian.net/browse/DOCU-3764
* Adds API spec
* Adds links to the CGW docs 
* Rewords and changes some terminology 
* Moves overview page from introduction section to gateway-manager section.
* Remove soc compliance
* Updated links to CGW overview (was a 404 in the nav, some pages pointed to the old link)
* Updated the data plane node use case table to include self-managed
=> Cloud Gateways: Chore PR

app/_includes/md/konnect/deployment-topologies.md, app/konnect/gateway-manager/dedicated-cloud-gateways.md, app/konnect/gateway-manager/index.md
https://konghq.atlassian.net/browse/DOCU-3794
Preview link: 
=> Chore: Update diagrams with "fully-managed" terminology

app/_data/tables/install_options_34x.yml, app/_src/gateway/install/index.md
Adding the UTM tracking to Start for Free and adjusting the table based on feedback from Aghi that he didn't want the term "Platform" to be interpreted as the whole Kong suite having an OSS option. So, renaming to Runtime based on discussion over slack. 
Preview link: https://deploy-preview-7222--kongdocs.netlify.app/gateway/latest/install/
=> (fix) Update to GW install page

app/_api/konnect/cloud-gateways/_index.md, app/konnect/gateway-manager/dedicated-cloud-gateways.md
Add Insomnia link, and set max-width to overview page
=> Cloud gateway: Add Insomnia link, and set max-width to overview page

app/_data/kong_versions.yml, app/gateway/changelog.md
Changelog and version bump for 3.4.3.6
Trying out a method to label backported items. 
https://konghq.atlassian.net/browse/DOCU-3757
Preview link: https://deploy-preview-7220--kongdocs.netlify.app/gateway/changelog/#3436
=> Release: Gateway 3.4.3.6

app/_src/gateway/production/debug-request.md
We found conflicting statements which need to be fixed.
N/A
=> Fix -correct conflict statement in debug-request.md

app/_includes/plugins/create-consumer/terraform.html, app/_includes/plugins/hub-examples/consumer.html, app/_includes/plugins/hub-examples/consumer_groups.html, app/_includes/plugins/hub-examples/global.html, app/_includes/plugins/hub-examples/route.html, app/_includes/plugins/hub-examples/service.html, app/_includes/plugins/hub-examples/terraform.html, app/_plugins/drops/plugins/hub_examples.rb, app/_plugins/filters/quote_filter.rb, app/_plugins/generators/plugin_single_source/plugin/page_data.rb
Add Terraform examples to the Plugin Hub
Preview link: https://deploy-preview-7244--kongdocs.netlify.app/hub/kong-inc/rate-limiting/how-to/basic-example/?tab=konnect-terraform
=> Add Konnect Terraform tab to plugin examples

app/konnect/dev-portal/access-and-approval/auto-approve-devs-apps.md, app/konnect/dev-portal/dev-reg.md
- Describe developer auto approval behavior when using SSO login
- Change Konnect catalog to Dev Portal catalog in SSO login instructions
Preview link: 
=> feat(portal): describe developer auto approval behavior when using SSO login

app/_hub/kong-inc/jwt/overview/_index.md
Update docs to reflect recent changes in the JWT plugins.
Added support for:
* ES512
* PS256
* PS384
* PS512
* EdDSA
@kong-docs Should we restructure the docs a bit to use `Conditional version tags` more effectively?
Jira: https://konghq.atlassian.net/browse/KAG-4029
=> plugins(jwt): support more algorithms

app/konnect/architecture.md
Quickstart does not exist anymore
=> Chore: Remove quickstart link

app/_src/gateway/support/index.md
Specify supported public cloud deployment platforms
Added a section to explicitly state supported public cloud deployment platforms.
See discussion https://kongstrong.slack.com/archives/C03CTMSHP6C/p1711364444857179
Preview link: 
=> Add supported public cloud deployment platforms

app/konnect/dev-portal/applications/dynamic-client-registration/index.md, app/konnect/updates.md
Remove image, fix endpoint urls, change a get request to a post request.
=> Chore: Dynamic Client Registration fixes

app/_src/gateway/breaking-changes/30x.md, app/_src/gateway/install/kubernetes/proxy.md, app/_src/gateway/plugin-development/custom-entities.md, app/_src/gateway/plugin-development/pdk/kong.request.md, app/_src/gateway/plugin-development/pdk/kong.tracing.md, app/_src/gateway/production/access-control/enable-rbac.md, app/_src/gateway/production/deployment-topologies/hybrid-mode/setup.md, app/_src/gateway/production/monitoring/index.md, app/_src/gateway/production/tracing/api.md, app/_src/gateway/reference/configuration/configuration-3.0-3.3.md, app/_src/gateway/reference/configuration/configuration-3.4.x.md, app/_src/gateway/reference/configuration/configuration-3.5.x.md, app/_src/gateway/reference/rate-limiting.md, app/_src/gateway/upgrade-v3.md, app/_src/gateway/upgrade/backup-and-restore.md
Fix multiple typos under app/_src/gateway
Preview link:
=> Fix multiple typos under app/_src/gateway

app/konnect/dev-portal/applications/dynamic-client-registration/auth0.md, app/konnect/dev-portal/applications/dynamic-client-registration/azure.md, app/konnect/dev-portal/applications/dynamic-client-registration/curity.md, app/konnect/dev-portal/applications/dynamic-client-registration/okta.md, app/konnect/gateway-manager/troubleshoot.md, app/konnect/updates.md
Fixed multiple typos under app/konnect directory
* stratgies -> strategies
* trasparent -> transparent
* mutliple -> multiple
I think this PR might go with `review:general` label. 
Preview link:
=> Fix multiple typos under app/konnect directory

app/_src/kubernetes-ingress-controller/guides/security/plugin-secrets.md
Fix instructions in the guide page of uing `configPatch`es in plugins.
Docs part of https://github.com/Kong/kubernetes-ingress-controller/issues/5687. 
Preview link:
=> Fix guide docs about using configPatches

app/_data/tables/support/gateway/third-party.yml, app/_data/tables/support/gateway/versions/37.yml, app/_src/gateway/support/index.md, app/_src/gateway/support/third-party.md
Update support pages for 3.7.
https://konghq.atlassian.net/browse/DOCU-3800
Preview link:
=> chore: Add 3.7 support tabs/pages and fix typo

app/_hub/kong-inc/graphql-proxy-cache-advanced/how-to/_index.md, app/_hub/kong-inc/graphql-proxy-cache-advanced/overview/_index.md, app/_hub/kong-inc/graphql-rate-limiting-advanced/how-to/_index.md, app/_hub/kong-inc/graphql-rate-limiting-advanced/overview/_index.md
Adding links to Kong with GraphQL ebook to make it more discoverable: https://konghq.com/solutions/api-management-graphql 
Preview link:
=> chore: Add links to graphql paper

app/_src/gateway/support/index.md
Link to the Konnect policy page from the Gateway page
=> Fix: Link to the Konnect policy page from the Gateway page

app/_src/gateway/plugin-development/pdk/index.md, app/_src/gateway/plugin-development/pdk/kong.jwe.md, app/_src/gateway/plugin-development/pdk/kong.log.md, app/_src/gateway/plugin-development/pdk/kong.tracing.md, app/_src/gateway/reference/cli.md
https://konghq.atlassian.net/browse/DOCU-3805
https://konghq.atlassian.net/browse/DOCU-3806
Generated PDK and CLI for 3.7
=> Chore: Generate PDK and CLI for Gateway 3.7

app/_hub/kong-inc/ai-rate-limiting-advanced/overview/_index.md
=> Fix: Visual error in AI plugin admonition

app/konnect/reference/search.md
`control_plane` was listed twice.
https://deploy-preview-7361--kongdocs.netlify.app/konnect/reference/search/#entity-types
=> Remove duplicated entry

app/konnect/compatibility.md
Update compatibility table for Konnect
Preview link:
=> Fix: Update Konnect compatibility dates

app/_data/kong_versions.yml, app/gateway/changelog.md
Changelog and version bump for 3.6.1.4
https://konghq.atlassian.net/browse/DOCU-3842
Preview link: https://deploy-preview-7377--kongdocs.netlify.app/gateway/changelog/
=> Release: Gateway 3.6.1.4

app/_src/gateway/support/index.md
moved konnect policy under the gateway policy so clearer for readers
Preview link:
=> Fix: Move Konnect policy note in Gateway support doc

app/_src/gateway/production/performance/performance-testing.md
The raw data is posted [here](https://docs.google.com/spreadsheets/d/1knu87tczpuTQ4a5si3WSkOoFHWf0pS8vqNpC44-Oxmw/edit#gid=499697946)
=> update the perf stats for 3.7

app/_src/gateway/production/performance/performance-testing.md
The raw results could be found [here](https://docs.google.com/spreadsheets/d/1knu87tczpuTQ4a5si3WSkOoFHWf0pS8vqNpC44-Oxmw/edit#gid=2133252633)
=> Update performance-testing.md for 3.7 rc5

app/_data/kong_versions.yml, app/_src/gateway/key-concepts/routes/expressions.md, app/_src/gateway/kong-enterprise/secrets-management/backends/hashicorp-vault.md, app/_src/gateway/reference/expressions-language/language-references.md, app/gateway/changelog.md
Changelog, version bump, and remove 'unless' statements for 3.5
https://konghq.atlassian.net/browse/DOCU-3739
Preview link: https://deploy-preview-7378--kongdocs.netlify.app/gateway/changelog/#3504
=> Release: Gateway 3.5.0.4

app/konnect/api/index.md
https://konghq.atlassian.net/browse/DOCU-3856
=> Fix: Add content types to Konnect API page

app/_data/docs_nav_gateway_3.7.x.yml, app/_src/gateway/breaking-changes/37x.md, app/_src/gateway/production/tracing/index.md
Breaking changes in 3.7.
https://konghq.atlassian.net/browse/DOCU-3808
Preview link:
=> chore: Breaking changes page for 3.7

app/_src/gateway/plugin-development/pluginserver/javascript.md
- added example configuration for Javascript custom plugins
- added some required dependency when running TypeScript 
Preview link: 
- [ x ] Review label added 
- [ x ] [Conditional version tags](https://docs.konghq.com/contributing/conditional-rendering/#conditionally-render-content-by-version) added, if applicable.
=> added example in javascript custom plugin

.github/workflows/build-docs-pdf.yml, .github/workflows/build-plugin-pdf.yml, .github/workflows/run-tests.yml, .github/workflows/scheduled-broken-link-checker.yml
=> WIP: Don't install netlify-cli globally when running smoke tests

app/_hub/kong-inc/acme/_changelog.md, app/_hub/kong-inc/ai-prompt-guard/_changelog.md, app/_hub/kong-inc/ai-proxy/_changelog.md, app/_hub/kong-inc/aws-lambda/_changelog.md, app/_hub/kong-inc/degraphql/_changelog.md, app/_hub/kong-inc/graphql-proxy-cache-advanced/_changelog.md, app/_hub/kong-inc/jwt-signer/_changelog.md, app/_hub/kong-inc/jwt/_changelog.md, app/_hub/kong-inc/key-auth/_changelog.md, app/_hub/kong-inc/ldap-auth-advanced/_changelog.md, app/_hub/kong-inc/mocking/_changelog.md, app/_hub/kong-inc/mtls-auth/_changelog.md, app/_hub/kong-inc/oas-validation/_changelog.md, app/_hub/kong-inc/openid-connect/_changelog.md, app/_hub/kong-inc/opentelemetry/_changelog.md, app/_hub/kong-inc/prometheus/_changelog.md, app/_hub/kong-inc/rate-limiting-advanced/_changelog.md, app/_hub/kong-inc/rate-limiting/_changelog.md, app/_hub/kong-inc/response-ratelimiting/_changelog.md, app/_src/gateway/breaking-changes/37x.md, app/gateway/changelog.md
* Compile changelog for 3.7.
* Add changelogs to plugins.
* Add missing breaking change to 3.7 breaking changes doc.
https://konghq.atlassian.net/browse/DOCU-3797
Preview link: https://deploy-preview-7411--kongdocs.netlify.app/gateway/changelog/
=> chore: Changelog for 3.7.0.0

app/konnect/updates.md
https://konghq.atlassian.net/browse/DOCU-3762
https://konghq.atlassian.net/browse/DOCU-3782
https://deploy-preview-7408--kongdocs.netlify.app/konnect/updates/
=> Chore: Update Konnect changelog for Gateway 3.7

app/konnect/updates.md
Update changelog
Remove incorrect line
Preview link:
=> Fix: konnect 3.7 changelog

app/konnect/analytics/index.md, app/konnect/network-resiliency.md
Updating the Konnect network FAQ with Q&As about telemetry data communication between cp and dp.
https://konghq.atlassian.net/browse/DOCU-3859
Preview link: https://deploy-preview-7434--kongdocs.netlify.app/konnect/network-resiliency/
=> Update: Telemetry FAQs for Konnect

app/_data/tables/version_errors_konnect.yml
https://konghq.atlassian.net/browse/KOKO-1675
Include new changes from https://github.com/Kong/koko-private/commit/bebd07ed6128703b06f55ff521ff7f3605cd2b20
Preview link:
=> chore: add compatibility updates for Gateway 3.7 release

app/konnect/dev-portal/applications/dynamic-client-registration/auth0.md
Fixes confusion around audience and client audience 
Preview link:
=> doc(dcr): clarify audience field

app/_data/docs_nav_mesh_2.8.x.yml, app/_src/mesh/features/meshopa.md
=> fix(mesh): remove beta on MeshOPA

app/gateway/changelog.md
Corrects broken link to demonstrated proof-of-possession page in changelog.
Preview link:
=> fix(changelog): correct broken link

api-specs/Gateway-EE/3.5/kong-ee-3.5.yaml, api-specs/Gateway-EE/latest/kong-ee.yaml
=> doc(*): update api docs and added missing the API of groups

app/_hub/kong-inc/acl/_api.md
Fixed 'Update and insert ACL group names' and 'Update ACL groups by ID' being reversed.
Preview link:
=> Fixes reversed descriptions of post and put.

app/_data/docs_nav_deck_1.38.x.yml, app/_data/docs_nav_deck_1.39.x.yml, app/_data/kong_versions.yml, app/_src/deck/reference/deck_file_add-plugins.md, app/_src/deck/reference/deck_file_openapi2kong.md, app/_src/deck/reference/deck_gateway_validate.md, app/_src/deck/reference/deck_validate.md
Bump deck versions, add new and missing cli flags.
Based on changelogs for 1.37 and and 1.38: https://github.com/Kong/deck/releases
Preview link:
https://deploy-preview-7466--kongdocs.netlify.app/deck/latest/reference/deck_file_openapi2kong/
https://deploy-preview-7466--kongdocs.netlify.app/deck/latest/reference/deck_file_validate/
https://deploy-preview-7466--kongdocs.netlify.app/deck/latest/reference/deck_file_add-plugins/
=> Release: decK 1.37 and 1.38

app/_hub/kong-inc/websocket-size-limit/overview/_index.md, app/_hub/kong-inc/websocket-validator/overview/_index.md
Converting this:
Into this:
Preview link: 
https://deploy-preview-7472--kongdocs.netlify.app/hub/kong-inc/websocket-size-limit/
https://deploy-preview-7472--kongdocs.netlify.app/hub/kong-inc/websocket-validator/
=> Chore: Convert codeblock diagrams into mermaid format

app/_data/docs_nav_gateway_3.8.x.yml, app/_data/kong_versions.yml, app/_data/tables/support/gateway/versions/38.yml, app/_src/gateway/breaking-changes/38x.md, app/_src/gateway/support/index.md, app/_src/gateway/support/third-party.md
Chore PR to set up 3.8 for development.
Preview link:
=> chore: Set up unreleased 3.8 version

app/_data/kong_versions.yml, app/gateway/changelog.md
Changelog and version bump for 3.4.3.9.
Preview link: https://deploy-preview-7432--kongdocs.netlify.app/gateway/changelog/#3439
=> Release: Gateway 3.4.3.9

app/_data/konnect_oas_data.json
=> Fix: fix 3.7 naming convention

app/_src/kubernetes-ingress-controller/plugins/oidc.md
Fixes a typo in documentation.
=> Fix: typo in OIDC doc

api-specs/Konnect/v2/yaml/api-products.yaml, api-specs/portal.yaml, app/_api/konnect-portal/_index.md, app/_api/konnect/cloud-gateways/_index.md, app/_data/konnect_oas_data.json, app/_plugins/generators/oas_definition/error_page.rb, app/_plugins/generators/oas_definition/product.rb, app/_plugins/generators/oas_definition_pages_generator.rb, spec/app/_plugins/generators/oas_definition/product_spec.rb
@mheap made additional changes to the x-error rendering in this PR. Please review
=> Fix support for x-errors in OAS

app/_data/kong_versions.yml, app/_hub/kong-inc/request-validator/_changelog.md, app/gateway/changelog.md
Changelog and version bump for 3.7.1.0.
Preview link: https://deploy-preview-7525--kongdocs.netlify.app/gateway/changelog/
=> Release: Gateway 3.7.1.0

app/_data/kong_versions.yml, app/gateway/changelog.md
Changelog and version bump for 3.6.1.5
Preview link: https://deploy-preview-7527--kongdocs.netlify.app/gateway/changelog/#3615
=> Release: Gateway 3.6.1.5

app/_data/kong_versions.yml, app/gateway/changelog.md
Changelog and version bump for 3.5.0.5.
Preview link: https://deploy-preview-7528--kongdocs.netlify.app/gateway/changelog/#3505
=> Release: Gateway 3.5.0.5

app/_data/kong_versions.yml, app/gateway/changelog.md
Changelog and version bump for 2.8.4.10
Preview link: https://deploy-preview-7530--kongdocs.netlify.app/gateway/changelog/#28410
=> Release: Gateway 2.8.4.10

app/_includes/md/about-plugins.md, app/_src/gateway/glossary.md
https://konghq.atlassian.net/browse/DOCU-2348
=> TD: Update Plugins overview page

app/_data/kong_versions.yml, app/gateway/changelog.md
changelog and version bump for 3.7.1.1
Preview link:
=> Release: Gateway 3.7.1.1

app/_data/kong_versions.yml, app/gateway/changelog.md
changelog and version bump for 3.6.1.6
Preview link:
=> Release: Gateway 3.6.1.6

app/_data/kong_versions.yml, app/gateway/changelog.md
changelog and version bump for 3.4.3.11
Preview link:
=> Release: Gateway 3.4.3.11

app/_data/kong_versions.yml, app/gateway/changelog.md
changelog and version bump for 2.8.4.11
Preview link:
=> Release: Gateway 2.8.4.11

app/gateway/changelog.md
`## Fixes` should be `### Fixes`
Preview link:
=> Fix: GW changelog heading levels

app/_src/gateway/kong-enterprise/workspaces/index.md
https://konghq.atlassian.net/browse/FTI-6013
Preview link:
=> docs(workspaces): add description about entities that have no workspaces or should be unique across workspaces.

api-specs/Konnect/v1/yaml/ksearch.yaml, api-specs/Konnect/v2/yaml/api-products.yaml, api-specs/Konnect/v2/yaml/control-planes.yaml, api-specs/Konnect/v3/yaml/identity.yaml
Generated OAS files from platform-api.
=> feat(sdk): automated oas update

app/_includes/md/k8s/single-ingress.md
closes: https://github.com/Kong/docs.konghq.com/issues/7584
Preview link:
=> fix: Gateway install on GKE

api-specs/Gateway-EE/latest/kong-ee.yaml
https://konghq.atlassian.net/browse/DOCU-2261
Added the endpoint to the generator as well.
=> add workspaces_ and fix a formatting issue to  EE admin API 

app/_hub/kong-inc/ai-proxy/overview/_index.md
Clarified a number of model supports, added GPT-4o / LLAMA3.
Preview link:
=> fix(ai-proxy): clarify model support

app/_assets/stylesheets/collapsible-sections.less, app/_data/docs_nav_gateway_3.0.x.yml, app/_data/docs_nav_gateway_3.1.x.yml, app/_data/docs_nav_gateway_3.2.x.yml, app/_data/docs_nav_gateway_3.3.x.yml, app/_data/docs_nav_gateway_3.4.x.yml, app/_data/docs_nav_gateway_3.5.x.yml, app/_data/docs_nav_gateway_3.6.x.yml, app/_data/docs_nav_gateway_3.7.x.yml, app/_data/docs_nav_gateway_3.8.x.yml, app/_src/gateway/key-concepts/consumers.md
Consumers entity reference containing:
* intro/general info about consumers
* use cases
* how to create a consumer using various tools
* bunch of FAQs
https://konghq.atlassian.net/browse/DOCU-3758
Preview link: https://deploy-preview-7512--kongdocs.netlify.app/gateway/latest/key-concepts/consumers/
=> Feat: Consumers key concept/reference page

app/konnect/analytics/index.md, app/konnect/updates.md
Konnect analytics ingestion toggle.
=> Feat: Konnect analytics ingestion toggle 

.vale.ini
Vale added this validation here
https://github.com/errata-ai/vale/commit/f7cbb579a821023c0fd8497b3866205f11e57e7a
=> Fix: Vale ignored classes line.

app/contributing/style-guide.md
https://konghq.atlassian.net/browse/DOCU-3817
Document expectations for writing about third-party things.
=> Chore: Documenting third-party tools instructions

app/_data/kong_versions.yml, app/gateway/changelog.md
Changelog and version bump for 3.7.1.2
Preview link:
=> Release: Gateway 3.7.1.2

app/_data/kong_versions.yml, app/gateway/changelog.md
Changelog and version bump for 3.5.0.7
Will need a plugin schema update but there's no RC yet, so will generate that when it's available.
Preview link:
=> Release: Gateway 3.5.0.7

app/_data/kong_versions.yml, app/gateway/changelog.md
changelog and version bump for 3.6.1.7
Preview link:
=> Release: Gateway 3.6.1.7

tools/broken-link-checker/config/ignored_targets.json
Add urls to the broken link checker's list of ignored_targets
Preview link:
=> fix: Add urls to the broken link checker's list of ignored_targets

app/_src/gateway/production/performance/performance-testing.md
Fixing a small typo on Kong Docs
Preview link:
=> Fixing small typo

app/_src/deck/guides/getting-started.md
=> Linkify link to deduplicate guide

app/_hub/kong-inc/request-validator/overview/_index.md
The previous sentences already clarified the strictly validation behavior. Hence remove a sentence that may confuse users.
> The parameter is strictly validated, which means a request with a parameter (for example, `application/json; charset=UTF-8`) is NOT considered valid for one without the same parameter (for example, `application/json`). The type, subtype, parameter names, and the value of the charset parameter are not case sensitive based on the RFC explanation.
Preview link: 
FTI-6102
=> fix(gateway/request-validator): update document

app/_hub/kong-inc/ai-proxy/how-to/llm-provider-integration-guides/_llama2.md
Removing an extra character from the end of an example.
Fixes https://github.com/Kong/docs.konghq.com/issues/7608.
=> Fix: Remove extra backslash

app/_src/gateway/reference/nginx-directives.md
Add a link to all "NGINX Injected Directives section" to explicitly state all supported namespaces.
Add a link to all "NGINX Injected Directives section" to explicitly state all supported namespaces. It avoids confusion as to what namespaces are supported in Kong.
Preview link:
=> Update nginx-directives.md to list supported namespaces

app/_src/mesh/installation/ecs.md
Updated docs after env variable was removed in 2.7
Preview link:
=> docs(mesh): update ECS env variables

app/konnect/updates.md
API Requests and Explorer now have a refresh button that allows users to manually refresh/fetch data without a full page site reload. It also preserves all filters.
Aha ticket: https://konghq.aha.io/features/KP-506
Preview link:
=> (feat/refresh): added release notes for new refresh button

app/_src/gateway/licenses/index.md
Adjusting phrasing around Enterprise license expiration.
Preview link:
=> License expiration adjustment

app/gateway/changelog.md
Changed typo `availibilty` to `availability`.
Preview link:
=> typo fix: availibilty to availability

app/_hub/kong-inc/ai-rate-limiting-advanced/overview/_index.md
Fixing the description for the AI RLA plugin. 
Reported on Slack 
Preview link:
=> fix: Phrasing and typos in AI RLA plugin

app/konnect/updates.md
=> Update changelog for SAML release

app/_data/docs_nav_gateway_3.4.x.yml, app/_data/kong_versions.yml, app/gateway/changelog.md
Changelog and version bump for 3.4.3.12
Preview link: https://deploy-preview-7727--kongdocs.netlify.app/gateway/changelog/#34312
Check that page exists: https://deploy-preview-7727--kongdocs.netlify.app/gateway/3.4.x/kong-enterprise/provenance-verification/
=> Release: Gateway 3.4.3.12

app/_assets/entrypoints/application.js, app/_assets/javascripts/promo-banner.js, app/_assets/stylesheets/header.less, app/_includes/nav-v2.html
Annual banner for the Summit hackathon, as requested by dev marketing.
https://konghq.atlassian.net/browse/DOCU-4020
Preview link:
=> chore: Banner for summit hackathon

app/konnect/dev-portal/index.md
Remove mention of free in dev portal analytics
=> Fix: Remove mention of free

app/konnect/gateway-manager/index.md, app/konnect/updates.md
https://konghq.atlassian.net/browse/DOCU-4017
=> Fix: Control planes can be deleted.

app/_redirects, app/contributing/user-interfaces.md, tools/broken-link-checker/config/ignored_targets.json
Fix a few broken links.
@Guaris tagging you because of the dev-portal one
Preview link:
=> Fix a few broken links

app/_src/gateway/production/performance/benchmark.md
This pull request updates the `resources.requests` field in the generated instructions for KIC deployments with [the minimum requirements from our docs](https://docs.konghq.com/gateway/latest/production/sizing-guidelines/#cluster-resource-allocations) and removes the `resources.limits` field to allow the user to set the maximum limitation.
KM-431
=> fix(gateway): update resources.requests to minimum hardware requirements

app/_hub/traceableai/traceableai/_metadata/_index.yml, app/_hub/traceableai/traceableai/schemas/_index.json
- Add timeout config for latest version of our plugin
- Specify konnect compatibility
- Add kong support versions
Preview link:
=> docs(traceableai) - Add timeout config, specify konnect compatibility, add kong versions

app/konnect/gateway-manager/data-plane-nodes/index.md, app/konnect/updates.md
https://konghq.atlassian.net/browse/DOCU-4025
* Adds a changelog
* Deletes the cloud launchers text from the data plane node index page
=> Chore: Cloud launchers deprecation announcement

app/_includes/nav-v2.html
Summit Hackathon is now open, so we've been asked to update the CTA from "learn more" to "enter now".
Preview link:
=> chore: Update banner CTA text

app/konnect/gateway-manager/data-plane-nodes/index.md
=> Fix: note in data plane nodes doc

app/_src/gateway/production/performance/performance-testing.md
The raw results could be found [here](https://docs.google.com/spreadsheets/d/1knu87tczpuTQ4a5si3WSkOoFHWf0pS8vqNpC44-Oxmw/edit?gid=1514764379#gid=1514764379)
=> Update performance-testing.md for 3.8 rc2

api-specs/Gateway-EE/latest/kong-ee.yaml
=> docs(admins): update the admin's API.

api-specs/Gateway-EE/3.3/kong-ee-3.3.json, api-specs/Gateway-EE/3.3/kong-ee-3.3.yaml, api-specs/Gateway-EE/3.4/kong-ee-3.4.json, api-specs/Gateway-EE/3.4/kong-ee-3.4.yaml, api-specs/Gateway-EE/3.5/kong-ee-3.5.yaml, api-specs/Gateway-EE/3.6/kong-ee-3.6.yaml, api-specs/Gateway-EE/latest/kong-ee.yaml
This PR added missing endpoints for 3.3 and 3.4.
1. `/admins`
2. `/groups`
3. `/rbac`
4. `/event-hooks`
5. `/audit-log`
6. added information endpoint `/`.
7. added `kong-admin-token` in request headers.
8. remove unused `Basic-auth-credential`'s tag.
9. added missing tag for consumer-group and license for version 3.3.
Preview link: 
KM-433,KM-434
=> docs(*): added missing endpoints and tags for 3.3 and 3.4

api-specs/Gateway-EE/latest/kong-ee.yaml
Reverts Kong/docs.konghq.com#7825
=> Revert "docs(admins): update the admin's API."

api-specs/Gateway-EE/3.6/kong-ee-3.6.yaml, api-specs/Gateway-EE/3.7/kong-ee-3.7.yaml, api-specs/Gateway-EE/latest/kong-ee.yaml
https://konghq.atlassian.net/browse/DOCU-4056
=> Fix: Event hooks missing delete

app/konnect/org-management/deactivation.md
Add a third option to close your Plus or Enterprise account
Preview link:
=> Fix: Add a third option to close your Plus or Enterprise account

app/konnect/gateway-manager/configuration/index.md
Add note about contacting support to increase resource limits.
Requested on Slack, as customers have run into these limits and didn't know what to do about them: https://kongstrong.slack.com/archives/C07JN2D8RAS/p1725722454208289?thread_ts=1725652540.259969&cid=C07JN2D8RAS
Preview link: https://deploy-preview-7877--kongdocs.netlify.app/konnect/gateway-manager/configuration/#configuration-limits
=> Update: Konnect resource limits note

app/konnect/updates.md, tools/beamer/fetch-beamer-posts.js
Adds an entry for Beamer to prepare the changelog for the drastic change in appearance. 
Adds a small line break to make sure that the change log entries don't misalign themselves. 
Checks to make sure that a month is already on the page.
=> Chore: Update changelog entries

.github/styles/kong/dictionary.txt, app/_data/docs_nav_gateway_3.8.x.yml, app/_src/gateway/migrate-to-new-dns-client.md, app/_src/gateway/production/networking/dns-considerations.md, app/_src/gateway/production/performance/benchmark.md
Documented migration to new DNS client.
https://konghq.atlassian.net/browse/DOCU-4021
Preview links:
- [Migration](https://deploy-preview-7805--kongdocs.netlify.app/gateway/unreleased/migrate-to-new-dns-client/)
- [Performance](https://deploy-preview-7805--kongdocs.netlify.app/gateway/unreleased/production/performance/benchmark/#dns-client)
- [DNS considerations](https://deploy-preview-7805--kongdocs.netlify.app/gateway/unreleased/production/networking/dns-considerations/#dns-clients)
=> Feat: New DNS client for Gateway 3.8

app/_src/gateway/production/performance/performance-testing.md
The raw results could be found [here](https://docs.google.com/spreadsheets/d/1knu87tczpuTQ4a5si3WSkOoFHWf0pS8vqNpC44-Oxmw/edit?gid=789258075#gid=789258075)
=> Update performance-testing.md for 3.8 rc4

app/_includes/footer.html, app/konnect/org-management/deactivation.md, app/konnect/updates.md
Updating links to the privacy policy and terms of use to the currently accurate links. Both of the old links were redirecting, and occasionally getting flagged as 404s (https://github.com/Kong/docs.konghq.com/actions/runs/10729302320/job/29755630384?pr=7857).
Preview link:
=> Chore: update legal links

.github/styles/kong/dictionary.txt, app/_hub/kong-inc/opentelemetry/_metadata/_index.yml, app/_hub/kong-inc/opentelemetry/how-to/_dynatrace.md, app/_hub/kong-inc/opentelemetry/how-to/_getting-started.md, app/_hub/kong-inc/opentelemetry/how-to/_spans.md, app/_hub/kong-inc/opentelemetry/how-to/dynatrace.md, app/_hub/kong-inc/opentelemetry/overview/_index.md
New page for Dynatrace.
Also split the very long main page into multiple how-to guides.
❗ Note to reviewers: The dynatrace page is the only new page. I didn't edit or rewrite any of the other content, I only split it into pages. You can copyedit them if you have time, but that's not the priority here.
https://konghq.atlassian.net/browse/DOCU-3879
Preview link: 
https://deploy-preview-7881--kongdocs.netlify.app/hub/kong-inc/opentelemetry/unreleased/
https://deploy-preview-7881--kongdocs.netlify.app/hub/kong-inc/opentelemetry/unreleased/how-to/dynatrace/
=> Feat: OTEL with Dynatrace + plugin doc refactor

app/konnect/updates.md
=> Fix: Konnect changelog

app/_data/tables/version_errors_konnect.yml
Add tracked changes for 3.8 release.
Add some 3.6 changes added after that release.
Update name format for a couple entries. 
https://konghq.atlassian.net/browse/KOKO-1951
https://konghq.atlassian.net/browse/DOCU-4039
Preview link:
=> feat: 3.8 tracked changes docs

app/konnect/updates.md
Update changelogs to new format, and announce that beamer is released.
=> Chore: Konnect changelog update

app/_hub/kong-inc/ai-semantic-cache/overview/_index.md, app/_includes/md/ai-plugins-links.md
Update semantic cache links to new name and add missing AI plugins links.
Link test should pass.
=> Fix: broken links in 3.8

app/konnect/gateway-manager/dedicated-cloud-gateways.md, app/konnect/geo.md
https://konghq.atlassian.net/browse/DOCU-4051
=> Chore: Update Cloud Gateways geos 

app/konnect/updates.md
Latest Konnect changelog entries from beamer
=> Automated Konnect changelog update [skip-ci]

app/_data/docs_nav_gateway_3.8.x.yml, app/_hub/kong-inc/ai-proxy-advanced/how-to/machine-learning-platform-integrations/bedrock.md, app/_hub/kong-inc/ai-proxy/how-to/machine-learning-platform-integration-guides/bedrock.md
DOCU-3863
Preview link: 
- https://deploy-preview-7913--kongdocs.netlify.app/hub/kong-inc/ai-proxy/how-to/machine-learning-platform-integration-guides/bedrock/
- https://deploy-preview-7913--kongdocs.netlify.app/hub/kong-inc/ai-proxy-advanced/how-to/machine-learning-platform-integrations/bedrock/
=> feat: Bedrock docs for AI Proxy and AI Proxy Advanced

app/_hub/kong-inc/opentelemetry/how-to/_dynatrace.md, app/_hub/kong-inc/opentelemetry/overview/_index.md
* more accurate endpoints
* blurb on metrics
Preview link: 
https://deploy-preview-7907--kongdocs.netlify.app/hub/kong-inc/opentelemetry/
https://deploy-preview-7907--kongdocs.netlify.app/hub/kong-inc/opentelemetry/how-to/dynatrace/
=> Fix: OTEL + dynatrace feedback

app/_hub/kong-inc/json-threat-protection/_metadata/_index.yml
The JSON-Threat-Protection IS compatible with Konnect, this PR is to fix it.
Preview link:
=> Fix: correct the Konnect compatibility of the JSON-Threat-Protection Plugin

app/_data/tables/version_errors_konnect.yml
Fixes broken entity links.
Preview link:
=> fix: broken entity links

app/_hub/kong-inc/prometheus/overview/_index.md
https://github.com/Kong/kong/blob/f03ea81c8912856534278a6852d0c9924a325a56/kong/plugins/prometheus/schema.lua#L20
https://konghq.atlassian.net/browse/DOCU-1601
=> Fix: Prometheus status code metrics description

api-specs/Gateway-EE/3.6/kong-ee-3.6.yaml, api-specs/Gateway-EE/3.7/kong-ee-3.7.yaml, api-specs/Gateway-EE/latest/kong-ee.yaml, api-specs/Gateway-OSS/3.6/kong-oss-3.6.yaml, api-specs/Gateway-OSS/3.7/kong-oss-3.7.yaml, api-specs/Gateway-OSS/latest/kong-oss.yaml
https://konghq.atlassian.net/browse/DOCU-1660
https://konghq.atlassian.net/browse/DOCU-1659
=> Chore: Clustering endpoints 

app/konnect/dev-portal/customization/self-hosted-portal.md
=> Chore: Update self-hosted portals

app/_hub/kong-inc/request-validator/overview/_index.md
Preview link: 
[FTI-6196](https://konghq.atlassian.net/browse/FTI-6196)
[FTI-6196]: https://konghq.atlassian.net/browse/FTI-6196?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(gateway/request-validator): mention format keyword only supported in draft4 version

app/_src/gateway/production/clustering.md, app/_src/gateway/production/deployment-topologies/hybrid-mode/setup.md
Followup to https://github.com/Kong/docs.konghq.com/pull/7935
Need the real links before merging.
Preview link:
=> Chore: minor cleanup to moved API docs

app/_hub/kong-inc/grpc-gateway/how-to/_index.md
Issue reported through docs feedback
Preview link:
=> Fix: Protobuf structure issue

app/_src/deck/faqs.md, app/_src/gateway/kong-enterprise/secrets-management/backends/env.md, app/_src/gateway/plugin-development/custom-entities.md, app/_src/kubernetes-ingress-controller/get-started/rate-limiting.md
Various errors and typos reported through docs feedback
=> Fix: typos

app/_src/gateway/kong-enterprise/secrets-management/backends/azure-key-vaults.md
https://github.com/Kong/docs.konghq.com/issues/7099
=> bug bash: Managed Identity seems to be failing for Azure Container Apps for secret manager integration

app/_hub/optum/kong-spec-expose/examples/_index.yml
https://github.com/Kong/docs.konghq.com/issues/5026
=> Bug bash: Expose plugin example must link to raw spec

app/konnect/dev-portal/create-dev-portal.md
https://github.com/Kong/docs.konghq.com/issues/7709
=> Bug-bash: Remove dev portal prereqs

app/_src/gateway/production/networking/firewall.md
Remove Transparent proxy section 
https://github.com/Kong/docs.konghq.com/issues/5355
=> Bug bash: remove transperent proxy section

app/_hub/kong-inc/request-transformer-advanced/overview/_index.md
Adjusting the link text in the plugin overview to be more descriptive.
Fixes https://github.com/Kong/docs.konghq.com/issues/5593.
Preview link:
=> Adjust Request Transformer Advanced plugin link text

app/konnect/compatibility.md
=> chore: update konnect compatibility

api-specs/Gateway-EE/3.3/kong-ee-3.3.json, api-specs/Gateway-EE/3.3/kong-ee-3.3.yaml, api-specs/Gateway-EE/3.4/kong-ee-3.4.json, api-specs/Gateway-EE/3.4/kong-ee-3.4.yaml, api-specs/Gateway-EE/3.5/kong-ee-3.5.yaml, api-specs/Gateway-EE/3.6/kong-ee-3.6.yaml, api-specs/Gateway-EE/3.7/kong-ee-3.7.yaml, api-specs/Gateway-EE/latest/kong-ee.yaml
=> docs(admin): added missing status of the endpoint `/admins`

app/_src/gateway/kong-manager/enable.md
Preview link: 
https://deploy-preview-7976--kongdocs.netlify.app/
KM-516
=> docs(gui): update docs for Kong Manager

app/_data/kong_versions.yml, app/gateway/changelog.md
Changelog and version bump for  Gateway 3.6.1.8.
Preview link: https://deploy-preview-8051--kongdocs.netlify.app/gateway/changelog/#3618
=> Release: Gateway 3.6.1.8

app/_hub/kong-inc/request-validator/overview/_index.md
crated from Jira: https://konghq.atlassian.net/browse/FTI-6269?focusedCommentId=144703
Preview link:
=> Update request-validator content-type validation

api-specs/Gateway-EE/latest/kong-ee.yaml, app/_src/gateway/kong-enterprise/db-encryption.md
- Add keyring/remove
- Add info about configuration for traditional/hybrid mode
[DOCU-4011](https://konghq.atlassian.net/browse/DOCU-4011)
Preview link: 
[DOCU-4011]: https://konghq.atlassian.net/browse/DOCU-4011?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update: Keyring docs

app/_src/gateway/get-started/ai-gateway.md
Added decK examples for the AI Gateway getting started guide, by request. 
Also added tabs to the example at the bottom of the page that I missed earlier.
Tested, everything works.
Preview link: https://deploy-preview-8077--kongdocs.netlify.app/gateway/latest/get-started/ai-gateway/
=> chore: decK tabs for the AI gateway getting started guide

app/_src/kubernetes-ingress-controller/install/helm.md
Adding a missing `.
Preview link:
=> Fix: typo in k8s install

app/_includes/md/kgo/konnect-entities-prerequisites.md, app/_includes/md/kgo/prerequisites.md, app/_includes/snippets/gateway-operator/install_with_helm.md, app/_src/gateway-operator/guides/plugin-distribution.md
Passes feature flags directly to the `install_with_helm.md` so they can be used in `helm install` command instead of enabling them separately with kubectl.
Preview links:
- https://deploy-preview-8106--kongdocs.netlify.app/gateway-operator/latest/guides/ai-gateway/
- https://deploy-preview-8106--kongdocs.netlify.app/gateway-operator/unreleased/guides/plugin-distribution/
- https://deploy-preview-8106--kongdocs.netlify.app/gateway-operator/unreleased/guides/konnect-entities/gatewaycontrolplane/
=> docs(kgo): pass feature flags to install with helm

app/_src/gateway-operator/reference/cli-arguments/1.4.x.md, app/_src/gateway-operator/reference/custom-resources/1.4.x.md
Updates the generated references for KGO 1.4.x.
Preview link:
=> chore(kgo): update generated crd and cli references

app/gateway-operator/changelog.md
Extracted from #8083 
Preview link: https://deploy-preview-8101--kongdocs.netlify.app/gateway-operator/changelog/#140
=> chore(kgo): add changelog for 1.4.0

app/_hub/impart-security/kong-plugin-impart/overview/_index.md
Incorrectly labeled title as overview, corrected it to Impart Security.  Link to page https://docs.konghq.com/hub/impart-security/kong-plugin-impart/
NA
NA
=> Update title to Impart Security

Gemfile, Gemfile.lock
=> Bump jekyll-generator-single-source

app/_src/gateway/production/sizing-guidelines.md
Adding a "development" entry to the table to match the "Kong Gateway resources" table earlier in the page.
The recommended values are the same as "small".
Request from Slack: https://kongstrong.slack.com/archives/CDSTDSG9J/p1730734309753949
Preview link:
=> Update: Add 'development' entry for cluster resource allocations table

api-specs/Gateway-EE/latest/kong-ee.yaml, api-specs/Gateway-OSS/latest/kong-oss.yaml
The version numbers on the latest API admin pages was `3.7.0` (EE) and `3.7.1` (OSS) and they should be `3.8.0`.
- [EE API admin page](https://docs.konghq.com/gateway/api/admin-ee/3.8.0.x/)
- [OSS API Admin page](https://docs.konghq.com/gateway/api/admin-oss/latest/)
Preview link:
=> fix(docs): correct the latest version on the API admin page

app/_data/kong_versions.yml, app/_plugins/generators/kuma_to_kong_mesh.rb, spec/fixtures/app/kuma-to-kong-mesh.md
With the recent change do the docs generator we were not rewrite the links correctly.
Preview link: 
<!-
=> docs(mesh): fix link rewrites

app/_includes/md/availability-stages.md
=> Feat: Support policy change

app/_data/docs_nav_kic_3.4.x.yml, app/_data/kong_versions.yml, app/_includes/md/kic-crd-upgrades.md, app/_src/kubernetes-ingress-controller/upgrade/kic.md
Changes instructions for upgrading KIC CRDs switching from the ones stored in the KIC repository, to the new `kong/kubernetes-configuration` central repository. It also prepares the unreleased KIC 3.4 version.
Note: for upcoming KIC 3.4 this will point to not yet existing `v1.0.0` `kong/kubernetes-configuration` tag. It will be released before KIC 3.4 and it's tracked as an explicit dependency:  https://github.com/Kong/kubernetes-ingress-controller/issues/6635
Part of https://github.com/Kong/kubernetes-ingress-controller/issues/6580.
Preview link: https://deploy-preview-8137--kongdocs.netlify.app/kubernetes-ingress-controller/unreleased/upgrade/kic/#update-custom-resource-definitions
=> docs(kic): refer to kubernetes-configuration in KIC 3.4 >= docs

app/_includes/header/nav-links.html, app/_layouts/default.html, jekyll-dev.yml, jekyll.yml
Make "Report an Issue" link configurable and fix translation banner in api specs.
Preview link:
=> Make "Report an Issue" link configurable

app/_hub/kong-inc/aws-lambda/overview/_index.md, app/_src/gateway/kong-enterprise/aws-iam-auth-to-rds-database.md, app/_src/gateway/kong-enterprise/secrets-management/backends/aws-sm.md
=> chore(gateway): add notice for unsupported AWS credential provider

app/_hub/kong-inc/ai-proxy-advanced/overview/_index.md, app/_hub/kong-inc/ai-proxy/overview/_index.md
Updated the AI Proxy and AI Proxy Advanced docs to add a request example with guardrails for Bedrock.
[DOCU-4167](https://konghq.atlassian.net/browse/DOCU-4167)
Preview link: 
[DOCU-4167]: https://konghq.atlassian.net/browse/DOCU-4167?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update: Guardrail for Bedrock

app/_hub/kong-inc/ai-rate-limiting-advanced/how-to/_index.md
Reverts    #8183
The upstream PR won't be included in the release
Preview link:
=> Revert #8183

app/_src/kubernetes-ingress-controller/guides/services/custom-entity.md, app/_src/kubernetes-ingress-controller/reference/feature-gates.md
Related issue: https://github.com/Kong/kubernetes-ingress-controller/issues/6628
Preview link: 
- https://deploy-preview-8153--kongdocs.netlify.app/kubernetes-ingress-controller/unreleased/guides/services/custom-entity/
- https://deploy-preview-8153--kongdocs.netlify.app/kubernetes-ingress-controller/3.3.x/guides/services/custom-entity/
- https://deploy-preview-8153--kongdocs.netlify.app/kubernetes-ingress-controller/3.2.x/guides/services/custom-entity/
=> kic: update Custom Entities guide for GA in 3.4

api-specs/Gateway-EE/3.8/kong-ee.yaml, api-specs/Gateway-EE/3.9/kong-ee.yaml, api-specs/Gateway-OSS/3.8/kong-oss.yaml, api-specs/Gateway-OSS/3.9/kong-oss.yaml
=> Chore: 3.9 api specs prep

app/_src/gateway/production/performance/performance-testing.md
The raw results could be found [here](https://docs.google.com/spreadsheets/d/1knu87tczpuTQ4a5si3WSkOoFHWf0pS8vqNpC44-Oxmw/edit?gid=131097464#gid=131097464)
=> Update performance-testing.md for 3.9 rc4

app/_data/docs_nav_gateway_3.10.x.yml, app/_data/kong_versions.yml
Releasing the docs for for Gateway 3.9 + creating a placeholder 3.10 version.
Preview link:  https://deploy-preview-8244--kongdocs.netlify.app/gateway/
* https://github.com/Kong/docs.konghq.com/milestone/63
Code freeze on all doc updates that aren't for this release.
```
make clean && make build
netlify dev
cd tools
cd broken-link-checker
node full.js --host <http://localhost:8888>
```
=> Release: Gateway 3.9

app/_data/docs_nav_gateway_3.9.x.yml, app/_hub/kong-inc/ai-prompt-guard/_changelog.md, app/_hub/kong-inc/ai-proxy-advanced/_changelog.md, app/_hub/kong-inc/ai-proxy/_changelog.md, app/_hub/kong-inc/ai-rate-limiting-advanced/_changelog.md, app/_hub/kong-inc/ai-request-transformer/_changelog.md, app/_hub/kong-inc/ai-response-transformer/_changelog.md, app/_hub/kong-inc/ai-semantic-cache/_changelog.md, app/_hub/kong-inc/ai-semantic-prompt-guard/_changelog.md, app/_hub/kong-inc/app-dynamics/changelog.md, app/_hub/kong-inc/aws-lambda/_changelog.md, app/_hub/kong-inc/correlation-id/_changelog.md, app/_hub/kong-inc/degraphql/_changelog.md, app/_hub/kong-inc/exit-transformer/_changelog.md, app/_hub/kong-inc/graphql-rate-limiting-advanced/_changelog.md, app/_hub/kong-inc/json-threat-protection/_changelog.md, app/_hub/kong-inc/jwe-decrypt/_changelog.md, app/_hub/kong-inc/jwt-signer/_changelog.md, app/_hub/kong-inc/jwt/_changelog.md, app/_hub/kong-inc/kafka-log/_changelog.md, app/_hub/kong-inc/key-auth/_changelog.md, app/_hub/kong-inc/loggly/_changelog.md, app/_hub/kong-inc/oas-validation/_changelog.md, app/_hub/kong-inc/openid-connect/_changelog.md, app/_hub/kong-inc/prometheus/_changelog.md, app/_hub/kong-inc/rate-limiting-advanced/_changelog.md, app/_hub/kong-inc/rate-limiting/_changelog.md, app/_hub/kong-inc/request-validator/_changelog.md, app/_src/gateway/breaking-changes/39x.md, app/gateway/changelog.md
Changelog and breaking changes page for 3.9.
https://konghq.atlassian.net/browse/DOCU-4164
https://konghq.atlassian.net/browse/DOCU-4154
Preview link: 
https://deploy-preview-8243--kongdocs.netlify.app/gateway/changelog/
https://deploy-preview-8243--kongdocs.netlify.app/gateway/unreleased/breaking-changes/
=> chore: Changelog for Gateway 3.9

app/konnect/compatibility.md
=> Chore: Update konnect compatibility for 3.9

app/_hub/kong-inc/prometheus/overview/_index.md
Fix parameter name and add enterprise badge for AI metrics in Prometheus docs.
Preview link: https://deploy-preview-8269--kongdocs.netlify.app/hub/kong-inc/prometheus/#ai-llm-metrics
=> Fix: Prometheus AI metrics

app/_src/deck/reference/deck_gateway_validate.md
Add doc for the feature online plugins filter flag for Deck
Related to PR: https://github.com/Kong/deck/pull/1458
Preview link:
=> feat(Deck): add feature online plugins filter flag

app/_data/docs_nav_deck_1.42.x.yml, app/_data/docs_nav_deck_1.43.x.yml, app/_data/kong_versions.yml, app/_src/deck/reference/deck_file_kong2tf.md
Bump decK version, as 1.4.2 went out friday last week.
Preview link:
=> Release: Deck 1.4.1 and 1.4.2

app/_src/kubernetes-ingress-controller/plugins/acl.md
#8277 missed the fact that we want the `konghq.com/credential` label upon creation to use the webhook validation. This PR fixes it.
Preview link: https://deploy-preview-8281--kongdocs.netlify.app/kubernetes-ingress-controller/unreleased/plugins/acl/#provision-jwt-credentials
=> kic: add secret credential labels upon creation

app/_hub/kong-inc/prometheus/overview/_index.md, app/_src/gateway/ai-gateway/index.md
Fixes the following:
- [Make the Logging label OSS instead of Enterprise](https://docs.konghq.com/gateway/3.8.x/ai-gateway/#logging)
- [Add Konnect Advanced Analytics bullet to the AI observability section and label](https://docs.konghq.com/gateway/3.8.x/ai-gateway/#ai-observability)
- [Mention AI gateway metrics on Prometheus plugin page and label as Enterprise](https://docs.konghq.com/hub/kong-inc/prometheus/#available-metrics): This is mentioned in the existing page, it's just referenced later down the page and the customer couldn't find it. I moved it to the "available metrics" section as well with a link to the other section for findability.
https://kongstrong.slack.com/archives/CDSTDSG9J/p1734333985135819
Preview link: 
- https://deploy-preview-8285--kongdocs.netlify.app/gateway/late …
=> fix: AI Gateway metrics info

app/_data/tables/version_errors_konnect.yml
https://konghq.atlassian.net/browse/KOKO-1954
Add available 3.9 compat changes. 
3.9 work that has not been checked into the Gateway yet is not included in this PR.
Also has a few formatting and typo updates.
Preview link:
=> feat: add compatibility updates for Gateway 3.9 release

app/_src/gateway-operator/get-started/konnect/deploy-data-plane.md
Reflect changes from
- https://github.com/Kong/gateway-operator/pull/947
in the documentation closes https://github.com/Kong/gateway-operator/issues/936
Preview link: https://deploy-preview-8306--kongdocs.netlify.app/gateway-operator/latest/get-started/konnect/deploy-data-plane/
=> kgo: do not require `serverHostname` for KonnectExtension for KGO >=1.5.x

.github/workflows/build-docs-pdf.yml, .github/workflows/build-plugin-pdf.yml, .github/workflows/run-tests.yml, .github/workflows/scheduled-broken-link-checker.yml
=> Run netlify dev with npx

app/_assets/javascripts/app.js
It feels weird when the tab is half way down the page
Preview link:
=> Don't scroll the page when setting a tab via query param

app/_src/gateway/kong-enterprise/datakit/get-started.md
Some minor adjustments to the datakit guide for better usability, including removing the "plugin_example" tag and switching to a simpler manually written example so that we don't have to deal with a placeholder for the service.
Issue reported on slack: https://kongstrong.slack.com/archives/CDSTDSG9J/p1736408687578789
Preview link: https://deploy-preview-8333--kongdocs.netlify.app/gateway/latest/kong-enterprise/datakit/get-started/
=> fix: Datakit guide

api-specs/Gateway-EE/3.4/kong-ee-3.4.yaml, api-specs/Gateway-EE/3.6/kong-ee-3.6.yaml, api-specs/Gateway-EE/3.7/kong-ee-3.7.yaml, api-specs/Gateway-EE/3.8/kong-ee.yaml, api-specs/Gateway-EE/3.9/kong-ee.yaml, api-specs/Gateway-EE/latest/kong-ee.yaml
=> Fix: Add Admins and groups schemas

app/_data/kong_versions.yml, app/gateway/changelog.md
Version bump and changelog for 3.4.3.16
Preview link: https://deploy-preview-8346--kongdocs.netlify.app/gateway/changelog/#34316
=> Release: Gateway 3.4.3.16

app/_api/konnect/notification-hub/_index.md
https://github.com/Kong/docs.konghq.com/pull/8353
=> Feat: notification hub

api-specs/Gateway-EE/3.6/kong-ee-3.6.yaml, api-specs/Gateway-EE/3.7/kong-ee-3.7.yaml, api-specs/Gateway-EE/3.8/kong-ee.yaml, api-specs/Gateway-EE/3.9/kong-ee.yaml, api-specs/Gateway-EE/latest/kong-ee.yaml
Fixes https://github.com/Kong/developer.konghq.com/issues/263
Made this match generated version, we can fix generated version text in source.
=> Fix: Vault shema to match generated one

api-specs/Gateway-EE/3.6/kong-ee-3.6.yaml, api-specs/Gateway-EE/3.7/kong-ee-3.7.yaml, api-specs/Gateway-EE/3.8/kong-ee.yaml, api-specs/Gateway-EE/3.9/kong-ee.yaml, api-specs/Gateway-EE/latest/kong-ee.yaml
Fixes https://github.com/Kong/developer.konghq.com/issues/302
=> Fix: Upstream algo section should be enum

.github/raise-pr-on-change.json
=> Fix path to files

app/_assets/entrypoints/application.js, app/_assets/javascripts/tabs.js, app/_assets/stylesheets/navtabs.less, app/_plugins/kuma-specific/tabs/tabs.rb, app/_plugins/kuma-specific/tabs/template.erb
This is a change needed backporting from `kuma-webiste`.
Closes https://github.com/Kong/kong-mesh/issues/7359 .
Preview link: https://deploy-preview-8385--kongdocs.netlify.app/mesh/latest/policies/meshloadbalancingstrategy/#examples
Click on the "I am using MeshService" checkbox and see if it converts between `kuma.io` style and `MeshService` style targetrefs.
=> fix(mesh): fix I'm using mesh service checkbox

app/_data/kong_versions.yml, app/gateway/changelog.md
Changelog and version bump for 3.9.0.1
Preview link: https://deploy-preview-8358--kongdocs.netlify.app/gateway/changelog/
=> Release: Gateway 3.9.0.1

app/_plugins/kuma-specific/tabs/tabs.rb
=> Fix rubocop issues

app/deck/file/kong2kic.md, app/deck/file/kong2tf.md
Add missing `kong2kic` and `kong2tf` examples
Preview link:
=> Add kong2kic and kong2tf examples

app/konnect/geo.md
Add dev portals to list of geo-specific items.
Update requested [on Slack](https://kongstrong.slack.com/archives/CDSTDSG9J/p1738952194597479).
Preview link:
=> Add dev portals to geo-specific objects list

app/deck/file/manipulation/index.md, app/deck/install/binary.md, app/deck/install/docker.md
Smriti gave feedback that upgrading deck is difficult. Added some short descriptions on how to upgrade.
Preview link:
=> Add upgrade instructions to decK

app/_src/gateway-operator/topologies/hybrid.md
KGO supports `KonnectExtension` in 1.4+. We missed updating the topology page with this new, easier way to configure things when it was released.
Preview link:
=> Use KonnectExtension in KGO hybrid topology doc

app/_src/gateway-operator/production/monitoring/metrics.md
Add introductions about metrics for Konnect entity operations.
Fixes https://github.com/Kong/docs.konghq.com/issues/8415.
Preview link: 
https://deploy-preview-8414--kongdocs.netlify.app/gateway-operator/unreleased/production/monitoring/metrics/#example-metrics-about-konnect-entity-operation
=> add docs for konnect entity operation metrics

app/_layouts/default.html
Add signals script tag as requested via slack
Preview link:
=> Add signals script tag

app/_src/gateway/key-concepts/routes/index.md
=> Fix: route priority info

app/_includes/md/kic/support.md, app/_src/kubernetes-ingress-controller/reference/version-compatibility.md
=> chore: update version compatibility for KIC

app/_hub/kong-inc/loggly/overview/_index.md
Remove unrelated description of Syslog in Loggly page.
Preview link:
=> Fix: Loggly plugin description update

app/_src/kubernetes-ingress-controller/plugins/custom.md
Fixes #8303 
Preview link: https://deploy-preview-8467--kongdocs.netlify.app/kubernetes-ingress-controller/latest/plugins/custom/
=> kgo: fix KongPluginInstallation link

app/_data/kong_versions.yml, app/gateway/changelog.md
Changelog and version bump for 3.7.1.4
Preview link:
=> Release: Gateway 3.7.1.4 

app/_src/gateway/kong-enterprise/fips-support/install.md
The gpg key wasn't displaying, so the install doc was broken.
Preview link:
=> Fix fips install

app/_hub/kong-inc/json-threat-protection/overview/_index.md
Please merge this PR after the PR https://github.com/Kong/kong-ee/pull/11437 is merged.
KAG-6419
Preview link:
=> docs(json-threat-protection): add a description for the supported HTTP methods

app/dev-portal/app-reg/index.md
=> Voigt edits 2

app/_plugins/generators/algolia/base.rb, app/_plugins/generators/site_product_data.rb
=> rubocop fixes

app/_data/docs_nav_dev-portal.yml, tools/_utilities/lib/nav-to-index-page.js
Update Dev Portal icons
Preview link: /dev-portal/
=> Fix Dev Portal icons

app/_assets/entrypoints/oas.js, app/_assets/javascripts/views/SpecView.vue, app/_layouts/oas/spec.html, app/_plugins/drops/oas/version.rb, app/_plugins/generators/oas_definition/page_data.rb, package-lock.json, package.json, vite.config.ts
=> Replace swagger-ui with spec-renderer

app/_src/gateway/production/networking/cp-dp-proxy.md
=> Fix: Update cp-dp-proxy.md

.github/styles/kong/dictionary.txt, app/deck/install/docker.md
=> fix(deck): docker on Windows

app/_assets/javascripts/views/SpecView.vue
=> ADd padding to api specs

api-specs/Konnect/v4/yaml/metrics.yaml, app/_api/konnect/metrics/_index.md, app/_data/konnect_oas_data.json
=> Feat: Metrics api

app/_data/docs_nav_gateway_3.10.x.yml, app/_src/gateway/production/deployment-topologies/hybrid-mode/incremental-config-sync.md, app/_src/gateway/production/deployment-topologies/hybrid-mode/index.md
Documentation for the incremental config sync feature.
https://konghq.atlassian.net/browse/DOCU-4174
Preview link: https://deploy-preview-8520--kongdocs.netlify.app/gateway/unreleased/production/deployment-topologies/hybrid-mode/incremental-config-sync/
=> Incremental config sync doc

app/_src/gateway-operator/guides/konnect-entities/consumer-and-consumergroup.md
Describes how to use Secrets as consumer credentials in KGO's Konnect entities.
ref: https://github.com/Kong/gateway-operator/issues/618
Closes #8474
Preview link:  https://deploy-preview-8547--kongdocs.netlify.app/gateway-operator/unreleased/guides/konnect-entities/consumer-and-consumergroup/#using-secrets
=> kgo: add KGO 1.5 guide for consumer credential Secrets

.github/workflows/ci-autofix.yml, .github/workflows/linting.yml
Addresses security vulnerability; see INC-456.
Preview link:
=> fix(security): pin version

app/konnect/reference/saml-idp-mappings.md
I'm modifying the referenced email claim for Azure SAML applications, updating from `user.email` to. `user.mail`.
I'm also including a note in the Azure navtab that states "ensure the `Namespace` value is empty".
Screenshots are attached for additional Azure/SAML context and verification.
* Default claims: ![Screenshot 2025-03-17 at 15 14 31](https://github.com/user-attachments/assets/e9025332-70c9-4f58-b27d-b2d0a279e3da)
* Claim edit window (showing `Namespace`): 
Preview link:
=> fix(konnect): update Azure SAML claim attributes

app/_hub/kong-inc/app-dynamics/overview/_index.md
=> feat: AppDynamics agent ARM support

app/deck/apiops/index.md
"X, Y and Z" was a placeholder that snuck through
Preview link:
=> Fix APIOps introduction

app/_hub/kong-inc/confluent-consume/overview/_index.md, app/_hub/kong-inc/kafka-consume/overview/_index.md
Followup of https://github.com/Kong/docs.konghq.com/pull/8506
Mainly fixes to plugin naming and some enumeration corrections
=> fix: s/consumer/consume/g

app/konnect/private-connections/aws-privatelink.md
Added new AWS Private Link regions
https://konghq.atlassian.net/browse/CSRE-3763
Preview link:
=> CSRE-3763 Added documentation for 2 new edge gateway regions

app/_data/extensions.yml, app/hub/plugins/license-tiers.md
Add a note that AI plugins require additional licensing
Preview link: https://deploy-preview-8597--kongdocs.netlify.app/hub/plugins/license-tiers/
=> Add AI pricing disclaimer

app/_hub/kong-inc/ai-proxy-advanced/how-to/_load-balancing.md, app/_hub/kong-inc/ai-proxy-advanced/overview/_index.md
Add following features:
- ai-proxy-advanced: new priority algorithm
- ai-proxy-advanced: failover creteria
- ai-proxy-advanced: cost as tokens_count_strategy (mention log_statistics must be on)
Fixes:
https://konghq.atlassian.net/browse/DOCU-4194
https://konghq.atlassian.net/browse/DOCU-4193
Preview link: 
AG-228
=> docs(ai-proxy-advanced): add new feature description for ai-proxy-advanced in 3.10

app/_data/kong_versions.yml, app/gateway/changelog.md
Changelog and version bump for 3.9.1.1
Preview link:
=> Release: Gateway 3.9.1.1

api-specs/Gateway-EE/latest/kong-ee.yaml, app/_src/gateway/admin-api/index_latest.md
https://github.com/Kong/kong-ee/pull/11436
=> 3.10 API spec changes

app/_src/gateway/admin-api/index_latest.md, app/_src/gateway/kong-enterprise/index.md, app/_src/gateway/kong-enterprise/partials.md
All links fixed except for the `partials` one, the endpoints were added to latest but not to 3.9
Preview link:
=> Fix links to api-endpoints

app/_src/gateway/admin-api/index_latest.md
=> Fix partials no if_version

app/_data/kong_versions.yml, app/gateway/changelog.md
Changelog and version bump for 3.4.3.17
Preview link:
=> Release: Gateway 3.4.3.17

app/_src/gateway/support/sbom.md
Add 3.10 sbom link and reorder in descending order.
Not live yet, so the link will be broken for now.
https://konghq.atlassian.net/browse/DOCU-4203
Preview link:
=> chore: Gateway 3.10 SBOM link

api-specs/Gateway-EE/latest/kong-ee.yaml, app/_data/konnect_oas_data.json
=> fix: 3.10 API update

app/dev-portal/access-and-approvals/sso.md
Provide additional IdP configuration information specifically related to the new Dev Portal and Konnect Portal Editor experience.
Based on this internal doc: https://docs.google.com/document/d/1_h2rsg4x77EnedPaILYKV1ce93IHHTPcqIVALCFw9lU/edit?tab=t.0
Preview link:
=> docs(portal): additional idp configuration

app/_assets/javascripts/plugin-hub.js, tests/sidebar.test.js
Fix Plugin Hub search after tier removal
Preview link: [/hub/](https://deploy-preview-8626--kongdocs.netlify.app/hub/)
=> Fix Plugin Hub search

app/_hub/kong-inc/ai-rag-injector/how-to/_index.md
=> Fix: title AI RAG INJECTOR

app/_includes/md/konnect/okta-sso.md
=> Fix SSO url

app/_src/gateway/plugin-development/distribution.md
=> Fix small typo under the OCI Artifacts section in distribution.md

app/_data/kong_versions.yml, app/_src/gateway-operator/guides/konnect-entities/cloud-gateways-data-plane-group-configuration.md, app/_src/gateway-operator/guides/konnect-entities/cloud-gateways-network.md
Mark KGO 1.5 as latest and fix some minor inconsistencies in Konnect DataPlane Group configuration docs
Preview link: https://deploy-preview-8653--kongdocs.netlify.app/gateway-operator/latest/guides/konnect-entities/cloud-gateways-data-plane-group-configuration/
=> kgo: make 1.5 latest and fix Konnect DataPlane Group configuration docs

app/_hub/kong-inc/ai-rag-injector/how-to/_index.md
=> Add AI RAG Injector Admin api usage

app/_hub/kong-inc/ai-proxy-advanced/how-to/_load-balancing.md
Fix algorithm field in priority load balancing example for AI Proxy Advanced
Preview link:
=> Fix: Priority load balancing example

app/_hub/kong-inc/ai-rag-injector/how-to/_index.md
Fix misleading title for step 2
Preview link: https://deploy-preview-8668--kongdocs.netlify.app/hub/kong-inc/ai-rag-injector/how-to/
=> [AI RAG Injector] How to - Update title of step 2

app/konnect/gateway-manager/control-plane-groups/migrate.md
CLUSTER_TYPE_COMPOSITE  -> CLUSTER_TYPE_CONTROL_PLANE_GROUP
=> Remove outdated Runtime groups parameter 

app/_src/gateway/production/logging/ai-analytics.md
=> Fix links of ai-semantic-cache

app/_hub/kong-inc/ai-proxy-advanced/overview/_index.md
=> fix: fix ai-proxy-advanced balancer doc link typo

app/_data/docs_nav_dev-portal.yml, app/dev-portal/portals/customization/custom-pages.md, app/dev-portal/portals/customization/snippets.md
Added nav item & docs for Snippets, in preparation of releasing the feature
- Aha: https://konghq.aha.io/epics/DEVP-E-3
- Jira: https://konghq.atlassian.net/browse/TDX-5270
=> [TDX-5270] Snippets docs

app/dev-portal/portals/customization/snippets.md
Reference “Snippets” instead of “Pages” on the snippet page
Preview link:
=> docs(portal): snippets page header

app/_data/kong_versions.yml, app/gateway/changelog.md
Changelog and version bump for 3.10.0.1
Preview link:
=> Release: Gateway 3.10.0.1

api-specs/Gateway-EE/3.10/kong-ee.yaml
=> Add gateway-ee 3.10 api-spec

app/_hub/kong-inc/request-callout/overview/_index.md
Request Callout examples [requested on Slack](https://github.com/Kong/developer.konghq.com/issues/1020#issuecomment-2779506535)
Preview link:
=> Feat: New Request Callout examples

app/_hub/kong-inc/ai-proxy/how-to/_sdk-usage.md
Updated AI "templated options" example for a better sub-string sample configuration.
=> fix(ai): update options-param templating documentation

app/_hub/kong-inc/ai-sanitizer/overview/_index.md
update ai-sanitizer doc
Preview link:
=> update ai-sanitizer doc

app/_includes/md/ai-plugins-links.md
AI plugins links list is missing plugins from 3.10.
Also removing the badges, since we're no longer using badges in 3.10 onward.
Preview link:
=> chore: Update list of AI plugins links

app/konnect/private-connections/aws-privatelink.md
Added Section for making Konnect Admin API requests over PrivateLink
1. https://konghq.atlassian.net/browse/CSRE-4181
2. https://konghq.atlassian.net/browse/CSRE-3768
Preview link:
=> CSRE-4181 Private Link for Konnect Admin API documentation

app/konnect/private-connections/aws-privatelink.md
=> privatelink: remove duplicate region

app/_hub/kong-inc/ai-rag-injector/how-to/_index.md
The script should be updated
Preview link:
=> update script for ai-rag

app/konnect/private-connections/aws-privatelink.md
=> private-link: fix regions list

app/_data/tables/support/gateway/versions/310.yml, app/_data/tables/support/gateway/versions/34.yml
Update the amazonlinux2 EOL date based on the [amazon linux 2 faq](https://aws.amazon.com/amazon-linux-2/faqs/). 
Preview link: https://deploy-preview-8747--kongdocs.netlify.app/
=> fix: update amazon linux 2 eol date

app/konnect/account-management/index.md
Fixed the link to the pricing page since it was currently a 404.
https://kongstrong.slack.com/archives/CDSTDSG9J/p1747126054849879
Preview link:
=> fix: Konnect billing dashboard link

app/_assets/javascripts/views/SpecView.vue, app/_assets/stylesheets/header.less, app/_assets/stylesheets/page-header.less, app/_assets/stylesheets/page.less, app/_assets/stylesheets/sidebar.less
=> More mobile fixes due to the banner

app/_hub/kong-inc/ai-rag-injector/how-to/_index.md
=> Fix AI RAG Injector to correct template

app/konnect/service-catalog/integrations/gitlab.md
https://deploy-preview-8711--kongdocs.netlify.app/konnect/service-catalog/integrations/gitlab/
=> Feat: Gitlab self-hosted

app/konnect/gateway-manager/configuration/config-store.md
=> Provide some details on the Konnect Config Store

app/_includes/md/kgo/prerequisites.md
fix: https://github.com/Kong/gateway-operator/issues/1584
Preview link:
=> update GatewayAPI version for KGO

app/_includes/nav-v2.html
=> Open link to dev site on the same tab

app/_hub/kong-inc/ai-proxy-advanced/how-to/_load-balancing.md
Fix: Updated options for vector DBs in  the AI Proxy advanced plugin.
[Preview link: ](https://deploy-preview-8780--kongdocs.netlify.app/hub/kong-inc/ai-proxy-advanced/how-to/load-balancing/#semantic-routing)
=> fix: Update vectordb options for AI Proxy Advanced

redirects.yaml
Update links to dev site based on past two weeks of migration.
Don't merge until the following PRs are both merged:
[Custom plugins in konnect and external PDK links](https://github.com/Kong/developer.konghq.com/pull/1705)
[Migrate brotli doc](https://github.com/Kong/developer.konghq.com/pull/1706)
=> chore: Update links in banner

redirects.yaml
I combined the Dev Portal snippets and pages docs into one doc on the dev site, so this updates their redirects.
https://github.com/Kong/developer.konghq.com/pull/1668
Preview link:
=> Update Dev Portal pages and snippets redirects

redirects.yaml
Adds the correct redirects for the newly migrated KM networking and FIPS support.
Preview link: 
- https://deploy-preview-8840--kongdocs.netlify.app/gateway/latest/kong-manager/networking/
- https://deploy-preview-8840--kongdocs.netlify.app/gateway/latest/kong-enterprise/fips-support/
=> KM networking and FIPS redirects

redirects.yaml
From Jason, he couldn't find where the Dev Portal RBAC section should go on the new dev site. This attempts to redirect from a section on the docs site to the dev site.
Preview link:
=> Add Dev Portal RBAC redirect

redirects.yaml
Migrated the [Verify audit log signatures page](https://github.com/Kong/developer.konghq.com/pull/1812)
=> Fix: Konnect audit logs migration

redirects.yaml
Migrated [Authenticate your Kong Gateway Amazon RDS database with AWS IAM](https://github.com/Kong/developer.konghq.com/pull/1810)
=> Fix: Redirect for Authenticate your Kong Gateway Amazon RDS database with AWS IAM

redirects.yaml
Updated redirect after migrating the StatsD monitoring how-to.
Do not merge until https://github.com/Kong/developer.konghq.com/pull/1734 is merged
=> StatsD how-to migration

redirects.yaml
Added dev site redirects for Datadog with Prometheus and Konnect audit log webhook how to
Preview link:
=> redirects: Datadog with prometheus and Konnect audit log webhook how to

app/_redirects
Redirect for https://github.com/Kong/developer.konghq.com/pull/1893.
Preview link: https://deploy-preview-8864--kongdocs.netlify.app/konnect/reference/search/
=> Redirect: Konnect search

app/_redirects
Issue reported on slack: https://kongstrong.slack.com/archives/CDSTDSG9J/p1750888219371709
Merge after https://github.com/Kong/developer.konghq.com/pull/1957.
https://deploy-preview-8872--kongdocs.netlify.app/konnect/org-management/users/
https://deploy-preview-8872--kongdocs.netlify.app/konnect/org-management/org-switcher/
=> Fix: Konnect redirects
