Kong/docs.konghq.com

app/_src/kic-v2/faq.md
Based on information gathered from 
- https://github.com/Kong/charts/pull/269
- https://github.com/Kong/kubernetes-ingress-controller/issues/682
- https://kubernetes.github.io/ingress-nginx/deploy/baremetal/#via-the-host-network
document when and how deploy KIC as DaemonSet, update of Helm chart docs is needed to, see and review https://github.com/Kong/charts/pull/918
Closes https://github.com/Kong/kubernetes-ingress-controller/issues/4728
Preview link:
=> Document in FAQ running KIC as DaemonSet

app/gateway/changelog.md
The PR fixes the issue that the changelog entries of OpenSSL version bumping from 1.1.1t to 3.1.1 are missing from several specific versions.
The missing version list are:
- 2.8.4.2
- 3.1.1.5
- 3.2.2.4
- 3.3.1.1
The PR adds all of them.
Preview link:
=> fix: fix changelog entry for openssl version bump

app/_data/tables/install_options.yml, app/_data/tables/install_options_34x.yml
On our [installation overview page for Gateway](https://docs.konghq.com/gateway/latest/install/), we only list RHEL and Debian as Docker options. Since this page was created, we've added support for Ubuntu and AL 2 & 2023 docker images. Ubuntu, especially, is the base OS for our convenience tags (eg latest, 3.4, 3.4.1.1) so not having it listed here is very confusing. 
Preview link: https://deploy-preview-6380--kongdocs.netlify.app/gateway/latest/install/
=> Fix: Add missing docker image options to Gateway install overview

app/_hub/kong-inc/opentelemetry/overview/_index.md
The request documented to configure the Opentelemetry plugin is invalid because it uses a dot `.` in the name of the attribute, which is interpreted as a field separator in the curl form data.
This updates the documentation without changing the example, using JSON instead of form data to allow passing a name that includes a dot.
Preview link:
=> fix(opentelemetry): address invalid request to set up plugin

app/_src/kubernetes-ingress-controller/guides/requests/rewrite-host.md
Ported content to 3.0
GWAPI tab first and the second tab for ingress
Preview link: https://deploy-preview-6408--kongdocs.netlify.app/kubernetes-ingress-controller/latest/guides/requests/rewrite-host/
=> fix: Rewrite hosts and Paths

app/_data/docs_nav_kic_3.0.x.yml, app/_includes/snippets/gateway-operator/install_with_kubectl_all_controllers.md, app/_src/gateway-operator/get-started/kic/install.md, app/_src/kubernetes-ingress-controller/get-started/index.md, app/_src/kubernetes-ingress-controller/install/gateway-operator.md, app/_src/kubernetes-ingress-controller/install/helm.md
Add KIC 3.0 Helm + KGO install instructions
Preview link: 
* https://deploy-preview-6421--kongdocs.netlify.app/kubernetes-ingress-controller/latest/install/helm/
* https://deploy-preview-6421--kongdocs.netlify.app/kubernetes-ingress-controller/latest/install/gateway-operator/
=> Add KIC 3.0 install methods

app/gateway/changelog.md
Copied the text written in 3.0.0.0 changelog entry for the aws-lambda plugin to when it was introduced in 2.8.1.3 for consistency. Makes it easier to find the versions in which those properties were added for `aws_assume_role_arn` for example.
N/A
=> Fix: 2.8.1.3 changelog entry for aws-lambda plugin changes to match 3.0.0.0

app/_hub/kong-inc/aws-lambda/_changelog.md
Extending the wording from the Gateway changelog in 3.0.0.0 and 2.8.1.3 to the plugin changelog for aws-lambda for 2.8.1.3 for consistency. 
N/A
=> Fix: Align wording of 2.8.1.3 update for `aws_assume_role_arn` property

.github/workflows/sync-kuma-submodule.yml
Adds the `skip-changelog` and `review:general` labels to this changelog so that the PR's from this action won't be picked up in the auto changelog.
=> Add labels to the PR created in sync-kuma-submodule.yml

app/_src/gateway/production/sizing-guidelines.md
Add section about `Dedicated Config Processing`
Fixes: https://konghq.atlassian.net/browse/KAG-2778
=> feat: dedicated config processing

app/_assets/stylesheets/header-v2.less, app/_includes/nav-v2.html
The input was hidden on small screens but the search icon was still there which was confusing.
This adds the input back and adjusts the results' dropdown accordingly.
I've also tried it on my phone using the QR code.
Preview link:
=> Fix search on mobile

app/_src/kic-v2/concepts/deployment.md
Remove KIC + Konnect warning
Preview link: /kubernetes-ingress-controller/latest/concepts/deployment/#konnect-integration
=> Remove Konnect beta warning from KIC

app/_hub/kong-inc/openid-connect/overview/_index.md
few typos and rewording of the openid-connect certificate-bound tokens feature (orig: https://github.com/Kong/docs.konghq.com/pull/6284)
Preview link: 
[KAG-2979](https://konghq.atlassian.net/browse/KAG-2979)
[KAG-2979]: https://konghq.atlassian.net/browse/KAG-2979?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(openid-connect): cert-bound tokens doc edits

app/_data/docs_nav_gateway_3.5.x.yml, app/_redirects, app/_src/gateway/how-kong-works/performance-testing.md, app/_src/gateway/reference/performance-testing-framework.md
The OSS performance testing framework is no longer in use and is not supported by Kong, as of 3.5.
This PR replaces https://github.com/Kong/docs.konghq.com/pull/6397. We don't want to delete the source file for the doc, as it's still relevant in earlier versions.
Preview link:
=> chore: Remove performance testing framework from 3.5

app/_data/docs_nav_kic_3.0.x.yml, app/_src/kubernetes-ingress-controller/guides/requests/customizing-load-balancing.md
Adds `Customizing load-balancing with KongUpstreamPolicy` guide as a replacement of `Using KongIngress resource` guide.
```
kubectl apply -f https://raw.githubusercontent.com/Kong/kubernetes-ingress-controller/c1849885d5077c25c3cb33707215b4c1a87a7bcb/config/crd/bases/configuration.konghq.com_kongupstreampolicies.yaml
```
=> chore: add customizing load-balancing with KongUpstreamPolicy

app/_src/kubernetes-ingress-controller/guides/migrate/credential-kongcredtype-label.md, app/_src/kubernetes-ingress-controller/guides/migrate/ingress-to-gateway.md, app/_src/kubernetes-ingress-controller/guides/migrate/kongingress.md, app/_src/kubernetes-ingress-controller/upgrade/kic.md
Add an upgrade guide for KIC 3.0
Preview link: https://deploy-preview-6369--kongdocs.netlify.app/kubernetes-ingress-controller/latest/upgrade/kic/
=> chore: add KIC 3 upgrade guide

app/_data/tables/support/gateway/versions/35.yml, app/_src/gateway/support/index.md
Setting the EOL date for 3.5.
Also removing Postgres 9-11 (was already removed from 3.4) and setting the EOL date for Debian 10 at June 2024, as that EOL is earlier than the general release EOL.
Preview link:
=> Chore: Support matrix updates for Gateway 3.5

app/_src/gateway/plugin-development/custom-logic.md, app/_src/gateway/plugin-development/entities-cache.md
In Kong 3.5 we added `plugin:configure` as an additional handler that is called each time there is a change in Kong plugin iterator.
This commit adds documentation for it.
See:
- https://konghq.atlassian.net/browse/KAG-2931
- https://github.com/Kong/kong/pull/11703
- https://github.com/Kong/kong-ee/pull/6795
- https://konghq.atlassian.net/browse/KAG-2672
- https://konghq.atlassian.net/browse/KAG-2678
- https://konghq.atlassian.net/browse/KAG-2679
Preview link:
=> docs(plugins): add docs about `plugin:configure` handler

app/_src/gateway/upgrade-v2.md
We needed to update the upgrade path table with the 3.5 upgrade paths. 
Preview link:
=> Chore: update upgrade paths for Gateway 3.5

app/_data/docs_nav_kic_3.0.x.yml, app/_includes/md/kic/add-certificate.md, app/_src/kic-v2/guides/using-ingress-with-grpc.md, app/_src/kubernetes-ingress-controller/gateway-api.md, app/_src/kubernetes-ingress-controller/guides/services/grpc.md
Add GRPC guide to KIC 3.0 docs 
Preview link: See guides->services->grpc
=> KIC: Fix GRPC Guide

app/_data/tables/support/gateway/versions/35.yml
InfluxDB is not supported in 3.5, since Vitals is deprecated.
Preview link: https://deploy-preview-6491--kongdocs.netlify.app/gateway/latest/support/third-party/
=> chore: Remove influxdb from list of supported 3rd party dependencies in 3.5

app/gateway/changelog.md
We found two changelog entries should be removed from `3.5.0.0`.
CC @AndyZhang0707 
Preview link:
=> [URGENT] Remove 2 unwanted changelog entries from 3.5.0.0

app/_layouts/extension.html
Plugins labelled as `premium` don't have the "Try in Konnect" banner. This PR fixes that.
Preview link:
=> Fix: Banner for using plugins in konnect

app/konnect/gateway-manager/index.md
Updating gateway manager doc page since Plus and Enterprise users can create multiple control planes. This was new as part of KOD1 for API Summit.
Preview link:
=> Update gw manager docs

app/gateway/changelog.md
Consolidate the lua-resty-aws version bump entries into one as both entries happened in the same release.
This is for Gateway Enterprise 3.5.0.0 changelog.
Preview link:
=> docs(changelog): consolidate the lua-resty-aws version bump changelog

app/_src/kubernetes-ingress-controller/guides/services/grpc.md
Improve documentation for gRPC support in KIC
- as long as https://github.com/Kong/kubernetes-ingress-controller/issues/4273 is not resolved only gRPC over HTTPS is supported, so mention it
- remove the redundant annotation `konghq.com/protocol: grpcs` from the service, because in [examples/gateway-grpcroute.yaml](https://github.com/Kong/kubernetes-ingress-controller/blob/314951c3279dcd38cb7de7e53f71969379a0340a/examples/gateway-grpcroute.yaml#L5-L17) it's not specified and that configuration is tested in KIC CI so it works
Preview link: https://deploy-preview-6497--kongdocs.netlify.app/kubernetes-ingress-controller/latest/guides/services/grpc/#overview
=> chore: improve docs about support of gRPC in KIC

app/_includes/md/kic/konnect-setup.md, app/_src/kubernetes-ingress-controller/install/cloud/aks.md, app/_src/kubernetes-ingress-controller/install/cloud/eks.md, app/_src/kubernetes-ingress-controller/install/cloud/gke.md
Make it clear that KIC install instructions are _not_ for Konnect + redirect to Gateway Manager as needed
Preview link: /kubernetes-ingress-controller/latest/install/cloud/gke/
=> Redirect to KIC in Konnect on cloud install pages

Gemfile, Gemfile.lock
Adds `ruby-lsp` gem to the `development` group. Required for vscode-ruby to run correctly
=> Add ruby-lsp to Gemfile

app/_src/gateway/install/docker/build-custom-images.md
Fix custom Docker build instructions. `openresty` is now symlinked in the package, which caused the `Dockerfile` provided to fail.
Preview link: /gateway/latest/install/docker/build-custom-images/
=> Fix custom Docker build instructions

app/gateway/changelog.md
As Dev Portal is deprecated on Gateway going forward, we should list any fixes for it in the changelog.
Fixes requested by PM.
Preview link:
=> Fix: Remove dev portal entries from 3.5 changelog

app/konnect/gateway-manager/data-plane-nodes/renew-certificates.md
Modified curl example for Konnect:
- needed to add double-quotes to properly expand $CERT envvar (curl was giving an error)
https://superuser.com/questions/835587/how-to-include-environment-variable-in-bash-line-curl#:~:text=Inside%20single%2Dquotes%2C%20the%20shell,completed%22'.%22%7D'
- Included the Authorization header in the Konnect request
Preview link:
=> Update Konnect curl request in renew-certificates.md

app/_hub/kong-inc/application-registration/versions.yml
On-prem Dev Portal docs have been removed from Gateway 3.5. Along with that, we should set 3.4 as the latest version for the App Registration plugin, as it can only be used with on-prem Dev Portal.
Preview link:
=> Update: Set max version for app registration plugin

app/_src/gateway/production/deployment-topologies/db-less-and-declarative-config.md
Adding a section for the compatibility warning while using Kong Manager with Kong under DB-less mode.
Preview link: 
Fixes KAG-3038
=> feat(dbless): add compatibility warning for Kong Manager

app/_assets/javascripts/modal.js
Fixing a typo that Lighthouse is complaining about: 
Preview link:
=> fix: Typo on aria attribute in modal

.github/workflows/scheduled-broken-link-checker.yml, app/moved_urls.yml
Just ran it locally and got this:
```json
[
{
"page": "http://localhost:8888/konnect/gateway-manager/kic/",
"text": "Kong Ingress Controller Deployment",
"target": "http://localhost:8888/kubernetes-ingress-controller/latest/concepts/deployment/",
"reason": "HTTP_404"
},
{
"page": "http://localhost:8888/konnect/gateway-manager/kic/",
"text": "Using Kong Gateway Enterprise",
"target": "http://localhost:8888/kubernetes-ingress-controller/latest/guides/choose-gateway-image/",
"reason": "HTTP_404"
},
{
"page": "http://localhost:8888/gateway/latest/how-kong-works/routing-traffic/",
"text": "Router Expressions language",
"target": "http://localhost:8888/gateway/latest/reference/router-expressions-language/",
"reason": "HTTP_404"
},
{
"page": …
```
=> Fix broken links

app/_assets/javascripts/components/Sidebar.vue, app/_assets/javascripts/components/Spec.vue, app/_assets/javascripts/services/api.js, package-lock.json, tools/konnect-oas-data-generator/package-lock.json
Bring back deps update.
Update code to match latest sdk-portal-api deps, it fixes the issue with the API pages.
Actually, any API spec link should work.
Oh and btw, they now work in preview apps 🎉 
[Preview link](https://deploy-preview-6562--kongdocs.netlify.app/gateway/api/admin-ee/latest/)
=> Bump deps after revert

app/_src/deck/faqs.md, app/_src/gateway/production/deployment-topologies/db-less-and-declarative-config.md
Update the URL of the deck JSON schema. This now resides in another repository.
=> fix: update deck schema URL

app/_src/gateway/licenses/examples.md
We've had a few customer support cases where customers are confused by a null response from the /licenses endpoint when they're not actually using the Admin API to load the license in the first place which is a requirement for this to work properly. When using an environment variable to set the license instead, the /licenses endpoint will not work for listing licenses. This PR is to make this clearer in the documentation.
N/A
=> Update: Listing a license requires license added via Admin API to begin with

README.md
Adding some tips for resolving the encoding errors while executing the `make run` command.
I usually encounter this issue because I don't have `LANG` or `LC_ALL` set in my environment for each shell session.
Preview link:
=> chore: add tips for encoding errors

app/_data/tables/support/gateway/versions/34.yml, app/_data/tables/support/gateway/versions/35.yml
We have tests running on different postgres versions including the latest, which is 16.1. We run these tests for 3.5.0.0 version and for 3.4.0.0. The docs site doesn't list postgres 16 as a supported version, so this PR updates the support tables.
Preview link:
=> chore: Add postgres 16 as a supported version for Kong Gateway 3.4 and 3.5

app/_src/gateway/kong-enterprise/secrets-management/backends/index.md
The vault backends list is missing Azure key vault, which was added in 3.5.
Preview link:
=> fix: Add missing Azure vault table entry

app/_hub/TheLEGOGroup/aws-request-signing/_metadata.yml, app/_hub/amberflo/kong-plugin-amberflo/_metadata.yml, app/_hub/datadome/kong-plugin-datadome/_metadata.yml, app/_hub/imperva/imp-appsec-connector/_metadata.yml, app/_hub/moesif/kong-plugin-moesif/_metadata.yml, app/_hub/nonamesecurity/nonamesecurity-kongprevention/_metadata.yml, app/_hub/nonamesecurity/nonamesecurity-kongtrafficsource/_metadata.yml, app/_hub/optum/kong-response-size-limiting/_metadata.yml, app/_hub/optum/kong-service-virtualization/_metadata.yml, app/_hub/optum/kong-spec-expose/_metadata.yml, app/_hub/optum/kong-splunk-log/_metadata.yml, app/_hub/optum/kong-upstream-jwt/_metadata.yml, app/_hub/salt/salt/_metadata.yml
Keep expecting to find third-party plugins by filtering on publisher name, but that doesn't work. 
Adding 3rd party plugin publisher names as search aliases, as well as literal plugin names (eg `aws-request-signing`). 
Also updating the supported versions for Optum plugins. Versions are based on the plugins' source code repos.
Test the new search terms in the plugin hub filter box.
=> chore: Add missing search aliases and supported versions for 3rd party plugins

app/_src/deck/index.md
Set `if_version` on links to the APIOps decK guide, as it was added with 1.24.x. 
Preview link:
=> fix: Broken links to APIOps guide

app/_src/gateway/kong-enterprise/secrets-management/backends/aws-sm.md, app/_src/gateway/kong-enterprise/secrets-management/backends/hashicorp-vault.md, app/_src/gateway/kong-enterprise/secrets-management/reference-format.md
The PR adds the missing part of Kong Gateway Vault's secrets versioning description.
Gateway's vault supports accessing versioning secrets by specifying version number as a fragment in the vault reference URL.
Note that this is not a new feature added recently, it exists long time ago, only the doc part is missing.
https://konghq.atlassian.net/browse/FTI-5168
Preview link:
=> fix: add the missing part of kong gateway vault's secrets versioning description

app/_hub/kong-inc/rate-limiting/overview/_index.md
Adds clarification that the basic rate-limiting plugin does not support Redis Cluster mode.
[Context](https://github.com/Kong/kong/issues/11846#issuecomment-1810350623)
=> docs: clarify on rate-limit redis cluster support

app/_src/gateway-operator/get-started/kic/install.md
Update version of GWAPI CRDs, mention standard and experimental.
**BLOCKED BY**
- https://github.com/Kong/docs.konghq.com/pull/6544
Preview link: https://deploy-preview-6585--kongdocs.netlify.app/gateway-operator/latest/get-started/kic/install/
=> kgo: enhance installation page

app/_src/kubernetes-ingress-controller/guides/services/grpc.md
closes https://github.com/Kong/kubernetes-ingress-controller/issues/5134
For HTTPRoute (support was added in https://github.com/Kong/kubernetes-ingress-controller/pull/5128, so KIC >= 3.1.0 wii support it). For ingress, it works for older versions too
Preview link: https://deploy-preview-6567--kongdocs.netlify.app/kubernetes-ingress-controller/latest/guides/services/grpc/
=> kic: update and extend gRPC how-to

README.md
Updates to the README:
* Added `make install-prerequisites` to the setup instructions for the docs site.
* Moved `cp .env.example .env` into the same section, since this is needed for the site to run.
* Removed `git submodule update` since it's part of `make install` now.
To do:
* Figure out why `foreman` doesn't get installed - it's included in the gemfile, so it should be. Otherwise, add a troubleshooting section to install foreman.
Preview link:
=> chore: Update readme to include make install-prerequisites

app/_includes/head.html
As part of SEO work, pages are getting `description` keys added to them for metadata.
Adjusting the way the metadescription gets generated for each page to include this option. 
If a page-specific description exists, it takes priority; otherwise it still falls back to the generic site description.
Check the meta description for the https://deploy-preview-6591--kongdocs.netlify.app/contributing/community/ page (open the page in dev tools, expand the `<head>` tag).
You should see:
```
<meta name="description" content="Join the Kong Documentation Contribution Community to collaborate, learn, and contribute to open source projects. Start your journey with Kong today!">
```
=> Chore: Assign metadescriptions to pages by `description`

app/_hub/kong-inc/tls-metadata-headers/_metadata.yml
Reported by Fero. This is a DP only plugin which _is_ compatible with Konnect
Preview link: /hub/kong-inc/tls-metadata-headers/
=> tls-metadata-headers is compatible with Konnect

app/_data/tables/support/gateway/third-party.yml, app/_data/tables/support/gateway/versions/35.yml, app/_src/gateway/kong-enterprise/index.md
Support for Azure Key Vault as a secrets backend was added in Gateway 3.5. This PR adds references to this support in the 3rd party tools page and Gateway Enterprise index.
Preview link:
=> fix: add missing references to Azure Key Vault

app/_src/gateway/production/environment-variables.md, app/_src/gateway/production/kong-conf.md, app/_src/gateway/reference/configuration.md
There are no links to the kong.conf reference from the kong.conf guides, so users are having trouble finding the reference.
Adding links to fix that.
Preview link:
=> Fix: Add cross-links between kong.conf guides and reference

app/_src/gateway/get-started/services-and-routes.md
Got 404 when visiting the URL shown in the document. Found the correct page after clicking "Gateway Services" and it turned out the correct URL didn't include the "/default" part. 
Preview link:
=> fix: fix URL of services page

app/konnect/getting-started/publish-service.md
The step-by-step process is clear; however, one critical step was missing - guiding users on how to publish the API documentation and a dynamic API reference to the public portal. To address this issue, I am adding an extra step that instructs users on how to publish their API Product and version documentation.
Preview link: https://docs.konghq.com/konnect/getting-started/publish-service/
=> Add a step to publish API Product and version docs

.github/styles/kong/dictionary.txt, app/_hub/kong-inc/openid-connect/overview/_index.md
Based on questions in slack, the example in docs does not mention how the plugin works with the access token specified as query string. The plugin uses `access_token` as the default query string parameter name. This is not specified anywhere. Hence this example shows how to use the plugin with the query string param as option instead of header
Preview link:
=> Update: OIDC plugin example for using an access token

app/_includes/md/deck-global-flags.md, app/_src/deck/guides/konnect.md
Remove references to username/password auth for latest versions of decK in order to promote usage of tokens instead of passwords for authentication.
Preview link:
=> doc(decK): Update authentication instructions

app/_src/deck/faqs.md, app/_src/gateway/production/deployment-topologies/db-less-and-declarative-config.md
decK is not meant for DB-less mode, since it uses the Admin API to manage configs. There was some inaccurate info in the docs about this, suggesting that decK _can_ be used for DB-less. Removing that and adding a note on the difference between declarative and decK config.
Preview link:
=> Fix: Remove inaccurate note and links about decK in db-less mode doc

app/_includes/md/gateway/db-less-upgrade.md, app/_includes/md/gateway/hybrid-upgrade.md, app/_includes/md/gateway/upgrade-backup.md, app/_src/gateway/upgrade/index.md, app/_src/gateway/upgrade/lts-upgrade.md
When using page variables in include, you're supposed to declare them as `include.kong_version` instead of `page.kong_version`. 
Forgot to convert these variables when I turned the reused sections into includes, so the links aren't getting cached correctly.
Preview link:
=> Fix: Upgrade guide include links

app/_plugins/generators/oas_definition/error_page.rb, app/_plugins/generators/oas_definition/product.rb, app/_plugins/generators/seo/index_entry/oas_page.rb
Adds support for per-API errors in the OpenAPI specs. If a spec contains an `x-errors` key and `"generateErrorsPage": true` is set in `konnect_oas_data.json` then a page will be generated from the errors in the docs. This allows us to return a URL in the API which links to docs e.g. https://kongapi.info/api-products/solar-error would link to /konnect/api/api-products/latest/errors/#solar-error
```yaml
x-errors:
example-error:
description: The provided API product does not contain a "foobar"
resolution: Send the "beebaz" parameter with a key starting with "ABC123"
link:
text: View API reference
url: /api/redact#transaction
solar-error:
description: The sun has come too close to the earth and your request could not be served
resolution: Wait until the sun moves away
create-rate-limit: …
```
=> Add x-errors support to OAS docs

app/_assets/javascripts/views/SpecView.vue
[Jira ticket](https://konghq.atlassian.net/browse/DOCU-3581)
Add link to `Catalog` to OAS pages.
OAS pages now render a link back to the catalog
Preview link: 
* https://deploy-preview-6643--kongdocs.netlify.app/konnect/api/runtime-groups-configuration/latest/
* https://deploy-preview-6643--kongdocs.netlify.app/konnect/api/portal-rbac/latest/
* https://deploy-preview-6643--kongdocs.netlify.app/gateway/api/admin-ee/latest/
=> Add link to `Catalog` to OAS pages

app/_src/kic-v2/faq.md
Based on information gathered from 
- https://github.com/Kong/charts/pull/269
- https://github.com/Kong/kubernetes-ingress-controller/issues/682
- https://kubernetes.github.io/ingress-nginx/deploy/baremetal/#via-the-host-network
document when and how deploy KIC as DaemonSet, update of Helm chart docs is needed to, see and review https://github.com/Kong/charts/pull/918
Closes https://github.com/Kong/kubernetes-ingress-controller/issues/4728
Preview link:
=> Document in FAQ running KIC as DaemonSet 

app/_src/gateway/production/monitoring/readiness-check.md
Port 8001 is used in the example curl command, but port 8100 is the one used in the rest of the documentation. Changing curl port to 8100.
Preview link:
=> Make port 8100 consistent in all examples

app/_layouts/extension.html
The `page.name` does not contain the plugin name to add to `KONG_PLUGINS` when enabling non-bundled plugins. `extn_slug` contains the correct name
Preview link: /hub/kong-inc/app-dynamics/
=> Use extn_slug when setting name for non-bundled plugins

app/assets/gateway-operator/v1.1.0/all_controllers.yaml
Following https://docs.konghq.com/gateway-operator/1.1.x/get-started/kic/install/ leads to a broken setup
Gateway stuck
```yaml
...
Status:
Conditions:
Last Transition Time:  1970-01-01T00:00:00Z
Message:               Waiting for controller
Reason:                Pending
Status:                Unknown
Type:                  Accepted
```
and in KGO logs
```log
...
{"level":"error","ts":"2023-12-18T14:56:15Z","msg":"Reconciler error","controller":"gatewayclass","controllerGroup":"gateway.networking.k8s.io","controllerKind":"GatewayClass","GatewayClass":{"name":"kong"},"namespace":"","name":"kong","reconcileID":"3597a449-5190-4fec-8f71-a52bcca235fc","error":"failed updating GatewayClass: gatewayclasses.gateway.networking.k8s.io \"kong\" is forbidden: User …
```
=> fix(kgo): proper rbac for 1.1.X in KIC Get Started

app/_assets/stylesheets/pages/landing-oas.less, app/_includes/oas/card.html, app/_layouts/oas/index.html, app/_plugins/drops/oas/product.rb
Related [Jira ticket](https://konghq.atlassian.net/browse/DOCU-3608)
Add a `Deprecated` section to the OAS Catalog page
Preview link:
=> Add a `Deprecated` section to the OAS Catalog page

app/_includes/sidebar/item.html
Quick follow-up to https://github.com/Kong/docs.konghq.com/pull/6657
Adds `aria-labels` to the buttons
Preview link:
=> Add aria-labels to buttons

app/contributing/variables.md
I noticed while reviewing https://github.com/Kong/docs.konghq.com/pull/6224 that we have Mesh and KIC product variables, so adding those to the contribution guide. 
Preview link: https://deploy-preview-6676--kongdocs.netlify.app/contributing/variables/
=> (chore) Add Mesh and KIC variables

app/_data/kong_versions.yml
I missed adding these with DOCU-3598/3.4.3.1 changelog
Bumping versions to 3.4.3 and 3.4.3.1
Preview link:
=> (chore) Update kong_versions.yml

app/_src/gateway/production/debug-request.md
The header `X-Kong-Request-Debug-Token` of the request-debug feature of Gateway is missing.
_[KAG-3365]_
Preview link: 
[KAG-3365]: https://konghq.atlassian.net/browse/KAG-3365?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: add missing `X-Kong-Request-Debug-Token` header of request-debug docs

app/_src/kic-v2/references/cli-arguments-2.12.x.md, app/_src/kic-v2/references/custom-resources-2.12.x.md
Auto-update the references for KIC v2.12.x
Preview link: 
* https://deploy-preview-6685--kongdocs.netlify.app/kubernetes-ingress-controller/2.12.x/references/custom-resources/
* https://deploy-preview-6685--kongdocs.netlify.app/kubernetes-ingress-controller/2.12.x/references/cli-arguments/
=> chore(KIC): update references for v2.12.x

app/_src/gateway/production/monitoring/readiness-check.md
Preview link: https://deploy-preview-6690--kongdocs.netlify.app/gateway/latest/production/monitoring/readiness-check/
=> (chore) correct port number in readiness check

app/gateway/changelog.md
Added in Enterprise features / fixes for version 3.4.3.1 that was recently discovered missing in the release notes.
Also fixed up a couple of other minor issues / formatting inconsistencies.
Related links:
* https://konghq.atlassian.net/browse/FTI-5570?focusedCommentId=120558
* https://github.com/Kong/kong-ee/blob/next/3.4.x.x/changelog/3.4.3.1/3.4.3.1.md
Preview link:
=> Fix: Add missing changelog entries for 3.4.3.1 and more

app/_src/gateway/index.md
`if_version` tags aren't spaced out correctly, so they're causing the following issues:
3.5:
3.4 and earlier:
Fixing by splitting out `if_version` tags, so that they don't encompass part of a still-existing section. The previous approach is harder to maintain + causes these spacing issues.
Preview link: check the Gateway overview page on 3.5 and 3.4.
=> Fix: Spacing on gateway overview page

app/_data/docs_nav_kic_3.0.x.yml, app/_src/kubernetes-ingress-controller/guides/security/plugin-secrets.md
Add a guide that shows how to use `configFrom` when configuring a plugin config from k8s secrets
Preview link: /kubernetes-ingress-controller/latest/guides/security/plugin-secrets/
=> Add KIC configFrom guide

.github/renovate.json
One dependency is shared with Kuma and lives in the submodule. This causes Renovate to fail to update our ruby dependencies because the submodules aren't cloned by default. Setting this config to true should fix the issue
Preview link:
=> Set `cloneSubmodules` to true in renovate's config

app/_data/docs_nav_kic_3.0.x.yml, app/_src/kubernetes-ingress-controller/guides/custom-class/internal-external.md
Add a guide that explains how to run internal/external ingresses using KIC
Preview link: /kubernetes-ingress-controller/latest/guides/custom-class/internal-external/
=> Add internal/external traffic KIC guide

app/_src/kubernetes-ingress-controller/guides/services/tls.md
Fix the Passthrough/Terminate examples for TLS with Gateway API + KIC
Preview link: /kubernetes-ingress-controller/latest/guides/services/tls/#tls-termination
=>  Fix KIC TLS Termination guide

app/_src/gateway/production/monitoring/prometheus.md
The link to prometheus plugin link was incorrect, hence fixed it
Preview link:
=> fix: fixed link to kong prometheus plugin reference

app/_data/docs_nav_kic_3.0.x.yml, app/_src/kubernetes-ingress-controller/guides/services/cross-namespace.md
For https://github.com/Kong/kubernetes-ingress-controller/issues/5154
Add a guide that covers using Gateway API resources with KIC across namespaces, including references to a Gateway from another namespace using listener allowedRoutes and references from an HTTPRoute to a Service in another namespace using a ReferenceGrant.
Preview link: https://deploy-preview-6677--kongdocs.netlify.app/kubernetes-ingress-controller/latest/guides/services/cross-namespace/
=> doc(kic) add reference grant guide

.github/workflows/sync-konnect-oas-data.yml
I noticed I have to manually add the label every time and I think this might fix that. I also added the `skip-changelog` label.
=> fix: Update label on generate OAS action

app/_src/gateway/upgrade/index.md
Reported on Slack, https://kongstrong.slack.com/archives/CDSTDSG9J/p1704899788300009
=> fix: broken link to support policy doc in the Gateway Upgrade guide

app/_src/kubernetes-ingress-controller/reference/faq/router.md
We haven't changed the default router flavor in the chart so we should not mention it in the docs. For now, the change of the default is on hold.
Preview link:
=> fix: do not mention default router change

app/_hub/kong-inc/oauth2/overview/_index.md
Change the wording on the Oauth2 plugin warning message. 
Preview link:
=> fix: small update to Oauth2 warning message

app/_redirects
Add missing redirect for Openshift install docs
Preview link:
=> Add redirect for Openshift install docs for Gateway

app/_includes/md/plugins-hub/log_custom_fields_by_lua.md
The `custom_fields_by_lua` config field in logging plugins affects all logging plugins, not just the one you configure it for. Adding this info and a workaround to the plugin docs. 
Appears in all logging plugins. For example: https://deploy-preview-6741--kongdocs.netlify.app/hub/kong-inc/file-log/#plugin-precedence-and-managing-fields
=> Update: custom_fields_by_lua precedence in logging plugins

app/_plugins/generators/plugin_single_source/pages/base.rb, app/_plugins/generators/plugin_single_source/plugin/pages_builder.rb, app/_plugins/generators/plugin_single_source/plugin/sidenav.rb, spec/app/_plugins/generators/plugin_single_source/pages/how_to_spec.rb, spec/fixtures/app/_hub/kong-inc/jwt-signer/how-to/_index.md, spec/fixtures/app/_hub/kong-inc/jwt-signer/how-to/nested/_tutorial.md, spec/templates/plugin_with_versions_spec.rb
Pull in Fabian's how-to nesting edits.
Preview link:
=> chore: Add nested sidenav items to plugin

app/_plugins/generators/plugin_single_source/plugin/sidenav.rb, spec/templates/plugin_with_versions_spec.rb
[Plugin Hub] Position nested sidenav subitems before links
[Preview link](https://deploy-preview-6767--kongdocs.netlify.app/hub/kong-inc/openid-connect/how-to/basic-example/)
=> [Plugin Hub] Position nested sidenav subitems before links

app/_src/kubernetes-ingress-controller/guides/services/tls.md
The `parentRef` for TLS HTTPRoutes was incorrectly set to `kong` rather than `example-gateway` as the guide expected. Reported by @liyangau.
Preview link: /kubernetes-ingress-controller/latest/guides/services/tls/
=> Fix TLS parentRef when using Gateway API

app/_hub/kong-inc/app-dynamics/overview/_index.md
Document missing certificate environment variables for AppDynamics, [added in 3.4.3.3.](https://docs.konghq.com/gateway/changelog/#plugins-4)
Values only appear in the 3.4.x version table. Will add to 3.5 when the patch is released as well.
Also adding a conditional for 3.6, which will remain hidden until we have a 3.6 version.
Preview link:
=> Feat: AppDynamics certificate env variables

app/_assets/stylesheets/index.less, app/_assets/stylesheets/roboto-fonts.css, app/_includes/head.html
To enhance the load performance in certain scenarios, we bundle the Roboto fonts stylesheet in app assets instead of fetching it from `fonts.googleapis.com` directly.
This patch is part of the DOCU-3037
The font file hosted on `fonts.gstatic.com` is guaranteed to be existed across the fonts version update so it's safe to self-host a snapshot of the stylesheet.
Preview link:
=> Self-host Google Fonts Stylesheet

app/_includes/footer.html, app/_includes/head.html
It seems that we don't have the subscription form anymore, so it's safe to remove the unused reCaptcha script
This patch is part of the DOCU-3037
Preview link:
=> Remove unused google reCaptcha script

app/_data/docs_nav_kic_3.1.x.yml, app/_data/kong_versions.yml
Bootstrap KIC 3.1 docs using the new `label: dev` functionality
Preview link: The dev link should show in previews, and will show in production
=> Bootstrap KIC 3.1 docs

app/_assets/stylesheets/roboto-fonts.css
Add `font-display: swap` to fonts to ensure that the text remains visible during webfont load
Preview link:
=> Add `font-display: swap` 

api-specs/Gateway-EE/3.5/kong-ee-3.5.yaml
Add RBAC auth to the Kong Admin EE spec.
https://konghq.atlassian.net/browse/DOCU-180
Preview link:
=> Update: Add admin token auth to Gateway EE spec [skip ci]

app/_data/installation/gateway.yml
With 3.5 having shipped, and 3.6 just around the corner, thought I'd get the jump on pre-creating the 3.7 Cloudsmith repos.
Sister PR to: https://github.com/Kong/gateway-docker-compose-generator/pull/133
I don't **believe** adding this now (to main) should cause any issues... @mheap ?
Preview link: https://deploy-preview-6776--kongdocs.netlify.app/
=> Add gateway-37 repo keys

api-specs/Gateway-OSS/3.4/kong-oss-3.4.yaml, api-specs/Gateway-OSS/3.5/kong-oss-3.5.yaml
Add WebAssembly filter chains to Gateway OSS 3.4 and 3.5 OpenAPI specs
JIRA: KAG-1885
=> Add WebAssembly filter chains to Gateway OSS 3.4 and 3.5 OpenAPI specs

tools/install-tester/config/jobs.yaml, tools/install-tester/config/setup.yaml, tools/install-tester/index.js
Test RHEL 2.x installation topics on el7 rather than el9
=> Add explicit RHEL7 and RHEL9 test targets

app/_hub/kong-inc/openid-connect/how-to/third-party/_auth0.md, app/_hub/kong-inc/openid-connect/how-to/third-party/_azure-ad.md, app/_hub/kong-inc/openid-connect/how-to/third-party/_curity.md, app/_hub/kong-inc/openid-connect/how-to/third-party/_google.md, app/_hub/kong-inc/openid-connect/how-to/third-party/_okta.md
The OIDC Okta guide incorrectly references `config.scopes_required` when it's actually configuring `config.scopes`.
Fixing that + some broken/outdated links + Dev Portal info that should be behind a conditional tag.
Also fixing the same links in the rest of the OIDC 3rd party guides.
https://konghq.atlassian.net/browse/DOCU-2277
Preview link:
=> Fix: Use config.scopes instead of config.scopes_required in OIDC okta guide

app/_src/gateway/kong-enterprise/dev-portal/authentication/okta-config.md, app/gateway/2.6.x/developer-portal/administration/application-registration/okta-config.md, app/gateway/2.7.x/developer-portal/administration/application-registration/okta-config.md, app/gateway/2.8.x/developer-portal/administration/application-registration/okta-config.md
Fix okta config doc bug, where the consumer claim field was listed as needing an application ID, but actually needs the name of the field that _contains_ the application ID.
https://konghq.atlassian.net/browse/DOCU-1456
Preview link:
=> Fix: Incorrect value listed for OIDC consumer claim field

app/_plugins/generators/seo/index_entry_builder.rb, app/_plugins/generators/utils/canonical_url.rb, spec/app/_plugins/generators/seo/index_entry_builder_spec.rb, spec/app/_plugins/generators/utils/canonical_url_spec.rb
There were two issues here:
* the canonical url generator didn't check if the url had an extension
* it was also modifying the provided url
Preview link:
=> Fix sitemap generation

.github/PULL_REQUEST_TEMPLATE.md
Since we no longer user version branches, we don't need to have a checklist item for them. Changing the PR checklist item to conditionals instead of version branches.
=> Update: PR template update for version conditionals [skip ci]

app/_assets/javascripts/app.js, app/_assets/stylesheets/badges.less, app/_includes/hub_cards.html, app/_includes/plugins/badges.html, app/_layouts/plugins/show.html, app/_plugins/drops/plugins/badges.rb
Adding OSS badges to plugins upon request. 
Adjusting the colours of the old OSS badge so it doesn't look like Insomnia + matches the other badges better.
Preview link: 
For example, if this change is for an upcoming 3.6 release, surround your change in `{% if_version gte:3.6.x %} <content> {% endif_version %}` tags (or `if_plugin_version` tags for plugins).
=> Feat: OSS badges

app/_src/gateway/production/deployment-topologies/db-less-and-declarative-config.md
Corrected the command to send the config to the Gateway. It was using a GET instead of POST and when using form-urlencoded data (--data) it throws a 400 error.  
{"message":"declarative config is invalid: {error=\"failed parsing declarative configuration: 1:1: found character that cannot start any token\"}","name":"invalid declarative configuration","code":14,"fields":{"error":"failed parsing declarative configuration: 1:1: found character that cannot start any token"}}
This was changed to use multipart/form-data (--form)
Preview link:
=> Fix: Incorrect request format in DB-less and declarative config doc

app/_src/kubernetes-ingress-controller/install/helm.md
The KIC Helm install docs showed how to customise the image by using the nightly KIC image. This confused some users who actually tried to use the nightly image in a non-test environment.
Preview link: [/kubernetes-ingress-controller/3.0.x/install/helm/](https://deploy-preview-6842--kongdocs.netlify.app/kubernetes-ingress-controller/3.0.x/install/helm/)
=> KIC: Use standard repository in Helm example instructions

app/_src/gateway/kong-enterprise/secrets-management/backends/aws-sm.md, app/_src/gateway/kong-enterprise/secrets-management/backends/gcp-sm.md
This PR adds a notice in the AWS/GCP vault backend doc page, to remind user to trust system ca-certificates store so that SSL certificate returned by those cloud providers are being trusted by kong.
https://konghq.atlassian.net/browse/FTI-5700
Preview link:
=> chore: add notice for trusting vault backend's ssl certificate

app/_src/kubernetes-ingress-controller/concepts/gateway-api.md
Adds an explanation of `--publish-service` vs. `konghq.com/publish-service` Gateway's annotation relation.
Part of https://github.com/Kong/kubernetes-ingress-controller/issues/5328.
Preview link: 
For example, if this change is for an upcoming 3.6 release, surround your change in `{% if_version gte:3.6.x %} <content> {% endif_version %}` tags (or `if_plugin_version` tags for plugins).
=> kic: add explanation for Gateway's publish service

app/_src/gateway/migrate-cassandra-to-postgres.md, app/_src/gateway/upgrade/index.md
I added the 3.6 upgrade path table for the upcoming release. I also fixed a few errors that aren't related to the release I noticed as I was going through the docs.
DOCU-3633
Preview link: https://deploy-preview-6844--kongdocs.netlify.app/gateway/dev/upgrade/#guaranteed-upgrade-paths
=> chore: Add 3.6 upgrade path table

.github/PULL_REQUEST_TEMPLATE.md
Last update had the formatting a bit wrong, plus the conditionals apply to both unreleased and released versions.
Also adding a bit more info on version keys, as I keep seeing contributors getting confused about them.
Here's how it looks with this update:
https://github.com/Kong/docs.konghq.com/blob/chore/pr-template/.github/PULL_REQUEST_TEMPLATE.md
For example, if this change is for an upcoming 3.6 release, surround your change in `{% if_version gte:3.6.x %} <content> {% endif_version %}` tags (or `if_plugin_version` tags for plugins).
=> chore: Update PR template again [skip ci]

app/_plugins/drops/releases_dropdown.rb, app/_plugins/hooks/pages_urls_hash.rb, app/_plugins/tags/page_exists.rb, spec/app/_plugins/drops/option_spec.rb
Quick and dirty solution that speeds up the rendering process locally by ~ 25%.
Keep a Set of the pages' urls, it has an Array's operations with a Hash's fast lookup.
When we released the `version_if` refactor we added 3mins+ to the  deploy time, this was mainly because we added 3 unreleased versions (kic, gateway and kgo).
Build times however are better with the change:
Preview link: 
You can …
=> Keep a Set of the pages' urls, it has an Array's operations

app/_plugins/generators/pages/productable.rb, app/_plugins/generators/pages/version_data.rb, app/_plugins/generators/versions.rb
Fixes a performance regression.
Deploys should be back to ~6-7 mins
=> Cache products and use them in generators

app/_src/gateway/admin-api/index_latest.md
Follow-up to markdown doc deprecation, we missed some anchor links + a bit of formatting. Also rephrased the DB-less section to stop repeating itself so much and to flow better.
Preview link: https://deploy-preview-6880--kongdocs.netlify.app/gateway/latest/admin-api/
=> Fix: Admin API markdown doc edits

app/_includes/plugins/priority_table.html, app/_plugins/tags/plugins_priority_table.rb, app/_src/gateway/plugin-development/custom-logic.md, app/konnect/reference/plugins.md
To generate the table, use the priorities defined in `app/_src/.repos/kong-plugins/app/data/priorities/`.
Add a new liquid tag `plugins_priority_table`, that takes `enterprise` or `oss` as an argument and uses the page's release (or latest for Konnect) to fetch the data. 
@lena-larionova I wasn't sure how we wanted to handle the case for `correlation-id`, so I added a separate table for it 🤷. From what I understand `free mode` uses the enterprise value and `oss` well, the oss one.
WDYT?
We could try to replicate the current behaviour too, it's a bit more complex though, but definitely doable.
[Preview link](https://deploy-preview-6866--kongdocs.netlify.app/gateway/latest/plugin-development/custom-logic/)
For example, if this change is for an upcoming 3.6 release, surround your change in …
=> Plugin priorities

app/_redirects
Removing redirects from anchor links like `/gateway/latest/admin-api/#vaults-object`. 
These redirects aren't supported and don't do anything.
Instead, we have a general redirect that covers anything under `/gateway/latest/admin-api/*`, and that should cover most situations. Old anchor links will just land at the top of `/gateway/latest/admin-api/`.
You can do the same for …
=> chore: Remove anchor link redirects

app/_data/docs_nav_deck_1.34.x.yml, app/_data/kong_versions.yml
Chore PR to set up an "unreleased" version for decK.
Why does it skip from 1.30.x to 1.34.x? Because three versions of decK have been released in the past two weeks, and we're not going to keep up with that. See https://github.com/Kong/deck/releases
Preview link: 
=> Chore: Add an unreleased/dev version for decK

app/_src/kubernetes-ingress-controller/reference/annotations.md
Documents KIC's `konghq.com/tags` annotation.
https://deploy-preview-6909--kongdocs.netlify.app/kubernetes-ingress-controller/latest/reference/annotations/
=> kic: document konghq.com/tags annotation

.github/workflows/auto-close-kong-issues.yml, .github/workflows/autogenerated-warning.yml, .github/workflows/check-links.yml, .github/workflows/ci-autofix.yml, .github/workflows/generate-changelog.yml, .github/workflows/linting.yml, .github/workflows/require-review-label.yml, .github/workflows/run-tests.yml, .github/workflows/sync-konnect-oas-data.yml, .github/workflows/sync-kuma-submodule.yml, .github/workflows/sync-submodules.yml
Setting timeouts for all jobs in our workflows that don't have a timeout. This is to prevent CI from setting the `${{ fromJSON(vars.GHA_DEFAULT_TIMEOUT) }}` timeout variable in our workflows (for example, see https://github.com/Kong/docs.konghq.com/pull/6888).
I set 10 minutes for any label checking jobs, and any jobs that normally take under 1 minute to run (see https://github.com/Kong/docs.konghq.com/actions). Anything longer, I set 30 minutes as the timeout.
* `lte:<version>` - less …
=> chore: Set explicit timeouts for all workflows [skip ci]

app/_hub/kong-inc/acl/_3.5.x/overview/_index.md, app/_hub/kong-inc/acl/overview/_index.md
ACL Doc was showing [Using ACLs with Consumer Groups](https://docs.konghq.com/hub/kong-inc/acl/how-to/consumer-groups/). in 3.5 it should only be accessible in 3.6+
=> Fix: ACL doc appearing in 3.5 when it should be in 3.6

app/_src/kubernetes-ingress-controller/license.md
Adds a section describing `KongLicense` CRD usage to the license guide.
Fixes https://github.com/Kong/kubernetes-ingress-controller/issues/5570.
https://deploy-preview-6910--kongdocs.netlify.app/kubernetes-ingress-controller/unreleased/license/
=> kic: extend license guide with KongLicense CRD

app/_src/kubernetes-ingress-controller/guides/security/kong-vault.md
Updates the "Kong Vault" guide with `KongVault` CRD usage.
Fixes https://github.com/Kong/kubernetes-ingress-controller/issues/5571.
https://deploy-preview-6917--kongdocs.netlify.app/kubernetes-ingress-controller/unreleased/guides/security/kong-vault/
=> kic: extend vault guide with KongVault CRD usage

app/_src/kubernetes-ingress-controller/guides/security/plugin-secrets.md
Extends `Using Kubernetes Secrets in Plugins` guide to describe the new `configPatches` fields and its usage.
Fixes https://github.com/Kong/kubernetes-ingress-controller/issues/5572.
Preview link:
=> kic: extend secrets in plugins guide with configFrom field

app/_hub/kong-inc/key-auth/overview/_index.md
Fixed a mistake in attaching json data to curl command.  
The `=`, not `:`, must be used to attach the 'body'.
>       -d, --data <data>
>              (HTTP MQTT) Sends the specified data in a POST request to the HTTP server, in the same way that a browser does when a
>              user has filled in an HTML form and presses the submit button. This makes curl pass the data to the server using the
>              content-type application/x-www-form-urlencoded. Compare to -F, --form.
>
>              --data-raw is almost the same but does not have a special interpretation of the @ character. To post data purely
>              binary, you should instead use the --data-binary option. To URL-encode the value of a form field you may use
>              --data-urlencode.
>
>              If any …
=> Fix a typo

app/_hub/kong-inc/exit-transformer/overview/_index.md
Original document assumed knowledge about location for reference of .lua files. Added instruction to save file in referenced lua package path location as per https://docs.konghq.com/gateway/latest/plugin-development/distribution/#manually
Preview link: https://deploy-preview-6922--kongdocs.netlify.app/hub/kong-inc/exit-transformer/#demonstration
=> Fix: Reference lua package path location in Exit Transformer plugin

app/_src/gateway/reference/configuration.md
kong.conf updates generated from latest 3.6 RC. 
Shouldn't be affected by changes in upcoming RCs, as the questionable redis config feature doesn't affect kong.conf at all.
Please don't copyedit, as the content is generated. The manual part is all the version tagging.
If something isn't version tagged, it's because it was a fix to the config file only (ie, the doc was wrong and was fixed, but the code didn't change). 
Preview link: https://deploy-preview-6923--kongdocs.netlify.app/gateway/unreleased/reference/configuration/
* `gte:<version>` - greater than or equal to a …
=> chore: kong.conf updates for 3.6

app/_src/gateway/production/deployment-topologies/hybrid-mode/setup.md
Cert expiration date has been added to /clustering/data-planes endpoint response. 
Found this during changelog editing.
https://github.com/Kong/kong/issues/11921
Preview link: https://deploy-preview-6938--kongdocs.netlify.app/gateway/unreleased/production/deployment-topologies/hybrid-mode/setup/
=> Feat: Add cert expiry to clustering/data-planes output

api-specs/Gateway-EE/latest/kong-ee.yaml, api-specs/Gateway-OSS/latest/kong-oss.yaml
* Added the Kong Gateway edition to the root endpoint (`/`) of the Admin API.
[#12097](https://github.com/Kong/kong/issues/12097)
* Enabled `status_listen` on `127.0.0.1:8007` by default.
[#12304](https://github.com/Kong/kong/issues/12304)
=> Fix: Add missing items from changelog to API specs [skip-ci]

app/gateway/changelog.md
3.4.3.4 was released earlier than the originally drafted date.
Preview link: https://deploy-preview-6941--kongdocs.netlify.app/gateway/changelog/#3434
=> fix: 3.4.3.4 release date

app/_src/kubernetes-ingress-controller/reference/custom-resources-3.1.x.md
Splits the top-level CRDs and the types that they rely on into separate sections to make it clear which types are meant to be used to create objects in the Kubernetes API.
Addresses @liyangau concern about the reference not signaling clearly which types are meant to be used to create objects in a cluster. 
It's propagated from the KIC repo: https://github.com/Kong/kubernetes-ingress-controller/pull/5611
Preview link: https://deploy-preview-6943--kongdocs.netlify.app/kubernetes-ingress-controller/latest/reference/custom-resources/
=> kic: split CRD reference types into sections

app/_hub/kong-inc/statsd-advanced/_metadata.yml, app/_hub/kong-inc/statsd/_metadata.yml
StatsD and StatsD Advanced are incorrectly categorized as Logging plugins, when they should be under Analytics and Monitoring.
See their categorization in Konnect:
Preview link: 
=> Fix: Move StatsD plugins to Analytics and Monitoring category

app/_assets/stylesheets/collapsible-sections.less, app/_assets/stylesheets/index.less, app/_includes/md/plugins-hub/oidc-prereqs.md, app/_layouts/extension.html
Restyling the collapsible sections in prereqs on the plugin hub to stop using the blue note blocks, as they aren't meant for that purpose.
Edge case when there actually needs to be a note (e.g. when something is a warning or a caution) that contains further info, tested on AppDynamics plugin.
Only applying to plugins for now, as the OIDC docs need it. Considered doing this for everything, but would need to rework the KIC prereq sections a fair bit, so that would need some more thought.
Current approach:
Other explored options:
Preview link: 
[OpenID Connect prereqs](https://deploy-preview-6902--kongdocs.netlify.app/hub/kong-inc/openid-connect/how-to/authentication/client-credentials/#prerequisites)
[AppDynamics note to "enable the …
=> Feat(plugins): Collapsible sections styling

app/_hub/kong-inc/ai-proxy/how-to/_mistral.md
The `mistral` provider docs are accidentally a copy of the `llama2` docs!
They need to specifically reference cloud-hosted mistral.ai, as the most common usage.
=> fix(mistral): docs are a copy of llama2

app/_data/docs_nav_deck_1.35.x.yml, app/_data/kong_versions.yml
Bump version in prep for 1.35 release.
Preview link: https://deploy-preview-6959--kongdocs.netlify.app/deck/unreleased/
=> chore: Create 1.35 unreleased deck version

app/konnect/gateway-manager/control-plane-groups/index.md
Removed the sentence because it is no longer true.
=> Fix: Remove sentence stating Analytics for a control plane group are only available at the group level.

app/_data/docs_nav_gateway_3.7.x.yml, app/_data/kong_versions.yml
Chore PR to set up next unreleased version.
Preview link: https://deploy-preview-6978--kongdocs.netlify.app/gateway/unreleased/
=> chore: Bump unreleased Gateway version to 3.7

app/_src/gateway/reference/expressions-language/language-references.md
Remove the `if_version` on OR operator in expression language reference page to let the OR operator (`||`) displayed correctly.
fixes #6972.
Preview link: 
https://deploy-preview-6975--kongdocs.netlify.app/gateway/latest/reference/expressions-language/language-references/#operators
=> Fix: remove if_version on the Or operator in the table

app/_src/gateway/kong-manager/auth/oidc/migrate.md
This pull request adds the ignored parameters to the migration guide for Kong Manager's OIDC feature.
Preview link: 
=> fix(kong-manager): add ignored params to the OIDC migration guide

app/_data/docs_nav_kic_3.1.x.yml, app/_data/docs_nav_kic_3.2.x.yml, app/_src/kubernetes-ingress-controller/reference/cli-arguments-3.1.x.md
Flagged in https://github.com/Kong/docs.konghq.com/actions/runs/7945193457/job/21691549272. Links have no `src`, so they're not being generated properly.
Generator will need adjusting to add a space between the end of the table and ``, otherwise the table breaks and looks like this: 
Ran into a couple other cross-folder issues (kic-v2 vs kubernetes-ingress-controller): 
* Why is https://github.com/Kong/docs.konghq.com/blob/main/app/_src/kic-v2/references/version-compatibility.md being maintained in `kic-v2` and not in the current folder?
* This PR was opened against kic-v2 because the same FAQ page doesn't exist in 3.x: https://github.com/Kong/docs.konghq.com/pull/6403 - should this info be in 3.x?
Preview link: 
For example, if this change is for an upcoming 3.6 release, enclose your …
=> Fix: Links to KIC cli-arguments reference

app/_src/gateway/kong-enterprise/cp-outage-handling.md
We missed some conditional rendering for a note about single backup nodes. It should only apply to 3.6 and later? (waiting on confirmation for the correct version, so this PR might change a little)
https://kongstrong.slack.com/archives/CDSTDSG9J/p1708369514356029?thread_ts=1708368658.991799&cid=CDSTDSG9J
Preview link: 
=> fix: Add 3.6 conditional rendering for single backup nodes

.github/styles/kong/dictionary.txt, app/_src/gateway/breaking-changes/36x.md, app/gateway/changelog.md
Document missing entry for ulimit breaking change.
Preview link: https://deploy-preview-6984--kongdocs.netlify.app/gateway/latest/breaking-changes/
=> Add documentation on higher ulimit requirement for 3.6.0.0

app/_hub/kong-inc/proxy-cache-advanced/overview/_index.md
Adding more info about how cache key is generated based on
https://github.com/Kong/kong-ee/blob/3.6.0.0/plugins-ee/proxy-cache-advanced/kong/plugins/proxy-cache-advanced/cache_key.lua#L110-L122
Preview: https://deploy-preview-6982--kongdocs.netlify.app/hub/kong-inc/proxy-cache-advanced/#cache-key
=> add more info about cache key generation in proxy-cache-advanced

app/_hub/kong-inc/oauth2/overview/_index.md
The note was added based on an old ticket that doesn't apply now. The OAuth2 plugin can be run in production. 
Preview link: https://deploy-preview-6988--kongdocs.netlify.app/hub/kong-inc/oauth2/
=> fix: Remove inaccurate note in OAuth2 plugin

app/_src/mesh/features/vault.md
As described in the PR changes, it's likely users want to create orphan tokens to authenticate to vault.
See also https://github.com/Kong/kong-mesh/issues/5412
Preview link: https://deploy-preview-6964--kongdocs.netlify.app/mesh/latest/features/vault/#step-4-configure-authentication-method
- Not applicable to a specific version
=> docs(mesh): in Vault docs switch to orphan tokens

app/_layouts/extension.html
Render the link to a plugin's configuration page only if it has a schema -this was removed in a [previous PR](https://github.com/Kong/docs.konghq.com/commit/5fbd08aa7fb3388d107bd4d144ae7c941ceb255b#diff-0e2df9b2eb63d24180f8e981ed509cf86eaa9747faef9fa76cb383f931ab2cff)-
A full scan results in the following 404s:
*  /hub/kong-inc/wasm/
*  /hub/kong-inc/enable-app-reg/
Those were introduced as part of https://github.com/Kong/docs.konghq.com/pull/6883/files
@lena-larionova should we set an empty `DocumentationURL` for those? WDYT?
Preview link: 
* `gte:<version>` - greater …
=> Fix links to plugins

app/_src/kic-v2/references/version-compatibility.md
Preview link: [/kubernetes-ingress-controller/latest/reference/version-compatibility/](https://deploy-preview-6998--kongdocs.netlify.app/kubernetes-ingress-controller/latest/reference/version-compatibility/)
=> Add Gateway 3.6 to KIC compatibility matrix

.github/styles/kong/dictionary.txt, app/_src/gateway/breaking-changes/36x.md
Preview link: https://deploy-preview-7005--kongdocs.netlify.app/gateway/latest/breaking-changes/
=> document HTTP/2 compatibility breaking change for 3.6

app/_src/mesh/features/meshglobalratelimit.md, app/_src/mesh/features/meshopa.md
Change the targetRef support table since 2.6 it has a different layout.
**Listener tags are not yet supported because the plugins need to be adjusted**
Preview link: 
fix: https://github.com/Kong/kong-mesh/issues/5342
=> docs(mesh): update MeshGlobalRateLimit and MeshOPA targetref support table

app/_data/tables/support/gateway/packages.yml, app/_data/tables/support/gateway/versions/28.yml, app/_data/tables/support/gateway/versions/32.yml, app/_data/tables/support/gateway/versions/33.yml, app/_data/tables/support/gateway/versions/34.yml, app/_data/tables/support/gateway/versions/35.yml, app/_data/tables/support/gateway/versions/36.yml
OS End of Life dates are only listed in our support matrix if the EOL is sooner than the EOL of the Gateway version. We were missing these dates in a few places. 
Preview link: https://deploy-preview-7008--kongdocs.netlify.app/gateway/latest/support-policy/
=> chore: Fix OS EOLs in Gateway support matrix

app/_src/gateway/install/linux/amazon-linux.md, app/_src/gateway/install/linux/debian.md, app/_src/gateway/install/linux/rhel.md, app/_src/gateway/install/linux/ubuntu.md
Add a step to stop Kong before trying to uninstall it to prevent errors, per https://konghq.atlassian.net/browse/DOCU-253
Preview link: 
=> chore: Add step to stop kong before uninstalling

app/_src/gateway/support/browser.md, app/_src/gateway/support/index.md, app/_src/gateway/support/third-party.md
Gateway 3.2.x enters sunset support on Feb 28th. 
Resolves [DOCU-3521](https://konghq.atlassian.net/browse/DOCU-3521).
Preview link: https://deploy-preview-7004--kongdocs.netlify.app/gateway/latest/support-policy/
[DOCU-3521]: https://konghq.atlassian.net/browse/DOCU-3521?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS …
=> Chore: Move Gateway 3.2 to sunset versions

app/_redirects, app/moved_urls.yml
This URL got flagged as 404ing at /latest/ by google console. Did some digging, realized that it should probably be in moved URLs instead anyway, based on the following rule:
* When a topic is moved and not removed or renamed, we should add an entry to moved URLs instead of redirects.
This _should_ generate the correct redirects automatically.
Preview link: 
https://deploy-preview-6983--kongdocs.netlify.app/gateway/3.6.x/production/benchmark/
https://deploy-preview-6983--kongdocs.netlify.app/gateway/latest/production/benchmark/
* `gte:<version>` - greater than or equal …
=> Fix: replace benchmark redirect with moved url entry

app/_data/docs_nav_deck_1.36.x.yml, app/_data/kong_versions.yml
Bump deck version to 1.35 and create an unreleased 1.36 version.
decK 1.35 was released earlier today: https://github.com/Kong/deck/releases/tag/v1.35.0
Preview link: https://deploy-preview-7015--kongdocs.netlify.app/deck/
=> Release: decK 1.35

app/_hub/kong-inc/rate-limiting-advanced/overview/_index.md, app/_src/gateway/kong-enterprise/index.md
The consumer groups description is outdated on the Kong Enterprise overview, as it describes consumer groups for rate limiting only. This is no longer the case.
https://docs.konghq.com/gateway/latest/kong-enterprise/#consumer-groups
Preview link: 
=> Fix: Consumer groups links and descriptions

app/konnect/updates.md
Changelog listed February twice
```
**Additional plugin support for consumer groups**
: Along with {{site.base_gateway}} 3.6 support in {{site.konnect_short_name}}, additional plugins are now supported for consumer groups.
: The following plugins can be applied to consumer groups using the Admin API and the Gateway Manager UI:
* [Rate Limiting (OSS)](/hub/kong-inc/rate-limiting/)
* [Request Termination](/hub/kong-inc/request-termination/)
* [Proxy Cache](/hub/kong-inc/proxy-cache/)
* [Proxy Cache Advanced](/hub/kong-inc/proxy-cache-advanced/)
**Konnect API Products**
```
=> Fix: Stray month in changelog

app/_src/gateway/admin-api/index_latest.md
experimenting w/ link formatting to see if we can have the links to specs from table open in new tab, similar to nav behavior.
Preview link: https://deploy-preview-6934--kongdocs.netlify.app/gateway/latest/admin-api/
=> Chore: spec endpoint links open in new tab

app/_src/gateway/kong-manager/auth/oidc/configure.md
Noticed a double `:` in the doc --> fixed it --> saw some formatting issues in the doc while fixing --> fixed those too.
Preview link: 
=> fix: Typos in oidc for kong manager doc

app/_src/gateway/licenses/index.md
Somehow, likely during a force push, the content from #6266 went missing from the 3.5 release branch, so the content never went live on the public site. This adds that content back in.
**Note:** There is no conditional rendering on purpose. Per the old PR: "Regarding this section of the license file, please remove the conditional rendering, it applies to all Kong versions." see https://github.com/Kong/docs.konghq.com/pull/6266#discussion_r1371001034
Preview link: 
* `lte:<version>` - less than or equal to a …
=> fix: Add missing license behavior content from 3.5

app/_src/gateway/how-kong-works/health-checks.md
Updated the HTTP method from POST to PUT for setting targets health. The current doc references a POST method which results in a 405 - Method not allowed error.
Preview link: 
=> fix: Updated HTTP method for setting targets health

app/_src/gateway/kong-manager/enable.md
The way the original command was written causes the shell to not find the -e command, resulting in an error.
=> Fix: Enable Kong Manager in Docker command fix

app/_src/kubernetes-ingress-controller/concepts/ingress.md
In https://github.com/Kong/docs.konghq.com/pull/6556#issuecomment-1978543101 @mloskot has noticed there's one more leftover of `kongCredType` usage. Let's convert it to the new label.
Preview link: https://deploy-preview-7040--kongdocs.netlify.app/kubernetes-ingress-controller/latest/concepts/ingress/#examples
=> kic: fix kongCredType leftover

README.md, app/_plugins/generators/plugin_single_source_generator.rb, app/_plugins/generators/sitemap.rb
Add the ability to disable the sitemap and hub generators to reduce local build times.
Generators are run every time a file changes. It takes approximately 16 seconds to run those generators (hub and sitemap) locally, even if the changed file wasn't related to that particular generator.
Disabling them locally significantly reduces the build times.
https://github.com/Kong/docs.konghq.com/assets/715229/7e1275e4-a937-4b6c-9696-853353c10fca
Note: cold start still takes about 87s. The first edit takes longer (17s) because of the `RESET` stage, after that, it only takes  2s.
Preview link: 
Use any of the …
=> Disable slow generators

app/_src/gateway/how-kong-works/routing-traffic.md, app/gateway/2.6.x/reference/proxy.md, app/gateway/2.7.x/reference/proxy.md, app/gateway/2.8.x/reference/proxy.md
Doc said "TCL/TLS", should be "TCP/TLS". 
Was reported in docs Slack. Ended up making this fix since it appears in old versioned files, and it's easier/cleaner to quickly search & replace.
Preview link: 
=> Fix: TCL/TCP typo

app/_src/kubernetes-ingress-controller/reference/troubleshooting.md
Announce reference to the diagnostic sever in the introductory paragraph of the section dedicated to dumping of the configuration. Otherwise, reader reaching the point 3 may feel a bit surprised and confused how the dump will actually be retrieved. IOW, a procedure should be briefly described first, then present details steps.
Preview link: 
=> Explain --dump-config gives access via diagnostic server

app/_data/kong_versions.yml, app/gateway/changelog.md
Bump version and create changelog entry for Gateway 3.6.1.1.
Preview link: https://deploy-preview-7046--kongdocs.netlify.app/gateway/changelog/
=> Release: Gateway 3.6.1.1

app/_src/deck/reference/deck_file_merge.md
`deck file merge` example uses `deck file patch`, where it should be `merge`. 
Parallel PR in decK repo: https://github.com/Kong/deck/pull/1237
Preview link: 
=> fix: decK file merge example

app/konnect/dev-portal/customization/index.md
Added a couple of notes to clarify that a requirement is to also allow Google Trust Services (pki.goog) by adding a CAA DNS record in a situation where a domain is already explicitly using CAA DNS records. 
What is a little complicated by this is that if a domain doesn't include any CAA DNS records then it's all good, but if they even set one CAA DNS record then it implicitly denies all issuers that they did not define, requiring them to add a new one for `pki.goog` since that is the issuer we utilize in Konnect.
Related [Slack thread](https://kongstrong.slack.com/archives/C03NRECFJPM/p1709667853741059?thread_ts=1709667666.887609&cid=C03NRECFJPM).
Preview link:
=> Update: Add note about Google ACME and DNS requirement

app/_hub/traceableai/traceableai/_metadata/_index.yml
The traceable plugin PR was opened before plugin versioning was changed, so it didn't fail until it got merged into main.
Preview link: Check that the traceable plugin appears in the Hub search/landing page.
https://deploy-preview-7054--kongdocs.netlify.app/hub/?search=traceable
=> fix: Metadata file for traceable plugin

api-specs/Gateway-EE/latest/kong-ee.yaml, api-specs/Gateway-OSS/latest/kong-oss.yaml, app/_includes/plugins/hub-examples/consumer.html, app/_includes/plugins/hub-examples/consumer_groups.html, app/_includes/plugins/hub-examples/global.html, app/_includes/plugins/hub-examples/route.html, app/_includes/plugins/hub-examples/service.html, app/_includes/plugins/schema.html
Fixing some minor issues with plugin schema & example docs:
* Description for the `name` field
* Description for the `instance_name` field
* Outdated links to the Admin API from the plugin config descriptions and plugin examples
* Standardize name variables in API URLs (`{serviceName}` etc)
https://konghq.atlassian.net/browse/DOCU-1498
https://konghq.atlassian.net/browse/DOCU-3412
https://konghq.atlassian.net/browse/DOCU-3706
Preview link: 
* …
=> Fix: Plugin name and instance_name descriptions

app/_assets/stylesheets/sidebar.less, app/_includes/sidebar/item.html
* Add a caret symbol to sidebar menus that also have a URL.
* Fixes overlap between long titles and the caret symbol.
[long nav titles](https://deploy-preview-7057--kongdocs.netlify.app/mesh/2.6.x/networking/service-discovery/)
before:
after:
[missing caret](https://deploy-preview-7057--kongdocs.netlify.app/gateway/latest/production/logging/log-reference/)
before:
after:
You can do the same …
=> Fix sidenav issues

app/_src/deck/reference/deck_file_render.md
Adds a new flag reference for the APIOps command `deck file render` introduced in deck 1.36.x
=> Adds --populate-env-vars to deck file render command reference

app/_src/gateway/breaking-changes/36x.md, app/gateway/changelog.md
The wording of https://github.com/Kong/docs.konghq.com/pull/6984 around `ulimit` is ambiguous; this PR changes it to specifically mention `ulimit -n`.
https://deploy-preview-7058--kongdocs.netlify.app/gateway/latest/breaking-changes/#operating-system-requirements
=> docs(gateway): adjust references to `ulimit -n`.

app/_includes/md/gateway/deployment-topologies.md, app/_src/gateway/production/deployment-topologies/db-less-and-declarative-config.md, app/_src/gateway/production/deployment-topologies/hybrid-mode/index.md, app/_src/gateway/production/deployment-topologies/index.md, app/_src/gateway/production/deployment-topologies/traditional/index.md
Adding topology diagrams based on a couple of slide decks of similar diagrams, converted into mermaid format.
https://konghq.atlassian.net/browse/DOCU-2482
Preview links:
https://deploy-preview-7059--kongdocs.netlify.app/gateway/latest/production/deployment-topologies/
https://deploy-preview-7059--kongdocs.netlify.app/gateway/latest/production/deployment-topologies/hybrid-mode/
https://deploy-preview-7059--kongdocs.netlify.app/gateway/latest/production/deployment-topologies/traditional/
https://deploy-preview-7059--kongdocs.netlify.app/gateway/latest/production/deployment-topologies/db-less-and-declarative-config/
For example, if this change is for an upcoming 3.6 release, enclose your content in `{% if_version gte:3.6.x %} <content> {% endif_version %}` tags (or `if_plugin_version` tags …
=> Feat: Topology diagrams for gateway docs

.github/workflows/generate-changelog.yml
We were creating PRs with `[skip ci]` which should be `[skip-ci]`
=> Fix: Typo in generate changelog GHA

app/_includes/md/kgo/prerequisites-kic.md, app/_src/gateway-operator/get-started/kic/install.md
Fix `{if}` block to introduce licenses when `enterprise` is enabled in the page to introduce prerequisite of installing KGO.
Preview link: 
=> fix if blocks for license part in KGO

app/_src/gateway/plugin-development/distribution.md
Fixes a minor issue in a sample Dockerfile for plugin distribution.   The example Dockerfile extends a Kong-ee docker image, so the entrypoint needs to match what is delivered by that image.
=> Fixes plugin install directions for Dockerfile entrypoint

app/_src/gateway/install/docker/build-custom-images.md
Reported by Stu. We link to a Jammy binary for > 3.1, but the Dockerfile was hardcoded to Focal.
Preview link: /gateway/latest/install/docker/build-custom-images/
=> Fix Gateway > 3.1 docker install instructions

app/_src/gateway-operator/guides/autoscaling-workloads/prometheus.md
Fix Prometheus query in KGO guide which caused it to intermittently (incorrectly) report 0 which then in turn caused the HPA to scale the workload to 0.
Preview link: 
=> kgo: fix Prometheus query in the guide which intermittently produced 0s which caused the targeted workload to scale down to 0

app/_data/kong_versions.yml, app/_src/gateway-operator/reference/version-compatibility.md
Update version compat matrix for KGO 1.2.
Also bump KIC latest to 3.1.2 and KGO to 1.2.1 to have up to date latest versions referenced in guides.
Preview link: 
=> kgo: update version compat table for 1.2

app/konnect/dev-portal/applications/dynamic-client-registration/auth0.md
Updated the Issuer URL information, as providing a trailing slash will cause issues.
When we have trailing slash for issuer URL, it get concatenated which will result in issuer as this https://dev-26uur0y8i4n8x3ez.us.auth0.com//api/v2/". So, informing users via docs will be valuable until if this can be gracefully handled.
Following steps mentioned in this docs and just have additional change of including / at the end of issuer url. And try to create an application in Dev Portal, which will fail with "Unable to create one time access token" error.
=> (fix) Update auth0 instructions to include warning on trailing forward slash in URL

app/gateway/changelog.md
The docs of `3.4.3.5` missed a version bump of `kong-lua-resty-kafka` from `0.17` to `0.18`.
FTI-5751
Preview link: 
=> docs(3.4.3.5): add missing version bump of kong-lua-resty-kafka

.github/styles/kong/dictionary.txt, app/_includes/md/availability-stages.md, app/_src/gateway/index.md, app/_src/gateway/support-policy.md, app/_src/gateway/support/index.md, app/_src/gateway/upgrade-v2.md, app/_src/gateway/upgrade-v3.md, app/_src/gateway/upgrade/index.md, app/gateway/2.6.x/index.md, app/gateway/2.6.x/install-and-run/upgrade-enterprise.md, app/gateway/2.6.x/install-and-run/upgrade-oss.md, app/gateway/2.7.x/index.md, app/gateway/2.7.x/install-and-run/upgrade-enterprise.md, app/gateway/2.7.x/install-and-run/upgrade-oss.md, app/gateway/2.8.x/index.md, app/gateway/2.8.x/install-and-run/upgrade-enterprise.md, app/gateway/2.8.x/install-and-run/upgrade-oss.md, app/gateway/2.8.x/support-policy.md
Adding a note to clarify what we deliver in a version, most notably patch versions, to make it clear that it is never safe to upgrade automatically. We can break semver with backports, and it isn't always predicatable.
https://konghq.atlassian.net/browse/DOCU-3717
Preview link: https://deploy-preview-7117--kongdocs.netlify.app/gateway/latest/support-policy/
You can do the same for older …
=> chore: Clarify our use of SemVer with Kong Gateway

app/_src/gateway/install/docker/index.md
Fixing this issue with the "Start Kong Gateway" heading:
Preview link: https://deploy-preview-7162--kongdocs.netlify.app/gateway/3.6.x/install/docker/
=> Fix: Spacing on Gateway Docker install page

app/_includes/md/plugins-hub/json-object-log.md
We are no longer including receive time in `latencies.kong`. This updates the description accordingly.
I also put all of the >=3.7 changes into one conditional block. There is now some duplication, but I feel this makes things more readable to the human eye.
Review the `file-log` plugin doc page.
[KAG-3798](https://konghq.atlassian.net/browse/KAG-3798)
[KAG-3798]: https://konghq.atlassian.net/browse/KAG-3798?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update: latencies.kong description

app/_includes/md/konnect/konnect-architecture.md, app/konnect/gateway-manager/data-plane-nodes/index.md, app/konnect/gateway-manager/data-plane-nodes/upgrade.md, app/konnect/gateway-manager/index.md, app/konnect/getting-started/index.md, app/konnect/index.md
We are now calling the original way of deploying ‘self-managed’, and cloud gateways are now referred to as fully-managed, or dedicated cloud instances. Update the Konnect documentation to ensure that we are referring to self-managed control planes across the docs.
I manually went through the docs to look for spots to update since there weren't any great search terms to find/replace in the docs set.
DOCU-3701
Preview link: https://deploy-preview-7093--kongdocs.netlify.app/konnect/
* `lte:<version>` - less …
=> feat: Cloud Gateway terminology updates

.github/styles/kong/dictionary.txt, app/_data/docs_nav_deck_1.37.x.yml, app/_data/kong_versions.yml, app/_src/deck/reference/deck_file_namespace.md
Doc updates for decK 1.36 + generate an unreleased 1.37 version.
Release went out three weeks ago.
https://github.com/Kong/deck/releases
Preview link: https://deploy-preview-7186--kongdocs.netlify.app/deck/latest/reference/deck_file_namespace/
=> Release: decK 1.36.x

app/_data/kong_versions.yml, app/gateway/changelog.md
Changelog and version bump for Gateway 3.6.1.2.
There are no kong.conf updates.
https://konghq.atlassian.net/browse/DOCU-3756
Preview link: https://deploy-preview-7170--kongdocs.netlify.app/gateway/changelog/
=> Release: Gateway 3.6.1.2

app/_data/kong_versions.yml
Update latest KIC version to 3.1.3 https://github.com/Kong/kubernetes-ingress-controller/releases/tag/v3.1.3
Preview link:
=> chore(kic): update latest to 3.1.3

app/_src/gateway/plugin-development/pdk/kong.log.md, app/gateway/2.6.x/pdk/kong.log.md, app/gateway/2.7.x/pdk/kong.log.md, app/gateway/2.8.x/pdk/kong.log.md
The syntax highlighter doesn't recognize `plain`, so it breaks the codeblock. The copy code icon scrolls with the text:
(source: https://docs.konghq.com/gateway/latest/plugin-development/pdk/kong.log/)
Reported on Slack.
Preview link: https://deploy-preview-7196--kongdocs.netlify.app/gateway/latest/plugin-development/pdk/kong.log/
=> Fix: Replace `plain` with `plaintext` for syntax highlighting

app/_includes/md/enterprise/deploy-license.md, app/_src/gateway/licenses/deploy.md, app/_src/gateway/licenses/examples.md
* Added notes about restarting the Kong Gateway nodes/service when updating a license.
* Linked the Troubleshooting documentation from Overview page on the Deploy page.
Added because this was an occasional issue with customers after updating a license where they kept seeing warnings in the logs and Kong Manager UI about an expiring license after updating it.
Preview link:
=> Update: Licensing Admin API updates and Troubleshooting section links

app/_data/docs_nav_konnect.yml, app/konnect/gateway-manager/data-plane-nodes/transit-gateways.md, app/konnect/getting-started/index.md
Updates the getting started doc to add an explanation of cloud gateways
Adds a doc that explains how to configure transit gateways. 
https://deploy-preview-7151--kongdocs.netlify.app/
https://deploy-preview-7151--kongdocs.netlify.app/konnect/getting-started/
https://deploy-preview-7151--kongdocs.netlify.app/konnect/gateway-manager/data-plane-nodes/transit-gateways/
=> Feat: Update get started with Konnect and transit gateway documentation

app/_data/docs_nav_kic_3.0.x.yml, app/_data/docs_nav_kic_3.1.x.yml, app/_data/docs_nav_kic_3.2.x.yml, app/_src/kubernetes-ingress-controller/reference/version-compatibility.md
For some reason the version compatibility matrix at https://docs.konghq.com/kubernetes-ingress-controller/3.1.x/reference/version-compatibility/#general
doesn't show up properly.
This PR fixes that. I'm not 100% sure of the reason for the broken rendering but extracting the old version compat matrix from v2 tree did help.
It also cleans up the file a bit and removes old k8s versions which are way out of support as of now.
https://deploy-preview-7205--kongdocs.netlify.app/kubernetes-ingress-controller/latest/reference/version-compatibility/#kubernetes
* `gte:<version>` - …
=> kic: fix version compat table for v3 versions

app/_hub/kong-inc/openid-connect/how-to/_cert-bound-access-tokens.md, app/_hub/kong-inc/openid-connect/how-to/authentication/_introspection.md, app/_hub/kong-inc/openid-connect/how-to/authentication/_jwt-access-token.md, app/_hub/kong-inc/openid-connect/how-to/authentication/_session.md
The OIDC cert-bound access tokens doc was added in 3.5, but got lost in a rebase. 
Preview link: https://deploy-preview-7208--kongdocs.netlify.app/hub/kong-inc/openid-connect/how-to/cert-bound-access-tokens/
=> Fix: Add missing client-bound access tokens doc to OIDC plugin

app/_plugins/kuma-specific/warning.rb
The markup we used in the tag was outdated. Change it so that a note is render and update the type of note so that it matches the one in Kuma. (the use a different system)
Preview link: https://deploy-preview-7199--kongdocs.netlify.app/mesh/latest/reference/kubernetes-annotations/#kumaiodirect-access-services
=> Fix {:.warning} in Kong mesh

app/_hub/kong-inc/app-dynamics/_metadata/_index.yml, app/_hub/kong-inc/aws-lambda/_metadata/_index.yml, app/_hub/kong-inc/file-log/_metadata/_index.yml, app/_hub/kong-inc/prometheus/_metadata/_index.yml, app/_hub/kong-inc/syslog/_metadata/_index.yml, app/hub/plugins/compatibility/index.md, app/konnect/compatibility.md, app/konnect/gateway-manager/plugins/add-custom-plugin.md, app/konnect/gateway-manager/plugins/index.md
https://konghq.atlassian.net/browse/DOCU-3699
Adding info about plugin compatibility with dedicated cloud gateways. 
This might not be the complete list of incompatible plugins. There is also currently nothing to link to for the differences on configuration for AWS IAM assumeRole.
Preview link:
https://deploy-preview-7216--kongdocs.netlify.app/hub/plugins/compatibility/
https://deploy-preview-7216--kongdocs.netlify.app/konnect/compatibility/
* …
=> Update: Plugin compatibility in dedicated cloud gateways

app/_src/kubernetes-ingress-controller/production/observability/events.md
Adds a section about Events for cluster scoped resources
Relevant KIC issue: https://github.com/Kong/kubernetes-ingress-controller/issues/5847
Preview link: 
=> kic: add section about events for cluster scoped resources

app/_src/gateway/kong-enterprise/provenance-verification.md
- PR aims to publish provenance signatures into a single central `kong/notary` repository instead of image repository. 
- This will require users performing an additional step starting GW 3.7.x for verifying provenance 
- Aims to provide a similar ux flow for provenance verification similar to verifying image signatures 
- This change is added in a `condition block` to avoid breaking any previous UX prior to 3.7.x for provenance verification
This PR features a change starting from GW release for 3.7.x that should include the GW PR: https://github.com/Kong/kong-ee/pull/8814 and https://github.com/Kong/kong-ee/pull/8816
Preview link: 
For example, if this change is for an upcoming 3.6 release, enclose your content in `{% if_version gte:3.6.x %} <content> {% endif_version %}` tags (or …
=> feat(SLSA/provenance): publish provenance to central notary repository

app/_assets/javascripts/app.js, app/_data/tables/install_options_34x.yml, app/_src/gateway/install/docker/index.md
Switch /install page to point to our Docker installation docs
Preview link: [/gateway/3.6.x/install/docker/](https://deploy-preview-7239--kongdocs.netlify.app/gateway/3.6.x/install/docker/)
=> Make Docker page show all available base images

app/_data/docs_nav_mesh_2.8.x.yml, app/_data/docs_nav_mesh_dev.yml, app/_data/kong_versions.yml
Fix to showing correct Kong Mesh versions in docs
Preview link: 
=> fix kong mesh navigation

app/_hub/kong-inc/session/overview/_index.md
Fixing a couple of undefined anchor links in the Session plugin. 
Ended up cleaning up a bit of grammar/style/punctuation as well.
Preview link: 
=> Fix: Session plugin missing links and minor cleanup

app/_hub/kong-inc/ai-proxy/how-to/_llama2.md
The example provided in the curl command references the ollama endpoint, http://ollama-server.local:11434/v1/chat, which returns a 404.
Per the docs (referenced earlier on this page), the correct endpoint should be /api/chat which I can confirm works.
https://github.com/ollama/ollama/blob/main/docs/api.md#generate-a-chat-completion
example:
$ curl localhost:11434/api/generate -d '{ "model": "llama2", "prompt":"Why does Kong make the best gateway?", "stream":false }' -i
HTTP/1.1 200 OK
$ curl localhost:11434/v1/generate -d '{ "model": "llama2", "prompt":"Why does Kong make the best gateway?", stream":false  }' -i
HTTP/1.1 404 Not Found
Content-Type: text/plain
Date: Tue, 16 Apr 2024 01:56:56 GMT
404 page not found
Preview link: 
For example, if this change is for an upcoming 3.6 release, …
=> Fix: Upstream URL for llama2 completion example

Gemfile.lock
Bump jekyll-generator-single-source
Includes new `page.release.tag` method
Preview link: 
=> Bump single-source-generator

app/_data/kong_versions.yml, app/gateway/changelog.md
Changelog and version bump for gateway 3.6.1.3.
No ticket, this is an ad hoc patch.
Preview link: https://deploy-preview-7219--kongdocs.netlify.app/gateway/changelog/#3613
=> Release: Gateway 3.6.1.3

.vale.ini
Vale will no longer trigger on
```
{% kgo_podtemplatespec_example %}
{% endkgo_podtemplatespec_example %}
```
=> Fix: Vale for kgo template

app/_assets/javascripts/app.js, app/_data/tables/install_options_34x.yml, app/_src/gateway/install/docker/index.md
Reverts Kong/docs.konghq.com#7239 and condenses Docker install to single row. Feedback on listing multiple available  platforms was that approach was confusing.
Testing: 
* https://deploy-preview-7251--kongdocs.netlify.app/gateway/latest/install/ > Docker row reads "Install with Docker" and links to OSS / Enterprise install instructions on https://deploy-preview-7251--kongdocs.netlify.app/gateway/latest/install/docker/
=> (fix) Revert "Make Docker page show all available base images" + condense Docker install to single row

app/_hub/kong-inc/ai-proxy/overview/_index.md
Anthropic released a new `messages` API, we change the `chat` route_type of Anthropic to the new `messages` API correspondingly. 
This new feature is about to be released in 3.7.0.0, the doc should be updated simultaneously.
The sister [PR](https://github.com/Kong/kong-ee/pull/8747) for kong-ee has already been merged.
=> feat: change path to `v1/messages` api for anthropic

.github/workflows/sync-kuma-submodule.yml
Set labels automatically when updating kuma instead of listing them in the PR description.
Preview link: 
=> Set labels automatically when updating kuma

app/_src/gateway/production/tracing/index.md
This is for `3.7.0.0` release.
The Granular Tracing is removed from `3.7.0.0` onward. Add a warning message to docs. See https://github.com/Kong/kong-ee/pull/8669 and https://konghq.atlassian.net/browse/KAG-2713.
Preview link: 
=> docs(*): add a deprecated message to granular tracing

app/_src/gateway/get-started/index.md, app/_src/gateway/get-started/proxy-caching.md
Fix proxy caching getting started guide after the move from mockbin to httpbin
Preview link: [/gateway/latest/get-started/proxy-caching/](https://deploy-preview-7258--kongdocs.netlify.app/gateway/latest/get-started/proxy-caching/)
=> Get Started: httpbin.org doesn't return a content-type charset

app/_src/gateway/get-started/proxy-caching.md
Fixing broken ordered list and putting the sections into tabs for better flow:
Preview link: https://deploy-preview-7260--kongdocs.netlify.app/gateway/latest/get-started/proxy-caching/#entity-level-proxy-caching
=> Fix: Broken ordered list in getting started guide

app/_hub/kong-inc/opentelemetry/overview/_index.md, app/_hub/kong-inc/zipkin/overview/_index.md, app/_includes/md/plugins-hub/tracing-headers-propagation.md
Documentation for the new (3.7.0.0+) tracing headers propagation module, available to the OpenTelemetry and Zipkin plugins.
Preview link: 
https://deploy-preview-7161--kongdocs.netlify.app/hub/kong-inc/opentelemetry/unreleased/#propagation
https://deploy-preview-7161--kongdocs.netlify.app/hub/kong-inc/zipkin/unreleased/#propagation
KAG-4105
=> feat(plugins): tracing headers propagation

Makefile
Now you can run `make vale` to run vale locally against your modified files.
=> Chore: add the ability to run vale on modified files locally to make file

app/_includes/docs-sidebar.html, app/_layouts/docs-v2.html, app/_src/gateway/support/index.md
Label LTS versions in the navigation to make them easier to identify: 
And adjust heading levels on the support page. The LTS section needed a heading to make it easier to find, both visually and via search; had to fix nesting to make that work.
Preview link: https://deploy-preview-7269--kongdocs.netlify.app/gateway/latest/support-policy/
=> Chore: LTS labels

app/konnect/gateway-manager/data-plane-nodes/transit-gateways.md
Adds mapping information to transit gateway documentation based on an issue reported by a customer.
=> Fix: Add mapping information to transit gateways documentation

app/konnect/api/filtering.md
https://konghq.atlassian.net/browse/DOCU-3783
Rewords the introduction paragraph to explicitly mention that the filtering options aren't present in every API, and that a reader should review the API spec for the most accurate info.
=> Fix: Clear up filtering endpoints issue

app/_src/kubernetes-ingress-controller/guides/services/cross-namespace.md
"Any" is not a valid value, it should be "All":
spec.listeners[0].allowedRoutes.namespaces.from: Unsupported value: "Any": supported values: "All", "Selector", "Same", <nil>
Fixed an apparent mistake in the docs where it said "Any", but meant "All"
Preview link: 
=> Changed from: Any to from: All

app/_plugins/hooks/products_renderer.rb
Prior to this change, KONG_PRODUCTS='gateway:*' was generating both `/gateway/*/` and `/gateway-operator/*/`
Preview link: 
=> Fix KONG_PRODUCTS so that it filters the right

app/_src/gateway/kong-enterprise/secrets-management/backends/index.md
Removed "environment variable" from the list of supported vaults because envars are not vaults. 
Preview link:
=> fix(vaults): envars are not vaults

app/_src/mesh/install.md
Fixing broken link test failure: https://github.com/Kong/docs.konghq.com/actions/runs/8768698057/job/24063340313
The old docker logo was deleted but the Mesh install page is still pointing to it. Changing it to use the latest docker logo instead.
Preview link: https://deploy-preview-7285--kongdocs.netlify.app/mesh/latest/install/
=> Fix: update docker logo on Mesh docs

app/_src/gateway/upgrade/index.md
Fixing two errors:
* In 3.4, the 2.8 -> 3.4 path should be a direct upgrade, since they're both LTS versions
* The "Traditional mode" 2.8.x row is missing in 3.5.x and 3.6.x
Also fixing up some copy/paste formatting.
Preview link: 
https://deploy-preview-7267--kongdocs.netlify.app/gateway/latest/upgrade/#guaranteed-upgrade-paths
https://deploy-preview-7267--kongdocs.netlify.app/gateway/3.4.x/upgrade/#guaranteed-upgrade-paths
https://deploy-preview-7267--kongdocs.netlify.app/gateway/3.5.x/upgrade/#guaranteed-upgrade-paths
* `gte:<version>` - …
=> Fix: Upgrade paths

.github/workflows/sync-submodules.yml
Run submodule-sync on repository_dispatch so that we don't need to wait for the cron to run
Preview link: 
=> Run submodule-sync on repository_dispatch

app/_data/kong_versions.yml, app/gateway/changelog.md
Changelog and version bump for Gateway 3.4.3.7.
Also merge https://github.com/Kong/docs.konghq.com/pull/7120 when this goes out.
Preview link:
=> Release: Gateway 3.4.3.7

app/_hub/kong-inc/application-registration/how-to/_index.md, app/_hub/kong-inc/application-registration/overview/_index.md
=> docs(plugins): updates the description for app-reg

app/_layouts/docs-v2.html, tests/sidebar.test.js, tools/admonition-summary/scrape.js
When looking at the docs for an older version, the banner currently says "You are browsing documentation for an outdated version." This isn't always true, as our LTS versions are older, but not considered "outdated". Changing the text to reflect this.
Preview link: https://deploy-preview-7314--kongdocs.netlify.app/gateway/3.4.x/
=> Chore: change 'outdated' to 'older' in version banner

app/_src/gateway/key-concepts/routes/expressions.md
KAG-3927
https://deploy-preview-7304--kongdocs.netlify.app/
=> Feat: new expressions flavor in 3.7

app/konnect/gateway-manager/data-plane-nodes/secure-communications.md
Added a row for clarity. 
Now looks like:
```
| Certificate | Type         | Issuer                   |
|-------------|--------------|--------------------------|
| `cert1`     | Service      | Issued by Intermediary   |
| `cert2`     | Intermediary | Issued by Root           |
| `cert3`     | Root         | Issued by Root (Self-signed) |
```
=> Fix: fix chart in secure comms update doc

app/_src/gateway-operator/guides/autoscaling-kong.md
I improved the readability of some commands separating their outputs, facilitating user copy-paste flow when trying out when trying the autoscaling setup, clarified the k6s installation is required before running the command and its javascript test.
Preview link:
=> Improved readability and detatched some commands from their output

app/_hub/kong-inc/datadog/overview/_index.md, app/_hub/kong-inc/http-log/overview/_index.md, app/_hub/kong-inc/opentelemetry/overview/_index.md, app/_hub/kong-inc/statsd/overview/_index.md, app/_hub/kong-inc/zipkin/overview/_index.md, app/_src/gateway/kong-plugins/queue/reference.md
Explicitly mention that queue parameters are scoped to one worker in the Queueing section of plugins that use queues.
Preview link: https://deploy-preview-7331--kongdocs.netlify.app/
KAG-4409
=> Add paragraph to explain queue parameter scope

app/_includes/md/about-plugins.md
Kong Gateways behavior is intentionally undefined when dealing with multiple consumer-group-scoped plugins, yet ensures deterministic behavior.
Bonus: whitespace fixes
=> docs(consumergroups): add paragraph about undefined behavior 

app/_hub/kong-inc/openid-connect/how-to/_fapi.md
This PR adds a page to summarize/link all the FAPI-related features that the OpenID Connect plugin provides.
https://konghq.atlassian.net/browse/DOCU-3627
Preview link: https://deploy-preview-7236--kongdocs.netlify.app/hub/kong-inc/openid-connect/unreleased/how-to/fapi/
=> feat(openid-connect): fapi docs

app/_hub/kong-inc/oas-validation/overview/_index.md
Update document for OAS-Validation plugin about OpenAPI 3.1.0
Preview link: https://deploy-preview-7310--kongdocs.netlify.app/hub/kong-inc/oas-validation/unreleased/
https://github.com/Kong/kong-ee/pull/7833
=> feat(gateway/oas-validation): OpenAPI 3.1.0 documentation

app/_hub/datadome/kong-plugin-datadome/_metadata/_index.yml
Based on review w/ @DaniellaFreese and Eric, this plugin doesn't qualify as Enterprise based on the revised categorization set at end of last year. 
Preview link: https://deploy-preview-7350--kongdocs.netlify.app/hub/datadome/kong-plugin-datadome/  (Enterprise badge removed from under title)
=> (fix) Remove "enterprise" category from Datadome

api-specs/Gateway-EE/latest/kong-ee.yaml
Audit Log endpoints (`/audit/requests` and `/audit/objects`) right now accept `before` and `after` parameters that allow a user to search through audit log endpoints
Preview link:
=> docs(api): describe before & after filters of audit log

tools/broken-link-checker/config/ignored_targets.json
Add https://openai.com to scheduled broken links' ignored targets, it returns 403 causing the action to fail
Preview link:
=> Add https://openai.com to scheduled broken links' ignored targets

.github/styles/kong/auto-ignore.txt, app/contributing/diagrams.md
I added instructions to the contributing docs about how to export Mermaid diagrams from the docs using the Mermaid live editor. This way, people can easily get the images for our diagrams and reuse them.
DOCU-3828
Preview link:
=> feat: Add Mermaid export instructions to contributing guide

tools/_utilities/lib/nav-to-urls.js
The broken link checker didn't catch a broken link when it was run in "PR" mode, but the full scan did.
Related PR: https://github.com/Kong/docs.konghq.com/pull/7381
In "PR" mode, the check pull the modified files, gets the corresponding urls, and checks those urls for broken links.
The problem was with the filenames-to-URLs transformation. The way it works is by checking the `docs_nav` files for an entry that has a file as `src` or `url`. If an entry in a nav file didn't have a `src` we used the `url` as `src`. See
https://github.com/Kong/docs.konghq.com/blob/main/tools/_utilities/lib/nav-to-urls.js#L34-L38.
However, this didn't consider the case where the `url` corresponds to a file that ends with `index.md`
Example:
In a PR `app/_src/gateway/ai-gateway/index.md` was modified and a …
=> Fixes check-links.yml

app/_hub/kong-inc/request-termination/overview/_index.md
Clarification: the plugin won't execute if if forward-proxy is enabled (valid for all versions)
Jira: https://konghq.atlassian.net/browse/FTI-5909
Kong idea reported to review the plugin priority: https://kong-internal-portal.ideas.aha.io/ideas/GTWY-I-886
Preview link: https://deploy-preview-7358--kongdocs.netlify.app/hub/kong-inc/request-termination/
=> request-termination and forward-proxy incompatibility

app/_includes/md/plugins-hub/sandbox.md
This PR adds more explanation about `kong.cache` cache instance inside serverless functions' sandbox environment.
Solves FTI-5898
Preview link:
=> fix(sandbox): add more explanation about kong.cache instance inside serverless function sandbox

app/_data/docs_nav_mesh_2.2.x.yml, app/_data/docs_nav_mesh_2.3.x.yml, app/_data/docs_nav_mesh_2.4.x.yml, app/_data/docs_nav_mesh_2.5.x.yml, app/_data/docs_nav_mesh_2.6.x.yml, app/_data/docs_nav_mesh_2.7.x.yml, app/_data/docs_nav_mesh_2.8.x.yml, app/_redirects
I'm removing the https://docs.konghq.com/mesh/latest/production/secure-deployment/api-access-control/ page that in Kong Mesh is handled by https://docs.konghq.com/mesh/latest/features/rbac/. This is an alternative to https://github.com/kumahq/kuma-website/pull/1784.
Preview link:
=> docs(rbac): remove a page that is by default not used in kong-mesh

api-specs/Gateway-OSS/latest/kong-oss.yaml, app/_src/gateway/admin-api/index_latest.md
Added WebAssembly Filter Chain endpoints to OSS Admin API spec, matching those from Admin-EE docs. (see #6829).
Preview link:
=> feat: add filter chains to Admin OSS spec

app/_data/kong_versions.yml, app/gateway/changelog.md
Changelog and version bump for 3.4.3.8
Schema update will come separately.
Preview link: https://deploy-preview-7379--kongdocs.netlify.app/gateway/changelog/#3438
=> Release: Gateway 3.4.3.8

.github/styles/kong/dictionary.txt, app/_hub/kong-inc/ai-proxy/how-to/_cloud-provider-authentication.md
> ⚠️ I need help here because there are two pre-requisites:
>
> 1. This only works in Kong Enterprise
> 2. This is only available (the whole page / feature) in Kong 3.7
I have added an explanation on how to use [Azure Managed Identity](https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/managed-identity) authentication when using the Kong AI Proxy within the Azure SaaS.
Preview link: https://deploy-preview-7390--kongdocs.netlify.app/hub/kong-inc/ai-proxy/unreleased/how-to/cloud-provider-authentication/
=> feat(ai-proxy): added Azure native auth explanation

api-specs/Gateway-OSS/3.3/kong-oss-33.yaml, api-specs/Gateway-OSS/3.4/kong-oss-3.4.yaml, api-specs/Gateway-OSS/latest/kong-oss.yaml
https://github.com/Kong/docs.konghq.com/issues/7365
The endpoint to retrieve entity schema is GET /schemas/{entity}/validate, but actual endpoint is GET /schemas/{entity}.
=> Fix: Validate schemas endpoint 

app/_hub/kong-inc/app-dynamics/_metadata/_index.yml, app/_hub/kong-inc/canary/_metadata/_index.yml, app/_hub/kong-inc/degraphql/_metadata/_index.yml, app/_hub/kong-inc/exit-transformer/_metadata/_index.yml, app/_hub/kong-inc/forward-proxy/_metadata/_index.yml, app/_hub/kong-inc/graphql-proxy-cache-advanced/_metadata/_index.yml, app/_hub/kong-inc/jq/_metadata/_index.yml, app/_hub/kong-inc/jwe-decrypt/_metadata/_index.yml, app/_hub/kong-inc/key-auth-enc/_metadata/_index.yml, app/_hub/kong-inc/mocking/_metadata/_index.yml, app/_hub/kong-inc/oauth2-introspection/_metadata/_index.yml, app/_hub/kong-inc/request-transformer-advanced/_metadata/_index.yml, app/_hub/kong-inc/response-transformer-advanced/_metadata/_index.yml, app/_hub/kong-inc/route-by-header/_metadata/_index.yml, app/_hub/kong-inc/route-transformer-advanced/_metadata/_index.yml, app/_hub/kong-inc/statsd-advanced/_metadata/_2.6.x.yml, app/_hub/kong-inc/statsd-advanced/_metadata/_2.7.x.yml, app/_hub/kong-inc/statsd-advanced/_metadata/_2.8.x.yml, app/_hub/kong-inc/statsd-advanced/_metadata/_index.yml, app/_hub/kong-inc/tls-handshake-modifier/_metadata/_index.yml, app/_hub/kong-inc/tls-metadata-headers/_metadata/_index.yml, app/_hub/kong-inc/upstream-timeout/_metadata/_index.yml, app/_hub/kong-inc/websocket-size-limit/_metadata/_index.yml, app/_hub/kong-inc/websocket-validator/_metadata/_index.yml, app/_hub/kong-inc/xml-threat-protection/_metadata/_index.yml, app/_plugins/generators/plugin_single_source/pages/configuration.rb, spec/app/_plugins/generators/plugin_single_source/pages/configuration_spec.rb
A bunch of EE plugins were moved to a new directory, breaking the "Edit this page" links on their schema config reference pages. This PR adds a source_url to each moved plugin to use as the link for editing.
https://konghq.atlassian.net/browse/DOCU-3841
For example, see https://deploy-preview-7386--kongdocs.netlify.app/hub/kong-inc/response-transformer-advanced/configuration/
=> chore: Set source URLs for moved EE plugins

api-specs/Gateway-OSS/3.3/kong-oss-33.json, api-specs/Gateway-OSS/3.3/kong-oss-33.yaml, api-specs/Gateway-OSS/3.4/kong-oss-3.4.json, api-specs/Gateway-OSS/3.4/kong-oss-3.4.yaml, api-specs/Gateway-OSS/3.5/kong-oss-3.5.yaml, api-specs/Gateway-OSS/latest/kong-oss.yaml
Remove references to the `plugin.ordering` field from OSS OpenAPI docs.
=> fix(admin-oss): Plugin ordering is an EE-only feature

app/_data/tables/support/gateway/versions/28.yml, app/_data/tables/support/gateway/versions/34.yml, app/_data/tables/support/gateway/versions/35.yml, app/_data/tables/support/gateway/versions/36.yml, app/_data/tables/support/gateway/versions/37.yml
Full support for RHEL 8 ends this month: https://access.redhat.com/product-life-cycles?product=Red%20Hat%20Enterprise%20Linux,OpenShift%20Container%20Platform%204
Full support for RHEL 7 also ended a while ago but we still list it, and have been building packages for a while. Will address that issue (if it is an issue) separately.
Preview link: https://deploy-preview-7400--kongdocs.netlify.app/gateway/latest/support-policy/
=> Fix: Set accurate EOL for RHEL8

.github/styles/kong/auto-ignore.txt, app/_hub/kong-inc/ai-proxy/_changelog.md, app/_hub/kong-inc/ai-proxy/how-to/_sdk-usage.md, app/_hub/kong-inc/ai-proxy/how-to/_streaming.md, app/_hub/kong-inc/ai-proxy/overview/_index.md
Adds documentation for the new streaming mode for the AI proxy plugin for 3.7.
DOCU-3768
Preview link: 
- https://deploy-preview-7293--kongdocs.netlify.app/hub/kong-inc/ai-proxy/unreleased/how-to/sdk-usage/
- https://deploy-preview-7293--kongdocs.netlify.app/hub/kong-inc/ai-proxy/unreleased/how-to/streaming/
=> feat: AI Proxy streaming

app/_hub/kong-inc/ai-proxy/overview/_index.md
Add version tags to plugin table, since streaming only appears in 3.7.
Preview link:
=> chore: set version tags around table

.github/styles/kong/dictionary.txt, app/_hub/kong-inc/request-validator/overview/_index.md
request-validation limitations are not listed anymore since 3.4 version. Adding them in the main page
https://github.com/Kong/docs.konghq.com/commit/b492d3ecb31e2335f37dfe361295c8bc545f2e85#diff-f88716a1e934cd881cb07ecb1cc41ebdcd62fd950aa0e821603755e1a8caa2d4
New feature in 3.6 to perform body validation on +json content-types.
Preview link: 
- [ x ] Review label added 
- [ x ] [Conditional version tags](https://docs.konghq.com/contributing/conditional-rendering/#conditionally-render-content-by-version) added, if applicable.
=> add content-type and body-validation explanation in _index.md

app/_hub/kong-inc/ai-azure-content-safety/overview/_index.md, app/_hub/kong-inc/ai-prompt-decorator/overview/_index.md, app/_hub/kong-inc/ai-prompt-guard/overview/_index.md, app/_hub/kong-inc/ai-prompt-template/overview/_index.md, app/_hub/kong-inc/ai-proxy/overview/_index.md, app/_hub/kong-inc/ai-rate-limiting-advanced/overview/_index.md, app/_hub/kong-inc/ai-request-transformer/overview/_index.md, app/_hub/kong-inc/ai-response-transformer/overview/_index.md
Fixing 3.7 links showing up in 3.6.
Preview link: https://deploy-preview-7420--kongdocs.netlify.app/hub/kong-inc/ai-proxy/#all-ai-gateway-plugins
=> fix: Pass release variable to links include

app/_includes/md/enterprise/deploy-license.md, app/_includes/md/gateway/setup.md
Add info on updating a license to license deploy doc.
Removed httpie formatted instructions, they shouldn't exist anymore.
Fixes https://konghq.atlassian.net/browse/FTI-5982
Preview link: https://deploy-preview-7433--kongdocs.netlify.app/gateway/latest/licenses/deploy/#deploy-the-license
=> Update: Make license update info easier to find

app/_data/docs_nav_gateway_3.7.x.yml, app/_data/kong_versions.yml
Releasing the docs for for Gateway 3.7.
Will create an  "unreleased" 3.8 branch after this is merged, as we need to create placeholder plugin schemas for 3.8.
Preview link:  https://deploy-preview-7412--kongdocs.netlify.app/gateway/
* https://github.com/Kong/docs.konghq.com/milestone/59?closed=1
Code freeze on all doc updates that aren't for this release.
```
make clean && make build
netlify dev
cd tools
cd broken-link-checker
node full.js --host <http://localhost:8888>
```
=> Release: Gateway 3.7.0.0

app/konnect/org-management/audit-logging/reference.md
Incorrect: application/text
Correct: text/plain
The description of `Context-Type` is incorrect.
The actual webhook received is `text/plain`.
Preview link:
=> Fixed Context-Type

app/_hub/kong-inc/openid-connect/how-to/_cert-bound-access-tokens.md
Converting HTTPie to curl. This topic was added in 3.6 and I ran out of time to convert it, so we just merged it.
Preview link: https://deploy-preview-7422--kongdocs.netlify.app/hub/kong-inc/openid-connect/how-to/cert-bound-access-tokens/
=> chore: Convert remaining OIDC topic that uses httpie to curl

app/_includes/md/plugins-hub/log-format.md
Fixed Log Format Indentation 
Preview link: [link](https://app.netlify.com/sites/kongdocs/deploys/664f896b0caadc0009df3a0f)
=> fix log format indentation

app/_hub/kong-inc/app-dynamics/overview/_index.md
During testing, it was found that Kong Gateway will start without the library, and won't error out.
https://konghq.atlassian.net/browse/DOCU-3862
Preview link:
=> Fix: remove inaccurate note about AppDynamics library

app/_src/gateway/support/sbom.md
https://konghq.atlassian.net/browse/DOCU-3802
Preview link: https://deploy-preview-7337--kongdocs.netlify.app/gateway/latest/support/sbom/
=> chore: 3.7 SBOM link

app/_data/installation/gateway.yml
* Updating 3.7 gpg and rsa keys public keys, the old ones were wrong.
This test should pass: https://github.com/Kong/docs.konghq.com/actions/runs/9306681536
Check https://deploy-preview-7442--kongdocs.netlify.app/gateway/3.7.x/install/linux/debian/?install=oss to see the correct gpg key.
=> Fix installation docs for 3.7

.github/workflows/install-instructions-test.yml
The localhost instruction is only accurate when testing locally. In the GH action, it tests against the prod site by default.
Preview link:
=> chore: Update label for install workflow [skip ci]

app/_data/tables/support/gateway/versions/28.yml, app/_data/tables/support/gateway/versions/34.yml, app/_data/tables/support/gateway/versions/35.yml, app/_data/tables/support/gateway/versions/36.yml, app/_data/tables/support/gateway/versions/37.yml
Reverts Kong/docs.konghq.com#7400
Was changed in error due to confusion in terminology. We will continue supporting RHEL 8 until either full EOL, or the EOL of the Kong version - whichever comes first.
=> Revert "Fix: Set accurate EOL for RHEL8"

app/_includes/plugins/hub-examples/terraform.html, app/_plugins/drops/plugins/examples/terraform.rb, app/_plugins/drops/plugins/hub_examples.rb
Fix Terraform examples with nested objects + lists of objects
Old:
```hcl
resource "konnect_gateway_plugin_ai_proxy" "my_ai_proxy" {
enabled = true
config = {
route_type = "llm/v1/chat"
auth = "{"header_name"=>"Authorization", "header_value"=>"Bearer <OPENAI_API_TOKEN>"}"
model = "{"provider"=>"openai", "name"=>"gpt-4", "options"=>{"max_tokens"=>512, "temperature"=>1.0}}"
}
control_plane_id = konnect_gateway_control_plane.my_konnect_cp.id
route = {
id = konnect_gateway_route.my_route.id
}
}
```
New:
```hcl
resource "konnect_gateway_plugin_ai_proxy" "my_ai_proxy" {
enabled = true
config = {
route_type = "llm/v1/chat"
auth = {
header_name = "Authorization"
header_value = "Bearer <OPENAI_API_TOKEN>"
}
model = {
provider = "openai"
name = "gpt-4"
options = {
max_tokens = 512
temperature = 1.0 …
```
=> Fix Terraform example generation

app/_src/gateway/plugin-development/pluginserver/go.md
Fix the outdated link to the Go plugin examples
Preview link:
=> Fix link to Go plugin examples

app/_src/gateway/reference/rate-limiting.md
Added the doc for the added interface `ratelimiting.new_instance` in the rate-limiting library.
https://konghq.atlassian.net/browse/FTI-5918
Preview link: https://deploy-preview-7455--kongdocs.netlify.app/gateway/latest/reference/rate-limiting/
=> feat(rate-limiting): add the doc for the added interface in rate-limiting library

app/_src/gateway/install/linux/ubuntu.md
The release name for Ubuntu is hardcoded in the URL, as most of our users are on Jammy. For those that aren't, they need to replace the distro name with their own. This info exists, but is noted _before_ the steps start, which meant that people weren't seeing the information. Moving the info into the relevant steps to make it clearer.
Fixes https://konghq.atlassian.net/browse/KAG-4608.
Preview link:
=> Fix: Move Ubuntu install distro note into steps

app/_data/installation/gateway.yml
Adds the keys from https://cloudsmith.io/~kong/repos/gateway-38/pub-keys
This is a no-op.
Preview link: https://deploy-preview-7483--kongdocs.netlify.app/
Sibling to: https://github.com/Kong/gateway-docker-compose-generator/pull/162
=> Add gateway-38 repo keys

app/_includes/md/kic/crd-ref/kong_plugin_description.md, app/_src/kubernetes-ingress-controller/concepts/annotations.md, app/_src/kubernetes-ingress-controller/concepts/custom-resources.md, app/_src/kubernetes-ingress-controller/reference/annotations.md
During work on
- https://github.com/Kong/kubernetes-ingress-controller/issues/5749
- https://github.com/Kong/kubernetes-ingress-controller/issues/5602
it's been spotted that docs do not mention all CRDs that support `konghq.com/plugins` annotation, this PR improves it. 
Preview link: 
- https://deploy-preview-7352--kongdocs.netlify.app/kubernetes-ingress-controller/latest/reference/custom-resources/#kongplugin
- https://deploy-preview-7352--kongdocs.netlify.app/kubernetes-ingress-controller/latest/concepts/annotations/#main
- https://deploy-preview-7352--kongdocs.netlify.app/kubernetes-ingress-controller/latest/concepts/custom-resources/#kongplugin (the diagrams should be updated too)
=> chore(kic): list all CRDs that supports konghq.com/plugins annotation

.github/styles/kong/dictionary.txt, app/_src/kubernetes-ingress-controller/reference/feature-gates.md
We [won't sanitize `KongPlugin` and `KongClusterPlugin`'s `config`](https://github.com/Kong/kubernetes-ingress-controller/pull/6138) - this PR documents that explicitly.
Preview link: https://deploy-preview-7468--kongdocs.netlify.app/kubernetes-ingress-controller/latest/reference/feature-gates/#sanitizekonnectconfigdumps
=> docs(kic): explicitly document SanitizeKonnectConfigDumps

app/_hub/kong-inc/jwt-signer/overview/_index.md
The consumer mapping priority order for the plugin is supposed to include both access token and channel token, but instead just listed access tokens. 
Also clarifying some of the phrasing around mapping so that it doesn't appear to contradict itself
https://konghq.atlassian.net/browse/DOCU-3413
Preview link: https://deploy-preview-7484--kongdocs.netlify.app/hub/kong-inc/jwt-signer/#consumer-mapping
=> Fix: Typo in JWT mapping order and clarify behavior

app/_src/kubernetes-ingress-controller/reference/annotations.md
Document feature introduced in 
- https://github.com/Kong/kubernetes-ingress-controller/pull/5977
Preview link: https://deploy-preview-7351--kongdocs.netlify.app/kubernetes-ingress-controller/3.1.x/reference/annotations/#konghqcomheaders-separator
=> kic: document newly added `konghq.com/headers-separator` annotation

.github/styles/kong/auto-ignore.txt, app/_data/docs_nav_kic_3.2.x.yml, app/_src/kubernetes-ingress-controller/guides/customize/image.md, app/_src/kubernetes-ingress-controller/guides/services/custom-entity.md
Add a guide page for using custom entities in KIC. Fixes #7479 
Preview link: 
https://deploy-preview-7486--kongdocs.netlify.app/kubernetes-ingress-controller/unreleased/guides/services/custom-entity/#test-the-service-with-the-degraphql-plugin
=> docs(kic 3.2) add guide page for example in configuring custom entity

app/_src/gateway/admin-api/index_latest.md
Customers were requesting a table that explains which status codes the admin API returns and what those codes mean.
DOCU-2952
Preview link:
=> fix: Table that expresses all HTTP responses returned by the admin API

app/_src/gateway/kong-manager/consumer-groups.md
There is a limited number of supported plugins for consumer groups, but that list changes with each release. Instead of manually maintaining a list (that is currently unmaintained), linking to https://docs.konghq.com/hub/plugins/compatibility/#scopes for the most accurate generated info.
Preview link:
=> Fix: Replace list of consumer groups plugins with link

app/_hub/TheLEGOGroup/aws-request-signing/_metadata/_index.yml
Remove extra word in compat list for the AWS Request signing plugin. The compatibility has to be an array of versions, not a boolean.
Preview link:
=> Fix: Remove extra word in plugin metadata

app/_data/docs_top_nav.yml
Adding AI Gateway to top nav.
Removing Kuma to keep our nav formatting. Kuma docs are now fully contained within Mesh docs, so the link is essentially a duplicate.
Preview link: https://deploy-preview-7513--kongdocs.netlify.app/
=> chore: Replace Kuma with AI Gateway in top nav

app/_src/gateway/install/docker/build-custom-images.md
Replaced some placeholder links with links to Dockerhub
Preview link: /gateway/3.7.x/install/docker/build-custom-images/
=> Fix DockerHub links in Docker custom image instructions

app/_src/kubernetes-ingress-controller/guides/high-availability/fallback-config.md
Enables KIC config dumps in the fallback configuration guide as we rely on it in instructions.
Preview link: 
https://deploy-preview-7516--kongdocs.netlify.app/kubernetes-ingress-controller/latest/guides/high-availability/fallback-config/
=> fix: enable config dumps in fallback guide

app/_data/docs_nav_konnect.yml, app/konnect/reference/terraform.md
Add Terraform page for Konnect so that it shows up when searching for "Terraform" on the docs site.
Please run the Algolia indexer after merge
Preview link: [/konnect/reference/terraform/](https://deploy-preview-7500--kongdocs.netlify.app/konnect/reference/terraform/)
=> Add Konnect Terraform reference page

app/_data/konnect_oas_data.json, app/_src/gateway/admin-api/index_latest.md, app/konnect/api/index.md
Removing beta label from admin API specs. 
The changes are staged in Konnect.
=> Chore: Remove beta label from Admin API specs

app/_src/kic-v2/references/version-compatibility.md
Found an edge case to https://github.com/Kong/jekyll-generator-single-source/pull/16 
where without a line break it wont render the table.
=> Fix: Fix rendering on version compatibility table

app/_src/gateway/production/deployment-topologies/hybrid-mode/setup.md
The '-alpine' tag does not exist after 3.4. This will lead to an error when the user copies and executes the command.
Preview link:
=> Remove -alpine in the image tag

app/_includes/md/kic/prerequisites.md, app/_src/kubernetes-ingress-controller/guides/services/grpc.md
`GRPCRoute` is now GA and does not require the experimental CRDs or `GatewayAlpha` flag.
Preview link: /kubernetes-ingress-controller/latest/guides/services/grpc/
=> GRPCRoute is no longer experimental

app/_src/gateway/kong-enterprise/plugin-ordering/index.md
https://konghq.atlassian.net/browse/FTI-6019
Preview link: https://deploy-preview-7523--kongdocs.netlify.app/gateway/latest/kong-enterprise/plugin-ordering/
=> Fix: Adjust description for consumer scoped plugin limitation

app/_src/gateway/production/logging/update-log-level-dynamically.md
It is not currently possible to change log level of a DP from a CP.
Issue reported on Slack: https://kongstrong.slack.com/archives/C03CTMSHP6C/p1718352130665089
Preview link: https://deploy-preview-7524--kongdocs.netlify.app/gateway/latest/production/logging/update-log-level-dynamically/
=> Update: Clarify that `/debug` doesn't work for DPs

app/_data/kong_versions.yml, app/gateway/changelog.md
Changelog and version bump for 3.4.3.10
Preview link: https://deploy-preview-7529--kongdocs.netlify.app/gateway/changelog/#34310
=> Release: Gateway 3.4.3.10

app/konnect/gateway-manager/data-plane-nodes/upgrade.md
Documentation does not line up with the product: instead of Update Cluster Config should be Edit or Resize Cluster
Preview link:
=> Fix: instead of Update Cluster Config should be Edit or Resize Cluster

app/_hub/kong-inc/openid-connect/how-to/_demonstrating-proof-of-possession.md
=> fix(dpop): ambiguity of key validation description

app/_data/kong_versions.yml, app/gateway/changelog.md
changelog and version bump for 3.5.0.6
Preview link:
=> Release: Gateway 3.5.0.6

app/_src/gateway/plugin-development/pluginserver/javascript.md
The title of the JS PDK doc looks like an accidental copy & paste that included the section name. Renaming the page to match the other PDKs, eg https://docs.konghq.com/gateway/latest/plugin-development/pluginserver/python/.
Preview link:
=> Fix: JavaScript PDK page title

app/_src/kubernetes-ingress-controller/guides/requests/rewrite-host-and-paths.md
KIC 3.2 content was being rendered in the 3.1 docs.
cc @fabianrbz we should probably error out if `gte:` `lte:` or `:eq` can't be found in the `if_version` tag
Preview link: [/kubernetes-ingress-controller/3.1.x/guides/requests/rewrite-host-and-paths/#path-manipulation](https://deploy-preview-7587--kongdocs.netlify.app/kubernetes-ingress-controller/3.1.x/guides/requests/rewrite-host-and-paths/#path-manipulation)
=> Add missing : to if_version tags in KIC docs

app/_hub/kong-inc/graphql-rate-limiting-advanced/_metadata/_index.yml, app/_layouts/plugins/configuration_examples.html, docs/templates/kong-plugin-template/_metadata/_index.yml
Adding a disclaimer to plugin basic examples about not using the examples in prod, and adding some extra language for the GraphQL RLA examples to caution against `sync_rate = -1` with the `cluster` strategy.
We can use this same templating to add extra example descriptions to any of the plugins in the future.
https://konghq.atlassian.net/browse/DOCU-3489
Additional note for GraphQL RLA:  https://deploy-preview-7590--kongdocs.netlify.app/hub/kong-inc/graphql-rate-limiting-advanced/how-to/basic-example/
=> Fix: GraphQL RLA example needs a warning to not run in prod

app/_hub/kong-inc/rate-limiting-advanced/overview/_index.md, app/_hub/kong-inc/rate-limiting/overview/_index.md
Both rate-limiting and rate-limiting-advanced plugins documentation specify that various policies are possible and states that `cluster` and `redis` are "Accurate". However it's possible to configure a `sync_rate` option for these plugins and set it to a value that does not offer synchronous behaviour allowing for some slippage in favor of performance.
This commit clarifies that `sync_rate` affects mentioned accuracy.
KAG-2896
https://github.com/Kong/kong/issues/11846
Preview link:
- [rate-limiting](https://deploy-preview-7607--kongdocs.netlify.app/hub/kong-inc/rate-limiting/#strategies)
- [rate-limiting-advanced](https://deploy-preview-7607--kongdocs.netlify.app/hub/kong-inc/rate-limiting-advanced/#strategies)
=> chore(rate-limiting): clarify rate-limiting accuracy

app/_includes/plugins/hub-examples/terraform.html
Version is no longer part of `server_url` in Terraform
Preview link:
=> Remove version from Terraform plugin examples

app/_src/gateway/install/linux/ubuntu.md
There's an unexpected `-v` without a version currently. This adds the version back in
Preview link: [/gateway/3.7.x/install/linux/ubuntu/?install=oss](https://deploy-preview-7622--kongdocs.netlify.app/gateway/3.7.x/install/linux/ubuntu/?install=oss)
=> Fix Ubuntu install script versions

api-specs/Gateway-EE/3.5/kong-ee-3.5.yaml, api-specs/Gateway-EE/3.6/kong-ee-3.6.yaml, api-specs/Gateway-EE/latest/kong-ee.yaml
In 3.6.0.0, the /consumers and /consumer_groups list endpoints started supporting pagination. The response payload changed from containing consumer and consumer_groups to data as the key in the response payload
https://konghq.atlassian.net/browse/DOCU-3883
=> Add pagination to consumers and consumer_groups endpoints in Admin API specs

app/_hub/kong-inc/ai-request-transformer/overview/_index.md
This PR is to fix the description about the execution order of the ai-request-transformer plugin
Preview link:
=> fix description about the execution order of the ai-request-transformer plugin

app/_assets/stylesheets/sidebar.less, app/_includes/plugins/sidebar.html, app/_layouts/extension.html, spec/templates/plugin_with_versions_spec.rb
Moving the plugins CTA out of a content banner and into the sidebar, which should help because:
* It now appears on every page in a particular plugin, not just the landing page for it
* Makes it noticeable but not in the way
* We can apply the callout to every plugin that's possible to use in Konnect (currently doesn't appear on Konnect Free plugins)
Preview link: Check Kong Enterprise plugins, Kong OSS plugins, and third-party plugins. The button should appear everywhere except the third-party plugins.
https://deploy-preview-7630--kongdocs.netlify.app/hub/kong-inc/ai-proxy/
https://deploy-preview-7630--kongdocs.netlify.app/hub/kong-inc/ai-rate-limiting-advanced/
https://deploy-preview-7630--kongdocs.netlify.app/hub/salt/salt/
=> chore: Move the plugins CTA into sidebar

app/_hub/kong-inc/key-auth-enc/_metadata/_index.yml, app/hub/plugins/compatibility/index.md, app/konnect/compatibility.md
* Fixing[ misleading/confusing note for Key Auth Enc](https://docs.konghq.com/hub/plugins/compatibility/#authentication:~:text=Key%20Authentication%20%2D%20Encrypted-,The%20time%2Dto%2Dlive%20(ttl)%20does%20not%20work%20in%20Konnect%20or%20hybrid%20mode.%20This%20setting%20determines%20the%20length%20of%20time%20a%20credential%20remains%20valid.,-LDAP%20Authentication), which was not providing enough info about why the plugin doesn't run in Konnect. 
* Rephrasing the "Not applicable" table entries in the konnect compatibility table to say "Not available in Konnect" to make it clearer
Preview link:
=> Fix: Key Auth Encrypted note and "not applicable" konnect labels

app/_data/docs_nav_gateway_3.7.x.yml, app/_data/docs_nav_gateway_3.8.x.yml, app/_includes/md/about-plugins.md
This link was leading to 404
Preview link: https://deploy-preview-7637--kongdocs.netlify.app/hub/plugins/overview/
=> fix(404): update link to plugin development guide

api-specs/Gateway-OSS/latest/kong-oss.yaml
Patched the schema definition for `target-request` in the OpenAPI Specification (OAS) to update the request body structure. The change emphasizes the `target` property as a direct attribute with a default value and descriptive documentation, enhancing clarity and usability.
The current request body now ensures better alignment with actual payload expectations, streamlining API interactions and improving developer experience.
To test this change:
1. Import the updated OpenAPI Specification into Postman.
2. Attempt to create an upstream target using the old payload structure.
3. Compare the behavior with the updated payload structure to observe the refined handling of `target` property.
Preview link:
=> Fix: Updated kong-oss.yaml

app/konnect/org-management/okta-idp.md
=> Fix: Broken relative links in Okta IDP documentation

app/_src/gateway/breaking-changes/36x.md
In 3.6.x their was a breaking change for HTTP/2 requests involving content-length of request body.  This was fixed in 3.7.0.0 and backported to 3.6.1.1.
This PR reflects that information in the 3.6.x changelog.
Preview link:
=> Added fix information for HTTP/2 content length breaking change

app/konnect/reference/plugins.md
Users are not warned about the limitations of Dynamic plugin ordering, particularly in relation to consumer scoped plugins.  This change informs of the limitation and provides a link to the details.
Users are not warned about the limitations of Dynamic plugin ordering in this page, particularly in relation to consumer scoped plugins. This change informs of the limitation and provides a link to the details. There have been cases of customers implementing dynamic ordering and then realise it is incompatible with consumer scoped plugins.
Preview link:
=> Provide link to limitations of dynamic plugin ordering

app/_src/mesh/index.md
Added alt text to three diagrams in the Kong Mesh docs.
I wasn't sure if there were any guidelines about the length of the alt text, so let me know if they should be shorter.
[DOCU-1709](https://konghq.atlassian.net/browse/DOCU-1709)
[DOCU-1709]: https://konghq.atlassian.net/browse/DOCU-1709?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix: Add alt text to Kong Mesh diagrams

app/_hub/kong-inc/opentelemetry/overview/_index.md
docs for https://github.com/Kong/kong/pull/13291
Preview link: 
KAG-4779
=> feat(observability): OpenTelemetry logs

app/_src/gateway/kong-enterprise/secrets-management/backends/hashicorp-vault.md
This PR adds a section to the Kong Gateway's HashiCorp Vault backend, describing how Kong does authentication and retrieving secrets by calling HashiCorp Vault's API. This could help users to set a correct `mount`, `namespace`, `auth_path` and secret reference path.
https://konghq.atlassian.net/browse/FTI-6071
Preview link:
=> chore: add more explanation for hashicorp vault's authentication and secret fetching

app/_includes/md/admin-listen.md, app/_includes/md/gateway/setup.md
Now that if_version uses the same whitespace handling we no longer need to do weird hacks to make conditionals work right, like closing an if_version block in the line below.
This type of hack cause issues when sending the files to Smartling and downloading them.
Preview link:
=> fix: Use inline if_version blocks

app/_src/gateway/kong-enterprise/aws-iam-auth-to-rds-database.md
This is a new feature developed in 3.8.
The PR adds the corresponding descriptions about how to enable the new feature that does role assuming when doing RDS IAM authentication.
https://konghq.atlassian.net/browse/KAG-4561
Preview link:
=> feat: add documentation about assume role support for rds iam authentication

app/gateway/changelog.md
This PR fixes an inconsistency changelog entry that `bumps lua-resty-healthcheck from 3.0.2 to 3.1.0`. The true purpose of this bumping is to remove the version check of another dependency library called `lua-resty-events`.
For 3.6.1.7 changelog on gateway side: https://github.com/Kong/kong-ee/pull/9615/files#diff-4a52a116e1f88a220681718511ab310665400da44b3934fadb1cc00544cbb4e3R15
For 3.7.1.2 changelog on gateway side: https://github.com/Kong/kong-ee/pull/9616/files#diff-40a27ffd90374a9ecc9cd699e3e0e9f7a417b14e001f716baf1674c883b23875R15
The PR also replaces the changelog entry that `bumps lua-resty-healtcheck from 3.0.1 to 3.0.2`(for gateway branches 3.6/3.7) and `bumps lua-resty-healthcheck from 1.6.4 to 1.6.5`(for gateway branches 3.4/3.5) with a better sentence(the sentence).
Preview …
=> fix(changelog): fix some changelog entry related to lua-resty-healthcheck bump

app/_src/gateway/kong-manager/auth/sessions.md
adding `idling_timeout` config for Kong Manager session (same as session plugin)
Preview link:
=> adds idling_timeout session parameter

app/_src/gateway/plugin-development/custom-entities.md
The `postgresql` key is wrong and should be `postgres`. 
Can check this in any plugin migrations file for our existing plugins, eg: https://github.com/Kong/kong/blob/master/kong/plugins/acl/migrations/000_base_acl.lua
Fixes https://github.com/Kong/docs.konghq.com/issues/5584.
Preview link:
=> Fix: wrong postgres key in plugin migrations examples

app/konnect/network.md
Adding API instructions to find control plane and telemetry hostnames for Konnect control planes. Tested both regular and KIC control planes.
The headings on this page were also broken and didn't work as anchor links, as they were nested inside navtabs. This doesn't work, so I turned them into regular headings.
Fixes https://github.com/Kong/docs.konghq.com/issues/6869.
Preview link: https://deploy-preview-7681--kongdocs.netlify.app/konnect/network/
=> Update: Add API instructions for finding Konnect hostnames

app/_hub/kong-inc/ai-proxy/how-to/llm-provider-integration-guides/_mistral.md
The description of the example and the example itself don't refer to the same format: the description says `ollama` but the example uses `openai`. The correct format is `openai`, as the example also uses an Authorization header, which is required for `openai`.
Fixes https://github.com/Kong/docs.konghq.com/issues/7609.
=> AI Proxy plugin: fix incorrect format in example

app/_data/kong_versions.yml, app/gateway/changelog.md
Changelog and version bump for 2.8.4.12.
Do not merge until the patch goes out.
Preview link: https://deploy-preview-7693--kongdocs.netlify.app/gateway/changelog/
=> Release: Gateway 2.8.4.12

app/gateway/2.8.x/install-and-run/centos.md
As of 2.8.4.12, we are no longer building Centos packages for Gateway 2.8. Changing the variables on the 2.8 page to hardcoded so that they don't pick up a version of a package that doesn't exist. The version no longer needs to change dynamically with releases.
Preview link:
=> Fix: Hardcode gateway version in centos doc

app/konnect/dev-portal/create-dev-portal.md
The prior sentence states that `and are discoverable on the internet` for Public Dev Portals. It seems like it would be good to  explicit that private are not (which is just an assumption I made)
Preview link:
=> Add clarifying statement about private dev portals

api-specs/Gateway-EE/3.5/kong-ee-3.5.yaml
Direct entities: /consumers and /consumer_groups (they have pagination support as of 3.5.0.2, which means they have data keys)
https://konghq.atlassian.net/browse/DOCU-3883
=> Fix: API Docs need update to reflect the current API response format

app/_plugins/blocks/kgo_podtemplatespec_example.rb, app/_src/gateway-operator/customization/data-plane-image.md, app/_src/gateway-operator/get-started/kic/create-gateway.md, app/_src/gateway-operator/get-started/kic/create-route.md, app/_src/gateway-operator/guides/ai-gateway.md, app/_src/gateway-operator/guides/autoscaling-workloads/overview.md, app/_src/gateway-operator/topologies/dbless.md
Make version of Gateway API APIVersion depend on KGO version.
Preview links
- https://deploy-preview-7686--kongdocs.netlify.app/gateway-operator/latest/get-started/kic/create-gateway/
- https://deploy-preview-7686--kongdocs.netlify.app/gateway-operator/latest/get-started/kic/create-route/
- https://deploy-preview-7686--kongdocs.netlify.app/gateway-operator/latest/guides/ai-gateway/
- https://deploy-preview-7686--kongdocs.netlify.app/gateway-operator/1.3.x/customization/data-plane-image/#using-gatewayconfiguration
=> kgo: make Gateway API APIVersion, depend on KGO version

app/_src/mesh/features/cert-manager.md
Missing docs for existing feature
Preview link:
=> docs(mesh): document caCert for cert-manager

app/_hub/kong-inc/key-auth-enc/overview/_index.md
https://kongstrong.slack.com/archives/CDSTDSG9J/p1722881243530569
We can only issue a request using key Id and not with the key itself.
=> Fix: key-auth-enc plugin request must use key_id

app/_src/deck/guides/multi-file-state.md
Fixing the select-tag examples in the decK docs to match real behavior. 
https://konghq.atlassian.net/browse/DOCU-4012
Preview link:
=> Fix: decK select tag examples

app/_src/gateway/kong-enterprise/secrets-management/backends/aws-sm.md
This PR adds a note to show a correct way of referencing secrets that has special slash symbols.
https://konghq.atlassian.net/browse/KAG-5054
Preview link:
=> chore: add more explanations about aws secret with slash in kong gateway

app/_hub/kong-inc/key-auth/overview/_index.md
I've read and re-read this section a few times - and I'm pretty sure there's a typo! But my apologies in advance if I've misunderstood the situation.
Kong will return a 401 when the API key is **not** known.
=> Update key-auth request behaviour matrix

changelog.md
This is a scheduled pull request to update the changelog.
=> Automated Changelog update [skip-ci]

app/_src/gateway/production/monitoring/healthcheck-probes.md
Updated the response code for when Kong readiness probe fails (not a 500 but a 503). Also updated references to Kong to use the dynamic doc generated feature.
N/A
=> Fix: Health Check Probes

app/_src/gateway/kong-enterprise/plugin-ordering/index.md
According to tests, this seems to be unique to each workspace. In other words, one workspace can still use dynamic ordering if consumer-scoped plugins are in use as long as the consumer-scoped plugins are in a different workspace than the one using dynamic ordering for example. This created confusion with a customer and required manual testing.
Case #[00047793](https://kong.lightning.force.com/lightning/r/Case/500PJ00000E12XaYAJ/view?ws=%2Flightning%2Fr%2FAccount%2F0014100001jcxrkAAA%2Fview).
N/A
=> Fix: Clarify workspace instead of environment for Dynamic Plugin Ordering feature

app/_hub/kong-inc/opentelemetry/_changelog.md
Issue reported on slack: certain parameters in the OTEL plugin are marked deprecated, but there is no changelog entry noting when the deprecation happened.
Preview link:
=> Fix: Add changelog entry for deprecated OTEL parameters in 3.7

package-lock.json, package.json
Lock spec-renderer and kongponents to the version without the toggle bug.
Looks like dependabot force-pushed the branch with my change on it. Setting the version back to the ones that work
Preview link:
=> Lock spec-renderer and kongponents to the version without the toggle bug

app/_data/tables/support/gateway/versions/38.yml, app/_src/gateway/support/index.md
- Added EOL for 3.8
- Removed support for RHEL 7 and Debian 10
DOCU-4030
Preview link:
=> chore(3.8): Update support matrix

app/konnect/org-management/sso.md
Table currently displays like this because of a missing backtick:
Preview link: https://deploy-preview-7819--kongdocs.netlify.app/konnect/org-management/sso/#reference
=> Fix: broken table in Konnect SSO doc

app/_hub/kong-inc/mtls-auth/how-to/_add-cert-authorities.md
The mTLS plugin doc contains an example of using the Konnect API with a generated cookie, which hasn't been possible for a long time. Fixing the example to reference a PAT instead.
Preview link:
=> Fix: Konnect example in mtls plugin

app/_hub/kong-inc/mtls-auth/how-to/_add-cert-authorities.md
Fixing mTLS auth examples:
* Incorrect URL in Konnect example
* Split response out from Admin API example to reduce confusion
Preview link:
=> Fix: Errors in mTLS Auth examples

app/_src/gateway/kong-enterprise/db-encryption.md
Kong 3.8 Enterprise will allow optional encryption of license payloads for users of the keyring db encryption feature:
* https://github.com/Kong/kong-ee/pull/9885
* https://github.com/Kong/kong-ee/pull/10023
* [KAG-5144](https://konghq.atlassian.net/browse/KAG-5144)
This adds a short blurb to the existing keyring docs to explain the feature.
https://deploy-preview-7835--kongdocs.netlify.app/gateway/unreleased/kong-enterprise/db-encryption/#configure-license-payload-encryption
[KAG-5144]: https://konghq.atlassian.net/browse/KAG-5144?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(gateway): document keyring license encryption for 3.8

app/_hub/kong-inc/hmac-auth/overview/_index.md
Fixes https://konghq.atlassian.net/browse/FTI-6211.
Preview link: https://deploy-preview-7841--kongdocs.netlify.app/hub/kong-inc/hmac-auth/#hmac-example
=> Fix: HMAC signing string in plugin example

app/_src/gateway/reference/key-management.md
The key set examples use a `PUT` method, which is not allowed by the API. The examples should be using `POST`. 
Fixed the method and switched all the `HOSTNAME` placeholders to our standard `localhost`.
Fixes #7838.
Preview link: https://deploy-preview-7842--kongdocs.netlify.app/gateway/latest/reference/key-management/#create-a-key-using-the-jwk-format-and-associate-it-with-a-key-set
=> Fix: Key set examples

app/_redirects, app/_src/gateway/kong-enterprise/consumer-groups/index.md, app/_src/gateway/kong-manager/consumer-groups.md
There are a few links to the consumer groups API point that point to 3.3.0.0 instead of `latest`. Updating to remove the hardcoded version.
Fixes https://github.com/Kong/docs.konghq.com/issues/7824. 
Preview link: 
https://deploy-preview-7843--kongdocs.netlify.app/gateway/latest/kong-enterprise/consumer-groups/
https://deploy-preview-7843--kongdocs.netlify.app/gateway/latest/kong-manager/consumer-groups/
=> Fix: Consumer groups versioned links

app/_src/gateway/breaking-changes/38x.md
Added 3.8 breaking changes (or what I thought were) from the changelog to the doc.
DOCU-4038
Preview link:
=> chore: 3.8 breaking changes

app/_hub/kong-inc/ai-rate-limiting-advanced/_metadata/_index.yml
The plugin currently appears twice because it's listed under two categories, and it should only be under AI: 
Issue reported by on Slack by Marco.
Preview link: search the plugin hub in the preview for "AI Rate Limiting Advanced" and make sure it only appears once.
=> fix: Remove AI RLA plugin from traffic control category on plugin hub

app/_hub/kong-inc/aws-lambda/_changelog.md
Adding a missing changelog entry for `base64_encode_body` (tracked down via blame in https://github.com/Kong/kong/commit/5853f9d0c0bb6afce4b6d3165cacbd86bb46b8d2). 
Since we no longer have specific docs for version 2.5.x, we don't need to update the config reference.
Fixes https://github.com/Kong/docs.konghq.com/issues/5544.
Preview link:
=> Fix: AWS Lambda plugin changelog entry for base64_encode_body

app/_hub/kong-inc/exit-transformer/overview/_index.md
Correcting the description of `handle_unknown`, which is currently misleading and doesn't provide enough context.
Fixes https://konghq.atlassian.net/browse/FTI-6080
Preview link: https://deploy-preview-7848--kongdocs.netlify.app/hub/kong-inc/exit-transformer/
=> Fix: Exit Transformer plugin handle_unknown description

api-specs/Gateway-EE/3.3/kong-ee-3.3.json, api-specs/Gateway-EE/3.3/kong-ee-3.3.yaml, api-specs/Gateway-EE/3.4/kong-ee-3.4.json, api-specs/Gateway-EE/3.4/kong-ee-3.4.yaml
Preview link: 
KM-468
DOCU-4054
=> docs(consumer_groups): add prefix `/{workspace}` for consumer_groups's endpoint in 3.3 and 3.4

app/_hub/kong-inc/app-dynamics/overview/_index.md
Adding ANALYTICS_ENABLE env variable to the AppDynamics env variables table.
Discovered via changelog entry.
@oowl what kind of analytics get logged via this variable, and _is_ it sending the data to AppD?
Preview link: https://deploy-preview-7861--kongdocs.netlify.app/hub/kong-inc/app-dynamics/unreleased/#environment-variables
=> Feat: AppD analytics_enable

app/_data/docs_nav_gateway_3.8.x.yml, app/_src/gateway/reference/configuration/configuration-3.8.x.md
The conf file has been generated and updated, but it's not showing up in the 3.8 preview because the nav wasn't updated.
Preview link:
=> Chore: Update link to kong.conf in 3.8 nav file

app/_src/gateway/kong-enterprise/aws-iam-auth-to-rds-database.md, app/_src/gateway/kong-enterprise/secrets-management/backends/aws-sm.md
This is a new feature in kong gateway 3.8. The original PR is here: https://github.com/Kong/kong-ee/pull/9654
The feature covers the update for three parts of the AWS-related features inside Kong gateway: the aws-lambda plugin, the aws vault backend, and the IAM authentication for RDS database.
KAG-4599
Preview link:
=> feat(aws): add custom sts endpoint configuration field for various aws features in kong gateway

app/_includes/md/gateway/upgrade-paths.md
https://konghq.atlassian.net/browse/DOCU-4031
Will be revisiting these paths following the release to see if this is still needed, for now just updating them regularly.
Preview link:
=> chore: upgrade paths for 3.8

app/_src/gateway/how-kong-works/routing-traffic.md
Fixed the URL for proxy_next_upstream to direct to Nginx documentation for that property. 
Fixes issue noted here: https://kongstrong.slack.com/archives/CDSTDSG9J/p1725897019405109
N/A
=> Fix: Correct the URL for Nginx proxy_next_upstream property

app/_hub/kong-inc/header-cert-auth/overview/_index.md
Adding a section on how to increase the header size limit so that certs aren't blocked or truncated.
Info provided on Slack: https://kongstrong.slack.com/archives/CDSTDSG9J/p1725983347871329?thread_ts=1725973425.599459&cid=CDSTDSG9J
Preview link: https://deploy-preview-7884--kongdocs.netlify.app/hub/kong-inc/header-cert-auth/unreleased/#header-size
=> Update: Add info about Header Cert Auth size limits

app/konnect/org-management/teams-and-roles/roles-reference.md, app/konnect/org-management/teams-and-roles/teams-reference.md
https://konghq.atlassian.net/browse/DOCU-3995
=> Service Catalog: teams and roles

app/_hub/traceableai/traceableai/overview/_index.md
Traceable overview page had "Overview" as title instead of "Traceable.io" because of the title element in the frontmatter.
=> Fix: Traceable overview title

app/_hub/kong-inc/ai-semantic-prompt-guard/how-to/_index.md
Added Redis in the prerequisites since it is needed to use the plugin
Preview link: 
- [N/A] [Conditional version tags](https://docs.konghq.com/contributing/conditional-rendering/#conditionally-render-content-by-version) added, if applicable.
=> Fix: Add missing prerequisites to AI semantic prompt guard plugin

app/_data/docs_nav_konnect.yml, app/_includes/md/konnect/azure-peering.md, app/konnect/gateway-manager/data-plane-nodes/azure-peering.md
https://konghq.atlassian.net/browse/DOCU-4041
=> Feat: Azure Vnet peering for Cloud Gateways

app/hub/plugins/license-tiers.md
Adjust table widths on plugins license tiers page.
Follow-up to https://github.com/Kong/docs.konghq.com/pull/7896#issuecomment-2343466920.
Preview link: https://deploy-preview-7912--kongdocs.netlify.app/hub/plugins/license-tiers/
=> fix: adjust table widths

app/_plugins/drops/plugins/badges.rb, spec/app/_plugins/drops/plugins/badges_spec.rb
Plugin Hub feature request: show both oss and enterprise badges when a plugin is supported in both.
Preview link: https://deploy-preview-7914--kongdocs.netlify.app/hub/
=> Update: Plugin Hub cards show both EE and OSS when both are supported

app/_assets/stylesheets/hub-landing-page.less
With so many badges on a card (up to 4 potentially, and often 3), the spacing looks awkward now, and doesn't look like the elements belong with each other. Reducing the spacing between badges (especially when on two lines) to have a better association between elements.
Before:
After:
Preview link:
=> Chore: Adjust badge spacing on hub landing page

app/konnect/gateway-manager/data-plane-nodes/renew-certificates.md
added docker copy command to move cert and key ointo container before restarting the gateway
Preview link:
=> Add docker copy command to move cert and key into container before restarting the gateway

app/_assets/entrypoints/application.js, app/_assets/stylesheets/header.less, app/_includes/nav-v2.html
Removing the Summit Hackathon banner with the call for submissions, as the deadline was yesterday and the hackthon is now over.
Preview link: Check that no banner appears at the top of the screen in the preview.
=> chore: disable summit hackathon banner

app/_plugins/blocks/inline_plugin_example/config.rb, app/_plugins/drops/plugins/examples/terraform.rb, app/_plugins/drops/plugins/hub_examples.rb, spec/app/_plugins/drops/plugins/example_spec.rb
Enabled TF example generation for all plugins.
Preview link: [/hub/kong-inc/ai-semantic-prompt-guard/how-to/basic-example/](https://deploy-preview-7915--kongdocs.netlify.app/hub/kong-inc/ai-semantic-prompt-guard/how-to/basic-example/)
=> Enable Terraform examples for all plugins

app/_src/deck/guides/run-with-docker-1.28.md, app/_src/deck/guides/run-with-docker.md
While working on decK docs, ran into this page and found that it had incorrect commands that set the port twice (`KONG_ADMIN_HOST:KONG_ADMIN_PORT:8001`), likely because of a copy/paste error. Tested all of them to make sure this wasn't some strange convention - it does not need the port twice.
Didn't convert to localhost, since this is connecting to Gateway from within the Docker container. If you're running on `localhost`, you need to use `host.docker.internal`, which will cause even more confusion. 
There was also one command that had the filename in the wrong position, fixed that as well.
Preview link: https://deploy-preview-7923--kongdocs.netlify.app/deck/latest/guides/run-with-docker/
=> Fix: broken command examples for running decK with Docker

app/_hub/kong-inc/json-threat-protection/_changelog.md, app/gateway/changelog.md
Document a known issue for the JSON threat protection plugin.
Issue reported in https://konghq.atlassian.net/browse/KAG-5398.
Preview link: https://deploy-preview-7924--kongdocs.netlify.app/gateway/changelog/#known-issues
=> Update: 3.8 known issue for JSON threat protection plugin

app/_hub/kong-inc/app-dynamics/overview/_index.md, app/_layouts/extension.html
* Documenting the ARM64 limitation for the C/C++ AppD SDK
* Fixing the collapsible note
https://konghq.atlassian.net/browse/DOCU-4061
Collapsible note with broken styling: https://docs.konghq.com/hub/kong-inc/app-dynamics/
Preview link: https://deploy-preview-7921--kongdocs.netlify.app/hub/kong-inc/app-dynamics/
=> Fix: AppD plugin missing info + broken collapsible note

app/_hub/kong-inc/ai-semantic-cache/_metadata/_index.yml
The AI Semantic Cache plugin is appearing in multiple categories, it should only be in one.
Preview link:
=> Fix: Remove AI Semantic Cache plugin from traffic control category

app/_src/kubernetes-ingress-controller/guides/requests/rewrite-annotation.md
Added prerequisite to call out that the `RewriteURIs` feature gate needs to be enabled for this annotation to work. 
Fixes an issue discovered when troubleshooting support case #00049247.
N/A
=> Fix: Add missing prerequisite for Rewrite URI annotation

app/_hub/kong-inc/ai-semantic-cache/how-to/llm-provider-integration-guides/_mistral.md, app/_hub/kong-inc/ai-semantic-cache/how-to/llm-provider-integration-guides/_openai.md, app/contributing/kong-plugins.md
Converting the LLM examples to use `plugin_example` instead for better consistency.
DOCU-4060
Preview link:
=> fix: Convert to AI Semantic Cache LLM examples to `plugin_example`

app/_includes/docs-sidebar.html
Adding AI Gateway to the docs left sidebar dropdown, and linking to the hub.
Putting it under Mesh to mimic the order on the Kong site.
Request from Marco.
Preview link: Check any page with a products dropdown, eg https://deploy-preview-7946--kongdocs.netlify.app/gateway/latest/.
=> Chore: Add AI Gateway to sidebar dropdown

app/_hub/kong-inc/app-dynamics/overview/_index.md
Some of the newer parameters for the AppDynamics plugin are missing the `_APPD` section of the prefix. They should all be `KONG_APPD_*`.
Preview link: https://deploy-preview-7945--kongdocs.netlify.app/hub/kong-inc/app-dynamics/#environment-variables
=> Fix: Add missing `_APPD` to env variables

app/_data/kong_versions.yml
decK latest version is set to 1.38 even though 1.40 is already out.
Preview link: https://deploy-preview-7944--kongdocs.netlify.app/deck/latest/
=> fix: decK latest version

app/_hub/kong-inc/acl/how-to/_consumer-groups.md.md, app/_hub/kong-inc/ai-azure-content-safety/how-to/_index.md, app/_hub/kong-inc/ai-proxy-advanced/how-to/_cloud-provider-authentication.md, app/_hub/kong-inc/ai-proxy-advanced/how-to/llm-provider-integration-guides/_anthropic.md, app/_hub/kong-inc/ai-proxy-advanced/how-to/llm-provider-integration-guides/_azure.md, app/_hub/kong-inc/ai-proxy-advanced/how-to/llm-provider-integration-guides/_cohere.md, app/_hub/kong-inc/ai-proxy-advanced/how-to/llm-provider-integration-guides/_llama2.md, app/_hub/kong-inc/ai-proxy-advanced/how-to/llm-provider-integration-guides/_mistral.md, app/_hub/kong-inc/ai-proxy-advanced/how-to/llm-provider-integration-guides/_openai.md, app/_hub/kong-inc/ai-proxy/how-to/_cloud-provider-authentication.md, app/_hub/kong-inc/http-log/how-to/_splunk.md, app/_hub/kong-inc/openid-connect/how-to/_demonstrating-proof-of-possession.md, app/_hub/kong-inc/openid-connect/how-to/authentication/_authorization-code-flow.md, app/_hub/kong-inc/openid-connect/how-to/authentication/_client-credentials.md, app/_hub/kong-inc/openid-connect/how-to/authentication/_introspection.md, app/_hub/kong-inc/openid-connect/how-to/authentication/_jwt-access-token.md, app/_hub/kong-inc/openid-connect/how-to/authentication/_kong-oauth-token.md, app/_hub/kong-inc/openid-connect/how-to/authentication/_password-grant.md, app/_hub/kong-inc/openid-connect/how-to/authentication/_refresh-token.md, app/_hub/kong-inc/openid-connect/how-to/authentication/_session.md, app/_hub/kong-inc/openid-connect/how-to/authentication/_user-info.md, app/_hub/kong-inc/openid-connect/how-to/authorization/_acl.md, app/_hub/kong-inc/openid-connect/how-to/authorization/_claims.md, app/_hub/kong-inc/openid-connect/how-to/authorization/_consumer.md, app/_hub/kong-inc/openid-connect/how-to/client-authentication/_mtls.md, app/_hub/kong-inc/opentelemetry/how-to/_dynatrace.md, app/_hub/kong-inc/opentelemetry/how-to/_getting-started.md, app/_plugins/blocks/plugin_example.rb
Adding Terraform as an option for any instance of `plugin_examples`.
@mheap are there any situations where this doesn't apply? All of the plugins with these example blocks are available in Konnect.
Preview link: Check any of the updated plugins, eg https://deploy-preview-7926--kongdocs.netlify.app/hub/kong-inc/openid-connect/how-to/authentication/authorization-code-flow/.
=> chore: Add terraform tab to plugin_examples blocks

app/_src/deck/guides/konnect.md
A user ran into an issue where, based on the doc phrasing, they assumed that `--konnect` is an existing flag for decK.  
Adjusting the sentence to remove confusion.
Fixes https://github.com/Kong/docs.konghq.com/issues/7950.
Preview link:
=> Update: Adjust decK Konnect flag phrasing to remove ambiguity

app/_data/kong_versions.yml, app/gateway/changelog.md
Changelog and version bump for 2.8.4.13.
Don't merge until release goes out.
See https://kongstrong.slack.com/archives/C02GZ0CGJNT/p1726668953815289 for release status.
Preview link: https://deploy-preview-7942--kongdocs.netlify.app/gateway/changelog/#28413
=> Release: Gateway 2.8.4.13

app/_hub/kong-inc/request-transformer/how-to/_templates.md
- Added undocumented "shared" substitution variable to documentation based on the specification defined in the plugin sources.
- Removed extraneous trailing character from code samples in the same section
- request-transformer sources: https://github.com/Kong/kong-plugin-request-transformer/blob/master/kong/plugins/request-transformer/access.lua#L87-L89
Preview link:
=> Add `shared` to list of available substitution sources in _templates.md

app/_src/kubernetes-ingress-controller/reference/troubleshooting.md
Adds a Konnect integration section to the troubleshooting guide. 
Preview link: https://deploy-preview-7853--kongdocs.netlify.app/kubernetes-ingress-controller/latest/reference/troubleshooting/#debugging-konnect-integration
=> docs(kic): add konnect integration troubleshooting section

app/_hub/kong-inc/ai-semantic-prompt-guard/_metadata/_index.yml
Konnect compatibility is incorrectly set as false in the plugin. Double-checked, it is available in Konnect.
Preview link:
=> Chore: Set AI Semantic Prompt Guard as Konnect-compatible

app/_hub/kong-inc/ai-semantic-prompt-guard/_metadata/_index.yml
=> fix(plugins): ai semantic prompt guard is EE-only

app/konnect/org-management/teams-and-roles/teams-reference.md
The Data Plane Node Admin and Service Admin roles no longer exist.  Looks like that's been the case for at least a year: https://github.com/Kong/kong-api-tests/blob/main/fixtures/kauth/kauth_teams.ts
Removed non-existent roles and added Control Plane Admin. Verified via UI and link above.
Preview link: https://deploy-preview-7986--kongdocs.netlify.app/konnect/org-management/teams-and-roles/teams-reference/
=> Fix: update konnect predefined teams

app/konnect/dev-portal/access-and-approval/manage-teams.md
This PR updates the docs for portal RBAC 
- replace `GATEWAY_SERVICE_ID` with `API_PRODUCT_ID` in assigned-roles example
-  add missing `entity_region` in assigned-roles example
Preview link: https://deploy-preview-7969--kongdocs.netlify.app/konnect/dev-portal/access-and-approval/manage-teams/#create-developer-teams
=> fix(portal): replace GATEWAY_SERVICE_ID with API_PRODUCT_ID [TDX-4644]

app/_src/gateway/get-started/index.md
The get.konghq.com repo is private, so we shouldn't link to it from docs.
Replaced it with instructions on how to see all options for the script.
Fixes https://github.com/Kong/docs.konghq.com/issues/5539.
Preview link: https://deploy-preview-7987--kongdocs.netlify.app/gateway/latest/get-started/
=> Fix: remove link to get.konghq.com repo

app/_src/gateway/production/running-kong/secure-admin-api.md
issue reported through docs feecback
Preview link:
=> Fix: Config file structure

app/_src/gateway/get-started/proxy-caching.md
https://github.com/Kong/docs.konghq.com/issues/5262
=> Bug bash: Wrong statement about cache hit meaning

app/_hub/kong-inc/acme/how-to/_index.md, app/_hub/kong-inc/acme/how-to/_local-testing-development.md, app/_hub/kong-inc/acme/overview/_index.md
* Added a table comparing the types of storage, what they are (info from [lua-resty-acme](https://github.com/fffonion/lua-resty-acme#storage-adapters)), and where they're available
* Minor adjustments to the ACME overview page for better flow with the table
* Tested the local storage guide and fixed it up to make it work + made the curl formatting consistent
Fixes https://github.com/Kong/docs.konghq.com/issues/7966 and https://konghq.atlassian.net/browse/DOCU-2910.
Preview link: 
https://deploy-preview-7996--kongdocs.netlify.app/hub/kong-inc/acme/
https://deploy-preview-7996--kongdocs.netlify.app/hub/kong-inc/acme/how-to/local-testing-development/
=> ACME plugin storage types

app/gateway/changelog.md
Some dates weren't in the ISO 8601 format, this fixes that.
DOCU-3877
Preview link:
=> fix: Change Gateway changelog dates to ISO 8601 format

app/konnect/api-products/service-documentation.md, app/konnect/dev-portal/publish-service.md
I updated our Dev Portal docs to state which versions of Swagger and OpenAPI are supported for uploaded API specs. 
I tested this by trying to upload example OpenAPI specs created by ChatGPT:
- 1.1 ❌ 
- 2.0 ✅ 
- 3.0 ✅ 
- 3.2 ✅ 
DOCU-3594
Preview link:
=> fix: Add notes about OpenAPI spec version compatibility

app/konnect/mesh-manager/service-mesh.md
I updated our Mesh Manager tutorial so that it uses the same demo app as what they're using in the Kong Mesh docs. 
I also verified that my changes worked by testing the full tutorial end-to-end.
Fixes #6625 
Preview link:
=> Change the demo app used in the mesh manager example

api-specs/Gateway-EE/3.7/kong-ee-3.7.yaml, api-specs/Gateway-EE/latest/kong-ee.yaml
Fixes https://github.com/Kong/docs.konghq.com/issues/7809
=> Bug bash: status endpoint not clear on port

app/_src/mesh/installation/docker.md
Fixed the version variable on the Docker Mesh install docs to stop pointing to `latest` and point to current page version instead. Pulled the resulting docker images with no issue.
Checked the rest of the Mesh install docs, this issue only happens on Docker.
Fixes https://github.com/Kong/docs.konghq.com/issues/4991.
Preview link: https://deploy-preview-8013--kongdocs.netlify.app/mesh/2.1.x/installation/docker/
=> Fix version variable on old mesh docker installs

app/_includes/md/gateway/upgrade-paths.md
Update the 3.1.x upgrade paths table to tell people to migrade to 3.1.1.x directly, as per the [changelog.](https://docs.konghq.com/gateway/changelog/#3113)
Fixes #5755.
Preview link: https://deploy-preview-8010--kongdocs.netlify.app/gateway/3.1.x/upgrade/#guaranteed-upgrade-paths
=> Fix: upgrade paths in 3.1.x

app/_src/gateway/plugin-development/pdk/kong.websocket.client.md, app/_src/gateway/plugin-development/pdk/kong.websocket.upstream.md
The websocket PDK pages are missing Enterprise badges, so users think that the functionality is available in OSS.
Fixes https://github.com/Kong/docs.konghq.com/issues/5555. 
Preview link: 
https://deploy-preview-8012--kongdocs.netlify.app/gateway/latest/plugin-development/pdk/kong.websocket.client/
https://deploy-preview-8012--kongdocs.netlify.app/gateway/latest/plugin-development/pdk/kong.websocket.upstream/
=> Add Enterprise badges to websocket PDK references

app/_data/tables/breaking_changes_lts.yml
We still list Deb 10 as an upgrade option, but Deb 10 is no longer supported.
Debian 9 was never supported, so we skip mentioning it.
Issue reported on Slack: https://kongstrong.slack.com/archives/CDSTDSG9J/p1727890089951339
Preview link:
=> Update supported Debian versions in upgrade guide table

app/konnect/gateway-manager/kic.md
The link in the note on the Konnect KIC page redirects to the KIC landing page: https://docs.konghq.com/konnect/gateway-manager/kic/#kic-in-konnect-association 
Replacing it with the latest real link.
Preview link:
=> Fix: Broken link in Konnect KIC page

app/_hub/kong-inc/correlation-id/overview/_index.md
Fixes https://github.com/Kong/docs.konghq.com/issues/5123
Preview: https://deploy-preview-8006--kongdocs.netlify.app/hub/kong-inc/correlation-id/
=> Bug bash: Logging correlation IDs doc does not specify the nginx context 

app/_src/gateway/plugin-development/custom-logic.md
Fixes https://github.com/Kong/docs.konghq.com/issues/7533
=> bug-bash: Change phase to directive in custom logic doc

app/gateway/changelog.md
Removing any "backported from" lines from the Gateway changelog, as they were causing many issues:
* Manually maintained, so the editor needs to have knowledge that an entry already exists, or else look for it in the changelog - this is difficult because the phrasing can change
* Inconsistently added - since this is manually maintained, it's hard to keep this content accurate, and difficult to tell which version the original change came from. Items get missed all the time.
* Doesn't add enough value (or much value at all) to warrant the maintenance
Preview link:
=> chore: Remove backport lines from Gateway changelog

app/_src/gateway/get-started/index.md
We have to pass the `-s` command to the bash script in order to pass additional arguments to the quickstart script.
The original help command gives the following error:
```
$ curl -Ls https://get.konghq.com/quickstart | bash -- -h
bash: -h: No such file or directory
```
Preview link:
=> fix(docs): fix the quickstart help command

app/konnect/service-catalog/index.md, app/konnect/service-catalog/integrations/github.md
Fixes capitalization of GitHub.
Preview link:
=> fix: fix capitalization of GitHub

api-specs/Konnect/control-planes-config/control-planes-config.yaml, api-specs/Konnect/v0/yaml/mesh-control-planes.yaml, api-specs/Konnect/v1/yaml/ksearch.yaml, api-specs/Konnect/v2/yaml/analytics-requests.yaml, api-specs/Konnect/v2/yaml/api-products.yaml, api-specs/Konnect/v2/yaml/application-auth-strategies.yaml, api-specs/Konnect/v2/yaml/audit-logs.yaml, api-specs/Konnect/v2/yaml/control-planes.yaml, api-specs/Konnect/v2/yaml/portal-management.yaml, api-specs/Konnect/v3/yaml/identity.yaml, api-specs/portal.yaml
Generated OAS files from platform-api.
=> feat(sdk): automated oas update

app/_data/landing_page.yml
- Updated our docs home page tile so it says "Service Catalog" instead of "service hub"
- I also noticed that we were still linking to on-prem Dev Portal docs there, so I removed that link
https://kongstrong.slack.com/archives/CDSTDSG9J/p1728660833269209
Preview link:
=> fix: Update Service Catalog tile on docs home page

app/konnect/gateway-manager/configuration/index.md
Adds `| Consumer Group Member | 50,000 |`
=> Fix: Add consumer group member to config limits page

app/_src/gateway/plugin-development/custom-logic.md
This actually should have been done in 0d121e25e3 when we removed the same warning from the WebSocket PDK docs.
=> Remove unstable warning from WebSocket plugin handler docs

app/_data/docs_nav_gateway_3.8.x.yml, app/_data/docs_nav_gateway_3.9.x.yml, app/_hub/kong-inc/ai-proxy-advanced/how-to/_load-balancing.md, app/_hub/kong-inc/ai-proxy-advanced/overview/_index.md
- Added link to AI proxy advanced load balancing in navigation under AI Gateway
- Updated AI proxy advanced overview to add missing load balancing algorithms and a section about retry/fallback
- Removed the semantic routing section and included the info in the load balancer algorithms section
- Added config example for each load balancer type
[DOCU-4076](https://konghq.atlassian.net/browse/DOCU-4076)
Preview link: 
- [N/A] [Conditional version tags](https://docs.konghq.com/contributing/conditional-rendering/#conditionally-render-content-by-version) added, if applicable.
[DOCU-4076]: https://konghq.atlassian.net/browse/DOCU-4076?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update: AI proxy advanced load balancing

app/_src/gateway/ai-gateway/index.md, app/_src/gateway/get-started/ai-gateway.md
We've gotten feedback that the AI getting started script is difficult to use as it obfuscates what's actually happening in the setup. This changes the getting started guide to set up a service, route, and plugin manually, then test that the plugin is working. 
Tested this locally, still need to test the Konnect instructions.
I left the AI quickstart script in at the bottom of the page with a bit of info on how to use it, for those people that are still interested. This script is very useful for demos and testing and we don't want to lose it.
Preview link: https://deploy-preview-8056--kongdocs.netlify.app/gateway/latest/get-started/ai-gateway/
=> Update: Rewrite AI Gateway Getting Started guide

app/konnect/org-management/teams-and-roles/roles-reference.md
Update the Konnect roles reference to the most recent actual state of Konnect.
Includes the new serverless roles.
Entries pulled from UI text with very light editing. Eventually, I expect we'll be generating this, so we won't want to manually edit.
Preview link: https://deploy-preview-8065--kongdocs.netlify.app/konnect/org-management/teams-and-roles/roles-reference/
=> Fix: Konnect roles reference

app/konnect/gateway-manager/control-plane-groups/index.md
The diagram description was referring to the wrong group. Fixed that and broke it into bullet points for easier flow.
Issue reported on Slack: https://kongstrong.slack.com/archives/CDSTDSG9J/p1729691071079309
Preview link:
=> Fix: Clean up diagram description

app/_src/kubernetes-ingress-controller/concepts/architecture.md, app/_src/kubernetes-ingress-controller/concepts/custom-resources.md, app/_src/kubernetes-ingress-controller/get-started/services-and-routes.md
- Replaced images on the Architecture, Services and routes, and Custom Resources pages with mermaid diagrams
- I pretty much just copy/pasted all the text from the old examples into mermaid
Preview link:
=> fix: Replace old KIC images with mermaid diagrams

app/konnect/gateway-manager/index.md, app/konnect/gateway-manager/serverless-gateways/index.md, app/konnect/gateway-manager/serverless-gateways/provision-serverless-gateway.md
=> fix: tidy some serverless docs

app/_src/gateway/kong-manager/enable.md
Preview link: 
https://deploy-preview-8059--kongdocs.netlify.app/
KM-599
=> docs(*): add more tips while using multiple domains

app/_includes/md/enterprise/migration-finish-warning.md, app/_src/gateway/admin-api/workspaces/reference.md, app/_src/gateway/breaking-changes/34x.md, app/_src/gateway/migrate-ce-to-ke.md, app/_src/gateway/reference/cli.md, app/_src/gateway/upgrade/blue-green.md, app/_src/gateway/upgrade/in-place.md, app/gateway/changelog.md
We currently need force upgrading to make sure the schema is correct and up-to-date.
This PR adds warnings to the upgrading guide, API doc, and CLI doc.
KAG-5040
Preview link:
=> docs(workspace): Add warnings to kong migrations

app/_data/docs_nav_kgo_1.4.x.yml, app/_includes/md/custom-plugin.md, app/_includes/md/kgo/prerequisites.md, app/_src/gateway-operator/guides/plugin-distribution.md, app/_src/kubernetes-ingress-controller/plugins/custom.md
Closes https://github.com/Kong/gateway-operator/issues/381
The most important page of this PR - https://deploy-preview-8034--kongdocs.netlify.app/gateway-operator/unreleased/guides/plugin-distribution/
The page touched by this PR - https://deploy-preview-8034--kongdocs.netlify.app/kubernetes-ingress-controller/latest/plugins/custom/
=> kgo: document KongPluginInstallation

app/_data/docs_nav_kgo_1.4.x.yml, app/_src/gateway-operator/customization/pod-disruption-budget.md
Adds a guide explaining how to define PodDisruptionBudget for DataPlane deployments.
Part of https://github.com/Kong/gateway-operator/issues/142.
Preview link: https://deploy-preview-7729--kongdocs.netlify.app/gateway-operator/unreleased/customization/pod-disruption-budget/
=> docs(kgo): add PodDisruptionBudget guide

app/_src/gateway-operator/guides/konnect-plugin-binding.md
Add guide page for using `KongPluginBinding` to configure plugins with Konnect.
Fixes https://github.com/Kong/gateway-operator/issues/568.
Dependent on #8034 for adding navigator page for KGO 1.4. 
Preview link:
=> KGO: add guide for kongpluginbinding

app/_assets/stylesheets/badges.less, app/_data/tables/konnect/integrations.yml, app/_includes/service-catalog-integrations.html, app/konnect/service-catalog/index.md, app/konnect/service-catalog/integrations/github.md, app/konnect/service-catalog/integrations/index.md
Adds support for eventing. Including a new badge. 
https://konghq.atlassian.net/browse/DOCU-4110
=> Feat: Eventing support in Service Catalog

.github/styles/kong/dictionary.txt, app/_data/docs_nav_kgo_1.4.x.yml, app/_includes/md/kgo/check-condition.md, app/_includes/md/kgo/konnect-entities-prerequisites.md, app/_src/gateway-operator/guides/konnect-entities/dpcertificate.md, app/_src/gateway-operator/guides/konnect-entities/key-and-keyset.md, app/_src/gateway-operator/guides/konnect-entities/konnect-plugin-binding.md, app/_src/gateway-operator/guides/konnect-entities/upstream-and-target.md, app/_src/gateway-operator/guides/konnect-entities/vault.md
Minor edits to the `KongPluginBinding` guide for KGO.
Preview link: https://deploy-preview-8108--kongdocs.netlify.app/gateway-operator/unreleased/guides/konnect-entities/konnect-plugin-binding/
=> kgo: kongpluginbinding guide

app/_hub/kong-inc/opentelemetry/overview/_index.md
The new logging OTEL/OTLP feature also comes with a kong.telemetry.log PDK module. Adding a link to the module from the page that describes the feature.
Issue reported on Slack: https://kongstrong.slack.com/archives/CDSTDSG9J/p1730248794886169
Preview link: https://deploy-preview-8104--kongdocs.netlify.app/hub/kong-inc/opentelemetry/#logging-for-custom-plugins
=> chore: Add link to logging module

app/_src/gateway-operator/reference/custom-resources/1.4.x.md
update API reference for KGO EE v1.4.0 
Preview link:
=> chore(kgo-ee): update API reference for v1.4.0

app/_data/kong_versions.yml
Flip kgo 1.4.x to latest, release went out Oct 31: https://github.com/Kong/gateway-operator/releases/tag/v1.4.0
`unreleased` version to follow in another PR.
Preview link:
=> Release: KGO 1.4.x

app/_data/docs_nav_mesh_2.9.x.yml
This fix is required so that we don't end up adding the wrong Kuma sidebar in Mesh
Preview link:
=> fix(mesh): correct invalid sidebar reference

app/_data/kong_versions.yml
754c941984f1e02ad11d967fc7ff42c5cc6bba0f fix(guide): fix and move guide for Kubernetes Gateway API (kumahq/kuma-website#2060)
70a5b8d237b5d9776069e1cde6b4e96dcb276a3c chore(deps): bump rexml from 3.3.8 to 3.3.9 (kumahq/kuma-website#2059)
7239fa44de5b09888fbc0452bf374b9311abb5f2 fix(policies): fix policy examples to use default mesh (kumahq/kuma-website#2057)
5917de6d11c63f74cb00b783292ed5a4709ac4be chore: small styles and quality of life improvements (kumahq/kuma-website#2058)
e6fc2862d054925e1bc2addb876ec7f21d85d81f feat(policies): move policies examples to policy_yaml (kumahq/kuma-website#2052)
d8ba516f7eb0bd1ad0aef7d3a9659444fc6412cd fix(policyyaml) fix policy yaml backendref tags (kumahq/kuma-website#2056)
25a6db240df3cfef795db2e7f65a9dcccca96b9a feat(jekyll): add …
=> chore(deps): bump kumahq/kuma-website from 2e6d25cc to 754c9419

app/konnect/updates.md
Latest Konnect changelog entries from beamer
=> Automated Konnect changelog update [skip-ci]

app/_src/gateway/production/access-control/register-admin-api.md
Fixing this step formatting issue:
Preview link: https://deploy-preview-8073--kongdocs.netlify.app/gateway/latest/production/access-control/register-admin-api/
=> Fix: Admins examples broken steps formatting

app/_data/docs_nav_mesh_2.10.x.yml
06058d8956f90b8ed3052fd5275218d889994c32 chore(mk/run): use npx to execute netlify-cli (kumahq/kuma-website#2081)
2a45090e5ab135a84f162483db5d0e9802846ed6 feat(blog): add 2.9 release blogpost (kumahq/kuma-website#2065)
e7b4096ca65f9720ae43b92488c6f0c8d2306024 chore(deps): update docs from repo source (kumahq/kuma-website#2078)
e2ed501124b8de5e6fdc109f7473bd38aa67ebab fix(js): handle sidebar links without trailing "/" for active link detection (kumahq/kuma-website#2074)
f9202ba2541a41be41227824850e469365ec3de8 Bump jekyll-generator-single-source (kumahq/kuma-website#1623)
113414440922d05dc8fd5e1e6c631b2b4d75e24a feat(guides): update otel collector guide to work with newest otel collector (kumahq/kuma-website#2070)
4de1239a71c0307b76952e06911e04060ba9a225 feat(guides): …
=> chore(deps): bump kumahq/kuma-website from 754c9419 to 06058d89

app/_assets/stylesheets/pages/landing-page.less, app/_data/landing_page.yml
Adding AI Gateway as a key feature to our docs landing page.
Changed the rows to a two-column max because otherwise it's a 3-3-1 tile overhang. Not sure if I like this more, please take a look.
Preview link:
=> Update: Add AI Gateway tile to landing page

app/konnect/network.md
the [CONTROL_PLANE_ID.eu.cp0.konghq.com](http://control_plane_id.eu.cp0.konghq.com/) in the documentation is wrong, since it should actually be [CONTROL_PLANE_DNS_PREFIX.eu.cp0.konghq.com](http://control_plane_dns_prefix.eu.cp0.konghq.com/)
=> Fix: network requirements

app/konnect/gateway-manager/configuration/config-store.md
Correct config store queries and references.
Preview link:
=> fix: correct config store queries

app/_data/hub_filters.yml, jekyll-dev.yml, jekyll.yml
Fix plugin hub filters.
The filters now live in `app/_data/hub_filters.yml` and categories in `app/_data/extensions.yml`
Looks like that when we merged the jp changes there was a conflict and I didn't solve it correctly.
This updates the data files with the new values.
Preview link:
=> Fix plugins filters after a bad rebase

app/_includes/head.html
=> Fix hreflangs, they should have the full url

app/_src/deck/reference/deck_file_kong2tf.md
Explain that the `-g` flag is typically used in combination with`deck gateway dump --with-id`.
=> kong2tf -g typically used in combination with gateway dump --with-id

app/_hub/kong-inc/request-validator/overview/_index.md
The doc says the the Kong `format` schema validation is supported, which is incorrect. JSON Schema `format` validation is actually what's supported.
Fixes https://konghq.atlassian.net/browse/FTI-6196.
Note to reviewers: I fixed the title of the section referring to the "Kong format schema" and some minor cleanup to the page, including removing unnecessary output examples. 
However, I couldn't actually get these examples to work as documented in the example. The last step, validation, always fails for me- though this is probably out of scope of this PR and is a separate issue.
Preview link:
=> fix: Request Validator incorrectly refers to Kong format schema

app/konnect/gateway-manager/serverless-gateways/index.md, app/konnect/gateway-manager/serverless-gateways/provision-serverless-gateway.md
Quick clarification change to ensure users know that Serverless Gateways may not be provisioned in their current Konnect region.
Preview link:
=> feat: serverless provisioning clarification

app/_src/gateway/support/index.md, app/_src/gateway/support/third-party.md
Gateway 3.5 reached end of full support and entered sunset support on Nov 8th. 
Removing the support tabs for this version and adding an entry into the sunset support table.
Preview link:
=> chore: Gateway 3.5 moves into sunset support

app/_data/kong_versions.yml, app/gateway/changelog.md
Changelog and version bump for Gateway 3.7.1.3.
Also merge https://github.com/Kong/docs-plugin-toolkit/pull/74 when this goes in.
Preview link:
=> Release: Gateway 3.7.1.3

app/_src/kubernetes-ingress-controller/guides/services/custom-entity.md
The heading was set to H1, which is massive and we don't use H1s in text.
Preview link:
=> Fix: Heading level in KIC custom entities guide

.github/styles/kong/dictionary.txt, app/_data/docs_nav_konnect.yml, app/konnect/private-connections/aws-privatelink.md
Add docs page for PrivateLink.
[DOCU-3871](https://konghq.atlassian.net/browse/DOCU-3871)
[CSRE-2806](https://konghq.atlassian.net/browse/CSRE-2806)
Replaces Kong/docs.konghq.com#7771
[DOCU-3871]: https://konghq.atlassian.net/browse/DOCU-3871?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CSRE-2806]: https://konghq.atlassian.net/browse/CSRE-2806?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Feat: PrivateLink connection

app/konnect/gateway-manager/data-plane-nodes/secure-communications.md
Fixed the formatting of the certificate steps, it was messed up.
Preview link:
=> fix: step formatting in Secure Comms

app/_data/kong_versions.yml, app/gateway-operator/changelog.md
Bump KGO to 1.4.1
OSS release: https://github.com/Kong/gateway-operator/releases/tag/v1.4.1
EE release https://github.com/Kong/gateway-operator-enterprise/releases/tag/v1.4.1
Preview link: https://deploy-preview-8193--kongdocs.netlify.app/gateway-operator/changelog/#141
=> chore(kgo): bump to 1.4.1

app/_data/docs_nav_konnect.yml, app/_data/tables/konnect/integrations.yml, app/konnect/service-catalog/integrations/datadog.md
Adding Datadog as a new Service Catalog integration.
DOCU-4109
Preview link: https://deploy-preview-8154--kongdocs.netlify.app/konnect/service-catalog/integrations/datadog/
=> feat: Service Catalog Datadog integration 

app/_src/gateway-operator/reference/custom-resources/1.4.x.md
Follow up on #8193 for KGO 1.4.1
Part of https://github.com/Kong/gateway-operator/issues/893
Preview link: https://deploy-preview-8199--kongdocs.netlify.app/gateway-operator/latest/reference/custom-resources/
=> chore(kgo): bump to CRD docs 1.4.1

app/gateway/changelog.md
Add missing dependency bump changelong entry to 3.8.1.0 ([eng PR here](https://github.com/Kong/kong-ee/pull/10599)) and add detail to capture the customer issue. Support was unable to find the fix in the changelog, since the initial issue wasn't mentioned.
Issue reported on slack: https://kongstrong.slack.com/archives/CDSTDSG9J/p1732724038244199
Preview link:
=> Fix: missing changelog entry for dependency bump

app/_assets/stylesheets/collapsible-sections.less, app/_includes/md/kgo/prerequisites.md, app/_includes/md/kic/prerequisites.md
We've gotten multiple reports from users that they can't tell that the KIC and KGO prereq notes are supposed to be clickable & expandable. Changing these notes to use the styling that we use for the plugins.
Had to shorten the prereqs to be more concise, but they still look a bit weird. This styling is really not meant for full sentences. At the same time, I don't want to put anymore time into this, as this is temporary anyway.
https://konghq.atlassian.net/browse/DOCU-4124
Preview links for example pages: 
https://deploy-preview-8180--kongdocs.netlify.app/kubernetes-ingress-controller/latest/guides/services/http/
https://deploy-preview-8180--kongdocs.netlify.app/gateway-operator/latest/guides/plugin-distribution/
=> Fix: use prereq styling for KIC and KGO

app/_includes/md/kgo/konnect-entities-prerequisites.md
Fixing broken styling on konnect entities guides.
Preview link:
=> Fix: KGO prereq styling

app/_data/tables/support/gateway/packages.yml, app/_src/gateway/support/index.md, app/_src/gateway/support/third-party.md
Add tabs for 3.9 support tables + add ubuntu 24.04 to the data file (it's already in 39.yml, was just missing from here).
Preview link: 
https://deploy-preview-8210--kongdocs.netlify.app/gateway/unreleased/support-policy/#supported-versions
https://deploy-preview-8210--kongdocs.netlify.app/gateway/unreleased/support/third-party/
=> chore: Update 3.9 support tables

app/_data/tables/install_options.yml, app/_src/gateway/install/docker/build-custom-images.md
Bump UBI version and Ubuntu version in docker custom build doc.
Note: I pointed the instructions at ubi:9.5 because we also set a specific patch for ubi-8 (8.1, though the latest is now 8.10). We can also just point to latest, but I think that's bad practice?
Preview link:
=> Feat: RHEL UBI 9 support

app/_hub/kong-inc/header-cert-auth/overview/_index.md
Updated the FAQ to include a note about how the certificate should  be passed. The docs were not entirely clear that base64 and url encoding require different data to be passed (one including the being/end certificate delimiters). 
If this is not the proper place for the details I can update as needed.
Preview link:
=> Header Cert Auth plugin: cert format FAQ

app/_data/docs_nav_mesh_2.10.x.yml, app/_data/docs_nav_mesh_2.9.x.yml
We lost these sections between releases. This fixes this
Preview link:
=> fix(mesh): add lost SBOM sections in 2.9 and 2.10

app/_data/docs_nav_mesh_2.10.x.yml, app/_data/docs_nav_mesh_2.8.x.yml, app/_data/docs_nav_mesh_2.9.x.yml
Sidebar was still showing MeshOPA as beta, this is not beta since 2.8
=> fix(mesh): remove Beta from MeshOPA sidebar

app/_hub/kong-inc/opentelemetry/_changelog.md
- Update _changelog.md to include deprecation of config.endpoint
- Fix typo in config.batch_flush_delay deprecation
`2024/12/05 15:16:04 [warn] 2533#0: *1692 [kong] init.lua:910 OpenTelemetry: config.endpoint is deprecated, please use config.traces_endpoint instead (deprecated after 4.0), client: 172.19.0.1, server: kong_admin, request: "PUT /plugins/924e591e-5544-4ee8-8327-32625f0034f0 HTTP/1.1", host: "localhost:8001"
`
Preview link: 
- [x ] Review label added
=> Update opentelemetry  _changelog.md to include deprecation of config.endpoint in 3.8

app/_data/installation/gateway.yml
Updating the public RSA and GPG keys for 3.9 and 3.10, required for installation.
https://cloudsmith.io/~kong/repos/gateway-39/pub-keys/
https://cloudsmith.io/~kong/repos/gateway-310/pub-keys/
The 3.10 keys won't affect anything for now, this just preps us for the next release.
Preview link: https://deploy-preview-8231--kongdocs.netlify.app/gateway/unreleased/install/linux/ubuntu/?tab=apt-repository
=> Chore: update public keys

app/_hub/kong-inc/ai-proxy-advanced/how-to/llm-provider-integration-guides/_huggingface.md, app/_hub/kong-inc/ai-proxy-advanced/how-to/llm-provider-integration-guides/_openai.md, app/_hub/kong-inc/ai-proxy-advanced/overview/_index.md, app/_hub/kong-inc/ai-proxy/how-to/llm-provider-integration-guides/_huggingface.md, app/_hub/kong-inc/ai-proxy/overview/_index.md, app/_includes/md/plugins-hub/ai-providers-prereqs-advanced.md, app/_includes/md/plugins-hub/ai-providers-prereqs.md
Add docs for AI Proxy and AI Proxy Advanced configuration with Hugging Face.
[DOCU-4166](https://konghq.atlassian.net/browse/DOCU-4166)
Preview links:
- https://deploy-preview-8182--kongdocs.netlify.app/hub/kong-inc/ai-proxy/unreleased/how-to/llm-provider-integration-guides/huggingface/
- https://deploy-preview-8182--kongdocs.netlify.app/hub/kong-inc/ai-proxy-advanced/unreleased/how-to/llm-provider-integration-guides/huggingface/
[DOCU-4166]: https://konghq.atlassian.net/browse/DOCU-4166?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Feat: Add Hugging Face as LLM provider

app/konnect/gateway-manager/configuration/vaults/how-to.md
Add link to environment variable vault config options.
Preview link: https://deploy-preview-8245--kongdocs.netlify.app/konnect/gateway-manager/configuration/vaults/how-to/
=> Fix: Add missing vault config link

app/_src/gateway/kong-enterprise/consumer-groups/index.md
Removing outdated plugin list and replacing with link to plugin scopes, as this list changes with every release.
Also removing a duplicate note.
Preview link:
=> Fix: Consumer groups compatible plugins list

app/_src/gateway/kong-enterprise/datakit/configuration.md
Set datakit template varibles in jekyll `raw` tags so that it doesn't get confused and complain about liquid syntax.
Preview link:
=> Fix: adjust datakit doc to clear jekyll warning

app/_src/gateway/production/performance/performance-testing.md
The raw results could be found [here](https://docs.google.com/spreadsheets/d/1knu87tczpuTQ4a5si3WSkOoFHWf0pS8vqNpC44-Oxmw/edit?gid=1008586201#gid=1008586201)
=> Update performance-testing.md for 3.9 rc5

app/_data/docs_nav_kic_3.0.x.yml, app/_data/docs_nav_kic_3.1.x.yml, app/_data/docs_nav_kic_3.2.x.yml, app/_data/docs_nav_kic_3.3.x.yml, app/_data/docs_nav_kic_3.4.x.yml, app/_src/kubernetes-ingress-controller/reference/feature-gates.md
Drop 'beta' from feature gates toc heading
Preview link:
=> kic: drop 'beta' from feature gates toc heading

app/_src/kubernetes-ingress-controller/reference/troubleshooting.md
Adds documentation about KIC's diagnostics server `/debug/config/raw-error` endpoint.
Closes #7548
Preview link:
=> kic: add /debug/config/raw-error mention for KIC 3.4+

app/_src/kubernetes-ingress-controller/reference/ingress-to-gateway-migration.md
Changed the conversion from `konghq.com/plugins` in the Ingress to the Gateway API migration. The conversion should be placed under `httpRoute.spec.rules[*].filters` in the HTTPRoute resource.
Following the [ingress2gateway](https://github.com/kubernetes-sigs/ingress2gateway/blob/main/pkg/i2gw/providers/kong/plugins.go) tool and the [Gateway API](https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io%2fv1.HTTPRouteFilter) documentation, the plugins annotation should be filters rather than headers.
Preview link:
=> docs(kic): fix ingress to gateway migration plugins conversion

app/_hub/kong-inc/app-dynamics/overview/_index.md
Removed the mention of Alpine from AppD docs.
Although the AppD agent does [support Alpine as of May 2022](https://docs.appdynamics.com/appd/23.x/latest/en/product-and-release-announcements/past-releases/past-agent-releases#PastAgentReleases-Version22.3.1-March15,2022), Kong stopped supporting Alpine in 3.3.x, so the older versions get a mention of Alpine, while it's completely removed from the newest ones.
https://konghq.atlassian.net/browse/DOCU-4121 
Preview link:
=> Fix: Inaccurate OS support for AppD C SDK agent

app/konnect/account-management/index.md, app/konnect/gateway-manager/kic.md
We were missing info about KIC licenses in Konnect, so adding that.
https://konghq.atlassian.net/browse/DOCU-4144
Preview link:
=> Fix: clarify license propagation in Konnect

app/_data/docs_nav_konnect.yml, app/_src/gateway/kong-enterprise/consumer-groups/index.md, app/_src/gateway/kong-manager/consumer-groups.md, app/konnect/api/index.md, app/konnect/dev-portal/access-and-approval/manage-teams.md, app/konnect/gateway-manager/configuration/consumer-groups.md, app/konnect/gateway-manager/declarative-config.md, app/konnect/org-management/access-tokens.md
Addressing feedback we’ve received on consumer groups docs, where some of the docs are outdated (kong manager), one is missing from the nav but findable via search (Konnect), and links for how-to guides go to the Rate Limiting plugin, which is only one of the plugins that supports consumer groups. 
* The Kong Manager topic is very short and doesn't need to exist, but doesn't hurt to leave it for now
* The Konnect topic is a condensed version of upcoming how-to guides
* As part of this, splitting out the Personal Access Token info into its own doc, as we link to it a bunch (I needed to from  the consumer groups doc), but its buried in a decK page.
Fixes https://github.com/Kong/docs.konghq.com/issues/6465 and https://konghq.atlassian.net/browse/DOCU-3593
Preview link: …
=> Fix: Consumer groups docs

.github/styles/kong/dictionary.txt, app/_src/kubernetes-ingress-controller/guides/services/custom-entity.md
Add section about events in KIC's custom entities guide.
Preview link: https://deploy-preview-8246--kongdocs.netlify.app/kubernetes-ingress-controller/unreleased/guides/services/custom-entity/#invalid-kongcustomentity-configuration
=> kic: add events section to custom entities guide

app/_includes/md/kic/http-test-routing-resource.md, app/_src/kubernetes-ingress-controller/guides/custom-class/internal-external.md
Add introduction of how to split internal and external traffic using gateway APIs. 
Fixes https://github.com/Kong/kubernetes-ingress-controller/issues/5237.
Preview link: 
https://deploy-preview-7551--kongdocs.netlify.app/kubernetes-ingress-controller/latest/guides/custom-class/internal-external/
=> update gateway part in splitting traffic page

app/_hub/kong-inc/graphql-proxy-cache-advanced/_changelog.md, app/_src/gateway-operator/guides/konnect-entities/faq.md, app/_src/kubernetes-ingress-controller/plugins/custom.md, app/gateway/changelog.md
Removing the hardcoded `unreleased` version from links, which likely made its way in because the links were breaking at the time, and that seemed like the right fix. `unreleased` should never be part of a production URL.
Fixes https://github.com/Kong/docs.konghq.com/issues/8192
Preview link:
=> Fix: Clean out "unreleased" links 

app/_includes/md/kic/http-test-routing-resource.md, app/_src/kubernetes-ingress-controller/plugins/acl.md
Minor fixes to KIC's ACL guide.
Fixing whitespaces.
Before:
After:
Also not requiring `secret` field for non HMAC JWT credentials (ref: https://github.com/Kong/kubernetes-ingress-controller/pull/6848).
Preview link: /kubernetes-ingress-controller/unreleased/plugins/acl
=> kic: minor fixes in ACL guide

app/_src/gateway-operator/production/upgrade/gateway-operator.md
Add link to charts' `UPGRADE.md` in KGO's upgrade guide.
Preview link:
=> kgo: add UPGRADE.md in upgrade guide

app/_data/kong_versions.yml, app/gateway/changelog.md
Version bump and changelog for Gateway 3.4.3.14.
Preview link:
=> Release: Gateway 3.4.3.14

app/_hub/dynatrace/dynatrace/_metadata/_index.yml, app/_includes/md/plugins-hub/dynatrace.md, app/_layouts/extension.html
Moving the tile into the analytics and monitoring category.
The custom banner is because this isn't even a plugin - this is very much an edge case.
Preview link: https://deploy-preview-8289--kongdocs.netlify.app/hub/?search=dynatrace
=> Fix: dynatrace tile category

.github/styles/kong/dictionary.txt, app/_data/docs_nav_kic_3.4.x.yml, app/_includes/md/kic/ca-certificates-note.md, app/_includes/md/kic/http-test-routing-resource.md, app/_includes/md/kic/prerequisites.md, app/_includes/md/kic/verify-upstream-tls-backendtlspolicy.md, app/_includes/md/kic/verify-upstream-tls-ca.md, app/_src/kubernetes-ingress-controller/guides/security/verify-upstream-tls.md, app/_src/kubernetes-ingress-controller/plugins/mtls.md, app/_src/kubernetes-ingress-controller/reference/annotations.md
Adds a guide covering upstream TLS verification configuration features added in KIC 3.4. 
Part of https://github.com/Kong/docs.konghq.com/issues/8133 (this guide will have to be extended with Gateway API instructions once https://github.com/Kong/kubernetes-ingress-controller/issues/6631 is implemented).
KIC nightly image has to be used for testing:
```shell
helm upgrade --install kong kong/ingress -n kong --create-namespace --set controller.ingressController.image.repository=kong/nightly-ingress-controller --set controller.ingressController.image.tag=2024-11-28 --set controller.ingressController.image.effectiveSemver=3.4.0
```
Preview link: https://deploy-preview-8201--kongdocs.netlify.app/kubernetes-ingress-controller/unreleased/guides/security/verify-upstream-tls/
=> docs(kic): add upstream TLS verification guide

app/_data/docs_nav_kic_3.4.x.yml, app/_src/kubernetes-ingress-controller/reference/combined-services-from-different-httproutes.md, app/_src/kubernetes-ingress-controller/reference/feature-gates.md
Add introduction of feature `CombinedServicesFromDifferentHTTPRoutes` in feature gate page and a new reference page.
fixes #8216.
Preview link:
=> KIC: feat: add introduction about combined service from different httproutes

app/_hub/kong-inc/exit-transformer/overview/_index.md
The status code is not updated in the lua script so it should remain 401.
After follow the Demonstration, I got an 401 status code but the doc says it is a 200. 
```
❯ http  localhost:8000 Host:example.com
HTTP/1.1 401 Unauthorized
Connection: keep-alive
Content-Length: 73
Content-Type: application/json; charset=utf-8
Date: Wed, 18 Dec 2024 15:17:35 GMT
Server: kong/3.8.0.0-enterprise-edition
X-Kong-Request-Id: 10e6903070b3246162eeac7756792938
X-Kong-Response-Latency: 3
x-some-header: some value
{
"error": true,
"message": "No API key found in request, arr!",
"status": 401
}
```
=> fix the status code in the 1st Demonstration

app/_hub/kong-inc/injection-protection/overview/_index.md
Added an example Injection Protection plugin log.
Preview link:
=> fix: Add example Injection Protection plugin log

app/konnect/reference/search.md
Addition of `public_labels` KSearch syntax. Public labels are meant to provide a client-facing search syntax in KSearch for API Products in Developer Portals. This emulates the same syntax as `labels`, but for API clients browsing the Developer Portal
Preview link:
=> feat: Public labels search syntax for Dev Portal

app/_src/kubernetes-ingress-controller/upgrade/kic.md
Add section to guide KIC users to upgrade gateway API to 1.2 as KIC 3.4 has bumped the gateway API version.
Fixes #8282.
Preview link:
=> kic: add update guide for gateway API 1.2

app/_src/gateway-operator/get-started/kic/create-gateway.md
The docs tell you to copy the value from `runtimeGroupID` but it appears to have changed to `controlPlaneID` in Konnect.
Preview link:
=> docs(kic): provide correct field name from helm chart values.yaml

app/_src/deck/guides/konnect.md
Deck versions < 1.40.0 show incorrect `deck diff` information. This PR adds a warning to the Konnect/deck guide
Preview link: [/deck/latest/guides/konnect/](https://deploy-preview-8314--kongdocs.netlify.app/deck/latest/guides/konnect/)
=> Add minimum decK version to Konnect docs

app/_src/gateway/plugin-development/custom-entities.md, app/_src/gateway/plugin-development/entities-cache.md
Fixed several small typos in plugin development pages.
Preview link:
=> Fix: typos in plugin development

app/_data/kong_versions.yml
Update latest KIC to 3.4.1 
Preview link:
=> chore(kic): update latest to 3.4.1

app/gateway/changelog.md
The deprecation notice for rhel7 mentions the wrong kong version.
Checked all the other version entries (2.8 onward), all the rest are correct.
Issue reported on slack: https://kongstrong.slack.com/archives/CDSTDSG9J/p1736248819331859
Preview link:
=> Fix: RHEL7 deprecation version

app/_hub/kong-inc/proxy-cache/overview/_index.md
In [the description of Proxy Cache](https://docs.konghq.com/hub/kong-inc/proxy-cache/), it is explained that the cache key is calculated using the following expression.
```
key = md5(UUID | method | request)
```
However, in the source code of Proxy Cache (3.9.0), the cache key is calculated from the following five elements.
https://github.com/Kong/kong/blob/3.9.0/kong/plugins/proxy-cache/cache_key.lua#L111-L112
Because of that, I have updated the expression in the documentation to match it with the one of source code.
Preview link:
=> docs: update the key calculation expression of proxy cache

.github/workflows/linting.yml, tools/check-unreleased-label/package-lock.json, tools/check-unreleased-label/package.json, tools/check-unreleased-label/run.js
Fails the build if gateway/deck/kubernetes-ingress-controller does not have a version with `label: unreleased`
=> Add tool to error with missing unreleased version

app/_data/docs_nav_gateway_3.1.x.yml, app/_data/docs_nav_gateway_3.10.x.yml, app/_data/docs_nav_gateway_3.2.x.yml, app/_data/docs_nav_gateway_3.3.x.yml, app/_data/docs_nav_gateway_3.4.x.yml, app/_data/docs_nav_gateway_3.5.x.yml, app/_data/docs_nav_gateway_3.6.x.yml, app/_data/docs_nav_gateway_3.7.x.yml, app/_data/docs_nav_gateway_3.8.x.yml, app/_data/docs_nav_gateway_3.9.x.yml, app/_src/gateway/production/deployment-topologies/kubernetes.md
Add first attempt at a "Kong on Kubernetes" topology page
Preview link: [/gateway/latest/production/deployment-topologies/kubernetes/](https://deploy-preview-7480--kongdocs.netlify.app/gateway/latest/production/deployment-topologies/kubernetes/)
=> Add page on KIC vs Hybrid mode for Kubernetes

app/_src/deck/faqs.md, app/_src/deck/guides/konnect.md, app/konnect/compatibility.md, app/konnect/gateway-manager/control-plane-groups/migrate.md, app/konnect/gateway-manager/declarative-config.md
Versions of decK before 1.4 have some inconsistency issues when used with Konnect. We need to tell our users to use 1.40 with Konnect at a minimum.
issue reported on slack: https://kongstrong.slack.com/archives/C03NRECFJPM/p1734711282132209
Preview link:
=> Fix: Update decK compatible version with Konnect

app/_src/gateway/production/deployment-topologies/kubernetes.md
Add a note that KIC+Portal are not compatible
Preview link: [/gateway/latest/production/deployment-topologies/kubernetes/](https://deploy-preview-8335--kongdocs.netlify.app/gateway/latest/production/deployment-topologies/kubernetes/)
=> Add KIC + Portal warning to Kubernetes topology

app/_hub/kong-inc/openid-connect/how-to/_demonstrating-proof-of-possession.md, app/_hub/kong-inc/openid-connect/how-to/authentication/_authorization-code-flow.md, app/_hub/kong-inc/openid-connect/how-to/authentication/_client-credentials.md, app/_hub/kong-inc/openid-connect/how-to/authentication/_introspection.md, app/_hub/kong-inc/openid-connect/how-to/authentication/_jwt-access-token.md, app/_hub/kong-inc/openid-connect/how-to/authentication/_kong-oauth-token.md, app/_hub/kong-inc/openid-connect/how-to/authentication/_password-grant.md, app/_hub/kong-inc/openid-connect/how-to/authentication/_refresh-token.md, app/_hub/kong-inc/openid-connect/how-to/authentication/_session.md, app/_hub/kong-inc/openid-connect/how-to/authentication/_user-info.md, app/_hub/kong-inc/openid-connect/how-to/authorization/_acl.md, app/_hub/kong-inc/openid-connect/how-to/authorization/_claims.md, app/_hub/kong-inc/openid-connect/how-to/authorization/_consumer.md, app/_hub/kong-inc/openid-connect/how-to/client-authentication/_mtls.md
In the OIDC plugin, `client_id`, `client_secret`, and` client_auth` must be arrays. See the config schema to verify:  https://docs.konghq.com/hub/kong-inc/openid-connect/configuration/
Fixes #8343 
Preview link:
=> Fix: OIDC plugin params listed as strings instead of arrays

app/_data/docs_nav_kgo_1.5.x.yml, app/_data/kong_versions.yml, app/_src/gateway-operator/guides/konnect-entities/konnect-plugin-binding.md
Describes global `KongPluginBinding` usage.
Closes https://github.com/Kong/gateway-operator/issues/440.
Preview link: https://deploy-preview-8351--kongdocs.netlify.app/gateway-operator/unreleased/guides/konnect-entities/konnect-plugin-binding/
=> docs(kgo): add global KongPluginBinding description

api-specs/Gateway-EE/3.4/kong-ee-3.4.yaml, api-specs/Gateway-EE/3.5/kong-ee-3.5.yaml, api-specs/Gateway-EE/3.6/kong-ee-3.6.yaml, api-specs/Gateway-EE/3.7/kong-ee-3.7.yaml, api-specs/Gateway-EE/3.8/kong-ee.yaml, api-specs/Gateway-EE/3.9/kong-ee.yaml, api-specs/Gateway-EE/latest/kong-ee.yaml
Adding missing schema.
Preview link:
=> Add schema for consumer groups

.github/raise-pr-on-change.json, .github/workflows/push-oas-downstream.yaml
=> Push gateway OAS to the dev site

api-specs/Gateway-EE/3.4/kong-ee-3.4.yaml, api-specs/Gateway-EE/3.5/kong-ee-3.5.yaml, api-specs/Gateway-EE/3.6/kong-ee-3.6.yaml, api-specs/Gateway-EE/3.7/kong-ee-3.7.yaml, api-specs/Gateway-EE/3.8/kong-ee.yaml, api-specs/Gateway-EE/3.9/kong-ee.yaml, api-specs/Gateway-EE/latest/kong-ee.yaml
Update the very outdated license report. This changed in 3.4.
Fixes https://github.com/Kong/developer.konghq.com/issues/264.
Preview link:
=> Update the license report response in Admin EE spec

app/_assets/stylesheets/blockquote-notes.less, app/_src/gateway/support/index.md
Adding an announcement banner to the support policy Gateway doc. 
This is to increase visibility over a potential blog, and to warn customers before 3.10 goes out.
No conditional version tags needed here. The banner is relevant to anyone on any version.
Once 3.10 goes out, we can add this same notice to the changelog, and integrate the LTS information directly into the support policy.
https://konghq.atlassian.net/browse/DOCU-4181
Preview link: https://deploy-preview-8355--kongdocs.netlify.app/gateway/latest/support-policy/
=> Update: Gateway LTS policy

api-specs/Gateway-EE/3.6/kong-ee-3.6.yaml, api-specs/Gateway-EE/3.7/kong-ee-3.7.yaml, api-specs/Gateway-EE/3.8/kong-ee.yaml, api-specs/Gateway-EE/3.9/kong-ee.yaml, api-specs/Gateway-EE/latest/kong-ee.yaml
Fixes: https://github.com/Kong/developer.konghq.com/issues/248
=> Fix: Vault sync endpoint

jekyll-dev.yml, jekyll.yml
The Kuma docs have had a few variables added to them that we didn't have in the docs.konghq.com config files, so the variables were resolving to nothing.
Issue reported on slack.
Preview link: 
https://deploy-preview-8384--kongdocs.netlify.app/mesh/latest/introduction/install/ - Mesh packages link
https://deploy-preview-8384--kongdocs.netlify.app/mesh/latest/production/cp-deployment/multi-zone/ - `kong-mesh-global-zone-sync`
=> Fix: Add missing mesh variables

app/_src/gateway/reference/expressions-language/language-references.md
This was a copy-n-paste error, different address family will always returning `true` for `not in` operations.
=> fix(expressions-language): fix inaccurate docs description of ATC behavior

app/_data/docs_nav_mesh_2.10.x.yml, app/_data/docs_nav_mesh_2.6.x.yml, app/_data/docs_nav_mesh_2.7.x.yml, app/_data/docs_nav_mesh_2.8.x.yml, app/_data/docs_nav_mesh_2.9.x.yml
We missed one navbar element
Preview link: 
fix: https://github.com/kumahq/kuma-website/issues/2158
=> docs(mesh): fix navbar to use kong-mesh instead of kuma

app/_data/kong_versions.yml
KIC 3.4.0 is an LTS release, but the LTS label is missing: https://github.com/Kong/kubernetes-ingress-controller/blob/main/CHANGELOG.md/#340
Fixes https://github.com/Kong/docs.konghq.com/issues/8368.
Preview link:
=> Fix: label KIC 3.4 as LTS

app/_src/gateway/breaking-changes/35x.md, app/gateway/changelog.md
Vitals is supported indefinitely for existing customer that have purchased it in the past, same as Dev Portal. Adjusting the docs to reflect this.
Preview link: https://deploy-preview-8365--kongdocs.netlify.app/gateway/3.5.x/breaking-changes/
=> chore: Adjust messaging around Vitals sustaining mode

app/_src/gateway/kong-manager/auth/sessions.md
This feature will be added from the 3.4.x~LTS version.
Preview link: 
https://deploy-preview-8313--kongdocs.netlify.app/
KM-860
=> docs(gui): update the multiple session feature for Kong Manager.

app/_data/docs_nav_gateway_3.9.x.yml, app/_src/gateway/reference/reserved-entity-names.md
Created a file under the References section to display the list of reserved entities which we discourage users from using and may trigger a schema violation error if they attempt it.
This resolves [DOCU-2116](https://konghq.atlassian.net/browse/DOCU-2116).
Preview link: 
[DOCU-2116]: https://konghq.atlassian.net/browse/DOCU-2116?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Feat: Add reserved entity names to References section

app/_src/gateway/kong-plugins/queue/reference.md, app/gateway/changelog.md
We missed documenting the `concurrency_limit` queue parameter in 3.8.
Removed the link to kong.conf from the changelog; these params aren't in kong.conf, they're in plugins.
Fixes https://github.com/Kong/docs.konghq.com/issues/8291.
Preview link: https://deploy-preview-8397--kongdocs.netlify.app/gateway/latest/kong-plugins/queue/reference/
=> Fix: Add missing queue parameter to table

app/_data/docs_nav_kgo_1.4.x.yml, app/_data/docs_nav_kgo_1.5.x.yml, app/_includes/md/kgo/prerequisites.md, app/_includes/snippets/gateway-operator/install_with_helm.md, app/_src/gateway-operator/get-started/kic/create-gateway.md, app/_src/gateway-operator/get-started/kic/install.md, app/_src/gateway-operator/production/certificates/custom_ca.md
- adjust the nightly repository based on recent introduction of https://hub.docker.com/r/kong/nightly-gateway-operator (and https://hub.docker.com/r/kong/nightly-gateway-operator-oss
- add guide for customizing cluster CA
Preview link: https://deploy-preview-8386--kongdocs.netlify.app/gateway-operator/unreleased/production/certificates/custom_ca/
=> kgo: add guide for customizing cluster CA

app/_hub/kong-inc/dynatrace/overview/_index.md, app/_hub/kong-inc/opentelemetry/how-to/_dynatrace.md
Updating the description of our Dynatrace implementation to provide more context, per request.
Preview link:
=> Update the Dynatrace integration description

api-specs/Gateway-EE/3.9/kong-ee.yaml, api-specs/Gateway-EE/latest/kong-ee.yaml, api-specs/Gateway-OSS/3.9/kong-oss.yaml, api-specs/Gateway-OSS/latest/kong-oss.yaml, app/_data/kong_versions.yml, app/_plugins/generators/pages/version_data.rb, app/_src/gateway/admin-api/index_latest.md
Fixing two issues with our Gateway Admin EE and OSS specs:
1. The version number in the specs for 3.9 and latest is incorrect, both should be 3.9 but are showing 3.8. The content of the files are correct for 3.9 though, I tracked down the file histories and it just looks like the version number update was missed.
2. The insomnia buttons to the versioned specs are incorrect. Easiest solution, added a shortcode for the version from 3.4 onward that we can access via `{{page.release.versions.short}}`.
Specs are already updated in Konnect Dev Portal.
Tested the buttons, they all import the correct specs. Note that the filename format changed in 3.8, so that's why I had to version tag the URLs.
Preview link:
=> Fix versioning issues with OAS and insomnia buttons

app/_data/docs_nav_gateway_3.10.x.yml, app/_data/docs_nav_gateway_3.5.x.yml, app/_data/docs_nav_gateway_3.6.x.yml, app/_data/docs_nav_gateway_3.7.x.yml, app/_data/docs_nav_gateway_3.8.x.yml, app/_data/docs_nav_gateway_3.9.x.yml, app/_redirects
We have two contradictory copies of the vulnerability update policy for Kong Gateway. 
One was supposed to be removed in 3.4, however it was only removed from the 3.4 nav file and not from 3.5 onward. There was already a 3.5 release branch at that time, which wasn't updated and caused us to end up with duplicate policies. See https://github.com/Kong/docs.konghq.com/pull/6000
Preview link:
=> Fix: Remove old security policy

app/_hub/kong-inc/request-validator/overview/_index.md
request-validator plugin only supports json schema validator for parameters.
[FTI-5619](https://konghq.atlassian.net/browse/FTI-5619)
Preview link: 
[FTI-5619]: https://konghq.atlassian.net/browse/FTI-5619?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs(plugin/request-validator): clarify supported validators

app/konnect/gateway-manager/dedicated-cloud-gateways/transit-gateways.md
Updated steps to ensure a customer has Tgw attachment for their own VPCs also.
Preview link:
=> Fix: transit gateways

app/_hub/kong-inc/request-transformer-advanced/how-to/_index.md
Update request-transformer-advanced examples to include replace.uri
- Added examples for replace.uri using static values and capturing groups.
- Improved documentation to clarify usage.
Preview link:
=> Update request-transformer-advanced examples to include replace.uri

app/_includes/plugins/sidebar.html, spec/templates/plugin_with_versions_spec.rb
Removes the "Try In Konnect" sidebar button for plugins which don't support Konnect.
Preview link:
=> remove try-in-konnect for incompatible plugins

app/_src/gateway/support/index.md, app/_src/gateway/support/third-party.md
Gateway 3.6 reached end of full support and entered sunset support on Feb 12th.
Removing the support tabs for this version and adding an entry into the sunset support table.
https://deploy-preview-8468--kongdocs.netlify.app/gateway/latest/support-policy/#supported-versions
https://deploy-preview-8468--kongdocs.netlify.app/gateway/latest/support/third-party/
=> chore: Gateway 3.6 moves into sunset support

app/_src/mesh/features/rbac.md
Added a warning to the RBAC documentation explaining the security risks of specifying access actions without binding them to specific resource types. Included an example of a misconfigured role and a corrected version to guide users in securing their permissions.
Preview link: https://deploy-preview-8473--kongdocs.netlify.app/mesh/latest/features/rbac/#accessrole
=> docs(mesh/rbac): add warning about unbounded access actions granting full access

app/konnect/network.md
Changed the existing cluster and telemetry hostnames to `CONTROL_PLANE_DNS_PREFIX` to match feedback I got here: https://kongstrong.slack.com/archives/C04RXLGNB6K/p1740607033227059
Preview link:
=> Fix Konnect cluster and telemetry hostnames

app/_data/kong_versions.yml
Update latest KIC to https://github.com/Kong/kubernetes-ingress-controller/releases/tag/v3.4.3
Ref: https://github.com/Kong/docs.konghq.com/pull/8483
Preview link:
=> kic: update latest version to 3.4.3

api-specs/Konnect/v3/yaml/api-builder.yaml, api-specs/Konnect/v3/yaml/portal-management.yaml, api-specs/Konnect/v3/yaml/portal.yaml, app/_api/konnect/api-builder/_index.md, app/dev-portal/portals/index.md
Added required files for docs portal to list new API Builder v3, and added YAML versions of specs to potentially fix Insomnia links.
Preview link:
=> Add v3 API Builder API, insomnia fixes for other portal v3 APIs

app/deck/file/lint.md
Link to all available `deck file lint` rules
Preview link: [/deck/file/lint](https://deploy-preview-8499--kongdocs.netlify.app/deck/file/lint)
=> Add link to Vacuum to deck file lint

app/_src/mesh/features/rbac.md
Add a new subsection under AccessRoleBinding that explains how to restrict the default binding which assigns the admin role to all users in the `mesh-system:authenticated` and `mesh-system:unauthenticated` groups. This prevents unintended admin access by showing how to limit admin privileges to a specific group (using `mesh-system:admin`).
Also, update most navtabs to use codeblocks for a better appearance and remove extra blank lines from the warning message.
Preview link:
- https://deploy-preview-8484--kongdocs.netlify.app/mesh/latest/features/rbac/#restricting-the-default-accessrolebinding
- https://deploy-preview-8484--kongdocs.netlify.app/mesh/latest/features/rbac/
=> docs(mesh/rbac): add subsection to restrict default AccessRoleBinding

app/_src/gateway/support/sbom.md
This PR changes the links that previous pointed to Salesforce, so that they now point to Cloudsmith, where I have manually mirrored the SBOM data.
See also: https://github.com/Kong/kong-ee/pull/11530
Preview link: 
#_[KAG-6491]_
[KAG-6491]: https://konghq.atlassian.net/browse/KAG-6491?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(gw): SBOMs now hosted on Cloudsmith

app/_layouts/docs-v2.html
Add a banner to highlight the v3 docs
Preview link: [/konnect/dev-portal/create-dev-portal/](https://deploy-preview-8508--kongdocs.netlify.app/konnect/dev-portal/create-dev-portal/)
=> Add banner for Portal v3 beta docs

app/_assets/javascripts/tabs.js, app/_includes/snippets/install_kumactl.md, app/_includes/snippets/install_os.md, app/_includes/snippets/use_kuma_k8s.md, app/_plugins/kuma-specific/tabs/tabs.rb, app/_src/mesh/features/meshglobalratelimit.md, app/_src/mesh/features/meshopa.md
06312a73ffd05c9d54d9a9227d923cdce13e6fff refactor(plugin/tabs): simplify usage and remove useUrlFragment (kumahq/kuma-website#2216)
9c4f7f9b6a3e53f01dc120b7245d7293f7ac834d chore: fix broken datadog agent links (kumahq/kuma-website#2218)
Triggered by [action](https://github.com/Kong/docs.konghq.com/actions/runs/13715870250).
=> chore(deps): bump kumahq/kuma-website from 502e3f8f to 06312a73

app/_src/gateway/production/deployment-topologies/hybrid-mode/setup.md
`KONG_CLUSTER_CERT_KEY` was showing `cluster.crt` as the file name. It should be `cluster.key`.
Issue reported on Slack: https://kongstrong.slack.com/archives/CDSTDSG9J/p1741304592807449
Preview link:
=> Fix: cluster key in hybrid mode setup page

.github/styles/kong/dictionary.txt, app/dev-portal/portals/customization/custom-pages.md
Document the new Dev Portal reserved paths.
Preview link:
=> docs(portal): reserved paths

app/konnect/gateway-manager/dedicated-cloud-gateways/transit-gateways.md
Issue reported at [https://github.com/Kong/docs.konghq.com/issues/8296](https://github.com/Kong/docs.konghq.com/issues/8296)
Change title from "How to configure Transit Gateway" to "How to configure AWS Transit Gateway", so it clearly states this is an AWS product.
In the "Configure AWS Transit Gateway" section, replace "Create Transit Gateway" with "Create transit gateway", in lowercase, as this is the term appearing in AWS.
Preview link:
=> Rename title in transit-gateways.md

app/_includes/md/plugins-hub/log_custom_fields_by_lua.md
Update log_custom_fields_by_lua.md with note of using dots for nested fields and using backslash to escape dots.
Added an example with both dot and escaped dot to demonstrate the use case.
Preview link: 
* https://github.com/Kong/kong/pull/14324
=> Update log_custom_fields_by_lua.md with note of using dots

app/_data/docs_nav_dev-portal.yml
This page doesn't exist, and it's triggering the broken link checker: https://github.com/Kong/docs.konghq.com/actions/runs/13723604625/job/38384691884?pr=8527
Preview link:
=> Fix: remove url for non-existent page

app/dev-portal/portals/customization/custom-pages.md
List the proxy path as reserved in Portal Custom Pages.
Preview link:
=> docs(portal): add reserved path for api proxy

app/_src/kubernetes-ingress-controller/plugins/custom.md
Add the introduction of installing migration scripts in custom plugins in KIC.
fixes https://github.com/Kong/docs.konghq.com/issues/8317.
Preview link:
=> docs(kic): add introduction of migration scripts in custom plugins

.github/workflows/ci-autofix.yml, .github/workflows/linting.yml
Use kong changed-files github actions as the original upstream has been compromised and shut down. See #incident-456.
=> fix(actions): use kong changed files

app/_data/kong_versions.yml, app/_plugins/hooks/supported_version_api.rb
Adds an API that returns supported Gateway versions for use in CI
Preview link: /_api/gateway-versions.json
=> Add API for Gateway versions

app/_data/docs_nav_gateway_3.10.x.yml, app/_src/gateway/kong-manager/strengthen-security.md
This pull request adds documentation for the usage of new configuration parameters `admin_gui_csp_header` and `admin_gui_csp_header_value` in Gateway 3.10 as a guide _Strengthen Security in Kong Manager_.
KM-1003
Preview link: https://deploy-preview-8550--kongdocs.netlify.app/gateway/unreleased/kong-manager/strengthen-security/
=> feat: add docs for CSP header in GW 3.10

app/_src/gateway/production/deployment-topologies/hybrid-mode/incremental-config-sync.md
The flag to enabled incremental config sync is now renamed to `incremental_sync`. 
https://github.com/Kong/kong-ee/pull/11836
The other flag is not needed.
Preview link:
=> Update incremental config sync flags

app/_hub/kong-inc/ai-semantic-cache/overview/_index.md
Add clarification of the cache_control config and explain the behaviour if being set with common AI services.
Preview link: 
- [na] [Conditional version tags](https://docs.konghq.com/contributing/conditional-rendering/#conditionally-render-content-by-version) added, if applicable.
AG-228
=> docs(ai-semantic-cache): add note on cache control behaviour

app/_hub/kong-inc/ai-rate-limiting-advanced/how-to/_index.md
=> AI RLA: Support for multiple limits and window sizes

app/_data/docs_nav_gateway_3.10.x.yml, app/_src/gateway/plugin-development/pdk/index.md, app/_src/gateway/plugin-development/pdk/kong.client.md, app/_src/gateway/plugin-development/pdk/kong.jwe.md, app/_src/gateway/plugin-development/pdk/kong.log.md, app/_src/gateway/plugin-development/pdk/kong.response.md, app/_src/gateway/plugin-development/pdk/kong.service.request.md, app/_src/gateway/reference/cli.md
https://konghq.atlassian.net/browse/DOCU-4207
https://konghq.atlassian.net/browse/DOCU-4206
Preview link:
=> Add cli and pdk docs

app/_hub/kong-inc/dynatrace/_metadata/_index.yml
Setting `network_config_opts: All` as a temp solution to avoid the incorrect entries in this table: https://docs.konghq.com/hub/plugins/compatibility/#analytics-monitoring
Issue came up on Slack.
Preview link:
=> fix: Dynatrace deployment options

app/_src/gateway/kong-enterprise/partials.md
There was a request to add information on how to use Partials with Custom Plugins.
Preview link: 
Please take a look at the two sections: The note about the difference between CE Redis and EE Redis (at the top of the page) and the section about Custom Partials.
https://deploy-preview-8608--kongdocs.netlify.app/gateway/unreleased/kong-enterprise/partials/
=> docs(partials): add info about using a parital with custom plugin

app/_src/gateway-operator/get-started/kic/create-gateway.md, app/_src/gateway-operator/guides/autoscaling-workloads/overview.md, app/_src/gateway-operator/guides/plugin-distribution.md, app/_src/gateway-operator/guides/upgrade/data-plane/blue-green.md, app/_src/gateway-operator/topologies/dbless.md
Removing readiness grom Gateways as per https://kongstrong.slack.com/archives/CA42V003B/p1742821156530799?thread_ts=1742569562.245049&cid=CA42V003B
Preview link:
=> [KGO] chore: remove readiness probe from gateways

app/_src/gateway/support/index.md, app/_src/gateway/support/third-party.md, app/gateway/2.8.x/support-policy.md
Gateway 2.8 moves into sunset support tomorrow (march 26). Can merge then.
We hadn't updated the 2.8 non-single-sourced support policy for a while (oversight), so making the tables match the latest version.
Also removing all version tags except 3.10, since we don't want 3.10 showing on prod yet.
Preview link:
=> Chore: Move Gateway 2.8 into sunset support

app/_data/kong_versions.yml
Releasing the docs for for Gateway 3.10.
Preview link:  https://deploy-preview-8599--kongdocs.netlify.app/gateway/
* https://github.com/Kong/docs.konghq.com/milestone/66
Code freeze on all doc updates that aren't for this release.
```
make clean && make build
netlify dev
cd tools
cd broken-link-checker
node full.js --host <http://localhost:8888>
```
=> Release: Gateway 3.10

app/_hub/kong-inc/request-callout/overview/_index.md
Warn about request-callout `forward` behavior.
=> docs(plugins/request-callout): warn about `forward` behavior

app/_hub/kong-inc/mtls-auth/overview/_index.md, app/_hub/kong-inc/tls-handshake-modifier/overview/_index.md
Add note about limitation on expressions routes to the mTLS and TLS handshake modifier plugins.
https://konghq.atlassian.net/browse/FTI-6227
Preview link: 
https://deploy-preview-8611--kongdocs.netlify.app/hub/kong-inc/mtls-auth/
https://deploy-preview-8611--kongdocs.netlify.app/hub/kong-inc/tls-handshake-modifier/
=> Fix: Expressions route limitation on mTLS and TLS Handshake Modifier

app/_src/gateway/support/index.md
LTS releases get 3 years, not 1.
Preview link:
=> Fix: adjust 310 support date for LTS

app/_data/kong_versions.yml, app/_includes/md/kic/prerequisites.md, app/_src/gateway-operator/get-started/kic/create-gateway.md, app/_src/gateway-operator/guides/upgrade/data-plane/blue-green.md, app/_src/kubernetes-ingress-controller/get-started/key-authentication.md, app/_src/kubernetes-ingress-controller/upgrade/gateway.md, jekyll-dev.yml, jekyll.yml
Since we don't have a CE 3.10 version, the "latest" version is no longer defined accurately. This is going to remain mostly static, other than patch releases, so adding it as a site variable.
Preview link:
https://deploy-preview-8630--kongdocs.netlify.app/kubernetes-ingress-controller/latest/upgrade/gateway/#upgrade-kong-gateway-using-helm
https://deploy-preview-8630--kongdocs.netlify.app/gateway-operator/latest/guides/upgrade/data-plane/blue-green/ (step 6)
=> Variable for latest gateway OSS version

app/_hub/kong-inc/ai-sanitizer/how-to/_index.md, app/_hub/kong-inc/ai-sanitizer/overview/_index.md, app/_includes/footer.html
Added note to tell users to reach out to support to get access to the private AI PII Service Docker image
https://kongstrong.slack.com/archives/C06GB3KM155/p1743148798458789
Preview link:
=> Fix: Add note about private Docker image

app/_src/gateway/reference/configuration/configuration-3.10.x.md
Code phrase used a `'` instead of a backtick.
Preview link: https://deploy-preview-8642--kongdocs.netlify.app/gateway/latest/reference/configuration/#postgres-settings
=> Fix: kong.conf broken table

app/konnect/gateway-manager/configuration/config-store.md
Added missing steps from the decK tab for creating and linking the config store to the vault before referencing it in the decK YAML config file.
This was creating confusion for customers wanting to use decK with the Konnect Config Store.
Preview link:
=> Fix: Update config-store.md for decK tab steps

app/_data/docs_nav_kgo_1.5.x.yml, app/_includes/md/kgo/konnect-cloud-gateways-provider-account.md, app/_includes/md/kgo/konnect-entities-prerequisites.md, app/_src/gateway-operator/guides/konnect-entities/cloud-gateways-data-plane-group-configuration.md, app/_src/gateway-operator/guides/konnect-entities/cloud-gateways-network.md
Closes #8466
Preview link: https://deploy-preview-8576--kongdocs.netlify.app/gateway-operator/unreleased/guides/konnect-entities/cloud-gateways-data-plane-group-configuration/
1. Install CRDs
```
kustomize build github.com/kong/kubernetes-configuration/config/crd/gateway-operator\?ref=v1.2.0 | kubectl apply --server-side -f -
```
1. Checkout https://github.com/Kong/charts, at `kgo-1.5-cluster-role-permissions` branch ( if it's missing or already merged, then use `main`)
1. Use the following `values.yaml` ( put it into the checked out `charts` repo)
```
fullnameOverride: gateway-operator
image:
repository: kong/gateway-operator-oss
tag: "1.5"
effectiveSemver: "1.5.0"
livenessProbe:
initialDelaySeconds: 1
periodSeconds: 1
customEnv:
KONNECT_SDK_HTTP_DUMP_REQUEST: "true" …
```
=> kgo: add KGO 1.5 Cloud Gateways Data Plane Group Configuration guide

app/_hub/kong-inc/request-callout/overview/_index.md
- Fixed broken markdown link from `templates](/hub/...)` to `[templates](/hub/...)`
Preview link:
=> fix(docs): Add missing bracket in URL link

app/_plugins/generators/plugin_single_source/plugin/page_data.rb
=> Fix version dropdown in plugin pages

app/_src/mesh/features/rbac.md
Since 2.6 the AccessRoleBinding looks the same for Global and Zone because we introduced applying policies on the zone.
Preview link:
=> fix(mesh): adjust outdated fragment about AccessRoleBinding for versions higher than 2.5

app/konnect/org-management/system-accounts.md
Fix system account token creation process
- Add required authentication header with bearer token
- Include proper request body in the API call
- Set correct content-type header
ref: https://docs.konghq.com/konnect/api/identity-management/latest/#/operations/post-system-accounts-id-access-tokens
Preview link:
=> Fix: Missing Auth Headers & Request Body in Token Creation API Call

app/_src/kubernetes-ingress-controller/reference/version-compatibility.md
ref: https://kongstrong.slack.com/archives/CA42V003B/p1743832759854869
Preview link: https://deploy-preview-8676--kongdocs.netlify.app/kubernetes-ingress-controller/latest/reference/version-compatibility/#gateway-api
=> chore(kic): fix KIC vs Gateway API compatibility table

app/_includes/md/about-plugins.md
docs(plugin): only one instance of a plugin is executed for the current request
The multiple instances of the same plugin are active for the current request context, the very first instance in the order of precedence is executed, and the rest are abandoned.
https://konghq.atlassian.net/browse/FTI-6582
Preview link:
=> docs(plugin): only one plugin instance is executed for the current request

app/_src/mesh/features/kds-auth.md
This feature was removed in 2.10.x
Preview link:
=> docs(mesh): don't display feature that was removed

app/_hub/kong-inc/ai-rate-limiting-advanced/_changelog.md, app/_src/gateway/breaking-changes/39x.md
A note is added to describe how to transform a deck yaml config that is exported from a previous version to the latest version where huggingface is supported as the llm_providers in ai-rate-limiting-advanced plugin
Preview link:
=> Added a note in changelog for ai-rate-limiting-advanced plugin

app/_src/gateway/breaking-changes/39x.md
Fix Gateway 3.9 breaking changes page. `{{site.base_gateway}}` doesn't render in page front matter.
Related page: https://docs.konghq.com/gateway/latest/breaking-changes/39x/
3.10's page shows:
Preview link:
=> chore: fix Gateway breaking changes changelog for 3.9

app/_src/gateway/kong-enterprise/workspaces/index.md
There is no limitation on having services or routes with the same routing rules in the same workspace.
See Slack for background: https://kongstrong.slack.com/archives/C03CTMSHP6C/p1744188119373439
Preview link:
=> Fix incorrect description of routing conflict rules

app/_data/kong_versions.yml, app/gateway/2.8.x/reference/cli.md, app/gateway/changelog.md
Changelog and version bump for gateway 2.8.4.14
Preview link:
=> Release: Gateway 2.8.4.14

app/_hub/kong-inc/ai-rag-injector/how-to/_index.md
An approach to update the content of ai-rag-injector plugin for Kong instances in hybrid mode or Konnect mode.
Preview link:
=> Updated ai-rag-injector docs

app/konnect/compatibility.md
Added 3.10 to Konnect compatibility table
https://kongstrong.slack.com/archives/CDSTDSG9J/p1744771182817609
Preview link: https://deploy-preview-8715--kongdocs.netlify.app/konnect/compatibility/
=> fix: Add 3.10 to Konnect compatibility table

app/_data/kong_versions.yml
Update KIC versions to include:
- https://github.com/Kong/kubernetes-ingress-controller/releases/tag/v3.4.4
- https://github.com/Kong/kubernetes-ingress-controller/releases/tag/v2.12.8
Preview link:
=> chore(kic): update versions

app/_data/docs_nav_konnect.yml, app/konnect/gateway-manager/dedicated-cloud-gateways/custom-plugins.md, app/konnect/gateway-manager/dedicated-cloud-gateways/index.md, app/konnect/gateway-manager/plugins/add-custom-plugin.md, app/konnect/gateway-manager/plugins/index.md
Docs for custom plugin streaming on DCGWs.
Preview link: https://deploy-preview-8556--kongdocs.netlify.app/konnect/gateway-manager/dedicated-cloud-gateways/custom-plugins/
=> Feat: Custom plugin streaming

app/_hub/kong-inc/confluent-consume/overview/_index.md, app/_hub/kong-inc/confluent/overview/_index.md, app/_hub/kong-inc/kafka-consume/overview/_index.md, app/_hub/kong-inc/kafka-log/overview/_index.md, app/_hub/kong-inc/kafka-upstream/overview/_index.md
Kafka 4.0 was released last month and users are running into problems because we don't explicitly say that we don't support it.
https://konghq.atlassian.net/browse/KAG-6911
Preview link:
=> chore: Mention that we don't support kafka 4.0

app/_hub/kong-inc/rate-limiting-advanced/overview/_index.md, app/_hub/kong-inc/rate-limiting/overview/_index.md
Added a table and info about window size and sync rate interactions in RLA, and what strategy they should use.
Preview link: https://deploy-preview-8732--kongdocs.netlify.app/hub/kong-inc/rate-limiting-advanced/#every-transaction-counts
=> update: Warn users about very high sync rates in RLA

app/_includes/md/konnect/generic-sso.md
Removed the note about only mapping a team 1:1 since users can and do use one to multiple mapping.
https://kongstrong.slack.com/archives/CDSTDSG9J/p1745342320616519
Preview link:
=> fix: Remove note about 1:1 Konnect team mapping

app/_hub/kong-inc/ai-azure-content-safety/overview/_index.md
This PR fixes two incorrect links pointing to AI prompt decorator in the Azure content safety main doc.
Preview link:
=> fix: Incorrect links in azure content safety docs

.github/styles/kong/dictionary.txt, app/_data/docs_nav_kgo_1.6.x.yml, app/_src/gateway-operator/guides/hardening/control-plane-watch-namespaces.md
- adds new section under guides: `/guides/hardening/control-plane-watch-namespaces/`
- `reference/cli-arguments/1.5.x` and `reference/custom-resources/1.5.x` in `app/_data/docs_nav_kgo_1.6.x.yml` will be updated separately for the 1.6 release
Closes: https://github.com/Kong/gateway-operator/issues/1501
Preview link: https://deploy-preview-8741--kongdocs.netlify.app/gateway-operator/unreleased/guides/hardening/control-plane-watch-namespaces/
=> feat(kgo): add watchNamespaces docs for KGO 1.6

app/_src/gateway-operator/get-started/kic/create-gateway-konnect-crds.md
CE version used in https://docs.konghq.com/gateway-operator/latest/get-started/kic/create-gateway/#gatewayconfiguration renders to an empty string.
Most likely due to usage of `{{ site.data.kong_latest_gateway.ce-version }}`.
This PR fixes it by using `{{site.latest_gateway_oss_version}}` instead.
Preview link: https://deploy-preview-8755--kongdocs.netlify.app/gateway-operator/latest/get-started/kic/create-gateway/#gatewayconfiguration (On Prem tab)
=> chore(kgo): fix latest Kong CE version variable

app/gateway/changelog.md
Issue raised on Slack. We're missing these changelog entries in 3.10.0.0: https://github.com/Kong/kong-ee/pull/11844/files
Preview link:
=> Fix: add missing Kong Manager changelog entries

app/_plugins/hooks/dev_site_link.rb, redirects.yaml
Fixes some redirects and prevent the platform from appending the dev site's url to full urls (konnect release notes)
Fixes https://github.com/Kong/developer.konghq.com/issues/1528
Preview link:
=> Fix redirects

app/_src/kubernetes-ingress-controller/guides/services/tls.md
Fix example command in the KIC guide for using TLS termination to configure SNI correctly.
Resolves https://github.com/Kong/kubernetes-ingress-controller/issues/7376.
Preview link: 
https://deploy-preview-8783--kongdocs.netlify.app/kubernetes-ingress-controller/latest/guides/services/tls/#tls-termination
=> kic: Fix example command for tls termination

app/konnect/centralized-consumer-management.md
The central consumers doc had a link to the key auth config portion, but users thought a regular key auth setup would work. I added the key auth step directly in and made it clear that this is a specific setup that central consumers require.
https://kongstrong.slack.com/archives/CA42V003B/p1747747053933969
Preview link: https://deploy-preview-8806--kongdocs.netlify.app/konnect/centralized-consumer-management/#create-consumers-and-realms
=> fix: Add key auth step directly in central consumers doc

app/_src/mesh/features/meshopa.md
We have updated MeshOPA policy in Kong Mesh in 2.11.x this aligns docs with current functionality 
Preview link:
=> update MeshOPA targetRef support matrix and fix outdated examples

app/konnect/dev-portal/audit-logging/index.md
The dev portal audit logging page says it links to the dev portal audit logs API, but there is no such thing. There is a Konnect audit logs API, which you can use for both Konnect platform and Dev Portal.
reported on slack: https://kongstrong.slack.com/archives/CDSTDSG9J/p1747335494900349
=> Fix link name to audit logs api

app/_data/docs_nav_mesh_2.12.x.yml
- Update `inherit.nav` path to point to the correct 2.12.x navigation file
- Remove trailing space from MeshOPA text entry
Preview link:
=> fix(mesh): fix nav reference in 2.12.x mesh docs

app/gateway/changelog.md, redirects.yaml
Added a redirect for the KM basic auth how to I just migrated, fixed the release dates for 3.10.0.2 and 3.4.3.19 since I mixed those up in #8829 
Preview link: 
- https://deploy-preview-8846--kongdocs.netlify.app/gateway/changelog/ (just the date)
- https://deploy-preview-8846--kongdocs.netlify.app/gateway/changelog/#34319 (just the date)
- https://deploy-preview-8846--kongdocs.netlify.app/gateway/latest/kong-manager/auth/basic/#main (test redirect in banner)
=> fix: Add KM basic auth redirect, fix the changelog dates

app/_headers, app/_redirects, netlify/functions/mesh_latest_version.js
Add a netlify function that fetches the latest mesh version from the dev site and returns it
The redirect was causing a CORS issue because the allow-control-origin weren't passed in the 301 response
With this change there's no longer a redirect, and the site should return a 200 response with the right headers + body.
Preview link:
=> Add a netlify function that fetches the latest mesh version from the dev
